### ISSUE TITLE
Returning address of local variable.

### ISSUE THREAD

**Issue by hjmjohnson** [Slicer/Slicer#4729]
This seems like a real bug that will result in accessing a memory location that could be reclaimed for some other use.

```
[105/484] Building CXX object Libs/MRML/Core/CMakeFiles/MRMLCore.dir/vtkMRMLScene.cxx.o
Slicer/Libs/MRML/Core/vtkMRMLScene.cxx:3510:11: warning: returning address of local temporary object [-Wreturn-stack-address]
  return (this->GetErrorMessage().c_str());
          ^~~~~~~~~~~~~~~~~~~~~~~
```

Fixing this may require changing the return value of a function.

**Comment by pieper** [comment]
[Here's the line](https://github.com/Slicer/Slicer/blob/47deb76d7556e40de4e25e585c4b24a63a153da5/Libs/MRML/Core/vtkMRMLScene.cxx#L3510) in question.  That method could just be removed.  It appears to be just a holdover from Tcl wrapping.  I agree it would be bad to use, but I doubt anyone is actually using it.
