### ISSUE TITLE
MRML Association fix breaking Windows packaging

### ISSUE THREAD

**Issue by sjh26** [Slicer/Slicer#4740]
Change introduced in: https://github.com/Slicer/Slicer/commit/ae1ac7ef6a42d2ba6a21fecaf85670f536ae43ea

CDash error:
http://slicer.cdash.org/viewBuildError.php?buildid=1856920

NSIS error log:
```
!insertmacro: end of MUI_STARTMENU_WRITE_END

WriteRegStr expects 4 parameters, got 6.

Usage: WriteRegStr rootkey subkey entry_name new_value_string

    root_key=(HKCR[32|64]|HKLM[32|64]|HKCU[32|64]|HKU|HKCC|HKDD|HKPD|SHCTX)

Error in script "D:/D/P/Slicer-0-build/Slicer-build/_CPack_Packages/win-amd64/NSIS/project.nsi" on line 721 -- aborting creation process
```

Line 721:
`WriteRegStr HKCU \"SOFTWARE\Classes\Slicer\" \"\" \"Slicer supported file\"`

@lassoan

**Comment by lassoan** [comment]
I thought I fixed this issue, but apparently not. I'll fix before the nightly build kicks in.
