### ISSUE TITLE
Missing hooks branch

### ISSUE THREAD

**Issue by Sunderlandkyl** [Slicer/Slicer#4742]
Hooks were previously retrieved from the [hooks branch](https://github.com/Slicer/SlicerGitSVNArchive/tree/hooks) in the old repository, however there is no longer any such branch.

Without the hooks, newly checked out repositories will fail pre-commit.

**Comment by jcfr** [comment]
Thanks for the report.

Corresponding branch has just been published. See https://github.com/Slicer/Slicer/tree/hooks

**Comment by Sunderlandkyl** [comment]
Thanks @jcfr!
