### ISSUE TITLE
Slicer download page is not refreshing

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4757]
Slicer download page still shows 2020-03-16 version.

Since latest stable release is very old, users rely on latest nightly builds and not having them severely impacts several of our projects.

**Comment by pieper** [comment]
@mhalle do you know how to update this?

**Comment by jcfr** [comment]
Closing. This is now working.

Revision reported for linux Preview package is 28875

![image](https://user-images.githubusercontent.com/219043/77391357-edb34380-6d6e-11ea-9d53-45e2d77872df.png)

And this corresponds to the revision computed from the git repository:

```
$ git rev-list HEAD --count
25838
```

`25838 + 3037` is `28875 ` (with `3037` corresponding to `Slicer_WC_COMMIT_COUNT_OFFSET`)
