### ISSUE TITLE
Slicer extensions are not found for latest preview releases

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4759]
Users reported they downoaded latest release from http://slicer.cdash.org/index.php?project=SlicerPreview, installed it, but no extensions were found.

**Comment by lassoan** [comment]
Probably due to using "respositoryRevision" instead of "revision". I'm investigating this now.

**Comment by lassoan** [comment]
Need to test tomorrow to confirm that the fix works well.

**Comment by jcfr** [comment]
Proposed fix makes sense and is consistent with changes introduced in https://github.com/Slicer/Slicer/commit/3814f1af649d63a1737005304b0924a03393446a

**Comment by jcfr** [comment]
Extensions are now available for download:


![image](https://user-images.githubusercontent.com/219043/77392363-1fc5a500-6d71-11ea-8441-ba7aee10cdfa.png)
