### ISSUE TITLE
misuse of vtkMRMLInteractionNode::EndPlacementEvent

### ISSUE THREAD

**Issue by anonym11** [Slicer/Slicer#4766]
https://github.com/Slicer/Slicer/blob/aaf75e2aaa70a92f16b3ea544b7a8901a98cd509/Libs/MRML/Core/vtkMRMLInteractionNode.cxx#L111-L117

## Steps to reproduce
I guess the event should be invoked based on previous interaction node.

## Expected behavior

line 111 should be 
```c++
  bool wasPlacing = (this->CurrentInteractionMode == vtkMRMLInteractionNode::Place);
```

## Environment
- Slicer version: Slicer-4.11-2020-03-25
- Operating system: Windows

**Comment by lassoan** [comment]
You are right. Could you send a pull request with the proposed change? Thank you!

**Comment by jcfr** [comment]
Good catch @anonym11 :pray: 

Ps: I edited the original issue description to directly include the relevant snippet.

**Comment by anonym11** [comment]
The proposed change is quite simple as listed in the original issue description, you can fix it quite conveniently by changing `bool wasPlacing = (mode == vtkMRMLInteractionNode::Place); ' to `bool wasPlacing = (this->CurrentInteractionMode == vtkMRMLInteractionNode::Place);'. Thanks very much.

**Comment by jcfr** [comment]
We will do. 

Are you okay if we acknowledge you in the commit message using:

```
Co-authored-by: anonym11 <fangwenz@gmail.com>
```

**Comment by anonym11** [comment]
OK. Sorry I missed your pull request, and just created a redundancy. Feel free to drop my pull request if necessary.
