### ISSUE TITLE
Move legacy Editor module to separate extension

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4772]
Move Editor module to separate extension.

**Comment by lassoan** [comment]
@jcfr could you copy the editor module (Modules\Scripted\Editor and Modules\Scripted\EditorLib ) to a separate extension with history? After that I can take care of the rest.

**Comment by jamesobutler** [comment]
Given the discussion at https://github.com/Slicer/Slicer/pull/4904#issuecomment-956351314, should this issue be tagged with the `status:wontfix` label and then be closed?
