### ISSUE TITLE
Patient names containing special characters do not appear correctly in DICOM browser

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#4778]
Patient names that contain special characters such as é or á do not appear correctly in the DICOM browser. They are replaced by a character with a question mark:
![image](https://user-images.githubusercontent.com/1325980/77742186-f9706580-700d-11ea-8d90-512bbda0fc46.png)
These patient names appear correctly in 4.10.2, so this is a regression. This may be related to my change about displayed fields. However, as the codebase was also recently updated to support UTF-8, it is surprising that this is still a problem.

## Steps to reproduce

Import patient with special characters such as é or á in the name.

## Expected behavior

Patient name should appear with the special character correctly displayed in the DICOM browser.

## Environment
- Slicer version: Slicer-4.11.0-2020-02-19
- Operating system: Windows

**Comment by pieper** [comment]
Hi @cpinter - can you test these images? https://www.dclunie.com/images/charset/index.html

**Comment by cpinter** [comment]
Here are the patient names. It does not look good.
![image](https://user-images.githubusercontent.com/1325980/77754965-3f382880-7024-11ea-982b-634d423fc4f2.png)

**Comment by lassoan** [comment]
I've tested with David's data sets when developed UTF-8 support and it worked well. I've tested again with latest preview release and it is good, too:

![image](https://user-images.githubusercontent.com/307929/77756202-1eaca600-7005-11ea-9f15-6e312b4d07b4.png)

Is it possible that you blocked/delayed Windows update on your computer? You need to be on at least "Windows 10 Version 1903 (May 2019 Update)".

Can you copy the "Operating system" line from your application log? Mine is

    [DEBUG][Qt] 27.03.2020 08:27:17 [] (unknown:0) - Operating system .........: Windows /  Personal / (Build 18363, Code Page 65001) - 64-bit

**Comment by cpinter** [comment]
Ah, great! I didn't use the very latest nightly, maybe that's why it was still a problem (I thought it contained the UTF improvements). Sorry for the noise then.

**Comment by cpinter** [comment]
I tried it with the very latest one I built from source. Just one thing that is different from @lassoan's screenshot, see the first patient
![image](https://user-images.githubusercontent.com/1325980/77757044-5a0c9c00-7028-11ea-9806-f61b057ea89c.png)
