### ISSUE TITLE
error: Failed to obtain launcher executable name !

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [Slicer/Slicer#4787]
When trying to launch Slicer, I get the following error message

```
error: Failed to obtain launcher executable name !
```

### Steps to reproduce

- install Ubuntu 18.04
- download Slicer archive from website
- extract archive
- run in command line `./Slicer`

### Expected behavior

The Slicer software should start.

### Environment
- Slicer version: Slicer-4.8, 4.10, 4.11, all lead to the same behavior 
- Operating system: Ubuntu 18.04, Linux 4.14, amd64

#4468

**Comment by pieper** [comment]
@Hugo-Trentesaux can you describe how you install the software?

**Comment by Hugo-Trentesaux** [comment]
Yes, sure:
```bash
wget https://download.slicer.org/bitstream/1023242
tar xf Slicer-4.10.tar.gz
./Slicer-4.10/Slicer
```
(I'm not on the computer right now so the file name do not match, but that's what I did)

**Comment by lassoan** [comment]
This post describes why you get this error: https://discourse.slicer.org/t/pre-build-or-locally-build-3dslicer-under-ubuntu-16-04-does-not-start-failed-to-obtain-launcher-executable-name/2322/8?u=lassoan

The specific reason might be that you are installing the application in a special folder - network folder, external drive, symlink, special character in folder name, wrong permissions, etc.

It would be great if you could compile the [application launcher](https://github.com/commontk/AppLauncher) (it is a small standalone project) in debug mode and see how this can be fixed. Potential solution is described in the linked post, but it would need to be tested on your computer.

**Comment by Hugo-Trentesaux** [comment]
Thanks for explaining me this post which I did not understand! My `/home` and my `/` are on different partitions. I moved the binary to `/opt`, which is on my `/` partition, and it started working.

I do not know where this bug could come from, but this is a workaround.

Thanks again @lassoan :smiley_cat:
