### ISSUE TITLE
Extension manager is slow

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4806]
From @rkikinis:

Operating system: Mac OS 10.15.4
Slicer version: Slicer-4.11.0-2020-04-01-macosx-amd64
Actual behavior:
Something is broken/bizarre with the extension manager. I need to click twice for the window to appear and the history tab is empty. After I install some extensions, i do not get a prompt to restart. When I close the extension manager and exit slicer, then the extension manager window pops up on its own and prompts for a restart.

See related discussion here: https://discourse.slicer.org/t/problematic-behavior-of-the-extension-manager/10986

**Comment by lassoan** [comment]
> I need to click twice for the window to appear

Maybe you just need to wait more. If your application is [not signed](https://github.com/Slicer/Slicer/issues/4724) then it may take minutes for the integrated web browser to launch. Could you try clicking only once and wait for several minutes?

> the history tab is empty

I could not reproduce this issue on Windows.

> After I install some extensions, i do not get a prompt to restart.

You may need to wait more. After the installation seems to be completed, it may take several minutes the restart button to become active.

> When I close the extension manager and exit slicer, then the extension manager window pops up on its own and prompts for a restart.

This may be the second instance of the extension manager (or just the single instance did not quit).

I find this behavior quite frustrating, too. Most likely all the problems are in the javascript and javascript/C++ communication layer (with sometimes extra slowdowns caused by the midas3 server), so probably @pieper would be the best person to debug.

**Comment by pieper** [comment]
I think this has nothing to do with javascript  : )

All the issues described by @rkikinis sound like symptoms of a slow response from the midas server.  As part of the discussion of the thread linked below I saw delays of over 8 minutes at some points and other times near instant response, which would explain why Ron's issues are not reproducible consistently.  This indicates that [this transition project](https://www.slicer.org/wiki/Documentation/Labs/ExtensionsServer) needs to get some attention (probably funding would help move it along...).

https://discourse.slicer.org/t/download-slicer-org-and-extension-catalogue-seems-slows/10835/11?u=pieper

**Comment by lassoan** [comment]
I suspect that the delays are in local javascript execution because for example after an extension download and installation is completed, you may need to wait several minutes for the "Restart" button to become active. The server should not be able to slow down anything other than the download.

Of course delays may still be side effects of slow server-side processing: there may be hundreds of background tasks, such as query list of extensions and download images, and the browser may delay other tasks until some background tasks are completed.

**Comment by pieper** [comment]
Considering that the extension manager client code hasn't changed but we know the midas server behavior has, I'd still focus on fixing the server first.  But of course we fix whatever code our debugging turns up.

**Comment by lassoan** [comment]
There are certainly transient issues with midas (long response times or complete timeouts), which may have worsened over time.

However, the issues that are reported here all started immediately when we switched to the new web browser in Qt (from WebKit to WebEngine).

**Comment by pieper** [comment]
As discussed on the slicer developer hangout, running this command in a terminal appears to be a reasonable workaround:
```
codesign --force --deep -s - /Applications/Slicer.app/Contents/MacOS/Slicer
```

**Comment by jcfr** [comment]
During the [hangout](https://discourse.slicer.org/t/2020-04-14-hangout/11107), we discovered that:
* using a dmg signed with a self-signed certificate had very little impact on the opening of the extension manager
* the process populating the restore tab was causing slowness
* the value of settings key `ExtensionCheckOnStartup/dontCheck` (variable `checkOnStartupSettingsKey`) defaulted to `false`, it should be `true`. (Note: When working on that code, we should remove the double negation)


https://github.com/Slicer/Slicer/blob/a624f9dd7b318a8e0b7d10497ebc4549dce73d9f/Base/QTGUI/qSlicerExtensionsRestoreWidget.cxx#L277-L309

**Comment by pieper** [comment]
Note also that as a workaround, restoring all extensions makes the manager load quickly again.

A good solution could be to only populate the restore extensions tab if the user asks for it explicitly.

**Comment by lassoan** [comment]
Report from @jamesobutler on the [Slicer forum](https://discourse.slicer.org/t/download-slicer-org-and-extension-catalogue-seems-slows/10835/15):

> Just wanted to report that upon trying to download the Slicer preview from the main download page today at 3:12 pm EST, that it got stuck with “Waiting for [slicer.kitware.com](http://slicer.kitware.com)…” for a long time. I ended up reloading the webpage and trying again and actually recording the time it would take to begin serving the download. It took 1 min 45 seconds to actually begin downloading. This was on my home internet which is stable and once it started downloading the ~200MB package it finished in like 4 seconds because of my download speeds. Faster response to begin serving the download would be greatly appreciated.

**Comment by jamesobutler** [comment]
Another user from the forum posted about extremely slow response from the extensions server. See https://discourse.slicer.org/t/running-slicer-on-headless-server-installing-extensions-and-more/11689/2

**Comment by lassoan** [comment]
All issues were due to actually launching two extension managers (because it took too long time for the first one to show up). It is fixed in https://github.com/lassoan/Slicer/commit/f0a7a9f9f4e6b2ea2a026b10f6b1b3899bf1fe97. It may still take a while for the extension manager to show up, which will be faster with the new extension manager server (and if that is not enough then startup time could be further improved by making querying of previously installed extensions more efficient).
