### ISSUE TITLE
tooltip in dicom browser is wrong

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#4835]
Can be replicated using study PD-1-Lung-00011 from the Anti-PD-Lung study on TCIA. 
 https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=41517500 

tested on mac, with nightly downloaded 2020-04-16

As shown in screenshot, the acquisition number doesn't match between the loadable and the tooltip.  The actual loading seems to be fine.

![image](https://user-images.githubusercontent.com/126077/79464655-58e7e280-7fc8-11ea-9e68-349da1defb2c.png)

**Comment by pieper** [comment]
Adding @rkikinis to the discussions since he's the one who discovered the issue.

**Comment by lassoan** [comment]
Option to split series by AcquisitionNumber was added 1-2 weeks ago. All the other split series fields (seriesInstanceUID, imageType, imageOrientationPatient, diffusionGradientOrientation) could not be mistaken for an integer number, so it was not a problem. Probably we should just make replacement of actual values by simple number should be disabled for AcquisitionNumber and maybe also for imageType.

**Comment by lassoan** [comment]
This should be fixed now.
