### ISSUE TITLE
 error: This CMake does not support the HTTPS protocol.  Ensure that CMake   is compiled with CMAKE_USE_OPENSSL enabled.

### ISSUE THREAD

**Issue by MurielCuiCui** [Slicer/Slicer#4839]
When I build Slicer with CMake, it come out a cmake error,
![image](https://user-images.githubusercontent.com/37406633/79525444-720a9500-8095-11ea-939b-e0720e153ecb.png)
How can I fix it,please help me

**Comment by jcfr** [comment]
It looks like your installation of CMake executable is not able to download files served over https.

From a terminal, could you try to run the following:

```
/path/to/cmake -P /path/to/Slicer/CMake/SlicerCheckCMakeHTTPS.cmake
```

where:

* `/path/to/cmake` is the full path to CMake executable 
* `/path/to/Slicer` is the path to your git checkout of Slicer sources

For example, here is the output of my workstation:

```
~/Software/cmake-3.17.0-Linux-x86_64/bin/cmake -P ~/Projects/Slicer/CMake/SlicerCheckCMakeHTTPS.cmake 
-- Checking if CMake supports https
-- Checking if CMake supports https - ok
```

**Comment by MurielCuiCui** [comment]
I download binary distribution of CMake for win64.  I try what you say,and it seems CMake doesn't support https.  Then I downloaded OpenSSL for windows, CMake again,it doesn't work either.

**Comment by jcfr** [comment]
Since CMake is statically linked against OpenSSL, there is no need to download OpenSSL libraries.

Now,  could you try the following:

1. In your local Slicer checkout, update file [CMake/SlicerCheckCMakeHTTPS.cmake](https://github.com/Slicer/Slicer/blob/master/CMake/SlicerCheckCMakeHTTPS.cmake) like this:

```diff
diff --git a/CMake/SlicerCheckCMakeHTTPS.cmake b/CMake/SlicerCheckCMakeHTTPS.cmake
index 6e28e92d55..4fe209423a 100644
--- a/CMake/SlicerCheckCMakeHTTPS.cmake
+++ b/CMake/SlicerCheckCMakeHTTPS.cmake
@@ -22,7 +22,8 @@ function(slicer_check_cmake_https)
     list(GET status 0 error_code)
     file(REMOVE ${dest})
     if(error_code)
-      message(FATAL_ERROR "error: This CMake does not support the HTTPS protocol. Ensure that CMake is compiled with CMAKE_USE_OPENSSL enabled.")
+      list(GET status 1 error_msg)
+      message(FATAL_ERROR "error: ${error_msg}")
     else()
       # Save result of check, this way there will be no need for a working network connection when reconfiguring
       set(Slicer_CMake_HTTPS_Supported TRUE CACHE INTERNAL "CMake supports HTTPS protocol")

```

2. Then,  rerun the command `/path/to/cmake -P /path/to/Slicer/CMake/SlicerCheckCMakeHTTPS.cmake`, what is the output ?

**Comment by MurielCuiCui** [comment]
I run the command you give,and here is the output 
![image](https://user-images.githubusercontent.com/37406633/79538205-74311b80-80b6-11ea-8dbf-5d7f146c17ea.png)

**Comment by jcfr** [comment]
Could you also try with replacing `https://raw.githubusercontent.com/Slicer/Slicer/master/CMakeLists.txt` with `https://google.com` ? 

Once with that information, I will pass the details to the CMake team so that we can work on a solution.

**Comment by MurielCuiCui** [comment]
Thanks a lot! It works for me !

**Comment by MurielCuiCui** [comment]
Hi, I am unable to download some packages via curl because of firewall. I use proxy to visit www.google.com ,command:  **curl -x socks5h://localhost:1080 http://www.google.com/** . Can I  add this into cmake file to run cmake in order to fetch packages from internet?

**Comment by lassoan** [comment]
Have you tried to set proxy settings in environment variables?

https://www.cyberciti.biz/faq/linux-unix-curl-command-with-proxy-username-password-http-options/

**Comment by jcfr** [comment]
It should possible to set HTTPS_PROXY and HTTP_PROXY env. variable. See http://cmake.3232098.n2.nabble.com/set-proxy-with-cmake-file-download-tp4715827p4752250.html

**Comment by MurielCuiCui** [comment]
Thanks for both of your suggestions,I try it on my computer, it seems work now.

My operating system is Windows7,I add two new enviroment variables: **http_proxy=socks5h://localhost:1080
https_proxy=socks5h://localhost:1080**
And then I open git bash,add
**export http_proxy=socks5h://localhost:1080
 export https_proxy=socks5h://localhost:1080**

then run cmake on current bash window
**cmake -G"Visual Studio 15 Win64" ../Slicer**

It works .
