### ISSUE TITLE
Add migration guide related to update of MRML Node copy API

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#4842]
Following integration of #4830 (Refactor MRML node API to support shallow and deep copy), migration guide should be updated to help extension maintainer update their code.

See https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide

Related to #3617

**Comment by lassoan** [comment]
Done: https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide/Slicer#MRML_node_copy_API_improvements
