### ISSUE TITLE
Remove SlicerPython and keep only PythonSlicer

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4843]
Python IDEs (specifically PyCharm, but potentially others) only recognize Python*.exe files as Python interpreters. To allow using Slicer's Python interpreter in these IDEs, we hade to add PythonSlicer, but kept SlicerPython around for not immediately breaking things.

This redundancy is confusing for users that we could resolve by simply removing SlicerPython for Slicer5.

**Comment by lassoan** [comment]
@jcfr @pieper do you agree that we should remove SlicerPython now? Slicer5 is a good time to make backward incompatible changes.

**Comment by pieper** [comment]
Yes.  As a softer transition maybe replace it with a simple program that prints an informative error message.

**Comment by jcfr** [comment]
After adding an entry to the migration guide and the scripting FAQ, I have no problem  with removing `SlicerPython`.

That said, having an informative error message in Slicer 5, and then removing it in Slicer 5.2 also works well.

**Comment by jcfr** [comment]
A migration guide entry was added. See https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide#Slicer_5.0:_SlicerPython_was_removed._Use_PythonSlicer_instead

**Comment by lassoan** [comment]
Thank you @jcfr for the quick fix!
