### ISSUE TITLE
Automatically orient slice views when loading a new volume

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4844]
It is one of the most common cause of confusion for users that slice view direction is not aligned to volume axes. See https://discourse.slicer.org/t/loading-cardiac-mr-images/11163/2 and many other posts. Users don't know that all they need to do is to click "Rotate to volume plane".

We should make simple things simple to do. So, we should automatically reorient slice views when a volume is loaded. @pieper @fedorov @rkikinis  do you agree?

Implementation could be simple - we could add a new option to `vtkMRMLApplicationLogic::vtkInternal::PropagateVolumeSelection(int layer, int fit)` to also reorient and enable it by default when loading a volume.

**Comment by fedorov** [comment]
I would add a setting to allow this, and it may make sense to do this by default, but there may be situations when this is not desirable (e.g., if I already have some other data loaded and my viewers are configured, and I don't want to disrupt what I already have).

**Comment by lassoan** [comment]
> I would add a setting to allow this, and it may make sense to do this by default, but there may be situations when this is not desirable (e.g., if I already have some other data loaded and my viewers are configured, and I don't want to disrupt what I already have).

I fully agree and this has been already taken care of: in Add data window, you can enable/disable "Show" option. If it is enabled (this is the default) then it already destroys your view setup (removes current foreground and background volumes from all views and only shows the new volume in the background and it resets the field of view). If we also change the slice orientation then will not make this any worse. If "Show" is disabled then the current view setup is kept intact.

**Comment by fedorov** [comment]
This sounds very good Andras, I don't have concerns to go ahead with what you propose.

**Comment by lassoan** [comment]
I've just realized that "Show" option is not yet available in DICOM module, but it would be quite easy to add to the DICOM browser options.

**Comment by pieper** [comment]
Yes, I agree too, that would eliminate much confusion.

I wonder if we should add some kind of visual indicator when showing non-patient aligned slices.  When the full slice controller is visible you see selector turn to "Reformat" but it's usually closed.  Some systems put direction letters on the sides of the images and they are, e.g. LR  when aligned but L+R- when tilted.

**Comment by lassoan** [comment]
> I wonder if we should add some kind of visual indicator when showing non-patient aligned slices. When the full slice controller is visible you see selector turn to "Reformat" but it's usually closed. Some systems put direction letters on the sides of the images and they are, e.g. LR when aligned but L+R- when tilted.

Yes, it would be certainly very good to have this. I've added a ticket to not forget about this (https://github.com/Slicer/Slicer/issues/4854).

**Comment by lassoan** [comment]
The original idea described in this issue has been implemented and further improvements are tracked in other tickets, so I'll close this issue now.
