### ISSUE TITLE
Remove remaining TCL build options

### ISSUE THREAD

**Issue by hjmjohnson** [Slicer/Slicer#4865]
## Is your feature request related to a problem? Please describe.

No problem, reduce development burden by removing code and build options that have minimal benefit to the Slicer community.

## Describe the solution you'd like

Remove all code reference by "Slicer_USE_PYTHONQT_WITH_TCL" variable.

## Describe alternatives you've considered

--- Perhaps this is really more important than it appears in the code base.  Then turn it on by default, and ensure it is tested.

## Additional context

Finding ways to minimize developer burden.

**Comment by jamesobutler** [comment]
Here is a link to a past discussion as it relates to TCL and EMSegment 
https://discourse.slicer.org/t/should-we-do-something-about-em-segmenter/4382
