### ISSUE TITLE
SQL Errors on terminal when importing DICOM files from Jupyter

### ISSUE THREAD

**Issue by davide84** [Slicer/Slicer#4871]
I'm using Slicer through Python3 in Jupyter to import DICOM files from a folder. In the terminal I get errors, although the files are imported correctly.

## Steps to reproduce

Use the script here:
https://www.slicer.org/wiki/Documentation/Nightly/ScriptRepository#How_to_load_DICOM_files_into_the_scene_from_a_folder
from a Jupyter notebook.
The DICOM files I'm importing are 512x512 CT slices.

## Expected behavior

No errors on console. They make debugging difficult, and might be a symptom of something else.

## Environment
- Slicer version: 4.10.2 r28257
- Operating system: Ubuntu 18.04.4 LTS

[terminal_output.txt](https://github.com/Slicer/Slicer/files/4502142/terminal_output.txt)

**Comment by lassoan** [comment]
Can you reproduce the problem using latest Slicer Preview Release?

**Comment by davide84** [comment]
No, I can't reproduce it - good news, thanks! This is the new, clean output:

`Initialization completed.
Switching to temporary DICOM database: /tmp/Slicer-cester/20200430_171836_TempDICOMDatabase
TagCacheDatabase adding table

"DICOM indexer has successfully inserted 326 files [0.13s]"
"DICOM indexer has successfully processed 326 files [0.17s]"
"DICOM indexer has updated display fields for 326 files [0.05s]"
('1',)
`

However, there is a new minor glitch connected to SQL. I ran version 4.11 from the notebook withouth ever having operated with Slicer from its GUI, and I got:

`Initialization completed.
Switching to temporary DICOM database: /tmp/Slicer-cester/20200430_171339_TempDICOMDatabase
TagCacheDatabase adding table

"DICOM indexer has successfully inserted 326 files [0.14s]"
"DICOM indexer has successfully processed 326 files [0.19s]"
"DICOM indexer has updated display fields for 326 files [0.06s]"
('1',)
Loading with imageIOName: GDCM
Specified database directory '/home/cester/Documents/SlicerDICOMDatabase' cannot be found
Unable to open DICOM database /home/cester/Documents/SlicerDICOMDatabase
`

The last two lines are the only difference to the "perfect" situation. It looks like the default folder for the DICOM database is not automatically created, I don't know if this is the intended behavior; once I created a folder, and specified it from the DICOM Module in Slicer, everything worked.
The thing was a bit strange, given that Slicer wrote it was switching to a temporary database.

**Comment by lassoan** [comment]
[This example](https://www.slicer.org/wiki/Documentation/Nightly/ScriptRepository#How_to_load_DICOM_files_into_the_scene_from_a_folder) creates a temporary database. Data is imported, loaded, and the database is deleted automatically and Slicer's DICOM database is set back to the default one. Maybe when there is no default database created yet, you get this warning. If this is the case then you can safely ignore this message (or you can create a default database using `DICOMUtils.openDatabase(databaseDir)`).

**Comment by davide84** [comment]
> and Slicer's DICOM database is set back to the default one.
This explains why it looks for it. All good, thanks!

Looks like I can close the issue, so I'll do it - hope it's the right way, it's my first bug report :)

**Comment by lassoan** [comment]
Great, thank you! If you have a question or you are not sure if some behavior is a bug or intentional then the best is to post it on the Slicer forum (discourse.slicer.org), where other community members can help/join the discussions.
