### ISSUE TITLE
MRI volume is loaded as several separate small volumes

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4872]
MRI images are loaded incorrectly (as many separate small volumes) instead of a single volume due to a change in the DICOM module yesterday - see details here: https://github.com/Slicer/Slicer/pull/4860

**Comment by pieper** [comment]
Which MRI volumes?  It doesn't happen for the ones I spot-checked.

As a general fix, maybe we should try limiting to load just subseries where [Acquisition Number](https://dicom.innolitics.com/ciods/mr-image/general-image/00200012) is different.

**Comment by lassoan** [comment]
For some reason, acquisition number _is_ often different within the same series for some reason. I really think we need to check spatial integrity and if it seems that the entire series is one 3D volume (no overlaps between slices) then it should not be split by default.

**Comment by pieper** [comment]
I guess we could only split automatically if there's a geometry warning, we already have that calculation.

**Comment by lassoan** [comment]
That's a good idea! If there is warning without splitting and there is no warning with splitting then it makes sense to split by default.

**Comment by pieper** [comment]
👍 I'm on it.

**Comment by lassoan** [comment]
This should be fixed now.
