### ISSUE TITLE
OpenSSL build warnings -Wnonportable-include-path with Mac 10.15 XCode 11

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#4875]
Issue initially reported by @hjmjohnson in #4875

Warning like the following are reported on macOS 10.15 with XCode 11:

```
In file included from /Users/johnsonhj/src/Slicer-build/curl/lib/urldata.h:79:
Slicer-build/OpenSSL/include/openssl/pem.h:62:11: warning: non-portable path to file '<OpenSSL/e_os2.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
          ^~~~~~~~~~~~~~~~~
          <OpenSSL/e_os2.h>
```

## Steps to reproduce

Build Slicer with default option

## Expected behavior

No warning should be reported

## Environment
- Reproducible building Slicer https://github.com/Slicer/Slicer/commit/4dd0e20872114c761435c05e42dc3cede2da880d
- on Mac 10.15 XCode 11

**Comment by jcfr** [comment]
##  Summary

The includes are in the expected location but it turns out clang is incorrectly following symlinks.

See https://openradar.appspot.com/radar?id=6091887509241856

## Details

It looks like the path is correct, the issue is that the file `e_os2.h` is found in two places:

```
cd /home/jcfr/Projects/Slicer-Release
find . | ack e_os2.h
./OpenSSL/e_os2.h
./OpenSSL/include/openssl/e_os2.h
```

Then, I looked at the compile command to build one of the object file including `urldata.h` (which itself includes `pem.h`, itself including `openssl/e_os2.h`):

Note: I replace space by a newline

```
cd
/home/jcfr/Projects/Slicer-Release/curl-build/lib
&&
/usr/bin/cc
-DBUILDING_LIBCURL
-DHAVE_CONFIG_H
-I/home/jcfr/Projects/Slicer-Release/curl-build/include/curl
-I/home/jcfr/Projects/Slicer-Release/curl/include
-I/home/jcfr/Projects/Slicer-Release/curl-build/lib/../include
-I/home/jcfr/Projects/Slicer-Release/curl/lib/..
-I/home/jcfr/Projects/Slicer-Release/curl/lib/../include
-I/home/jcfr/Projects/Slicer-Release/curl-build/lib/..
-I/home/jcfr/Projects/Slicer-Release/curl/lib
-I/home/jcfr/Projects/Slicer-Release/curl-build/lib
-I/home/jcfr/Projects/Slicer-Release/zlib-install/include
-I/home/jcfr/Projects/Slicer-Release/OpenSSL/include

-fPIC
-O3
-DNDEBUG


-D_BSD_SOURCE
-o
CMakeFiles/libcurl.dir/cookie.c.o


-c
/home/jcfr/Projects/Slicer-Release/curl/lib/cookie.c
```

The warning you see would make sense if `/home/jcfr/Projects/Slicer-Release/` would be listed as well.

Then, digging a little further ... it turns out that the files in `include/openssl` are symlinks and I think this is what is causing the warnings:

```
ls -alsh openssl/
total 8.0K
4.0K drwxrwxr-x 2 jcfr jcfr 4.0K Mar 31 18:24 .
4.0K drwxr-xr-x 3 jcfr jcfr 4.0K Mar 31 18:24 ..
   0 lrwxrwxrwx 1 jcfr jcfr   22 Mar 31 18:24 aes.h -> ../../crypto/aes/aes.h
   0 lrwxrwxrwx 1 jcfr jcfr   24 Mar 31 18:24 asn1.h -> ../../crypto/asn1/asn1.h
   0 lrwxrwxrwx 1 jcfr jcfr   28 Mar 31 18:24 asn1_mac.h -> ../../crypto/asn1/asn1_mac.h
   0 lrwxrwxrwx 1 jcfr jcfr   25 Mar 31 18:24 asn1t.h -> ../../crypto/asn1/asn1t.h
   0 lrwxrwxrwx 1 jcfr jcfr   22 Mar 31 18:24 bio.h -> ../../crypto/bio/bio.h
   0 lrwxrwxrwx 1 jcfr jcfr   26 Mar 31 18:24 blowfish.h -> ../../crypto/bf/blowfish.h
   0 lrwxrwxrwx 1 jcfr jcfr   20 Mar 31 18:24 bn.h -> ../../crypto/bn/bn.h
   [...]
   0 lrwxrwxrwx 1 jcfr jcfr   24 Mar 31 18:24 x509.h -> ../../crypto/x509/x509.h
   0 lrwxrwxrwx 1 jcfr jcfr   28 Mar 31 18:24 x509v3.h -> ../../crypto/x509v3/x509v3.h
   0 lrwxrwxrwx 1 jcfr jcfr   28 Mar 31 18:24 x509_vfy.h -> ../../crypto/x509/x509_vfy.h
```

**Comment by hjmjohnson** [comment]
superceeded buy #4876

**Comment by hjmjohnson** [comment]
JC:  The problem is aliasing on a mandatory case insensitive file system.


The following fixes the problem nicely as well:  
-    set(EP_SOURCE_DIR ${CMAKE_BINARY_DIR}/${proj})
+    set(EP_SOURCE_DIR ${CMAKE_BINARY_DIR}/${proj}-${OPENSSL_DOWNLOAD_VERSION})
 
The directory name either needs to be "openssl" for the root SOURCE directory, or something that is not a case instensive version of that.    If we were to get the slicer root build tree out of the path, that might also work.

**Comment by hjmjohnson** [comment]
@jcfr I hate case insensitive file systems.  But some adobe products don't work on case sensitive systems, and some older university programs (that were windows only during development) break on case sensitive file systems.

**Comment by jcfr** [comment]
Thanks for testing, I have a fix on the way.
