### ISSUE TITLE
Display color bar using displayable manager

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4891]
Color bars in slice and 3D views are currently not handled by displayable managers and not managed by appropriate modules.

All color bars should be managed by one module (probably Colors module) and their parameter should be stored in MRML nodes (probably display node should contain a flag that would control visibility of the color bar).

**Comment by MichaelColonel** [comment]
I'm trying to implement basics of the basics, and i have questions how to do some general elements.

I'm not quite understand how to communicate with display manager of scalar bar, by means of MRMLNode or MRMLDisplayNode? For example parameters such as: make scalar bar visible, title font size, scalar bar size.

**Comment by MichaelColonel** [comment]
A question about color bar representation on 3D view.

[vtkMRMLScalarBarDisplayableManager](http://apidocs.slicer.org/master/classvtkMRMLScalarBarDisplayableManager.html) is responsible only for 2D slices because it inherits [vtkMRMLAbstractSliceViewDisplayableManager](http://apidocs.slicer.org/master/classvtkMRMLAbstractSliceViewDisplayableManager.html). What displayable manager can i use to show a color bar in 3D view, or should i create a new displayable manager for that purpose?

**Comment by lassoan** [comment]
Since the scalar bar will behave very similarly in slice and 3D views it would make sense to have a single displayable manager class, using vtkMRMLAbstractDisplayableManager as base class.  You can use vtkMRMLRulerDisplayableManager or vtkMRMLOrientationMarkerDisplayableManager as examples. I don't really like the "scalar bar" name, so the new class name could be vtkMRMLColorBarDisplayableManager.

You can leave the current vtkMRMLScalarBarDisplayableManager class as is for now, we can later rename it to vtkMRMLWindowLevelDisplayableManager to avoid confusion between scalar bar/color bar.

**Comment by lassoan** [comment]
> I'm not quite understand how to communicate with display manager of scalar bar, by means of MRMLNode or MRMLDisplayNode? For example parameters such as: make scalar bar visible, title font size, scalar bar size.

Displayable managers typically render display nodes: one display node is mapped to one widget (or if no interactivity needed then to just a plain VTK actor). The displayable manager observes display nodes and if it finds that the display node is the right type and displayable in the current view then it creates a widget/actor and adds it to the renderer.

For color nodes, we want to have the option to display color bar for a model, volume, etc. For this, we could add a "ColorBarVisibility" bool property (and other properties as needed, for example for position and size of the color bar within a view) to vtkMRMLDisplayNode.

**Comment by MichaelColonel** [comment]
Here is my bare minimum for testing of display node and displayable manager.

vtkMRMLColorBarDisplayNode: [source](https://github.com/MichaelColonel/Slicer/blob/colorbar-dm/Libs/MRML/Core/vtkMRMLColorBarDisplayNode.cxx) and [header](https://github.com/MichaelColonel/Slicer/blob/colorbar-dm/Libs/MRML/Core/vtkMRMLColorBarDisplayNode.h)

vtkMRMLColorBarDisplayableMnager: [source](https://github.com/MichaelColonel/Slicer/blob/colorbar-dm/Libs/MRML/DisplayableManager/vtkMRMLColorBarDisplayableManager.h) (header)[https://github.com/MichaelColonel/Slicer/blob/colorbar-dm/Libs/MRML/DisplayableManager/vtkMRMLColorBarDisplayableManager.cxx]

Display manager added via Colors module: https://github.com/MichaelColonel/Slicer/blob/colorbar-dm/Modules/Loadable/Colors/qSlicerColorsModule.cxx#L89-L93

Another couple of questions are about implementation of the basics:
1. What scalar bar actor is better to use in final version? I use default vtkScalarBarActor.
2. If i want to update displayable manager every time when ColorBarDisplayNode is modified, where should i call this->RequestRender() in displayable manager? Now i managed to update displayable manager via GUI when slice view or 3D view is updated (slice is changed).

```
For example
//---------------------------------------------------------------------------
void vtkMRMLColorBarDisplayableManager::ProcessMRMLNodesEvents(vtkObject *caller, unsigned long event, void *callData)
{
//  vtkWarningMacro("ProcessMRMLNodesEvents: process color bar node events");

  this->Superclass::ProcessMRMLNodesEvents(caller, event, callData);
  switch(event)
  {
  case vtkCommand::ModifiedEvent:
    {
      vtkMRMLColorBarDisplayNode* cbNode = vtkMRMLColorBarDisplayNode::SafeDownCast(caller);
      if (cbNode)
      {
        this->Internal->ColorBarDisplayNode = cbNode;
        // display node is modified, update color bar
        this->RequestRender();
      }
    }
    break;
  default:
    break;
  }
}
```

**Comment by MichaelColonel** [comment]
With scalar bars via displayable manager i have got bar always on top, but i have tested with created markup nodes, not loaded from file.

![image](https://user-images.githubusercontent.com/3785912/133731796-a20ec99c-7da4-427a-83ce-3b6dc71dd810.png)

**Comment by jamesobutler** [comment]
@lassoan Should this issue be considered closed by https://github.com/Slicer/Slicer/commit/d36e96bd544db2489d624c85727194cde6da7484? #6111 was created to document further improvements to the color bar.

**Comment by lassoan** [comment]
Yes, this is now resolved. Color legend is displayed using displayable manager. It uses a separate layer, so it is consistently displayed above markups, regardless in what order they are added to the scene.
