### ISSUE TITLE
ModelMaker output orientation is not consistent with orientation of input

### ISSUE THREAD

**Issue by JEHoctor** [Slicer/Slicer#4894]
Model maker output is rotated 180° about the Superior-Inferior axis with respect to the input. The following image shows a slice of a correctly oriented LabelMapVolume in the same 3D space as the incorrectly oriented surface model produced by ModelMaker.

![Screenshot_3](https://user-images.githubusercontent.com/28733243/80316181-3759d880-87ca-11ea-926b-3deb73015caf.png)

## Steps to reproduce

When reproducing using either the manual steps or the python script, one must first go to Edit -> Application Settings -> Modules, and ensure that "Prefer Executable CLIs" **is** checked. Then restart Slicer.

### Manual steps

1. Load a segmentation into the scene as a label map volume.
2. Open ModelMaker and select your segmentation next to "Input Volume".
3. Next to "Models" select "Create new ModelHierarchy".
4. Press "Apply".

### Python script

I don't yet have a working Python script to trigger this bug.

## Expected behavior

The coordinate system of the output should be the same as that of the input. If the input LabelMapVolume is oriented with anatomical features aligned to Slicer's coordinate system, then the output should be aligned too.

## Environment
- Slicer version: Slicer-4.11.0-2020-04-19
- Operating system: Ubuntu 18.04.4 LTS and Mac OS X 10.14.6

**Comment by lassoan** [comment]
That's a regression due to recent default LPS/RAS model coordinate system change. I'll fix this but in the meantime you can use Segmentations module to convert labelmap->segmentation->model.

**Comment by jcfr** [comment]
@JEHoctor  Thanks for the detailed report :pray:
