### ISSUE TITLE
AttributeError: module 'slicer' has no attribute 'vtkMRMLSegmentEditorNode'

### ISSUE THREAD

**Issue by quabug** [Slicer/Slicer#4897]
```Switch to module:  "SegmentEditor"
Traceback (most recent call last):
  File "/Users/quabug/proj/slicer/cmake-build-debug/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/SegmentEditor.py", line 130, in enter
    self.selectParameterNode()
  File "/Users/quabug/proj/slicer/cmake-build-debug/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/SegmentEditor.py", line 86, in selectParameterNode
    segmentEditorNode = slicer.vtkMRMLSegmentEditorNode()
AttributeError: module 'slicer' has no attribute 'vtkMRMLSegmentEditorNode'
```

## Steps to reproduce
1. Compile from source
2. Launch
3. Switch to "SegmentEditor"
<img width="751" alt="image" src="https://user-images.githubusercontent.com/683655/80615487-511d4900-8a72-11ea-821f-1a1dfda6a913.png">

## Expected behavior
<img width="554" alt="image" src="https://user-images.githubusercontent.com/683655/80615636-81fd7e00-8a72-11ea-8ae0-347976e00f85.png">

## Environment
- Slicer version: 4.11.0-2020-04-29 r29021 / 2389c29
- Operating system: Mac 10.15

**Comment by lassoan** [comment]
See my answer in the discourse topic that you created. If you prefer to discuss this here then please post this URL there.
