### ISSUE TITLE
Slicer cannot be compiled if Python debug library is present

### ISSUE THREAD

**Issue by dzenanz** [Slicer/Slicer#4898]
In VTK's configuration, `PYTHON_DEBUG_LIBRARY` picks up value `C:/Python36-x64/libs/python36_d.lib` which interferes with some subsequent steps. Other Python-related stuff points to Slicer's version of Python, e.g. `PYTHON_LIBRARY`=`M:/Dev/Slicer-vs15/python-install/libs/python36.lib`

## Steps to reproduce

1. Select to also install debug library when installing Python.
1. Build Slicer (I don't know whether `CMAKE_CONFIGURATION_TYPES` set to `Debug` is important)

## Expected behavior

Build finishes with 0 errors.

## Environment
- Slicer version: 06e32736660fc54592b5f98fca34dd2870a9647c
- Operating system: Windows 10 version 1909
- Visual Studio 2019 with MSVC toolset v140

Key part of configure output in an incremental build:
```text
Setting C++ standard
Setting C++ standard - C++11
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
Configuring Slicer organization domain [www.na-mic.org]
Configuring Slicer organization name [NA-MIC]
Configuring Slicer default home module [Welcome]
Configuring Slicer default favorite modules [Data, Volumes, Models, Transforms, Markups, SegmentEditor]
Configuring Slicer text of disclaimer at startup [Thank you for using %1!

This software is not intended for clinical use.]
Configuring Slicer requires admin account [OFF]
Configuring Slicer install root [$LOCALAPPDATA/NA-MIC]
Configuring Slicer release type [Experimental]
Configuring Slicer version [4.11.0-2020-04-29]
Configuring Slicer revision [29021]
Configuring VTK
  Slicer_VTK_RENDERING_BACKEND is OpenGL2
  Slicer_VTK_SMP_IMPLEMENTATION_TYPE is TBB
  Slicer_VTK_VERSION_MAJOR is 8
Configuring Slicer with Qt 5.10.0 (using modules: Core, Widgets, Multimedia, Network, OpenGL, PrintSupport, UiTools, Xml, XmlPatterns, Svg, Sql, WebEngine, WebEngineWidgets, WebChannel, Script, Test, )
Setting QT_PLUGINS_DIR: C:/Dev/Qt/5.10.0/msvc2015_64/plugins
Setting QT_BINARY_DIR: C:/Dev/Qt/5.10.0/msvc2015_64/bin
Setting ExternalData_OBJECT_STORES to 'M:/Dev/Slicer-vs15/Slicer-build/ExternalData/Objects'
Configuring Slicer for [win-amd64]
CMake Error at M:/Dev/Slicer-vs15/VTK/CMake/FindPythonLibs.cmake:126 (get_filename_component):
  get_filename_component unknown component
  M:/Dev/Slicer-vs15/python-install/libs/python36.lib
Call Stack (most recent call first):
  M:/Dev/Slicer-vs15/CTK/Utilities/CMake/FindPythonQt.cmake:8 (find_package)
  C:/Program Files/CMake/share/cmake-3.17/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  M:/Dev/Slicer-vs15/CTK-build/CTKConfig.cmake:185 (find_dependency)
  CMakeLists.txt:809 (find_package)

...

CMake Warning (dev) at M:/Dev/Slicer-vs15/vtkAddon/CMake/vtkMacroKitPythonWrap.cmake:242 (target_link_libraries):
  Link library type specifier "optimized" is followed by specifier
  "optimized" instead of a library name.  The first specifier will be
  ignored.
Call Stack (most recent call first):
  M:/Dev/Slicer-vs15/vtkAddon/CMakeLists.txt:206 (vtkMacroKitPythonWrap)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by lassoan** [comment]
We recently renamed Slicer's Python interpreter from SlicerPython to PythonSlicer and probably you haven't reconfigured the project completely since then. A clean build should resolve the issue. Reopen if you experience any problems on build that you do from scratch.

**Comment by dzenanz** [comment]
I did a clean build of e33439f950cca5a63976d249851eac6f52bc2530 overnight, and the same problem occurs. SimpleITK and VTK run into the problem. The complete build log is attached: [Output-Build.txt](https://github.com/Slicer/Slicer/files/4558841/Output-Build.txt)

**Comment by jamesobutler** [comment]
My suspicion is that the important part to replicate this issue will be using CMake 3.17

**Comment by lassoan** [comment]
Normally debug-mode Python is not used anywhere. Even if your application is built in debug mode, you would still use release-mode Python.

I have these in my VTK CMakeCache.txt file:

```
//Path to a library.
PYTHON_DEBUG_LIBRARY:FILEPATH=PYTHON_DEBUG_LIBRARY-NOTFOUND
//Initial cache
PYTHON_EXECUTABLE:PATH=C:/D/S4D/python-install/bin/SlicerPython.exe
//Initial cache
PYTHON_INCLUDE_DIR:PATH=C:/D/S4D/python-install/include
//Initial cache
PYTHON_LIBRARY:FILEPATH=C:/D/S4D/python-install/libs/python36.lib
```

Can you temporarily move away `C:/Python36-x64/libs` folder to somewhere to make sure it cannot be found during the build process and see if it indeed fixes the problem?

**Comment by dzenanz** [comment]
This is what I had in VTK's cache:
```text
//Path to a library.
PYTHON_DEBUG_LIBRARY:FILEPATH=C:/Python36-x64/libs/python36_d.lib
//Initial cache
PYTHON_EXECUTABLE:PATH=M:/Dev/Slicer-vs15/python-install/bin/PythonSlicer.exe
//Initial cache
PYTHON_INCLUDE_DIR:PATH=M:/Dev/Slicer-vs15/python-install/include
//Initial cache
PYTHON_LIBRARY:FILEPATH=M:/Dev/Slicer-vs15/python-install/libs/python36.lib
```
Removing `C:/Python36-x64/libs` and starting a clean build of Slicer succeeds.

**Comment by lassoan** [comment]
Thanks, this is very useful information. Could you please check if this fixes the issue?

https://github.com/Slicer/Slicer/compare/master...lassoan:fix-debug-mode-build-error-wrong-python

**Comment by dzenanz** [comment]
Sadly, it did not solve the problem. [Output-Build.txt](https://github.com/Slicer/Slicer/files/4574800/Output-Build.txt) Now SimpleITK fails, despite its `PYTHON_DEBUG_LIBRARY` being set to `M:/a/Svs15/python-install/libs/python36.lib`.

**Comment by lassoan** [comment]
So, it did solve the problem for VTK? That would be great!

Have you tried to clean SimpleITK build directories (SimpleITK-build, SimpleITK-install, SimpleITK-prefix)?

**Comment by dzenanz** [comment]
This arises in a clean build.

**Comment by laurennlam** [comment]
@dzenanz Did you find a solution ?

**Comment by dzenanz** [comment]
No solution, but workaround: do not install python with debug library.

**Comment by lassoan** [comment]
The attempt to set PYTHON_DEBUG_LIBRARY was note successful - it did not help but it caused build errors (#4991).

I'll close this issue for now, as there is a workaround and it seem to happen very rarely. We can reopen if it turns out to be a common issue.
