### ISSUE TITLE
Glyph type not updated when switching between Markup lines

### ISSUE THREAD

**Issue by torquil** [Slicer/Slicer#4909]
I have two Line markups, one with Glyph type Cross2D and one with Circle2D. When switching between the lines by mouse clicking one the different line items at the top of the markups module, the Advanced settings below (which I have open to view), is updated to reflect the settings for the currently selected line. However, it seems that the Slicer is forgetting to updated the "Glyph type" setting. It is always the showing same as what I selected the last time I changed the Glyph type for one of the lines.

**Comment by pieper** [comment]
Yes, I can reproduce this with the current master.
