### ISSUE TITLE
"Selected" and "unselected" colours for Markup objects

### ISSUE THREAD

**Issue by torquil** [Slicer/Slicer#4910]
In the advanced properties for a markup object, there are colour choices for "selected" and "unselected" states of the markup object. However, seems to be the "Selected" colour that is used when the object is not selected, and the "Unselected" colour is never used, it seems.

Whenever I hover the mouse pointer above a markup object, it turns green not matter what the "Selected" colour is set to. And if I select a markup by clicking/highlighting it in the list of markups in the markups module, nothing happens to the object colour seen in the slice view or 3D view.

So I am a bit unsure what constitutes "selection" of a markup object.

What I think would be useful is the following:

Case 1: The object is not highlighted in the markups module list and the mouse is not hovering above the object.
Colour: Unselected colour

Case 2: The object is highlighted in the markups module list or the mouse is hovering above the object.
Colour: Selected colour

For the latter case it should be possible to unselect the object, so that the "unselected" colour is used. E.g. by clicking once more on the object in the markups module list.

**Comment by pieper** [comment]
Thanks for the report 👍 

Selected refers to the checkbox in the first column of the control points panel.  Hover highlight is different and I guess currently it's not possible to customize.  Selecting rows in the control point table is yes another thing to do with cut and paste select.  

I agree there are several different things going on but I don't think they are technically bugs.  It might make sense to think if there are ways to display the module panel control point list concept of selection in the view and maybe display the view hover selection in the module panel.  Probably better to move this to a discussion on discourse.

![image](https://user-images.githubusercontent.com/126077/80978201-be730600-8df3-11ea-9440-3de7540edac0.png)
