### ISSUE TITLE
Add convenience launcher or build-system target to locally build sphinx doc

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#4914]
## Is your feature request related to a problem? Please describe.

Facilitate building of sphinx documentation by Slicer developer

## Describe the solution you'd like

Per [suggestion](https://github.com/Slicer/Slicer/pull/4771#pullrequestreview-381575591) of @lassoan :

> It would be nice to add documentation generation target to the build or add a standalone utility (using Slicer launcher?) to generate the documentation.

## Describe alternatives you've considered

Document steps required to locally install requirements

## Additional context

See https://github.com/Slicer/Slicer/pull/4771

**Comment by lassoan** [comment]
Added a module to build documentation locally (it does not require install tree, just a checked out git repository and an installed Slicer): https://github.com/PerkLab/SlicerSandbox/tree/master/DocumentationTools

**Comment by lassoan** [comment]
DocumentationTools module (in Sandbox extension) should be sufficiently convenient for both users and developers.
