### ISSUE TITLE
Facilitate organization of image links for image uploaded to a discourse topic

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#4915]
## Is your feature request related to a problem? Please describe.

To avoid adding image to the Slicer source repository, image are added to discourse topics.

More specifically, one topic per module or documentation section is manually created in the [Documentation / Documentation Resources](https://discourse.slicer.org/c/dev/documentation-resources/26) category.

For example:

* [Getting Started section](https://discourse.slicer.org/t/getting-started-section/10932)
* [Data Module](https://discourse.slicer.org/t/data-module/10842)

Considering that (1) discourse does **not** provide us with the final link to include in documentation and (see section `Handling of images by discourse platform` below) that (2) uploading a folder images is tedious, we need to provide a mechanism to streamline this process.

## Describe the solution you'd like

Create a script, webpage or jupyter notebook available in binder to facilitate the organization of images links for image uploaded to a discourse topic.

## Describe alternatives you've considered

[A clear and concise description of any alternative solutions or features you've considered.]

### Handling of images by discourse platform

_Explanation below copied from https://github.com/Slicer/Slicer/pull/4771#discussion_r398322407_

When you first drag and drop an image into  a discourse post, it is uploaded into a temporary location and is available using an url like this one (available doing right click `Copy Image Location` in the preview):

```
https://aws1.discourse-cdn.com/standard17/uploads/slicer/original/2X/d/sywbxlReSbohAlm7G5Hy8s47Osp.png
```
and it generates markdown like this one:

```markdown
![auto_complete|21x21](upload://sywbxlReSbohAlm7G5Hy8s47Osp.png)
```

Then, after saving the post, the markdown remains unchanged but the image is moved to an amazon S3 bucket and the url become:

``'
https://discourse-cloud-file-uploads.s3.dualstack.us-west-2.amazonaws.com/standard17/uploads/slicer/original/2X/c/c823cbb536a39bef882e6b75d10c3b9e8e92d931.png
```

where `discourse-cloud-file-uploads` is a bucket and `standard17/uploads/slicer/original/2X/c/c823cbb536a39bef882e6b75d10c3b9e8e92d931.png` is the key

Additionally, discourse server post-process the image to decrease it size (in this example from 316 bytes to 208 bytes) and the S3 key likely includes the SHA1 of the post-processed file (`c823cbb536a39bef882e6b75d10c3b9e8e92d931` in our example)

Looking at the discourse code, it turns out that only `png` file are optimized:

https://github.com/discourse/discourse/blob/efd5fb665b0f478c0159b7dfb315dc0afa820c17/lib/upload_creator.rb#L334-L342

and here is the optimization function:

https://github.com/discourse/discourse/blob/efd5fb665b0f478c0159b7dfb315dc0afa820c17/lib/file_helper.rb#L100-L125

It uses the following ruby package: https://github.com/toy/image_optim which itself uses http://optipng.sourceforge.net/

It is also possible to recover the SHA1 by running `optipng`:

```
$ src/optipng/optipng -o2 /path/to/Slicer/Docs/user_guide/images/module_segment_editor/auto_complete.png -keep -strip all

$ sha1sum /path/to/Slicer/Docs/user_guide/images/module_segment_editor/auto_complete.png*
c823cbb536a39bef882e6b75d10c3b9e8e92d931  /path/to/Slicer/Docs/user_guide/images/module_segment_editor/auto_complete.png
93070ab5f8ecf49ed4c01a98936834ea3b1762e8  /path/to/Slicer/Docs/user_guide/images/module_segment_editor/auto_complete.png.bak
```

`c823cbb536a39bef882e6b75d10c3b9e8e92d931` is the SHA1 found in the URL

**Comment by lassoan** [comment]
Images are stored in github as release assets. Users have only contributed to the documentation in the last 6 months fixing typos, therefore it is probably not necessary to make image upload more convenient.
