### ISSUE TITLE
readthedocs: Update "Hardware Requirements"

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#4917]
Migrate text from  

https://www.slicer.org/wiki/Documentation/Nightly/SlicerApplication/HardwareConfiguration 

to 

https://slicer.readthedocs.io/en/latest/user_guide/getting_started.html#hardware-requirements

This file should be edited: https://github.com/Slicer/Slicer/blob/master/Docs/user_guide/getting_started.rst

If the file is getting too large, consider creating a file called `hardware_requirements.rst`

**Comment by lassoan** [comment]
Done.
