### ISSUE TITLE
Standard Python package "lzma" is not available

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4920]
Several Python packages, such as pandas or skimage complains that `lzma` package (that is supposed to be included in Python) is not available.

For example, error when trying to import skimage:

```
from skimage.morphology import skeletonize
```

```
ModuleNotFoundError                       Traceback (most recent call last)
In  [5]:
Line 3:     

File C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-05-06\lib\Python\Lib\site-packages\skimage\__init__.py, in <module>:
Line 133:   from .data import data_dir

File C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-05-06\lib\Python\Lib\site-packages\skimage\data\__init__.py, in <module>:
Line 61:    import pooch

File C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-05-06\lib\Python\Lib\site-packages\pooch\__init__.py, in <module>:
Line 7:     from .processors import Unzip, Untar, Decompress

File C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-05-06\lib\Python\Lib\site-packages\pooch\processors.py, in <module>:
Line 8:     import lzma

File C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-05-06\lib\Python\Lib\lzma.py, in <module>:
Line 27:    from _lzma import *

ModuleNotFoundError: No module named '_lzma'
```

**Comment by jcfr** [comment]
We would need to first update python-cmake-buildsystem to support building lzma module

See https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/a1ce7c2cf346ce62648d8c3e9e5cae7f655d4309/cmake/extensions/CMakeLists.txt#L30-L31

**Comment by pieper** [comment]
I've gotten this message before too, but it was never really an issue if you aren't using that format.

**Comment by lassoan** [comment]
It would be nice to add wsgiref.simple_server, too. The lack of this package seems to prevents running Jupyter server in Slicer's Python environment. See https://github.com/Slicer/SlicerJupyter/issues/45.
