### ISSUE TITLE
Improvements to the Texts module

### ISSUE THREAD

**Issue by karamellpelle** [Slicer/Slicer#4925]
Here are some suggestions for the _Texts_ module

* Use monospaced font. In this way you can make tables etc. This will also let your notes stand out compared to the application font for a better user experience.
* It should be possible to just type in your notes directly without clicking the Edit button. And remove the Save and Cancel buttons. I didn’t see those buttons, so when I tried to Clone the text node in Data view, the text was not copied.
* The editor field should look editable. Now it's just a white rectangle.

**Comment by lassoan** [comment]
The second and third bullet points are already implemented. You can enable direct editing in advanced section.

Edit/Save is needed if you want to edit text while you expect that other modules may change the node at the same time.
Using a monospaced font is a good idea. Pull request with the change is welcome.

**Comment by lassoan** [comment]
Switched to a monospaced font.
