### ISSUE TITLE
Enhance markups plane widget appearance

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4930]
It would be useful to display plane boundary in 3D view (similarly how it is already done in slice view, but maybe with a thin tube instead of just a line).

We would also need flags to control what to display: boundary, filling, or both. Maybe we don't need new MRML attribute but the existing EdgeVisibility and Representation properties could be used.

**Comment by lassoan** [comment]
@Sunderlandkyl "Outline" and "Fill" checkboxes turn on/off visibility of them in 3D views but not in slice views (sliders work both in slice and 3D views). Could you have a look? Is this intentional?

**Comment by Sunderlandkyl** [comment]
I intended the visibility checkboxes to affect 2D as well. Should be addressed by #5090.

**Comment by lassoan** [comment]
Perfect, thank you.
