### ISSUE TITLE
Slicer 5.0 Extension Manager: Manage Extensions Tab icons

### ISSUE THREAD

**Issue by spujol** [Slicer/Slicer#4936]
In the Slicer 5.0 Extension Manager 'Manage Extensions' tab, the icon of some extensions do not show up whereas they are displayed in the 'Install Extensions' tab (e.g. Curve Maker, SlicerDMRI).

<img width="948" alt="ManageExtensionTab" src="https://user-images.githubusercontent.com/1847492/82930717-20073a00-9f86-11ea-8786-a57f55d9c6df.png">
<img width="943" alt="CurveMaker" src="https://user-images.githubusercontent.com/1847492/82930735-25648480-9f86-11ea-9f4a-e472ae8e0d8b.png">
<img width="940" alt="SlicerDMRI" src="https://user-images.githubusercontent.com/1847492/82930743-285f7500-9f86-11ea-8926-12a7aafd5773.png">

Remaining extensions without valid icon:

I had a look at a couple of extensions and submitted a few PRs to fix icons - they are all some trivial issues (using outdated Slicer wiki links, using the github file's page instead of the download link, etc).

For @lassoan:
- [x] https://github.com/AIM-Harvard/SlicerRadiomics/pull/73
- [x] https://github.com/ETS-vis-interactive/SlicerPRISMRendering/pull/21
- [x] https://github.com/hina-shah/SlicerBatchAnonymize/pull/17
- [x] https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer/pull/66
- [x] https://github.com/SNRLab/SNRMeasurement/pull/4
- [x] https://github.com/lassoan/SlicerDRRGenerator.git

For @jcfr:
- [ ] https://github.com/NIRALUser/SPHARM-PDM/blob/master/CMakeLists.txt
- [ ] https://github.com/KitwareMedical/OsteotomyPlanner

For @jamesobutler:
- [x] https://github.com/gsi-biomotion/SlicerRegistrationQA/pull/15
- [x] switched to fork https://github.com/jamesobutler/SlicerRegularizedFastMarching until this is merged: https://github.com/AldrickF/SlicerRegularizedFastMarching/pull/2
- [x] switched to fork https://github.com/jamesobutler/ModelClip until this is merged: https://github.com/Ting-Jia/ModelClip/pull/3
- [x] switched to fork https://github.com/lassoan/SlicerCleverSegmentation/ until this is merged: https://github.com/JonathanRamos/SlicerCleverSegmentation/pull/3
- [x] switched to fork https://github.com/lassoan/SlicerBreastImplantAnalyzer until this is merged: https://github.com/lancelevine/SlicerBreastImplantAnalyzer/pull/7
- [x] switched to fork https://github.com/jamesobutler/SlicerBrainVolumeRefinement until this is merged: https://github.com/CSIM-Toolkits/SlicerBrainVolumeRefinement/pull/1
- [x] https://github.com/DCBIA-OrthoLab/DatabaseInteractorExtension/pull/11

**Comment by jamesobutler** [comment]
For CurveMaker:
If I change https://github.com/tokjun/CurveMaker/blob/5619cf50e5e14bffa47dbc277e217c6bd50685dd/CMakeLists.txt#L10 to

```diff
- set(EXTENSION_ICONURL "http://www.slicer.org/slicerWiki/images/b/b7/CurveMakerIcon.png")
+ set(EXTENSION_ICONURL "https://raw.githubusercontent.com/tokjun/CurveMaker/master/CurveMaker.png")
```
then the Icon appropriately shows in the ExtensionsManager installed list.
![image](https://user-images.githubusercontent.com/15837524/121962764-2e61f880-cd37-11eb-94cb-9bf46e334468.png)
The current ICONURL `http://www.slicer.org/slicerWiki/images/b/b7/CurveMakerIcon.png` gets redirected to `https://www.slicer.org/w/img_auth.php/b/b7/CurveMakerIcon.png` so the redirect might be breaking things.

All extensions that were shown in the installed tab that had icons correctly shown have a CMakeLists.txt with a ICONURL that is of `https://raw.githubusercontent.com` type.

Should old links to images hosted by www.slicer.org be updated to images hosted in the GitHub source repositories?
cc: @jcfr, @lassoan

**Comment by lassoan** [comment]
Good catch! Yes, we are moving away from the wiki, with all documentation and data hosted in extension repositories, so we should use the images stored in the extension's repository.

**Comment by lassoan** [comment]
The main issue was that icon downloading did not follow redirects. The reworked extensions manager now follows redirects, so only a handful of extensions are without icons - all due to outdated or incorrect URLs in the extension's top-level CMakeLists.txt file.

**Comment by jamesobutler** [comment]
> re Remaining extensions without valid icon:

@lassoan For pull requests that are not merged in a timely manner from the repository maintainers, should we switch the repo to one of our forks as specified in the https://github.com/Slicer/ExtensionsIndex so that the icon and screenshot issues are fixed and so we don't have broken links littering the ExtensionsManager when browsing through extensions?

**Comment by lassoan** [comment]
Agreed. I've switched to a fork for CleverSegmentation and BreastImplantAnalyzer.

@jamesobutler Could you merge RegularizedFastMarching, ModelClip, and BrainVolumeRefinement patches into your forks' main branches so that I can switch to your forks in the ExtensionsIndex?

**Comment by lassoan** [comment]
Most of the issues have been resolved. Submitted issues/pull requests in the affected repositories for the few remaining extension icon problems:
- https://github.com/KitwareMedical/OsteotomyPlanner/issues/128
- https://github.com/ALive-research/Slicer-Liver/pull/166
- https://github.com/NIRALUser/SPHARM-PDM/issues/78
- https://github.com/jamesobutler/ModelClip/pull/1
