### ISSUE TITLE
Segment statistics ignores parent transform

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4942]
Segment statistics module silently ignores parent transform, which may lead to unexpected results.

This could be fixed by cloning segmentation to a temporary node, hardening the transform, and computing everything on that. 

Transformation of master volume should be taken into account, too (but probably that is done already).

**Comment by Sunderlandkyl** [comment]
Which statistics are ignoring the parent transform?

As far as I can tell, the relevant labelmap and scalar volume statistics are affected by the parent transform,

**Comment by lassoan** [comment]
Labelmap statistics without scalar volume, with the new metrics. See for example this scene, which contains a sphere drawn over MRHead that is somewhat flattened with a linear transform:

https://1drv.ms/u/s!Arm_AFxB9yqHu5s6KPuhhzm-pJgSig?e=ypUKj3

Roundness should be well below 1.0.

If I harden the transform then I get quite strange results (roundness > 1.1).

If I resample the segmentation to be isotropic (change segmentation geometry, force isotropic) then I finally get reasonable results (roundness well below 1).

**Comment by Sunderlandkyl** [comment]
Ah, I see! I was only thinking of the statistics with obvious RAS coordinates (centroid, OBB, etc.).
