### ISSUE TITLE
Make volume centering apply a transform

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4952]
Center volume function (in Volumes module and in Add data/Center option) hardens the centering transform on the volume. It should apply the centering transform but should not harden it so that no information is discarded, the same transform can be applied to other nodes, and the transformation can be undone.

See more information in this discussion: https://discourse.slicer.org/t/volume-rendering-not-centered/11735

**Comment by jcfr** [comment]
Potentially related to https://github.com/Slicer/Slicer/issues/4459
