### ISSUE TITLE
Unable to start 4.11.0-2020-06-01 on Windows

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#4957]
Windows package installed from download.slicer.org is unable to start and displays the following dialogs.

This was not a problem with the 4.11.0-2020-05-30 package, but is a problem with the 4.11.0-2020-06-01 package.

The Qt related dlls were not included in the package.  Once I paste them in the 4.11.0-2020-06-01 install location then Slicer is able to start.  Those missing are highlighted below:
![image](https://user-images.githubusercontent.com/15837524/83523559-5fff7d00-a4b0-11ea-9524-aefb7cb4b200.png)

![image](https://user-images.githubusercontent.com/15837524/83522515-c71c3200-a4ae-11ea-9b3b-b5252a97a65d.png)
![image](https://user-images.githubusercontent.com/15837524/83522541-d00d0380-a4ae-11ea-9ed7-48cc2834eb06.png)
![image](https://user-images.githubusercontent.com/15837524/83522557-d4392100-a4ae-11ea-8c41-951ff19d9164.png)
![image](https://user-images.githubusercontent.com/15837524/83522567-d7341180-a4ae-11ea-9061-6f324e65b65e.png)

## Environment
- Slicer version: Slicer-4.11.0-2020-06-01
- Operating system: Windows

**Comment by jamesobutler** [comment]
@sjh26 Your commit 2a99657052a2cad890f7d1a754ba2ae76496aa76 (as related to https://discourse.slicer.org/t/missing-qt-library-references/11816) seems potentially relevant to this.

**Comment by sjh26** [comment]
Yeah, I put that in to hopefully address the Linux bug.  Will revert.

**Comment by jamesobutler** [comment]
Fixed by the revert https://github.com/Slicer/Slicer/commit/7da2ff7067218b28111f3c4ea1d6ad76147e0175.
