### ISSUE TITLE
Slicer modules fail to load

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4958]
On some Windows computers (updated to latest Windows 10 version), Slicer starts but extensions fail to load.

There are error messages about dlls failing to load:

```
[CRITICAL][Qt] 02.06.2020 20:51:42 [] (unknown:0) -   Error(s):
    Cannot load library C:\Users\nanchuangyue\AppData\Roaming\NA-MIC\Extensions-29059\SlicerHeart\lib\Slicer-4.11\qt-loadable-modules\qSlicerGeUsMovieReaderModule.dll: The specified module could not be found.
[CRITICAL][Qt] 02.06.2020 20:51:42 [] (unknown:0) -   Error(s):
    Cannot load library C:\Users\nanchuangyue\AppData\Roaming\NA-MIC\Extensions-29059\SlicerHeart\lib\Slicer-4.11\qt-loadable-modules\qSlicerKretzFileReaderModule.dll: The specified module could not be found.
[CRITICAL][Qt] 02.06.2020 20:51:42 [] (unknown:0) -   Error(s):
    Cannot load library C:\Users\nanchuangyue\AppData\Roaming\NA-MIC\Extensions-29059\SlicerHeart\lib\Slicer-4.11\qt-loadable-modules\qSlicerPhilips4dUsReaderModule.dll: The specified module could not be found.
[CRITICAL][Qt] 02.06.2020 20:51:42 [] (unknown:0) -   Error(s):
    Cannot load library C:\Users\nanchuangyue\AppData\Roaming\NA-MIC\Extensions-29059\SlicerIGT\lib\Slicer-4.11\qt-loadable-modules\qSlicerBreachWarningModule.dll: The specified module could not be found.
[CRITICAL][Qt] 02.06.2020 20:51:42 [] (unknown:0) -   Error(s):
    Cannot load library C:\Users\nanchuangyue\AppData\Roaming\NA-MIC\Extensions-29059\SlicerIGT\lib\Slicer-4.11\qt-loadable-modules\qSlicerCollectPointsModule.dll: The specified module could not be found.
[CRITICAL][Qt] 02.06.2020 20:51:42 [] (unknown:0) -   Error(s):
    Cannot load library C:\Users\nanchuangyue\AppData\Roaming\NA-MIC\Extensions-29059\SlicerIGT\lib\Slicer-4.11\qt-loadable-modules\qSlicerCreateModelsModule.dll: The specified module could not be found.
[CRITICAL][Qt] 02.06.2020 20:51:42 [] (unknown:0) -   Error(s):
    Cannot load library C:\Users\nanchuangyue\AppData\Roaming\NA-MIC\Extensions-29059\SlicerIGT\lib\Slicer-4.11\qt-loadable-modules\qSlicerFiducialRegistrationWizardModule.dll: The specified module could not be found.
[CRITICAL][Qt] 02.06.2020 20:51:42 [] (unknown:0) -   Error(s):
    Cannot load library C:\Users\nanchuangyue\AppData\Roaming\NA-MIC\Extensions-29059\SlicerIGT\lib\Slicer-4.11\qt-loadable-modules\qSlicerPathExplorerModule.dll: The specified module could not be found.
[CRITICAL][Qt] 02.06.2020 20:51:42 [] (unknown:0) -   Error(s):
    Cannot load library C:\Users\nanchuangyue\AppData\Roaming\NA-MIC\Extensions-29059\SlicerIGT\lib\Slicer-4.11\qt-loadable-modules\qSlicerPivotCalibrationModule.dll: The specified module could not be found.
[CRITICAL][Qt] 02.06.2020 20:51:42 [] (unknown:0) -   Error(s):
    Cannot load library C:\Users\nanchuangyue\AppData\Roaming\NA-MIC\Extensions-29059\SlicerIGT\lib\Slicer-4.11\qt-loadable-modules\qSlicerTransformProcessorModule.dll: The specified module could not be found.
[CRITICAL][Qt] 02.06.2020 20:51:42 [] (unknown:0) -   Error(s):
    Cannot load library C:\Users\nanchuangyue\AppData\Roaming\NA-MIC\Extensions-29059\SlicerIGT\lib\Slicer-4.11\qt-loadable-modules\qSlicerUltrasoundSnapshotsModule.dll: The specified module could not be found.
[CRITICAL][Qt] 02.06.2020 20:51:42 [] (unknown:0) -   Error(s):
    Cannot load library C:\Users\nanchuangyue\AppData\Roaming\NA-MIC\Extensions-29059\SlicerIGT\lib\Slicer-4.11\qt-loadable-modules\qSlicerVolumeResliceDriverModule.dll: The specified module could not be found.
[CRITICAL][Qt] 02.06.2020 20:51:42 [] (unknown:0) -   Error(s):
    Cannot load library C:\Users\nanchuangyue\AppData\Roaming\NA-MIC\Extensions-29059\SlicerIGT\lib\Slicer-4.11\qt-loadable-modules\qSlicerWatchdogModule.dll: The specified module could not be found.
```
## Steps to reproduce

Install Slicer and SlicerHeart extension.

## Expected behavior

All modules should load without errors

## Environment
- Slicer version: Slicer-4.11.0-2020-05-19
- Operating system: Windows 10

**Comment by lassoan** [comment]
The problem was that `vcruntime140_1.dll` was not found. Installing Visual C++ runtime 
https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads fixed the problem! Please check how these runtime libraries are installed.

**Comment by jamesobutler** [comment]
@lassoan `vcruntime140_1.dll` is showing present in at least Slicer-4.11.0-2020-05-30 and later.  I installed Slicer IGT in the Slicer-4.11.0-2020-05-30 version, restarted and everything loaded fine.
![image](https://user-images.githubusercontent.com/15837524/83591095-24eb6100-a525-11ea-840c-24d538d47d09.png)
![image](https://user-images.githubusercontent.com/15837524/83591164-4c422e00-a525-11ea-8477-4ce8b12c2e74.png)
![image](https://user-images.githubusercontent.com/15837524/83591293-9e834f00-a525-11ea-8bad-721ecc052e24.png)

**Comment by lassoan** [comment]
Thanks for checking.

vcruntime140_1.dll were still not present in the install tree of Slicer 4.11.0-2020-05-27, but I can confirm that it is there in Slicer 4.11.0-2020-05-30.

We can close this now and reopen if users report errors again.

**Comment by finetjul** [comment]
@jamesobutler I'm packaging myself Slicer master but `vcruntime140_1.dll` does not get packaged. That file is not in the MSVC_REDIST_DIR (C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Redist/MSVC/14.16.27012) folder. How did you fix it ? Should I manually paste the `vcruntime140_1.dll` file in the `MSVC_REDIST_DIR` folder before packaging ?

**Comment by jcfr** [comment]
@finetjul  This should have fixed in https://github.com/Kitware/CMake/commit/ecbf6546d7b4b28ddda40649ecf9d7a4cbe12dcc

>That file is not in the MSVC_REDIST_DIR (C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Redist/MSVC/14.16.27012) folder.

Where it the file then ? After we understand this better .. may be worth escalating to the CMake team

**Comment by jamesobutler** [comment]
![image](https://user-images.githubusercontent.com/15837524/89459686-0da03e00-d737-11ea-981b-aa886d64fdf5.png)
 
I'm using CMake 3.17.3 and built Slicer using Visual Studio 2019 and the v142 toolset.  These VC files match what I have in the location:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\14.26.28720\x64\Microsoft.VC142.CRT

**Comment by finetjul** [comment]
I am using CMake 3.15.7 and building with Visual Studio 2017 and the v141 toolset. 

Here is what I have in `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Redist\MSVC\14.16.27012\x64\Microsoft.VC141.CRT`
![image](https://user-images.githubusercontent.com/219044/89465072-cd11e600-d771-11ea-867d-e30f492df8ea.png)

Do you think I should have `vcruntime140_1.dll` in my MSVC Redist folder ?

**Comment by jamesobutler** [comment]
No. vcruntime140_1.dll is only with Visual Studio 2019.  Are you having problems loading a module that you built with your Slicer master build?

**Comment by finetjul** [comment]
I understood the problem. I am build Slicer master with MSVC 2017, however the Qt 5.15.0 library I am using is for msvc2019_64 (binaries do not exist for msvc2017). The Qt DLLs require `vcruntime_140_1.dll` wich is understandably not packed by Slicer.
Do you think MSVC 2017 work be able to build and package Slicer correctly with msvc2015_64 Qt binaries ?

Maybe we should mention it [here](https://www.slicer.org/wiki/Documentation/Nightly/Developers/Build_Instructions#Tested_and_recommended_build_environment)

Thanks !

**Comment by finetjul** [comment]
Actually it is not possible to build with msvc2015_64 binaries because they do not contain Qt WebEngine.
And Qt 5.15 does not ship msvc2017 binaries.
That means MSVC 2017 should not be a recommended/tested build environment for Slicer. Do you agree ?

**Comment by jamesobutler** [comment]
If you’re not building Qt from source and using only the available binaries, then yes you would likely pick the MSVC 2019 version to use in Slicer.

> You can mix binaries built by different versions of the toolset. However, you must use a toolset at least as recent as the most recent binary to link your app. Here's an example: you can link an app compiled using the 2017 toolset to a static library compiled using 2019, if they're linked using the 2019 toolset.

See https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019

This is why Qt doesn’t also provide MSVC 2017 binaries because you can just use 2019 to stay compatible with other older binaries.
