### ISSUE TITLE
Use vtkContourInterpolator to show segmentation closed surface representation in slice views

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4959]
Slice intersection of complex segmentations are often displayed incorrectly when master representation is closed surface.

This pull request has a fix, but it requires a VTK fix before it can be merged:
https://github.com/Slicer/SlicerGitSVNArchive/pull/1075

**Comment by jamesobutler** [comment]
@lassoan Is this the same as issue #4693?

**Comment by lassoan** [comment]
Yes, it is. I'll close that now.
