### ISSUE TITLE
Configure step of VTK fails (module vtkVTKm is not present)

### ISSUE THREAD

**Issue by karamellpelle** [Slicer/Slicer#4964]
After successful CMake configuring and generating, the build (`make`) fails:

    CMake Error at CMake/vtkModuleTop.cmake:56 (message):
      No such module "vtkVTKm" needed by "vtkAcceleratorsVTKm"

This is because Slicer points to the VTK commit [_a44e00db0d_](https://github.com/Slicer/VTK/commit/a44e00db0dd000d41268fa77c1d86d4d5977aeaa):

    [ 44%] Performing update step for 'VTK'
    Previous HEAD position was a81d1af082 [backport MR-6943] Qt 5.15 needs the include file QPainterPath
    HEAD is now at a44e00db0d COMP: Remove vtk-m submodule

## Environment
- Slicer version: #4962 29b7e2974
- Operating system: macOS

Take a look, @jcfr :)

**Comment by jcfr** [comment]
Thanks for the report.

Having a look now.
