### ISSUE TITLE
Save all configuration settings locally

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4966]
Currently, Slicer code and settings are installed in 2 locations:
- Slicer core and additionally installed Python packages in: c:\Users\andra\AppData\Local\NA-MIC
- Slicer*.ini files and extensions in c:\Users\(username)\AppData\Roaming\NA-MIC\

It would be better if all these would be saved in a single location (in the Slicer core installation folder):
- it would make Slicer fully portable: could run from a USB stick, or Slicer could be used as a pre-configured viewer on a DICOM CD
- in shared installation environments, all users would work with the same preconfigured settings and set of extensions and Python packages

**Comment by jcfr** [comment]
Makes sense.

Ideally, functions [slicerUserSettingsFilePath](https://github.com/Slicer/Slicer/blob/276c72e150f62d719f75d1606a47f959557454b2/Base/QTCore/qSlicerCoreApplication.cxx#L1224-L1228) and [slicerRevisionUserSettingsFilePath](https://github.com/Slicer/Slicer/blob/276c72e150f62d719f75d1606a47f959557454b2/Base/QTCore/qSlicerCoreApplication.cxx#L1230-L1252) should return path based on build settings [Slicer_CPACK_NSIS_INSTALL_REQUIRES_ADMIN_ACCOUNT](https://github.com/Slicer/Slicer/blob/47deb76d7556e40de4e25e585c4b24a63a153da5/CMake/SlicerApplicationOptions.cmake#L123-L146)

**Comment by lassoan** [comment]
> Ideally, functions [slicerUserSettingsFilePath](https://github.com/Slicer/Slicer/blob/276c72e150f62d719f75d1606a47f959557454b2/Base/QTCore/qSlicerCoreApplication.cxx#L1224-L1228) and [slicerRevisionUserSettingsFilePath](https://github.com/Slicer/Slicer/blob/276c72e150f62d719f75d1606a47f959557454b2/Base/QTCore/qSlicerCoreApplication.cxx#L1230-L1252) should return path based on build settings [Slicer_CPACK_NSIS_INSTALL_REQUIRES_ADMIN_ACCOUNT](https://github.com/Slicer/Slicer/blob/47deb76d7556e40de4e25e585c4b24a63a153da5/CMake/SlicerApplicationOptions.cmake#L123-L146)

Since Python packages are installed within the Slicer home folder, it is no longer an option to install Slicer into a protected folder (writeable only by admins).

Protected folders are still usable for custom applications (by enabling Slicer_CPACK_NSIS_INSTALL_REQUIRES_ADMIN_ACCOUNT) if all extensions and Python packages bundled. It is an independent decision to enable Slicer_STORE_SETTINGS_IN_APPLICATION_HOME_DIR, which can be used for making settings read-only, too.

We may need to make fine tunings (how and where .ini files are created, for example creating mutable copy of some default .ini files) or add helper tools (for example, a tool could create a portable Slicer instance automatically by copying application, settings, and DICOM database to a new folder).
