### ISSUE TITLE
Error trying to build Slicer without CLI

### ISSUE THREAD

**Issue by ScrappyCocco** [Slicer/Slicer#4970]
## Steps to reproduce

1. Download slicer from master (i'm on a4017472d6220903f7f85c5e49b547f1f6830f39)
2. Generate solution with these cmake settings:
![image](https://user-images.githubusercontent.com/11294898/84320299-b84e1300-ab71-11ea-8a30-bf8693627241.png)

3. Try to build Slicer.sln
4. Error at the end:
```
18>  vtkMRMLSequenceBrowserNode.cxx
18>LINK : fatal error LNK1104: impossibile aprire il file 'qSlicerBaseQTCLI.lib' [SlicerBuild\Slicer-build\Modules\Loadable\Sequences\MRML\vtkSlicerSequencesModuleMRML.vcxproj]
18>Compilazione progetto "Slicer.vcxproj" NON COMPLETATA.
```
(impossible to open qSlicerBaseQTCLI.lib)

## Consequences
Slicer.exe and Slicer.sln are still generated inside `Slicer-build`
But there are errors of missing dlls trying to launch Slicer:

Also it doesn't know the DICOM module(?)

![image](https://user-images.githubusercontent.com/11294898/84320392-e2073a00-ab71-11ea-846f-7d38d0f1ef96.png)

## Expected behavior

The solution should build and the debug should run i guess(?)
I don't see any problem on my end

## Environment
- Slicer version: 4.11.0-2020-06-09
- Operating system: Windows 10 Pro 1909

**Comment by lassoan** [comment]
I agree, most likely Sequences/MRML does not actually need qSlicerBaseQTCLI (it may be just some copy-paste error that we did not notice, as we did not try building without CLI). I'll start a test build to confirm this.

**Comment by lassoan** [comment]
I've pushed a fix. Please pull from the latest master and let us know if the build succeeds. Thank you!

**Comment by ScrappyCocco** [comment]
Now there's this error, that i never seen before i think
```
18>  Building Custom Rule Slicer/Modules/Loadable/Plots/Logic/CMakeLists.txt
18>  cl : warning della riga di comando D9002 : l'opzione sconosciuta '-library=stlport4' verrà ignorata
18>  vtkSlicerPlotsLogic.cxx
18>slicerbuild\ctk\libs\widgets\ctkLayoutManager.h(26): fatal error C1083: Non è possibile aprire il file inclusione: 'QDomDocument': No such file or directory [SlicerBuild\Slicer-build\Modules\Loadable\Plots\Logic\vtkSlicerPlotsModuleLogic.vcxproj]
```
(Unable to open include file "QDomDocument")

**Comment by ScrappyCocco** [comment]
It's strange beccause the Qt xml module is required and present in Slicer/CMakeLists.txt
Anyway, trying to fix it changing temporary the include to `#include <QtXml\QDomDocument>`
Cause like 6 linker errors:
![image](https://user-images.githubusercontent.com/11294898/84358898-1e658500-abc8-11ea-8ec3-399990973dd4.png)

**Comment by lassoan** [comment]
I've pushed some more fixes. Please try again. Thanks!

**Comment by ScrappyCocco** [comment]
Now Slicer.sln built successfully
```
19>------ Inizio compilazione: Progetto: ALL_BUILD, Configurazione: Debug x64 ------
========== Compilazione: 19 completate, 0 non riuscite, 0 aggiornate, 0 ignorate ==========
```
(0 failed)

**But** it looks like the DICOM module is not registered, why(?)
![image](https://user-images.githubusercontent.com/11294898/84489793-84263f80-aca2-11ea-8c94-b88bf27b760a.png)
