### ISSUE TITLE
Data Module stucks when Running a filtering 

### ISSUE THREAD

**Issue by helonic** [Slicer/Slicer#4975]
I apply some filters to my data (eg.BinaryMorphologicalOpeningImageFilter) and at the end I remove all unnecessary nodes from the scene (label maps/segmentation nodes) that were created in the meantime. Right after applying the filtering, I remove all nodes through the following function:

```
def RemoveNodeFromScene(node):
if slicer.mrmlScene:
slicer.mrmlScene.RemoveNode(node)
```
After I use the filtering, I have realized that the “Data module” stucks, and I cannot handle the visibility of the nodes from there anymore.
Here is a file with the necessary functions to run it through Python Interactor.
https://www.dropbox.com/s/35lsuegpymhx94n/sample.txt?dl=0

## Environment
- Slicer version: Slicer-4.11.0-2929-06-03
- Slicer version: Slicer-4.11.0-2929-03-10
- Operating system: Windows 10 Home edition

**Comment by lassoan** [comment]
It is probably because the code deletes the subject hierarchy singleton node. It would be nicer if deleting the subject hierarchy would result in recreating it from scratch instead of making the GUI stuck in an inconsistent state.

**Comment by helonic** [comment]
Thanks, Andras, that worked.
