### ISSUE TITLE
Add "Export as..." entry to Data context menu

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#4989]
## Is your feature request related to a problem? Please describe.

The Save As dialog requires many clicks to perform file saving, but for some use case people want to just move data to another app and need a streamlined method.

## Describe the solution you'd like

* When one or more nodes are selected in the Data module and the context menu (right click) there would be an "Export as..." entry.  
* Activating the "Export as..." would bring up a submenu.  
  * If all the selected nodes are of the same storable type, then the submenu would contain one entry for each file type supported by the storable.
  * If the nodes are of different types, then the submenu would have one entry "`N` nodes to default formats" where N is the number of selected nodes
  * If the selection includes only non-storable nodes the "Export as..." option would be disabled
  * If the selection is mixed storable and non-storable the submenu would say "`M` of `N` nodes to default formats"

On selecting, a directory browser dialog would open, and when a valid directory is picked the action would use the [temporary storage node method](https://discourse.slicer.org/t/markupsline-fcsv-loads-as-markupsfiducials/11545/37?u=pieper) to save in the indicated formats so the scene is not modified.  File basenames would be the node names.

## Describe alternatives you've considered

See [discussion here](https://discourse.slicer.org/t/markupsline-fcsv-loads-as-markupsfiducials/11545).

## Additional context

Discussion of SH plugin implementation between @pieper and @cpinter :

> Hi Csaba -

So you probably saw the pull request - small thing I figured we should fix.

I think I need it anyway, but I'm still stuck on what I'm trying to do, so I hope you can give a pointer (and not say it's impossible!).

Basically after talking it over with the SlicerMorph team we decided we want to add a context menu action for Export, which would have a submenu with all the valid file extensions for the selected node type.  Triggering the action would bring up a folder dialog and then save the selection.

But we also want to do this for multiple selections, and I can't find a way to add my action to the multiple select menu, which seems to be hardcoded to be delete and toggle visibility.

So my two questions are:

* can I generate a dynamic submenu in my plugin?

* can I add an action to the multiple select context menu?

Thanks in advance!
-Steve

Hi Steve,

 

This is great! I’m glad subject hierarchy is being used in so many projects. Of course it still has its limitations (and bugs).

 

* can I generate a dynamic submenu in my plugin?

Yes, this one is easy to do, and it is a basic functionality of SH (unless I misunderstand the question). In showContextMenuActionsForItem you can decide dynamically which action you registered in itemContextMenuActions you want to show for the current item

 

* can I add an action to the multiple select context menu?

This is something I have never taken on due to the lack of direct need, and its apparent complexity. I did add this hard-coded multi-select context menu for the most basic operations because it is obviously useful and was relatively easy to do. What I can imagine is collecting the context menu actions offered by the plugins for each selected item (this is easy to do), and then combine them somehow. For example we could show those that are common to all the items in the selection. This would mean adding this collection feature here, similarly to what is done for single selection. It is not obvious how to do the collection. For example, we could refactor the action visibility mechanism for the plugins so that instead of showing or hiding them in showContextMenuActionsForItem, we would just collect the visibilities in a map and apply them in the tree view. Unfortunately this would break the SH plugins in extensions, and would be backwards incompatible. Another solution I can imagine, although a bit hacky, is to clear visibility (hideAllContextMenuActions) then show and store state for each selected item.

 

I’m happy to chat about this if you’d prefer that. Or we could talk about this at the Slicer weekly hangout.

 

csaba

**Comment by pieper** [comment]
Referring to the second point, about context menus for multiple selection, perhaps this "Export as..." could just be added to the core SH as a first step and not do a major change to the plugin mechanism for this one use case.

**Comment by cpinter** [comment]
I agree. The Export As feature you described can be implemented in the tree view, a bit similarly to what @lassoan did very recently about transforms.

**Comment by pieper** [comment]
A version of this is now merged in SlicerMorph https://github.com/SlicerMorph/SlicerMorph/tree/master/ExportAs

**Comment by ebrahimebrahim** [comment]
I am looking into moving the ExportAs module into core

**Comment by ebrahimebrahim** [comment]
After discussion, here's an approach that there was enough consensus on for now:

The right-click menu for a selected node in the Data module should contain an "Export" or "Save" option.
This option should bring up a simple-looking save dialogue that has the following vertically arranged things:
- a file selector
- a file type selector that remembers what the previous choice was for this type of node
- a save button
- checkboxes for any options that show up in the options column for the node in the general save dialogue:

![save](https://user-images.githubusercontent.com/1879759/130650727-d9fa333b-dea8-401d-9313-ac37190eefe7.png)

It would be nice for this to be extensible so that choosing "Export" for certain nodes leads to a specialized dialogue for that type of node (e.g. segmentation node), but this can be put off to later.

---

I don't know if I will be able to do this myself, but I wanted to record some of the results of the discussion.
