### ISSUE TITLE
mac build error with libcurl

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#4998]
```
make[5]: *** No rule to make target `/sr/curl-install/lib/libcurl.a', needed by `bin/libRemoteIO.dylib'.  Stop.
make[4]: *** [Libs/RemoteIO/CMakeFiles/RemoteIO.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [Slicer-prefix/src/Slicer-stamp/Slicer-build] Error 2
make[1]: *** [CMakeFiles/Slicer.dir/all] Error 2
make: *** [all] Error 2
```
## Steps to reproduce

Building current master 128fb86dd18040d9f7871d2276346e093d3248ae

Wiped out all curl and Slicer directories from the build tree.

## Environment
macOS 10.14.6
```
$ clang --version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by pieper** [comment]
In a debug build, there is a library called `libcurl-d.a`

```
$ find curl* -iname lib\*.a
curl-build/lib/libcurl-d.a
curl-install/lib/libcurl-d.a
```

**Comment by jcfr** [comment]
Thanks for the report and thanks for testing Debug build.

**Comment by pieper** [comment]
I'm rebuilding in release mode too, but I'm guessing it works there.  It appears to be some issue with the cmake config files in the install tree.  I don't think [the way curl is added](https://github.com/Slicer/Slicer/blob/master/Libs/RemoteIO/CMakeLists.txt#L38) would be an issue.

I can work around this issue for now.

**Comment by pieper** [comment]
Confirming that the release build completed with no errors.

Also as a temporary workaround the following command can be used to make a debug build work:
```cp curl-install/lib/libcurl-d.a curl-install/lib/libcurl.a```

**Comment by pieper** [comment]
@jcfr do you have an idea how to fix this?  If not maybe I should file an issue with curl or cmake?

**Comment by cpinter** [comment]
I have the same issue on Windows. The error is `LINK : fatal error LNK1104: cannot open file 'C:\d\S4D\curl-install\lib\libcurl.lib'`
and in the said folder there is only a libcurl-d.lib.
I tried to solve it with setting another postfix [similar to this](https://github.com/Slicer/Slicer/blob/master/SuperBuild/External_curl.cmake#L111-L120), but CMAKE_BUILD_TYPE is empty so not sure how it should be done.
