### ISSUE TITLE
Slicer requires installation of Visual Studio redistributables

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5001]
It has been reported multiple occasions (and I personally debugged one case so I can confirm) that Windows installations and specifically SlicerRT modules did not load correctly until Visual Studio redistributable package was installed.

See reports here:
- https://discourse.slicer.org/t/dicom-segmentation-import-problem-on-windows/12084/8
- https://discourse.slicer.org/t/slicerrt-dicom-rt-import-issue/11881/2

Maybe the issue is that SlicerRT (most precisely, Plastimatch) uses OpenMP for some things. It may be possible that the OpenMP DLL (vcomp140.dll) that is bundled in the installation package is incorrect?

**Comment by pieper** [comment]
I was able to start a fresh gpu enabled VM on AWS Workspaces and Slicer + SlicerRT installed and run fine, no redistributable package required.  This version of windows came with a few things like firefox pre-installed, so maybe it's not representative of other windows installations in this respect?  Also although the AWS interface said it was windows 10 it's a server version underneath the windows 10 interface.

Is there anything else to try on this machine before I shut it down?

![image](https://user-images.githubusercontent.com/126077/85791562-05002500-b700-11ea-84c6-95c031694f04.png)

**Comment by jamesobutler** [comment]
Seems like in both situations as reported on the forum the user was using Slicer 4.10.2 and then installed SlicerRT.

**Comment by pieper** [comment]
Ah, good catch @jamesobutler 🙏 

Right, I can reproduce the issue with 4.10.2 on the AWS machine.  I guess we already know the workaround, so is there anything else to test?

![image](https://user-images.githubusercontent.com/126077/85798524-9de86d80-b70b-11ea-9ff6-b9db896381a1.png)

**Comment by jamesobutler** [comment]
The only recent change as it is related to Slicer Stable extensions is the change (https://github.com/Slicer/DashboardScripts/commit/c242d16e093d008e957394ae448625030f2c2bb4) that the extensions are being built with VS2019+v140 toolset instead of VS2015+v140 toolset.  The Slicer core stable package isn't build every night and was built with a VS2015+v140 toolset configuration.

**Comment by lassoan** [comment]
Thanks a lot Steve, this was very helpful information, it means that we have not missed anything very obvious. I don't think we can test anything more on it.

One system that I troubleshooted remotely (and I could only fix by installing VC++ redistributables) was Chinese. It might be possible that DLLs that are available on a system by default depends on localization of Windows. 

I think we can close this issue now and when this comes up we take note Windows version & language, and Slicer version and see if we can recognize a common pattern.

**Comment by pieper** [comment]
Okay great, I shut off the machine for now.  The AWS workspaces option was fairly easy in the end and might be useful in the future.  For the record, to run Slicer I needed to request a quota increase to access a GPU machine, which took about 2 days.  Then it takes about 20 minutes to create the machine.  You use a custom app to access the remote desktop, which provided about the same performance I get with VNC to other VMs.  It cost $22/month to keep the machine turned off, and $1.75 / hour when it is on.  I'll probably keep it around for a bit in case we want to do more testing.  The machine itself is 8 core, 15 gig memory, with a gpu (didn't notice exactly which one).
