### ISSUE TITLE
Curl build errors on Ubuntu 20.04 (focal) Linux system using gcc-9.3.0

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5005]
Building (detached) branch upstream/4859-fix-linux-crash (c666ad29d) with Qt-5.12.9 or Qt-5.15.0 on an Ubuntu 20.04 (focal) Linux system using gcc-9.3.0, I get:

Errors:
> /home/lee.newberg/git/Slicer-SuperBuild-Debug-5.12.9/curl/lib/warnless.c:101:4: error: #error "SIZEOF_CURL_OFF_T not defined"
> /home/lee.newberg/git/Slicer-SuperBuild-Debug-5.12.9/curl/lib/warnless.c:192:40: error: ‘CURL_MASK_SCOFFT’ undeclared (first use in this function); did you mean ‘CURL_MASK_SINT’?

Warnings:
> /home/lee.newberg/git/Slicer-SuperBuild-Debug-5.15.0/curl/lib/curl_setup.h:397:6: warning: "SIZEOF_CURL_OFF_T" is not defined, evaluates to 0 [-Wundef]
> /home/lee.newberg/git/Slicer-SuperBuild-Debug-5.15.0/curl/lib/warnless.c:88:6: warning: "SIZEOF_CURL_OFF_T" is not defined, evaluates to 0 [-Wundef]
> /home/lee.newberg/git/Slicer-SuperBuild-Debug-5.15.0/curl/lib/warnless.c:91:8: warning: "SIZEOF_CURL_OFF_T" is not defined, evaluates to 0 [-Wundef]
> /home/lee.newberg/git/Slicer-SuperBuild-Debug-5.15.0/curl/lib/warnless.c:94:8: warning: "SIZEOF_CURL_OFF_T" is not defined, evaluates to 0 [-Wundef]
> /home/lee.newberg/git/Slicer-SuperBuild-Debug-5.15.0/curl/lib/warnless.c:97:8: warning: "SIZEOF_CURL_OFF_T" is not defined, evaluates to 0 [-Wundef]
> /home/lee.newberg/git/Slicer-SuperBuild-Debug-5.15.0/curl/lib/warnless.c:197:1: warning: control reaches end of non-void function [-Wreturn-type]

_Originally posted by @Leengit in https://github.com/Slicer/Slicer/pull/4992#issuecomment-648302425_

**Comment by jcfr** [comment]
I am failing to reproduce this using  `dockbuild/ubuntu2004-gcc9`. Here is what I did

First, download the dockbuild image and generate the convenience script:

```
docker pull dockbuild/ubuntu2004-gcc9
docker run --rm dockbuild/ubuntu2004-gcc9 > ~/bin/dockbuild-ubuntu2004
chmod u+x ~/bin/dockbuild-ubuntu2004
```

Then, make working directory and checkout the curl sources used in Slicer:

```
mkdir /tmp/5005-curl-build-failure-ubuntu2004-gcc9
cd /tmp/5005-curl-build-failure-ubuntu2004-gcc9

git clone git://github.com/Slicer/curl -b slicer-7.70.0-2020-04-29-53cdc2c
```

Then, shell into the ubuntu image:

```
cd /tmp/5005-curl-build-failure-ubuntu2004-gcc9
dockbuild-ubuntu2004 bash
```

Finally, configure the project:

```
cmake \
  -S curl \
  -B curl-build  \
      -DCMAKE_BUILD_TYPE:BOOL=OFF \
      -DBUILD_TESTING:BOOL=OFF  \
      -DBUILD_CURL_EXE:BOOL=OFF  \
      -DBUILD_SHARED_LIBS:BOOL=OFF \
      -DENABLE_ARES:BOOL=OFF \
      -DCURL_ZLIB:BOOL=ON  \
      -DCURL_DISABLE_FTP:BOOL=ON \
      -DCURL_DISABLE_LDAP:BOOL=ON \
      -DCURL_DISABLE_LDAPS:BOOL=ON \
      -DCURL_DISABLE_TELNET:BOOL=ON \
      -DCURL_DISABLE_DICT:BOOL=ON \
      -DCURL_DISABLE_FILE:BOOL=ON \
      -DCURL_DISABLE_TFTP:BOOL=ON \
      -DHAVE_LIBIDN2:BOOL=FALSE

```

and build 

```
cmake --build curl-build --config Debug
```

And here are some more details:

```
$ cat curl-build/CMakeCache.txt | grep -E "COMPILER.+FILEPATH"
CMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc
CMAKE_C_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar-9
CMAKE_C_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib-9

$ cat curl-build/CMakeCache.txt | grep -E "FLAGS.+STRING"
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_OFF:STRING=
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_OFF:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_OFF:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_OFF:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_OFF:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
```

**Comment by Leengit** [comment]
It was a user error on my part.  I had a mixture of old curl and new curl files in my Slicer-SuperBuild-Debug/curl* directories that were incompatible.  Removing those subdirectories and then invoking cmake and make fixed the problem.
