### ISSUE TITLE
Build failed with error: cannot open input file 'optimized.lib'

### ISSUE THREAD

**Issue by simohauml** [Slicer/Slicer#5020]
Windows 10 build failed with error: cannot open input file 'optimized.lib'

## Steps to reproduce

Follow build steps on https://www.slicer.org/wiki/Documentation/Nightly/Developers/Build_Instructions
Open VS solution file generated by CMake GUI
Right-click ALL_BUILD
Select Build option

## Error

Error	LNK1181	cannot open input file 'optimized.lib' [D:\sbd\SimpleITK-build\SimpleITK-build\Wrapping\Python\SimpleITK_PYTHON.vcxproj] [D:\sbd\SimpleITK-build\SimpleITK.vcxproj]	SimpleITK	D:\sbd\LINK	1	

## Environment
- Slicer git HEAD version: 792667ebfcb10e525830803c3fd874d864d48f6d
- Windows 10 Enterprise LTSC Version 1809
- Microsoft Visual Studio Enterprise 2019 Version 16.6.2 (v142)
- CMake 3.17.3
- QT 5.15.0
- Python 3.6.7 (I also installed Python 2.7 for other project)
- Source path: D:\ss
- Build path(debug): D:\sbd

[CMakeError.log](https://github.com/Slicer/Slicer/files/4840174/CMakeError.log)
[CMakeOutput.log](https://github.com/Slicer/Slicer/files/4840175/CMakeOutput.log)
[build-output.txt](https://github.com/Slicer/Slicer/files/4840176/build-output.txt)

**Comment by lassoan** [comment]
Probably VTK accidentally found some debug-mode built Python, while it should have used the release-mode Python built by Slicer. Could you check what Python library is listed in VTK's CMakeCache.txt?

**Comment by simohauml** [comment]
> Probably VTK accidentally found some debug-mode built Python, while it should have used the release-mode Python built by Slicer. Could you check what Python library is listed in VTK's CMakeCache.txt?

Here is what I found in CMakeCache.txt file under ~buildpath/VTK-build
[CMakeCache.txt](https://github.com/Slicer/Slicer/files/4841448/CMakeCache.txt)

//Path to a library.
PYTHON_DEBUG_LIBRARY:FILEPATH=C:/Program Files/Python36/libs/python36_d.lib
//Initial cache
PYTHON_EXECUTABLE:PATH=D:/sbd/python-install/bin/PythonSlicer.exe
//Initial cache
PYTHON_INCLUDE_DIR:PATH=D:/sbd/python-install/include
//Initial cache
PYTHON_LIBRARY:FILEPATH=D:/sbd/python-install/libs/python36.lib
//Initial cache
PYTHON_LIBRARY:FILEPATH=D:/sbd/python-install/libs/python36.lib

//Enable vtkpython and pvtkpython binaries
VTK_ENABLE_VTKPYTHON:BOOL=ON

//Details about finding PythonInterp
FIND_PACKAGE_MESSAGE_DETAILS_PythonInterp:INTERNAL=[D:/sbd/python-install/bin/PythonSlicer.exe][v3.6.7()]
//Details about finding PythonLibs
FIND_PACKAGE_MESSAGE_DETAILS_PythonLibs:INTERNAL=[D:/sbd/python-install/libs/python36.lib][D:/sbd/python-install/include][v()]

//Directory where python modules will be built
VTK_BUILD_PYTHON_MODULES_DIR:INTERNAL=D:/sbd/VTK-build/bin/$<CONFIG>/Lib/site-packages

//Directory where python modules will be installed
VTK_INSTALL_PYTHON_MODULES_DIR:INTERNAL=./bin/Lib/site-packages

**Comment by simohauml** [comment]
With a review of build instruction, found I was using Visual Studio 2019, toolset v142. I will try toolset v140 and v141.
Sorry for post the issue here, I should try more and ask in the development community site.

**Comment by lassoan** [comment]
If the problem persists, temporarily rename or remove `C:/Program Files/Python36/libs/python36_d.lib`, as it is incorrectly found as PYTHON_DEBUG_LIBRARY.

**Comment by lassoan** [comment]
Seems like the same issue as #4898.

**Comment by simohauml** [comment]
Uninstall Python 3.6.7 (with debug lib installed) solve this issue.
