### ISSUE TITLE
Can't open Extensions Manager

### ISSUE THREAD

**Issue by fepegar** [Slicer/Slicer#5022]
When I click on the Extensions Manager button, I get the following message:

<img width="688" alt="Screen Shot 2020-06-30 at 13 08 04" src="https://user-images.githubusercontent.com/12688084/86124707-7579be00-bad3-11ea-8c20-c8127cb82cf2.png">

## Environment
- Slicer version: `Slicer-4.11.0-2020-06-29`
- Operating system: `macOS Catalina 10.15.5`

**Comment by jamesobutler** [comment]
xref #4999

**Comment by fepegar** [comment]
Thanks @jamesobutler, I should've searched before posting.

**Comment by jcfr** [comment]
Do you get an error message similar to this one:

```
dyld: Library not loaded: /Volumes/D/Support/qt-everywhere-build-5.15.0/lib/QtGui.framework/Versions/5/QtGui
  Referenced from: /Applications/Slicer 2.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
```

**Comment by fepegar** [comment]
Yes. I couldn't see it the previous time because the OS didn't allow me to run Slicer form the terminal (I had to go and right click -> Open). Now I opened it from zsh and can see that message.

**Comment by jcfr** [comment]
This is helpful, look like we need to fix the packaging rule associated with `QtWebEngineProcess`

**Comment by jamesobutler** [comment]
Another report of this issue by a user in the forum. See https://discourse.slicer.org/t/problematic-behavior-of-the-extension-manager/10986/11

**Comment by pieper** [comment]
Thanks for cross-linking @jamesobutler 👍 

@jcfr , this user report sounds like the behavior I mentioned on the hangout - first the error dialog and then the extension dialog opens.  It's an odd issue that may involve packaging but also something else.

**Comment by jamesobutler** [comment]
Another user report of this on the forum https://discourse.slicer.org/t/macos-nightly-extensions-manager-error/12445.

**Comment by smrolfe** [comment]
Hello, I was wondering if there are any updates on this issue? I'm getting similar behavior with todays Mac preview. I see an error message on launching the extension manager the first time. Launching a second time brings up the window, but the extensions are missing. After waiting a few minutes, the "Restore" tab is populated and I'm able to install the extensions listed there. I'm not able to get new extensions.

**Comment by jcfr** [comment]
@smrolfe  We are actively working on finalizing the new infrastructure, more details available here: https://www.slicer.org/wiki/Documentation/Labs/ExtensionsServer#Status

**Comment by fepegar** [comment]
@jcfr are you planning to revert the changes that lead to this issue until the new infrastructure is ready? If not? Do you know when they were introduced? Would an older Slicer work?

**Comment by che85** [comment]
The last working version for me is Slicer 4.11.0-2020-06-04 (revision 29111 / a12d8d3)

**Comment by che85** [comment]
I also tried directly accessing the extension server at http://slicer.kitware.com/midas3/slicerappstore, but getting the following errors:

```
The system has encountered the following error:
Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1040] Too many connections' in /projects/src/Midas3/library/Zend/Db/Adapter/Pdo/Abstract.php:129 
Stack trace: #0 /projects/src/Midas3/library/Zend/Db/Adapter/Pdo/Abstract.php(129): PDO->__construct('mysql:dbname=mi...', 'midas', 'mida$pa$$', Array) #1 
/projects/src/Midas3/library/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect() #2
 /projects/src/Midas3/library/Zend/Db/Adapter/Abstract.php(460): Zend_Db_Adapter_Pdo_Mysql->_connect() #3
 /projects/src/Midas3/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `er...', Array) #4
 /projects/src/Midas3/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `er...', Array) #5
 /projects/src/Midas3/library/Zend/Log/Writer/Db.php(145): Zend_Db_Adapter_Abstract->insert('errorlog', Array) #6
 /projects/src/Midas3/library/Zend/Log/Writer/Abstract.php(85): Zend_Log_Writer_Db->_write(Array) #7
 /projects/src/Mi
In /projects/src/Midas3/library/Zend/Controller/Plugin/Broker.php, line: 336
At 09:50:25 2020-07-15

Please notify your administrator with this information.
```

**Comment by jcfr** [comment]
> are you planning to revert the changes that lead to this issue until the new infrastructure is ready? If not? Do you know when they were introduced? Would an older Slicer work?

I don't think a particular change is introducing the error. Problem is summarized [here](https://www.slicer.org/wiki/Documentation/Labs/ExtensionsServer#Current_infrastructure) in the `Current infrastructure` section.

> Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1040] Too many connections'

We already have a daily restart of the server, I will work with our administrator to increase the frequency and also increase the allocated memory.

Waiting the new infrastructure is rolled out, we will have to be patient :pray:

**Comment by jcfr** [comment]
To follow up on this, memory associated with the current server has been increased and restart of database and web server has been scheduled for 11am ET and 11pm ET

**Comment by pieper** [comment]
I make a local release build on mac, and then ran `make package` in the `Slicer-build` directory and ended up with this error message that seems to correspond with the runtime error.

I can run `./_CPack_Packages/macosx-amd64/DragNDrop/Slicer-4.11.0-2020-07-31-macosx-amd64/Slicer.app/Contents/MacOS/Slicer ` and the extension manager opens correctly, but probably because it resolves to the original version of the file.

```
757 - fixing item /usr/local/Cellar/qt/5.15.0/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore with @rpath/Frameworks
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: no LC_RPATH load command with path: @executable_path/Frameworks found in: /opt/sr/Slicer-build/_CPack_Packages/macosx-amd64/DragNDrop/Slicer-4.11.0-2020-07-31-macosx-amd64/Slicer.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess (for architecture x86_64), required for specified option "-rpath @executable_path/Frameworks @loader_path/../../../../../../../../"
CPack: Create package
CPack: - package: /opt/sr/Slicer-build/Slicer-4.11.0-2020-07-31-macosx-amd64.dmg generated.
```
Full `make package` [build log is here](https://gist.github.com/pieper/a078274925ad1746ae300e63f33d9d5b)

**Comment by pieper** [comment]
I found a fix for the original issue posted by @fepegar.  😄   

Should also work for @che85 and @smrolfe and address issue #4999.  Note this is purely a packaging issue and is unrelated to the backend extension server (the two issues confounded a bit).

PR https://github.com/Slicer/Slicer/pull/5077 should fix it once merged, but this command should work in the meantime.

It should work for anyone who put Slicer.app in /Applications, but editing the last line should allow you to fix an installation anywhere.

```

install_name_tool \
  -add_rpath @loader_path/../../../../../../../../ \
  -change \
    /Volumes/D/Support/qt-everywhere-build-5.15.0/lib/QtCore.framework/Versions/5/QtCore \
    @rpath/Frameworks/QtCore.framework/Versions/5/QtCore \
  -change \
    /Volumes/D/Support/qt-everywhere-build-5.15.0/lib/QtGui.framework/Versions/5/QtGui \
    @rpath/Frameworks/QtGui.framework/Versions/5/QtGui \
  -change \
    /Volumes/D/Support/qt-everywhere-build-5.15.0/lib/QtNetwork.framework/Versions/5/QtNetwork \
    @rpath/Frameworks/QtNetwork.framework/Versions/5/QtNetwork \
  -change \
    /Volumes/D/Support/qt-everywhere-build-5.15.0/lib/QtPositioning.framework/Versions/5/QtPositioning \
    @rpath/Frameworks/QtPositioning.framework/Versions/5/QtPositioning \
  -change \
    /Volumes/D/Support/qt-everywhere-build-5.15.0/lib/QtQml.framework/Versions/5/QtQml \
    @rpath/Frameworks/QtQml.framework/Versions/5/QtQml \
  -change \
    /Volumes/D/Support/qt-everywhere-build-5.15.0/lib/QtQmlModels.framework/Versions/5/QtQmlModels \
    @rpath/Frameworks/QtQmlModels.framework/Versions/5/QtQmlModels \
  -change \
    /Volumes/D/Support/qt-everywhere-build-5.15.0/lib/QtQuick.framework/Versions/5/QtQuick \
    @rpath/Frameworks/QtQuick.framework/Versions/5/QtQuick \
  -change \
    /Volumes/D/Support/qt-everywhere-build-5.15.0/lib/QtWebChannel.framework/Versions/5/QtWebChannel \
    @rpath/Frameworks/QtWebChannel.framework/Versions/5/QtWebChannel \
  -change \
    /Volumes/D/Support/qt-everywhere-build-5.15.0/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore \
    @rpath/Frameworks/QtWebEngineCore.framework/Versions/5/QtWebEngineCore \
  \
    /Applications/Slicer.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess

```

**Comment by lassoan** [comment]
Thanks a lot @pieper 🥇 it is awesome that finally this serious issue will get fixed. I don't know much about how Mac build & package works, so I cannot review the changes, but hopefully @jcfr or someone else can.

**Comment by jcfr** [comment]
Thanks @pieper , that is very helpful and should allow me to easily update the build system 🙏

**Comment by fepegar** [comment]
Today's preview, `4.11.0-2020-08-02 r29250 / 1a8a340`, has an interesting (and unusable) look:

<img width="1392" alt="Screen Shot 2020-08-04 at 11 05 58" src="https://user-images.githubusercontent.com/12688084/89281945-b4ef7900-d642-11ea-8e3b-c1867ee9661b.png">

**Comment by fepegar** [comment]
Widgets work, though. I've managed to install the extension I was looking for.

**Comment by fepegar** [comment]
I'm still having this problem: https://github.com/Slicer/Slicer/issues/5022#issuecomment-668507814

Can anyone reproduce?

**Comment by pieper** [comment]
Weird.  I don't have that problem.  Today's preview works great.

![image](https://user-images.githubusercontent.com/126077/90679549-558e8d00-e22e-11ea-8910-e0f2c3665d9f.png)

**Comment by fepegar** [comment]
(I'm using today's preview as well)

**Comment by lassoan** [comment]
Do you have the washed-out colors issue? If yes, please create a new issue for it, as it may be unrelated to the main topic of this bug report (and that was fixed).
