### ISSUE TITLE
Characters with accents are not correctly displayed in Extensions Manager

### ISSUE THREAD

**Issue by fepegar** [Slicer/Slicer#5031]
Hi all,

This happens in the main window of the Extensions Manager, but not when I click on the extension icon and get in.

![Capture_slicer2](https://user-images.githubusercontent.com/12688084/86626899-483f7b00-bfbf-11ea-84d0-ea855392af5f.PNG)

If this is problematic, I don't mind removing the accents, but I thought I'd let you know.

## Environment
- Slicer version: Slicer-4.11.0-2020-07-04
- Operating system: Windows 10

**Comment by jcfr** [comment]
Since we are actively working on developing a new frontend and backend for the extension manager, I suggest we close this issue.

**Comment by fepegar** [comment]
Ok, thanks @jcfr.
