### ISSUE TITLE
Module Finder: Avoid confusion disabling item editing

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5033]
When using the module finder, double clicking on a module name in the list switch to module eding.

## Steps to reproduce

Search for a module. For example, type `bl`, then double click on the `Tables` module name and it allows the user to update the module name

![image](https://user-images.githubusercontent.com/219043/86704824-425b9100-bfe3-11ea-8351-640b27a25208.png)

## Expected behavior

Instead of editing the module name, double clicking should switch to the module.

## Environment
- Slicer version: Slicer-4.11.0-2020-07-06
- Operating system: NA

**Comment by lassoan** [comment]
Good idea I'll fix/implement this!
