### ISSUE TITLE
Tests for TorchIO extension are failing on Slicer CDash

### ISSUE THREAD

**Issue by fepegar** [Slicer/Slicer#5036]
I have been checking the test logs for the `TorchIO` extension and keep seeing that they fail, but I can't interpret the logs and don't know if there's anything I need to change in my code.

Why I'm doing:
1. Go to this website: http://slicer.cdash.org/index.php?project=SlicerPreview
2. Search for torchio
3. Open the three results

## Linux

[`Test (0 passed, 0 failed, 0 not run)`](http://slicer.cdash.org/buildSummary.php?buildid=1958954).

Why are the tests not being run?

## Windows

[`Test (1 passed, 1 failed, 0 not run)`](http://slicer.cdash.org/buildSummary.php?buildid=1959434).

The test that fails is `py_nomainwindow_qSlicerTorchIOTransformsModuleGenericTest`, because `test_widgetRepresentation (qSlicerTorchIOTransformsModuleGenericTest.qSlicerTorchIOTransformsModuleGenericTest) ... Failed to obtain reference to 'qSlicerMainWindow'`. Not sure what that means.

The test I wrote passed, but the summary says "Unstable". What does that mean?

## macOS

[`Test (0 passed, 2 failed, 0 not run)`](http://slicer.cdash.org/buildSummary.php?buildid=1959517).

One of the tests that failed is the one that failed on Windows. The other is the one I wrote. In the log I can see some output from `slicer.util.pip_install` and then `error: [/Volumes/D/P/S-0-build/Slicer-build/bin/Slicer.app/Contents/MacOS/./Slicer] exit abnormally - Report the problem.`.

**Comment by jcfr** [comment]
> Linux: Why are the tests not being run?

We do not run test on linux, only build for now

> Windows
> Failed to obtain reference to 'qSlicerMainWindow'. Not sure what that means.

We try to run the generic test without having the main window instantiated, and we expect the test to pass.

Generic tests are based of these files:
* https://github.com/Slicer/Slicer/blob/master/Base/QTGUI/Testing/Cxx/qSlicerModuleGenericTest.cxx.in
* https://github.com/Slicer/Slicer/blob/master/Base/QTGUI/Testing/Cxx/qSlicerModuleWidgetGenericTest.cxx.in
* https://github.com/Slicer/Slicer/blob/master/Base/QTCore/Testing/Python/qSlicerModuleGenericTest.py.in

Will have to look at this in more details to understand if this is a regression in Slicer or an issue with  the module.

Is it something you could investigate on your platform ?

> macOS

Let me know if you would like me to get a stack trace of the build machine




## Access to testing results

To  more quickly lookup the testing result:

(1) select "Show Filter"

![image](https://user-images.githubusercontent.com/219043/87054432-1867c180-c1d1-11ea-8fc7-b6e65b1642e4.png)

(2) select "build name"

![image](https://user-images.githubusercontent.com/219043/87054565-42b97f00-c1d1-11ea-8b7e-72dd6ce30f25.png)

(3) you then get this link:

http://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=TorchIO

**Comment by fepegar** [comment]
Hi @jcfr. Thanks for the info and for the filtering tips. I can investigate the Windows issue if you can guide me a bit about it.

For the macOS issue, is that the very low-level stack trace the OS shows when Slicer crashes? I'm not sure I'll understand much... Also, the tests pass in my mac so I have no idea what might be going on.

**Comment by lassoan** [comment]
Is this still an issue in the latest Slicer Preview Release?

**Comment by fepegar** [comment]
> Is this still an issue in the latest Slicer Preview Release?

Yes. I just removed the dialogs in testing mode (https://github.com/fepegar/SlicerTorchIO/commit/d8c727ac401dcb28b701279e396f56ba0de29392). Hopefully, that will help. I will check again tomorrow and keep you posted.

**Comment by fepegar** [comment]
The errors are still happening. I think most of them are timeouts (10 minutes). I don't know why that happens. For [this macOS test](https://slicer.cdash.org/test/18736385), for example, the end of the log says 

```test_TorchIOTransforms (TorchIOTransforms.TorchIOTransformsTest) ... ok

----------------------------------------------------------------------
Ran 2 tests in 48.953s

OK
Switch to module:  ""
Switch to module:  ""
```

And the status is still `Failed`.

**Comment by jamesobutler** [comment]
@fepegar Do you want to track testing issues over at https://github.com/fepegar/SlicerTorchIO/issues instead of in this issue? I believe the originally posted issue is not happening anymore. However some tests are timing out because it gets to the confirm ok/cancel display for `TorchIO will be downloaded and installed now. The process might take some minutes.` and that never gets clicked on.

**Comment by lassoan** [comment]
To skip popups during testing, you can check `slicer.app.commandOptions().testingEnabled` property in Python. It is set to `True` when Slicer is launched with `--testing`, which is enabled for most (if not all) automatic tests.

**Comment by fepegar** [comment]
If the originally posted issue is not happening anymore, I'm happy to track this somewhere else. I will reopen if I see the errors are still happening. Thanks, @jamesobutler and @lassoan.
