### ISSUE TITLE
Allow using a color node for segmentation to labelmap export

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5044]
A lot of users still use legacy file format (3D labelmap volume with hardcoded label values) for storing segmentation. These users have a hard time making Segmentations module's labelmap volume export assign label values that they want.

Segmentations tries to preserve existing label values, but if segments are added/deleted or moved between segments then this heuristic may not be enough.

## Describe the solution you'd like

Allow segmentations labelmap export feature take a color node. Colors could be found by matching the segment's name and the corresponding color index could be used as label value.

GUI could consist of
1. Additional checkbox: "Set label values from color node" (if enabled then label values would be retrieved from color table; otherwise the current behavior would be preserved - label values stored in the segmentation node would be used).
2. Additional color node selector. "none text" would be "reference volume node color" (if the user does not select anything then the reference volume's color node would be used)

## Describe alternatives you've considered

Terminology file could contain label value, too, but it is harder to create terminology files and those who can do it, they would probably capable of doing the terminology to label value conversion themselves.

## Additional context

https://discourse.slicer.org/t/how-to-change-the-label-value-of-binary-labelmap-volume/12511/7

https://discourse.slicer.org/t/segment-ids-when-imported-from-label-map/12502/2

**Comment by lassoan** [comment]
One more user requested this:
https://discourse.slicer.org/t/export-segmentation-scene-mrml-and-segmentations-nrrd-into-nifti-format-for-dropbox-viewing/12517/14

We could consider this for Slicer-5.0, as it should not be too much work and needed by many users.

**Comment by Sunderlandkyl** [comment]
Feature added in 5615e73.
