### ISSUE TITLE
Create markups ROI

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5061]
Annotation ROI nodes have many limitations. We need complete rework, based on markups infrastructure.

## Describe the solution you'd like

Have a new vtkMRMLMarkupsROINode, similar to vtkMRMLAnnotationROINode but with these additional features:
- [x] can be rotated
- [x] can be transformed (#1636)
- [x] has label
- [x] its color can be set
- [x] has inside-out mode (https://github.com/Slicer/Slicer/issues/1596)

Additional specific requests:

High priority:
- [x] Storage: use a single "orientation" matrix for storing orientation (instead of separate xAxis, yAxis, zAxis"), as it is more consistent with how we usually manage orientation
- [x] Storage: "sideLenghts" is very clear definition for a box, but not so good if we generalize the ROI (e.g., to ellipsoid); "diameter" or "size" could be better, as they are probably still clear enough and applicable to more shapes than just a box
- [x] Storage: "origin" is consistent with how we represent a coordinate system, but in case of a ROI, it may be more informative to have the "center" displayed in the file (if users create a file manually or from an external software, it could be more intuitive if they specify the center); "center" is also a bit more clear than "origin" (it may not be clear for everyone that origin is in a corner)
- [x] Storage: it would be better to display ROI properties (origin, size, etc.) near the beginning (before control points, measurments, display sections), because these files will be directly viewed and edited by users, so we should always start with the most important information
- [x] Make filling 20% opacity by default (and set it to 0% when used as volume rendering clipping ROI)
- [x] Translation/rotation handles are too small in 3D (about half the size compared to slice views)
- [x] When a ROI is already the active widget and user clicks place mode again then a new widget should be created (now it resets the current widget). At least until we improve the widget toolbar (we should have separate options for editing selected segmentation or create a new one).
- [x] When the ROI is in bounding box mode and has many control points and then you switch to box mode then the ROI seems to remain in bounding box mode.
- [x] We need outline (wireframe) display in 3D view (for example, for volume rendering clipping that would be a good representation)
- [x] After placing a ROI (at least when it is done, interactively, initiated via the GUI) then make the interaction handles displayed by default, because now after you place the ROI it is very hard to adjust it.
- [x] Make right-click menu work on all interaction handle points
- [x] Make right-click work on the outline (but maybe on the filled area as well, if it is >0%) so that interaction handles can be activated/deactivated in a viewer (it can be hard to find a ROI node in the Data module)
- [x] Add "Interaction handles visibility" option to eye icon right-click menu in subject hierarchy tree (probably for all markups)

Medium priority:
- [x] Cannot unzoom the slice view using right-click-and-drag when the ROI fills the slice view. Maybe the ROI should not respond to right-click inside the ROI, only at the boundary.
- [x] By default, left-click on a handle should jump slice views to that position (the same way as control points; configurable with event translations) (https://github.com/Slicer/Slicer/pull/6153)
- [x] Make the interaction arrows a bit more subtle. ROIs can be quite small and those arrows can be relatively very large. Maybe make it possible to only show the sphere handles and not the arrows.
- See task below ~~Prevent the arrows crossing the ROI boundary: it is a bit confusing that when the ROI is small then the interaction arrows cross the interaction handles on the sides. A possible solution could be to shorten the arrows for small ROIs so that its maximum size would be capped at 50-70% of the ROI box radius (it would be just shortened when the ROI is small, but it would not grow longer than the current size).~~
- [x] Add separate scale parameter for interaction handles.
- [x] Bounds of the ROI should be the bounds of the ROI box (currently bounds has zero extent along all 3 axes if ROI type is box; if it is bounding box then it has some extent, but it does not include the corners of the box, so it is quite confusing). 
- [x] ROI center is not always visible in slice views. This makes it difficult to translate the entire ROI and it would be better to see the ROI property (label, measurements), too. (https://github.com/Slicer/Slicer/pull/6173)

Low priority:
- [x] Make Get/SetXYZ more consistent with the Annotation ROI node: in annotation ROI node these values are not affected by the parent transform node, so they are in the node's coordinate system, and not in world. RadiusXYZ in markups ROI node is not affected by parent transform node (good), but XYZ value in markups ROI node _is_ affected by parent transform node (not consistent with annotation ROI node).
- [x] Fix volume measurement of transformed ROI: applying a transform with diag(2.0, 2.0, 2.0, 1.0) makes the ROI appear bugger but its volume remains the same. Need to update the measurement to compute true volume. It would be useful to add a GetSizeWorld() method.
- [x] If the ROI is transformed using a rotation transform then ROI size adjustment sliders (Markups module / ROI settings / ... Range sliders) change all the bounds of the ROI. The sliders should probably show and change size in the local coordinate system (without any potential scaling by the parent transform). In the future there might be a "Transformed" flag (similarly to how control point coordinates can be displayed with/without the parent transform applied), but we don't need this dual mode for now.
- [x] Add a flag to enable/disable rotation
- [x] It is odd that there are no control points at all in box mode. Could we store at least the center as a control point?
- [x] If a bounding box type ROI is created and two points are placed then the ROI is not filled (even though it has 0 thickness, it should be filled)
- [x] When moving the mouse over an interaction handle, the mouse cursor and handle color alternates between hand and arrow and selected/unselected color. It always ends up being correct but the flickering is distracting.
- [ ] Interaction is very slow in debug mode. It seems to be due to plane clipping. It couldbe nicer if we could use one clipping filter because this filter has huge overhead when clipping very simple shapes. It could be also faster to use vtkPlaneCutter.
- [ ] When interacting with the ROI in one-up 3D view, the slice representation is still being updated (vtkSlicerROIRepresentation2D::UpdateFromMRML is called and it runs this->ROIWorldToSliceTransformFilter->Update(), which takes a long time)
- [x] It would be probably better if all interaction handles disappear when the ROI is out of the slice plane (now the arrows are always displayed)
- [x] Add a shortcut (Alt+Left-click-and-drag) for symmetric adjustment of handle. This allows making the ROI box thinner without changing its position.
- [x] Can you add an ellipsoid mode? It would help identifying any design issues that may come up in the future when we want to generalize the concept (e.g., create custom ROI widgets). Handles could be probably the same as now. => can be added in ExtraMarkups extension (https://github.com/chir-set/SlicerExtraMarkups/)
- [x] Show node name in views (it could be similar how I enabled label display recently for curves, but in this case the label should be displayed in the center)
- [x] Add measurement plugins (volume, diagonal, maybe xyz diameter)
- [x] When only rotation handles are visible then the arc just hangs in the air. It would be nice to somehow make it connected to the center.
![image](https://user-images.githubusercontent.com/307929/110144045-e5002580-7da5-11eb-8e66-f0faa6496a14.png)

To discuss:
- [x] Would it be possible to add corner handles to slice views? (just for consistency with 3D views)
- [ ] How does the ROI work with non-linear transforms? It should probably work similarly to angle and line markup, so that it would not be warped by the transforms, only the control points/handles would be transformed and they would be connected with straight lines.
- [ ] We could consider initializing the ROI with single-slice thickness. This would facilitate using it for generating 2D-like ROIs (useful for generating training data for object detection AI applications). At the same time, it is easier to adjust bounds of a cubic ROI than expanding of a flat plane.

**Comment by lassoan** [comment]
@Sunderlandkyl it would be great if you could fix the high-priority items because then we could ask people to test this and give us feedback.

**Comment by Sunderlandkyl** [comment]
>Cannot unzoom the slice view using right-click-and-drag when the ROI fills the slice view. Maybe the ROI should not respond to right-click inside the ROI, only at the boundary.

I haven't been able to reproduce this. Does it require a certain visibility option?

**Comment by lassoan** [comment]
> > Cannot unzoom the slice view using right-click-and-drag when the ROI fills the slice view. Maybe the ROI should not respond to right-click inside the ROI, only at the boundary.
> 
> I haven't been able to reproduce this. Does it require a certain visibility option?

This happens with small regions (that has a physically small diameter). For example, if I zoom in to see the small region then the ROI border can be right-clicked from very far from the actual border. If the ROI is small then clicking anywhere in the slice is interpreted as clicking on the border. Try this scene: https://www.dropbox.com/s/qscypclrlmenyb9/2021-02-25-ROI-plane-right-click.mrb?dl=0

Maybe there is something wrong with how the border's click tolerance is computed (it might be computed in physical coordinates instead of display coordinates).

**Comment by Sunderlandkyl** [comment]
RIght, I see it now, thanks!

**Comment by lassoan** [comment]
Flickering is fixed in bc8145b08b5a1ba17bebf811bc35a97414ebc559

**Comment by jamesobutler** [comment]
In the "Advanced" area of the "Display" section in the Markups module, there is the option for "Line Thickness".  This works for vtkMRMLMarkupsLineNode, vtkMRMLMarkupsCurveNode and vtkMRMLMarkupsClosedCurveNode.  

@Sunderlandkyl Is this expected to work for vtkMRMLMarkupsROINode given that it is also made up of lines? Could it be made to work? I'm looking to change the line thickness to change how the ROI is viewed in 2D slice views.

**Comment by Sunderlandkyl** [comment]
It's not currently implemented for ROI, but it should work. I'll take a look at it.

**Comment by lassoan** [comment]
@Sunderlandkyl we are getting close to releasing Slicer5 and it would be great if the majority of the remaining tasks listed in this issue could be addressed. Could you spend some time with this in the next 2-3 weeks (I would estimate that Slicer5 will be released in about a month, and it would be good to have some time for testing the changes)?

**Comment by Sunderlandkyl** [comment]
> has inside-out mode ("Inverse" ROI rendering #1596)

The Markups ROI node currently has options for getting the inside-out planes:
https://github.com/Slicer/Slicer/blob/840e67574758e456c01c08a97b7b13926dff6429/Modules/Loadable/Markups/MRML/vtkMRMLMarkupsROINode.h#L182-L187

I don't see a trivial way to add this to volume rendering. Is there an example somewhere?

**Comment by lassoan** [comment]
The end goal would be to be able to specify for volume rendering to keep or remove what is inside the ROI.

We do what vtkMRMLAnnotationROINode::GetTransformedPlanes did - invert plane normals depending on its inside-out flag. But probably making the volume rendering module call `markupsROI->GetPlanes(planes, markupsROI->GetInsideOut());` would be better, because that is applicable to all ROI shapes. For example, in case of a cropping ellipsoid for volume rendering, the ROI would give the ellipsoid's parameters and the InsideOut flag would be set in the shader and the shader would know how to crop inside/outside an ellipsoid.

**Comment by Sunderlandkyl** [comment]
> ROI center is not always visible in slice views. This makes it difficult to translate the entire ROI and it would be better to see the ROI property (label, measurements), too

@lassoan How does this interact with the SliceProjection property? Should the control point be visibile regardless of SliceProjection?

**Comment by lassoan** [comment]
I think the most intuitive behavior would be to show the center when the corners are visible. This is already implemented and available if the user enables "translation" interaction mode.

The problem is that translation interaction mode also displays arrows, which are useful, but they also makes the view quite cluttered (especially when they are large relative to the ROI size; or when there are multiple ROIs).

As a short-term solution, we could enable translation interaction mode by default and not show the arrows.

As a long-term solution, we probably cannot avoid implementing the concept of "focused" node (I've added a separate ticket about this: https://github.com/Slicer/Slicer/issues/6159). We could change the implementation so that the arrows (or even the interaction points) would only be displayed if the node has the focus. This would help with keeping the views simpler, prevent accidental changes, and would be more similar to how most graphics editing software work.

**Comment by jcfr** [comment]
@Sunderlandkyl @lassoan What do you think of closing this one and creating more specific ones ?

**Comment by lassoan** [comment]
All the important features are implemented, issues are fixed. Performance optimizations, new feature requests, etc. can be tracked in follow-up issues (no need to create them now).
