### ISSUE TITLE
Segmentation editor regression: uneven or interrupted paint strokes -- especially with pen

### ISSUE THREAD

**Issue by fusentasticus** [Slicer/Slicer#5063]
In 4.11.0-2020-07-20, I get the results below when trying to paint: the first is with a pen on a Wacom tablet, the second with mouse. Both result from undersampled mouse tracking apparently, but it's especially bad with the pen! 

![with pen](https://user-images.githubusercontent.com/11786553/88598339-1a39dd80-d037-11ea-97fc-cfc7f897ef49.jpg)
![image](https://user-images.githubusercontent.com/11786553/88598550-86b4dc80-d037-11ea-9051-0aa255252085.png)

## Steps to reproduce

Start Slicer [with all extensions disabled just in case], load the sample CT chest volume, go to Segment Editor, create Segment, choose chest volume, choose paint, and the use pen or mouse.

## Expected behavior

Smooth strokes from gazilions of circle imprints. Paint effect produced smooth strokes in 4.11.0.2020-01-08. 

## Environment
- Slicer version: Slicer-4.11.0-2020-07-20
- Operating system: Windows

**Comment by lassoan** [comment]
@Sunderlandkyl could you check if pen mode works as intended in latest preview release? Does pen&touch mode have to be enabled manually?

**Comment by Sunderlandkyl** [comment]
Downloading latest version to test now. I wonder if it has to do with differences between events in Qt 5.10 and Qt 5.15.

There is still no explicit handling of tablet events in Slicer, they're just interpreted as mouse events. I'm going to take this opportunity to bump up the priority of getting the proper tablet event handling integrated in VTK + Slicer.

**Comment by lassoan** [comment]
This should be at least investigated for Slicer-4.11 and depending on how difficult a fix is, the final resolution may be postponed to later.

**Comment by Sunderlandkyl** [comment]
@fusentasticus I've tested both versions of Slicer, as well as 4.10.2 with a Microsoft Surface Pen, and I don't notice any meaningful difference in paint strokes between the versions.

I don't have a Wacom tablet to test, could you record a short video showing the differences in the paint strokes?

Still working to get the updated tablet events integrated with Slicer, which may or may not solve the issue.

**Comment by fusentasticus** [comment]
Thanks for looking into this.  I have done some more testing myself. On a Dell XPS 15 Windows laptop (with Intel I7, Nvidia graphics) I have *no* problems with either mouse or Wacom. On both devices, I observed FPS in the 3D window of 3D slicer. On the PC (Intel 4-core I5, 24Gb RAM, AMD graphics), I see only up to 7-8 fps when moving mouse. On the XPS, I see up to 28 fps. Unfortunately, I'm going to be away from PC the next couple of weeks. 

So, I'm currently thinking hat 1) the core issue is not tablet use as such, and 2) there's some hardware dependency that somehow is reflected in the FPS.  (I don't presently have the AMD graphics spec on me,) On the laptop, the fps tracks the mouse speed, on the desktop, not very much so.

**Comment by lassoan** [comment]
It's this still a problem in latest Slicer Preview Release?

**Comment by lassoan** [comment]
Please reopen if this is still a problem.

**Comment by lassoan** [comment]
Another user report - and discussion with possible solutions: https://discourse.slicer.org/t/delays-in-paint-function-using-wacom-cintiq22/19952
