### ISSUE TITLE
No nightly package and no nightly extensions for macOS available

### ISSUE THREAD

**Issue by che85** [Slicer/Slicer#5079]
In the past few days, there were new builds created for all platforms other than macOS. Same for all extensions.

For the nightly packages, macOS is displayed but no downloadable package is available.

For the nightly extensions, linux and windows builds are available but macOS is completely missing.

## Steps to reproduce

http://slicer.cdash.org/index.php?project=SlicerPreview&date=2020-08-02

**Comment by lassoan** [comment]
@jcfr @sjh26 Please help. Due to packaging and extension manager errors, we cannot get new features and fixes to our research assistants, who as a result cannot do their work. We are trying to be creative and find various workarounds, but it this is just becoming too hard to manage.

**Comment by sjh26** [comment]
The tests are all going to the 15 minute timeout, which is screwing up the rest of the build:

http://slicer.cdash.org/viewTest.php?buildid=1978035.  I am going to disable testing for now and restart the builds so we can get a package and extensions up today.

**Comment by jcfr** [comment]
Since I was working on the issue #5080 , I manually started the macOS build later than expected.

**Comment by lassoan** [comment]
Thank you!
