### ISSUE TITLE
Configure error: JsonCpp_INCLUDE_DIR does NOT match value used to configure Slicer

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5080]
Many extensions have this new configuration error due to calling this in a module's CMakeLists.txt:

```
find_package(Slicer REQUIRED)
include(${Slicer_USE_FILE})
```

Resulting error message:

```
-- Configuring Loadable module: WorkflowSegmentation [qSlicerWorkflowSegmentationModuleExport.h]
CMake Error at D:/D/P/Slicer-0-build/Slicer-build/SlicerConfig.cmake:681 (message):
  Variable JsonCpp_INCLUDE_DIR defined prior calling 'find_package(Slicer)'
  does NOT match value used to configure Slicer.  It probably means that a
  different JsonCpp_INCLUDE_DIR has been used to configure this project and
  Slicer.

  JsonCpp_INCLUDE_DIR=

  Slicer_JsonCpp_INCLUDE_DIR=D:/D/P/Slicer-0-build/JsonCpp/include
Call Stack (most recent call first):
  D:/D/P/Slicer-0-build/Slicer-build/SlicerConfig.cmake:879 (slicer_config_set_ep)
  SkillAssessment/CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
See also "D:/D/P/S-0-E-b/PerkTutor-build/CMakeFiles/CMakeOutput.log".
See also "D:/D/P/S-0-E-b/PerkTutor-build/CMakeFiles/CMakeError.log".
```

(http://slicer.cdash.org/viewConfigure.php?buildid=1979043)

The error is fixed by removing find_package+include (see [fix in SlicerHeart](https://github.com/SlicerHeart/SlicerHeart/commit/7b81faac7cd723e34cb020914e0ed796be30c1bc)).

It would be better to fix this in Slicer so that there is no need to update extensions and templates.

**Comment by pieper** [comment]
Looks like this was caused when I [turned off the ParameterSerializer](https://github.com/Slicer/Slicer/commit/7c6039021224cf1e9a1d594d9b258ab12e8e6e74).   I'll see if I can reproduce the issue with a local build.

**Comment by pieper** [comment]
I could reproduce the build error, but I didn't find any way to fix it.  Any ideas or suggestions?

**Comment by lassoan** [comment]
Removing these lines from CMakeLists.txt files in subdirectories fixes the issue:

```
find_package(Slicer REQUIRED)
include(${Slicer_USE_FILE})
```

But I don't know why this is necessary and if there is a better way to handle this.

@jcfr do you have any suggestions?

**Comment by pieper** [comment]
Yes, I saw you had made that change in SlicerHeart but I was also looking to see if there was something that could be done at the Slicer level to fix this.

**Comment by lassoan** [comment]
Yes, it would be much better to understand what happened and fix the root cause of the issue.

**Comment by jcfr** [comment]
> Yes, it would be much better to understand what happened and fix the root cause of the issue.

While looking at this, I noticed that VolumeRendering module depends on JsonCpp.
https://github.com/Slicer/Slicer/blob/1a8a34060e491e659c7edd0dc2a7171ca12278ad/CMake/SlicerBlockInstallCMakeProjects.cmake#L48-L54

Look like we may have to call ` slicer_is_loadable_builtin_module_enabled("VolumeRendering" _build_volume_rendering_module) ` in this location:

https://github.com/Slicer/Slicer/blob/1a8a34060e491e659c7edd0dc2a7171ca12278ad/CMake/SlicerCPackBundleFixup.cmake.in#L207-L211

Or we could introduce a variable called `Slicer_USE_JsonCpp`

**Comment by jcfr** [comment]
I found the root cause:
https://github.com/Slicer/SlicerExecutionModel/blob/60e43e92966ea4df957620b8d59954f2bfd8cf8b/SlicerExecutionModelConfig.cmake.in#L149-L151

The variables should be set only if not an empty string, otherwise it prevent over package from looking up JsonCpp

**Comment by pieper** [comment]
Thanks @jcfr ! 👍

**Comment by lassoan** [comment]
This is great, thank you!
