### ISSUE TITLE
 Debug: Run-Time Check Failure #2 - Stack around the variable 'k' was corrupted.

### ISSUE THREAD

**Issue by Hurmean** [Slicer/Slicer#5084]
### VS2019 v142 + QT 5.15
![1596527065(1)](https://user-images.githubusercontent.com/12394658/89267701-27c01a80-d66a-11ea-8b42-b1bc177a7095.png)

**Comment by lassoan** [comment]
Thanks for the report. We can only investigate and fix problems if we can reproduce them. Can you give us instructions for reproducing the issue?

**Comment by Hurmean** [comment]
WIN 10
VS 2019
QT 5.15 msvc2019_64
cmake 3.17.3

cmake-gui sets default except PYTHONQT::OFF

**Comment by Hurmean** [comment]
> Thanks for the report. We can only investigate and fix problems if we can reproduce them. Can you give us instructions for reproducing the issue?

WIN 10
VS 2019
QT 5.15 msvc2019_64
cmake 3.17.3
cmake-gui sets default except PYTHONQT::OFF

**Comment by lassoan** [comment]
What did you do when the issue occurred? Or did it happen during startup?

**Comment by Hurmean** [comment]
> What did you do when the issue occurred? Or did it happen during startup?

yes,it happens during startup

**Comment by lassoan** [comment]
Win10 + VS2019 v142 + QT 5.15 works well on factory machines and many other developer machines. If you can still reproduce the issue by following the [build instructions](https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/windows.html) then let us know.
