### ISSUE TITLE
Crash when displaying animated popup window on MacOS

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5092]
Multiple users reported crash of Slicer 4.11.0-2020-07-27 r29229 (and later) on MacOS Catalina when hovering over the pushpin icon in viewers or threshold slider in Volumes module. More details: https://discourse.slicer.org/t/latest-slicer-preview-release-crashes-randomly-on-macos-catalina/12759

**Comment by lassoan** [comment]
I was able to reproduce this on macOS Mojave (10.14.6), so most likely the issue is a regression in Qt-5.15.

**Comment by jamesobutler** [comment]
@lassoan On Windows I observed the following message in the console when there is animated popup.  It appears to only show the first time the popup is shown. I was hovering over the slice viewers and 3D view pins.
```
UpdateLayeredWindowIndirect failed for ptDst=(1234, 95), size=(231x160), dirty=(231x160 0, 0) (A device attached to the system is not functioning.)
```

**Comment by lassoan** [comment]
Found a way to reproduce the issue almost all the time:
- Load MRHead sample
- Go to volumes module
- Hover over window/level slider (do not click) for a few seconds
- Click and drag the lower value of threshold slider and move to the right quickly

The last two steps should be done fairly quickly. One step right after the other.

**Comment by lassoan** [comment]
> @lassoan On Windows I observed the following message in the console when there is animated popup. It appears to only show the first time the popup is shown. I was hovering over the slice viewer pins and 3D view pins.
> 
> ```
> UpdateLayeredWindowIndirect failed for ptDst=(1234, 95), size=(231x160), dirty=(231x160 0, 0) (A device attached to the system is not functioning.)
> ```

Thank you. I agree that this may be a different manifestation of the same underlying error.

**Comment by lassoan** [comment]
Changing animation mode from scrolling to fade fixed the issue. We can also change the effect duration to make the popup window appear instantaneously. I'll send a pull request to CTK soon.

**Comment by fogelton** [comment]
Did you report this to qt, I have simillar problem but I do not have a reproducable example.

**Comment by lassoan** [comment]
We did not report it to Qt. I searched the web for similar issues and other projects have not reported it, so most likely we did something unusual (and we did not like the animation anyway), so we just removed the animation.

It would be a lot of work to create a minimal example that reproduces the issue, so we did not even attempt to report it to Qt developers.
