### ISSUE TITLE
Warnings at startup: QAccessibleTable::child: Invalid index at: 0 0

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5094]
Several such warnings are logged when starting Slicer:

```
[WARNING][Qt] 11.08.2020 15:44:08 [] (unknown:0) - QAccessibleTable::child: Invalid index at: 0 0
[WARNING][Qt] 11.08.2020 15:44:08 [] (unknown:0) - QAccessibleTable::child: Invalid index at: 0 0
```

See user report at: https://discourse.slicer.org/t/qaccessibletable-warnings-in-preview-release-clean-install/12953

## Environment
- Slicer version: Slicer-4.11.0-2020-08-10
- Operating system: Windows 10

**Comment by sjh26** [comment]
I've seen this as well in my custom apps recently (past week or two) on Windows 10.  Haven't had any luck nailing down the source, but it seems to have appeared without any changes of Slicer or Qt version, making me think it is operating system related.

Windows version w/ bug: 192628.1
Windows version w/o bug: 18363.959
