### ISSUE TITLE
Loading an STL as a segmentation in the Add Data dialog does not correctly read the coordinate system

### ISSUE THREAD

**Issue by sjh26** [Slicer/Slicer#5097]
When loading an STL as a segmentation in the Add Data dialog does not correctly read the coordinate system.  If you load the file as a model, and again as a segmentation, they will not overlap correctly.

## Steps to reproduce

1. Test file (generated in Slicer by export a segment to a surface mesh and saving to STL): https://www.dropbox.com/s/yjk5xd49bbdcies/Segment_1.stl?dl=0

2. Load file twice in Slicer, once as a model, and once as a segmentation

<img width="1280" alt="Screenshot 2020-08-12 18 28 30" src="https://user-images.githubusercontent.com/25040869/90075041-77d25900-dcca-11ea-8092-076701dbed0a.png">

## Expected behavior

The model and the segmentation should be in the same place
## Environment
- Slicer version: Slicer-4.11.0-2020-08-11
- Operating system: Windows 10

**Comment by cpinter** [comment]
Which one is the correct position? I mean before you saved it as STL was it in the position of the model or the segmentation?

**Comment by sjh26** [comment]
The model version is in the correct place.  No trasnforms were applied, this was just done straight from an image.

Image: https://www.dropbox.com/s/5jhxql7qcmak8fx/image.nii?dl=0 .  It should overlap the kneecap.

**Comment by lassoan** [comment]
I've checked the code and plain STL and OBJ readers are used, without checking coordinate system information. qSlicerSegmentationsReader.cxx should be updated to use vtkMRMLModelStorageNode to read the model (that takes care of coordinate system transformations). There is not even necessary to add the storage node to the scene, it can be used as it is done in c:\D\S4\Modules\CLI\MergeModels\MergeModels.cxx

**Comment by sjh26** [comment]
Yes!  Thanks for helping track down the issue, I will get a fix put together.
