### ISSUE TITLE
Crash on macOS in vtkOpenGLRenderer::HaveAppleQueryAllocationBug()

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5099]
Slicer seems to crash on macOS. It is unclear if it is macOS, Qt, or VTK issue, or combination of both.

@che85 most recently found crash is in vtkOpenGLRenderer::HaveAppleQueryAllocationBug().

See complete log at https://gist.github.com/che85/1207be08bae6d3a5e24374d5384ac30f

There may be a [fix](https://github.com/Kitware/VTK/commit/bcddf73c726200531acca87b675681c5cc1617ab) for it in VTK master, so this should be tested after upgrading to latest VTK in Slicer.

## Steps to reproduce

@che85 could you give instructions/script to reproduce this?

## Environment
- Slicer version: Slicer-4.11.0-2020-08-??
- Operating system: macOS 10.15.5

**Comment by pieper** [comment]
I haven't seen this particular crash on mac.

**Comment by lassoan** [comment]
Users have not reported this error recently, maybe fixed by VTK or Qt updates. Closing it now and will reopen if users run into this again.
