### ISSUE TITLE
Modules names are gone in the new Module finder on macOS Catalina

### ISSUE THREAD

**Issue by fepegar** [Slicer/Slicer#5119]
## Steps to reproduce

Just open the module finder. Names are gone, except the selected one.

<img width="960" alt="Screen Shot 2020-08-20 at 10 54 46" src="https://user-images.githubusercontent.com/12688084/90756129-e7040a80-e2d3-11ea-8d7f-565f4d70094c.png">

## Environment
- Slicer version: Slicer-4.11.0-2020-08-18
- Operating system: macOS Catalina 10.15.5

**Comment by fepegar** [comment]
Update: I restarted Slicer and the names are now visible.

**Comment by jamesobutler** [comment]
You probably had changed the style from Dark mode to light?
See https://github.com/Slicer/Slicer/pull/4993#issuecomment-667679276

**Comment by fepegar** [comment]
> You probably had changed the style from Dark mode to light?
See #4993 (comment)

Maybe I opened that window last night and I checked it this morning, I'm not sure. I'll keep an eye on this to see if it happens again and let you know.

**Comment by lassoan** [comment]
Fixed in https://github.com/Slicer/Slicer/commit/2054a88780bf961bf0b0f4b2f7c74275371170f2
