### ISSUE TITLE
Add a feature in Screen Capture to adjust the rendering window size to selected width/height

### ISSUE THREAD

**Issue by muratmaga** [Slicer/Slicer#5122]
Currently screen capture module captures individual frames in the size of the 3D viewer window. 

## Describe the solution you'd like

Our users requested on option to be able to set rendering window size to an arbitrary size so that they can create high-resolution video. 

[A clear and concise description of what you want to happen.]

A field that users can select some predetermined output sizes (e.g., 1920x1200, 1920x1080, 3840x2160 etc) which will be size of the individual output frames saved to disk.

## Describe alternatives you've considered

[A clear and concise description of any alternative solutions or features you've considered.]

## Additional context

[Add any other context or screenshots about the feature request here.]

**Comment by lassoan** [comment]
The feature is available in Animator module in SlicerMorph, therefore I'll close this issue.
