### ISSUE TITLE
Python welcome text not readable in dark mode

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#5137]
What I believe is called the "WelcomeText" for the python console shows up very dark in dark mode (top) but you can see that it's there if you highlight it (bottom)

![image](https://user-images.githubusercontent.com/126077/91218832-a64b2d80-e6e7-11ea-8400-3bb0c7bab814.png)

![image](https://user-images.githubusercontent.com/126077/91218841-ad723b80-e6e7-11ea-8470-2a83330a92e8.png)

## Steps to reproduce

Start slicer and open python console

## Environment
- Slicer version: Slicer-4.11-2020-08-25 build from source
- Operating system:  Mac , 10.15.6

**Comment by fepegar** [comment]
Related: some text not visible in light mode. Tried after removing Slicer.ini and this version:

```ini
[DEBUG][Qt] 28.09.2020 17:15:50 [] (unknown:0) - Slicer version ...........: 4.11.0-2020-09-23 (revision 29388 / 9d27ede) macosx-amd64 - installed release
[DEBUG][Qt] 28.09.2020 17:15:50 [] (unknown:0) - Operating system .........: Mac OS X / 10.15.5 / 19F101 - 64-bit
```

<img width="565" alt="Screen Shot 2020-09-28 at 17 17 49" src="https://user-images.githubusercontent.com/12688084/94459063-bfe00900-01ae-11eb-9dd0-302bf672423d.png">
<img width="571" alt="Screen Shot 2020-09-28 at 17 18 02" src="https://user-images.githubusercontent.com/12688084/94459070-c1113600-01ae-11eb-80c3-b42b18fd0374.png">

**Comment by lassoan** [comment]
Have you restarted Slicer after switching to light mode?

**Comment by fepegar** [comment]
Yes, I just installed it actually. Now I installed the TorchIO extension and can't open at all. What's the procedure for this? New issue and stack trace?

**Comment by lassoan** [comment]
Console text that is already printed is not recolored if you change the color scheme, so that's normal.

If you experience problems related to Python package installation then please create a new issue and describe what you did exactly and what happened (what is that you cannot open at all?).

**Comment by fepegar** [comment]
> If you experience problems related to Python package installation then please create a new issue and describe what you did exactly and what happened (what is that you cannot open at all?).

Ok, I will. Thanks.

> Console text that is already printed is not recolored if you change the color scheme, so that's normal.

Maybe I didn't explain properly.

- My macOS switches automatically between light and dark
- Now, during the day, it's light
- I just installed the latest Preview, opened and found this problem
- I closed Slicer, removed the .ini and tried again, with no luck

I haven't touched the light/dark settings during this.

**Comment by lassoan** [comment]
Qt follows OS dark mode settings by default (you can override this in application settings/appearance/style). You don't need to delete Slicer.ini (it'll just reset all settings to default). I don't know what you mean by "no luck". What did you expect to happen and what happened instead?

**Comment by fepegar** [comment]
> Qt follows OS dark mode settings by default (you can override this in application settings/appearance/style).

I'm happy with this.

> You don't need to delete Slicer.ini (it'll just reset all settings to default).

I deleted the config file because I've changed the Python colors before, so I thought that might have caused this issue.

> I don't know what you mean by "no luck". What did you expect to happen and what happened instead?

Sorry, I just mean that the characters were still not visible. I expected the font color to have better contrast with respect to the background. However, the error traceback was still not clearly visible after closing Slicer, deleting the config file and opening Slicer.

**Comment by lassoan** [comment]
@pieper There have been related fixes recently. Can you check if this is still an issue in the latest preview release?

**Comment by fepegar** [comment]
I can see the welcome and error messages on the latest macOS preview release.

**Comment by fepegar** [comment]
Works also in dark mode.

**Comment by lassoan** [comment]
Thank you for testing, I close this issue then.
