### ISSUE TITLE
Subject hierarchy crashes due to Plugin named ' "Folder" ' cannot be found

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5169]
In several tests on MacOS the application crashes and the last log messages are:

```
qSlicerSubjectHierarchyAbstractPlugin *qSlicerSubjectHierarchyPluginHandler::pluginByName(QString) : Plugin named ' "Folder" ' cannot be found
error: [/Volumes/D/P/S-0-build/Slicer-build/bin/qSlicerModelsModuleCxxTests] exit abnormally - Report the problem.
```

http://slicer.cdash.org/testDetails.php?test=10110020&build=2003622
http://slicer.cdash.org/testDetails.php?test=10110021&build=2003622
http://slicer.cdash.org/testDetails.php?test=10110023&build=2003622
http://slicer.cdash.org/testDetails.php?test=10120750&build=2003622

**Comment by cpinter** [comment]
The error message might be related to the crash, because on Windows neither the Folder plugin error nor the crash does not occur.

Another finding is that the issues started on August 23, and given that the other SH related commit (https://github.com/Slicer/Slicer/commit/8d002ac1158b250cc49b81189cc5f3ce44e88676) is unlikely to cause something like this, the culprit is possibly this one:
https://github.com/Slicer/Slicer/commit/4c6e770e21e9bd2b052ef62d50aa83126603cadf

**Comment by che85** [comment]
It seems that the core plugins are not loaded when running the test. The only registered sh plugin is the models sh plugin. 

When registering the folder sh plugin before registering the models plugin, the test succeeds

```
diff --git a/Modules/Loadable/Models/qSlicerModelsModule.cxx b/Modules/Loadable/Models/qSlicerModelsModule.cxx
index 5a61c0bf9..221c490fd 100644
--- a/Modules/Loadable/Models/qSlicerModelsModule.cxx
+++ b/Modules/Loadable/Models/qSlicerModelsModule.cxx
@@ -40,6 +40,8 @@
 // SubjectHierarchy Plugins includes
 #include "qSlicerSubjectHierarchyPluginHandler.h"
 #include "qSlicerSubjectHierarchyModelsPlugin.h"
+#include "qSlicerSubjectHierarchyFolderPlugin.h"
+
 
 //-----------------------------------------------------------------------------
 /// \ingroup Slicer_QtModules_Models
@@ -154,6 +156,9 @@ void qSlicerModelsModule::setup()
       QStringList() << "vtkMRMLModelNode", true, this));
     }
 
+  qSlicerSubjectHierarchyPluginHandler::instance()->registerPlugin(
+    new qSlicerSubjectHierarchyFolderPlugin());
+
   // Register Subject Hierarchy core plugins
   qSlicerSubjectHierarchyPluginHandler::instance()->registerPlugin(new qSlicerSubjectHierarchyModelsPlugin());
 }
```

```
herzc@f01898442662 ~/D/S/Slicer-build> ./Slicer --launch bin/qSlicerModelsModuleCxxTests 
Available tests:
  0. qSlicerModelsModuleWidgetTest
  1. qSlicerModelsModuleWidgetTest1
  2. qSlicerModelsModuleWidgetTestScene
  3. vtkSlicerModelsLogicAddFileTest
To run a test, enter the test number: 0
********* Start testing of qSlicerModelsModuleWidgetTester *********
Config: Using QtTest library 5.15.0, Qt 5.15.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 11.0.3 (clang-1103.0.32.62) (Apple))
PASS   : qSlicerModelsModuleWidgetTester::initTestCase()
Info: In /Users/herzc/sources/cpp/Slicer/Modules/Loadable/Models/Testing/Cxx/qSlicerModelsModuleWidgetTest.cxx, line 80
Expecting warning message(s)...

Generic Warning: In /Users/herzc/sources/cpp/Slicer/Base/Logic/vtkSlicerApplicationLogic.cxx, line 873
filePath is an empty string !

Info: In /Users/herzc/sources/cpp/Slicer/Modules/Loadable/Models/Testing/Cxx/qSlicerModelsModuleWidgetTest.cxx, line 82
Expected warning message(s) successfully received

QSYSTEM: qSlicerModelsModuleWidgetTester::testClearCurrentNode() virtual double qSlicerSubjectHierarchyFolderPlugin::canOwnSubjectHierarchyItem(vtkIdType) const : Failed to access subject hierarchy node
QSYSTEM: qSlicerModelsModuleWidgetTester::testClearCurrentNode() virtual void qMRMLSubjectHierarchyTreeView::setCurrentNode(vtkMRMLNode *) : Unable to find subject hierarchy item by data node  left
PASS   : qSlicerModelsModuleWidgetTester::testClearCurrentNode()
PASS   : qSlicerModelsModuleWidgetTester::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 281ms
********* Finished testing of qSlicerModelsModuleWidgetTester *********
vtkDebugLeaks has found no leaks.
```

Does it have to do something with the testing environment? 

When starting a Slicer instance, all core plugins are loaded. So I don't think that the crashes are caused by this error, but I am not sure.

**Comment by cpinter** [comment]
Thanks for investigating this! It makes things easier that the folder plugin error and the crash in the test are related.

The folder plugin is supposed to be registered here:
https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.cxx#L126

What I'd do is put a breakpoint at the line just ablve with [this revision](https://github.com/Slicer/Slicer/commit/d343e2dc42551efefac0715fd60c58823e8bb06a) built (right before the test started failing), and see where is it called. And then see why in the latest it isn't.

**Comment by lassoan** [comment]
The problem has been recently fixed. Tests on macOS don't fail due to this error anymore.
