### ISSUE TITLE
Calling vtkMRMLSliceViewInteractorStyle::SetActionEnabled systematically disable SetCursorPosition 

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5175]
Variable `EnableCursorUpdate` should be updated only if the corresponding action mask is specified

https://github.com/Slicer/Slicer/blob/66f8ecac15a861ff9d480e4a54003aaf69d6a317/Libs/MRML/DisplayableManager/vtkMRMLSliceViewInteractorStyle.cxx#L151-L168

## Steps to reproduce

Copy paste the following in the python interactor:

```
sliceWidget = slicer.app.layoutManager().sliceWidget("Red")
sliceWidget.sliceView().interactorStyle().SetActionEnabled(slicer.vtkMRMLSliceViewInteractorStyle.Blend, False)
```

## Expected behavior

Since only `Blend` is expected to be disabled, the DataProbe is still  expected to be updated when moving the mouse of the `Red` slice viewer.

## Workaround

Re-enable `SetCursorPosition` last after updating other mode:

```
sliceWidget = slicer.app.layoutManager().sliceWidget("Red")
sliceWidget.sliceView().interactorStyle().SetActionEnabled(slicer.vtkMRMLSliceViewInteractorStyle.Blend, False)
sliceWidget.sliceView().interactorStyle().SetActionEnabled(slicer.vtkMRMLSliceViewInteractorStyle.SetCursorPosition, True)
```

**Comment by lassoan** [comment]
This issue has been fixed.

**Comment by jcfr** [comment]
For future reference, see https://github.com/Slicer/Slicer/commit/cc84a82193a60694e25e1addd92bb15143cd7a7e and https://discourse.slicer.org/t/how-to-disable-right-click-zoom-function-individually/18029/2
