### ISSUE TITLE
Camera nodes seem to proliferate on loading scene

### ISSUE THREAD

**Issue by hherhold** [Slicer/Slicer#5181]
After working with some scene files for a while, changing views, using dual 3D, loading and reloading scenes, etc, I've noticed the number of camera nodes increases. Many of these nodes have the same name, which results in a half dozen "Camera", 3 or 4 "Camera_1", a couple "Camera_2", one or two "Camera_3", and so on. This is kind of annoying when I use the Cameras module to switch cameras between views or use the same camera for multiple views, as searching through the list of cameras is kind of useless when so many have the same name.

The workaround is just to keep cycling through cameras, so it's more of an annoyance than something like a data loss issue.

## Steps to reproduce

1. Start Slicer.
2. Load in MRHead (or some other data).
3. Save the scene.
4. Quit slicer.
5. Start slicer.
6. Go to cameras module. Note that there is a single camera.
7. Load in the scene you just created.
8. In Cameras module, note multiple cameras with duplicate names. 

## Expected behavior

The cameras in the scene file should be loaded in and replace any existing cameras. It seems that the "Add Data" is *truly* just adding in the existing cameras. 

Actually, in typing this up, I realize that you could argue that Adding data is EXACTLY what is expected, and this behavior should be preserved. I would say then that it would be nice to have a button in the cameras module to remove duplicate cameras.

(If this "remove duplicates" thing is an acceptable fix, I'm happy to take a stab at it.)

## Environment
- Slicer version: Slicer-4.11.0-2020-09-01
- Operating system: MacOS 10.15.5

**Comment by lassoan** [comment]
This should be fixed by https://github.com/Slicer/Slicer/commit/e78f557cd0cc70587e6dc01fa4983447462b0db6
