### ISSUE TITLE
vtkSlicerMarkupsWidgetRepresentation3D not exposed in python

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#5182]
`markupsDisplayableManager.GetWidget(fiducialsNode.GetDisplayNode())` returns `MRMLDisplayableManagerPython.vtkMRMLAbstractWidget` not `vtkSlicerMarkupsWidgetRepresentation3D` meaning that you can't call any of the subclass methods.

## Steps to reproduce

Fresh scene, add a fiducial, then paste this in console:
```
fiducialsNode = slicer.util.getNode('F')
layoutManager = slicer.app.layoutManager()
threeDWidget = layoutManager.threeDWidget(0)
threeDView = threeDWidget.threeDView()
className = "vtkMRMLMarkupsDisplayableManager"
markupsDisplayableManager = threeDView.displayableManagerByClassName(className)
fiducialsWidget =  markupsDisplayableManager.GetWidget(fiducialsNode.GetDisplayNode())
fiducialsRepresentation =  fiducialsWidget.GetRepresentation()

print(fiducialsWidget.GetClassName())
print(fiducialsRepresentation.GetClassName())
print(fiducialsWidget.__repr__())
print(fiducialsRepresentation.__repr__())

assert fiducialsWidget.GetClassName() in fiducialsWidget.__repr__()
assert fiducialsRepresentation.GetClassName() in fiducialsRepresentation.__repr__()
```
## Expected behavior

The widget and representations types should match their class names. 

## Environment
- Slicer version: Slicer-4.11-09-08
- Operating system: Mac + 10.15

**Comment by lassoan** [comment]
Only standard "MRML", "Logic", "Widgets" libraries are imported into `slicer` namespace. To access classes in other libraries, such as widget representations in vtkSlicerMarkupsModuleVTKWidgets, you need to import them manually. Without that, the Python wrapper cannot get to the exact class, but gets stuck somewhere higher in the hierarchy.

`import vtkSlicerMarkupsModuleVTKWidgetsPython` before you try to access the class will fix the problem.

I guess the main question is if these classes are part of the official Python API of Slicer. If they are, then probably it would be better to import them into the Slicer namespace. @jcfr what do you think?

**Comment by pieper** [comment]
Yes, importing is a good workaround 👍 

If they are part of the public C++ API I would say yes, they should be imported to be consistent with the rest of the application.

**Comment by jcfr** [comment]
Makes sense. If not alreay done, I will submit a PR tmrw.

**Comment by jcfr** [comment]
Coincidentally, I am facing a similar issue  in a custom  application where I need to toggle the visibility of the interactive handle in a specific view.

Going to land a PR shortly.

**Comment by jcfr** [comment]
Worth noting that with VTK9 ... while the class are not available in the `slicer` package, the snippet above works correctly.
This is because dependency are automatically imported and VTKWidget  is a dependency of MRMLDisplayableManager.

When trying the snippet above in a Slicer build against VTK8, it fails as expected.
