### ISSUE TITLE
Curve Maker

### ISSUE THREAD

**Issue by spujol** [Slicer/Slicer#5202]
The Curve Maker module does not overlay curvature values on the curve model.
(Slicer4.11-2020-09-20 on MacOSX 10.14.6)

<img width="1680" alt="Screen Shot 2020-09-24 at 8 49 42 PM" src="https://user-images.githubusercontent.com/1847492/94187159-dd0f9180-fea7-11ea-87f8-732400b2c497.png">

**Comment by lassoan** [comment]
I think the specific error in CurveMaker extension has been already reported (https://github.com/tokjun/CurveMaker/issues/10) and fixed (https://github.com/tokjun/CurveMaker/issues/10), just has not been integrated. You can comment on these issues or write to Junichi to integrate (should be a click of a button).

Note that CurveMaker is being surpassed by Markups curve. I think the last feature that CurveMaker had but markups curve did not was curvature display, but @cpinter is currently working on that and it is expected to be ready in 1-2 weeks.

**Comment by lassoan** [comment]
Markups curves can now compute and display curvature:

![image](https://user-images.githubusercontent.com/307929/108159874-ec40e700-70b5-11eb-8966-76a3ea9b5fa0.png)
