### ISSUE TITLE
vtkOutputWindow appears on close

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#5204]
There is a vtkOutputWindow pop-up appearing on close of Slicer.  I caught the pop-up in a screenshot as seen below
![image](https://user-images.githubusercontent.com/15837524/94819386-2fcbda80-03cd-11eb-89e3-34511a7fcbf5.png)
It appears to be related to vtkMRMLScene::Clear. This seems to match the change in https://github.com/Slicer/Slicer/commit/3b7330634fa66b41c62b1db0ab40091f8b3fd967. It was not an issue in Slicer-4.11.0-2020-09-12.

## Steps to reproduce

Open Slicer, close Slicer and observe vtkOutputWindow pop-up that flashes open and closed.

## Expected behavior

No vtkOutputWindow to appear on close.

## Environment
- Slicer version: Slicer-4.11.0-2020-09-23
- Slicer version: Slicer-4.11.0-2020-09-17
- Operating system: Windows

**Comment by lassoan** [comment]
I just added this info message to be able to better track in the logs what the user does, but somehow we should disable this when the application is shutting down.

**Comment by jamesobutler** [comment]
What was a little weird was that there wasn't a typical window for like vtkDebugLeaks. It was just the vtkOutputWindow.  I guess this is considered an "INFO" level VTK output message and therefore not an "ERROR" type that would be displayed in the vtkDebugLeaks window.

**Comment by jcfr** [comment]
I suspect the message are displayed after the logging handler have been destroyed.

Are configured here:
https://github.com/Slicer/Slicer/blob/87ca5d3378b1fe1bb4eced078887fcbfc1cbd9c2/Base/QTGUI/qSlicerApplication.cxx#L234-L250

The error log model is managed using a [QSharedPointer](https://doc.qt.io/qt-5/qsharedpointer.html#dtor.QSharedPointer) a here:
https://github.com/Slicer/Slicer/blob/87ca5d3378b1fe1bb4eced078887fcbfc1cbd9c2/Base/QTCore/qSlicerCoreApplication_p.h#L157-L158
