### ISSUE TITLE
Can't open Slicer after installing TorchIO extension

### ISSUE THREAD

**Issue by fepegar** [Slicer/Slicer#5205]
Can't open Slicer after installing TorchIO extension

## Steps to reproduce

1. Install fresh Slicer
2. Install `TorchIO` extension using the Extensions Manager (despite https://github.com/Slicer/Slicer/issues/5118)
3. Restart Slicer
4. Open `TorchIO Transforms` module. Some Python packages are installed
5. Close Slicer
6. I can't open Slicer anymore. Stack trace attached

[slicer_log.txt](https://github.com/Slicer/Slicer/files/5293883/slicer_log.txt)

## Expected behavior

Slicer starts normally.

## Environment
- Slicer version: 4.11.0-2020-09-23
- Operating system: macOS Catalina 10.15.5

**Comment by jamesobutler** [comment]
It appears torchio is requiring SimpleITK < 2 as seen [here](https://github.com/fepegar/torchio/blob/master/setup.py#L20).  The latest Slicer is using SimpleITK 2.0 (2.0rc3 to be exact though this can be updated to the official 2.0.0 tag now that it is out). During the install process is it uninstalling the current SimpleITK to then downgrade? If it attempts to install SimpleITK 1.2.4 from pypi that is built with ITK 4.13 while Slicer is using ITK 5.1.1.

**Comment by fepegar** [comment]
Thanks, @jamesobutler. That's probably the problem. I'll give priority to https://github.com/fepegar/torchio/issues/318 and close this when it works.

**Comment by lassoan** [comment]
Thanks @jamesobutler for the quick investigation and @fepegar for working on a fix. I'll close this issue here, as we don't expect to have any changes in Slicer core.
