### ISSUE TITLE
Slicer 4.11.0-2020-09-28 does not start successfully

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#5208]
When I start Slicer I get the following errors on startup. @jcfr This is likely due to changes made in 26f1f47a8aeb5905459376f9a4948716541d21b1.
![image](https://user-images.githubusercontent.com/15837524/94573373-07fb3c00-0240-11eb-8c9a-6cd985450927.png)
![image](https://user-images.githubusercontent.com/15837524/94573394-0c275980-0240-11eb-8eb9-c237dc19f4b6.png)
![image](https://user-images.githubusercontent.com/15837524/94573409-0f224a00-0240-11eb-8628-02f7b67b6cd9.png)
![image](https://user-images.githubusercontent.com/15837524/94573421-121d3a80-0240-11eb-8913-0c1e382f9b08.png)

## Environment
- Slicer version: Slicer-4.11.0-2020-09-28
- Operating system: Windows

**Comment by jamesobutler** [comment]
There had previously been a commit related to the QmlModels stuff that had to be reverted because it also had broken Windows packaging. See https://github.com/Slicer/Slicer/commit/7da2ff7067218b28111f3c4ea1d6ad76147e0175.

**Comment by jcfr** [comment]
> QmlModels stuff that had to be reverted because it also had broken Windows packaging

I will have a look after my current meeting and sort this out
