### ISSUE TITLE
 VTK 9: Surface smoothing prevent segments from being shown in 3D 

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5223]
## Steps to reproduce

* Build setting Slicer_VTK_MAJOR_VERSION to 9
* Create Segment
* Click "Show 3D"

## Expected behavior

Segment surface should visible in 3D

Disabling surface smoothing allows the surface to be visible

## Environment
- Slicer version: https://github.com/Slicer/Slicer/commit/c658b7b428a37d6f4e925664099ee30fd4ca408c
- Operating system: All

**Comment by sjh26** [comment]
So, the 3D representation is actually present and visible, but has been shrunk down by the smoothing.

1. Create a segment
2.  Click "Show 3D"
3. Re-center 3D view
4. Zoooooooooooooooom in very close, and you will see the segment model



Pure vtk python code to reproduce the shrinking:
```` python
reader = vtk.vtkPolyDataReader()
reader.SetFileName('/path/to/Sphere.vtk')
reader.Update()

smoothingFilter = vtk.vtkWindowedSincPolyDataFilter()
smoothingFilter.SetInputData(reader.GetOutput())
smoothingFilter.SetNumberOfIterations(10)
smoothingFactor = 0.5
passBand = pow(10.0, -4.0 * smoothingFactor)
smoothingFilter.SetPassBand(passBand)
smoothingFilter.BoundarySmoothingOff()
smoothingFilter.FeatureEdgeSmoothingOff()
smoothingFilter.NonManifoldSmoothingOn()
smoothingFilter.NormalizeCoordinatesOn()
smoothingFilter.Update()

writer = vtk.vtkPolyDataWriter()
writer.SetFileName('/path/to/Sphere-smooth.vtk')
writer.SetInputData(smoothingFilter.GetOutput())
writer.Update()
````

When run through Slicer VTK8 python, the sphere remains the same size

When run through Slicer VTK9 python, we see the shrinking

**Comment by jcfr** [comment]
### vtkWindowedSincPolyDataFilter changes

* [changes](https://github.com/Slicer/VTK/commits/slicer-v9.0.20201111-733234c785/Filters/Core/vtkWindowedSincPolyDataFilter.cxx) to `vtkWindowedSincPolyDataFilter.cxx` in VTK9 branch `slicer-v9.0.20201111-733234c785` used in Slicer
* [changes](https://github.com/Kitware/VTK/commits/master/Filters/Core/vtkWindowedSincPolyDataFilter.cxx) to `vtkWindowedSincPolyDataFilter.cxx` in VTK9 master
* [changes](https://github.com/Slicer/VTK/commits/slicer-v8.2.0-2018-10-02-74d9488523/Filters/Core/vtkWindowedSincPolyDataFilter.cxx) in VTK8 branch `slicer-v8.2.0-2018-10-02-74d9488523` used in Slicer.

Since there is no changes to the filter between the VTK9 version used in Slicer and the current master, listed below are the additional commits relative to the VTK8 version used in Slicer:

* [5f2544d193](https://github.com/Kitware/VTK/commit/5f2544d193) - Reworked filter for performance and reduced memory usage.
* [252d8c8933](https://github.com/Kitware/VTK/commit/252d8c8933) - Fixed some easy cases of clang-tidy bugprone-reserved-identifier
* [bd6903ebd9](https://github.com/Kitware/VTK/commit/bd6903ebd9) - Corrected some slightly-wrong (70-90 char long) function separator comments
* [ac76fe1636](https://github.com/Kitware/VTK/commit/ac76fe1636) - clang-format: reformat using clang-format-8
* [3add3bc930](https://github.com/Kitware/VTK/commit/3add3bc930) - clang-format: sort header include statements 
* [be39b25111](https://github.com/Kitware/VTK/commit/be39b25111) - vtkCellArray redesign to enable random access.

**Comment by jcfr** [comment]
I confirm that after reverting "[5f2544d193](https://github.com/Kitware/VTK/commit/5f2544d193) - Reworked filter for performance and reduced memory usage", the issue is not reproducible.

**Comment by jcfr** [comment]
I suspect this is a related issue: 
* [vtk#18058](https://gitlab.kitware.com/vtk/vtk/-/issues/18058) vtkWindowedSincPolyDataFilter::NormalizeCoordinates issue

**Comment by jcfr** [comment]
This is indeed related to the same issue, commenting the following line prevent the issue from happening:

https://github.com/Slicer/Slicer/blob/19bf24de4ed7447c5d2b7b49ecc73dd4cfb66a83/Libs/vtkSegmentationCore/vtkBinaryLabelmapToClosedSurfaceConversionRule.cxx#L352

**Comment by jcfr** [comment]
Waiting the issue is addressed upstream, I will revert the problematic change in the Slicer/VTK fork.

**Comment by lassoan** [comment]
Great progress, thank you @jcfr. Hopefully Will is going to fix this soon, as the performance improvements in this filter make a big difference in segmentation when 3D view is enabled.

**Comment by jcfr** [comment]
Thanks to @wschroed, issue has been fixed in https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7569, I will take care of integrating the change in Slicer/VTK shortly.
