### ISSUE TITLE
Fail on Slicer itk when build module

### ISSUE THREAD

**Issue by MarcosSoares10** [Slicer/Slicer#5240]
When i try to build my module i got this error:

`itkConnectedThresholdImageFilter.hxx:298: undefined reference to itk::operator<<(std::ostream&, itk::ConnectedThresholdImageFilterEnums::Connectivity)`

## Steps to reproduce

I just added it on my code:

```
#include "itkConnectedThresholdImageFilter.h"
typedef itk::ConnectedThresholdImageFilter<MaskImageType, MaskImageType> ConnectedFilterType;
typename ConnectedFilterType::Pointer ccFilter;
ccFilter = ConnectedFilterType::New();
```

## Environment
- Slicer version: Slicer-4.11.20200930-0000-00-00
- Operating system:  Linux
![itkfail](https://user-images.githubusercontent.com/15058981/95657214-9184f680-0ae9-11eb-94a4-3603ee676dee.png)
 UBUNTU 20
- QT 5.12

**Comment by lassoan** [comment]
See an example of how ConnectedThresholdImageFilter can be used with recent ITK versions here: https://github.com/Slicer/Slicer/blob/master/Libs/vtkITK/vtkITKWandImageFilter.cxx

Please post further questions about how to use Slicer in [Development category on the Slicer forum](https://discourse.slicer.org/c/dev/5).
