### ISSUE TITLE
Cannot create quantitative view on macOS Catalina

### ISSUE THREAD

**Issue by timthirion** [Slicer/Slicer#5242]
Slicer fails to create an OpenGL context for quantitative views.

## Steps to reproduce

1. Start Slicer
2. Choose any quantitative view, for example, "Conventional Quantitative" => "Standard"
3. The quantitative view will be grey and the command line will report an error that the OpenGL context could not be created.

<img width="1298" alt="Screen Shot 2020-10-12 at 11 48 02 AM" src="https://user-images.githubusercontent.com/1335089/95766344-240bce00-0c81-11eb-9381-73764cfdaa1d.png">

## Expected behavior

The quantitative view should be available.

## Environment
- Slicer version: commit 1a8a34060e
- Operating system: macOS Catalina 10.15.6

**Comment by lassoan** [comment]
Is it a custom build? Does the latest stable version (Slicer-4.11.20200930) work?

Note that we are removing the legacy JavaScript-based charts infrastructure before Slicer 5 release and only keep the much more capable VTK-based Plots module (and associated "interactive" quantitative views) - see #4904.

**Comment by timthirion** [comment]
Yes, this was from a custom build. I checked the latest stable version and it doesn't have the issue, so we could close this.

Any idea why a custom build would exhibit this behavior but the packaged version doesn't?

**Comment by lassoan** [comment]
It is most likely what Qt version you use and how you build it. This legacy "Charts" infrastructure in Slicer used JavaScript in a QWebEngine widget, and QWebEngine (wraps the entire Chromium engine, which is essentially an operating system).

Is there a particular reason you are still using Charts instead of Plots?

**Comment by timthirion** [comment]
No, no reason. I was experimenting with some initial custom development and ran into this issue. I can use Plots moving forward.

**Comment by pieper** [comment]
My local mac builds also have this `icu` problem with any qSlicerWebWidget (it cropped up a few years ago when either Qt or MacOS changed). It's a bit annoying but has never really been a show stopper since the factory builds are fine.

**Comment by sjh26** [comment]
Possible match on issue:

https://bugreports.qt.io/browse/QTBUG-85576?focusedCommentId=519859&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel

**Comment by pieper** [comment]
Very interesting.  Do you have any idea what `DYLD_FRAMEWORK_PATH` should be set to?

There is a file `/usr/local/Cellar/qt/5.15.0/lib/QtWebEngineCore.framework/Resources/icudtl.dat`, which I assume is the one that Qt is looking for, but I didn't find any path that made a difference, e.g. I tried this:

`DYLD_FRAMEWORK_PATH=/usr/local/Cellar/qt/5.15.0/lib/QtWebEngineCore.framework/Resources ./Slicer-build/Slicer`

**Comment by sjh26** [comment]
I think it needs to be unset, bot set to a specific path.

**Comment by pieper** [comment]
It's already not set, so it seems Qt finds a system icu file.  In this case I was hoping that setting the correct path would resolve the issue, but no luck.  It's not a high priority since the Slicer release builds work, just an annoyance that I was hoping we had a workaround for.
