### ISSUE TITLE
Crash when clicking DICOM Retrieve with no selection

### ISSUE THREAD

**Issue by xriobe** [Slicer/Slicer#5244]
Slicer crashes in the DICOM Query/Retrieve window if we click on Retrieve without selecting data.

## Steps to reproduce

- launch Slicer
- load DICOM module
- click on DICOM networking
- check Storage listener (optional)
- click on Query and retrieve
- use MedicalConnections server (default one but same with others)
- click on Query (you can filter the date to make it quick)
-> some patients should appear on the list
- do not select any and click on Retrieve
=> Slicer crash

![image](https://user-images.githubusercontent.com/66792993/95851822-1757aa80-0d53-11eb-9f7e-1577dfcc1634.png)

## Expected behavior

At least nothing happens but I can suggest 2 behaviors:
- the Retrieve button is disabled if nothing is selected in the data list
- a popup message indicating that nothing is selected

## Environment
- Slicer version: Slicer-4.11.20200930 (Downloaded)
- Operating system: Ubuntu 20.04 LTS

**Comment by pieper** [comment]
Thanks for reporting this, I was able to reproduce and will fix it in CTK.

Here's a fix PR: https://github.com/commontk/CTK/pull/991
