### ISSUE TITLE
Markups cannot be picked after VTK9 upgrade

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5250]
In some situations, markups fiducials cannot be picked (and their labels are not displayed). Sometimes changing the window size or changing zoom factor makes them pickable.

Setting opacity to 0.99 or changing to crosshair glyph fixes the issue, so it seems that the markups occlude themselves. vtkSelectVisiblePoints has a tolerance value, which should ensure that a glyph cannot cause the point detected as occluded, but maybe something has changed around that in VTK9. Maybe the real-world tolerance computation is impacted by changes in some automatic internal rescaling of coordinates (https://discourse.vtk.org/t/documentation-for-vertexmc-normalmc-mcdcmatrix-mvcmatrix/1883/3; history of vtkOpenGLPolyDataMapper.h contains a few more changes that might be related).

## Steps to reproduce

Type this into the Python console:

```python
import numpy as np
pts = np.array([
    [ 22.08201981, -23.33771133,  20.25755501],
    [ 22.24702835, -31.33755684,  21.34285164],
    [ 21.05020905, -33.57769394,  20.82586288],
    [ 19.80578232, -38.49482346,  21.96247864],
    [ 18.11996651, -39.62874985,  20.58876419],
    [ 15.6773119 , -43.51329041,  20.84062958],
    [ 14.88829422, -45.93460083,  22.75982285],
    [ 13.19761467, -49.92071915,  24.98643875],
    [ 11.26348495, -51.92196655,  24.92158699],
    ])

ptsNode = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsFiducialNode")
slicer.util.updateMarkupsControlPointsFromArray(ptsNode, pts)
slicer.util.resetThreeDViews()  # to reset the box size
```

Point labels are not displayed and points cannot be clicked.

If opacity of the markups node is set to 0.99 or glyph type is set to crosshair then the points become pickable (and labels appear) again.

## Expected behavior

Markups points should be pickable if they are not occluded.

## Environment
- Slicer version: Slicer-4.??.?-YYYY-MM-DD
- Operating system: Windows / Linux / Mac + which version

**Comment by jcfr** [comment]
@sankhesh  I am wondering if issue related to #5220 is also causing this issue.

**Comment by sankhesh** [comment]
@jcfr I am not sure. I've started looking into #5220. I'll post back once I have something to report.
