### ISSUE TITLE
Slicer fails to start on default Ubuntu 20.04 configuration

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5251]
Slicer fails to start and displays cryptic message on default Ubuntu 20.04 configuration, due to missing xinerama plugin.
See more information here: https://discourse.slicer.org/t/cant-start-latest-stable-on-ubuntu-20-04/14029

**Comment by sjh26** [comment]
Additional instructions added to installation: https://slicer.readthedocs.io/en/latest/user_guide/getting_started.html#linux to help address this.

Additional options for communicating install instructions:

- Add check to launcher
    - Detect failed start and show message
- **Add text / warning to download.slicer.org for linux**

**Comment by sjh26** [comment]
I will add the link to the download site, and then close.  Will create a new issue for adding the check to the launcher.

**Comment by jamesobutler** [comment]
@sjh26 added the link to the download site in https://github.com/Slicer/slicer.org/commit/0cd0fc7a75953f16fbd29f8ceb0ea212c012c337.
![image](https://user-images.githubusercontent.com/15837524/172486931-6ead31aa-afdb-42fc-84c7-266e36e3d364.png)

@sjh26 Based on your previous comment, should this issue be closed and a new issue created for adding the check to the launcher?

**Comment by jcfr** [comment]
Closing. A specific issue discussing approaches for implementing checks has been created.
