### ISSUE TITLE
Demon Registration (BRAINS) and Vector Demon Registration (BRAINS) no longer available in 4.11

### ISSUE THREAD

**Issue by keith272** [Slicer/Slicer#5255]
In Slicer 4.10.2, Demon Registration (BRAINS) and Vector Demon Registration (BRAINS) were available under Registration > Specialized, but have disappeared in Slicer 4.11. I haven't seen any mention of their removal so perhaps it is actually a bug.

**Comment by jamesobutler** [comment]
@hjmjohnson, I believe these were removed on purpose in 39054218c3a6bffb0e0e9adffd4c7a515f2f08a2. Is that correct?

**Comment by hjmjohnson** [comment]
Yes.  Those tools were not maintained, and we have no record of anyone using them for many many years.

**Comment by jamesobutler** [comment]
For clarity a second user was also looking for Demons Registration (BRAINS) in the latest Slicer version which was posted about in #5333. Unclear if the module was previously being used or if there was a different tool that ultimately worked for their use case.

**Comment by lassoan** [comment]
Now ANTS registration is available in Slicer (via SlicerANTS extension), which should be sufficient. Especially since BRAINS, Elastix, Plastimatch, and other registration modules are available, too.
