### ISSUE TITLE
cmake could not find sqlite when build from source and Slicer_USE_SYSTEM_sqlite=ON

### ISSUE THREAD

**Issue by hubutui** [Slicer/Slicer#5264]
According to https://github.com/Slicer/Slicer/blob/decb14c0bacd2f1c763c736e26302ca97c8c9678/CMakeLists.txt#L1
the minimum cmake version is 3.13.4. And according to https://github.com/Slicer/Slicer/blob/decb14c0bacd2f1c763c736e26302ca97c8c9678/SuperBuild/External_sqlite.cmake#L10-L14
when `Slicer_USE_SYSTEM_sqlite=ON`, cmake will try to find sqlite. However, according to [cmake's doc](https://cmake.org/cmake/help/v3.14/module/FindSQLite3.html), with cmake 3.14, we could simply write:
```
find_package(SQLite3 REQUIRED)
```
Maybe we could update `cmake_minimum_required(VERSION 3.13.4)` to `cmake_minimum_required(VERSION 3.14)`?

**Comment by lassoan** [comment]
You may also need to provide SQLite3_DIR.

**Comment by hubutui** [comment]
Yes, `SQLite3_DIR` should be set to where `sqlite-config.cmake` or `sqliteConfig.cmake` locate, but there are no such files. sqlite pkg from Archlinux ships only these files:
```text
sqlite /usr/
sqlite /usr/bin/
sqlite /usr/bin/showdb
sqlite /usr/bin/showjournal
sqlite /usr/bin/showstat4
sqlite /usr/bin/showwal
sqlite /usr/bin/sqldiff
sqlite /usr/bin/sqlite3
sqlite /usr/include/
sqlite /usr/include/sqlite3.h
sqlite /usr/include/sqlite3ext.h
sqlite /usr/lib/
sqlite /usr/lib/libsqlite3.so
sqlite /usr/lib/libsqlite3.so.0
sqlite /usr/lib/libsqlite3.so.0.8.6
sqlite /usr/lib/pkgconfig/
sqlite /usr/lib/pkgconfig/sqlite3.pc
sqlite /usr/share/
sqlite /usr/share/licenses/
sqlite /usr/share/licenses/sqlite/
sqlite /usr/share/licenses/sqlite/license.txt
sqlite /usr/share/man/
sqlite /usr/share/man/man1/
sqlite /usr/share/man/man1/sqlite3.1.gz
```

**Comment by lassoan** [comment]
You can build [this sqlite](https://github.com/azadkuh/sqlite-amalgamation), create the necessary CMake files manually.

You may also try if CMake's FindSQLite3.cmake script can find sqlite on your system. If that works well then you may change `find_package(${proj} REQUIRED)` to `FindSQLite3` in External_sqlite.cmake.

But SQLite is so tiny that letting Slicer build it should not make much difference.

**Comment by hubutui** [comment]
Yes, I change `find_package(${proj} REQUIRED)` to `find_package(SQLite3 REQUIRED)` and it works great.
