### ISSUE TITLE
Plane resizing

### ISSUE THREAD

**Issue by muratmaga** [Slicer/Slicer#5265]
In addition to the default translation operations with the widget, please allow to resize the plane through widget handles. Default action can be still translate, with shift modifier it becomes scaling (movement in the direction of arrow increases the size, movement opposite to the arrow reduces the size of the plane for that axis). 

If this is confusing or difficult to implement, consider adding points in the midpoint of each edge to enable resizing (similar to current ROI tool).

**Comment by lassoan** [comment]
I agree. Probably the most intuitive would be to place the ROI with a single control point. The control point would serve as the center point, the normal would be a surface normal. The size could maybe some default physical value or derived from the size of the view (e.g., it could fill half the view).
