### ISSUE TITLE
vtkSlicerCLIModuleLogic Python class is not found

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5266]
Using Slicer-4.11.20200930:

```ptyhon
>>> slicer.vtkSlicerCLIModuleLogic()
(qSlicerBaseQTCLIPython.vtkSlicerCLIModuleLogic)00000167BA933648
```

Using latest master:

```python
>>> slicer.vtkSlicerCLIModuleLogic()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: this class cannot be instantiated
```

I’ve debugged into wrappython.exe and the problem is that for some reason the hierarchy cannot find the parent’s class in the hierarchy and so it determines that vtkSlicerCLIModuleLogic is not a VTK class, therefore it looks for a public constructor (instead of New()), which is of course is not found.

Originally reported here: https://discourse.slicer.org/t/calls-to-cli-makes-tests-to-fail/13835/10?u=lassoan

**Comment by jcfr** [comment]
Thanks for the detailed report, that is helpful

**Comment by BishopWolf** [comment]
This issue seems to be resolved in the last build. At least I don't have more errors. Please confirm for you

**Comment by lassoan** [comment]
The issue probably has not been resolved yet, we just switched back temporarily to VTK8 in factory builds due to this and other problems.

**Comment by jcfr** [comment]
This is still an issue when building against VTK9. 

Since we reverted the current nightly to VTK8, it works.

**Comment by sjh26** [comment]
This is a must-fix before switching to VTK9, as it prevents running clis from python
