### ISSUE TITLE
Letter "F" appears at [0,0,0] whenever point labels shown for MarkupsCurve

### ISSUE THREAD

**Issue by mikebind** [Slicer/Slicer#5276]
Anytime point labels are visible for a MarkupsCurve, a letter F appears at [0,0,0] in the 3D view window.  

## Steps to reproduce
Open Slicer.  Load an image volume (I used the MRHead sample volume for the screenshot).  Create a new open MarkupsCurve and click to place some control points.  Click to display point labels. 

![image](https://user-images.githubusercontent.com/3981795/97453715-3ded1800-18f3-11eb-838a-49436e92b20d.png)

At this point, the "F" appears at the origin of the 3D space. It does not appear to have an associated glyph.  [0,0,0] is not listed as a control point location. 

The "F" changes color (along with the markup curve) if any of the control points are "unselected":
![image](https://user-images.githubusercontent.com/3981795/97454603-2c584000-18f4-11eb-8021-1682725ccdb7.png)

## Expected behavior
To not have a letter "F" appear as an extraneous point label when point labels are visible. Otherwise, the MarkupsCurve behavior is as I expect.

## Environment
- Slicer version: Slicer-4.11.20200930
- Operating system: Windows 10

**Comment by lassoan** [comment]
@Sunderlandkyl could you have a look? This might be due to the recent development of allowing occluded markup points to appear.

**Comment by mikebind** [comment]
I have experienced this issue for months, it is just that I got around to reporting it now.   I just checked, and I get the same behavior in 4.11.0-2020-01-08, which is the oldest 4.11 I still have set up
