### ISSUE TITLE
missing libOpenGL.so on ubuntu 20.10

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#5286]
The download gives this error:
```
$ ~/Downloads/Slicer-4.13.0-2020-10-31-linux-amd64/Slicer 
/home/pieper/Downloads/Slicer-4.13.0-2020-10-31-linux-amd64/bin/SlicerApp-real: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory
pieper@sdp-november:~$ cat /etc/issue
Ubuntu 20.10 \n \l
```

4.11-20200930 works fine on the same machine.

**Comment by jcfr** [comment]
Probably related to https://github.com/Slicer/Slicer/issues/5228

**Comment by swd543** [comment]
On ubuntu 20.10 I am facing the same issue. Trying to open the precompiled stable binary it reports `[Slicer-4.11.20200930-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.` Tried compiling it from source but the issue persists.
