### ISSUE TITLE
SetSelectedSegmentID does not report error if segment doesn't exist

### ISSUE THREAD

**Issue by fusentasticus** [Slicer/Slicer#5289]
For scripting little routines, it's not good if an operation proceeds on the wrong segment. But that happens easily with the current semantics of `SetSelectedSegmentID(SegmentID)` of a mrmlSegmentEditorNode. It doesn't raise an exception if the `SegmentID` doesn't exist. And so a script will continue, operating on whatever was already selected.

## Environment
- Slicer version: Slicer-4.11

**Comment by lassoan** [comment]
There are use cases when stricter check could be useful but that the selected segment ID can be set before the segment actually exists is an important feature, not an error case. For example, when the scene is loaded then nodes can be loaded in arbitrary order, so the segment editor node may be initialized when the segmentation node does not even exist yet.

When an error occurs in MRML then a warning/error is logged. It would be certainly useful to see those logs in the Python console and there are discussions about this already (https://github.com/Slicer/Slicer/pull/5176) but it is not implemented yet.
