### ISSUE TITLE
Clip segmentations in 3D view using ROI

### ISSUE THREAD

**Issue by hherhold** [Slicer/Slicer#5299]
Many of the specimens we work on (micro-CT for insect morphology, both living and fossil) have surprisingly complicated internal structures. It would be really helpful to be able to crop the 3D view of a segment while doing manual segmentation.

This is currently doable by exporting to a model and then clipping that model using clipping planes, but this is an extra step and is not "interactive" while doing segmentation tasks. An ROI clip/crop/mask similar to what is available in Volume Rendering would be ideal.

(I'm willing to take a stab at this but it is very likely over my head as far as Slicer internals goes.)

**Comment by lassoan** [comment]
@Sunderlandkyl after you developed the new markups ROI node you could have a look at this task.

As a first step, it could work the same how models are clipped now. But we should also think about how clipping could be improved in a next steps to work similarly to what you implemented in Dynamic modeler's Plane cut tool (capping, clipping with not just slice planes but markups, etc.).

**Comment by Sunderlandkyl** [comment]
@cpinter The issue should be fixed by https://github.com/Slicer/Slicer/pull/8083.

**Comment by cpinter** [comment]
Thank you very much Kyle!
