### ISSUE TITLE
Line label is not updated until measurements are updated

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5302]
Line label in slice views (L: 13.5mm) is not updated when the node is renamed, only when points are moved.

## Steps to reproduce

- Place a markups line
- Rename the line node
- Label in slice view is not changed => ERROR
- Move a line endpoint -> the label is updated then

## Expected behavior

When the node name is changed then the label should be updated, too.

## Environment
- Slicer version: Slicer-4.13.0-2020-11-17
- Operating system: Windows 10

**Comment by jamesobutler** [comment]
Using Slicer 4.13.0-2020-12-29 I came across this bug as well.

The label does not get updated when a Markups Angle object is also renamed, but will update when the angle measurement is updated.
