### ISSUE TITLE
Moving item to new folder does not mark correct file(s) as modified for saving

### ISSUE THREAD

**Issue by JC3** [Slicer/Slicer#5303]
If an item (e.g. a segmentation) is moved into a folder in the data module, it seems that whatever file the info about that hierarchy is stored in is not marked as modified, and so is not automatically selected when saving. So if you move items around you have to select all files to save for the hierarchy change to be saved.

## Steps to reproduce

Open a scene. Move a segmentation into a new folder. Save the scene without adjusting the default file selection.

Then open the scene again. The segmentation will be in its previous location.

## Expected behavior

Expected segmentation to be in the new folder when the scene is opened again. 

Workaround is to select all the files when saving. Then the info is saved. I'm sure there's a specific file; I didn't try to discover which one it was.

## Environment
- Slicer version: Slicer-4.11.20200930
- Operating system: Windows 10

**Comment by lassoan** [comment]
Subject hierarchy folder structure is saved into the scene. If you move a node into a different folder then it is detected as a change in the scene and by Slicer will mark the scene as modified in the save dialog.

I could not reproduce the problem that you described - after I moved the segmentation node into a subject hierarchy folder, saved the scene, restarted Slicer, then loaded the scene, the segmentation showed up correctly in the folder where it was at the time of the scene save.

If you can post a link to a scene file (mrb file or zipped up scene folder) that is supposed to have the segmentation node in a folder but it does not appear in a folder when loading into Slicer then we can investigate this further.
