### ISSUE TITLE
Segmentation editor effects performance regression between version 4.10 and version 4.11

### ISSUE THREAD

**Issue by Thibault-Pelletier** [Slicer/Slicer#5308]
There seems to be some performance regression with at least some for the segmentation editor effects between version 4.10 and version 4.11.

These performance issues are visible when comparing the "Paint" and the "Erase" effects between the two versions.

This issue may be related to issue #5063.

### Steps to reproduce
Benchmarks were ran on a 512x512x1093 volume with volume rendering deactivated (Anonymous DICOM).

- Load the volume
- Load the segment editor module with one segment
- Select the paint tool
- When release the mouse button there is a visible break in responsiveness when using version 4.11 vs 4.10.2
- The erase button has even more visible lag when releasing the mouse button
- Reverting the qSlicerSegmentEditorPaintEffect.cxx and qSlicerSegmentEditorPaintEffect_p.h files to the version prior to commit 8519c1bcde1872fd72fe73ea56e8dacd5c91e641 seems to restore version 4.10 responsiveness for the paint effect

### Environment
OS : Windows 10
Slicer versions : 4.10.2 and 4.11.20200930

**Comment by Thibault-Pelletier** [comment]
@andras do you have an idea of what coud be the reason of the regression? I'm happy to investigate, I just wanted to know if you have some hints beforehand. Thanks for your insight.

**Comment by lassoan** [comment]
Can you provide an example scene that demonstrates this issue?

**Comment by Thibault-Pelletier** [comment]
Thank you for coming back to me,

You will find hereafter a link to the scene where the performance difference is noticeable (I have set sharing restrictions to Kitware only, please let me know if I need to change it):

https://drive.google.com/file/d/1lz2JWolIWdvaN6r0-WWZw-0-XZY2vHkt/view?usp=sharing

**Comment by lassoan** [comment]
On this sample data set, Slicer-4.11.20200930 paint works faster for me than Slicer-4.10.2, but erase is indeed about 50% slower. This post-paint/erase delay are about 1 second on a laptop on a larger than average data set, so overall the difference is very small, but I agree that it is noticeable.

Do you have the same experience, or you experience longer delays?

**Comment by Thibault-Pelletier** [comment]
Thank you for your feedback,

On my configuration Slicer-4.11.20200930 paint and erase are slower than Slicer-4.10.2 : 

Slicer 4.11 :

- Paint : about 0.5 seconds lag
- Erase : about 1 second lag 

Slicer 4.10.2 :

- Paint : Almost no noticeable lag (< 0.1 seconds)
- Erase : Very small lag (< 0.3 seconds)

I think the most toubling difference I experience is that I can keep on painting / erasing using Slicer 4.10.2 even if the changes don't reflect directly on the volume whereas the UI becomes unresponsive using 4.11 until the changes are applied (which may be only a matter of the lag being different on my configuration).

I ran the test on the following configuration : 

- Alienware laptop
- i7-9750H 2.6 GHz
- Geforce GTX 1650 4GB
- 8 GB of ram

**Comment by lassoan** [comment]
https://github.com/Slicer/Slicer/pull/5578 fixes the problem. Thanks for your contribution.
