### ISSUE TITLE
Markups occluded display broken after upgrading to VTK9

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5317]
Markups module allows user to show occluded markups using a semi-transparent actor. If we enable this option now, these occluded parts do not show up anymore.

## Steps to reproduce

- Load MRHead
- Draw a curve in the yellow view so that parts of the curve goes above the red slice, and parts of the curve are below
- Show red slice view in 3D
- Rotate the 3D view a bit => parts of the curve behind the red slice view are occluded 
- Enable Markups module / Display / Advanced / 3D Display / Occluded visibility
- Occluded parts of the curve are not visible => ERROR!

## Expected behavior

- Occluded curve segments should appear as semi-transparent

For example, in Slicer-4.11.20200930

![image](https://user-images.githubusercontent.com/307929/100190753-ec698600-2ebc-11eb-8e2b-9b5501fe56ca.png)

## Environment
- Slicer version: Slicer master 2020-11-24, built with VTK9
- Operating system: Windows 10

**Comment by sankhesh** [comment]
@lassoan I can reproduce this too. Could you please point me to the code that shows and controls the opacity of the occluded actor?

**Comment by jcfr** [comment]
I could search for "Occluded" in this file: [vtkSlicerCurveRepresentation3D](https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.cxx)

**Comment by jcfr** [comment]
| VTK8 | VTK 9|
|----|-----|
| ![image](https://user-images.githubusercontent.com/219043/101112386-274d7700-35ab-11eb-989c-78f15b040582.png) |  ![image](https://user-images.githubusercontent.com/219043/101112475-5fed5080-35ab-11eb-901f-ede8997683f1.png) |

**Comment by jcfr** [comment]
Closing. Issue fixed in https://github.com/Slicer/Slicer/commit/a96498c63dd986166b0dcd9e28cdeeed043285f5 after integrating #5361
