### ISSUE TITLE
Segmentation imported from plain nrrd file is saved with smaller extent than the original

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5323]
When a plain nrrd file is loaded as segmentation then the reference geometry is not set and so when the segmentation is saved, the extent is reduced to the minimum necessary. We should preserve the original extent.

See details here:
https://discourse.slicer.org/t/segmentation-is-cropped-to-minimum-extent/14788

**Comment by lassoan** [comment]
@Sunderlandkyl you have fixed this, haven't you?

**Comment by Sunderlandkyl** [comment]
Not sure. I'll double check.

**Comment by Sunderlandkyl** [comment]
Should be fixed by 2d1e1d819a8cf410b025e8f4c523280860b5c736.
