### ISSUE TITLE
Failure to run Slicer 4.10 built in Debug against Qt 5.7 using VS2015

### ISSUE THREAD

**Issue by Jared-Dai** [Slicer/Slicer#5329]
[Give a short summary of what the problem is]

## Steps to reproduce
I am not sure if this problem is related to environment. It occurs when I run the project which is already compiled sucessfully. 

[describe what you did and what happened - attach screenshots if possible]

![image](https://user-images.githubusercontent.com/66655052/100995019-2fe58380-3592-11eb-8baa-83b360630713.png)

## Expected behavior

[describe what you expected to happen]
When I run the project, an Error window will pop up that says " Unable to locate program input point ?setDefaultQVTKCursor@QVTKOpenGLNativeWidget@@QEAAXAEBVQ Cursor@@@Z  at qMRMLWidgets.dll"
## Environment
- Slicer version: Slicer-4.10.0-2020-8-9
- Operating system: Windows + VS2015 Qt5.7

**Comment by lassoan** [comment]
This indicates that import lib file does not match the dll. You need completely different build trees for debug and release mode build.

Nite that this Slicer version is from several years ago. We can only provide free developer support for troubleshooting issues with the latest Slicer master version.

**Comment by jamesobutler** [comment]
Considering this git issue is labeled `status:wontfix`, I will close this now.  For historical purposes it can always be found again as a closed issue, but currently has no value as an open issue.

Questions regarding building Slicer from source can be asked over on the forum https://discourse.slicer.org/. Latest build documentation can be found at https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/index.html.
