### ISSUE TITLE
Increasing Markups line thickness does not work after updating to VTK9

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5332]
Markups module allows user to change the line thickness of annotation. After increasing the thickness, only the outline of the line are displayed when using VTK9.

## Steps to reproduce

- Load MRHead
- Draw a curve, angle and line on any of the slice view
- Increase Markups module / Display / Advanced / Line Thickness
- Only the outline is displayed => ERROR

![image](https://user-images.githubusercontent.com/219043/101113434-5d8bf600-35ad-11eb-8d1f-91deb6c9f912.png)

## Expected behavior

| VTK8 (expected) | VTK9 (error)
|----|---|
| ![image](https://user-images.githubusercontent.com/219043/101113728-ff134780-35ad-11eb-8352-976fc39b8dc2.png) | ![image](https://user-images.githubusercontent.com/219043/101113756-0d616380-35ae-11eb-814e-672b3238959b.png) |

## Environment
- Slicer version: Slicer master 2020-12-02, built with VTK9
- Operating system: Ubuntu

**Comment by jcfr** [comment]
Thickness is handled here:

https://github.com/Slicer/Slicer/blob/2f0ef879a0af69c4d5a4e25796e41ff3921cb910/Modules/Loadable/Markups/VTKWidgets/vtkSlicerCurveRepresentation3D.cxx#L249-L264

**Comment by sankhesh** [comment]
@jcfr IMHO, this should have been fixed in a96498c after integrating #5361

**Comment by jcfr** [comment]
> IMHO, this should have been fixed in a96498c after integrating #5361

I confirm :partying_face: 

Closing. Issue fixed in https://github.com/Slicer/Slicer/commit/a96498c63dd986166b0dcd9e28cdeeed043285f5 after integrating #5361
