### ISSUE TITLE
Demons Registration (BRAINS) does not appear in 4.11.2 Windows

### ISSUE THREAD

**Issue by dsl103** [Slicer/Slicer#5333]
The Demons Module does not seem to be accessible from the menu in 4.11.2.  A module search does not find it.  The "All Modules" drop down also does not seem to be available.

**Comment by jamesobutler** [comment]
This was removed. See #5255 for details.

**Comment by jamesobutler** [comment]
Marked as duplicate. Closing this issue now to contain conversation over at the other issue.
