### ISSUE TITLE
property needed in markups logic CopyBasicDisplayProperties

### ISSUE THREAD

**Issue by mauigna06** [Slicer/Slicer#5335]
https://github.com/Slicer/Slicer/blob/0574e2576a3d8781cfbb5cc7c46f5fcaf5e1d729/Modules/Loadable/Markups/Logic/vtkSlicerMarkupsLogic.cxx#L893

May be this line should be added:

`
targetDisplayNode->SetHandlesInteractive(sourceDisplayNode->GetHandlesInteractive());
`

I'd like that so that markups can be default created with the interaction handles on

**Comment by lassoan** [comment]
Saving interaction handles display state would cause more confusion for users than it would help in those very few cases where it is actually useful. Defaults are also used for all markup types, so even if you just want to apply it for planes, it would be also applied to points, curves, lines, etc. so you would need to keep turning it off for those markup types.

Normally, you would implement such special behavior (creating markups with handles on by default) in your own module. For example, placing a plane and then adjusting it with interaction handles is a quite common use case. We usually solve this by adding an observer to the markups plane node and when the user placed 3 control points then we hide the control points and display the interaction handle. If you can determine a good initial plane orientation from 1 control point then you can add the two control points automatically after the first one is placed and immediately hide the control points and show the interaction handles.
