### ISSUE TITLE
Segment Editor "overwrite visible segments" mode sometimes allow overlap

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5338]
If "Overwrite visible" mode is enabled and there is a hidden segment then visible segments are not overwritten (which would be the correct behavior) but they overlap.

See more information here: https://discourse.slicer.org/t/masking-overwrite-visible-allowing-overlap-instead-of-overwriting/14857/8

## Steps to reproduce

- Load this scene: https://1drv.ms/u/s!Arm_AFxB9yqHxM1HwpPPM-NsSSPYHw?e=eXGuya
- Select Segment_2
- Click Apply in Margin effect
- Purple segment overlaps with the visible green segment => ERROR

## Expected behavior

Purple segment should overwrite the visible green segment.

## Environment
- Slicer version: Slicer-4.13.0-2020-12-07
- Operating system: Windows 10

**Comment by lassoan** [comment]
@Sunderlandkyl have you looked at this issue? I remember you worked on something similar but I'm not sure it was exactly this.

**Comment by Sunderlandkyl** [comment]
No, I'll take a look at it.

**Comment by lassoan** [comment]
@Sunderlandkyl you have fixed a lot of segmentation issues since February. Is this one still unresolved?

**Comment by jamesobutler** [comment]
Following the instructions I provided at https://discourse.slicer.org/t/masking-overwrite-visible-allowing-overlap-instead-of-overwriting/14857/8, I am still able to replicate the observed behavior using Slicer 4.13.0-2021-07-22.

**Comment by Sunderlandkyl** [comment]
Sorry, this fell off of my radar. I'll take a look on Monday.

**Comment by lassoan** [comment]
Fixed in https://github.com/Slicer/Slicer/pull/5760/commits/286d0112a4826101291a70f2b7330eaa567e2efd
