### ISSUE TITLE
GUISupportQtOpenGL is deprecated in VTK9

### ISSUE THREAD

**Issue by ghisvail** [Slicer/Slicer#5339]
Compilation of `master` with VTK9 fails because the `GUISupportQtOpenGL` module is not available.

```
CMake Error at CMakeLists.txt:815 (find_package):
  Found package configuration file:

    /app/lib/cmake/vtk-9.0/vtk-config.cmake

  but it set VTK_FOUND to FALSE so package "VTK" is considered to be NOT
  FOUND.  Reason given by package:

  Could not find the VTK package with the following required components:
  GUISupportQtOpenGL.
```

According to this [post](https://discourse.vtk.org/t/guisupportqtopengl/2733) the latter is deprecated and no longer built. Indeed, if the module is enabled in the CMake args, the config log tells you it's no longer registered:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    VTK_MODULE_ENABLE_VTK_GUISupportQtOpenGL

```

**Comment by lassoan** [comment]
You have not build VTK with the correct build options (you missed enabling Qt support).

It is strongly recommended to build Slicer according to the [build instructions](https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/index.html). If you do that then Slicer builds VTK (and all other dependencies) with the correct options and applies any patches that are not yet available in the upstream repository.

**Comment by jcfr** [comment]
@ghisvail We are now closing this issue, if you still have issues building Slicer, we suggest you post your question on the forum. See https://discourse.slicer.org/
