### ISSUE TITLE
MacOS extensions missing for SlicerPreview

### ISSUE THREAD

**Issue by che85** [Slicer/Slicer#5340]
MacOS extensions for Slicer Preview have not been built since 2020-11-21

## Steps to reproduce

Extensions built:
http://slicer.cdash.org/index.php?project=SlicerPreview&date=2020-11-21

Missing MacOS extensions the next day:
http://slicer.cdash.org/index.php?project=SlicerPreview&date=2020-11-22

**Comment by lassoan** [comment]
Around the same time (+/- 1 day) about 190 tests on Mac started to fail with timeout. I don't know if it's related but it should be fixed, too.

**Comment by che85** [comment]
Awesome, at least builds are back on http://slicer.cdash.org/index.php?project=SlicerPreview

**Comment by che85** [comment]
Correction. As of today, the extensions are also provided in the ExtensionManager. Did you change anything?

**Comment by jamesobutler** [comment]
Is this issue considered resolved? Tests for factory-south-macos.kitware were turned off (see #5391) which allowed for extensions to upload appropriately. Tests were switched over to computron-macos-tests.kitware.

**Comment by lassoan** [comment]
Yes, the issue is resolved.
