### ISSUE TITLE
Add favorite extensions list to Extensions manager

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5341]
Restore extensions tab in Extensions Manager is meant to help reinstalling previously installed extensions. However, in practice it is not useful, because it lists all the extensions that the user has ever installed on any Slicer versions. It means that if the user event installed an extension once, just to try it, and found it not useful, there is no way to remove it from the list.

Over time a large number of extensions and Slicer revisions can accumulate and metadata of all these extensions are queried (e.g., to be able to display extension description), which can significantly increase extension manager startup time.

Instead of (or maybe in addition to) the "all previously installed extensions" list, there should be a "Favorite extensions" list that the user can manage by manually adding and removing extensions.

Possible implementation:
- Add "Add to favorite" button to Manage extensions tab
- Add "Remove selected from favorites" button to "Restore extensions" tab
- Save list of favorite extension name, description (needed for search without querying the extensions manager for metadata), and maybe Slicer version that was last used in, or last install date

These changes should be probably implemented after switching to the new girder-based extensions manager backend.

**Comment by pieper** [comment]
Yes to all those suggestions.  Also the check for updates should be asynchronous from opening the extension manager.  We could have a "check for updates" setting and check in the background whenever Slicer starts.  We could then add some kind of decorator to the extension manager toolbar button when new extensions are discovered.

**Comment by lassoan** [comment]
I've worked on some extensions manager fixes and could give it a stab to implement this favorites feature.

Would everyone be OK with removing extension install history (which extensions were installed for which Slicer versions) and instead just maintain a favorite extensions list?

**Comment by pieper** [comment]
> Would everyone be OK with removing extension install history (which extensions were installed for which Slicer versions) and instead just maintain a favorite extensions list?

Sounds fine to me.

**Comment by lassoan** [comment]
This is how it looks now:

![image](https://user-images.githubusercontent.com/307929/171630419-a13868e5-acae-4b43-a2e4-28133f7795ed.png)

The "Restore extensions" tab is gone, it was redundant and bad performance and design. Instead, we have a tab to manage current extensions, i.e., the ones that are installed or the user "bookmark"-ed them (bookmarked extensions appear in the managed extensions list on all Slicer versions, even if not installed). I'll add "Install all" and "Update all" buttons.

Update check is asynchronous and very fast, so we can re-enable automatic extension update checks at startup. We could display an "update notification" symbol on the extensions manager toolbar button when updates are available, and we could also reenable fully automatic updates.

**Comment by jcfr** [comment]
That will be a great improvement :100: 


Suggestions:

* Use plain/full bookmark icon (or the one with a star in the middle)
* Using a star icon would also be consistent with browser pages as well.

Questions:
* After un-bookarmking a `not installed` extension. What happen ? 
* To support adding any extension as favorite  ... I suggest we enhance the [slicer-extensions-webapp](https://github.com/KitwareMedical/slicer-extensions-webapp) frontend to include a star icon for bookmark/un-bookmark. This could be done adding a [BookmarkState](https://github.com/KitwareMedical/slicer-extensions-webapp/blob/1181036578291594931fdda716a3c6e50d7aebec/src/lib/api/extension.service.ts#L49-L52)
