### ISSUE TITLE
Slicer building error in Ubuntu18.04 with default Qt version 5.9.5

### ISSUE THREAD

**Issue by mxochicale** [Slicer/Slicer#5343]
Hi All,

Following [build_instructions for Ubuntu 20.04](https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/linux.html) to build slicer in Ubuntu 18.04, I found one issue with the version of cmake which I have updated to version 3.19.1 [sorted out here](https://stackoverflow.com/questions/49859457/how-to-reinstall-the-latest-cmake-version). I am now in the point of selecting the right Qt version which has an issue (shown below). I am guessing that there should be a README to be able to have the right version with all the required components of Qt (Multimedia, UiTools, XMLPatterns, SVG, WebEngine, Script, X11Extras, Private). I then wonder if you have any recommendations on which Qt version is recommended and perhaps point out references on how to build qt with all those required components for slicer.

## Steps to reproduce
Follwoing [build_instructions for Ubuntu 20.04](https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/linux.html), the following error apears  while building slicer
``` 
$ cd Slicer-SuperBuild-Debug
$ make
~/Slicer/Libs/MRML/Widgets/qMRMLSceneFactoryWidget.cxx:23:10: fatal error: QRandomGenerator: No such file or directory
 #include <QRandomGenerator>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Libs/MRML/Widgets/CMakeFiles/qMRMLWidgets.dir/build.make:1299: recipe for target 'Libs/MRML/Widgets/CMakeFiles/qMRMLWidgets.dir/qMRMLSceneFactoryWidget.cxx.o' failed
make[5]: *** [Libs/MRML/Widgets/CMakeFiles/qMRMLWidgets.dir/qMRMLSceneFactoryWidget.cxx.o] Error 1
CMakeFiles/Makefile2:10251: recipe for target 'Libs/MRML/Widgets/CMakeFiles/qMRMLWidgets.dir/all' failed
make[4]: *** [Libs/MRML/Widgets/CMakeFiles/qMRMLWidgets.dir/all] Error 2
Makefile:181: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/Slicer.dir/build.make:162: recipe for target 'Slicer-prefix/src/Slicer-stamp/Slicer-build' failed
make[2]: *** [Slicer-prefix/src/Slicer-stamp/Slicer-build] Error 2
CMakeFiles/Makefile2:454: recipe for target 'CMakeFiles/Slicer.dir/all' failed
make[1]: *** [CMakeFiles/Slicer.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
```

## Expected behaviour
I made a quick search and it seems that I do not have the right version of Qt. "If this is <5.10 you will need to update Qt. On Linux this means that you may have to download Qt from their website rather than through your package manager [ref](https://stackoverflow.com/questions/57647925/qrandomgenerator-no-such-file-or-directory)"  

## Environment
    Slicer version: latest commit in master 
    Operating system: GNU/Linux Ubuntu 18.04
    Qt version: 5.9.5
    gcc: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    cmake version 3.19.1
    OpenSSL 1.1.1  11 Sep 2018

**Comment by lassoan** [comment]
You can find some information on what Qt version to use and how to build your own Qt here: https://discourse.slicer.org/t/should-i-build-qt-5-10-from-source-on-linux/2484

You can also just remove this test and see if you run into any other issues. If the only issue with Qt-5.9 is the lack of QRandomGenerator class then that test can be automatically disabled if an old Qt version is used.

**Comment by lassoan** [comment]
We have not heard from the user, so we can assume that the problem has been resolved.
