### ISSUE TITLE
Minor documentation bug.

### ISSUE THREAD

**Issue by hina-shah** [Slicer/Slicer#5351]
`createProgressIndicator` should be `createProgressDialog`

https://github.com/Slicer/Slicer/blob/0b8e88e436bd242f6ef6f4f52b6463064248919c/Base/Python/slicer/util.py#L2071

**Comment by lassoan** [comment]
Could you please send a pull request? You can make a change on the web GUI and it takes care of everything (creates a fork, commits your changes, pushes that to your fork, creates a pull request).
