### ISSUE TITLE
Wondering for Image display

### ISSUE THREAD

**Issue by czj1989** [Slicer/Slicer#5357]
Hello! It is not a bug. I just wonder something about image display in Slicer.  when I used vtk6.2 to display image with vtkImageReslice::SetInterpolationModeToLinear() and vtkImageActor:InterpolateOn(),  I got Figure A which was not smoothing. But I load the same image in Slicer, then I got Figure B which was very smoothing.  Besides, the image is also not smoothing in itk-snap. Can you tell me the additional operations has done by Slicer? Thank you very much!

Figure A
![image](https://user-images.githubusercontent.com/48468966/103199518-fe0fd480-4925-11eb-855b-7a42bb9bb495.png)

Figure B
![image](https://user-images.githubusercontent.com/48468966/103199560-141d9500-4926-11eb-8b53-056179e2ac70.png)

**Comment by pieper** [comment]
Maybe the difference is that Slicer uses vtkImageReslice to resample the images to screen space (pixels on your monitor) but when you use a vtkImageActor it uses the original image as a texture.

**Comment by pieper** [comment]
We use discourse.slicer.org for this kind of discussion, so let's move any follow up over there, thanks.
