### ISSUE TITLE
Make slice views aligned with image axes by default

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5379]
## Is your feature request related to a problem? Please describe.

New users keep struggling because slice views not aligned with image axes by default.

https://discourse.slicer.org/t/rotate-to-volume-plane/8032/2
https://discourse.slicer.org/t/nearby-fiducial-points-at-different-slices/15309/6
https://discourse.slicer.org/t/read-prostate-mr-image-failed/3423/8
https://discourse.slicer.org/t/slice-number-change/4358/2
https://discourse.slicer.org/t/segmentation-editor-how-to-disable-painting-on-adjacent-slices/1459/4
https://discourse.slicer.org/t/mri-dwi-images-load-with-wrong-orientation/482

Instead of trying to educate users about why Slicer behaves like this, we should change the behavior so that new users get what they expect. It should be easy to enable the current behavior (keep current slice view orientation, aligned with anatomical axes by default).

## Describe the solution you'd like

Add a "Reset orientation on show" checkbox (enabled by default for new installations) for visibility context menu in Data module, similarly to the existing "Reset field of view on show" context menu.

If this option is enabled then when the volume is propagated in slice views, eye icon is clicked in data tree for a volume, or volume drag-and-dropped into slice views, slice views would be reset to their default orientation (to make sure that different views would not be snapped to the same orientation) and then "rotate to volume plane" would be activated.

For single-slice volumes:
- If slice views are not linked, the slice could be added to the first slice view that does not show any volume yet.
- If slice views are linked then, the slice could be added to the first slice view group that does not show any volume yet.

## Describe alternatives you've considered

I don't have any other good ideas, but open to suggestion.

## Additional context

Part of the "Make simple things simple and complex things possible" effort.

**Comment by pieper** [comment]
It's true that this is a common problem and that the solution is not easy to figure out.  There's always a tradeoff of course that adding more options adds complexity too.

Maybe an option would be to visually indicate in the slice viewer when volumes are being resliced, and then clicking that does the rotation to volume plane and makes the indicator go away.

But I do like the idea of an option in the data context menu too.

**Comment by lassoan** [comment]
> Maybe an option would be to visually indicate in the slice viewer when volumes are being resliced, and then clicking that does the rotation to volume plane and makes the indicator go away.

Thanks, this is a good point. Such indicator would be useful regardless of how we align slice views by default (so it could be implemented in addition to the automatic alignment). In this "snapped" mode we could also force slice views to be centered on the image slice (to ensure there is no interpolation between slices), which is useful if distance between slices is large.

**Comment by pieper** [comment]
Agreed, and maybe it should be in the color bar next to the "fit" button.

**Comment by fepegar** [comment]
While I appreciate this is helpful for new users, is there a way to disable it? I'm too used to the old behavior :)

**Comment by lassoan** [comment]
Yes, while most often you want the slice view to adapt to the selected volume, sometimes you want to keep the slice constant and show whatever is visible from the current volume there. You can disable resetting the field of view and/or orientation of the slice by  using the checkboxes in Subject Hierarchy visibility menu (right-click on the eye icon).

**Comment by fepegar** [comment]
Thanks, @lassoan. Is there a way to _disable_ the automatic views reformatting?

I.e. I'd like to see this

![Screenshot](https://user-images.githubusercontent.com/12688084/110363733-d2524e80-803a-11eb-84ed-a921ea15d5de.png)

instead of this

![Screenshot1](https://user-images.githubusercontent.com/12688084/110363747-d67e6c00-803a-11eb-91b9-723dd49d18db.png)

when I load an image.

**Comment by lassoan** [comment]
"Reset view orientation on show" state is persistent (stored in shared Slicer.ini application settings file), so if you don't want to align the slice views to the volume axes automatically then you need to disable it only once and it will remain disabled forever, for all images, in all Slicer instances.
