### ISSUE TITLE
Please add the feature that name and description can be displayed as a label for curves

### ISSUE THREAD

**Issue by rbumm** [Slicer/Slicer#5384]
## Is your feature request related to a problem? Please describe.

The VMTK displays the centerline model as a curve in 3D view, but there is no default label assigned to the curve. 

## Describe the solution you'd like

You would want to see the name of the curve ("Aneurysm") and the description (length of centerline curve) on the 3D display 

## Describe alternatives you've considered

The alternative is to enable the label for the curve control points, but there are usually too many or it is cumbersome to select a specific one. They do not display a length

## Additional context

[Add any other context or screenshots about the feature request here.]

**Comment by lassoan** [comment]
Curve node names are now displayed in views.
