### ISSUE TITLE
vtkAddon test failures

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5390]
Almost all tests pass on Windows now. The only remaining failing tests are [vtkAddon tests](http://trunk.cdash.org/viewTest.php?onlyfailed&buildid=2122241) which would require a launcher so that VTK libraries are found.

It would be great if we could achieve a green dashboard because we could then spot regressions much more easily.

**Comment by lassoan** [comment]
@jcfr All tests pass on Windows now, except these vtkAddon tests. Do you think you will have time to implement the fix that you talked about? I may be able to help if you can tell how this could work. We could also consider disabling the tests until the issue is fixed to not pollute the test reports.

**Comment by jcfr** [comment]
I will follow up on Monday with either a fix or an issue outlining what to do to address it.
