### ISSUE TITLE
Qt designer crash on Windows

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#5401]
In the latest Slicer versions (newer than a few weeks, TBD) the Qt Designer does not start but crashes.

Slicer revisions and results:
- https://github.com/Slicer/Slicer/commit/ae0f55c8b507cdfe561e613d22c54cbb6272fedc (Jan 25): crash
- https://github.com/Slicer/Slicer/commit/9a7330277e99d17e1ab9350b98dff84db59d3dc3 (Jan 19) : crash
- https://github.com/Slicer/Slicer/commit/e0705d9c7ad71367c42363299502713a19ed5d44 (Jan 13) (VTK9): crash

## Steps to reproduce

Slicer.exe --designer

## Expected behavior

Designer starts, CTK and Slicer widgets available

## Environment
- Slicer version: Slicer-4.13.0-2021-01-19
- Operating system: Windows 10

**Comment by lassoan** [comment]
The crash is caused by qSlicerTerminologiesModuleWidgetsPlugins.dll. If you delete it then designer starts correctly. There must be something that changed in terminologies module that causes a crash when designer launches it.
