### ISSUE TITLE
Force libarchive to not use homebrew libraries during packaging on macOS

### ISSUE THREAD

**Issue by piiq** [Slicer/Slicer#5415]
Packaged version of Slicer doesn't work on machines other than it was build if libarchive prerequisites were installed via homebrew.

When trying to run a freshly built and packaged Slicer on macOS the app fails to launch and an error pops up:

```
Library not loaded: /usr/local/opt/zstd/lib/libzstd.1.dylib
  Referenced from: Slicer.app/Contents/lib/Slicer-4.13/libarchive.17.dylib
```

The error indicates that during building `libarchive` has linked some of it's requirements to homebrew versions rather than local ones. For example `lz4` and `zstd` are installed by homebrew with `rsync` and `subversion` so if you have at least one of these two application installed via homebrew, `libarchive` will link these libraries to `/usr/local/opt/` and the packaged Slicer will not run on other machines.

## Steps to reproduce

- Install rsync or subversion via homebrew
- Build Qt
- Build Slicer
- Package Slicer
- Run the packaged application on a different mac

## Expected behavior

Slicer launches

## Environment

- Slicer version: Slicer-4.13.0-2021-01-26-macosx-amd64
- Operating system: Mac 11.1

**Comment by lassoan** [comment]
There is already a check in place for Qt, it could be applied to LibArchive, too.

**Comment by jcfr** [comment]
For reference, this approach could be generalized and improved:

https://github.com/Slicer/Slicer/blob/f1cf41897f6e930305f51c1fe37d9ed91e2bcf82/CMakeLists.txt#L644-L670
