### ISSUE TITLE
Startup Crash on fresh build on Linux Mint 20.1

### ISSUE THREAD

**Issue by RobinMontferme** [Slicer/Slicer#5420]
After building the application from source (git-cloned from this repository), the application would crash on start after the splash screen disappear.

## Steps to reproduce
Follow the steps [here](https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/linux.html).

Launch the application `./Slicer`
The splash screen  displays then the application abruptly stops. 
The following line is then displayed in the terminal:
```error: [/home/robin/Documents/PROJET_INFO/master/m2/S2/Projet/3D_slicer/Slicer-SuperBuild-Debug/Slicer-build/bin/./SlicerApp-real] exit abnormally - Report the problem.```
## Environment
- Slicer version: Slicer-4.13.0-2021-01-30
- Operating system: Linux Mint 20.1 (based on Ubuntu 20.04)

## GDB trace

Trace obtained with gdb on `Slicer-build/bin/SlicerApp-real`

```#0  0x00007fffe1fa7d71 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00007fffe1fa8c3c in QDialogButtonBox::setStandardButtons(QFlags<QDialogButtonBox::StandardButton>) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff73f080f in Ui_ctkSettingsDialog::setupUi(QDialog*) (this=0x555556d0e740, ctkSettingsDialog=0x555556cd1510) at /home/robin/work/Projet/3D_slicer/Slicer-SuperBuild-Debug/CTK-build/CTK-build/Libs/Widgets/ui_ctkSettingsDialog.h:57
#3  0x00007ffff73edbfb in ctkSettingsDialogPrivate::init() (this=0x555556d0e740) at /home/robin/work/Projet/3D_slicer/Slicer-SuperBuild-Debug/CTK/Libs/Widgets/ctkSettingsDialog.cpp:75
#4  0x00007ffff73ee9e4 in ctkSettingsDialog::ctkSettingsDialog(QWidget*) (this=0x555556cd1510, _parent=0x0) at /home/robin/work/Projet/3D_slicer/Slicer-SuperBuild-Debug/CTK/Libs/Widgets/ctkSettingsDialog.cpp:187
#5  0x00007ffff7b98ba1 in qSlicerApplicationPrivate::init() (this=0x555555adbb40) at /home/robin/work/Projet/3D_slicer/Slicer/Base/QTGUI/qSlicerApplication.cxx:267
#6  0x00007ffff7b999a1 in qSlicerApplication::qSlicerApplication(int&, char**) (this=0x7fffffffda90, _argc=@0x7fffffffda3c: 1, _argv=0x7fffffffdc08) at /home/robin/work/Projet/3D_slicer/Slicer/Base/QTGUI/qSlicerApplication.cxx:373
#7  0x000055555555cfc6 in (anonymous namespace)::SlicerAppMain(int, char**) (argc=1, argv=0x7fffffffdc08) at /home/robin/work/Projet/3D_slicer/Slicer/Applications/SlicerApp/Main.cxx:40
#8  0x000055555555d2fe in main(int, char**) (argc=1, argv=0x7fffffffdc08) at /home/robin/work/Projet/3D_slicer/Slicer/Base/QTApp/qSlicerApplicationMainWrapper.cxx:56
```
## Notes
- When tested on Ubuntu 20.4 by a colleague, this issue never came up. It seems the issue comes from Qt5 however .
- running Slicer with the following command `./Slicer --gdb` doesn't seems to work
- This bug causes most of the test to fail (especially python related test), as I assume the application should be started up before. The complete list of failed test can be found [here](https://pastebin.com/SLtTvUbb)

**Comment by pieper** [comment]
@RobinMontferme is this still an issue or have you found a way around it?  I don't think any of the Slicer core developers use this distribution so it's not clear how to debug or fix the reported issue.

**Comment by lassoan** [comment]
No feedback received from the reporter, closing this.
