### ISSUE TITLE
Using crop volume sequence on a transformed proxy node creates a volume with all voxels value 0

### ISSUE THREAD

**Issue by nathanbmnt** [Slicer/Slicer#5423]
Using crop volume sequence on a transformed proxy node creates a volume with all voxels value 0

## Steps to reproduce
1. Load a scalar volume node sequence (`.seq.nrrd`,  `.seq.mhd`, etc.)
2. Create a transform that moves and rotates the proxy volume 90 degrees.
![image](https://user-images.githubusercontent.com/40271210/106518284-a5dd6c80-64a7-11eb-9f5a-7d302800080d.png)
3. Use the crop volume widget to set up CropVolumeParameters
![image](https://user-images.githubusercontent.com/40271210/106518325-b68de280-64a7-11eb-8476-6cc88e8ed882.png)
4. Switch to the Crop Volume Sequence Widget, select the CropVolumeParameters, and select (overwrite input) for output volume sequence.
![image](https://user-images.githubusercontent.com/40271210/106518541-08366d00-64a8-11eb-8dbc-b3554d71851f.png)
5. Click apply, the volume proxy node has the correct dimensions but all voxels are value 0 and it is in the wrong RAS location
![image](https://user-images.githubusercontent.com/40271210/106518782-62373280-64a8-11eb-9969-c58c9df378d6.png)

## Expected behavior

Every frame of the proxy volume is cropped according to where the ROI is _after_ the proxy node has been transformed. This is how the regular Crop Volume widget works.

## Environment
- Slicer version: Slicer-4.13.0-2021-01-31
- Operating system: Windows 10

**Comment by lassoan** [comment]
Crop volume sequence module ignores parent transforms. It makes sense to improve it so that it takes those into account. I'll push a fix today or tomorrow.

**Comment by lassoan** [comment]
Fixed in https://github.com/Slicer/Slicer/commit/8e08cdc7b0edb7578edf531f8e28b1ec13f782b8
