### ISSUE TITLE
Launcher does not set Python paths correctly on macOS

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5437]
SlicerJupyter bundles argon2-cffi package but Slicer cannot find these packages after installation.

site-packages folders in extensions are not added correctly to paths.

See more details here:

https://discourse.slicer.org/t/is-slicerjupyter-broken-on-macos-due-to-argon2-cffi-again/15823/7?u=lassoan

## Environment
- Slicer version: Slicer-4.13.0-2020-02-03
- Operating system: macOS

**Comment by lassoan** [comment]
@jcfr this is a blocking point for releasing the current version as stable and may be just a single-line fix, for someone who knows which "home" folder variable to use:

https://github.com/commontk/AppLauncher/blob/9931394cf50c72083ab0b20ea443f1cc591f7752/Base/ctkAppLauncher.cpp#L545

**Comment by jcfr** [comment]
Reading of the settings file on macOS happen in `qSlicerCoreApplication` using the method `ctkAppLauncherSettings::pathsEnvVars()`:

https://github.com/Slicer/Slicer/blob/00a3bcb3cfa68a54426aa8533768fc65a70eb78c/Base/QTCore/qSlicerCoreApplication.cxx#L265-L282

To address the issue, we need to update the implementation of this method to check if path are relative and prepend the launcher dir like it is done in `ctkAppLauncherPrivate::buildEnvironment`

**Comment by lassoan** [comment]
Awesome, thank you for the pointer. Do you plan to continue working on this or prefer that I take it from here?

**Comment by jcfr** [comment]
> Do you plan to continue working on this

AppLauncher PR should be ready for review in few mins.
