### ISSUE TITLE
Update documentation link in Slicer download page

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5443]
We would need to update a few links on download.slicer.org, for example "New Users" should not point to https://slicer.readthedocs.io/en/latest/user_guide/getting_started.html.

I've tried to send a pull request with the proposed changes but the previously used repository seems to be deprecated now: https://github.com/mhalle/slicer4-download_deprecated

**Comment by jamesobutler** [comment]
It appears that https://github.com/mhalle/slicer4-download_deprecated might still be used. There is https://github.com/mhalle/slicer4-download_deprecated/issues/11 which details moving it to the Slicer org but https://github.com/Slicer/download.slicer.org is an empty repo.

@jcfr Is there going to be more development time planned to finalize the new Slicer website in https://github.com/Slicer/slicer.org/tree/landing-page-redesign? Will the Slicer download page change from the current subdomain method to one that uses the same theme and is a subpage? Like the ITK download page? https://itk.org/download/

**Comment by jcfr** [comment]
> Is there going to be more development time planned to finalize the new Slicer website

Yes, this will happen after we finalize the VTK9 transition

> Will the Slicer download page change from the current subdomain method to one that uses the same theme and is a subpage?

That is indeed the goal.

**Comment by jamesobutler** [comment]
@lassoan Is this issue still relevant now with the latest updates to the new https://download.slicer.org/ (https://github.com/Slicer/slicer_download) ?

There is not a "New Users" link, but there is a "Getting Started" that links to https://slicer.readthedocs.io/en/latest/user_guide/getting_started.html which is part of the site's bottom navigation area across all pages on the domain.
![image](https://user-images.githubusercontent.com/15837524/126910715-1eeddce0-07a8-48ab-9ce3-ac1282709231.png)

**Comment by lassoan** [comment]
All the links now point to up-to-date locations. A few references are still left to the old wiki, because that content has not been moved yet.
