### ISSUE TITLE
Loading TIFF file but it won't load into slicer?

### ISSUE THREAD

**Issue by kanikayad15** [Slicer/Slicer#5446]
I went to load a TIFF file into Slicer, but when I hit Ok the image did not appear on the screen. The image also does not appear under the Data tab. I did not get an error message either. Why is my file not working?
## Environment
- Slicer version: Slicer-4.11.20200930
- Operating system: Mac 10.15.7 
Here's the log report if it's relevent
[DEBUG][Qt] 10.02.2021 14:51:08 [] (unknown:0) - Session start time .......: 2021-02-10 14:51:08
[DEBUG][Qt] 10.02.2021 14:51:08 [] (unknown:0) - Slicer version ...........: 4.11.20200930 (revision 29402 / 002be18) macosx-amd64 - installed release
[DEBUG][Qt] 10.02.2021 14:51:08 [] (unknown:0) - Operating system .........: Mac OS X / 10.15.7 / 19H15 - 64-bit
[DEBUG][Qt] 10.02.2021 14:51:08 [] (unknown:0) - Memory ...................: 8192 MB physical, 2048 MB virtual
[DEBUG][Qt] 10.02.2021 14:51:08 [] (unknown:0) - CPU ......................: GenuineIntel Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz, 2 cores, 4 logical processors
[DEBUG][Qt] 10.02.2021 14:51:08 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, Sequential threading
[DEBUG][Qt] 10.02.2021 14:51:08 [] (unknown:0) - Qt configuration .........: version 5.15.1, with SSL, requested OpenGL 3.2 (core profile)
[DEBUG][Qt] 10.02.2021 14:51:08 [] (unknown:0) - Developer mode enabled ...: no
[DEBUG][Qt] 10.02.2021 14:51:08 [] (unknown:0) - Prefer executable CLI ....: yes
[DEBUG][Qt] 10.02.2021 14:51:08 [] (unknown:0) - Application path .........: /Applications/Slicer.app/Contents/MacOS
[DEBUG][Qt] 10.02.2021 14:51:08 [] (unknown:0) - Additional module paths ..: /Applications/Slicer.app/Contents/Extensions-29402/SegmentEditorExtraEffects/lib/Slicer-4.11/qt-scripted-modules, /Applications/Slicer.app/Contents/Extensions-29402/MarkupsToModel/lib/Slicer-4.11/qt-loadable-modules
[DEBUG][Python] 10.02.2021 14:51:10 [Python] (/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pydicom/datadict.py:432) - Reversing DICOM dictionary so can look up tag from a keyword...
[DEBUG][Python] 10.02.2021 14:51:13 [Python] (/Applications/Slicer.app/Contents/lib/Slicer-4.11/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: Annotations
[DEBUG][Python] 10.02.2021 14:51:14 [Python] (/Applications/Slicer.app/Contents/lib/Slicer-4.11/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentEditor
[DEBUG][Python] 10.02.2021 14:51:14 [Python] (/Applications/Slicer.app/Contents/lib/Slicer-4.11/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentStatistics
[DEBUG][Qt] 10.02.2021 14:51:14 [] (unknown:0) - Switch to module:  "Welcome"
[ERROR][VTK] 10.02.2021 14:51:56 [vtkITKArchetypeDiffusionTensorImageReaderFile (0x7fe3e93117e0)] (/Volumes/D/S/S-0/Libs/vtkITK/vtkITKArchetypeDiffusionTensorImageReaderFile.cxx:166) - There is more than one file, use the vtkITKArchetypeImageSeriesReader instead
[ERROR][VTK] 10.02.2021 14:51:58 [vtkITKArchetypeImageSeriesVectorReaderSeries (0x7fe3e804f9d0)] (/Volumes/D/S/S-0/Libs/vtkITK/vtkITKArchetypeImageSeriesVectorReaderSeries.cxx:163) - Exception from vtkITK MegaMacro: 
itk::InvalidRequestedRegionError (0x7fe3e543a1f0)
Location: "unknown" 
File: /Volumes/D/S/S-0-build/ITK/Modules/IO/ImageBase/include/itkImageFileReader.hxx
Line: 339
Description: ImageIO returns IO region that does not fully contain the requested regionRequested region: ImageRegion (0x7ffee5011528)
  Dimension: 3
  Index: [0, 0, 0]
  Size: [7843, 5044, 1]
StreamableRegion region: ImageRegion (0x7ffee5011578)
  Dimension: 3
  Index: [0, 0, 0]
  Size: [7719, 5044, 1]
[ERROR][VTK] 10.02.2021 14:51:58 [vtkCompositeDataPipeline (0x6000023bae60)] (/Volumes/D/S/S-0-build/VTK/Common/ExecutionModel/vtkExecutive.cxx:782) - Algorithm vtkITKArchetypeImageSeriesVectorReaderSeries(0x7fe3e804f9d0) returned failure for request: vtkInformation (0x600000742340)
  Debug: Off
  Modified Time: 292676
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0
[ERROR][VTK] 10.02.2021 14:51:58 [vtkITKArchetypeImageSeriesScalarReader (0x7fe3e804b0e0)] (/Volumes/D/S/S-0/Libs/vtkITK/vtkITKArchetypeImageSeriesScalarReader.cxx:253) - UpdateFromSeries: Unsupported number of components: 1 != 3
[ERROR][VTK] 10.02.2021 14:51:58 [vtkMRMLNRRDStorageNode (0x7fe3e930cdd0)] (/Volumes/D/S/S-0/Libs/MRML/Core/vtkMRMLNRRDStorageNode.cxx:187) - ReadData: This is not a nrrd file
[ERROR][VTK] 10.02.2021 14:51:58 [vtkMRMLVolumeArchetypeStorageNode (0x7fe3e93115e0)] (/Volumes/D/S/S-0/Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.cxx:387) - ReadDataInternal: Cannot read file as a volume of type DiffusionTensorVolume[fullName = /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021723.tif]
	Number of files listed in the node = 0.
	File reader says it was able to read 3 files.
	File reader used the archetype file name of /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021723.tif [reader 0th file name = /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021723.tif]
FileFormatError
[ERROR][VTK] 10.02.2021 14:51:58 [vtkMRMLNRRDStorageNode (0x7fe3e804f7d0)] (/Volumes/D/S/S-0/Libs/MRML/Core/vtkMRMLNRRDStorageNode.cxx:187) - ReadData: This is not a nrrd file
[ERROR][VTK] 10.02.2021 14:51:58 [vtkMRMLVolumeArchetypeStorageNode (0x7fe3e804f7d0)] (/Volumes/D/S/S-0/Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.cxx:387) - ReadDataInternal: Cannot read file as a volume of type VectorVolume[fullName = /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021723.tif]
	Number of files listed in the node = 0.
	File reader says it was able to read 3 files.
	File reader used the archetype file name of /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021723.tif [reader 0th file name = /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021723.tif]
FileFormatError
[ERROR][VTK] 10.02.2021 14:51:58 [vtkMRMLVolumeArchetypeStorageNode (0x7fe3e80435b0)] (/Volumes/D/S/S-0/Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.cxx:387) - ReadDataInternal: Cannot read file as a volume of type Volume[fullName = /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021723.tif]
	Number of files listed in the node = 0.
	File reader says it was able to read 3 files.
	File reader used the archetype file name of /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021723.tif [reader 0th file name = /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021723.tif]
FileFormatError
[INFO][VTK] 10.02.2021 14:51:58 [vtkMRMLScene (0x7fe3eb3e3ef0)] (/Volumes/D/S/S-0/Libs/MRML/Core/vtkMRMLScene.cxx:316) - vtkMRMLScene::Clear
[ERROR][VTK] 10.02.2021 14:53:37 [vtkITKArchetypeDiffusionTensorImageReaderFile (0x7fe3a562ef60)] (/Volumes/D/S/S-0/Libs/vtkITK/vtkITKArchetypeDiffusionTensorImageReaderFile.cxx:166) - There is more than one file, use the vtkITKArchetypeImageSeriesReader instead
[ERROR][VTK] 10.02.2021 14:53:40 [vtkITKArchetypeImageSeriesVectorReaderSeries (0x7fe3a562a040)] (/Volumes/D/S/S-0/Libs/vtkITK/vtkITKArchetypeImageSeriesVectorReaderSeries.cxx:163) - Exception from vtkITK MegaMacro: 
itk::InvalidRequestedRegionError (0x7fe3e5628780)
Location: "unknown" 
File: /Volumes/D/S/S-0-build/ITK/Modules/IO/ImageBase/include/itkImageFileReader.hxx
Line: 339
Description: ImageIO returns IO region that does not fully contain the requested regionRequested region: ImageRegion (0x7ffee5010398)
  Dimension: 3
  Index: [0, 0, 0]
  Size: [7843, 5044, 1]
StreamableRegion region: ImageRegion (0x7ffee50103e8)
  Dimension: 3
  Index: [0, 0, 0]
  Size: [7719, 5044, 1]
[ERROR][VTK] 10.02.2021 14:53:40 [vtkCompositeDataPipeline (0x60000244af40)] (/Volumes/D/S/S-0-build/VTK/Common/ExecutionModel/vtkExecutive.cxx:782) - Algorithm vtkITKArchetypeImageSeriesVectorReaderSeries(0x7fe3a562a040) returned failure for request: vtkInformation (0x6000004e9240)
  Debug: Off
  Modified Time: 347977
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0
[ERROR][VTK] 10.02.2021 14:53:40 [vtkITKArchetypeImageSeriesScalarReader (0x7fe3a5627c50)] (/Volumes/D/S/S-0/Libs/vtkITK/vtkITKArchetypeImageSeriesScalarReader.cxx:253) - UpdateFromSeries: Unsupported number of components: 1 != 3
[ERROR][VTK] 10.02.2021 14:53:40 [vtkMRMLNRRDStorageNode (0x7fe3a562a4b0)] (/Volumes/D/S/S-0/Libs/MRML/Core/vtkMRMLNRRDStorageNode.cxx:187) - ReadData: This is not a nrrd file
[ERROR][VTK] 10.02.2021 14:53:40 [vtkMRMLVolumeArchetypeStorageNode (0x7fe3a562ed60)] (/Volumes/D/S/S-0/Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.cxx:387) - ReadDataInternal: Cannot read file as a volume of type DiffusionTensorVolume[fullName = /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021724.tif]
	Number of files listed in the node = 0.
	File reader says it was able to read 3 files.
	File reader used the archetype file name of /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021724.tif [reader 0th file name = /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021723.tif]
FileFormatError
[ERROR][VTK] 10.02.2021 14:53:40 [vtkMRMLNRRDStorageNode (0x7fe3a5629e40)] (/Volumes/D/S/S-0/Libs/MRML/Core/vtkMRMLNRRDStorageNode.cxx:187) - ReadData: This is not a nrrd file
[ERROR][VTK] 10.02.2021 14:53:40 [vtkMRMLVolumeArchetypeStorageNode (0x7fe3a5629e40)] (/Volumes/D/S/S-0/Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.cxx:387) - ReadDataInternal: Cannot read file as a volume of type VectorVolume[fullName = /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021724.tif]
	Number of files listed in the node = 0.
	File reader says it was able to read 3 files.
	File reader used the archetype file name of /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021724.tif [reader 0th file name = /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021723.tif]
FileFormatError
[ERROR][VTK] 10.02.2021 14:53:40 [vtkMRMLVolumeArchetypeStorageNode (0x7fe3a5627a50)] (/Volumes/D/S/S-0/Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.cxx:387) - ReadDataInternal: Cannot read file as a volume of type Volume[fullName = /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021724.tif]
	Number of files listed in the node = 0.
	File reader says it was able to read 3 files.
	File reader used the archetype file name of /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021724.tif [reader 0th file name = /Users/kanikayadav/Desktop/research pictures/2:8 downloaded/1021723.tif]
FileFormatError
[INFO][VTK] 10.02.2021 14:53:40 [vtkMRMLScene (0x7fe3e77ff9d0)] (/Volumes/D/S/S-0/Libs/MRML/Core/vtkMRMLScene.cxx:316) - vtkMRMLScene::Clear

**Comment by lassoan** [comment]
It seems that there are 3 files with similar names in the folder and the reader tries to load all 3 of them as a volume.

Probably the files do not have the exact same size or at least one of them may be multi-frame or might be corrupted.

You should be able to load it by checking "Single File" checkbox in Add data window (appears if you check "Show Options" checkbox).

**Comment by lassoan** [comment]
> Dimension: 3
Index: [0, 0, 0]
Size: [7843, 5044, 1]
StreamableRegion region: ImageRegion (0x7ffee50103e8)
Dimension: 3
Index: [0, 0, 0]
Size: [7719, 5044, 1]

This confirms that the 3 TIFF files do not have the same size, therefore you need resize them to have the same size or check "Single File" option when loading.

**Comment by lassoan** [comment]
Assuming the solution described above resolved the problem, the issue can be closed now.
