### ISSUE TITLE
Only one slice loaded when working with abdominal radiographies and version 4.10.2

### ISSUE THREAD

**Issue by jgl-sycai** [Slicer/Slicer#5473]
Hi,

Thanks for this great work. I have a problem when loading some DICOM files with which I'd require your assistance please.

I have data from abdominal CT scans and radiographies, all in DICOM format. 

One same patient has a DICOM folder for a CT scan and another for an abdominal x-ray.

Both imaging test shall be the same or very similar, however, when loading both in 3DSlicer, the CT scan loads it perfectly and all sagital, coronal and axial views are properly displayed. When loading the x-ray only one axial slide is visible and sagital and coronal views show just one slice.

This behavior happens with any version below 4.11. With the 4.11 version this does not happen and everything is displayed perfect.

Although it works good with version 4.11, I would need to load the DCM files properly with the 4.8 version since the PC I am working on has an old graphic card and only that version works.

Modality field in the metadata is "CT" in both cases

Could you help me out here please and let me know if there was any change commited that could have affected to the way DICOM files are loaded?

## Steps to reproduce

DICOM data loaded clicking on the "DCM" buttom on the upper left corner.

This is the result when loading the patient with Slicer 4.10.2 ( with lower version, the result is the same).
![imagen](https://user-images.githubusercontent.com/78298419/108484915-a6924300-729c-11eb-92ad-53b6453c2cc5.png)

This is the result when loading the patient with Slicer 4.11.20200930

![imagen](https://user-images.githubusercontent.com/78298419/108484477-223fc000-729c-11eb-930f-985da605233b.png)

**Comment by pieper** [comment]
There are continuous bug fixes and improvements so it's hard to know exactly what isn't working in the old Slicer.  It's a shame the new code doesn't run on your old PC, but we don't have resources to maintain old versions of Slicer.

If feasible, you could save out the volume as nrrd from the new version and that should work on the old version.

**Comment by lassoan** [comment]
You can also use free cloud instances of Slicer on binder: https://mybinder.org/v2/gh/slicer/SlicerNotebooks/master?filepath=SlicerWeb.ipynb

It is not as convenient as a local Slicer, you need to upload your data to the web, etc. but it may be an acceptable temporary solution until you upgrade.
