### ISSUE TITLE
Importing the numpy C-extensions failed. [slicer 4.11.20200930, archlinux]

### ISSUE THREAD

**Issue by Asteriod1** [Slicer/Slicer#5474]
When starting slicer I get a lot of errors concerning the numpy C-extensions.
...
Importing the numpy C-extensions failed.
...
Original error was: 

```
libgfortran-2e0d59d6.so.5.0.0:
ELF load command address/offset not properly aligned
```

Workaround:

```
install -c -s /usr/lib/libgfortran.so.5.0.0 \
 /opt/3dslicer/lib/Python/lib/python3.6/site-packages/numpy.libs/libgfortran-2e0d59d6.so.5.0.0
```

I also did:

```
install -c -s /usr/lib/gcc/x86_64-pc-linux-gnu/5.5.0/libgfortran.so.3.0.0 \
 /opt/3dslicer/lib/Python/lib/python3.6/site-packages/scipy.libs/libgfortran-ed201abd.so.3.0.0
```

After this slicer is starting without error messages.

Regards
Wolfgang

**Comment by sjh26** [comment]
Likely source of issue:
https://github.com/pypa/manylinux/issues/119

**Comment by sjh26** [comment]
Discourse posts:

https://discourse.slicer.org/t/slicer-stable-4-11-20210226-issue-with-scipy-package-in-linux/16354

https://discourse.slicer.org/t/slicer-4-11-20200930-cant-import-pip-installed-pillow-on-linux/14448

**Comment by Asteriod1** [comment]
Analogous to what Alex_Vergara wrote in 

https://discourse.slicer.org/t/slicer-stable-4-11-20210226-issue-with-scipy-package-in-linux/16354

reinstalling from python console solves the issue here too:

from slicer.util import pip_install
pip_install('numpy -U')

**Comment by jcfr** [comment]
Since systematically stripping  symbols from all shared library found in  `python-install/lib/python3.6/site-packages` is leading to import error, we will instead selectively strip symbols.

Here is the size of the `python-install/lib/python3.6/site-packages` directory obtained after applying different stipping strategy:

```
419M: No stripping
393M: Stripping all *.so libraries
398M: Stripping only _SimpleITK*.so library
```
