### ISSUE TITLE
Slicer 4.6.2 vs Slicer 4.11.2020090

### ISSUE THREAD

**Issue by MarinaDoshkov** [Slicer/Slicer#5476]
In Slicer 4.6.2 I was able to use left click on mouse to control contrast. I have not used Slicer for a few years and so I went back to using it and downloaded the lastest software Slicer 4.11 but I cannot figure out for life of me how to change the contrast (left click on mouse does not do anything). 

I am also having strange layout issues. Slicer 4.6.2 was nice and compact and worked well on my laptop screen but Slicer 4.11 is wide screen and runs off my screen and icons are larger and blurrier 

Lastly, I was considering going back and using Slicer 4.6.2 but the extensions I need that I was able to download in Slicer 4.11 are not available in 4.6?!

Help please! 

![Extensions in 4 11 but not in 4 6](https://user-images.githubusercontent.com/79385896/108612166-e7c94680-73b3-11eb-9633-df6a2bc26b71.JPG)
![Slicer 4 11 20200930](https://user-images.githubusercontent.com/79385896/108612167-e861dd00-73b3-11eb-9a8b-ebb8125a41d4.JPG)
![Slicer 4 6 2](https://user-images.githubusercontent.com/79385896/108612168-e8fa7380-73b3-11eb-847b-9d390b6e6014.JPG)

**Comment by lassoan** [comment]
> In Slicer 4.6.2 I was able to use left click on mouse to control contrast. I have not used Slicer for a few years and so I went back to using it and downloaded the lastest software Slicer 4.11 but I cannot figure out for life of me how to change the contrast (left click on mouse does not do anything).

Slicer has now multiple mouse modes. One of them is window/level: https://slicer.readthedocs.io/en/latest/user_guide/user_interface.html#adjusting-image-window-level

> I am also having strange layout issues. Slicer 4.6.2 was nice and compact and worked well on my laptop screen but Slicer 4.11 is wide screen and runs off my screen and icons are larger and blurrier

I guess you are using linux, which often has trouble with screen scaling. You can configure screen scaling parameters with these environment variables: https://slicer.readthedocs.io/en/latest/user_guide/settings.html#runtime-environment-variables

> Lastly, I was considering going back and using Slicer 4.6.2 but the extensions I need that I was able to download in Slicer 4.11 are not available in 4.6?!

Which extensions are you missing?

**Comment by MarinaDoshkov** [comment]
I got the contrast to work! Yay! 

I am not using Linux, just windows. 

Attachment screen capture has the list of extensions. 

Thank you so much 
Marina

**Comment by MarinaDoshkov** [comment]
Extensions missing from Slicer 4.6:   SegmentEditorExtraEffects, QuantitativeReporting, MarkupsToModel, DCMQI, SlicerDevelopmentToolbox

Thanks


From: Marina Piscitelli-Doshkov
Sent: Saturday, February 20, 2021 9:13 PM
To: Slicer/Slicer; Slicer/Slicer
Cc: Manual
Subject: RE: [Slicer/Slicer] Slicer 4.6.2 vs Slicer 4.11.2020090 (#5476)

I got the contrast to work! Yay! 

I am not using Linux, just windows. 

Attachment screen capture has the list of extensions. 

Thank you so much 
Marina

**Comment by lassoan** [comment]
Oh, yes, of course, 4.6 does not have any of those extensions. Use latest Slicer Stable or Preview Release.

**Comment by lassoan** [comment]
Which Windows version do you use? Do you have multiple displays connected to your computer? Is any of your displays high-DPI?

**Comment by MarinaDoshkov** [comment]
Just a laptop, Windows 10 home 64 bit, not sure about the screen

**Comment by lassoan** [comment]
What is your screen size (in inches) and the resolution (in pixels)?

**Comment by lassoan** [comment]
You can disable scaling (which will most likely result in much smaller buttons and text) by setting the `QT_ENABLE_HIGHDPI_SCALING` to `0` in your environment (or run `set QT_ENABLE_HIGHDPI_SCALING=0` command in a console and run `Slicer.exe`).

**Comment by jamesobutler** [comment]
@MarinaDoshkov Do you have "Make everything bigger" turned on? Slicer 4.6.2 might be old in that it never respected this scaling, but the new Slicer version is respecting this scaling.
![image](https://user-images.githubusercontent.com/15837524/108633882-c1072080-7444-11eb-89a5-aad4ae1436da.png)

**Comment by MarinaDoshkov** [comment]
That fixed it!!  THANK YOU both SOOO much! 

It is a 15in screen with 1920x1080 pixel resolution

**Comment by jamesobutler** [comment]
Closing this issue now.  @MarinaDoshkov if you have any more questions about using the newer version of Slicer you can ask over at https://discourse.slicer.org/.
