### ISSUE TITLE
Measurements update fails to build on mac factory

### ISSUE THREAD

**Issue by sjh26** [Slicer/Slicer#5481]
Error:
https://slicer.cdash.org/viewBuildError.php?buildid=2160573

Likely source:
https://github.com/Slicer/Slicer/commit/c02710d59064215150a2026f71a83554fb734ad1

**Comment by lassoan** [comment]
Thank you, I've tested on Windows and Linux, but not on macOS.

**Comment by lassoan** [comment]
Fixed in https://github.com/Slicer/Slicer/commit/aa7ff8154100367cfe926bd9ab2144ccaaaec932
