### ISSUE TITLE
Add automatic application update notification

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5502]
## Is your feature request related to a problem? Please describe.

We are trying to move towards releasing a new stable version quarterly. However, users may not be aware that a new Slicer core is available. Users also stop getting extension updates if they are not using the latest stable release.

## Describe the solution you'd like

Implement a mechanism that checks if a new version of Slicer is available. The server that queries for new Slicer versions could also collect some statistics about which Slicer versions are used and how often.

## Additional context

https://discourse.slicer.org/t/updated-slicer-binary-automatic-notification/766
https://discourse.slicer.org/t/snapshot-release-updates-and-user-notification/16341

**Comment by lassoan** [comment]
@jcfr do we know how the Slicer download site will work? It would be quite easy to implement this, but it does not make sense to implement it for the current download site if it will be replaced with another in the near future.

**Comment by lassoan** [comment]
Cautionary tale about introducing telemetry feature into an open-source software without enough open communication with the community: https://www.zdnet.com/article/audacity-reverses-course-on-plans-to-add-opt-in-telemetry-after-outcry

**Comment by jamesobutler** [comment]
See https://discourse.slicer.org/t/stable-update-notification/23655 for more brainstorming related to this issue.

**Comment by lassoan** [comment]
@jcfr could you recommend an API to check for application updates? Ideally, it would be a web API call that would take the current application name, version, revision, and operating system as inputs and it would return information on the new release (version, revision, release webpage URL).

**Comment by lassoan** [comment]
I've found that the download site already has API for this:

https://download.slicer.org/find?os=win&stability=release
https://download.slicer.org/find?os=macosx&stability=release
https://download.slicer.org/find?os=linux&stability=release

The referenced pull request uses this API to check if application update is available.
