### ISSUE TITLE
Update DCMTK to 3.6.6

### ISSUE THREAD

**Issue by fedorov** [Slicer/Slicer#5510]
## Is your feature request related to a problem? Please describe.

Update DCMTK to the latest release + an extra patch, in particular to address a bug incorrectly decoding certain types of DICOM segmentation objects.

## Describe the solution you'd like

Cherry-pick extra commit into the latest DCMTK 3.6.6 release and make a PR to Slicer.

## Describe alternatives you've considered

Not upgrading DCMTK.

## Additional context

https://github.com/QIICR/dcmqi/issues/341#issuecomment-707053566 and the following comments, and #5503.

If there are no objections, I can work on a PR.

**Comment by lassoan** [comment]
No objections, please send a pull request. Thank you!

**Comment by fedorov** [comment]
Currently, we use DCMTK 3.6.5 directly from the DCMTK repo. In the past, we used to keep patched DCMTK versions in https://github.com/InsightSoftwareConsortium/DCMTK. 

Would you prefer to put the patched version under https://github.com/InsightSoftwareConsortium/DCMTK, or create a new repo under the Slicer org?

**Comment by jcfr** [comment]
If the extra commit is not yet in upstream, consider creating a branch called `patched-DCMTK-3.6.6_20210115` in https://github.com/commontk/DCMTK/ and then cherry pick the commit prepending the string `[Backport] ` or `[Backport PR-NNN] ` to the commit title.

**Comment by pieper** [comment]
If the ITK community also needs the patch, that would the logical home to use in both Slicer and dcmqi, since it's a mutual dependency.  If for some reason they don't want to then Slicer or CTK makes sense.

**Comment by fedorov** [comment]
I don't have any preference, so I will go with @jcfr advice.

**Comment by jcfr** [comment]
>  I will go with @jcfr advice.

I just checked and you have write access to https://github.com/commontk/DCMTK/ a

Thanks for your help with this :pray:

**Comment by fedorov** [comment]
Yes, I've just pushed the branch. I will test on the dcmqi side, and then proceed with a PR to Slicer.

**Comment by jcfr** [comment]
For future reference, see https://github.com/commontk/DCMTK/tree/patched-DCMTK-3.6.6_20210115

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/Slicer/Slicer/pull/5511
