### ISSUE TITLE
Make plane markups widget more similar to ROI markups widget

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5519]
It is very hard to set the size of a plane widget using node methods. It is not very clear how it is supposed to work.

## Describe the solution you'd like

There should be a SetSize method, similarly to ROI markups widget.

Overall, the ROI markups widget API is much more intuitive.
It would be great if plane widget would have a similar API (except of course Size property would be just 2-dimensional).

GUI for placement and adjustment could work similarly, too, with a single markup in the middle and handles for the corner points.

There could be a single-click place mode where plane normal would be taken from the normal of the slice plane (in slice view) or surface normal of the picked object (in 3D views).

**Comment by lassoan** [comment]
@Sunderlandkyl could you work on this in the next few weeks (before the Slicer5 release)?

**Comment by Sunderlandkyl** [comment]
Yes, I have been working on it this week.
