### ISSUE TITLE
Create new Linux archive for stable release including unstripped python libraries

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5525]
## Is your feature request related to a problem? Please describe.

The latest linux stable release include stripped python modules preventing used from importing module like scipy.
See https://github.com/Slicer/Slicer/issues/5474

## Describe the solution you'd like

1. Download and manually fixup the linux archive by including unstripped linux modules. This could be done by integrating the site-packages directory still available on `metroplex` factory
2. Re-upload package on slicer.kitware.com and ensure the new package is considered by download.slicer.org

## Describe alternatives you've considered

Create a new release ...

1. Update https://github.com/Slicer/Slicer/commits/v4.11 accordingly
2. Cherry-pick relevant commits (see https://github.com/Slicer/Slicer/pull/5524)
3. Create a new release

## Additional context

NA

**Comment by lassoan** [comment]
The problem is fixed now.

**Comment by jcfr** [comment]
Since we will soon release Slicer 5 and the original issue has been fixed in https://github.com/Slicer/Slicer/pull/5524/commits/e72d3e875995866d571cd3f6907aed697b020fb4, we will not spend time to address this.
