### ISSUE TITLE
stuck module window slicer version 4.11.20210226

### ISSUE THREAD

**Issue by delants** [Slicer/Slicer#5534]
## Steps to reproduce

Upon uploading new data, the intro window which is also the module window is stuck in the center with no exit option or ability to move it, I can move the main window around behind it, but that's it, it remains stuck and foreground

## Environment

* Slicer version 4.11.20200930 as well as in slicer version 4.11.20210226

**Comment by jcfr** [comment]
Thanks for reporting the issue :pray: 

To help us understand the problem, could you be more specific regarding the steps needed to reproduce the problem ?

For example, what do you mean by "uploading new data"  ? Providing screenshots or even making a video would be very helpful.

**Comment by lassoan** [comment]
Can you share an example data set that reproduces this? (upload to dropbox/onedrive/google drive and post the link here)

Please also share the application log of a failed session. If you cannot go to menu: Help / Report a bug in the session where the window is stuck then restart Slicer and in "Report a bug" window, select the previous session.

**Comment by delants** [comment]
Apologies I'm still quite new to slicer! Also, the issue occurred regardless of attempting to load data- the menu was stuck upon opening the application
It has mysteriously resolved itself, but here is the log from the previous session
Log from previous session: 

[DEBUG][Qt] 17.03.2021 12:42:31 [] (unknown:0) - Session start time .......: 2021-03-17 12:42:31
[DEBUG][Qt] 17.03.2021 12:42:31 [] (unknown:0) - Slicer version ...........: 4.11.20210226 (revision 29738 / 7a593c8) win-amd64 - installed release
[DEBUG][Qt] 17.03.2021 12:42:31 [] (unknown:0) - Operating system .........: Windows /  Personal / (Build 18363, Code Page 65001) - 64-bit
[DEBUG][Qt] 17.03.2021 12:42:31 [] (unknown:0) - Memory ...................: 7937 MB physical, 19355 MB virtual
[DEBUG][Qt] 17.03.2021 12:42:31 [] (unknown:0) - CPU ......................: GenuineIntel , 8 cores, 8 logical processors
[DEBUG][Qt] 17.03.2021 12:42:31 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, TBB threading
[DEBUG][Qt] 17.03.2021 12:42:31 [] (unknown:0) - Qt configuration .........: version 5.15.1, with SSL, requested OpenGL 3.2 (compatibility profile)
[DEBUG][Qt] 17.03.2021 12:42:31 [] (unknown:0) - Developer mode enabled ...: no
[DEBUG][Qt] 17.03.2021 12:42:31 [] (unknown:0) - Prefer executable CLI ....: yes
[DEBUG][Qt] 17.03.2021 12:42:31 [] (unknown:0) - Application path .........: C:/Users/delan/AppData/Local/NA-MIC/Slicer 4.11.20210226/bin
[DEBUG][Qt] 17.03.2021 12:42:31 [] (unknown:0) - Additional module paths ..: (none)
[DEBUG][Python] 17.03.2021 12:42:47 [Python] (C:\Users\delan\AppData\Local\NA-MIC\Slicer 4.11.20210226\lib\Python\Lib\site-packages\pydicom\datadict.py:432) - Reversing DICOM dictionary so can look up tag from a keyword...
[DEBUG][Python] 17.03.2021 12:43:01 [Python] (C:\Users\delan\AppData\Local\NA-MIC\Slicer 4.11.20210226\lib\Slicer-4.11\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: Annotations
[DEBUG][Python] 17.03.2021 12:43:04 [Python] (C:\Users\delan\AppData\Local\NA-MIC\Slicer 4.11.20210226\lib\Slicer-4.11\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentEditor
[DEBUG][Python] 17.03.2021 12:43:04 [Python] (C:\Users\delan\AppData\Local\NA-MIC\Slicer 4.11.20210226\lib\Slicer-4.11\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentStatistics
[DEBUG][Qt] 17.03.2021 12:43:04 [] (unknown:0) - Switch to module:  "Welcome"
[INFO][VTK] 17.03.2021 12:43:53 [vtkMRMLVolumeArchetypeStorageNode (0000021B280D84B0)] (D:\D\S\Slicer-1\Libs\MRML\Core\vtkMRMLVolumeArchetypeStorageNode.cxx:509) - Loaded volume from file: C:/Users/delan/OneDrive/Desktop/Ant Images/9860.czi - use.tif. Dimensions: 1024x1024x63. Number of components: 1. Pixel type: unsigned char.
[DEBUG][Qt] 17.03.2021 12:43:53 [] (unknown:0) - "Volume" Reader has successfully read the file "C:/Users/delan/OneDrive/Desktop/Ant Images/9860.czi - use.tif" "[0.35s]"
[DEBUG][Qt] 17.03.2021 12:44:16 [] (unknown:0) - Switch to module:  ""

**Comment by lassoan** [comment]
Everything looks normal in the log. Based on the additional information you provided, it seems that you undocked the module panel by drag-and-dropping its title bar.

You can move the toolbar anywhere you like or dock it to the left or right side of the application by dragging its title bar; or move it to default left-side docked position using menu: View / Reset to default.

**Comment by jcfr** [comment]
I am wondering if the fact the data are "onedrive" could have caused some issue. For example, while the files are fully synced locally.

**Comment by lassoan** [comment]
No further information was received from the user, closing the issue now.
