### ISSUE TITLE
website: Slicer logo should link back to landing page

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5538]
## Is your feature request related to a problem? Please describe.

User may easily get "lost" while browsing. 

## Describe the solution you'd like

To allow user to easily go back to a simple page, clicking on "slicer logo" should have a similar and consistent outcome for all slicer websites. It should go back to main slicer.org landing page.

![image](https://user-images.githubusercontent.com/219043/111791895-11359f00-889a-11eb-89e0-2422455b2bbe.png)

## Describe alternatives you've considered

NA

## Additional context

NA

**Comment by lassoan** [comment]
Do you mean you would make the link on the Slicer icon on readthedocs point to www.slicer.org?

**Comment by jcfr** [comment]
> Do you mean you would make the link on the Slicer icon on readthedocs point to www.slicer.org?

Indeed, I updated the description to be more explicit

**Comment by lassoan** [comment]
I've never seen that project on redthedocs where that top-left icon went anywhere else than the documentation root. I would find it very confusing. Since the documentation is opened in a new tab anyway, the user can simply close the tab to get back to the landing page.

**Comment by jamesobutler** [comment]
Indeed I would expect clicking on that logo to go to home page for the documentation. Not the slicer.org page which is on a different domain and doesn’t have the same type navigation as the documentation.

**Comment by jcfr** [comment]
Agreed with your assessment, looking at these websites also confirm this:
* https://jupyter.readthedocs.io/en/latest/index.html
* https://pandas.pydata.org/docs/index.html

Thanks for taking the time to discuss this. Now closing.

**Comment by jcfr** [comment]
Alternatively, we could probably have a "Useful links" section like what is done here: https://requests.readthedocs.io/en/latest/user/quickstart/

![image](https://user-images.githubusercontent.com/219043/111829144-b06e8c80-88c2-11eb-96d0-7693854a9745.png)

**Comment by jcfr** [comment]
To provide some background, this issue was originally created after sharing recent website and documentation updates with @rkikinis

**Comment by lassoan** [comment]
Having some kind of a navigation bar on all Slicer websites (landing page, download, readthedocs, discourse, github, dashboard, wiki, twitter, youtube, ...) that allow jumping between all these sites could be useful. Not easy to implement it consistently, though. Maybe just a link back to the landing page from everywhere would be enough.
