### ISSUE TITLE
Interactive handles of markups plane don't transform well after transform is hardened

### ISSUE THREAD

**Issue by mauigna06** [Slicer/Slicer#5539]
interactiveHandles of plane don't transform well after transform is hardened

## Steps to reproduce

1. Create a plane
2. Activate the interaction handles
3. Create a new linear transform and set up a rotation
4. Apply the linear transform to the plane
5. Harden the transform

![Screenshot9](https://user-images.githubusercontent.com/19158307/111827638-e1ea5680-88c8-11eb-8e8c-61000f1b57e4.png)

## Expected behavior

![Screenshot_1](https://user-images.githubusercontent.com/19158307/111827687-f4fd2680-88c8-11eb-8222-d6faca192d10.png)

## Environment
- Slicer version: Slicer-4.13.0-2021-03-09
- Operating system: Windows x64

**Comment by lassoan** [comment]
I agree, this is not the expected behavior. The markups plane node is new and there are still bugs and API improvements in progress.

@Sunderlandkyl this can be probably fixed along with this related issue: https://github.com/Slicer/Slicer/issues/5519

**Comment by mauigna06** [comment]
Thanks Andras for such a fast response
