### ISSUE TITLE
Extension Manager not loading available extensions

### ISSUE THREAD

**Issue by FedericoGnesotto** [Slicer/Slicer#5542]
When opening the extension manager and switching to the "Install Extensions" tabs, the manager displays the "Loading extension" message indefinitely. 
I also get the following messages in the Log:
```
Uncaught TypeError: A.widget is not a function
Uncaught TypeError: extDiv.find(...).attr(...).stars is not a function
```
I suspect that this might have to do with the local network on this machine, since I tried a similar machine on another network and there I could not encounter this issue.

Any ideas on how to solve this?

Thanks a lot for your suggestions

## Environment
- Slicer version: Slicer-4.13.0-2021-04-09
- Operating system: Windows

**Comment by lassoan** [comment]
You can try to configure your network proxy manually and if it does not work then install extensions manually. See details here: https://slicer.readthedocs.io/en/latest/user_guide/extensions_manager.html#extensions-manager-does-not-show-any-extensions

**Comment by FedericoGnesotto** [comment]
Thank you @lassoan , I managed to configure Internet Explorer to use my network proxy and now the extensions load correctly. I also followed this [post](https://discourse.slicer.org/t/using-slicer-behind-proxy/6545). Maybe it makes sense to mention this in the guidelines?

**Comment by FedericoGnesotto** [comment]
I am now experiencing a similar issue with a newly built slicer version: when I open the extension manager to install extensions I get the following error (see screenshot): `No extensions found for win:64-bit, revision: '29876'. Please try a different combination`. Any ideas? Thanks
![Annotation 2021-05-14 121156](https://user-images.githubusercontent.com/79929002/118256413-b8574100-b4ad-11eb-8f52-7f4eda8e59b3.png)

**Comment by lassoan** [comment]
We are upgrading our server. Disruptions are expected. Please monitor this topic (and add any questions/comments/requests there): https://discourse.slicer.org/t/upcoming-downtime-for-download-slicer-org-and-extension-manager-due-to-package-server-transition/17444/2
