### ISSUE TITLE
Slice intersections appear white in 3D view when no volume displayed

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#5550]
The Slice Intersections are not showing with their corresponding color in the 3D View on first startup as they previously have been. I tested with Slicer-4.13.0-2021-02-03 and Slicer-4.13.0-2021-02-04 and it works in the first and stops working in the later version. Likely cuprit is commit e78f557cd0cc70587e6dc01fa4983447462b0db6 from 2021-02-04. The problem also exists in latest Slicer Preview Slicer-4.13.0-2021-03-24.

## Steps to reproduce

1. Open 3D Slicer
2. Link Slice Controls
3. Toggle Slice View visibility on
4. Observe Slice views in the 3D View

![image](https://user-images.githubusercontent.com/15837524/112553955-d4870d80-8d9b-11eb-9d4d-14f38dd48aa3.png)

5. Clear the scene. (File->Close Scene or `slicer.mrmlScene.Clear()`)
7. Link Slice Controls and Toggle Slice View visibility on
8. Observe Slice views in the 3D View are now showing with their appropriate color

![image](https://user-images.githubusercontent.com/15837524/113902861-57e22f00-979e-11eb-8bdc-125d4c367986.png)

## Expected behavior

1. Open 3D Slicer
2. Link Slice Controls
3. Toggle Slice View visibility on
4. Observe Slice views in the 3D View with the appropriate colors.
![image](https://user-images.githubusercontent.com/15837524/112553899-b9b49900-8d9b-11eb-9242-6354f4059840.png)

## Environment
- Slicer version: Slicer-4.13.0-2021-02-04
- Operating system: Windows 10

**Comment by jamesobutler** [comment]
@lassoan I see you tagged this with the VTK 9 label. Did you determine that this doesn’t happen with VTK8? The commit that introduced the issue didn’t seem to me like it would be different based on VTK version.

**Comment by lassoan** [comment]
First it looked like it could be related to the VTK9 switch, which happened around the same time when this issue cropped up, but if you pinpointed the exact commit then it is most likely independent of VTK9. I'll remove the VTK9 tag.

It is quite rare to show empty slices and if the slice is empty then it is not a huge issue to not know which view it belongs to. So, fixing it it seems lower priority than most other issues that we are working on currently. It would be great if you have time to investigate and fix this, but if not then probably we'll get to it in a few months.

**Comment by jamesobutler** [comment]
https://github.com/Slicer/Slicer/commit/a1c44fab014a6be93e5917fe63ffee3a98dba597 ❌ [Slicer 4.13.0-2022-01-26](https://slicer-packages.kitware.com/api/v1/file/61f12c2d342a877cb3063a52/download)
.
.
https://github.com/Slicer/Slicer/commit/169638177c555484f4524e60d78859aec52408b5 ✔️ [Slicer 4.13.0-2022-01-27](https://slicer-packages.kitware.com/api/v1/file/61f2e57b342a877cb306fedb/download)

Therefore this issue was liked fixed by changes made in https://github.com/Slicer/Slicer/commit/bc5d5b45fcb1949a2545ee1c2e2c1f35976698ac.

I can also confirm that this is also not an issue in latest Slicer stable 5.0.3.
