### ISSUE TITLE
Extension Manager is empty

### ISSUE THREAD

**Issue by sulaimanvesal** [Slicer/Slicer#5554]
I have tried to install several version of 3D Slicer on Mac machine in the past few days to use SlicerJupyter extension for file conversion (STL to NRRD), but it shows an empty page when I open extension manager.

**Comment by lassoan** [comment]
I've just checked and extensions appear correctly for latest Slicer Preview Release (2021-03-26).

See troubleshooting instructions here: https://slicer.readthedocs.io/en/latest/user_guide/extensions_manager.html#troubleshooting

If you still have problems then please attach a screenshot.

**Comment by sulaimanvesal** [comment]
I have checked the troubleshooting instructions before, but none of them really helped me out. Below, you can see the screenshot of my Extension Manager. I see only a transparent small window with "read more" link, which redirect me to the slicer webpage. 

![image](https://user-images.githubusercontent.com/20819071/112740588-f36bd800-8f32-11eb-9e3d-24749c316a9e.png)

**Comment by lassoan** [comment]
You need to install Slicer (drag-and-drop Slicer.app to Applications) as described in [installation instructions](https://slicer.readthedocs.io/en/latest/user_guide/getting_started.html#mac).

The washed out appearance is a problem that was observed on older macbooks (see details [here](https://github.com/Slicer/Slicer/issues/5118)). Could you take a screenshot of your system information window so that we can see what your exact software and hardware configuration is? Note that you can still use the extension manager, it is just harder to see the content. A workaround is to manually set macOS to use dark mode.

**Comment by sulaimanvesal** [comment]
I can confirm that setting macOS to dark mode worked for me. Thank you for your prompt help @lassoan 

![image](https://user-images.githubusercontent.com/20819071/112743779-1b693480-8f4f-11eb-9dc1-e5a1bbb93775.png)

**Comment by lassoan** [comment]
Great!
Could you take a screenshot of your system information window so that we can see what your exact software and hardware configuration is? (we are trying to figure out why this problem happens only on certain systems and each new data point helps)

**Comment by sulaimanvesal** [comment]
Sure, here is the screenshot of my system information (I guess, my MacBook is old, and maybe because of my old graphic card, this issue raised, but not very sure):

![image](https://user-images.githubusercontent.com/20819071/112744148-44d78f80-8f52-11eb-8724-e82d8ee7cec4.png)

**Comment by lassoan** [comment]
Thank you, this is useful. It fits the pattern that we have been seeing.

If you had time to test this a bit further... Could you check if you set your dark mode settings to the original (I guess it was "auto") and enter this in the terminal windows before launching ./Slicer (in the same terminal), and see if the extension manager looks any different:

```
export QTWEBENGINE_CHROMIUM_FLAGS=--blink-settings=darkMode=4,darkModeImagePolicy=2
```

It would be nice if you could try with different values, too: for `darkMode` try 0, 1, 2, 3, 4; for `darkModeImagePolicy` try 0, 1, 2 (based on values documented [here](https://chromium.googlesource.com/chromium/src/+/refs/tags/77.0.3865.0/third_party/blink/renderer/platform/graphics/dark_mode_settings.h)).

Thank you!

**Comment by lassoan** [comment]
Closing this issue now. Issue #5118 keeps tracking the status of this problem.

**Comment by sulaimanvesal** [comment]
Hi @lassoan,

Sorry I got busy but I have tested what you said.  I have set my dark-mode to "auto", and here is the output (same wash-out):

![image](https://user-images.githubusercontent.com/20819071/113226014-f96bfc80-9243-11eb-9971-968af2bbd660.png)

**Comment by lassoan** [comment]
Too bad that the flags did not make any difference. Thanks a lot for testing and reporting back anyway.
