### ISSUE TITLE
Add API to Slicer so that a markups node can be moved using the interactions handle only in certain directions

### ISSUE THREAD

**Issue by mauigna06** [Slicer/Slicer#5558]
## Is your feature request related to a problem? Please describe.

Sometimes is needed to let the user only move a plane with a certain axis of the interactions handle.

## Describe the solution you'd like

Add API to Slicer so that a markups node can be moved using the interactions handle only in certain directions.
Here is one example of what I would like:
`markupsNode = getNode('myMarkupsNodeName')`
`displayNode = markupsNode .GetDisplayNode()`
`displayNode.HandlesInteractiveOn()`
`displayNode.HandlesInteractiveTranslateAlongXAxisOn()`
`displayNode.HandlesInteractiveTranslateAlongYAxisOn()`
`displayNode.HandlesInteractiveTranslateAlongZAxisOff()`
`displayNode.HandlesInteractiveRotateAroundXAxisOff()`
`displayNode.HandlesInteractiveRotateAroundYAxisOff()`
`displayNode.HandlesInteractiveRotateAroundZAxisOn()`

I would like interaction handles show all axes like right now, but only the specified axis (above) to be interactive.

**Comment by lassoan** [comment]
@Sunderlandkyl what do you think about adding

bool RotationHandleAxes[3];
bool ScaleHandleAxes[3];
bool TranslationHandleAxes[3];

to vtkMRMLMarkupsDisplayNode that would further filter the visibility of handles?

We would not need to add GUI (to keep things simpler for users and save developer time) and we could decide to write only non-default configuration to MRML scene (if all 3 axes are enabled we would not set the attribute).

**Comment by Sunderlandkyl** [comment]
Sure, that makes sense to me.
