### ISSUE TITLE
Multivolume data load bug

### ISSUE THREAD

**Issue by selmanca** [Slicer/Slicer#5560]
It is probably a simple bug because when I installed vtk on Conda, "vtk.VTK_MAJOR_VERSION" works but on Slicer it can't find it.
When I try to load multivolume DICOM images it gives this problem.
```
Loading with imageIOName: GDCM
Window/level found in DICOM tags (center=5205.0, width=10411.0) has been applied to volume 7: SAG T2MAP
Failed to read a multivolume: module 'vtkmodules.all' has no attribute 'VTK_MAJOR_VERSION'
Traceback (most recent call last):
  File "C:/Users/selma/AppData/Local/NA-MIC/Slicer 4.13.0-2021-03-30/bin/../lib/Slicer-4.13/qt-scripted-modules/MultiVolumeImporterPlugin.py", line 665, in load
    if vtk.VTK_MAJOR_VERSION <= 5:
AttributeError: module 'vtkmodules.all' has no attribute 'VTK_MAJOR_VERSION'
Could not load: SAG T2MAP - as a 8 frames MultiVolume by EchoTime as a MultiVolume
```
![Screenshot_1](https://user-images.githubusercontent.com/67283781/113198199-4f559a00-926e-11eb-863d-2c9e391f2a9e.jpg)

## Steps to reproduce

When I try to load multivolume DICOM images it gives this problem.

## Expected behavior

To work

## Environment
- Slicer version: Slicer-4.13.0-2021-03-30 r29806
- Operating system: Windows 10

**Comment by lassoan** [comment]
Thanks for reporting.

VTK9 does not have vtk.VTK_MAJOR_VERSION and so `vtk.vtkVersion().GetVTKMajorVersion()` must be used instead. But since we don't support VTK5 for a really long time we'll just remove the old code.

**Comment by selmanca** [comment]
Thank you for your attention.
I am closing the issue

**Comment by lassoan** [comment]
We are working on removing the code parts that are no longer compatible with VTK9.

**Comment by jcfr** [comment]
@lassoan Thanks for the pull requests, corresponding changes have been reviewed and integrated.
