### ISSUE TITLE
fcsv files are slow to load due to extra computation

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#5564]
See: https://discourse.slicer.org/t/read-performance-between-json-and-fcsv

There is a lot of updating of display nodes (scalar range and parametric curves) each time a point is inserted.

## Steps to reproduce

Access data linked in discussion above (3400 fiducials).  Json data loads instantly, fcsv takes a few minutes.

## Expected behavior

The load speed should be basically the same for both.

## Environment
- Slicer version: Slicer-4.22.20210226
- Operating system: mac big sur

**Comment by lassoan** [comment]
I'll have a look at unnecessary updates during adding/removing points in bulk.

**Comment by pieper** [comment]
> I'll have a look at unnecessary updates during adding/removing points in bulk.

Thanks!  I'm happy to help too, but I'm sure you know this part of the code better than I do.
