### ISSUE TITLE
Report testing failures on windows

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5572]
## Is your feature request related to a problem? Please describe.

Solution described below will ensure relevant error are logged into the dashboard when test fail on windows. (see also https://github.com/Slicer/Slicer/issues/2934)

## Describe the solution you'd like

Was originally suggested by @lassoan in https://mantisarchive.slicer.org/view.php?id=2934#c12991, on windows we suggest to:
* build `Slicer-real.exe` and `SlicerWithConsole-real.exe`
* configure two launchers `Slicer.exe` and `SlicerWithConsole.exe`
* update macro `slicerMacroBuildApplication` removing the option `Slicer_HAS_CONSOLE_IO_SUPPORT` and systematically configure two launchers and two build two executables.
* update [CMakeLists.txt](https://github.com/Slicer/Slicer/blob/b538adb1cf2ade75aaef945c788713212b46b274/CMakeLists.txt#L680-L681 with ) to set `Slicer_LAUNCHER_EXECUTABLE` using `WithConsole` suffix

  ```diff
  +set(Slicer_APPLICATION_NAME_SUFFIX "")
  +if(WIN32)
  +  set(Slicer_APPLICATION_NAME_SUFFIX "WithConsole")
  +endif()
  +set(Slicer_LAUNCHER_EXECUTABLE ${_slicer_dir}/${Slicer_MAIN_PROJECT_APPLICATION_NAME}${Slicer_APPLICATION_NAME_SUFFIX}${CMAKE_EXECUTABLE_SUFFIX})
  -set(Slicer_LAUNCHER_EXECUTABLE ${_slicer_dir}/${Slicer_MAIN_PROJECT_APPLICATION_NAME}${CMAKE_EXECUTABLE_SUFFIX})
  ```

## Describe alternatives you've considered

Setup an additional dashboard with `Slicer_BUILD_WIN32_CONSOLE` enabled (see 

## Additional context

NA

**Comment by jcfr** [comment]
cc: @sjh26 @lassoan

**Comment by jamesobutler** [comment]
I believe this has been resolved by @lassoan with https://github.com/Slicer/Slicer/commit/8eaa925245a96cf46d6c2baab72bc7c07b6e3aa3. I'm observing an extension (SlicerProstate) built on the Windows factory build machine reporting console output for a failed test (https://slicer.cdash.org/test/19283460) which prior to https://github.com/Slicer/Slicer/commit/8eaa925245a96cf46d6c2baab72bc7c07b6e3aa3 produced an empty output (https://slicer.cdash.org/test/19211234).

**Comment by lassoan** [comment]
Indeed, this issue is fixed now.
