### ISSUE TITLE
Segment Editor's Erase effect "Erase all segments" option only erase current segment

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5584]
Segment Editor's Erase effect, if "Erase all segments" checkbox is checked then painting strokes in views should erase from all segments, but it only erases from the currently segment.

## Steps to reproduce

- Load MRHead
- Create 3 segments and paint a few strokes.
- Click Erase effect, check "Erase all segments" option
- Click-and-drag in slice views => only the currently selected segment is erased from

## Expected behavior

The strokes should erase content from all segmentes.

## Environment
- Slicer version: Slicer-4.13.0-2021-03-27
- Operating system: Windows10

**Comment by lassoan** [comment]
This issue is still present in Slicer-4.13.0-2021-07-24.

**Comment by jcfr** [comment]
@Sunderlandkyl  If you didn't already start to work on this, we would like to assign this issue to a new developer  that just joined our team. What do you think ?

**Comment by Sunderlandkyl** [comment]
Currently working on it. It's been rolled into some other updates that I'm making. Should be done soon.
