### ISSUE TITLE
Make markups ROI node API more convenient

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5588]
In all VTK classes, vectors can be either set as separate x,y,z values or as an xyz vector. Many properties of vtkMRMLMarkupsROINode can only be set as xyz vector:

```
>>> roiNode.SetCenter(20,30,40)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: SetCenter() takes exactly 1 argument (3 given)
>>> roiNode.SetCenter([20,30,40])
>>> 
```

We need variants of methods that allow setting vectors as 3 scalar arguments.

**Comment by Sunderlandkyl** [comment]
SetCenter/SetSize functions now have methods (added in 4c170cd7527a1cd2c1360d89d0fa6e54779064ad) accepting both vectors and individual components.
