### ISSUE TITLE
qSlicerCoreApplication::application()->moduleManager()->module("VolumeRendering")

### ISSUE THREAD

**Issue by NeoPi** [Slicer/Slicer#5593]
In my project, I have the following code：
`qSlicerAbstractCoreModule* volumeRenderingModule =
		qSlicerCoreApplication::application()->moduleManager()->module("VolumeRendering");
vtkSlicerVolumeRenderingLogic* volumeRenderLogic = 
		volumeRenderingModule ? vtkSlicerVolumeRenderingLogic::SafeDownCast(volumeRenderingModule->logic()) : 0;
if (!volumeRenderLogic) return;	`

The program always fails to get the expected value of `volumeRenderingModule `

How can I fix it?

## Environment
- Slicer version: Slicer-4.4
- Operating system: Windows 7/ Windows10

**Comment by jcfr** [comment]
If this code is added to a loadable module, make sure your module depends on the `VolumeRendering` module by listing it as a dependency.

For example:

https://github.com/Slicer/Slicer/blob/dd5b27fc7c46eb43225910c0ff3831e5f3d7c41c/Modules/Loadable/Transforms/qSlicerTransformsModule.cxx#L76-L81

**Comment by jcfr** [comment]
>  Slicer version: Slicer-4.4

That seems incorrect, which one is the SHA of your Slicer checkout ?
