### ISSUE TITLE
Segment editor: constrain Draw and Scissors to horizontal or vertical lines

### ISSUE THREAD

**Issue by ferdymercury** [Slicer/Slicer#5605]
## Is your feature request related to a problem? Please describe.
It's hard to draw a contour that is perfectly flat in one dimension.

## Describe the solution you'd like
A modifer of the Draw and Scissors tool, e.g. while pressing CTRL, that only allows horizontal or vertical lines. As done e.g. in Inkscape. Maybe also with a check-button to allow 45 deg ones?
Alternatively, a Rectangle Tool.

## Describe alternatives you've considered
Doing it with the Python interactor.

## Additional context
Useful for creating e.g. a support structure that lies flat on the couch.

**Comment by lassoan** [comment]
All these features are already available in Scissors tool. You can draw support structure from any point to the bottom with free-hand drawn shape, rectangular, or cylindrical shape. You can also draw horizontal or vertical line in a slice plane by choosing rectangle shape.

**Comment by ferdymercury** [comment]
Thanks for the fast reply. This is indeed helpful, however non-intuitive to reach from the user-interface point of view.
Could a comment be added on the "Draw Tool" extra-details, saying:
If you want to draw horizontal / vertical lines, use the "Scissor Tool" instead.

**Comment by jamesobutler** [comment]
Agreed that it is not intuitive. I would expect something named "Scissors" would only do subtractive functions not additive (Fill Inside, Fill Outside). 

@lassoan It would be nice to merge "Scissors" additive functionality with the "Draw" effect. Thereby creating a Draw/Cut pair just like how Paint/Erase are related pairs with one being additive and one being subtractive.

**Comment by lassoan** [comment]
Yes, maybe something like "Lasso" would be less misleading. Sometimes we find better names years after we come up with the initial name, but then we don't want to upset existing users by "moving the cheese" without a very good reason.

I agree that the Draw and Scissors effect should be merged. I've been thinking about this new tool and it should no be hard to implement it at all. I've described it in detail here: https://github.com/Slicer/Slicer/issues/5606
