### ISSUE TITLE
Segmentations move when segment editor is opend

### ISSUE THREAD

**Issue by JensVanlommel** [Slicer/Slicer#5615]
When i load a scene that i want to adjust and open segment editor, the segments move to a different location and i'm not able to edit the segments, nor can i move through the slides of my MRI.

## Steps to reproduce

Loaded a scene of segmentations of an MRI. clicked on segment editor. after which the segmetations moved. I can only adjust the volume of the segmentations, no other adjustments can be made nor can i move through the slides of my MRI

## Expected behavior

being able to adjust my segmentations

## Environment
- Slicer version: Slicer-4.??.?-YYYY-MM-DD
- Operating system:  Mac version 11.1

**Comment by pieper** [comment]
Thanks for the report.  Can you provide steps to reproduce this with public data?

**Comment by lassoan** [comment]
For your convenience, when you open a segmentation, the master volume that was displayed last time when the segmentation was edited gets displayed automatically in slice viewers. This changes the field of view and (and so which parts of the segmentation is displayed) and also limits the slice selector to the region of thile master volume. 

You can either change the master volume in the Segment Editor or change background volume in slice views to the volume that you would like to see while editing the segmentation.
