### ISSUE TITLE
Cannot extract using Firmware Mod Kit

### ISSUE THREAD

**Issue by leensky1027** [Slicer/Slicer#5617]
CAN ANYONE HELP, I HAVE THIS ERROR EVERYTIME I TRY TO EXTRACT FIRMWARE USING FMK.
THANKS

bff_huffman_decompress.c: In function ‘unpack_parse_header’:
bff_huffman_decompress.c:167:14: warning: implicit declaration of function ‘read’; did you mean ‘fread’? [-Wimplicit-function-declaration]
  167 |  bytesread = read(in, hdr + prelen, PACK_HEADER_LENGTH - prelen);
      |              ^~~~
      |              fread
bff_huffman_decompress.c: In function ‘unpack’:
bff_huffman_decompress.c:318:22: warning: implicit declaration of function ‘dup’ [-Wimplicit-function-declaration]
  318 |  unpack_parse_header(dup(in), dup(out), pre, prelen, bytes_in, &unpackd);
      |                      ^~~
uncramfs.c: In function ‘do_file’:
uncramfs.c:231:28: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  231 |       srcdata=(const u8*)(((u32)(base+offset)+blksize-1) & ~(blksize-1));
      |                            ^
uncramfs.c:231:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  231 |       srcdata=(const u8*)(((u32)(base+offset)+blksize-1) & ~(blksize-1));
      |               ^
uncramfs.c: In function ‘do_chrdev’:
uncramfs.c:324:35: warning: implicit declaration of function ‘major’ [-Wimplicit-function-declaration]
  324 |       snprintf(s, 17, "%3d, %3d", major(size), minor(size) );
      |                                   ^~~~~
uncramfs.c:324:48: warning: implicit declaration of function ‘minor’; did you mean ‘mincore’? [-Wimplicit-function-declaration]
  324 |       snprintf(s, 17, "%3d, %3d", major(size), minor(size) );
      |                                                ^~~~~
      |                                                mincore
uncramfs.c: In function ‘main’:
uncramfs.c:727:29: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
  727 |    printf("[Volume size: 0x%x]\n", fslen_ub);
      |                            ~^      ~~~~~~~~
      |                             |      |
      |                             |      size_t {aka long unsigned int}
      |                             unsigned int
      |                            %lx
/usr/bin/ld: /tmp/ccUBpWp7.o: in function `do_chrdev':
/mnt/c/Users/LEENSKY/desktop/fmk/src/uncramfs/uncramfs.c:324: undefined reference to `minor'
/usr/bin/ld: /mnt/c/Users/LEENSKY/desktop/fmk/src/uncramfs/uncramfs.c:324: undefined reference to `major'
/usr/bin/ld: /tmp/ccUBpWp7.o: in function `do_blkdev':
/mnt/c/Users/LEENSKY/desktop/fmk/src/uncramfs/uncramfs.c:364: undefined reference to `minor'
/usr/bin/ld: /mnt/c/Users/LEENSKY/desktop/fmk/src/uncramfs/uncramfs.c:364: undefined reference to `major'
collect2: error: ld returned 1 exit status
make[1]: *** [<builtin>: uncramfs] Error 1
make: *** [Makefile:7: all] Error 2
Tools build failed! Check pre-requisites. Quitting...

**Comment by lassoan** [comment]
This repository belongs to 3D Slicer medical image visualization software (www.slicer.org). It does not have code or feature similar to what you mentioned.
