### ISSUE TITLE
Upgrade python syntax in dependent projects  to 3.6 and newer

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5626]
Suggested follow-up updates:
* [x] https://github.com/fedorov/MultiVolumeExplorer
* [x] https://github.com/fedorov/MultiVolumeImporter
* [x] https://github.com/Slicer/LandmarkRegistration
* [x] https://github.com/SimpleITK/SlicerSimpleFilters
* [x] https://github.com/pieper/CompareVolumes

_Originally posted by @jcfr in https://github.com/Slicer/Slicer/issues/5625#issuecomment-832234844_

**Comment by jcfr** [comment]
Thanks for working on this 🙏

**Comment by jcfr** [comment]
As a sanity check, I suggest to locally run the associated self tests

**Comment by jamesobutler** [comment]
Will run tests and then issue PR tomorrow.
