### ISSUE TITLE
Extensions install directory does NOT exist

### ISSUE THREAD

**Issue by isiloon** [Slicer/Slicer#5627]
I get this error when I open extension manager

Extensions can not be installed.
Extensions install directory does NOT exist: D:/Program Files/NA-MIC/Slicer 4.11.20210226/NA-MIC/Extensions-29738
Check that 3D Slicer is properly installed. Read more...

3dslicer is installed to this directory D:\Program Files\NA-MIC\Slicer 4.11.20210226, is it something about ASCII letters or what?

Regards

**Comment by jamesobutler** [comment]
See if this post on the forum matches what you are describing. https://discourse.slicer.org/t/unable-to-install-extensions-when-slicer-is-installed-in-system-location/16588

**Comment by isiloon** [comment]
great, running as admin solved the issue. Thank you James
