### ISSUE TITLE
Instantiating a slicer.qSlicerWebWidget() breaks extensions manager

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5632]
if I instantiate a webwidget before launching the extensions manager, I cannot install extensions anymore. Steps to reproduce.

Python console:
```python
slicer.qSlicerWebWidget()
```

Open the extension manager for the first time
The extensions buttons only show the Download option.

(reported on discourse.slicer.org: https://discourse.slicer.org/t/slicer-qslicerwebwidget-disable-extension-manager-install/17398)

This issue has been first reported in https://github.com/Slicer/Slicer/issues/4602. It was thought to be a side effect of the DataStore module initialization, but as it turns out, the problem is at lower level.

## Steps to reproduce

- Start Slicer
- instantiate a web widget by `slicer.qSlicerWebWidget()`
- open extensions manager => "Download" buttons are displayed instead of "Install"

![image](https://user-images.githubusercontent.com/307929/117460816-e8856980-af1a-11eb-9233-fbe1b6e38765.png)

## Environment
- Slicer version: Slicer-4.11.20210226
- Operating system: Windows

**Comment by pieper** [comment]
Hmm, might be some crosstalk with the [download handler](https://github.com/Slicer/Slicer/blob/0094e9a35bd266cc8b0e677858dabce797c9928f/Base/QTGUI/qSlicerWebWidget.cxx#L219-L240) we added to intercept download from the morphosource web site.

**Comment by fbordignon** [comment]
This issue persists on Slicer 4.13.0-2021-08-31 revision 30139

**Comment by pieper** [comment]
Looking a bit more at this, it seems that the `[window.extensions_manager_model](https://github.com/KitwareMedical/slicer-extensions-webapp/blob/ed938dacb21154b81ee17680dd464b41c199f097/src/lib/api/extension.service.ts#L66-L83)` is not working as expected if the web widget has already been initialized once.  Either it's not detected or it's throwing an uncaught error.

@jcfr do you know a good way to debug this?

**Comment by lassoan** [comment]
The logic around qSlicerWebWidgetPrivate::initializeWebChannel is quite complex and if it is messed up then it can break the web widgets the way they are broken now. So, it would be a good place to start digging.

**Comment by jcfr** [comment]
Thanks for the detailed report, i will have a look.
