### ISSUE TITLE
Improve "release process" progress tracking

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5641]
## Is your feature request related to a problem? Please describe.

When a release is being created, the checklist associated with the issue documenting progress is manually crafted. For example, see https://github.com/Slicer/Slicer/issues/5217 (`v4.11.20200930`), https://github.com/Slicer/Slicer/issues/5489 (`v4.11.20210226`) and https://github.com/Slicer/Slicer/issues/6337 (`v5.0`).

While the steps are already documented on the wiki (see [here](https://www.slicer.org/wiki/Documentation/Nightly/Developers/ReleaseProcess)), this still remains tedious and prone to error.

## Describe the solution you'd like

Similarly to existing template for issue and feature, I suggest we create a "Release" template.

See https://github.com/Slicer/Slicer/tree/master/.github/ISSUE_TEMPLATE

## Describe alternatives you've considered

* Create and update a discourse post
* Use a google document

## Additional context

NA

**Comment by sensaiankit** [comment]
I am willing to solve the issue, as i am a beginner would anyone like to guide me please
