### ISSUE TITLE
Include a "maintainer guide" in readthedocs

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5642]
## Is your feature request related to a problem? Please describe.

As information related to the release process are in the wiki, discussing or updating the information is often done when a release is being done.

This makes the release process tedious and make it difficult to involve others in the process.

## Describe the solution you'd like

Transition information from https://www.slicer.org/wiki/Documentation/Nightly/Developers/ReleaseProcess to a sub-section called "Maintainer guide / Release process" in readthedocs.

## Describe alternatives you've considered

* Keep updating the wiki

## Additional context

* See https://github.com/Slicer/Slicer/issues/5641

**Comment by lassoan** [comment]
Since the development process evolves independently from Slicer versions, it is probably more appropriate to store it in the Slicer/Slicer GitHub wiki (https://github.com/Slicer/Slicer/wiki). It also makes the developer guide more to the point (the release process only affects 1-2 developers in the world).

**Comment by jcfr** [comment]
Makes sense, for completeness, what do you think of adding the section "Maintainer guide" and referencing the wiki ?

**Comment by lassoan** [comment]
Yes, we should refer to the wiki from the reference guide (roadmap, development process, release process, etc). [vscode wiki](https://github.com/Microsoft/vscode/wiki) is a pretty good example (very clear and focused).

**Comment by jcfr** [comment]
Closing. The relevant pages have been added to the wiki. See https://github.com/Slicer/Slicer/wiki
