### ISSUE TITLE
Build error using smart pointer and vtkSetGet macros in debug mode

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#5649]
Build error due to ambiguous overload

## Steps to reproduce

Mac build in debug mode

## Expected behavior

Should build fine, but instead get build errors like this:

```
[ 18%] Building CXX object Libs/MRML/Core/CMakeFiles/MRMLCore.dir/vtkMRMLMeasurement.cxx.o
In file included from /Users/pieper/slicer/latest/Slicer/Libs/MRML/Core/vtkMRMLMeasurement.cxx:10:
/Users/pieper/slicer/latest/Slicer/Libs/MRML/Core/vtkMRMLMeasurement.h:158:3: error: use of overloaded operator '<<' is ambiguous (with operand types 'vtkOStreamWrapper'
      and 'vtkSmartPointer<vtkCodedEntry>')
  vtkGetObjectMacro(QuantityCode, vtkCodedEntry);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/s/VTK/Common/Core/vtkSetGet.h:238:54: note: expanded from macro 'vtkGetObjectMacro'
                << "): returning " #name " address " << this->name );   \
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/opt/s/VTK/Common/Core/vtkSetGet.h:467:33: note: expanded from macro 'vtkDebugMacro'
   vtkDebugWithObjectMacro(this,x)
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/opt/s/VTK/Common/Core/vtkSetGet.h:576:18: note: expanded from macro 'vtkDebugWithObjectMacro'
    vtkmsg << "" x << "\n\n";                                                    \
    ~~~~~~~~~~~~~^
/opt/s/VTK/Common/Core/vtkOStreamWrapper.h:71:22: note: candidate function
  vtkOStreamWrapper& operator << (const vtkSmartPointerBase&);
                     ^
/opt/s/VTK/Common/Core/vtkOStreamWrapper.h:74:22: note: candidate function
  vtkOStreamWrapper& operator << (void*);
                     ^
/opt/s/VTK/Common/Core/vtkOStreamWrapper.h:87:22: note: candidate function
  vtkOStreamWrapper& operator << (bool);
                     ^
/opt/s/VTK/Common/Core/vtkSmartPointer.h:248:17: note: candidate function [with T = vtkCodedEntry]
inline ostream& operator << (ostream& os, const vtkSmartPointer<T>& p)
                ^
/opt/s/VTK/Common/Core/vtkSmartPointerBase.h:130:31: note: candidate function
VTKCOMMONCORE_EXPORT ostream& operator << (ostream& os,
                              ^

```
Most likely introduced by this commit: https://github.com/Slicer/Slicer/commit/5d7453f0e51c916c4a59ff50d158b2f9fddaa1aa

Wouldn't happen in release builds since this is in a `vtkDebugMacro` inside the `vtkGetObjectMacro`.

I've never seen `vtkSmartPointer` mixed with `vtkGetObjectMacro` before so it's not clear how best to resolve this.

## Environment
- Slicer version: master branch dc47b7a2b6ea656bc4b02f04c17e6e5cb47013a0
- Operating system: Mac + 11.2.3, Xcode 12.5

**Comment by lassoan** [comment]
It works well on Windows and Linux and I think it also works on MacOS of you use with vtk9. It would take me a lot of time to reproduce a build environment where this fails so if you can reproduce it @pieper on your computer then it would be great if you could fix it. It should be some trivial casting or implicit conversion error.

**Comment by lassoan** [comment]
If you cannot make the get object macro work then implementing a trivial get function will work for sure.

**Comment by pieper** [comment]
No problem, I'll try with vtk9 debug build on mac.  I'm not sure how to cast it (would need to be inside the macro I think). Implementing trivial get/set methods would be easy enough, but it's kind of a shame to lose the debug functionality of the macro.

It's true it doesn't fail for me on my linux debug build with vtk9, so if that's also the case on mac then we can just ignore this since vtk8 is basically deprecated for us now.

**Comment by pieper** [comment]
Problem did not happen with a fresh vtk9 build (debug on macos).  If we're not supporting vtk8 any reason not to turn off the option entirely?

**Comment by lassoan** [comment]
Thanks for testing this. I would support of officially removing VTK8 support but my understanding is that @jcfr would like to create a new interim release that still supports VTK8 (so that we can have a release that is compatible with both VTK 8 and 9).

We can wait for @jcfr to chime in but maybe it is simpler to replace the Get macros with simple Get methods.

**Comment by jcfr** [comment]
> new interim release that still supports VTK8

Indeed, that would be 4.15

**Comment by jcfr** [comment]
> I 've never seen vtkSmartPointer mixed with vtkGetObjectMacro before so it's not clear how best to resolve this

I suspect partially backporting  kitware/VTK@560020133f5184b923e35c6527a2eacf9b6c69b4 (Add new setters for smart pointers) will likely address the issue.

This part in particular:

```diff
--- a/Common/Core/vtkSetGet.h
+++ b/Common/Core/vtkSetGet.h
 //
 // Get pointer to object wrapped in vtkNew.  Creates member Get"name"
 // (e.g., GetPoints()).  This macro should be used in the header file.
@@ -277,10 +318,18 @@ virtual type *Get##name ()                                              \
 virtual type *Get##name ()                                              \
 {                                                                       \
   vtkDebugMacro(<< this->GetClassName() << " (" << this                 \
-                << "): returning " #name " address " << this->name );   \
+                << "): returning " #name " address "                    \
+                << static_cast<type*>(this->name) );                    \
   return this->name;                                                    \
 }
```

**Comment by pieper** [comment]
I suspect yes, that patch would work.  If you want to merge it I could test a mac debug build.  We don't strictly-speaking need to be able to build a debug version of the release, but I think it's good form.

**Comment by pieper** [comment]
Or the custom Get/Set methods are also fine if that's less trouble.
