### ISSUE TITLE
qMRMLWindowLevelWidget set manual min/max not working.

### ISSUE THREAD

**Issue by fbordignon** [Slicer/Slicer#5651]
`setAutoWindowLevel(qMRMLWindowLevelWidget::ManualMinMax)`

If in auto mode, changes to Manual W/L instead of manual min max

## Steps to reproduce
Python console:
```
a = slicer.qMRMLWindowLevelWidget()
b = getNode("MyNode")
a.setMRMLVolumeNode(b)
a.show()
a.setAutoWindowLevel(slicer.qMRMLWindowLevelWidget.ManualMinMax)
```

## Expected behavior

Should change to manual min/max?

## Environment
- Slicer version: Slicer-4.11
- Operating system: Windows 10

**Comment by lassoan** [comment]
Good catch. The editing mode changes correctly to ManualMinMax (label are set to Min/Max and moving the end of a slider changes the minimum value not the window), but the AutoManualComboBox selection is not updated. It would be great if you could fix this.

![image](https://user-images.githubusercontent.com/307929/119001054-a536ec00-b959-11eb-8f5b-d2bcb3408f11.png)

**Comment by fbordignon** [comment]
I will try to contribute on this, maybe just update the combobox.
