### ISSUE TITLE
Eliminate failed print from batch lot on prusa slicer

### ISSUE THREAD

**Issue by samadia** [Slicer/Slicer#5653]
Consider this...when we want 10 parts to be print together, the system creates a single g-code file. But let the system see it as sub-10 g-codes and when the main file is selected all are printed together but in case of failure if we want to stop and resume we need to have some option to still print 10 parts or not or we can eliminate failed print and continue with rest.
#prusaslicer

**Comment by jamesobutler** [comment]
Hi @samadia unfortunately you have posted to the wrong repository. You are looking for https://github.com/prusa3d/PrusaSlicer. This is a repo for https://www.slicer.org/.
