### ISSUE TITLE
PrusaSlicer hangs on opening

### ISSUE THREAD

**Issue by rushputin** [Slicer/Slicer#5655]
In setting up a new PC, I installed PrusaSlicer, and it worked fine.  I then uninstalled it and reinstalled it to a folder under the D: drive.

Now, when I run it, it just hangs.  It gets past the modal, and just sit there until I manually kill the process.

I've tried 
- Reinstalling it via the standalone installer 
- Reinstalling it via the full package installer
- Reinstalling it in C:
- Simply running the rc from github.
- Reinstalling it as an admin

with no success.

## Steps to reproduce

- Open PrusaSlicer
- Application hangs

![2021-05-26](https://user-images.githubusercontent.com/5021770/119663545-6fce4a80-be00-11eb-885b-06a3b0ab19b6.png)

## Expected behavior

- Normal utilization of application

## Environment
- Slicer version: PrusaSlicer-2.3.1+win64-202104161404
- Operating system: Windows 10 Home 20H2 
- CPU Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz   2.90 GHz
- Graphics card: NVIDIA GeForce GTX 1660 Ti

**Comment by jamesobutler** [comment]
Hi @rushputin unfortunately you have posted to the wrong repository. You are looking for https://github.com/prusa3d/PrusaSlicer. This is a repo for https://www.slicer.org/.

**Comment by rushputin** [comment]
> Hi @rushputin unfortunately you have posted to the wrong repository. You are looking for https://github.com/prusa3d/PrusaSlicer. This is a repo for https://www.slicer.org/.

How embarassing!  I'll move it to the proper repo.  Thanks!
