### ISSUE TITLE
Document all Slicer core modules on readthedocs

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5664]
Documentation of some Slicer core modules are almost all on readthedocs (see https://github.com/Slicer/Slicer/pull/5662). These are the only remaining ones that need to be ported from the Slicer wiki/reviewed/rewritten:

@lassoan:
- [x] user_guide/modules/sequences
- [x] user_guide/modules/cropvolumesequences (added through https://github.com/Slicer/Slicer/pull/6656)
- [x] user_guide/modules/screencapture
- [x] user_guide/modules/welcome
- [x] user_guide/modules/sampledata
- [x] user_guide/modules/dataprobe
- [x] user_guide/modules/simplefilters (added through https://github.com/Slicer/Slicer/pull/6656)
- [x] user_guide/modules/multivolumeimporter (added through https://github.com/Slicer/Slicer/pull/6658)
- [x] user_guide/modules/multivolumeexplorer (added through https://github.com/Slicer/Slicer/pull/6658)
- [x] user_guide/modules/editor
- [x] user_guide/modules/datastore

@pieper:
- [x] user_guide/modules/landmarkregistration
- [x] user_guide/modules/dmriinstall
- [x] user_guide/modules/endoscopy
- [x] user_guide/modules/labelstatistics

@cpinter:
- [x] #6019

@Sunderlandkyl:
- [x] user_guide/modules/dynamicmodeler (added through https://github.com/Slicer/Slicer/pull/6640)
- [x] user_guide/modules/colors
- [x] user_guide/modules/markups (update) (added through https://github.com/Slicer/Slicer/pull/6643)

@jcfr or @sjh26:
- [x] user_guide/modules/eventbroker (added through ae2e56b493138eaa9d9082951f49bb3d693a2a9d)
- [x] user_guide/modules/extensionwizard (added through https://github.com/Slicer/Slicer/pull/6634)
- [x] user_guide/modules/vectortoscalarvolume (added through https://github.com/Slicer/Slicer/pull/6635)
- [x] user_guide/modules/performancetests (added through https://github.com/Slicer/Slicer/pull/6668)
- [x] user_guide/modules/selftests (added through https://github.com/Slicer/Slicer/pull/6669)

@RafaelPalomar:
- [x] user_guide/modules/cropvolume (added through https://github.com/Slicer/Slicer/pull/6663)
- [x] user_guide/modules/surfacetoolbox (added through https://github.com/Slicer/Slicer/pull/6666)

**Comment by cpinter** [comment]
Related PR awaiting review: https://github.com/Slicer/Slicer/pull/5683

**Comment by RafaelPalomar** [comment]
Hello, I take on the following modules, if you want to release some pressure:

 user_guide/modules/cropvolume
 user_guide/modules/surfacetoolbox

**Comment by lassoan** [comment]
@RafaelPalomar You wrote above you would take a stab on documenting cropvolume and surfacetoolbox. It would be great if you could do it Monday morning so that we have complete documentation of all Slicer core modules for the new release. Thank you!

**Comment by lassoan** [comment]
Thanks a lot @RafaelPalomar for the two module documentations!

**Comment by jcfr** [comment]
Closing. All module documentation pages have been added (or in the process of being integrated with pull requests)
