### ISSUE TITLE
Support for documenting all extensions in slicer documentation

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5669]
We should have a solution that scales well for documenting all the extensions, not just those that are bundled with Slicer and that works for all module types, not just CLI. 

This would allow us to include documentation of _all_ extensions in the Slicer documentation, the same way as for bundled extensions. 

This would result in a documentation that is similar to the old wiki, where all the extensions are documented, not only Slicer core modules. Building the documentation should be a lightweight process and so it should not include installing or building Slicer - so that it can be easily handled by readthedocs.

This could be achieved for example by having all necessary information in the extension description files (in json). There could be a link to a markdown file for the extension and a markdown file for each module (or the markdown file content could be embedded in the json file) and for CLI modules there could be a link to an additional XML file.

_Originally posted by @lassoan in https://github.com/Slicer/Slicer/pull/5662#discussion_r643513070_

**Comment by lassoan** [comment]
This has been implemented and remaining tasks are tracked in https://github.com/Slicer/Slicer/issues/5664.
