### ISSUE TITLE
Slicer 3D could not startup in windows10

### ISSUE THREAD

**Issue by yllgl** [Slicer/Slicer#5690]
## Steps to reproduce

I could not startup slicer 3D on my computer. I get the following message using eventvwr.exe.
```
Faulting application name: SlicerApp-real.exe，version: 0.0.0.0, time stamp: 0x60c2ef90
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process ID: 0x3530
Faulting application start time:  0x01d76020440f9dd4
Faulting application path: D:\Slicer 4.13.0-2021-06-10\bin\SlicerApp-real.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 7eff8d05-0eb7-48d8-964a-20d50a07728e
Faulting package full name: 
Faulting package-relative application ID:
```

## Environment
- Slicer version: Slicer 4.13.0-2021-06-10
- Operating system: Windows 10 20H2 19042.1052
- Hardware:
CPU	Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz   2.30 GHz
RAM 12.0 GB
Intel(R) HD Graphics 530
NVIDIA GeForce GTX 950M

I get DLL dependency information using Dependency Walker tool and get the following file, which I change the suffix .csv to .txt in order to upload it.
[SlicerApp-real.txt](https://github.com/Slicer/Slicer/files/6643498/SlicerApp-real.txt)

I have followed the [get_help_doc](https://slicer.readthedocs.io/en/latest/user_guide/get_help.html#slicer-application-does-not-start) instructions and it's useless.

**Comment by lassoan** [comment]
Laptops with dynamically switched Intel+NVidia graphics are often have driver issues. Have you installed latest drivers? 

Have you used Slicer on this computer successfully before? Have you tried deleting Slicer.ini?

Do you use the Intel or the NVidia GPU for Slicer? You can try to temporarily change your systen settings to use NVidia for all applications and see if it fixes the problem (or in NVidia settings, choose to use NVidia GPU for SlicerApp-real.exe).

**Comment by lassoan** [comment]
Also try to install [Microsoft Visual C++ Redistributable for Visual Studio 2019](https://visualstudio.microsoft.com/downloads/#microsoft-visual-c-redistributable-for-visual-studio-2019). We had one case in the past when on a Chinese Windows version some of the required MSVCRT files were missing.

**Comment by yllgl** [comment]
Where is Slicer.ini? I have never used Slicer on this computer successfully before. I have tried to install  Microsoft Visual C++ Redistributable for Visual Studio 2019 but it's helpless. I have updated drivers. I'm not sure if it use NVidia to run applications, although I made the settings.
![image](https://user-images.githubusercontent.com/23625282/121844770-0b275100-cd17-11eb-8ff3-943e60fe11f8.png)

**Comment by lassoan** [comment]
As I wrote above, change GPU settings for `SlicerApp-real.exe` (not for `Slicer.exe`).

See settings file location at: https://slicer.readthedocs.io/en/latest/user_guide/get_help.html#slicer-application-does-not-start

**Comment by yllgl** [comment]
@lassoan 
>change GPU settings for SlicerApp-real.exe
I have changed GPU settings for SlicerApp-real.exe but it remains the same problem.

There is no NA-MIC directory in `c:\Users\<yourusername>\AppData\Roaming`. And I have tried `Slicer.exe --disable-settings` and no help. I also tried `set path=` and then Enter Slicer.exe to start Slicer. But useless.

**Comment by lassoan** [comment]
You can write me a an email (lasso at queensu.ca) to set up a teams/skype/hangout meeting with screen sharing to debug this.

**Comment by lassoan** [comment]
We had a call and could not find a way to make Slicer work on this computer. PythonSlicer interpreter could be started but Qt designer failed with the same way as Slicer. So, most likely the graphics chipset/drivers of the computer is incompatible with Slicer. The only solution I could suggest is to use a more recent computer (preferably at least 8th generation Intel chipset).
