### ISSUE TITLE
Extensions are missing for latest Slicer Preview Release for about half a day

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5699]
Extensions for Slicer Preview Releases usually appear around 2am and extensions are continuously added to it until about 11am. So, there is about a 9 hour gap between 2am-11am EST when the latest Slicer Preview Release does not have all the extensions yet.

In the East Coast this means that those people who download Slicer in the morning will not see extensions for a few hours. It should be mostly tolerable.

However, for Europe, 2am-11am EST is at 8am-5pm. This means that pretty much during the entire day, newly downloaded Slicer Preview Releases miss many extensions.

A simple solution would be to prevent download.slicer.org page from updating between 12am to 11am EST (keep showing the previous Slicer Preview Release until extensions are available for the new release).

**Comment by jamesobutler** [comment]
See your git issue #4976 from almost exactly a year ago. Must be that time 😄

**Comment by lassoan** [comment]
I searched for issues but somehow I did not find this. Thank you. I'm closing this then.
