### ISSUE TITLE
Can't open segmentations

### ISSUE THREAD

**Issue by IliasPa** [Slicer/Slicer#5706]
[Give a short summary of what the problem is]
I work with brain segmentations. Two months ago I could edit them. Now, when I import my segmentations, there is nothing in Segment Editor.
## Steps to reproduce
[describe what you did and what happened - attach screenshots if possible]
I put the .nii & .mrml file into the software (as Volume & MRML Scene, respectively) and then in the Segment Editor.
There aren't my segmentations there.

![image](https://user-images.githubusercontent.com/86381965/123166993-ac807680-d47e-11eb-8d1e-f6ec07e1c4fe.png)

## Expected behavior
[describe what you expected to happen]
I expected to find my segmentations.

## Environment
- Slicer version: Slicer-4.11.20200930-2021-06-24
- Operating system: Windows 10

**Comment by lassoan** [comment]
How did you save your segmentation? Segmentation is normally stored in a seg.nrrd file. Do you have such file?

The mrml file is just an index of which files should be loaded and what display settings - it does not store the actual image or segmentation data.

**Comment by IliasPa** [comment]
You are right. Thank you! The software is very good, but I do not have a lot of hours in it. Thank you, it worked. I just opend the .nrrd file as segmentation.

I'm also having a .vp & a .acsv file, I have no idea what they are. But my problem is solved.

I'm sorry about my english. It is not my language.
