### ISSUE TITLE
3D Slicer fails to open on MobaXterm

### ISSUE THREAD

**Issue by fabiogeraci** [Slicer/Slicer#5707]
Good Morning,

My setup: Windows 10 - Ubuntu WSL1 (Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 4.4.0-19041-Microsoft x86_64)) - MobaXterm

In bashrc I have the following lines:
```
#
export SITK_SHOW_COMMAND=${HOME}/Slicer-4.11.20210226-linux-amd64/Slicer
export PATH="$PATH:${HOME}/Slicer-4.11.20200930-linux-amd64"
#
```
Issue: I am trying to launch 3D Slicer from MobaXterm, using:
`~/Slicer-4.11.20210226-linux-amd64/Slicer`
It seems to be working but then I get the following error:
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-username'
Switch to module:  "Welcome"
Slicer: Fatal IO error: client killed
The X11 connection broke: I/O error (code 1)
XIO:  fatal IO error 0 (Success) on X server "localhost:10.0"
      after 1362 requests (1362 known processed) with 0 events remaining.
free(): invalid size
```

**Comment by pieper** [comment]
I've never used MobaXterm but based on their web site they claim to support X11 applications with OpenGL like Slicer.  If you buy their license you might be able to get support from them, otherwise I'm not sure there's much you can do.

**Comment by lassoan** [comment]
Do you mean that Slicer works well for a while via MobaXterm and then it crashes? Do you do anything specific in Slicer when MobaXterm crashes or it happens randomly?

Anyway, no matter what an application does, it should not be able to crash the terminal client. If MobaXterm is not robust enough then you can try xrdp or vnc. You can also try the latest Slicer Stable Release or latest Slicer Preview Release.

**Comment by lassoan** [comment]
For me, WSL2 and xrdp worked perfectly. RDP is also nicer because Windows has a built-in RDP client (mstsc.exe), so you don't need to install anything to connect to Slicer. See more details here: https://discourse.slicer.org/t/slicer-can-be-built-and-runs-well-on-windows-subsystem-for-linux-wsl2/16022

Latest WSL2 makes running GUI applications even simpler (you don't need to set up the xrdp server manually, etc.).

**Comment by fabiogeraci** [comment]
Hello as it turned out my wsl was a bit compromised, so i resetted and started fresh. Also after setting user and password at launch on wsl i swithed to MobaXterm. then I installed all the following packages

```
sudo apt install mesa-utils libxss1 libegl1-mesa libgl1-mesa-glx libxcomposite1 libxcursor1 libxi6 libxtst6 libxrandr2 libasound2 xauth
sudo apt-get install libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0 libxcb-render-util0 libxcb-xkb-dev libxkbcommon-x11-dev libpulse-dev libnss3 libglu1-mesa libxcb-xinerama0 libxcb-shape0
```

```
sudo cp /mnt/c/Users/$USER/Downloads/Slicer-4.11.20210226-linux-amd64.tar.gz ${HOME}
tar -zxvf Slicer-4.11.20210226-linux-amd64.tar.gz
rm Slicer-4.11.20210226-linux-amd64.tar.gz

mkdir ~/bin
ln -s ~/Slicer-4.11.20210226-linux-amd64/Slicer ~/bin/ImageJ
```

and added the following to bashrc
```
export SITK_SHOW_COMMAND="${HOME}/Slicer-4.11.20210226-linux-amd64/Slicer"
export PATH="$PATH:${HOME}/Slicer-4.11.20210226-linux-amd64"
```
end finally I got it to work on moba, I also noticed that moba run method needs to be set on auto

I hope this will help somebody else
