### ISSUE TITLE
Please implement the functionality to block the rotation of individual axes in 3D view

### ISSUE THREAD

**Issue by rbumm** [Slicer/Slicer#5712]
## Is your feature request related to a problem? Please describe.

The 3D View tends to tumble when you rotate it with the mouse.

## Describe the solution you'd like

It would be great if we could block the rotation of the frontal vertical axis, the sagittal horizontal axis, and the axial axis on demand. I suggest defining certain hotkeys ("a","s","d"), which would block the rotation in each of the axes if pressed. 

## Describe alternatives you've considered

no alternatives I could think of

## Additional context

none

**Comment by jamesobutler** [comment]
This issue can be closed because https://github.com/Slicer/Slicer/commit/dd407fb22cb2c50527a59161ba6e0125e4e14bc6 was integrated?

**Comment by rbumm** [comment]
Yes, sure.

**Comment by rbumm** [comment]
Was implemented,
