### ISSUE TITLE
Unable to place markups points while moving mouse

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#5713]
I've determined that as of https://github.com/Slicer/Slicer/commit/6b8566e6384b34d86c353a3a2cd93c873673018a, I'm unable to place markups points while moving the mouse which is when I'm placing points quickly. I first observed this when using the Surface Cut segment editor effect.

cc: @lassoan 

## Steps to reproduce
1. Open Slicer
2. Set placement mode to persistent
3. Move your mouse while trying to click to place points. You will observe that the points don't get placed.
4. Stop moving your mouse then click to place a point. The point will be placed.

https://user-images.githubusercontent.com/15837524/123838262-cfc18080-d8d9-11eb-998b-45273e885faa.mp4

## Expected behavior

Points should be placed even when moving the mouse quickly and clicking.

## Environment
- Slicer version: 3D Slicer 4.13.0-2021-06-25 (http://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&name=Slicer-4.13.0-2021-06-25-win-amd64.exe&checksum=461ec99a00bdc963b62e636efdfba3ed)
- Operating system: Windows

**Comment by lassoan** [comment]
Thanks for the feedback. The change in behavior was introduced to remove the clash of right-click to finish placement / right-button-down to show context menu; and clash of left-click to jump to selected fiducial and left-button-down to place a fiducial. As a side effect, it also enables zooming and rotating view, etc. without exiting markups placement mode, and frees up the left-click-and-drag during placement in slice views.

So the current implementation has several important advantages. It indeed means that you need to stop to place a point. Right now I feel that the advantages outweigh the single disadvantage, but it would be good to hear from others as well.

@jamesobutler would you mind posting on discourse to ask users to try the new behavior and give feedback on the usefulness of being able to rotating/zoom view during placement vs. dropping points without stopping?

**Comment by jamesobutler** [comment]
Sure I can start a discourse post. Unfortunately I can already assume from our users using Surface Cut and DrawTube segment effects, or even quickly placing a ruler using the vtkMRMLMarkupsLineNode that this is going to slow down the workflow and will be annoying.

**Comment by lassoan** [comment]
I can see that the advantages are not obvious in slice views because currently click-and-drag is not used in slice views. Just try it in a 3D view!

**Comment by jamesobutler** [comment]
Discourse forum post: https://discourse.slicer.org/t/feedback-requested-requirements-to-place-a-fiducial/18407

Placing fiducials in the 3D view in our 3D ultrasound workflow is not really of interest to us. We use the 3D view for visualization purposes only. I can ask some of the other users in my group about the usage in the 3D view, but I would assume they have similar opinions.

We also do some custom fiducial placement of M-Mode using DrawTube and this M-Mode volume doesn't even need a 3D view being a 2D/2Dt volume. We detect this when we load and show volumes and set it to Red-slice only. These draw tube points are placed pretty quickly and having to stop to click is painful for the workflow.
![image](https://user-images.githubusercontent.com/15837524/123866864-9b5ebc00-d8fb-11eb-93c2-d38b692eecb6.png)

**Comment by lassoan** [comment]
Thanks for all the additional information. To avoid having parallel threads, let's discuss in the forum topic and we can summarize the conclusion here in the end.
