### ISSUE TITLE
ConvertToGridTransform returns vtkMRMLTransformNode instead of vtkMRMLGridTransformNode

### ISSUE THREAD

**Issue by simonoxen** [Slicer/Slicer#5717]
Is there a reason why the ConvertToGridTransform method outputs a vtkMRMLTransformNode instead of a vtkMRMLGridTransformNode? 

https://github.com/Slicer/Slicer/blob/aaa9f918a4ee4f35bf09e05c5d7e53d083b2e4e3/Modules/Loadable/Transforms/Logic/vtkSlicerTransformLogic.h#L112

I'm developing a [module](https://github.com/netstim/SlicerNetstim/tree/master/WarpDrive) that takes grid transforms as input. When implementing I tried to strictly take vtkMRMLGridTransformNode as input and this way might be more straightforward for the user.

I usually load non linear transforms that are loaded as grid transforms so there's no problem. But I realised that if I wanted to this from within Slicer, vtkMRMLTransformNode are generated (and therefore not recognised as possible input).

Of course, this is easy to change on my side, but I wonder if there's a reason for this. If not, I can also try to contribute a change.

Thanks

**Comment by lassoan** [comment]
Could you post this question on the Slicer forum (https://discourse.slicer.org)? The behavior is intentional and others may be interested to learn about this, too.
