### ISSUE TITLE
Pantalla Negra al iniciar Slicer3D

### ISSUE THREAD

**Issue by Panizo1979** [Slicer/Slicer#5729]
[Give a short summary of what the problem is]
Al finalizar  la instalación de la versión 11 de Slicer y ejecutarlo me aparece una pantalla negra y no termina de verse completamente la aplicación.

## Steps to reproduce
![image](https://user-images.githubusercontent.com/72659449/124815140-88b43a80-df2c-11eb-981b-5233bfe96e72.png)

[describe what you did and what happened - attach screenshots if possible]

## Expected behavior

Espero que se ejecute correctamente
[describe what you expected to happen]

## Environment
- Slicer version: Slicer-4.11.2021?-2021-07-07
- Operating system: Windows / Linux / Mac + which version
Windows 7 Profesional  64 Bits
![Error 3D Slicer](https://user-images.githubusercontent.com/72659449/124816018-a03ff300-df2d-11eb-888c-38d045818924.png)

Procesador 3.40 GHz
Memoria RAM : 8 GB

**Comment by jamesobutler** [comment]
Windows 7 is currently not a supported platform with the latest Slicer preview (see [here](https://slicer.readthedocs.io/en/latest/user_guide/getting_started.html?highlight=Windows%2010#operating-system-versions).  You can try downloading Slicer 4.11.20210226 (still has the possibility of not working) at https://download.slicer.org/ or an older release at https://slicer.kitware.com/midas3/folder/274.

**Comment by lassoan** [comment]
Most likely the issue is that you have a very old chipset (a computer more than 5 years old).
