### ISSUE TITLE
Improve markups rendering performance

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5752]
To ensure that rendering of markups for reasonable-sized scenes (something like 500 markups) is fluid to render even with interaction and label display enabled:

`vtkSlicerMarkupsWidgetRepresentation3D::GetViewScaleFactorAtPosition`
When I attach VerySleepy to a release-mode version (which is not totally reliable) then I keep seeing `vtkSlicerMarkupsWidgetRepresentation3D::GetViewScaleFactorAtPosition` as a performance bottleneck. Computing the scale factor should be a very inexpensive operation (essentially multiplication with a 4x4 matrix). However, how we compute the scale now (using `Renderer->WorldToDisplay`) is very costly.

Making `vtkSlicerMarkupsWidgetRepresentation3D::GetViewScaleFactorAtPosition` return a fixed value (instead of actually computing the scale) seem to make a significant difference. Could you verify this and if you confirm that this has significant impact, could you think about a solution? Either fixing inefficiency of `WorldToDisplay` or by implementing a fast/batch version of it.

Reduce the number of actors
We added a separate actor for displaying almost identical things, just with different colors. We could modulate the color (and even the markup type) using a point data array.

Could you try to merge the Unselected+Selected+Active pipeline and the Project+ProjectBack pipeline? That would allow us to go from 5 actors to 2 actors per control point, which could be a significant improvement.

Check if profiling `RelWithDebInfo` brings up anything else
For example, would disabling `vtkDebugLeaks` make a difference? It is quite expensive now (collects call stack, etc.) and I think it is enabled for release-mode builds on the factory.

**Comment by Connor-Bowley** [comment]
@lassoan  I can confirm that on Linux (Ubuntu 20.04) that having `vtkSlicerMarkupsWidgetRepresentation3D::GetViewScaleFactorAtPosition` return a fixed value has significant impact (using perf and time for rough comparisons). 

Can you provide more information on how you would recommend computing the scale factor without use of WorldToDisplay?

**Comment by Connor-Bowley** [comment]
Also, were you creating 1 markup node with many markups, or did you have many markup nodes with only 1 markup per node?

**Comment by Connor-Bowley** [comment]
https://github.com/Connor-Bowley/Slicer/commit/5b966f55238c39410735ecc073c52d7f2310d9f1

Added a caching mechanism for only computing the transformation matrix to go from world to view coordinates once per call to `vtkSlicerMarkupsWidgetRepresentation3D::canInteract`. This reduced the average call time of `vtkSlicerMarkupsWidgetRepresentation3D::GetViewScaleFactorAtPosition` by ~95% (2253.94 ns to 95.973 ns on a `RelWithDebInfo` build, by inserting some `std::chrono::system_clock::now()` calls in the code) on a scene with 1000 Fiducial points on a single Fiducial Node.

I am unsure as to the minimum criteria for resetting the cache of the transformation matrix (changing screen size, moving camera, etc) and exactly how to reset on those events, so currently it will reset the cache during each call to `vtkSlicerMarkupsWidgetRepresentation3D::canInteract`. 

@lassoan if you get a chance, please try out the changes I made and see if they cause an improvement for your scenario.

I will investigate if these changes will make any difference on a scene that has many Fiducial Nodes that each only have 1 Fiducial point (I suspect these changes will not affect that scenario). I will then look into what optimizations could be made for that scenario.

**Comment by lassoan** [comment]
Thanks a lot for working on this, I'll have a quick look and we can talk about it during the developer meeting that'll start soon.

**Comment by Connor-Bowley** [comment]
Turning off vtkDebugLeaks did not make much of a difference on Linux.

**Comment by Connor-Bowley** [comment]
From what I am seeing, it looks like the interactive handles are a larger performance hit than the label.

**Comment by Connor-Bowley** [comment]
I have a PR out to fix this in both Slicer/VTK and VTK/VTK.
https://github.com/Slicer/VTK/pull/40
https://gitlab.kitware.com/vtk/vtk/-/merge_requests/8548

**Comment by lassoan** [comment]
Some improvement ideas has been merged (determining scale factor), others have proven not to make a big difference (debug leaks), and the remaining idea of merging actors is now tracked in #5398, therefore closing this issue now.
