### ISSUE TITLE
Plot name cannot be modified

### ISSUE THREAD

**Issue by riep** [Slicer/Slicer#5770]
The plot view name cannot be modified. Also, please note that a warning pops up when switching to a view with a plot 

## Steps to reproduce
Add a plot view in slicer and run the following command

```python
plotNode = slicer.app.layoutManager().plotWidget(0).mrmlPlotViewNode()
plotNode.SetLayoutLabel("myplot")
```

## Expected behavior
Plot view label should be changed to myplot

## Environment
- Slicer master
- Operating system: Linux 20.04

**Comment by jcfr** [comment]
> Add a plot view in slicer

Since there are two type of plots (Interactive vs Standard), could you provide a set of steps including the creation of the nodes and their addition to the scene ?

**Comment by lassoan** [comment]
I was able to reproduce and fix the issue and will push a fix after some more testing.
