### ISSUE TITLE
Selected view turns magenta

### ISSUE THREAD

**Issue by riep** [Slicer/Slicer#5772]
The selected view is turned magenta after pressing key "3"

## Steps to reproduce

Load a volume
Click in a slice view
Press key "3"

The selected view turns magenta

## Expected behavior

Nothing happens as it is not a referenced shortcut.

## Environment
- Slicer version: Slicer master
- Operating system: Linux 20.04

**Comment by pieper** [comment]
I believe that's some built-in VTK behavior to enable a stereo rendering mode.

**Comment by riep** [comment]
good catch https://vtk.org/doc/release/5.0/html/a01650.html
Keypress 3: toggle the render window into and out of stereo mode. By default, red-blue stereo pairs are created. Some systems support Crystal Eyes LCD stereo glasses; you have to invoke SetStereoTypeToCrystalEyes() on the rendering window.

**Comment by pieper** [comment]
+1 for disabling them and exposing the 'r' functionality.

**Comment by riep** [comment]
I tested all and only 3 was working slicer probably overwrite the others

**Comment by riep** [comment]
r is documented in slice but do not know if slicer overwrite it. It does a volume centering so ...

**Comment by lassoan** [comment]
The effect of shortcuts are not always visible. For example, `w` and `s` only affects certain actors, such as slice views shown in the 3D view or the orientation labels, `p` works if you are over a polygonal actor, ... We'll disable them.
