### ISSUE TITLE
Incoming folder in DICOM database folder not emptied after ctk.ctkDICOMRetrieve()

### ISSUE THREAD

**Issue by rbumm** [Slicer/Slicer#5773]
[Give a short summary of what the problem is]

After DICOM networking retrieval with ctk.ctkDICOMRetrieve() (reading from local or remote PACS)  the DICOM database folder contains two folders: 
"dicom"
"incoming"

Directly after reading (and hours later) the size of "incoming" is about the same as "dicom", several GB depending on the data requested.   

## Expected behavior

"dicom" should contain the data, "incoming" should be empty after retrieval. 

## Possible cause

"incoming" seems not to be routinely emptied after each successful retrieval. 

## What I tried

Deleted all files in "incoming" which did not have a negative effect when I reopened Slicer with the same database.  

## Environment
- Slicer version: Slicer-4.13.0-2021-07-29
- Operating system: Windows

**Comment by pieper** [comment]
It should be enough to add `os.remove(dicomFilePath)` between the two lines below.  The incoming folder would then be emptied as the files are added to the database.

https://github.com/Slicer/Slicer/blob/21f8ba46beb67ae169387dd94237b0d7f8087302/Modules/Scripted/DICOMLib/DICOMProcesses.py#L341-L342
