### ISSUE TITLE
Segment Editor "Smoothing" operation slow in 4.13

### ISSUE THREAD

**Issue by rbumm** [Slicer/Slicer#5774]
## Unexpected behavior

During tests of the LungCTSegmenter extension using the Slicer version mentioned below, the finalization of the lung masks, which involves the Segment Editor´s "Smoothing" method, took longer than expected.   
Method: "Gaussian", kernelsize "2 mm"

Version 4.13: 
Production of:
"right", "left" and "other" masks: 129 s 

## Expected behavior

Version 4.11: 
Production of
"right", "left" and "other" masks: 56 s 

## Environment
- Slicer version: Slicer 4.13.0-2021-08-05
- Operating system: Windows

**Comment by jamesobutler** [comment]
How old is this Version 4.11 that is being referenced?

This seems like it would be because of https://discourse.slicer.org/t/smoothing-with-gaussian-standard-deviation-changed-at-some-point/18431. Where previously the Gaussian Standard Deviation "2 mm" was actually being used as "2 pixels", but then that was fixed.  The observed result was that in the post-fix version, smoothing was much more aggressive and therefore would take longer than a value previously used.

**Comment by rbumm** [comment]
Thank you. That 4.11  is quite old: Slicer 4.11.20200930

In fact, the smoothing result looks as if it was a bit more aggressive (but usable)  when the LungCTSegmenter was run in 4.13. Will there be any changes in smoothing aggressiveness in final 4.13 or should I deal with the problem on the extension side?

**Comment by jamesobutler** [comment]
The thing that triggered the change was now Standard deviation smoothing is actually sending the correct values. So yes, if you want to tune your smoothing value you can go ahead and do that.

It's something encouraged in the migration guide
https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide/Slicer#Smoothing_effect

I made that discourse post when I was determining why I needed to change my default smoothing value to get the same results as before.

**Comment by rbumm** [comment]
Ok, I will probably version check Slicer and use a different parameter in 4.13. Have a pleasant weekend.

**Comment by rbumm** [comment]
Sry, this does not work ... 
I tested with different KerneSizeMm parameters (0.5,1,2,3) but the result stays the same, overdone, and the operation lasts 128 s 
This is how I call the effect

`                
self.segmentEditorNode.SetSelectedSegmentID(segmentId)
self.segmentEditorWidget.setActiveEffectByName("Smoothing")
effect = self.segmentEditorWidget.activeEffect()
effect.setParameter("SmoothingMethod","GAUSSIAN")
effect.setParameter("KernelSizeMm","2")
effect.self().onApply()
`

**Comment by lassoan** [comment]
For Gaussian smoothing, the kernel size is computed automatically, you just specify the standard deviation see here: https://slicer.readthedocs.io/en/latest/developer_guide/modules/segmenteditor.html#smoothing

**Comment by rbumm** [comment]
Great, 
```
effect.setParameter("GaussianStandardDeviationMm","2")
```
takes about 80 s and gives a good result in 4.13

**Comment by lassoan** [comment]
Thanks for the update, the problem is settled then.

@jamesobutler it is great that you remembered this!

**Comment by jamesobutler** [comment]
> For Gaussian smoothing, the kernel size is computed automatically, you just specify the standard deviation see here: https://slicer.readthedocs.io/en/latest/developer_guide/modules/segmenteditor.html#smoothing

@lassoan Good catch about the clarification of KernelSizeMM different than GaussianStandardDeviationMM. Yes even without specifying a different default for Gaussian MM, the smoothing results would’ve changed after your bug fix.
