### ISSUE TITLE
Can not start Slicer and Event Viewer recorded a DLL loading problem

### ISSUE THREAD

**Issue by XiDeng** [Slicer/Slicer#5777]
[Give a short summary of what the problem is]

Can not start Slicer

[describe what you did and what happened - attach screenshots if possible]

I opened Slicer via shortcut of it, and the loading window showed and the program was loading modules. A few seconds later, the window disappered, and then there was no any new window appearing.
![无标题](https://user-images.githubusercontent.com/32667583/128640094-38b3d519-9353-44ab-a3f2-c0699794032a.png)

I got an Application Error from Event Viewer. The information shows that the Faulting module path is Qt5Core.dll. I tried to set path in command windows and start Slicer.exe again, but it didn't work also.

I used to install 4.10.2, but the problem is still.
## Expected behavior

[describe what you expected to happen]

Know how to start Slicer on my computer.

## Environment
- Slicer version: Slicer 4.13.0-2021-08-07
- Operating system: Windows Professional 20H2 19042.1110

Thanks!

**Comment by XiDeng** [comment]
Regular information in Event Viewer:
错误应用程序名称: SlicerApp-real.exe，版本: 0.0.0.0，时间戳: 0x610f67ab
错误模块名称: Qt5Core.dll，版本: 5.15.1.0，时间戳: 0x5f506b86
异常代码: 0xc0000409
错误偏移量: 0x0000000000021498
错误进程 ID: 0xf94
错误应用程序启动时间: 0x01d78c7821e42cf2
错误应用程序路径: C:\Users\oeel\AppData\Local\NA-MIC\Slicer 4.13.0-2021-08-07\bin\SlicerApp-real.exe
错误模块路径: C:\Users\oeel\AppData\Local\NA-MIC\Slicer 4.13.0-2021-08-07\bin\Qt5Core.dll
报告 ID: 1bbf6978-b5bb-40ba-ae7d-bf1746352382
错误程序包全名: 
错误程序包相对应用程序 ID: 

Detail in Event Viewer:
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-08-08T17:09:26.5996880Z" /> 
  <EventRecordID>359</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-6INROA8</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SlicerApp-real.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>610f67ab</Data> 
  <Data>Qt5Core.dll</Data> 
  <Data>5.15.1.0</Data> 
  <Data>5f506b86</Data> 
  <Data>c0000409</Data> 
  <Data>0000000000021498</Data> 
  <Data>f94</Data> 
  <Data>01d78c7821e42cf2</Data> 
  <Data>C:\Users\oeel\AppData\Local\NA-MIC\Slicer 4.13.0-2021-08-07\bin\SlicerApp-real.exe</Data> 
  <Data>C:\Users\oeel\AppData\Local\NA-MIC\Slicer 4.13.0-2021-08-07\bin\Qt5Core.dll</Data> 
  <Data>1bbf6978-b5bb-40ba-ae7d-bf1746352382</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by XiDeng** [comment]
Also, I ran depends.exe and I got a dwi file :
[SlicerApp-real.zip](https://github.com/Slicer/Slicer/files/6951207/SlicerApp-real.zip)

**Comment by XiDeng** [comment]
[SlicerApp-real.zip](https://github.com/Slicer/Slicer/files/6951221/SlicerApp-real.zip)

**Comment by lassoan** [comment]
What CPU model and graphics does your computer have?
Does installing Microsoft Visual Studio redistributable package solve the issue?

**Comment by XiDeng** [comment]
> What CPU model and graphics does your computer have?
> Does installing Microsoft Visual Studio redistributable package solve the issue?

CPU: Intel i7-7700K
GPU:Nvidia GeForce RTX 2070

My computer exists Microsoft Visual C++ Redistributable Package from 2005 to 2019, both x64 and x86.

**Comment by jamesobutler** [comment]
Was Slicer downloaded from https://download.slicer.org/, or from another website, or manually built and packaged?

Does Qt5Core.dll actually exist at "C:\Users\oeel\AppData\Local\NA-MIC\Slicer 4.13.0-2021-08-07\bin\Qt5Core.dll"?

Do you have an anti-virus/malware that is quarantining these dll files?

**Comment by XiDeng** [comment]
> Was Slicer downloaded from https://download.slicer.org/, or from another website, or manually built and packaged?
> 
> Does Qt5Core.dll actually exist at "C:\Users\oeel\AppData\Local\NA-MIC\Slicer 4.13.0-2021-08-07\bin\Qt5Core.dll"?
> 
> Do you have an anti-virus/malware that is quarantining these dll files?

Yes, the file actually exists at the path

I exit all the anti-virus software in my computer expect Windows safe center(Windows Defender).

**Comment by jamesobutler** [comment]
Do you have other Qt DLLs on system path? 

Have you attempted to install PyQt? Or use other python packages or modules that rely on PyQt?

**Comment by lassoan** [comment]
We had a somewhat similar error reported [here](https://github.com/Slicer/Slicer/issues/5690) but that was on a very old computer. There should be no reason why Slicer could not run on your configuration.

Have you ever run any Slicer version on this computer?

Could you try if [ParaView](https://www.paraview.org/download/) works? (it has a similar software stack as Slicer - with VTK and Qt)

**Comment by XiDeng** [comment]
> We had a somewhat similar error reported [here](https://github.com/Slicer/Slicer/issues/5690) but that was on a very old computer. There should be no reason why Slicer could not run on your configuration.
> 
> Have you ever run any Slicer version on this computer?
> 
> Could you try if [ParaView](https://www.paraview.org/download/) works? (it has a similar software stack as Slicer - with VTK and Qt)

It is my first time to run Slicer on my computer, and I have tried two versions, 4.10 and 4.13, respectively.

I installed and ran ParaView just now, and it is running normally.
![无标题](https://user-images.githubusercontent.com/32667583/128652097-db3b11a1-99a6-4386-9f16-3051e194cd7f.png)

**Comment by XiDeng** [comment]
> Do you have other Qt DLLs on system path?
> 
> Have you attempted to install PyQt? Or use other python packages or modules that rely on PyQt? Or even Pyside?

There are same Qt DLLs in the ITK-SNAP/bin. I found ITK-SNAP/bin in the system path, and I have removed this path. It doesn't work.

I searched "PyQt5" in Everything, and I found some folders in Pycharm's cache folders.![Pyqt](https://user-images.githubusercontent.com/32667583/128652311-aa62f78a-8f16-42df-9d65-1b5563fcff9a.png)

**Comment by lassoan** [comment]
> I found ITK-SNAP/bin in the system path

Wow, that should not happen. On Windows, you should never add a folders of a user program to the the PATH environment variable (other than maybe small statically-built utilities). Adding uncontrolled folders with random DLLs in them can make other programs use those DLLs instead of their own and has [several other disadvantages](https://devblogs.microsoft.com/oldnewthing/20110725-00/?p=10073). If you added folders to your paths because there are programs in it that you want to start without typing the full path, then you can use the [`App Paths`[(https://helgeklein.com/blog/how-the-app-paths-registry-key-makes-windows-both-faster-and-safer/). 

Try to open a command prompt, execute this command to clear the path environment variable (it only has effect in that command prompt):

```
set path=
```

List all the environment variables by `set` command and if you have any Python environment variables then clear them the same way as you cleared the `path`.

Then launch Slicer:

```
cd /d "C:\Users\oeel\AppData\Local\NA-MIC\Slicer 4.13.0-2021-08-07\"
Slicer.exe
```

**Comment by XiDeng** [comment]
> > I found ITK-SNAP/bin in the system path
> 
> Wow, that should not happen. On Windows, you should never add a folders of a user program to the the PATH environment variable (other than maybe small statically-built utilities). Adding uncontrolled folders with random DLLs in them can make other programs use those DLLs instead of their own and has [several other disadvantages](https://devblogs.microsoft.com/oldnewthing/20110725-00/?p=10073). If you added folders to your paths because there are programs in it that you want to start without typing the full path, then you can use the [`App Paths`[(https://helgeklein.com/blog/how-the-app-paths-registry-key-makes-windows-both-faster-and-safer/).
> 
> Try to open a command prompt, execute this command to clear the path environment variable (it only has effect in that command prompt):
> 
> ```
> set path=
> ```
> 
> List all the environment variables by `set` command and if you have any Python environment variables then clear them the same way as you cleared the `path`.
> 
> Then launch Slicer:
> 
> ```
> cd /d "C:\Users\oeel\AppData\Local\NA-MIC\Slicer 4.13.0-2021-08-07\"
> Slicer.exe
> ```

  T^T, I tried this method at the first time, and I removed some path in paths. It doesn't work. And the Event Viewer recorded the same information.

**Comment by XiDeng** [comment]
I noticed that the error module path is "C:\Users\oeel\AppData\Local\NA-MIC\Slicer 4.13.0-2021-08-07\bin\Qt5Core.dll". If it is indicate that the program call the Qt5Core.dll in this path (Right Path)?

**Comment by lassoan** [comment]
Do you have any other instance of Qt5Core.dll on your computer? If an incorrectly implemented software installer (or an unsuspecting user) places Qt binaries in a system location then it may break Slicer (and many other software that use Qt).

**Comment by lassoan** [comment]
It is not possible to continue the investigation without the reporter's feedback. Closing the issue now - will reopen if similar problems come up again.
