### ISSUE TITLE
Cleanup references to midas3 and/or slicer.kitware.com

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5797]
Considering the server `slicer.kitware.com` will be shutdown around September 15th, impacted documentation and/or test should be updated.

## Steps to reproduce

See https://github.com/Slicer/Slicer/search?q=midas3

## Expected behavior

Unless the documentation mentioned the old server to provide historical context, no other occurrences should be reported.

## Related issues

* https://github.com/Slicer/Slicer/issues/5796
* https://github.com/Slicer/Slicer/issues/4602

**Comment by sjh26** [comment]
Remaining occurrences:
- legacy support for Midas in the extension manager code
- extension build tests
