### ISSUE TITLE
SegmentEditor paint 3D click with no change pollutes undo states

### ISSUE THREAD

**Issue by Connor-Bowley** [Slicer/Slicer#5808]
When using the segment editor paint, if you click outside the segment in question such that nothing is paints (e.g. you rotate the 3D image), it counts as one of the "undo states". Pressing undo after this then restores a state that is exactly the same.

## Steps to reproduce

1. Create a segment with something in it
  a. I imported sample data MRHead and used thresholding to create a segment.
1. Show segment in 3D view
2. Enter paint.
3. Paint a sphere onto the segment
4. Left click outside of the existing segment, but in the 3D view such that no new paint is added
5. Click undo (nothing should happen in the 3D view, but the redo button should be enabled)
6. Click undo again (the painted sphere should undo)

## Expected behavior

A click with no change in the actual segmentation while paint is active does not affect the undo/redo stack.

## Environment
- Slicer version: Slicer-4.13.0
- Operating system: Linux - Ubuntu 20.04

**Comment by lassoan** [comment]
Thank you for reporting this. I could see the logic in the proposed behavior, but in Slicer and most other software undo refers to undoing an action, not undoing the effects of an action.

For example, in PowerPoint: change text color of a textbox to red by clicking on the toolbar, click the same button again (there are no visible changes, as the text is already red). Click Undo -> the text remains red. Click Undo again -> the text changes back to its original color.

Therefore, Slicer's current undo/redo behavior is consistent with standard software.

**Comment by Connor-Bowley** [comment]
I understand you point, but if you rotate the image and then press undo it does not un-rotate the image. Also I would liken clicking outside the segment in question to merely moving the text cursor in the PowerPoint presentation. When you undo in Powerpoint in that case, the last "action" was the cursor move, but what is undone is whatever actual change was done before it (adding text, change color, etc).

If in Slicer someone painted in the exact same spot twice (not sure if this is even possible, since it paints on top of already painted material), I could see having to undo twice to remove both actions, but I feel as if something like rotating the image is in another category action. Perhaps we could talk about this at the next weekly Slicer hangout meeting.

**Comment by lassoan** [comment]
> Also I would liken clicking outside the segment in question to merely moving the text cursor in the PowerPoint presentation

I don't find moving the text cursor similar to painting with a brush. It is much more similar when to paint in an already filled area with the same color in MS Paint - and that works exactly the same way as in Slicer.

There are many more improvement possibilities that are more impactful and less controversial. We should focus our attention on those.

**Comment by lassoan** [comment]
@Connor-Bowley thank you for explaining the issue today at the developer meeting. The problem of creating undo state when just the view is rotated is now fixed.

**Comment by Connor-Bowley** [comment]
Thank you!
