### ISSUE TITLE
`qMRMLThreeDWidget` is not supposed to be inherited?

### ISSUE THREAD

**Issue by kerim371** [Slicer/Slicer#5810]
Hi,

I'm developing custom slicer app and I wanted to set custom `qMRMLThreeDViewControllerWidget` to the `qMRMLThreeDWidget`. But `qMRMLThreeDWidgetPrivate` is declared and defined in `qMRMLThreeDWidget.cxx` (i.e. there is no `qMRMLThreeDWidget_p.h` file). Also there is no protected constructor for inherited classes that follows pimpl idea.

Was it hidden intensionally or is it some kind of a drawback?

By the way the similar class `qMRMLSliceWidget` has `qMRMLSliceWidget_p.h` header and Slicer Astro uses it to add custom button.

**Comment by lassoan** [comment]
Please ask Slicer programming questions on the Slicer forum (in Development category). Only enter an issue here if you are fairly certain that you have found a bug, or there is a clearly defined feature request (preferably after discussing it on the forum).
