### ISSUE TITLE
Wrong extension version is installed if clicking Install button in the extension's detail page

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5821]
The extension index seem to offer the most recent version of an extension and not the one that belongs to the current Slicer version, if the Install button is clicked on the extension detail page.

## Steps to reproduce

If Install is clicked in the extension list then everything works:

![image](https://user-images.githubusercontent.com/307929/130733089-15481c83-1fc5-44bb-bcc4-9ce6046e642a.png)

However, if Install is clicked on the extension page then installation is successful, but after restart the modules of the extension do not show up:

![image](https://user-images.githubusercontent.com/307929/130733158-31c967dd-4645-44f5-b3fb-8e369118c261.png)

![image](https://user-images.githubusercontent.com/307929/130732921-e6e1030d-2831-45c0-b523-2ed10c4d7b97.png)

## Environment
- Slicer version: Slicer-4.13.0-2021-08-16
- Operating system: Windows10

**Comment by jcfr** [comment]
Closing. This has been fixed in https://github.com/KitwareMedical/slicer-extensions-webapp/commit/7039737a59d4a20f9c16274659edc2a062c5e703
