### ISSUE TITLE
Qt 5.15.2 upgrade

### ISSUE THREAD

**Issue by fbordignon** [Slicer/Slicer#5825]
I'm always frustrated when I click a button on its padding area, a visual feedback of a click happens, but the clicked() signal is not emitted. This is a known Qt 5.15.1 bug:

https://bugreports.qt.io/browse/QTBUG-86587
https://bugreports.qt.io/browse/QTBUG-88276

I would like to see an upgrade of Slicer Qt version to 5.15.2

I've successfully compiled Slicer 4.11.20210226 with Qt 5.15.2 only by properly changing the Qt5_DIR CMAKE variable on windows.
There seems to be no problems with the interface or anything else.

Originally posted on https://discourse.slicer.org/t/upgrade-to-qt-5-15-2/19366

**Comment by sjh26** [comment]
Done!

- Updated/built/pushed docker image: https://github.com/Slicer/SlicerBuildEnvironment/pull/23
- Updated build scripts: https://github.com/Slicer/DashboardScripts/commit/c3f57092a81b9f63fc5d5e8f3f0a37e262bef611
- Installed Qt 5.15.2 on overload factory

Qt 5.15.2 will be available in the next Preview.
