### ISSUE TITLE
Addition of a label volume drop down in the segment editor and button for overlapping it with the image

### ISSUE THREAD

**Issue by charuu** [Slicer/Slicer#5829]
## Is your feature request related to a problem? Please describe.
I was working on a segmentation problem for a number of images for preparing data for my project and during segmentation it is repeatedly required to load the image and label volume and analyse the overlap for any missing information.
## Describe the solution you'd like
 I would prefer these options on one screen itself which includes addition of a label volume drop down in the segment editor widget and action button for overlapping it with the image 

## Describe alternatives you've considered
I had developed an extension-specific for my project use but I find that this feature would be useful for work on segmentation of images for analysis against the image.

## Additional context

<img width="1186" alt="Screenshot 2021-04-05 at 11 03 29 PM" src="https://user-images.githubusercontent.com/13659619/131174907-c621935b-8da2-4a15-8281-1d0e5e3a332d.png">

**Comment by charuu** [comment]
Yes, but when I have to load 100 masks for images then I would have to select the "Segmentation" option in each. Instead, if all are loaded in one go and when we select the image and label we want, then we can have an option to set it as segmentation on the segment editor itself.

**Comment by lassoan** [comment]
In these cases, you can just name the files in a way that gives Slicer a hint that they are segmentation nodes. Set the filename to `something.seg.nrrd` (instead of `something.nrrd`) and then Slicer will set description to segmentation by default.

**Comment by charuu** [comment]
ok, sounds good. I will close the issue.

**Comment by pieper** [comment]
Note too that in the Add Data dialog you can hold down the shift key while changing the load type of one items and all the matching rows will also change.  With this you could easily load 100 stl or nrrd files as segmentations.
