### ISSUE TITLE
Not able to download Slicer

### ISSUE THREAD

**Issue by polyminds** [Slicer/Slicer#5833]
[Give a short summary of what the problem is]

## Steps to reproduce

[describe what you did and what happened - attach screenshots if possible]

## Expected behavior

[describe what you expected to happen]
- I tired more than a 10 times to download slicer both of the version stable and the latest release by browser and IDM but its not downloading. It just stop and not able to save on computer.

## Environment
- Slicer version: Slicer-4.13.0-2021-09-01 & 4.11.20210226- 2021-03-01
- Operating system: Windows

**Comment by lassoan** [comment]
I've just tested and the download of the latest stable and preview releases using VPNs from a couple of countries in North America, Europe, and Asia and it worked well (download successfully completed well under one minute).

**Comment by polyminds** [comment]
I'm still facing same issue ! It says the packets is not fetchable and download just stop ! Says time out

**Comment by fbordignon** [comment]
Downloads are working for me as well (Brazil)

**Comment by lassoan** [comment]
> I'm still facing same issue ! It says the packets is not fetchable and download just stop ! Says time out

Can you attach a screenshot? I've never seen any message like that in a web browser ever, on any website. What web browser are you using? Do you have any special networking configuration (VPN, corporate firewall, etc.)? Do you have similar problems with other sites?

**Comment by lassoan** [comment]
It seems that the download site operates well, so it must have been a configuration/network issue on the specific user's computer.
