### ISSUE TITLE
DataStore module shows "Not Found"

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5845]
The DataStore module displays: "Not Found -- The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.".

Could you update the server configuration so that it displays a simple static page that:
- explains that the datastore is moved
- includes a link that the user can click (do not auto-redirect!) that opens the new download location
- includes a link that opens a discourse topic where people can ask questions if they have trouble finding a data set (it is probably better to redirect people to an existing topic that is created for this purpose where we can give further hints; we would also prevent many small topics all asking about the data store)

## Steps to reproduce

Open the DataStore module.

## Expected behavior

Display information about how to download data from the data store.

## Environment
- Slicer version: Slicer-4.11.0.20210226, Slicer-4.13.0-2021-09-04
- Operating system: Windows

**Comment by jcfr** [comment]
Previews of the page associated with both the Browse and Upload tab:
* https://deploy-preview-60--extensions-slicer-org.netlify.app/midas3/slicerdatastore
* https://deploy-preview-60--extensions-slicer-org.netlify.app/midas3/slicerdatastore/user/login

![image](https://user-images.githubusercontent.com/219043/133212993-6d221941-f54b-4eae-92df-f4ddab81c244.png)

>  link that opens a discourse topic where people can ask questions if they have trouble finding a data set

What about linking  [this topic](https://discourse.slicer.org/t/datastore-data-not-showing-for-uploaded-dataset/175) ?

**Comment by jcfr** [comment]
Closing. Issue fixed in https://github.com/KitwareMedical/slicer-extensions-webapp/pull/60
