### ISSUE TITLE
extensions manager extensionMetadata bug

### ISSUE THREAD

**Issue by sobiny** [Slicer/Slicer#5848]
Unable to manually install an extension with the ExtensionsManager (duplicate of #5840)

Looking at

https://github.com/Slicer/Slicer/blob/94f9a9a16d6bdfc2ae75250ba2b84571929132b6/Base/QTCore/qSlicerExtensionsManagerModel.cxx#L1723-L1732

`extensionMetadata` is never empty

All modules cannot be installed

delete 1724-1727 or move？

## Steps to reproduce

See details at #5840 

## Environment
- Slicer version: Slicer-4.13.0-2021-09-14
- Operating system: Windows / Linux / Mac

**Comment by jamesobutler** [comment]
@sobiny Are you describing issue #5840 which is the bug of not being able to manually install extensions which displays as "Error retrieving extensions metadata"?

**Comment by sobiny** [comment]
extensionMetadata variable After 1724 lines, the variable is not empty. Cannot enter the judgment function of 1729
So all s4ext description files are left with only one line:

`enabled true`

Many variables such as "slicer_revision" and "arch" cannot be recorded

When the module is loaded, the version is incorrect, the system is incorrect, and the model cannot be activated

right "*.s4ext" file:

```
arch amd64
archivename 30172-win-amd64-MarkupsToModel-git415d506-2020-11-08.zip
category Informatics
contributors Thomas Vaughan (PerkLab, Queen's University), Andras Lasso (PerkLab, Queen's University), Adam Rankin (Robarts Research Center, Western University), Aniqah Mair (PerkLab, Queen's University), Jaime Garcia Guevara (PerkLab, Queen's University)
description Create tube or closed surface models from points of a markup fiducial node.
enabled true
homepage https://github.com/SlicerIGT/MarkupsToModel
iconurl https://github.com/SlicerIGT/SlicerMarkupsToModel/raw/master/MarkupsToModel.png
os win
revision 415d506
scm git
scmurl https://github.com/SlicerIGT/SlicerMarkupsToModel
slicer_revision 30172
status 
```
 @jamesobutler

**Comment by jamesobutler** [comment]
So you are describing #5840 here?

**Comment by sobiny** [comment]
It might be.
Today was when I was compiling the extension, I found that it couldn't be installed. After checking for several hours, I tracked down the problem.
Sorry, but this is the first time I use github. I'm not good at English.
Sorry,Sorry
@jamesobutler

**Comment by sobiny** [comment]
@jamesobutler Yes, I read #5840 carefully, the initial error is the same as mine
