### ISSUE TITLE
Slicer Extensions Catalog Page is empty

### ISSUE THREAD

**Issue by upupming** [Slicer/Slicer#5852]
[Give a short summary of what the problem is]

I have seen it is not able to download extensions for a while on the Windows platform, but now I go to the extension download page, the page is also empty.

When I open the extension manager of my Slicer (built from source code), I got this message:

![image](https://user-images.githubusercontent.com/24741764/133279543-b6c51354-6270-482d-a1af-77d3d9ad1622.png)

The link in the message is https://extensions.slicer.org/catalog/All/30166/win , the page is empty.

## Steps to reproduce

[describe what you did and what happened - attach screenshots if possible]
Go to https://slicer.kitware.com/midas3/slicerappstore?search=&category=All as per [the docs referred](https://slicer.readthedocs.io/en/latest/user_guide/extensions_manager.html#overview).

The page is also empty now:

![image](https://user-images.githubusercontent.com/24741764/133278641-c6f65f63-fbbe-423a-8376-a7b26be3b019.png)

## Expected behavior

[describe what you expected to happen]
Extensions should be listed there.

## Environment
- Slicer version: 4.13
- Operating system: Windows

I have saved a web archive page here (it is also empty, so it may not be the problem of my local network): https://web.archive.org/web/20210914145419/https://extensions.slicer.org/catalog/All/30166/win

**Comment by jcfr** [comment]
Thanks for the report.

Since they are no extensions built for version `30166`, this explains what you observed. There are extensions associated with  the latest preview build. 

See https://extensions.slicer.org/catalog/All/30181/win

You can download the latest version at https://download.slicer.org

For reference, recent preview builds and associated extensions are also available [here](https://slicer-packages.kitware.com/#collection/5f4474d0e1d8c75dfc70547e/folder/5f4474d0e1d8c75dfc705484)

**Comment by jcfr** [comment]
@upupming  Where you able to address your issue downloading the latest preview build at https://download.slicer.org ?

**Comment by upupming** [comment]
The latest build is okay. However I am developing Slicer from source code, what can I do to install the extensions? Thanks

**Comment by jcfr** [comment]
>  However I am developing Slicer from source code, what can I do to install the extensions? 

Association of extensions with a version of Slicer is done based on the Slicer revision, arch and operating system.

It is assumed that the build environment used to build extensions and application also match. This is the case for the installers and extensions we officially make available to the community.

This is why I would suggest to also build locally the extensions you would like to use in your custom version of Slicer.

There are way to circumvent this. To discuss further, I suggest you post a questions on the forum providing more context. See https://discourse.slicer.org/c/dev/5. That way, answers will benefit everyone and will be easily searchable.

Ideally, your post would provide details and answers regarding the following:
- Context of your question. Consider referencing this issue.
- Reasons for building Slicer locally ? Is there missing features ?
- Details about your use case

In the meantime, I will close this issue.
