### ISSUE TITLE
Restore Markups ROI widget

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5857]
Need to fix a few things after the recent pluggable markups rework:

- qMRMLMarkupsROIWidget widget was removed. This widget should have been kept, as it is intended to be reused in module widgets and does not have any Slicer dependency.
- The qSlicerMarkupsROIWidget was given a confusing name. It is not for editing markups ROI widget properties but it is a special qSlicerMarkupsAdditionalOptionsWidget, which displays whatever widgets it considers useful and hides itself if it cannot do anything with the current widget. It should be renamed to qSlicerMarkupsAdditionalROIOptionsWidget or something similar.
- MRML node update handling in qSlicerMarkupsROIWidget is not correct. The markups node modified event should not call onMRMLNodeModified but updateWidgetFromMRML, and all GUI updates should be performed in that method. This method should be called when a MRML node is set.

All other additional options widgets should be updated similarly.

**Comment by RafaelPalomar** [comment]
I'm working on this, which is related to [https://discourse.slicer.org/t/module-pythonqt-qslicermarkupsmodulewidgets-has-no-attribute-qmrmlmarkupsroiwidget/19675/6](https://discourse.slicer.org/t/module-pythonqt-qslicermarkupsmodulewidgets-has-no-attribute-qmrmlmarkupsroiwidget/19675/6)
