### ISSUE TITLE
Download button on Extensions Server does not work

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5863]
Cannot download extensions from the Extensions Server when using a regular web browser.

## Steps to reproduce

- Open this page: https://extensions.slicer.org/catalog/All/30181/win?q=slicerigt
- Click the "Download" button -> the button flashes but nothing happens.
- Click on the extension's icon to open the details page.
- Click the "Download" button -> the button flashes but nothing happens.

## Expected behavior

Clicking "Download" should download the extension package.

## Environment
- Microsoft Edge, Google Chrome
- Operating system: Windows, Microsoft Edge browser

**Comment by lassoan** [comment]
The packages don't show up on the CDash dashboard either.

Workaround: download from https://slicer-packages.kitware.com/#collection/5f4474d0e1d8c75dfc70547e/folder/5f4474d0e1d8c75dfc705484

**Comment by lassoan** [comment]
Packages show up on CDash, but the Download button still does not work.

This is quite bad because IT admins changed something at CHOP (Matt Jolley's group) and now they can only access the extensions manager via their standard web browser. However, they cannot download anything using the extensions server.

For example, open this link: https://extensions.slicer.org/catalog/All/30338/win then click on any download buttons - nothing happens.

**Comment by lassoan** [comment]
@jcfr please check this. It may be an easy fix and it would make a huge difference for users behind hospital/corporate firewalls.

**Comment by jcfr** [comment]
See https://github.com/KitwareMedical/slicer-extensions-webapp/issues/13

**Comment by lassoan** [comment]
OK, I'll comment on that issue.

**Comment by lassoan** [comment]
This has come up again: https://discourse.slicer.org/t/how-do-i-integrate-these-installed-extensions-into-the-exe-installation-package/20525

**Comment by jcfr** [comment]
Thanks, I will tackle this in the next few days.

**Comment by jcfr** [comment]
Closing. A fix has been integrated. See https://github.com/KitwareMedical/slicer-extensions-webapp/pull/64
