### ISSUE TITLE
Unable to see rendered volume in the 3D viewer

### ISSUE THREAD

**Issue by charuu** [Slicer/Slicer#5884]
After compiling the Slicer repos from source, I launched the application and loaded a .vtk image. On performing volume rendering, I am unable to see the volume and get error :

void qSlicerVolumeRenderingModuleWidget::onEffectiveRangeModified() : Invalid volume property node

## Steps to reproduce

Load .vtk volume using data loader
Switch to volume rendering module 
Click on the eye next to volume drop down.

## Expected behavior

I should be able to see a 3D rendered volume

## Environment
Slicer version: 4.13.0-2021-09-18 r30223 / bcaab0a
OS. : 10.14.5 (18F132)

**Comment by lassoan** [comment]
Have you clicked the ["Center 3D view" button](https://slicer.readthedocs.io/en/latest/user_guide/user_interface.html#d-view) after enabling volume rendering?

What are the image dimensions and spacing of the volume? (see in Volumes module / Volume information section)

Does [drag-and-drop of the volume from the Data module to a 3D view](https://slicer.readthedocs.io/en/latest/user_guide/user_interface.html#selecting-displayed-data) work?

**Comment by charuu** [comment]
On centering i dont see any change:
<img width="692" alt="Screenshot 2021-09-21 at 6 04 53 PM" src="https://user-images.githubusercontent.com/13659619/134171518-2f6262aa-00dd-4d13-9e26-40812c6aded1.png">

Image dimensions are 300 X 300 X 400
Image spacing  0.1mm

**Comment by charuu** [comment]
And dragging and dropping on 3D viewer makes no difference

**Comment by lassoan** [comment]
What is the Scalar Type and Scalar Range (in Volume information section)?

**Comment by charuu** [comment]
Scalar type is float 
Scalar range is -1725.6 to 2037.74

**Comment by lassoan** [comment]
I see. For float volumes, it may be hard to find a good threshold value automatically. You can adjust the "Shift" slider to choose what is shown.

**Comment by charuu** [comment]
But volume rendering works in Slicer version 4.13.0-2021-08-27 r30134 / 72b3a74, for the same image
<img width="759" alt="Screenshot 2021-09-21 at 6 20 42 PM" src="https://user-images.githubusercontent.com/13659619/134173619-c8ddafc8-72bd-4ade-bc3e-dc6c92022b6c.png">

**Comment by lassoan** [comment]
> AddNewNodeByClass: failed to create node by class vtkMRMLAnnotationROINode

This suggests that this Slicer installation has been corrupted. Could you try the installing the very latest Slicer Preview Release and see if it works as expected?

**Comment by jamesobutler** [comment]
@charuu Are you still able to replicate this issue with the very latest Slicer Preview build?

**Comment by lassoan** [comment]
No response was received from the user, assuming the problem got resolved. Closing this.
