### ISSUE TITLE
Markups control point placement improvements

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5889]
This is a follow-up to pull request https://github.com/Slicer/Slicer/pull/5325. It contains fixes and improvements that were identified during the review but has not been completed before the integration:

- [ ] When clicking the control point table to edit a point then the point position is filled immediately. This position gets deleted if I move over to a view and leave the view and the edit icon disappears from the table. It would be better if starting editing would just change the icon to edit (would not show the coordinates) and after going over a view and coming back, the edit icon would stay displayed in the table while placement mode is enabled. This would make it clear for the user which point will be the next to place (without need to hover over any view) and would ensure that the table state would not be changed just because the user temporarily moves the mouse over a view.
- [ ]  vtkMRMLColorTableNodeRandom color table is not designed for creating nice, distinguishable colors. Instead, use MediumChartColors, DarkBrightChartColors, LightPaleChartColors. Make the color index start at 0 (not at 3) and wrap around if the color index reaches the number of values in the color table. Remove UpdateCurrentColorTableIndex (fuse it into GetNewMarkupsColor). Make GetNewMarkupsColor return a double* (you need to add a `double LastReturnedMarkupsColor[3];` in the class to store the vector that is returned) and add `VTK_SIZEHINT(3)` to make the method conveniently usable from Python.
- [ ] It is inconsistent that ROIs have all the same color if created one by one but have different colors if "Place multiple control points" is enabled.
- [ ] Lot of "child widget is not accessible warnings" when selecting a control point in the table
- [ ] The down-arrow button on the place widget's place button should be hidden if the force single/force multiple option is chosen. 
- [ ] Fix failing toolbar test: qSlicerMouseModeToolBarTest1
- [ ] Update documentation (https://slicer.readthedocs.io/en/latest/user_guide/modules/markups.html#)
- [x] *Display* markups toolbar -> *Toggle* markups toolbar (because the same menu is used for showing/hiding)
- [x] Node selector and color selector in the toolbar must have the same height as the toolbar buttons
- [x] Add a spacer between the new markup buttons and the node selector button

**Comment by muratmaga** [comment]
There is a bug that the locked (template) state of the fiducial node is not retained after save, when loading it into a new scene. 

I am not sure whether this has anything to do with Markups module changes, but file location after loading for a fiducial node is not retain. Save a fiducial node on desktop, reset scene, load the fiducial from json, add a point and use the save as to see that it defaults the ~/Documents as oppose to where the file was read from. This has big potential for data loss. If this is not related to markups changes, I can file a separate bug.

**Comment by lassoan** [comment]
I am also investigating issues reported here:

https://github.com/Project-MONAI/MONAILabel/issues/422

I've already found a logic error in the markups place widget (in the update-gui-from-mrml method there are update-mrml-from-gui calls). I'm implementing the fix, along with a few others.

**Comment by smrolfe** [comment]
Thanks, I have submitted a pull request to fix the locked state issue on loading and am looking at the others.

**Comment by lassoan** [comment]
@muratmaga the two issues that you reported are fixed in https://github.com/Slicer/Slicer/commit/cfc69c5fcd8e119dcf3060561c999c8a9baebd93

**Comment by lassoan** [comment]
We are starting to get questions/complaints about ROIs "not working", which is actually due to people not being able to figure out how to place annotation ROIs now. We'll speed up adding full support of markups ROIs everywhere where annotation ROIs are used now, but we need to tell the users what they can do right now.

@smrolfe Please create a post on discourse that describes the changes, explains the rationale (so that people appreciate the improvements and not just be upset about the changes), and tells how they can add and edit the old annotation ROIs now. It would be nice if you could create a 1-minute youtube video about the new features and a separate short (10 seconds or so) video about how to create annotation ROIs. Please do this as soon as possible, this is more important than all the other fixes and improvements that we have been talking about.

**Comment by jamesobutler** [comment]
Using the Slicer Preview 4.13.0-2021-09-23 (4eed6072b8e2d2be1b237aae2ff88af72cd91b0d) placing vtkMRMLAnnotationRulerNode from the GUI also been removed? Those objects have ruler tick marks that the line node does not have. It may have been fixed, but is this similar in issue to not being able to place the older vtkMRMLAnnotationROINode objects?
![image](https://user-images.githubusercontent.com/15837524/134781075-d9929047-d21f-418d-88e5-8aac5e75464c.png)

**Comment by smrolfe** [comment]
@lassoan Thanks, I am putting these videos together right now with today's preview version.

**Comment by smrolfe** [comment]
@jamesobutler that looks like it's a bug, I will fix in the next build if so.

**Comment by smrolfe** [comment]
@jamesobutler it looks like this was fixed as of the last commit by @lassoan.

However with this version I am experiencing a new issue, where the placement button is always inactivated, so only one fiducial point can be placed.

**Comment by lassoan** [comment]
@jamesobutler I don't understand why tickmarks are useful for distance measurement lines. Continue the discussion about thisntipic here: https://discourse.slicer.org/t/tickmarks-on-markups-line/17865

**Comment by lassoan** [comment]
> However with this version I am experiencing a new issue, where the placement button is always inactivated, so only one fiducial point can be placed.

The very latest Slicer master version (not available as a release package yet, as I've committed the fix this morning) works well for me. The placement button gets deactivated the right time (when "point number locked" is enabled and all points are defined or missed).

**Comment by smrolfe** [comment]
I built the most recent master and the place button is never becoming active, even when the point number is unlocked as here: 

<img width="903" alt="image" src="https://user-images.githubusercontent.com/43060230/134785548-51a4754f-b743-4c9f-9c41-2c1b14359fb4.png">

If it's not replicating for you, maybe it's an issue with my build. I will try a fresh build.

**Comment by lassoan** [comment]
How do you create the node and add the points? Can you describe the exact clicks?

**Comment by smrolfe** [comment]
I used the "create new fiducial node" button in the Markups toolbar and clicked in the scene to place one point. 

I am rebuilding the latest master now and will update here when I have tested it.

**Comment by smrolfe** [comment]
I put together very short videos showing the new Markups functions and the changes to the Annotations module. Since the Annotations won't work correctly until the next preview, would it make sense to post these tomorrow? I'm also planning to make a video showing a landmark templating procedure.

https://youtu.be/ddd1U61eVlo
https://youtu.be/0NvZaLJQeyE

**Comment by lassoan** [comment]
Yes, I think it makes sense to create a post now and just mention if a release has bugs/limitations.

**Comment by lassoan** [comment]
Do you use Camtasia for recording videos? You can add cursor effects there to make mouse clicks visible. It would make the videos a bit more clear.

Can you make the annotation video shorter? You don't need to explain any annotations features (the whole module will go away anyway, so it is better not to teach people what features it has). Just in 20 seconds show what are the 5 mouse clicks users need to place an annotation ruler or line.

Placing an annotation ROI/ruler took 4 mouse clicks before, so that would not be too bad, but I guess the main regression is that they need to switch modules. What do you think about adding a section to the right side of the toolbar to place annotations:

    [Label: "Legacy:"] [Button: place ROI] [Button: place ruler] [button: go to Annotations module]

**Comment by jamesobutler** [comment]
The updated qSlicerMarkupsPlaceWidget seems to create weird situations when it is used elsewhere such as in the SurfaceCut effect area. The place button has a menu drop down but there is no addition menu options as it is always in continuous placement mode.

There is also the ability to unset points with the menu options of the delete button which then leaves the model in a weird state that can't be applied.

Any other uses of qSlicerMarkupsPlaceWidget that may now have weird behavior now?
![image](https://user-images.githubusercontent.com/15837524/134789076-46d6c059-c81e-4475-9bf8-0832f957b9f0.png)

**Comment by jamesobutler** [comment]
Also what is the reason for having both of these widgets? I was a bit confused about which one to use.
![image](https://user-images.githubusercontent.com/15837524/134789169-8e1988bd-3c68-426c-a0cd-c665d280d3b5.png)

**Comment by lassoan** [comment]
> The updated qSlicerMarkupsPlaceWidget seems to create weird situations 

We remained backward compatible with existing widgets, but the new features are enabled by default. We can revisit the markups place widget and make the new features disabled by default. Please keep send these comments @jamesobutler, they are very helpful.

If you can still edit your comments then add a '- [ ]` to each action item so that we can track their completion more easily.

>  what is the reason for having both of these widgets?

The two buttons are different: one is a mouse mode selector, the other is a markups place widget. They look very similar (the icon is the same and the main action is the same), but not exactly (one is a toggle, the other is a buttongroup; the dropdown menu is different, too). I agree that it is not ideal, it is somewhat redundant and may be confusing, but we experimented with at least 10-15 combinations in the last several months and this GUI came out as the winner.

Suggestions are welcome. I hope that as we use this GUI it'll become more clear how it should be improved.

For example, we could hide the button from the markups toolbar (and move the multiple point place option to the "..." menu), but it would be a bit strange that the most important button is missing from the markups toolbar.

**Comment by jamesobutler** [comment]
When I start Slicer the toolbutton in the mouse mode toolbar is just a toggle markups toolbar button. It gets confusing after adding a fiducial node as this toggle toolbar action is no longer the default action in the toolbar so it appears the Toolbutton is now completely different since the default action does a very different thing.
![image](https://user-images.githubusercontent.com/15837524/134789531-c30eb705-c665-45f0-967e-413c1e1c60eb.png)
![image](https://user-images.githubusercontent.com/15837524/134789564-caacaeca-ab59-4252-94a5-5b84d7afb3a7.png)

My suggestion would be to make the placement action the default action always even on startup and have the toggle markups toolbar be consistently the submenu action.

**Comment by jamesobutler** [comment]
- [ ] What is the correct terminology to use? This will become an issue communicating to users on the forum or elsewhere. This should be made consistent across all previous and new functionality.
- Fiducials
- Markups
- Markups Points
- Points
- Control Points

![image](https://user-images.githubusercontent.com/15837524/134789714-d909a234-3873-4986-b8f2-a6f0c37010af.png)
![image](https://user-images.githubusercontent.com/15837524/134789688-ec5409f9-a89c-4c38-a8e2-bb9f5a9b40e2.png)
![image](https://user-images.githubusercontent.com/15837524/134789833-9443c6b7-4bb2-4fd7-a157-093d6884047d.png)
![image](https://user-images.githubusercontent.com/15837524/134789681-14b0cf12-0768-4e77-8ffd-75c9123f06e8.png)
![image](https://user-images.githubusercontent.com/15837524/134789692-bbb98a3c-932e-4392-9cb9-c57eb291192d.png)
![image](https://user-images.githubusercontent.com/15837524/134789765-249835b3-c029-4721-8d69-5f4fd50b841c.png)

**Comment by jamesobutler** [comment]
- [ ] Mouse cursor icon is not updating when placing Annotation Ruler or Annotation ROI nodes. It stays as the regular mouse arrow cursor type during the placement of the 2 required control points for these objects. Toggling a Markups line node will have the correct cursor icon. It toggles on both circled widgets in the image below. 
![image](https://user-images.githubusercontent.com/15837524/134790518-da923c43-e116-4fff-8f22-d4a4fb1656bb.png)
However when the place buttons for the annotation module are pressed they only toggle on one of these widgets.
![image](https://user-images.githubusercontent.com/15837524/134790547-60a01ca0-882e-4584-bcb1-b14731fd301f.png)
![image](https://user-images.githubusercontent.com/15837524/134790566-3ad6222b-dbc4-4737-b344-8bcfb468e669.png)

**Comment by muratmaga** [comment]
>     * What is the correct terminology to use? This will become an issue communicating to users on the forum or elsewhere. This should be made consistent across all previous and new functionality.

First screen capture is correct. That's the fiducial node, and the person is placing a fiducial. 
Second one should be changed to match the first. 

In the third one more accurate description of the behavior would be "Locks the markup list so that all mouse interactions for points in the list are disabled".

Fourth/fifth are a bit tricky for fiducial type, as the individual "points" are shown as control points in the module tab. While it makes sense for all other markup types, "control point" term is a bit redundant for fiducials. I use points and control points interchangeably to refer to individual entries in a Markup node. Perhaps we can remove the "control" from "control points" and just simply use points, which is also shorter for these kinds of tooltips.

**Comment by lassoan** [comment]
There are control points, curve points (interpolated points between curve points for curves), and interaction points (for moving, scaling the node; used heavily for ROI). So, while it would be very nice to simplify the terminology, I think we should keep using the "control point" terminology on the user interface. We can omit the "control" word if it is obvious what we mean (for example in the "Control points" section we can just use "point").

- Place buttons: "Use mouse to place a point" would make sense to me, as this button does not create new nodes anymore (except when multiple placement is enabled).

**Comment by jamesobutler** [comment]
I can work on the tedious part of finding all the text places to be more consistent in their terminology.

**Comment by smrolfe** [comment]
I've added a post on discourse with a brief explanation of the changes and demo videos (including the new shorter annotations clip) [here](https://discourse.slicer.org/t/changes-to-the-markups-module/19871).

**Comment by jamesobutler** [comment]
I've been using the new markups toolbar a bit and have some observations. 

Can we make the markup node creation more collapsed? Since it is in a QToolBar, similar actions like node creation should be included in a menu of a QToolButton. The more expanded view where all markup node creation buttons are shown is appropriate in the actual Markups module. Markups is a pluggable framework where more markups can be registered and added into Slicer and creating a new button in the toolbar for each registered markup is not sustainable as it will only make the Markups toolbar larger. What do you all think of the following change?

Current Markups ToolBar:
![image](https://user-images.githubusercontent.com/15837524/134817956-a21c85d7-3c8f-4d0f-8466-df7741ec9b7e.png)

Proposed Markups ToolBar:
![image](https://user-images.githubusercontent.com/15837524/134817973-c7229656-6c4c-4874-a274-a86b2a18bf5f.png)

Markups Module:
![image](https://user-images.githubusercontent.com/15837524/134818022-eebc24c5-5d5d-4dd7-8c12-3ce3463fd58c.png)

**Comment by muratmaga** [comment]
I personally have no preference. I like the aesthetics of the proposed solution, but the currently layout gives you what's available in terms of markupNodes visually, and probably easier to learn for new comers to Slicer.

There has been quite a bit of activity on Markup types in the last two years, but are we expecting more types appearing anytime soon?

**Comment by jamesobutler** [comment]
The Markups module was updated with a pluggable interface for extensions to register more markups. That support was only added in mid-April of this year so it’s pretty new in regards to support of more markups being added separately from what is in Slicer core.

**Comment by pieper** [comment]
Yes, as @jamesobutler points out, the generalization of the markups by @RafaelPalomar should lead to greater use of markup types for sophisticated interactive functions like parametric structures for measuring or editing.

**Comment by lassoan** [comment]
> There has been quite a bit of activity on Markup types in the last two years, but are we expecting more types appearing anytime soon?

There will be more: Bezier surface (already in progress), NURBS surface (already in progress), arrow, bidirectional measurement, Cobb's angle, etc. Most of them will be provided in extensions.

**Comment by jamesobutler** [comment]
re https://github.com/Slicer/Slicer/issues/5889#issuecomment-927342225 I've issued https://github.com/Slicer/Slicer/pull/5901 with the proposed changes for node creation in the toolbar using a menu rather than individual buttons.

**Comment by smrolfe** [comment]
> Can we make the markup node creation more collapsed?

Moving from a dropdown menu to push buttons for node creation was request from @lassoan, to make the interface more intuitive. However, with changes to the place button/addition of the node selector maybe this is now less necessary?

These buttons are also consistent with the node creation buttons in the Markups module, which would have the same issues if many more node types are added.

**Comment by jamesobutler** [comment]
I think the Markups module can be in more of uncollapsed state with the markups type organized in a grid layout design. The markups module can have lots of details shown at once including all markups types. This could also be changed to a different method once the user has to search through a very large list. However the Markups toolbar needs to be in a more tightly organized design as ToolBars take advantage of menus for having lots of actions in a small space. The toolbar is currently already large and not set up in a sustainable manner to add more markups.

**Comment by lassoan** [comment]
Adding a popup menu to the markups toolbar to save space does not make much sense to me, as we can have the entire application window width for a toolbar (enough for probably 50 different kind of markups). The popup makes sense if we move back node creation to the mouse mode button, but the problem there was that it was not clear if that button creates a new point or a new node, and we also wanted to have a chance for users to see which one is the active node, select an active node, set color, visibility, lock state, and other basic properties. These many features don't fit in the mouse mode toolbar. If we add a second toolbar then we have a lot of space...

@jamesobutler we went through many iterations of this GUI. There were several variants with having markups creation in a popup. We can revisit all the decisions, but we should experiment with paper prototype, figma, or work on alternative designs in private branches and not in the main branch.

> the Markups toolbar needs to be in a more tightly organized design

I think we have lots of space, because when somebody is landmarking then he can temporarily show the markups toolbar in a new toolbar row.

**Comment by jamesobutler** [comment]
Unfortunately for our group having all markup node creation types shown all at once in the toolbar is going to be a nonstarter for us to use it. Unfortunately because node creation has moved completely to the toolbar and not in the Mouse Mode toolbar we now don’t have a good option. More rows of toolbars is not a design we would like as it decreases vertical space for important things like the slice viewers and module panel area. Having a really long markups toolbar won’t be able to fit well with some other standard toolbars still visible.

**Comment by muratmaga** [comment]
The nice thing about this current layout, you don't have to use the toolbar, if you don't want to. You can do the node creation within the Markups module and then continue adding points to them using the place mode. 


![image](https://user-images.githubusercontent.com/21285140/134825229-4b11fc52-9a59-4407-96d2-a26eaadf0f19.png)

**Comment by jamesobutler** [comment]
Since we use the markups functionality primarily for measurements having to constantly switch the active module to Markups to be able to place a ruler/line node is not very efficient compared to what we have had which is a quick toolbar action (while still having a single toolbar area).

**Comment by muratmaga** [comment]
WOn't a shortcut for line node creation fix your issue?

**Comment by jamesobutler** [comment]
A keyboard shortcut would work only if it was duplicated with a GUI object like a toolbar action. Keyboard shortcuts are hidden and not helpful for new users.

**Comment by muratmaga** [comment]
I agree about the keyboard shortcuts being hidden and not discoverable easily for new users. But they tend to be the most effective thing for repetitive tasks and allow for two-hand operation, as you don't even have to change the focus of mouse cursors from your slice views or 3D render window, and keep adding measurements... 
It does require training people, but so does pretty much everything in Slicer.

**Comment by jamesobutler** [comment]
Yes, keyboard shortcuts are great for advanced power user stuff that can be trained. However, I’m hoping to make Slicer easy and simple for new users and not have to require training. Slicer being difficult to use is something I would hope to change rather than an accepted fact.

I would be willing to help brainstorm a better solution for the community in regards to the toolbar design. I haven’t seen much talk on the discourse forum regarding design changes to the toolbar area. This would be helpful as markup placement is likely one of the most used toolbar options. There was https://discourse.slicer.org/t/proposed-changes-to-markups-to-support-unplaced-points/12714/13 from July 2020 about adding unset/set abilities for control points which I’m all fine with. However maybe I missed a post about design changes for the toolbars?

**Comment by lassoan** [comment]
> More rows of toolbars is not a design we would like as it decreases vertical space 

Have you considered snapping the toolbar to the left or right? It does not impact vertical space then. However, you then need a solution for the node selector (convert it to some kind of a pop-up widget in vertical mode.

Also, even if the toolbar remains horizontal, is needs to be shown only temporarily, so it should have minimal impact.

> Since we use the markups functionality primarily for measurements having to constantly switch the active module to Markups to be able to place a ruler/line node is not very efficient

The toolbar alone was not actually usable for measurements. For example, you could not place multiple markups fiducials or curves using only the toolbar (there was no way to indicate to create a new point or a new node). At the minimum you need a way to delete the last placed point, a node selector, a way to delete a node,  and a way to distinguish creating new node/point, but having shortcuts for other features (lock/unlock, show/hide, etc.) can be very handy, too.

The idea was that since we already have a dedicated toolbar in a new row (because obviously there is no space in the existing toolbar row for an additional a node selector and several extra buttons) then we have plenty of space,

I would change the popup/exposed style of markup node create buttons until there is a clear

**Comment by muratmaga** [comment]
>  However, I’m hoping to make Slicer easy and simple for new users and not have to require training.

This is a different discussion, but I have been through that about three years ago when we started with SlicerMorph, then sort of accept the fact that the best we can do is to document things thoroughly for our specific usage, and keep documentation up to date. The with problem making it simple (as I came to accept) that there are so many different uses and users that simplifying for some is going to cause a problem for others (like we are facing right now).

**Comment by jamesobutler** [comment]
^ I would suggest a Slicer custom application which is what we do for further customization to simplify workflows. However there can be a balance of simple to use with advanced options with good design. That’s how I help regular Slicer.

**Comment by lassoan** [comment]
> However maybe I missed a post about design changes for the toolbars?

The [pull request](https://github.com/Slicer/Slicer/pull/5325) has been under review for almost a year. You even reviewed and gave feedback on it. Everything was developed and discussed fully openly, constantly listening for feedbacks and suggestions. Discussions can be on discourse but also in tickets or pull requests, so I agree that it is easy to miss things.

We could try to agree on these high-level questions first:
1. What is the minimum feature set needed for making measurements?
2. Are these features fit on the existing single toolbar row or temporarily showing a second toolbar while doing measurements is acceptable.

If we can pin these down then we can limit the number of options that are on the table.

**Comment by lassoan** [comment]
> accept the fact that the best we can do is to document things thoroughly for our specific usage

I haven't given up on this. We need to aim for making simple things simple and complex things possible. It is not easy to achieve this and there are very few successful examples, but we should definitely do better than now.

**Comment by jamesobutler** [comment]
Yes reviewing the pull request in detail could have brought up some of these issues sooner though building the changes is a bigger requirement than posting designs on discourse. There is more likely community feedback to pictures of design on the forum than having to build a pull request.

> We could try to agree on these high-level questions first:
> 
> What is the minimum feature set needed for making measurements?
> Are these features fit on the existing single toolbar row or temporarily showing a second toolbar while doing measurements is acceptable.

I would be happy to respond to this on a discourse post where we are likely to receive more community feedback.

**Comment by lassoan** [comment]
> I would be happy to respond to this on a discourse post where we are likely to receive more community feedback.

No problem, it could make sense to take this question to discourse, this thread is becoming a bit too long anyway.

**Comment by cpinter** [comment]
> making simple things simple

Off-topic, but an idea that could facilitate this: do we have a list of these "simple things" that we want to make simple? If not, then a page containing a list of these simple things and a description about how they are simple already and what should be improved would serve as a good guideline for core Slicer designers. Complex things are already possible, so I think what is missing here are the simple things.

**Comment by jamesobutler** [comment]
- [ ] Go to the markups module, create a new markups node (e.g. vtkMRMLMarkupsFiducialNode), then I'm unable to toggle off placement mode in the mouse mode toolbar
![image](https://user-images.githubusercontent.com/15837524/135181891-546a60dc-c5fb-4636-bb7d-33f33e2b8199.png)

**Comment by lassoan** [comment]
> unable to toggle off placement mode in the mouse mode toolbar

The mouse mode buttons have been working like this for many years. It is effectively a radio button group rendered in pushbutton style, and not independent toggle buttons. You cannot deactivate a button by clicking on it, but clicking always activates the button.

We could consider converting them to toggle buttons for consistency with the place button.

**Comment by jamesobutler** [comment]
Anyone else noticing that the WindowLevel mouse mode cursor icon is no longer present while in that mouse mode? I can adjust window level while in the mode, but the correct cursor icon is missing.

**Comment by cpinter** [comment]
I downloaded a release yesterday, and in that I cannot see a different mouse cursor in W/L mode as I did before, it is always the default cursor, so it seems to be a regression.

By the way I really like the way the markups toolbar works. Much more intuitive when you add a node and when a point. I don't mind it being wide, because the right half of it can disappear with the leftmost half shown only. That said I don't think I'd miss the right half if it wasn't there, or was available in an extras section or something.

**Comment by cpinter** [comment]
> mouse mode cursor icon for markup control point placement is also no longer present

I can confirm this too.

**Comment by lassoan** [comment]
I'll split up this ticket to many because there are too many tasks and probably @smrolfe cannot work on all of them at once and they each may require discussion.

**Comment by cpinter** [comment]
Another bug: the custom markups registered externally do not appear in the toolbar. They did appear before in the dropdown.

**Comment by lassoan** [comment]
This issue has become unmanageable. I've moved all the open issues to these tickets:
- https://github.com/Slicer/Slicer/issues/5911
- https://github.com/Slicer/Slicer/issues/5912
- https://github.com/Slicer/Slicer/issues/5913
- https://github.com/Slicer/Slicer/issues/5914
- https://github.com/Slicer/Slicer/issues/5915
- https://github.com/Slicer/Slicer/issues/5916
- https://github.com/Slicer/Slicer/issues/5917
- https://github.com/Slicer/Slicer/issues/5918

I haven't created an issue for the problem of mouse mode and place buttons looking similar and doing similar things. That would probably worth a discussion on the Slicer Forum to figure out what a good overall behavior could be.

I'm closing this issue, for any additional problems submit a new bug report; and for improvements to discuss, start a topic on the Slicer Forum.
