### ISSUE TITLE
Loading a DICOM directory with 352 files the error is "Could not load", <dir> - as a 3 frames MultiVolume by B.standard value

### ISSUE THREAD

**Issue by ignaciordc** [Slicer/Slicer#5894]
The MultiVolumeImporterPlugin breaks when trying to load the data. Sometimes only.

## Steps to reproduce
The data has been 'manipulated' to stitch 4 different sections with 138 images each.
This process of stitching generates a directory with all the images (138x4) as a single sequence.
Loading these generated directories as data, sometimes works and sometimes breaks, which might mean that the stitching process is weak and does not check well that the tags modified contained proper information.

The only fields I am modifying in the DICOM files in the stitching process are:
['Image Type', 'Series Time', 'Series Description',
                'Series Instance UID', 'Series Number', 'Instance Number',
                'SAR', 'Frame of Reference UID', 'Slice Location']
I do not discard that the original, unmodified files have tags with missing information for the 3D volume....

[describe what you did and what happened - attach screenshots if possible]
![error_3d_001](https://user-images.githubusercontent.com/5857265/134751882-ac9f5036-b3b4-41f4-bad2-5b24021929fe.png)
![error_3d_003](https://user-images.githubusercontent.com/5857265/134751890-b0704aac-7ee1-4016-a5fc-91b4cfaf301b.png)
![error_3d_002](https://user-images.githubusercontent.com/5857265/134751893-b73e01b3-11fe-4827-b7d9-3bc9834a81b9.png)

## Expected behavior

Display the Volume and the other 3 2D views. This is ocurring 70% of the times....

## Environment
[DEBUG][Qt] 25.09.2021 02:21:14 [] (unknown:0) - Session start time .......: 2021-09-25 02:21:14
[DEBUG][Qt] 25.09.2021 02:21:14 [] (unknown:0) - Slicer version ...........: 4.11.20210226 (revision 29738 / 7a593c8) win-amd64 - installed release
[DEBUG][Qt] 25.09.2021 02:21:14 [] (unknown:0) - Operating system .........: Windows /  Professional / (Build 18363, Code Page 65001) - 64-bit
[DEBUG][Qt] 25.09.2021 02:21:14 [] (unknown:0) - Memory ...................: 32574 MB physical, 37438 MB virtual
[DEBUG][Qt] 25.09.2021 02:21:14 [] (unknown:0) - CPU ......................: GenuineIntel , 8 cores, 8 logical processors
[DEBUG][Qt] 25.09.2021 02:21:14 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, TBB threading
[DEBUG][Qt] 25.09.2021 02:21:14 [] (unknown:0) - Qt configuration .........: version 5.15.1, with SSL, requested OpenGL 3.2 (compatibility profile)
[DEBUG][Qt] 25.09.2021 02:21:14 [] (unknown:0) - Developer mode enabled ...: no
[DEBUG][Qt] 25.09.2021 02:21:14 [] (unknown:0) - Prefer executable CLI ....: yes
[DEBUG][Qt] 25.09.2021 02:21:14 [] (unknown:0) - Application path .........: C:/Users/ignac/AppData/Local/NA-MIC/Slicer 4.11.20210226/bin
[DEBUG][Qt] 25.09.2021 02:21:14 [] (unknown:0) - Additional module paths ..: NA-MIC/Extensions-29738/SlicerOpenCV/lib/Slicer-4.11/qt-loadable-modules, NA-MIC/Extensions-29738/DeepInfer/lib/Slicer-4.11/qt-scripted-modules, NA-MIC/Extensions-29738/SlicerJupyter/lib/Slicer-4.11/qt-loadable-modules, NA-MIC/Extensions-29738/SlicerJupyter/lib/Slicer-4.11/qt-scripted-modules, NA-MIC/Extensions-29738/SlicerDMRI/lib/Slicer-4.11/cli-modules, NA-MIC/Extensions-29738/SlicerDMRI/lib/Slicer-4.11/qt-loadable-modules, NA-MIC/Extensions-29738/SlicerDMRI/lib/Slicer-4.11/qt-scripted-modules, NA-MIC/Extensions-29738/UKFTractography/lib/Slicer-4.11/cli-modules, NA-MIC/Extensions-29738/UKFTractography/lib/Slicer-4.11/qt-loadable-modules, NA-MIC/Extensions-29738/UKFTractography/lib/Slicer-4.11/qt-scripted-modules
[DEBUG][Python] 25.09.2021 02:21:16 [Python] (C:\Users\ignac\AppData\Local\NA-MIC\Slicer 4.11.20210226\lib\Python\Lib\site-packages\pydicom\datadict.py:432) - Reversing DICOM dictionary so can look up tag from a keyword...
[CRITICAL][Stream] 25.09.2021 02:21:17 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 25.09.2021 02:21:17 [] (unknown:0) -   File "<string>", line 1, in <module>
[CRITICAL][Stream] 25.09.2021 02:21:17 [] (unknown:0) -   File "C:\Users\ignac\AppData\Local\NA-MIC\Slicer 4.11.20210226\lib\Python\Lib\imp.py", line 170, in load_source
[CRITICAL][Stream] 25.09.2021 02:21:17 [] (unknown:0) -     module = _exec(spec, sys.modules[name])
[CRITICAL][Stream] 25.09.2021 02:21:17 [] (unknown:0) -   File "<frozen importlib._bootstrap>", line 618, in _exec
[CRITICAL][Stream] 25.09.2021 02:21:17 [] (unknown:0) -   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[CRITICAL][Stream] 25.09.2021 02:21:17 [] (unknown:0) -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[CRITICAL][Stream] 25.09.2021 02:21:17 [] (unknown:0) -   File "C:/Users/ignac/AppData/Local/NA-MIC/Slicer 4.11.20210226/NA-MIC/Extensions-29738/DeepInfer/lib/Slicer-4.11/qt-scripted-modules/DeepInfer.py", line 1, in <module>
[CRITICAL][Stream] 25.09.2021 02:21:17 [] (unknown:0) -     import Queue
[CRITICAL][Stream] 25.09.2021 02:21:17 [] (unknown:0) - ModuleNotFoundError: No module named 'Queue'
[CRITICAL][Qt] 25.09.2021 02:21:17 [] (unknown:0) - loadSourceAsModule - Failed to load file "C:/Users/ignac/AppData/Local/NA-MIC/Slicer 4.11.20210226/NA-MIC/Extensions-29738/DeepInfer/lib/Slicer-4.11/qt-scripted-modules/DeepInfer.py"  as module "DeepInfer" !
[CRITICAL][Qt] 25.09.2021 02:21:17 [] (unknown:0) - Fail to instantiate module  "DeepInfer"
[CRITICAL][Qt] 25.09.2021 02:21:17 [] (unknown:0) - The following modules failed to be instantiated:
[CRITICAL][Qt] 25.09.2021 02:21:17 [] (unknown:0) -    DeepInfer
[DEBUG][Python] 25.09.2021 02:21:18 [Python] (C:\Users\ignac\AppData\Local\NA-MIC\Slicer 4.11.20210226\lib\Slicer-4.11\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: Annotations
[DEBUG][Python] 25.09.2021 02:21:20 [Python] (C:\Users\ignac\AppData\Local\NA-MIC\Slicer 4.11.20210226\lib\Slicer-4.11\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentEditor
[DEBUG][Python] 25.09.2021 02:21:20 [Python] (C:\Users\ignac\AppData\Local\NA-MIC\Slicer 4.11.20210226\lib\Slicer-4.11\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentStatistics
[DEBUG][Qt] 25.09.2021 02:21:20 [] (unknown:0) - Switch to module:  "Welcome"
[DEBUG][Qt] 25.09.2021 02:21:41 [] (unknown:0) - Switch to module:  ""

**Comment by lassoan** [comment]
Please test with the latest Slicer Preview Release, too.

Can you share a sample data set that reproduces this issue?

**Comment by ignaciordc** [comment]
Andras:

Thanks for asking. Fedorov gave me a hint to solve it: some of the images had been generated with different number of Rows/Columns.
So, all is good.

Thanks,
   Ignacio

**Comment by lassoan** [comment]
Thanks for the update, I'm closing this issue then.
