### ISSUE TITLE
Extension updates not found in stable version

### ISSUE THREAD

**Issue by muratmaga** [Slicer/Slicer#5908]
As described in https://discourse.slicer.org/t/cant-update-extensions-on-the-current-stable/19901

extension manager in the current stable does not find/install any updates for install extensions. If a new stable based on the new infrastructure will be out soon, then it is not very concerning. But it still needs to be checked.

**Comment by sjh26** [comment]
@jcfr will this be an issue with the upcoming Slicer 5 stable?

**Comment by jamesobutler** [comment]
@muratmaga You should take another look at this issue with the newly cut Slicer 5.0 stable release.
