### ISSUE TITLE
Markups: Fix varying coloring of markups ROI nodes

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5912]
It is inconsistent that ROIs have all the same color if created one by one but have different colors if "Place multiple control points" is enabled.

Also, vtkMRMLColorTableNodeRandom color table is not designed for creating nice, distinguishable colors. Instead, use MediumChartColors, DarkBrightChartColors, LightPaleChartColors. Make the color index start at 0 (not at 3) and wrap around if the color index reaches the number of values in the color table. Remove UpdateCurrentColorTableIndex (fuse it into GetNewMarkupsColor). Make GetNewMarkupsColor return a double* (you need to add a `double LastReturnedMarkupsColor[3];` in the class to store the vector that is returned) and add `VTK_SIZEHINT(3)` to make the method conveniently usable from Python.

## Environment
- Slicer version: Slicer-4.11.0-2021-09-27
- Operating system: Windows

@smrolfe

**Comment by lassoan** [comment]
@smrolfe what do you think?

**Comment by smrolfe** [comment]
Thanks! I missed this. I will be able to look at it early next week.

**Comment by smrolfe** [comment]
@lassoan This issue is addressed in the commit: https://github.com/smrolfe/Slicer/commit/55f9f5f23ceb091349d277b9ef97ed25e9475caa

**Comment by smrolfe** [comment]
@lassoan @jamesobutler Checking in on the status of this commit, thanks!

**Comment by jamesobutler** [comment]
@lassoan Are there additional things needed here for this issue? Or has https://github.com/Slicer/Slicer/commit/c8daef472497776cb9db67487c2664c384407d31 closed this issue?

**Comment by lassoan** [comment]
Good catch. Yes, this can be closed now.
