### ISSUE TITLE
Markups: Lots of "child widget is not accessible" warnings when selecting a control point in the table

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5913]
When Slicer is built in debug mode, lots of "child widget is not accessible warnings" when selecting a control point in the table or adding new points while the control points table is visible.

## Environment
- Slicer version: Slicer-4.11.0-2021-09-27
- Operating system: Windows

@smrolfe

**Comment by jamesobutler** [comment]
@lassoan I'm unable to replicate this using Slicer-4.11.0-2021-09-27 (downloaded from https://slicer.cdash.org/viewFiles.php?buildid=2415461). I did the following:
- Launch Slicer
- Go to Markups module
- Press the create fiducial button in the markups module and place an initial point
- Expand the control points table
- Place more control points
- File->Report a bug to view the log

Can you see only see these warnings with a debug build of Slicer? What is the source of the warning?

**Comment by lassoan** [comment]
Yes, sorry, it is only in debug mode.

**Comment by jamesobutler** [comment]
I wonder if this will be fixed by @jcfr ’s PR #6015.

**Comment by lassoan** [comment]
Unfortunately, it is not likely that the deprecation warnings will fix this. There seems to be an actual issue with how items are selected. I also see huge slowdowns of the control point table when having just a few hundred points in it.

So, the control point table must be thoroughly reworked. It also has to be factored out from the module widget to become a standalone, reusable widget (maybe just move all the features into qMRMLMarkupsControlPointListWidget; maybe convert it to a model-view design).
