### ISSUE TITLE
Markups: Mouse mode is no longer reflected by mouse cursor shape

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5915]
Anyone else noticing that the WindowLevel mouse mode cursor icon is no longer present while in that mouse mode? I can adjust window level while in the mode, but the correct cursor icon is missing.

A potentially related issue that also must be fixed is the failing toolbar test: qSlicerMouseModeToolBarTest1.

## Environment
- Slicer version: Slicer-4.11.0-2021-09-27
- Operating system: Windows

@smrolfe

**Comment by smrolfe** [comment]
Thanks, I'm working on this issue now.

**Comment by jamesobutler** [comment]
Closed by dd8d8a5650af40601cd85091f23c3f66b86b8ccc.
