### ISSUE TITLE
Markups: Documentation of Markups module has not been updated to reflect latest changes

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5916]
Markups module documentation (https://slicer.readthedocs.io/en/latest/user_guide/modules/markups.html#) needs an update after the recent improvements.

When everything is settled then a Slicer forum post must be submitted in the "Support" category with the "feature" tag attached that describes the new features strictly from a user standpoint. No implementation details, only description of new features and changes. Need to add screenshots and embed YouTube videos in the page.

## Environment
- Slicer version: Slicer-4.11.0-2021-09-27
- Operating system: Windows

@smrolfe

**Comment by jamesobutler** [comment]
Appears that there are several screenshots to update here as it relates to the new Markups toolbar that will be needed prior to stable release.

**Comment by jamesobutler** [comment]
@lassoan Do we need to add this to the 4.13 milestone so the documentation matches the new Slicer 5.0 release? I remembered about this issue when linking to it in https://discourse.slicer.org/t/draw-specific-dimension/22934/3?u=jamesobutler.
