### ISSUE TITLE
Markups: Custom markups do not appear in the markups toolbar

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5918]
Custom markups registered externally do not appear in the toolbar. They did appear before in the dropdown.

## Environment
- Slicer version: Slicer-4.11.0-2021-09-27
- Operating system: Windows

@smrolfe

**Comment by smrolfe** [comment]
Is there documentation creating a custom markup? Or an existing one I can import for testing?

**Comment by cpinter** [comment]
Hi @smrolfe , thanks for the follow-up! I created an extension with a single custom markup: https://github.com/cpinter/SlicerGridSurface

It's very experimental so please don't mind the issues, however, it registers a custom markup that shows up in the Markups module and in the old toolbar as well, but not the new one.

**Comment by lassoan** [comment]
There is also a module in Slicer core (Utilities\Templates\Modules\LoadableCustomMarkups) and a test of dynamically registering/unregistering new markup types at runtime (PluggableMarkupsSelfTest.py).
