### ISSUE TITLE
 Why clone a line node without display properties?

### ISSUE THREAD

**Issue by shunxinyi2021** [Slicer/Slicer#5926]
slicer 4.13
我画了一条直线如图, 并且设置了显示属性加粗和颜色…

> I drew a straight line as shown in the figure, and set the display attributes bold and color…

[![image](https://aws1.discourse-cdn.com/standard17/uploads/slicer/optimized/2X/9/9198492ddc2e91035f65a6a7ce48d3d361a0da6d_2_582x500.png)

image1726×1482 126 KB

](https://aws1.discourse-cdn.com/standard17/uploads/slicer/original/2X/9/9198492ddc2e91035f65a6a7ce48d3d361a0da6d.png "image")

and then clone it… get this result

[![image](https://aws1.discourse-cdn.com/standard17/uploads/slicer/optimized/2X/b/bb0b3618687299afce7937abc13b50ac8ea4641a_2_690x407.png)

image2152×1270 164 KB

](https://aws1.discourse-cdn.com/standard17/uploads/slicer/original/2X/b/bb0b3618687299afce7937abc13b50ac8ea4641a.png "image")

Why clone a line node without display properties?

**Comment by jamesobutler** [comment]
Originally mentioned at https://discourse.slicer.org/t/why-clone-a-line-node-without-display-properties/19922/3

From @lassoan 

> I guess the cloned node is using default markups properties, which make sense, but probably copying display properties would be a more desirable behavior.
