### ISSUE TITLE
Slicer crashes on deleting segmentation node with initialized/unapplied Fill between slices

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#5929]
Slicer will crash and exit when deleting a segmentation node that has an initialized/unapplied Fill between slice effect preview.

## Steps to reproduce

1. Use the "Draw" effect to apply regions at different slice offsets.
2. Switch to the "Fill between slices" effect and initialize the preview
3. Delete the Segmentation node and observe that Slicer crashes and exits.

![image](https://user-images.githubusercontent.com/15837524/135896311-6bf66ba1-e053-4642-9f41-748d9d2d4178.png)

## Expected behavior

Upon deleting the segmentation node where there is an initialize preview for fill between slices, that the preview disappears and the segmentation node is deleted without Slicer crashing.

## Environment
- Slicer version: Slicer-4.13.0-2021-10-03
- Operating system: Windows 10

**Comment by lassoan** [comment]
Thanks for reporting, fixed.
