### ISSUE TITLE
Intersection point moves when rotating with Ctrl+Alt+Drag

### ISSUE THREAD

**Issue by gaoyi** [Slicer/Slicer#5936]
[Give a short summary of what the problem is]

## Steps to reproduce

The same question has been asked on the Forum where I put a video showing the situation:

https://discourse.slicer.org/t/rotation-center-moves-in-ctrl-alt-drag/19986

Copied from there:

I’m trying to use the Ctrl+Alt+Drag to rotate the volume interactively. However the Center seems moving with rotation.

But this only seems happen when I have a customized layout (shown in the video). This moving-center does not happen in standard layout such as the Four-Up and others.

Andras pointed out there that the problem is that the near-parallel planes indeed intersect, and a checking of close-to-parallelism is needed.

It is therefore added in the pull request.

## Expected behavior

The rotation center should not move with rotating, just as the situation in the standard layout such as the Four-Up and others.

## Environment
I'm tested on the system (version) below but I believe the problem is cross platform.
- Slicer version: Slicer-4.11.20210226
- Operating system:  Linux Mint 19.3

**Comment by jamesobutler** [comment]
@lassoan since you merged #5937, this issue can be closed now?

**Comment by lassoan** [comment]
Yes, good catch, it is fixed now.
