### ISSUE TITLE
Slicer-4.13 hangs at startup on Windows11

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5945]
Slicer does not start up (hangs, then the operating system terminates it) on Windows11

See discussion here:
https://discourse.slicer.org/t/slicer-on-windows-11/20085/11

## Environment
- Slicer version: Slicer 4.13.0-2021-10-08
- Operating system: Windows 11 Pro, Version: 21H2, OS build: 22000.194

**Comment by jamesobutler** [comment]
I'm glad that the libopenblas information was a helpful hint. Thanks for tracking down a workaround! I'll keep an eye on Windows 11 compatibility issues and if this workaround becomes no longer needed.
