### ISSUE TITLE
Make volume presets more accessible 

### ISSUE THREAD

**Issue by rbumm** [Slicer/Slicer#5951]
## Is your feature request related to a problem? Please describe.

Volume presets are a very useful feature but are a little hard to find in the "Volumes" module.  

## Describe the solution you'd like

It would be helpful to have all available presets in the right-click menu of each of the slice windows. 

## Describe alternatives you've considered

They could also be placed in the windows/level mouse selector, but the right-click menu location seems even better. 

## Additional context

[Add any other context or screenshots about the feature request here.]

**Comment by lassoan** [comment]
Fixed in https://github.com/Slicer/Slicer/pull/5964
