### ISSUE TITLE
Segmentation Sequences Can't handle segment being deleted

### ISSUE THREAD

**Issue by nathanbmnt** [Slicer/Slicer#5953]
## Steps to reproduce

1. Load a sequence volume
2. Create a segmentation on the first frame of the volume with one segment
3. Go to the sequences module, create a new sequence and set the segmentation as its proxy node, check save changes
![image](https://user-images.githubusercontent.com/40271210/137944266-d9b8461e-3366-4d6c-9242-b9880f2bd914.png)
4. change to the second frame and edit the segment there
![image](https://user-images.githubusercontent.com/40271210/137944842-c2903a70-eb8f-4ebf-b967-a98ec51c32cb.png)
5. delete the segment, the segment is removed from the segments table as expected. 
![image](https://user-images.githubusercontent.com/40271210/137945336-89dbe3e0-0de4-4d56-857c-2cac203d774b.png)
But if you scroll to the first frame the segment is still not in the segments table even though it shows up in the sliceviews
![image](https://user-images.githubusercontent.com/40271210/137945385-cedd0ae3-b2c4-48cf-8ca5-96d789098aed.png)
6. Click Add in the segmentation module, no segment is created, this shows up in console:
`class QStandardItem *__cdecl qMRMLSegmentsModelPrivate::insertSegment(class QString,int) : Item mismatch when inserting segment item with ID  "Segment_2"`

## Expected behavior

The segment table updates to show the segment on frames which have the segment, and no segment on frames without the segment.

## Environment
- Slicer version: Slicer-4.13.0-2021-09-14
- Operating system: Windows 10

**Comment by lassoan** [comment]
I was able to reproduce this. The segment list widget gets into some kind of invalid state and it does not display segments anymore.

@Sunderlandkyl could you have a look at this?
