### ISSUE TITLE
Slicer crashes when loading .mhd file

### ISSUE THREAD

**Issue by Nicolaas94** [Slicer/Slicer#5955]
Slicer crashes after loading any .mhd file

## Steps to reproduce

I opened Slicer and dragged a .mhd file into the Slicer window. The window "add data into the scene" popped up and I loaded the data file as a volume. Clicked "OK" and Slicer shuts itself down. 

## Expected behavior

I expected that Slicer loaded the .mhd ultrasound volume like it always did before or like any other volume. 

## Environment
- Slicer version: Slicer-4.11.20210226
- Operating system: Windows 10 64-bit system

[Slicer_bug.txt](https://github.com/Slicer/Slicer/files/7381755/Slicer_bug.txt)

What to do?

**Comment by lassoan** [comment]
Thank you, please provide the corresponding .raw file, too.

**Comment by jamesobutler** [comment]
The locations described such as on the Desktop or where SampleData would use a path with your username.

When the file is located on the desktop can you provide the full filepath of its location? Are there special characters anywhere such as your username?

Is your OS in a different language other than English?
