### ISSUE TITLE
Extension page is empty if EXTENSION_SCREENSHOTURLS is empty in CMakeLists.txt

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5973]
A number of extension pages rendered as empty:

https://extensions.slicer.org/view/RegistrationQA/30338/win
https://extensions.slicer.org/view/Sandbox/30338/win
https://extensions.slicer.org/view/ShapeRegressionExtension/30338/win
https://extensions.slicer.org/view/SlicerDevelopmentToolbox/30338/win
https://extensions.slicer.org/view/SlicerOpenCV/30338/win

It seems those and only those extensions are impacted that have EXTENSION_SCREENSHOTURLS in their CMakeLists.txt file:

https://github.com/gsi-biomotion/SlicerRegistrationQA/blob/master/CMakeLists.txt
https://github.com/PerkLab/SlicerSandbox/blob/master/CMakeLists.txt
https://github.com/jcfr/ShapeRegressionExtension/blob/master/CMakeLists.txt
https://github.com/QIICR/SlicerDevelopmentToolbox/blob/master/CMakeLists.txt
https://github.com/Slicer/SlicerOpenCV/blob/master/CMakeLists.txt

See related discussion here: https://discourse.slicer.org/t/sandbox-extension-needed-for-mandible-reconstruction-extension-and-it-is-not-available/20413/2

**Comment by jcfr** [comment]
This is confirmed by inspecting the console:

![image](https://user-images.githubusercontent.com/219043/197086827-b05ed68b-c3b8-4903-b9a4-9b5f2bac3fb0.png)

**Comment by jcfr** [comment]
Related issue is https://github.com/KitwareMedical/slicer-extensions-webapp/issues/74

**Comment by jcfr** [comment]
The extensions frontend has been improved to properly handle these cases:
* missing `screenshots` metatdata
* `screenshots` metatdata set an empty string

URLs listed above (https://github.com/Slicer/Slicer/issues/5973#issue-1039702544) now all render a non-blank page.
