### ISSUE TITLE
How can I retrieve data from the server and process it locally？

### ISSUE THREAD

**Issue by LuPingChina** [Slicer/Slicer#5979]
In DICOM module, the query and retrieve function can be used to query the data on the server, but after clicking the retrieve button, the data cannot be added to the database. What's the problem? How can I retrieve data from the server and process it locally.

Retrieve button prompt:

```
MOVE request failed, server does report error
MOVE request failed: Status Detail:

# Dicom-Data-Set
# Used TransferSyntax: Little Endian Implicit
(0000,0902) LO [Unknown move destination "SERVERAENEW", failing C-MOVE-RQ from C] # 64, 1 ErrorComment
```

**Comment by lassoan** [comment]
This is most probably a DICOM network configuration issue. Please check if any of the [discussions of this topic on the Slicer forum](https://discourse.slicer.org/search?q=dicom%20query%20retrieve) helps and if you still have problems then describe everything that you have tried and the results you got. You may also try query/retrieve using the more modern DICOMweb protocol, by using the DICOMweb extension.

**Comment by LuPingChina** [comment]
Thankyou very much again.
