### ISSUE TITLE
BUG:  deleting grow-from-seeds preview volume prevents initialisation from being cancelled

### ISSUE THREAD

**Issue by DIV-on-github** [Slicer/Slicer#5988]
Deleting a grow-from-seeds preview volume in the Data module prevents the grow-from-seeds initialisation from being cancelled in the Segment Editor module.  

## Steps to reproduce

As per 
https://discourse.slicer.org/t/segment-editor-unable-to-restart-grow-from-seeds-effect-from-scratch-if-volume-deleted/20449
1    (a) Paint seeds in many segments. (b) Toggle visibility of some relevant segments off.
2   Set up Grow from Seeds effect by clicking Initialize. This produces ‘wrong’ results in the preview Volume.
3       (a) Delete the preview Volume in the Subject heirarchy tab of the Data module. (b) The Cancel button in the Grow from Seeds effect’s panel is disabled.
4    Toggle visibility of all relevant segments on.
5        Set up Grow from Seeds effect anew by clicking Initialize again. This produces the same (‘wrong’) results as before, because Cancel was not clicked.

## Expected behavior

Either deleting the preview volume should be equivalent to clicking `Cancel`, or the `Cancel` button should still be clickable.  

## Environment
- Slicer version: Slicer-4.11.20210226
- Operating system: Windows 10 x64

## Suggested fix

Two alternatives
*    Deleting the preview volume automatically invokes all of the actions that would have been invoked by clicking Cancel. The Cancel button becomes disabled/inactive upon completion. (Preferred)
*   Deleting the preview volume does not have any further consequences. The Cancel button remains enabled/active upon completion. (Less preferred)

**Comment by lassoan** [comment]
This is already fixed in recent Slicer Preview Releases. Please test.
