### ISSUE TITLE
Simplify Markups API with clear deprecations of old methods

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#5990]
Consider the following where there are 3 different methods that do the same thing, but have different names without any deprecations about which is the preferred one to use and which ones are scheduled to be removed.

There appears to be carry over from "Annotations" module days which had "Fiducial" and that was ported to the "Markups" module for compatibility. Then a new version called "Markup" was used to refer to the individual points in the node and then that was changed to "Control Point". 
```python
markups_node = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsFiducialNode")
markups_node.AddFiducial(0,0,0)
# All 3 below do the exact same thing which is to lock the first index control point in the markups node
markups_node.SetNthFiducialLocked(0, True)
markups_node.SetNthMarkupLocked(0, True)
markups_node.SetNthControlPointLocked(0, True)
```

All these versions make it difficult for new developers to know which version should be used. Maintaining compatibility has started to become detrimental to the ease of use of the Markups API and deprecations should begin to be enforced so they can be removed.

**Comment by jamesobutler** [comment]
@lassoan Can you help with the plan of how to proceed here?

**Comment by jcfr** [comment]
> re: SetNthFiducialLocked

Based on [this search](https://github.com/search?p=3&q=SetNthFiducialLocked&type=Code), it used only here

https://github.com/SlicerMorph/SlicerMorph/blob/07e63af8145d07a62182a75bbc3050076f1fc01c/PseudoLMGenerator/PseudoLMGenerator.py#L274-L275

The other results corresponds to Slicer forks

**Comment by jcfr** [comment]
> re: SetNthMarkupLocked

Based on [this search](https://github.com/search?q=SetNthMarkupLocked&type=Code), it is used at least in `SlicerRT` and `QIICR/PETTumorSegmentation`

**Comment by jcfr** [comment]
> re: SetNthControlPointLocked

Based on [this search](https://github.com/search?q=SetNthControlPointLocked&type=Code), it is used in:

* https://github.com/SlicerMorph/SlicerMorph/blob/1e10653243971667ecde9750b730189e4b9aba91/MorphPreferences/Resources/SlicerMorphRC.py

* https://github.com/Mazze/CartoInterpolation/blob/3d6360c8752570cb8604dbdcaaed9b2a319d1c13/convert.py

* https://github.com/stephan1312/SlicerEAMapReader/blob/5b33a3a8410be37b0440ce5ea3f07bfe73f60121/EAMapReader-Slicer-4.11/lib/Slicer-4.11/qt-scripted-modules/EAMapReader.py

* https://github.com/SlicerHeart/SlicerHeart/blob/a9b348584666e78d0aff40eb3e25833d48204bdc/ValveClipDeviceSimulator/ValveClipDevices/devices.py
 
* https://github.com/mikebind/slicer-airway-landmarks/blob/bbbaa198451ca56808fcacd1f0f05b2c5f720184/AirwayLandmarks.py

 
* https://github.com/SNRLab/BronchusDifficultyIndex/blob/bce9d138a221a95c83cc2e23778d72a37a75bef8/CenterlineSlider.py

* https://github.com/SNRLab/BronchusDifficultyIndex/blob/1b600a9fda4cc6ee336d35c80e0d3eadafe79310/ModifiedCenterlineComputation.py

* https://github.com/SlicerMorph/SlicerMorph/blob/67c622c4ab15f0a1dee2bb00dffde8dbcd5a91be/FormatMarkups/FormatMarkups.py


The other results corresponds to Slicer forks

**Comment by lassoan** [comment]
We don't see all the private projects that may use the old APIs, so I would recommend to focus on the API that we want to have. The API should be consistent in naming, behavior, and types, and it is safe and fast in C++ and convenient in Python (e.g., return a vector instead of requiring and input vector that the method updates) with no redundancy.

Deprecation is a long process if we don't want to update the users. It could be something like add to documentation of deprecated methods that they are deprecated; in 6 months log a warning if they are used, in 1-2 years remove them completely.
