### ISSUE TITLE
Cancelling "Create new (node) as ..." dialog should not create new object

### ISSUE THREAD

**Issue by DIV-on-github** [Slicer/Slicer#6002]
Cancelling "Create new _X_ as ..." dialogue creates new object with the default name (as if from "Create new _X_"), but clicking `Cancel` should not produce any object.  
I think this happens in several modules, with different types of object, including `Table` and `Volume`.  

## Steps to reproduce

Invoke "Create new Table as ..." dialogue, such as for the _Output table_ of the **Segment Statistics** module.
Click `Cancel`.
This creates a new Table object with a default name.  

## Expected behaviour

Should not create any new object.  

## Environment
- Slicer version: Slicer-4.11.20210226
- Operating system: Windows 10 x64

**Comment by DIV-on-github** [comment]
Actually the dialogue is a "Rename" dialogue.  
Apparently what is happening when choosing the "Create new _X_ as ..." menu item is that Slicer first creates the object (with the default name) and then invokes the _Rename_ dialogue.

**Comment by lassoan** [comment]
I agree that it would be nicer if the node would not be created until the user specifies a name and clicks OK.

"Create new X as..." indeed creates a new node and offers the user to rename it:

https://github.com/Slicer/Slicer/blob/f46c47486bf081edff6ad246e2ca4e9265f40416/Libs/MRML/Widgets/qMRMLNodeComboBox.cxx#L437-L438

I agree with labels added by @pieper that it is an easy fix (display an input popup with a proposed name before adding the new node) for a little improvement, so this is very well suited as a development task for a new contributor.

**Comment by sedrakSofthenge** [comment]
Hi there,
I am trying to contribute to the project, and wanted to pick this item, since it's labeled as "good first issue", but I am completely new to this project, especially from user perspective, can't figure out how to perform "create new (node) as" action, can you please give more details?
Regards.

**Comment by pieper** [comment]
> how to perform "create new (node) as" action

@sedrakSofthenge most modules use the same combo box to select node types, and these have the "Create new..." option.  You can just try any of those and when the dialog box to change the name comes up you can cancel and see that the new node with the default name is still in the scene.

<img width="401" alt="image" src="https://github.com/Slicer/Slicer/assets/126077/88e3cb66-99b4-4d40-84c2-13949cd8b860">
