### ISSUE TITLE
Issue with startup

### ISSUE THREAD

**Issue by asammarc** [Slicer/Slicer#6005]
When I updated to the most recent stable version of slicer, when I open it it looks like this:
![image](https://user-images.githubusercontent.com/93960419/140852873-7a05dca6-cf1f-48ba-a59f-519b5d99a883.png)
I have tried uninstalling and reinstalling several times, with no success.

## Steps to reproduce

When I click the slicer icon to open the program, this is how it looks.

## Expected behavior

I would expect it to look normal

## Environment
- Slicer version: Slicer-4.11-2021-02-26
- Operating system: Windows 10.0.19043

**Comment by lassoan** [comment]
This is caused by a faulty Intel Graphics driver version (see https://discourse.slicer.org/t/slicer-opening-screen-error-green-stripes/12543). Upgrading or downgrading to a different version fixes the issue.
