### ISSUE TITLE
Delete Slicer4 CDash project

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#6063]
> Then Slicer4 can be kept around for some time for debugging when certain things maybe began to fail, and then after awhile when we don't need to look back at the old results, then remove the Slicer4 project.

See https://github.com/Slicer/Slicer/issues/4644

**Comment by jamesobutler** [comment]
It has been over 4 months since the rename to using SlicerStable so the Slicer4 project can be deleted now. https://slicer.cdash.org/index.php?project=Slicer4

![54E117C6-9735-4941-BE51-FFCACF907501](https://user-images.githubusercontent.com/15837524/166150917-8cbe34cc-3e0b-490a-9017-c4ecc29d643a.jpeg)

**Comment by jcfr** [comment]
Deleting the project makes sense, I just sent an email to Kitware sysadmins.

## History

The `Slicer4` project was created in Sept 2010 [^1] and was used until Feb 2018 to organize both Stable and Nightly (now called Preview) submissions. 

Then from Feb 2018 to April 2022, the `Slicer4` project was used to organize the extensions build associated with the stable release [^2].

Between 2010 and 2022, 254367 builds have been submitted to `Slicer4` project.

Starting with Slicer 5.0, the `Slicer4` project is defunct and a new project called `SlicerStable` is used [^3].

[^1]: https://github.com/Slicer/Slicer/commit/cfb3499485486eeecd407aa9b6c7c7c3eb49962f
[^2]: https://github.com/Slicer/Slicer/commit/19180ec0db26ff1b246765e686d5890b1af9b527
[^3]: https://github.com/Slicer/Slicer/commit/62e4d8544f2a6f30b707a87288a5e1b9fc5a5a86

**Comment by jcfr** [comment]
Et voila, the project has been removed.

![image](https://user-images.githubusercontent.com/219043/166410598-4c0f55ba-84c5-444b-832b-718fe507fdec.png)

**Comment by jcfr** [comment]
Removal of the project and associated history have been documented in the following discourse post:
https://discourse.slicer.org/t/update-related-to-available-cdash-projects/23252
