### ISSUE TITLE
how to solve the problem of Model To Model Distance that terminates with faliure?

### ISSUE THREAD

**Issue by maxfaxsurgeon** [Slicer/Slicer#6069]
[Hi all dear colleagues, I want to ask regarding a technical issue of 3D Slicer: 

I am doing a research in regard to stability studying of fixation tools in maxillofacial skeleton by  doing  superimposition of  T1 (immediate postop) and T2 (6 months postop) using Dolphin software and then using 3D Slicer to do measurements of any displacement:

I had two problems:
1. when I do processing the two models (.stl format) in 3D Slicer using:
Pick'n paint function: work properly.
Model To Model distance: suddenly terminates with failure? although previously it was working with no problems; so what could be the problem and how to solve it? I initially used 3D Slicer 4.11.0, then downloaded 4.13.0 Last release and the problem is still exist.

The 2nd question is :
after doing superimposition by Dolphin software and saving the T1 and T2 as registered models in .stl format, then using these models to be opened by 3D Slicer: but when I open them in the last  slicer release software they were not superimposed as done by dolphin, what could be the reason and how to solve this problem? is there any way to check the superimposition of the two models in Dolphin after saving the models in the PC?

I hope I have explained the problems clearly and please any one is familiar with both or any one of the mentioned software could contact me, highly appreciated your support and help. 

Email: mohqasalwatary@gmail.com

WhatsApp: 008619160360903.]

## Steps to reproduce

[describe what you did and what happened - attach screenshots if possible]

## Expected behavior

[describe what you expected to happen]

## Environment
- Slicer version: Slicer-4.13.0-2021-12-03, also 4.11.0-2021-02-26
- Operating system: Windows  + which version
- 
![image](https://user-images.githubusercontent.com/95540324/144718545-bb0235fd-db5c-44c6-85e9-8f0469a3e185.png)
![image](https://user-images.githubusercontent.com/95540324/144718559-d17397ba-ccc3-40b8-82b1-fd0ea46c764c.png)

**Comment by pieper** [comment]
For now this is being [discussed on discourse](https://discourse.slicer.org/t/modeltomodel-distance-module-is-not-working-properly/20907/9).  If there's a specific bug in the core either reopen this or start new issues with one topic per github issue to facilitate tracking.
