### ISSUE TITLE
Support exporting multiple nodes in one batch

### ISSUE THREAD

**Issue by ebrahimebrahim** [Slicer/Slicer#6074]
We should be able to export multiple nodes with a couple of clicks in the Data module.

This issue can be assigned to me.

## Describe the solution you'd like

- A variation of the "Export to file..." context menu item should be available when right clicking on a folder. This could export all nodes nested under the folder, if they have the same type.
- Perhaps also: right clicking after selecting multiple nodes should also offer the option to export them all, assuming they are of the same type.

In both cases, it should lead to the export dialog, which should be given some reasonable way of deciding how to name the nodes.

## Additional context

- [earlier PR for exporting individual nodes](https://github.com/Slicer/Slicer/pull/5876)
- useful earlier commit message: 3fcc1ebd13a150af335eb8d3918435c66668e2e6
- [announcement introducing export functionality](https://discourse.slicer.org/t/new-export-functionality/20950)

## Questions

1. How should filename be decided when multiple nodes are involved? Some ideas:
  a. Gray out the filename text entry box in the export dialog, and force reasonable default names. Maybe just use the node's name, and perhaps preferring the filename in the associated storage node if it exists.
  b. Use the filename text entry box in the export dialog to allow a choice of "base name" that could be prepended or appended to the names of the exported nodes.
2. How should we handle the case where nodes have different types? Some ideas:
  a. Don't provide export option in the context menu in this case.
  b. Provide option, but raise an error telling user to select nodes having all the same type.
  c. Let the majority node type win, only exporting nodes of that type.
  d. Raise a warning that this is what will be done.
  e. Raise a dialog that allows the user to specify which node type they want to export.
  f. Tweak the export dialog to somehow be able to handle nodes of different types.
3. In the case of exporting a folder, should the entire hierarchy be traversed? Or only the direct children of the folder?

**Comment by lassoan** [comment]
> How should filename be decided when multiple nodes are involved?

Option (a) sounds good to me. You would replace the filename selector by a folder selector.
Also add an option to recreate the subject hierarchy folder structure as file folder structure (it can prevent name clashes).

> How should we handle the case where nodes have different types?

I feel all the options unnecessarily inconvenient for the user. This feature is so useful and powerful that it would be a pity if having some extra node in a folder would interfere with the export.

Could we show for each node class: node type (label), file extension (combobox), options (custom widget)?

> In the case of exporting a folder, should the entire hierarchy be traversed? Or only the direct children of the folder?

Both could be necessary, so we would need to add a checkbox for it (enabled by default).

Note that we may have multiple selection, so a recursive search is not completely trivial. See how it is implemented in qMRMLSubjectHierarchyTreeView::toggleVisibilityOfSelectedItems and qSlicerSubjectHierarchyPluginHandler::showItemsInView. To avoid code duplication, create a utility method somewhere that can be used from the export dialog and elsewhere.

**Comment by ebrahimebrahim** [comment]
> > In the case of exporting a folder, should the entire hierarchy be traversed? Or only the direct children of the folder?
> 
> Both could be necessary, so we would need to add a checkbox for it (enabled by default).

Follow up question: if the entire hierarchy is traversed for export, then do we want to recreate the hierarchy as a directory structure on the device? Or do we flatten the hierarchy, exporting each file to the target directory? Or have a checkbox to toggle between the two behaviors?

@smrolfe @muratmaga would be good to also hear from the SlicerMorph folks about this, since they have experience with users of this functionality

**Comment by ebrahimebrahim** [comment]
> so we would need to add a checkbox for it (enabled by default).

@lassoan Where in the application should such a checkbox go?

**Comment by ebrahimebrahim** [comment]
> Note that we may have multiple selection, so a recursive search is not completely trivial. See how it is implemented in `qMRMLSubjectHierarchyTreeView::toggleVisibilityOfSelectedItems` and `qSlicerSubjectHierarchyPluginHandler::showItemsInView`. To avoid code duplication, create a utility method somewhere that can be used from the export dialog and elsewhere.

@lassoan Looking over handling of multiple selection in these implementations, it is looking like I have to exit the "plugin" framework to be able to work with multiple selection. Is this correct? Should I give up the plugin framework and populate the export context menu action within `qMRMLSubjectHierarchyTreeView` directly like it does for "toggle visibility" and "delete"?

I don't see a way around it, unless there is some way to access `qMRMLSubjectHierarchyTreeViewPrivate`'s `SelectedItems` ([this](https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx#L136)) from within a subject hierarchy plugin.

**Comment by muratmaga** [comment]
> @smrolfe @muratmaga would be good to also hear from the SlicerMorph folks about this, since they have experience with users of this functionality

We only used a single level of hierarchy, nothing more complicated than that. It is something like one folder level for models, one for volumes, one for labelmaps etc...

**Comment by lassoan** [comment]
Good point. For supporting multi-selection for context menu, we would need some infrastructure development (to be able to pass a list of IDs to subject hierarchy plugins in `qSlicerSubjectHierarchyRegisterPlugin::showContextMenuActionsForItem(vtkIdType itemID)`. Since this would be substantial work, and probably not used as often (because selecting multiple nodes in a tree is somewhat tedious), it would be enough to allow export of folders (all children in the folder, recursively).

> > so we would need to add a checkbox for it (enabled by default).
> 
> @lassoan Where in the application should such a checkbox go?

It could be in the "Export data" popup, which is displayed when the user right-clicks on a folder and clicks on "Export to files...".

**Comment by ebrahimebrahim** [comment]
@jcfr @lassoan This can be moved back to the Slicer 4.13.0 milestone. I think I'll have it ready very soon.

**Comment by lassoan** [comment]
Sounds great! Looking forward to the pull request.
