### ISSUE TITLE
Allow us to enter a path to place all files.

### ISSUE THREAD

**Issue by bhs67** [Slicer/Slicer#6079]
The Pursa Slicer Printer Setting files should be placed in the location of our choosing.  This can be accomplished by allowing us to enter a path to all of our unique files.

All of my unique files are on the D: drive (Excel files, Word files, Visual Studio code files, etc).  

I periodically backup all of my unique files.  If the C: drive crashed, or if the laptop is stolen, it would be easy to retrieve all of my unique files via the backup.

Currently, the Printer Setting files (filename.ini) are saved on C:\Users\...\AppData\Roaming\PrusaSlicer\print.  

The Printer Setting files should be saved in an area that is easy for us to backup.  Allowing us to enter the path to place these files would be very helpful.

**Comment by lassoan** [comment]
This is the bugtracker of www.slicer.org medical image analysis software.

**Comment by bhs67** [comment]
Where should I place this request?

**Comment by jamesobutler** [comment]
Hi @bhs67 unfortunately you have posted to the wrong repository. You are looking for https://github.com/prusa3d/PrusaSlicer. This is a repo for https://www.slicer.org/.

**Comment by bhs67** [comment]
Sorry.  I was referred to this site by Prusa Support.  Thanks for the prompt responses!
