### ISSUE TITLE
Transformed Volumes Not Showing when Rendered with VTK GPU Ray Casting

### ISSUE THREAD

**Issue by jmcox9** [Slicer/Slicer#6083]
There is an issue with certain transformable volumes being accounted for in the Transforms module when a particular rendering style is selected for those volumes in the Volume Rendering module.

## Steps to reproduce

After applying a centering transform to an eligible volume in the Volumes module, switching to the Transforms module and selecting “volume name” centering transform does not display “volume name” under the list of Transformed volumes if “volume name” has been rendered with VTK GPU Ray Casting in the Volume Rendering module. This issue occurs with .AIM and SEG.AIM volume formats using the CT-AAA rendering preset. The issue can be easily fixed by switching “volume name” to VTK CPU Ray Casting in the Volume Rendering module.

## Expected behavior

After applying a centering transform to an eligible volume in the Volumes module, switching to the Transforms module and selecting “volume name” centering transform should display “volume name” under the list of Transformed volumes.

## Environment
- Slicer version: Slicer-4.13.0-2021-11-18
- Operating system: Windows

**Comment by lassoan** [comment]
> After applying a centering transform to an eligible volume in the Volumes module, switching to the Transforms module and selecting “volume name” centering transform does not display “volume name” under the list of Transformed volumes

If the volume does not show up in the transformed nodes list then it is a GUI widget bug in the Transforms module. This cannot be related to what volume rendering mode is chosen. Could you submit a separate issue for this, along with instructions to reproduce the issue? (If I load MRHead sample data set, go to Volumes module, click Center, then go to Transforms module then the volume shows up in the Transformed list)

Both CPU and GPU volume rendering can display linearly transformed volumes. I know of only one difference: GPU volume rendering does not render volumes that are turned inside out (a transformation matrix is applied that has negative determinant). CPU volume renderer may be more tolerant for this transformation error, but the GPU volume renderer's behavior is reasonable, too. Could you copy here the values from the transformation matrix that is applied to the volume?

**Comment by lassoan** [comment]
Closing this. The investigation would have required further information from the reporter.
