### ISSUE TITLE
Rename markup node update issue

### ISSUE THREAD

**Issue by dwijmistry11** [Slicer/Slicer#6089]
When we are creating **Point List** Markup it create node with some name. after marking it on a segment when we are renaming node it is not updating name in the views.

## Environment
- Slicer version: Slicer-4.13.0-2021-12-14
- Operating system: Windows 10/  Mac 12.1

**Comment by jamesobutler** [comment]
Are you looking for the "Apply" button in the advanced section of the control points section of the Markups module. If you change the node name and want that to be applied to all the labels you would click that button. Below is images of the UI with that Apply button and also the python example usage of the same thing.

```python
point_list_node = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsFiducialNode")
point_list_node.AddControlPoint([0,0,0])
point_list_node.AddControlPoint([0,0,10])
```
![image](https://user-images.githubusercontent.com/15837524/146981375-8440cd40-d121-41e1-94a1-e6be5e03beb9.png)
```python
point_list_node.SetName("NewNodeName")
```
![image](https://user-images.githubusercontent.com/15837524/146981330-91b0587d-45fc-4445-96c0-787367fcf8f6.png)
```python
slicer.modules.markups.widgetRepresentation().onRenameAllWithCurrentNameFormatPushButtonClicked()
```
![image](https://user-images.githubusercontent.com/15837524/146981349-202b880f-c6dc-4369-9cbe-8ebc5cc8e7e4.png)

**Comment by jamesobutler** [comment]
@dwijmistry11 If you have issues using Slicer and need to ask if something might be a bug or if you're missing an existing functionality you can use the Slicer forum (https://discourse.slicer.org/) for help.

Closing this issue now as it does not appear there is an actual bug that needs addressing here.
