### ISSUE TITLE
Double-left-click to apply draw effect no longer working

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#6103]
Double-left-click to apply points placed using the draw effect is no longer working. Instead it is just maximizing/restoring the slice view.
![image](https://user-images.githubusercontent.com/15837524/148300834-240ad4c8-ba9c-4ff9-966d-7261525af009.png)

Working correctly ✔️ : Slicer-4.13.0-2021-10-19 -> repository revision https://github.com/Slicer/Slicer/commit/11d0ca30162e9fd0315997dd41908354376b52a4 Download factory build from [here](https://slicer-packages.kitware.com/api/v1/file/hashsum/SHA512/7679ae4e286d9b5617fc738668ea13da4ccf175294bc65973781a864a86e6d8240fa154472bb7a80eb9826cc7bf2dac0560f278433bb8442cd3296fcf15d39fa/download)
Not working correctly ❌: Slicer-4.13.0-2021-10-20 -> repository revision https://github.com/Slicer/Slicer/commit/fbe3f9a9c01ad942ff7676d90d61f86781757b1d Download factory build from [here](https://slicer-packages.kitware.com/api/v1/file/hashsum/SHA512/7679ae4e286d9b5617fc738668ea13da4ccf175294bc65973781a864a86e6d8240fa154472bb7a80eb9826cc7bf2dac0560f278433bb8442cd3296fcf15d39fa/download)

Based on the commits committed on October 20th 2021, it is likely that https://github.com/Slicer/Slicer/commit/fbe3f9a9c01ad942ff7676d90d61f86781757b1d, authored by @lassoan, is the commit that introduced this bug.

## Steps to reproduce

1. Open Slicer and load MRHead sample data set
2. Go to Segment Editor module and add a segmentation.
3. Switch to the "Draw" effect and place points.
4. Double left-click to apply and observe that the slice view maximizes instead of applying the segmentation.

## Environment
- Slicer version: Slicer-4.13.0-2021-01-03 latest (https://github.com/Slicer/Slicer/commit/ae608a672b49d3fd11efef89f7a2a425f11e11a3)
- Slicer version: Slicer-4.13.0-2021-10-20 repository revision https://github.com/Slicer/Slicer/commit/fbe3f9a9c01ad942ff7676d90d61f86781757b1d. Download factory build from [here](https://slicer-packages.kitware.com/api/v1/file/hashsum/SHA512/7679ae4e286d9b5617fc738668ea13da4ccf175294bc65973781a864a86e6d8240fa154472bb7a80eb9826cc7bf2dac0560f278433bb8442cd3296fcf15d39fa/download)
- Operating system: Windows 10

**Comment by lassoan** [comment]
@jamesobutler thanks for reporting, fix pushed, please test.

**Comment by jamesobutler** [comment]
Thanks! I have confirmed this fixes the reported issue.
