### ISSUE TITLE
Cannot run other python environment from Slicer Python

### ISSUE THREAD

**Issue by MathieuLeclercq** [Slicer/Slicer#6106]
Hello,
I am developing an extension for Slicer that offers a GUI for runnning 3D  surface segmentation. The GUI and the segmentation algorithm both work fine separately, but I need to call my own python environment in the extension code to start the process automatically. The idea is to execute in a scripted cli module a command with os.system() that runs the segmentation program in the right environment. I was able to make it work on a local environment on my machine, even when both python versions are different. But there are errors when trying to do it from Slicer's Python. At first I had issues because __sysconfingdata__linux_x86_64-linux-gnu.py file was missing. I followed the instructions written on page 394 of [3D Slicer documentation](https://readthedocs.org/projects/slicer/downloads/pdf/latest/), but now the error that I get is "AssertionError: SRE module mismatch".  The ideal solution would be to import all the dependencies directly into Slicer's Python so that I don't need to call another environment. The thing is that I am working on python 3.9 and Slicer Python is 3.6. For now I don't know how to solve that issue.

## Steps to reproduce

All source files for the segmentation algorithm and the Slicer extension are on [this release.](https://github.com/MathieuLeclercq/fly-by-cnn/releases/tag/3.1) 
NB: I am currently developing this extension on 3D Slicer, but the idea is to port it to SlicerSALT.

## Expected behavior

The way the module should work is: after selecting the parameters for the segmentation with the GUI, the segmentation algorithm runs in background. A progress bar shows that the segmentation is running, and when it is over the 3D surface can be opened in 3D Slicer.

## Environment
- Slicer version: Slicer-4.13.0-2021-09-18
- Operating system: Linux CentOS 7
@bpaniagua 
@jcfr

**Comment by lassoan** [comment]
By default if executables are run in Slicer's environment. You can run a process in the system environment (the environment that Slicer has started in) as shown here: https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#launch-external-process-in-startup-environment

To allow more community members to help out and reduce noise in the issue tracker, in the future please ask questions on the [Slicer forum](https://discourse.slicer.org/) and only submit an issue here if it has been already discussed or if you are confident that you have found a bug. Thanks!

**Comment by lassoan** [comment]
If something is not clear, does not work, or if the suggested solution is not ideal (e.g., you may need to add a "wrapper script", which Slicer calls that executes the real script in the system environment and you would want instead a single script that is directly run in the system environment) then write on the Slicer forum. Thank you.
