### ISSUE TITLE
Slicer Failing to Load Ultrasounds on Different Machines 

### ISSUE THREAD

**Issue by li4mm4rtin** [Slicer/Slicer#6116]
I am having trouble opening ultrasounds on a windows machine but have no problems on a Mac. Both machines are running 4.11. When I try to load the file on windows I get the error "error occurred while loading selected files" and the log file that was placed below. Let me know if anyone has any ideas on how to fix this error.

[FailedLoad.log](https://github.com/Slicer/Slicer/files/7891032/FailedLoad.log)

**Comment by pieper** [comment]
The log says things like file not found and bad file format.  So there's something wrong with your data.  Please post to discourse.slicer.org with any specific questions and share the data if you can.
