### ISSUE TITLE
Error when load mrb file for the latest Slicer v4.13.0-2022-01-28

### ISSUE THREAD

**Issue by 1939938853** [Slicer/Slicer#6146]
- Error: Loading D:/data/data.mrb - ERROR: In D:\D\P\Slicer-0\Libs\MRML\Core\vtkMRMLStorableNode.cxx, line 322
vtkMRMLLabelMapVolumeNode (00000269450C7230): vtkMRMLStorableNode::UpdateScene failed: Failed to read node LabelMapVolume (vtkMRMLLabelMapVolumeNode1) using storage node vtkMRMLVolumeArchetypeStorageNode2.

- Error: Loading D:/data/data.mrb - ERROR: In D:\D\P\Slicer-0\Libs\MRML\Core\vtkMRMLStorableNode.cxx, line 322
vtkMRMLLabelMapVolumeNode (00000269450C8810): vtkMRMLStorableNode::UpdateScene failed: Failed to read node LabelMapVolume_1 (vtkMRMLLabelMapVolumeNode2) using storage node vtkMRMLVolumeArchetypeStorageNode3.

**Comment by lassoan** [comment]
This may be normal if the labelmap was empty. Previous Slicer versions did not report this as errors. It is also possible that you only saved the scene and not the labelmap.

Can you share the data set? (zip all your files, upload it to somewhere, and post the link)

**Comment by 1939938853** [comment]
Hello, 

They are the data [here](https://pocus.cs.queensu.ca/#collection/5d9e6f2cd9e6a3be02d01293/folder/5d9e6f72d9e6a3be02d01294).

**Comment by lassoan** [comment]
Those labelmap images were empty when the scene was saved. You can safely ignore those errors.
