### ISSUE TITLE
Update vtkpng in Slicer's vtk

### ISSUE THREAD

**Issue by adamrankin** [Slicer/Slicer#6158]
I am trying to update SlicerOpenCV to newer OpenCV, but I'm getting libpng symbol conflicts. Could vtkpng in VTK be updated?

https://gitlab.kitware.com/vtk/vtk/-/commit/c20de1471bb85791da10e87abd1ce6d9ec23d9c9

Adam

**Comment by jcfr** [comment]
That would make sense. Do you confirm that the latest VTK need to be updated ? And not only the curent VTK version associated with Slicer master.

For reference, here is the PR updating VTK in Slicer. See https://github.com/Slicer/Slicer/pull/5978

**Comment by adamrankin** [comment]
Ah yes, that PR would fix this issue. Thanks!

**Comment by adamrankin** [comment]
With VTK branch above:
![image](https://user-images.githubusercontent.com/3210398/152700276-6276f108-cb9f-4e73-9b1d-213afaca964c.png)

**Comment by jcfr** [comment]
Thanks for testing the branch. 

Does it mean you were able to build the SlicerOpenCV extension?

**Comment by adamrankin** [comment]
Yes. That screenshot is my built slicer, with the package installed via extension manager from packaged .zip.

**Comment by jcfr** [comment]
Great. And do not hesitate to "play" with the build using volume rendering, markups, etc ... and report any issues.


After the build of the SlicerVirtualReality extension is fixed. I will go ahead and merge.
