### ISSUE TITLE
Some strings cannot be translated to other languages

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#6177]
Not all strings that are visible on the GUI show up in the list of translatable strings. Some strings show up but they do not get translated.

- [x] Module names that are visible on the GUI (i.e., module title) are not translated. For example: Volumes, Models, Markups (although they are available in the module widget) - see https://github.com/Slicer/Slicer/issues/6826
- [x] Python scripted modules are not translatable yet (except the GUI that is loaded from .ui file)
  - https://github.com/Slicer/Slicer/commit/60c659f33b672d8e8a7193f0741a2f56aaac080c (originally reviewed through https://github.com/Slicer/Slicer/pull/6920)
- [x] CLI modules are not translatable yet
  - fixed in https://github.com/Slicer/Slicer/pull/6681
- [x] Extensions are not translatable yet - done: see instructions at https://github.com/Slicer/SlicerLanguagePacks/blob/main/DevelopersManual.md#how-to-make-an-extension-translatable
- [x] Various examples of non-translatable strings: https://discourse.slicer.org/t/some-words-are-not-extracted-to-crowdin/21908 -- screenshots are no longer visible, but probably we already fixed those issues
- [x] Translation file must be added for CTK
  - https://github.com/Slicer/Slicer/pull/6926
  - https://github.com/commontk/CTK/pull/1076
  - https://github.com/commontk/CTK/pull/1079
  - https://github.com/commontk/CTK/pull/1077
  - https://github.com/commontk/CTK/pull/1068
- [x] Color table names are not translatable (see in Volumes module / Display section)
  - the issue is now tracked in https://github.com/Slicer/SlicerLanguagePacks/issues/59
- [x] Some strings appear in weblate but are actually non-translatable. This includes string properties in .ui files, such as `nodeTypes` in `qMRMLNodeComboBox`.

Documentation improvements:
- [x] Add documentation for Data Probe (describe what L, F, B labels mean = label, foreground, background) -- this is now tracked in https://github.com/Slicer/SlicerLanguagePacks/issues/60

**Comment by lassoan** [comment]
Yes, these issues still persist. They are due to that in current Slicer source code some dynamically created strings are not marked as translatable and we would need to implement collection of translatable strings from extensions.

**Comment by lassoan** [comment]
Non-translatable strings:
- [ ] Color table names are not translatable (see in Volumes module / Display section)

Documentation improvements:
- [ ] Add documentation for Data Probe (describe what L, F, B labels mean = label, foreground, background)

**Comment by jcfr** [comment]
@lassoan In addition of re-targeting to 5.5, I updated the description to update status & reference relevant commits and pull requests.

Since this issue aims to track on-going effort and is being actively worked on, re-targeting to the next milestone (instead of `Backlog`) seems reasonable.

**Comment by lassoan** [comment]
All the problems are now fixed or tracked in other issues.
