### ISSUE TITLE
Improve Export to file for multiple nodes

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#6180]
- Enable "Expor to file..." feature for clicking on the scene: it is just a folder the same way as all other folders
- Add an option to recreate folder structure: it would be an amazingly effective way to save a complex hierarchy of nodes
- Allow specifying non-existing subfolder(s) as Directory: it makes it much simpler to save into a new subfolder. If we already have a temporary folder but want to specify a subfolder for the new saved data then currently we need to: 1. click the `...` button, 2. click `New folder`, 3. type the folder name, then 4. click `Select` - we could save all these clicks by auto-creating the specified folder (and all parents). Some file writers create parent folders automatically, so the current behavior is also inconsistent (depending on the nodes, they can or cannot be written to a not-yet-existing folder).

**Comment by ebrahimebrahim** [comment]
> Add an option to recreate folder structure: it would be an amazingly effective way to save a complex hierarchy of nodes

With this option enabled, how would the following situation be treated (where a storable node has children)?

![image](https://user-images.githubusercontent.com/1879759/153653221-770de539-41eb-49cb-9185-81b69ac1e785.png)

Suggestion for saved directory hierarchy:

- `New Folder/`
  - `"MRHead Copy.nrrd"`
  - `MRHead.nrrd`
  - `MRHead_files/`
    - `F.json`
    - `L.json`

**Comment by ebrahimebrahim** [comment]
> Enable "Expor to file..." feature for clicking on the scene: it is just a folder the same way as all other folders

Making sure I understand correctly: The idea is to treat the scene as a folder and export its children. We don't want to export the _scene_ itself  (i.e. the `.mrml` file), correct?

**Comment by lassoan** [comment]
Correct, we would not export the .mrml file (just all the nodes that show up in the subject hierarchy).

**Comment by lassoan** [comment]
> With this option enabled, how would the following situation be treated (where a storable node has children)?

Everything would be saved as now. The storable node would be saved as `NodeName.ext` and the children would be saved as `NodeName/SomeOtherNodeName.ext`.

**Comment by ebrahimebrahim** [comment]
> * Allow specifying non-existing subfolder(s) as Directory: it makes it much simpler to save into a new subfolder. If we already have a temporary folder but want to specify a subfolder for the new saved data then currently we need to: 1. click the `...` button, 2. click `New folder`, 3. type the folder name, then 4. click `Select` - we could save all these clicks by auto-creating the specified folder (and all parents). Some file writers create parent folders automatically, so the current behavior is also inconsistent (depending on the nodes, they can or cannot be written to a not-yet-existing folder).

I think it makes sense to make the change at the level of saving logic, not just export. So I would make the change in `qSlicerCoreIOManager::saveNodes`. This is because the inconsistent behavior that you describe applies to saving as well.

Let me know if you think this makes sense or not

**Comment by ebrahimebrahim** [comment]
> Add an option to recreate folder structure: it would be an amazingly effective way to save a complex hierarchy of nodes

important question: should this setting be enabled by default or not?

**Comment by lassoan** [comment]
> I think it makes sense to make the change at the level of saving logic

I don't see a risk if it handled at lower level, as long as it can be guaranteed that the necessary directories are always created.

> should this setting be enabled by default or not?

Yes, I think it makes sense to enable this by default.

This feature is also useful because creating subject hierarchy folders from file system folders is already available (right-click on "Scene" in subject hierarchy and choose "Create hierarchy from loaded directory structure").
