### ISSUE TITLE
Extra undoState saved when redo is pressed on SegmentEditor

### ISSUE THREAD

**Issue by mauigna06** [Slicer/Slicer#6183]
Redo adds an extra undoState breaking up expected behaviour (and our customApp segmentEditor logic)

## Steps to reproduce

Use a example CT on the segment editor module. Select Paint effect. Paint 3 separed lines (or brush strokes) on axial view, Press undo button (there will be 2 lines on the axial view). Paint another separed line (now there are 3 lines again) because of this action an extra undoState is added that means you need to press undoButton 3 times (the expected would be 2) to have only one line on the sliceView.

## Environment
- Slicer version: Slicer-4.13.0-2022-02-09
- Operating system: Windows 10

**Comment by lassoan** [comment]
Thank you for the clear error report, I've pushed a fix.
