### ISSUE TITLE
Packaging misses two ITK libraries.

### ISSUE THREAD

**Issue by chir-set** [Slicer/Slicer#6209]
I'm building Slicer on Arch Linux at e4b8a88 with clang 13.0.1 and cmake 3.22.2.

Slicer would start only if we manually copy libITKniftiio-5.3.so.1 and libITKznz-5.3.so.1 from the build tree to $Slicer/lib/Slicer-4.13/. They are not packaged otherwise.

I have not tested factory preview build. That's easily manageable though. FYI.

Regards

**Comment by jamesobutler** [comment]
Yes we are aware of the packaging issues on the Linux platform. Something we are currently tracking at https://github.com/Slicer/Slicer/issues/6202 and will plan to resolve soon. It is broken in the factory build as well.

**Comment by jamesobutler** [comment]
Will proceed with tracking issue in #6202. Closing this now as a duplicate.
