### ISSUE TITLE
Get OpenVR working with latest Slicer

### ISSUE THREAD

**Issue by sjh26** [Slicer/Slicer#6214]

**Comment by cpinter** [comment]
Can you add more details? Is it only the matter of updating OpenVR in SlicerVR or something (other than flying) broke with the latest version?

Btw should this be a SlicerVR ticket given that that is where OpenVR is used with Slicer?

**Comment by jcfr** [comment]
I finalized the update of VTK to support building the extension, here is a preview: https://github.com/KitwareMedical/SlicerVirtualReality/pull/89#issuecomment-1048746241

@cpinter could you help address the remaining build issue due changes in VTK ?


Note: these commits are temporary and may change while I am finalizing.

**Comment by cpinter** [comment]
Yes, definitely. Thanks @jcfr !

**Comment by lassoan** [comment]
Regarding flying not working. This error (see https://github.com/KitwareMedical/SlicerVirtualReality/pull/89) indicates that recognizing gestures was refactored in the vtkOpenVRRenderWindowInteractor base class:

> In file included from /home/jcfr/Projects/SlicerVirtualReality/VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx:21:
/home/jcfr/Projects/SlicerVirtualReality/VirtualReality/MRML/vtkVirtualRealityViewInteractor.h:43:16: error: ‘virtual void vtkVirtualRealityViewInteractor::RecognizeComplexGesture(vtkEventDataDevice3D*)’ marked ‘override’, but does not override
   43 |   virtual void RecognizeComplexGesture(vtkEventDataDevice3D* edata) override;

The interactor in SlicerVirtualReality needs to be updated accordingly.

**Comment by cpinter** [comment]
Just an update that a debug Slicer is being built with the updated VTK. I'll work on fixing SlicerVR build during the weekend.

**Comment by jcfr** [comment]
I spend some time on that and I am finalizing. Then, I will publish my updated work and I will let you test & improve.

**Comment by jcfr** [comment]
> I will publish my updated work

See https://github.com/KitwareMedical/SlicerVirtualReality/pull/90

**Comment by jcfr** [comment]
Closing. Build of the extension has been fixed and remaining problems have been documented in https://github.com/KitwareMedical/SlicerVirtualReality/issues/91
