### ISSUE TITLE
VTK import fails using PythonSlicer from a Slicer build tree on Windows

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#6228]
`import vtk` fails in PythonSlicer.exe interpreter on Windows:

```
No module named 'logic'
DLL load failed while importing qSlicerBaseQTCLIPython: The specified module could not be found.
Traceback (most recent call last):
  File "D:\D\P\Slicer-0\Applications\SlicerApp\Testing\Python\StandalonePythonImportSlicerTest.py", line 2, in <module>
    import vtk
  File "D:\D\P\Slicer-0-build\VTK-build\bin\Lib\site-packages\vtk.py", line 31, in <module>
    all_m = importlib.import_module('vtkmodules.all')
  File "D:\D\P\Slicer-0-build\python-install\Lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\D\P\Slicer-0-build\VTK-build\bin\Lib\site-packages\vtkmodules\all.py", line 30, in <module>
    from .vtkRenderingQt import *
ImportError: DLL load failed while importing vtkRenderingQt: The specified module could not be found.
```

This causes `py_standalonepython_import_slicer` test to fail - see https://slicer.cdash.org/test/21535427

## Steps to reproduce

<s>Start `PythonSlicer.exe` in the install tree and type `import vtk`.</s>

Start `PythonSlicer.exe` in the `python-install` directory in the Slicer build tree and type `import vtk`.

## Expected behavior

VTK should be imported successfully.

## Workaround

Adding these lines to c:\D\S4R\python-install\bin\PythonSlicerLauncherSettings.ini fixes the issue:

```
[LibraryPaths]
1\path=C:/Qt/5.15.0/msvc2019_64/bin
size=1
```

## Environment
- Slicer version: Slicer-4.13.0-2022-02-20
- Operating system: Windows

**Comment by jcfr** [comment]
Thanks for the report. I will have a look this evening
