### ISSUE TITLE
Cannot access qSlicerVolumesModuleWidget::convertVolume() from Python

### ISSUE THREAD

**Issue by koegl** [Slicer/Slicer#6239]
In order to convert a volume to a label map programmatically I wanted to use the `qSlicerVolumesModuleWidget::convertVolume()` function, however I cannot access it through Python.

I can get the `qSlicerVolumesModuleWidget` with `slicer.util.getModuleWidget('Volumes')`, but it does not have the `convertVolume()` method

This happen in the latest preview version (2022-03-02) and in the stable release (4.11.20210226)

## Steps to reproduce
Try accessing the `convertVolume()` method in Python

## Expected behavior
The `convertVolume()` method should be accessible

## Environment
version 4.13.0  revision 30670  built 2022-03-03
- Slicer preview version: Slicer-4.13.0-2022-03-02
- Operating system: macOS Monterey, 12.2.1

**Comment by pieper** [comment]
That is a [protected slot](https://github.com/Slicer/Slicer/blob/cb3a1ff14fac3419f3e3f08632a6cac6bedb52ca/Modules/Loadable/Volumes/qSlicerVolumesModuleWidget.h#L52) of the widget, meaning it's not meant to be called by other code.  I see [you worked this out on discourse](https://discourse.slicer.org/t/how-to-convert-volume-to-label-map-programmatically/22288) and found how to do it with the logic.  In general we prefer keeping the GUI code as thin as possible and have it call logic methods for real work.
