### ISSUE TITLE
Slice view rendering does not work after loading scene when startup layout is 3D only

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#6284]
The slice views are empty and cannot be fixed with any action after we load a scene that has a layout containing slice views when the current layout (which was also the layout when starting Slicer) before loading the scene is 3D only.

## Steps to reproduce

* Set layout to 3D only
* Close Slicer
* Start Slicer
* Load scene that has some 2D views, like a Four-Up layout
* 2D views are inoperational

https://user-images.githubusercontent.com/1325980/160597008-6f5e60ee-5b71-4a24-9102-63433bed394e.mp4

## Expected behavior

* Every view shows data and work normally

## Environment
- Slicer version: Slicer-4.13.0-2022-03-28
- Operating system: Windows 10

**Comment by jcfr** [comment]
There is a VTK option that could be enabled `VTK_REPORT_OPENGL_ERRORS_IN_RELEASE_BUILDS`.

See https://github.com/Slicer/VTK/blob/slicer-v9.1.20220125-efbe2afc2/Rendering/OpenGL2/CMakeLists.txt#L314
