### ISSUE TITLE
Segment editor effects disabled when they should be enabled

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#6291]
After a certain sequence of steps the effects in Segment Editor are disabled although they should be enabled.

A workaround for this is to simply add an empty segment and delete it and they become enabled.

## Steps to reproduce

* Load MRHead
* Load CTChest
* Go to Segment Editor (segmentation for CTChest is created)
* Go to Data module
* Right-click MRHead and choose "Segment this..."
* Add empty segment -> Effect list is disabled but they should be enabled

https://user-images.githubusercontent.com/1325980/161081857-458333b9-8ad0-4458-992c-680404bdc131.mp4

## Expected behavior

The effect list should be enabled

## Environment
- Slicer version: Slicer-4.13.0-2022-03-29
- Operating system: Windows 10

**Comment by lassoan** [comment]
I cannot reproduce this issue anymore using latest Slicer Preview Release.
