### ISSUE TITLE
Install extensions is empty

### ISSUE THREAD

**Issue by phcerdan** [Slicer/Slicer#6293]
I am not able to access any content in Extension Managet > Install Extensions tab.
 
![image](https://user-images.githubusercontent.com/3021667/161153014-2c0d35b8-cf31-405a-b895-97a927f4e794.png)

The percentage bar gets into 100% and then white screen. I had no problems in other nightly versions of 4.13.

I thought that maybe it was a problem with my global Slicer.ini, so I removed it to start in a clean-state, but the problem persists.

## Steps to reproduce
Download latest 4.13, go to Extension Managet > Install Extensions tab and see it (in Linux).

## Expected behavior
I expected to see extensions, as in other nightly versions.
I have faced this behavior with Slicer previews from at least one or two months. Before that I remember was working.

## Environment
- Slicer version: Slicer-4.13.0-2022-03-28
- Operating system: Linux / Gnome /  X

**Comment by lassoan** [comment]
This is due to an SSL certificate issue or an overly aggressive firewall.

Is your computer behind a proxy server or corporate firewall?

Can you try installing more Slicer versions and determine which day the problem appeared?

**Comment by phcerdan** [comment]
Not behind a proxy, but it seems related indeed with ca-certificates. I am on Archlinux.

Will explore more and report back. Thanks for the hints @lassoan.

**Comment by phcerdan** [comment]
I can download urls from the Slicer python console, so it's not a SSL problem, as reported by @muratmaga in the discourse.

```python
url = qt.QUrl("https://slicer-packages.kitware.com/api/v1/file/613b26b1342a877cb3bee81e/download")
request = qt.QNetworkRequest(url)
manager = qt.QNetworkAccessManager()
reply = manager.get(request)

while (not reply.isFinished()):
    slicer.app.processEvents()

localFile = qt.QFile("/tmp/downloaded2.zip")
localFile.open(qt.QIODevice.WriteOnly)
localFile.write(reply.readAll());
localFile.close()

print(f"HTTP response code: {reply.attribute(qt.QNetworkRequest.HttpStatusCodeAttribute)}")
print(f"Error code: {reply.error()}")

```
```
>>> print(f"HTTP response code: {reply.attribute(qt.QNetworkRequest.HttpStatusCodeAttribute)}")
HTTP response code: 200
>>> print(f"Error code: {reply.error()}")
Error code: 0
>>> 
```

**Comment by lassoan** [comment]
It seems that you can access the backend server, which is useful information. We need to check if the frontend server (that displays the web GUI) can access this backend server, too.

You can debug that by opening the http://127.0.0.1:1337 address in a chromium based browser and then check if the request that gets the list of packages from the backend server is successful. The request will look something like this:

https://slicer-packages.kitware.com/api/v1/app/5f4474d0e1d8c75dfc705482/extension?app_revision=30735&os=win&q=&limit=0&sort=meta.baseName&sortdir=1

Also check out the application log in Slicer, as chromium logs errors there.

**Comment by phcerdan** [comment]
I cannot access: http://127.0.0.1:1337/. Tested with Chrome and Brave (chromium based).

Not even with:  `google-chrome-stable --remote-debugging-port=1337`

**Comment by phcerdan** [comment]
Umm, now we are talking:
```
[CRITICAL][FD] 01.04.2022 18:31:44 [] (unknown:0) - [105373:105818:0401/183144.592996:ERROR:devtools_http_handler.cc(420)] GetMimeType doesn't know mime type for: browser/84bc2af8-7e78-4931-b94d-579f9d278cdc text/plain will be returned
[CRITICAL][FD] 01.04.2022 18:31:44 [] (unknown:0) - [105373:105373:0401/183144.593058:ERROR:devtools_http_handler.cc(420)] GetMimeType doesn't know mime type for: browser/84bc2af8-7e78-4931-b94d-579f9d278cdc text/plain will be returned
[CRITICAL][FD] 01.04.2022 18:31:51 [] (unknown:0) - [105373:105818:0401/183151.576423:ERROR:devtools_http_handler.cc(420)] GetMimeType doesn't know mime type for:  text/plain will be returned
[CRITICAL][FD] 01.04.2022 18:31:51 [] (unknown:0) - [105373:105373:0401/183151.576622:ERROR:devtools_http_handler.cc(420)] GetMimeType doesn't know mime type for:  text/plain will be returned

```

**Comment by lassoan** [comment]
You can try the web widget with the extensions manager and various other sites like this:

```python
w = slicer.qSlicerWebWidget()
w.url = "https://extensions.slicer.org/catalog/All/30735/win"
w.show()
```

You can try other pages to confirm that the browser works well.

If you open the http://localhost:1337 page on Google Chrome or Microsoft Edge then you should see something like this:

![image](https://user-images.githubusercontent.com/307929/161308042-1f2976d1-29cf-49db-abcc-2e1404d2b021.png)

**Comment by phcerdan** [comment]
Ok, the `SlicerWebWidget` seems my failing part here, I can see the same output than when opening the Extensions Manager:

![image](https://user-images.githubusercontent.com/3021667/161309025-4e00e121-45d6-4214-a547-0ce71ea26035.png)

**Comment by lassoan** [comment]
Please try other websites, `https://www.google.com/`, `https://www.amazon.com/`, etc.

**Comment by phcerdan** [comment]
> Please try other websites, `https://www.google.com/`, `https://www.amazon.com/`, etc.

Same output, not loading, just the percentage bar.

**Comment by lassoan** [comment]
OK, so the issue is not related to the extensions manager. It is purely a chromium issue.

@RafaelPalomar could you help us here? Have you experienced similar problems on ArchLinux?

**Comment by phcerdan** [comment]
Long shot here, but might this news from Archlinux be related?

https://archlinux.org/news/chromium-losing-sync-support-in-early-march/

**Comment by jamesobutler** [comment]
Reports from users about this issue:
- https://discourse.slicer.org/t/extension-manager-in-linux-empty/22343
- https://discourse.slicer.org/t/archlinux-and-slicer-extensions-manager-is-empty/22710

**Comment by phcerdan** [comment]
Thanks for the links @jamesobutler. Indeed 100% related, I trusted google too much and didn't search in the slicer discourse for this topic.

**Comment by phcerdan** [comment]
I am not able to show a webpage either using pure pyqt5, so no slicer related. Closing, will keep the discussion on discourse, as it is more general.
