### ISSUE TITLE
"Close Scene" always claims the file has been modified and hasn't been saved

### ISSUE THREAD

**Issue by DIV-on-github** [Slicer/Slicer#6296]
`File` > `Close Scene` always claims the file has been modified and hasn't been saved, even if the user has just saved it immediately before.  

## Steps to reproduce

Open '3D Slicer'.  
Open some files and do a bunch of stuff*.  
Save all files with the "Save" button on the toolbar.  
Immediately close though `File` > `Close Scene`.  It always complains that the scene file (`*.mrml`) has been modified and hasn't been saved.  

*I realise the above is a bit general, but it seems to happen every time, no matter what operations are performed.  I cannot recall ever _not_ seeing that message.  

## Expected behaviour

If nothing has changed since the last save, then the user shouldn't see any warning.  

## Environment
- Slicer version: Slicer-4.13.0-2022-01-19
- Operating system: Windows 10 Enterprise x64

**Comment by jamesobutler** [comment]
> Slicer version: Slicer-4.13.0-2022-01-19

@DIV-on-github Have you tried with a recent Slicer preview release? It appears you are using one from January. This should already be fixed by https://github.com/Slicer/Slicer/commit/8694fc789671ef66644d10fff66d9c37826c40bd which was committed based on original report at https://discourse.slicer.org/t/save-before-exit-always-shows-even-right-after-save/21926.

**Comment by DIV-on-github** [comment]
Ah, I know what I did wrong:   I searched for issues mentioning "save", didn't see any, and concluded it hadn't yet been reported — but I neglected to search beyond _open_ issues.  Sorry.  
No, I haven't tried with another release.  I'll take your word that it was fixed.

**Comment by jamesobutler** [comment]
Yes please try the latest Slicer Preview as this will soon be the new Slicer Stable. We are looking for any remaining issues prior to release and your help is appreciated!

In regards to bug reports the bug report template created includes the following text (see below) which instructs to test with the latest Slicer Preview prior to submitting the report.

> [Give a short summary of what the problem is. Note: Before submitting an error report, please test if the problem is reproducible in the latest Slicer Preview Release. If the problem does not occur in the latest Slicer Preview Release then most likely it has been already fixed and there is no need to report it again.]
