### ISSUE TITLE
Pixel spacing incorrect when exporting US volumes to DICOM

### ISSUE THREAD

**Issue by koegl** [Slicer/Slicer#6302]
Exporting a US volume to DICOM (and setting the modality to US in the DICOM export dialog) incorrectly exports pixel spacing. This does not happen when the modality is set e.g. to CT

## Steps to reproduce
1. Export a US volume to DICOM (e.g. this one from RESECT [Case1-US-after.nii.zip](https://github.com/Slicer/Slicer/files/8423138/Case1-US-after.nii.zip)):
Right-click on the volume, select export to DICOM, accept the dialog that says that a study etc will be created, input 'US' as the modality and click export
2. Load the exported files into the DICOM database and load them. A warning saying "Image spacing may need to be calibrated for accurate size measurements." should appear.

## Expected behavior
The pixel spacing should be the same as in the original volume. In the case of the RESECT example linked above, if we go the the 'Volumes' module we see that the spacing of the original volume was (0.21239mm; 0.21239; 0.21239mm) and of the loaded volume (1.00000mm; 1.00000mm; 0.21239mm)

## Environment
- Slicer version: Slicer-4.13.0-2022-04-04
- Operating system: Mac M1Pro macOS Monterey 12.3

**Comment by lassoan** [comment]
David Clunie may provide a tool that can create valid 3D US images - see https://discourse.slicer.org/t/exporting-volumetric-ultrasound-to-dicom/22265/18. Until then, closing this issue.

See also https://github.com/Slicer/Slicer/issues/6303.
