### ISSUE TITLE
Only a single slice of a multi-file dicom is loaded

### ISSUE THREAD

**Issue by vinpa64** [Slicer/Slicer#6307]
I've noticed that Slicer 4.13 seems to behave differently than 4.11 when I try to load a multi-file dicom.

If you drag and drop a single file of a multi-file dicom into Slicer, de-select the "Single File" option, and click "Ok", in 4.13, only the slice corresponding to the file which was dragged and dropped is loaded. Opening a multi-file dicom like this is in 4.11 loads the whole volume, although often the volume is assembled with some slices out of order.

Was this change intentional? Is there a better quick way to open a multi-file volume in Slicer? It can be worked around by using something like dcm2niix to first merge the files, but sometimes if you just want to check something quickly, it is nice to open it directly in Slicer.

**Comment by lassoan** [comment]
DICOM files must be loaded using the DICOM module (see [documentation](https://slicer.readthedocs.io/en/latest/user_guide/data_loading_and_saving.html#dicom-data)). 

In general, there is no way to open a DICOM data set "quickly". Interpreting just a set of image files in a folder may work in many cases. However, these simple quick methods break down when you have unrelated files in a folder, a series is spread across many folders, does not work robustly if files are missing (not acquired, data corrupted, etc.), slices are not spaced evenly, orientation of slices vary across the series, etc. Many DICOM data objects (Segmentation Objects, RT information objects) cannot be interpreted alone, but the application must be look up information in linked data objects.

We'll soon prevent loading of DICOM files via the "Add data" window to avoid loading issues - see https://github.com/Slicer/Slicer/issues/5726. However, before that we would like to make sure that we make DICOM loading as simple as possible (without sacrificing robustness and wide support for various information object types). If you have any specific suggestions then please add comments to https://github.com/Slicer/Slicer/issues/5726.
