### ISSUE TITLE
Installing extension SegmentEditorExtraEffects hangs Slicer

### ISSUE THREAD

**Issue by dazzag24** [Slicer/Slicer#6310]
Using 2 different preview versions of 3D Slicer: 

VERSION="4.13.0.20220404"
VERSION="4.13.0.20220107"

I have experienced a hang when using a Python script to install the SegmentEditorExtraEffects extension

## Steps to reproduce

Create this script in /tmp/install-slicer-extension.py

```
import os
extensionName = os.environ['EXTENSION_TO_INSTALL']
print(f"installing {extensionName}")
em = slicer.app.extensionsManagerModel()
extensionMetaData = em.retrieveExtensionMetadataByName(extensionName)
extensionPackageFilename = ""

if slicer.app.majorVersion*100+slicer.app.minorVersion < 413:
    # Slicer-4.11
    itemId = extensionMetaData["item_id"]
    url = f"{em.serverUrl().toString()}/download?items={itemId}"
    extensionPackageFilename = f"{slicer.app.temporaryPath}/{itemId}"
else:
    # Slicer-4.13  
    itemId = extensionMetaData["_id"]
    url = f"{em.serverUrl().toString()}/api/v1/item/{itemId}/download"
    extensionPackageFilename = f"{slicer.app.temporaryPath}/{itemId}"

slicer.util.downloadFile(url, extensionPackageFilename)
em.installExtension(extensionPackageFilename)
exit()
```

then run:

`EXTENSION_TO_INSTALL=SegmentEditorExtraEffects xvfb-run --auto-servernum  /opt/slicer/Slicer --python-script /tmp/install-slicer-extension.py`

From the logging I suspect is happening on the `em.installExtension(extensionPackageFilename)` line.

[describe what you did and what happened - attach screenshots if possible]

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/1055831/162943820-d809e3a6-9dda-4b5b-8caf-e50cc32446dd.png">

## Expected behavior

Install process should not hang.

## Environment
- Slicer version: Slicer-4.??.?-YYYY-MM-DD

VERSION="4.13.0.20220404"
VERSION="4.13.0.20220107"

- Operating system: Windows / Linux / Mac + which version

Linux AMD64

**Comment by lassoan** [comment]
> there are permissions issues with the NA-MIC dir

There are many docker images out there that work well and can be used as examples. You probably have started from one of these examples but then made some changes in how you set up permissions at one place, which required changing permissions at other places. If you have any suggestions for how or where we could document these details that developers could find then let us know.

> Is there a better way for em.installExtension() to report errors to the user rather than just hanging?

Errors are already reported. What you have run into is that a popup was displayed to confirm installation of dependent extensions. You can disable this feature by setting `em.interactive = False`.

I've added this to the slicer-notebook docker image. Although it is unnecessary there, it should help in cases when this docker image is used as a template for other projects:

https://github.com/Slicer/SlicerDocker/blob/master/slicer-notebook/install.sh#L59

The interactive mode is documented in the [extensions manager API documentation](http://apidocs.slicer.org/master/classqSlicerExtensionsManagerModel.html#af0af1b681cd4c090de078ebbb06b8c1e) and now also included in the [script repository example](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#download-and-install-extension).

Any suggestions for making the solution easier to find for future developers are welcome.

**Comment by dazzag24** [comment]
Thanks.  I had used https://github.com/Slicer/SlicerDocker/blob/master/slicer-notebook/install.sh as inspiration.

Could the `em.interactive = False` line go on line 43 instead so that it applies to both the slicer-4.11 and slicer-4.13 cases?

**Comment by lassoan** [comment]
I don't think interactive flag was available in 4.11.

**Comment by dazzag24** [comment]
Can extensions also be installed in the users $HOME/.config/NA-MIC dir?

**Comment by lassoan** [comment]
More and more extensions rely on additional Python packages, so you need to treat Slicer as any other virtual Python environment that a user creates - that would be problematic to share between users. So, even though extensions could be installed into a user home folder and the extensions may work if they don't install any additional Python packages, this is not a supported use case anymore.
