### ISSUE TITLE
Segment Editor effect list stuck disabled

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#6311]
In some cases the effect list stays disabled even though it should be enabled.

## Steps to reproduce

- Load MRHead
- Right-click MRHead in Data module and choose "Segment this.."
- Add segment
- Right-click MRHead in Data module and choose "Segment this.."
- Add segment
- Editing tools are not enabled

## Expected behavior

The effects should be enabled

## Environment
- Slicer version: Slicer-4.13.0-2022-04-12
- Operating system: Windows 10

**Comment by lassoan** [comment]
Can we close this (fixed by https://github.com/Slicer/Slicer/pull/6312)?
