### ISSUE TITLE
Zoom in linked slices gets out of sync when using right-click+drag (again)

### ISSUE THREAD

**Issue by DIV-on-github** [Slicer/Slicer#6318]
## Steps to reproduce

I linked the slice views and when I **right-click+drag** to change the field of view (zoom), only the field of view of the slice where my mouse is is changed.

When I use **ctrl+scroll** all the linked slice views are synchronised and change together.

I assume that this is a bug, based on similar past reports:

* [Zoom in linked slices gets out of sync when using ctl+scroll](https://discourse.slicer.org/t/zoom-in-linked-slices-gets-out-of-sync-when-using-ctl-scroll/9994) (Jan. 2020)
* [Zoom in linked slices gets out of sync when using right-click+drag 1](https://discourse.slicer.org/t/zoom-in-linked-slices-gets-out-of-sync-when-using-right-click-drag/21678) (Jan. 2022)

In previous versions using either **right-click+drag** or **ctrl+scroll** was equivalent: both methods changed the field of view (or zoom) of all linked slices.
Indeed, the second linked post, above, indicates that a bug with the same symptoms was fixed in version 4.13.0; revision 30570; built 2022-01-29, so this appears to be a regression.  

I didn’t notice any indication in the online [User Guide for the user interface](https://slicer.readthedocs.io/en/latest/user_guide/user_interface.html#slice-views) that the behaviour is supposed to be different.

I initially posted this to https://discourse.slicer.org/t/bug-zoom-in-linked-slices-gets-out-of-sync-when-using-right-click-drag-again/22996
and this unexpected behaviour has been verified by another user.  

## Expected behaviour

Linking slices is expected to mean that zoom would be synchronised across all slices, regardless of the method of user interaction.  

Alternatively, if it's an intended feature, then it should be documented in the online [User Guide for the user interface](https://slicer.readthedocs.io/en/latest/user_guide/user_interface.html#slice-views).

## Environment
- Slicer version: Slicer-4.13.0-2022-03-31 (or earlier) to Slicer-4.13.0-2022-04-16 (or later)
- Operating system: Windows 10 Pro for Workstations

**Comment by lassoan** [comment]
Thank you, for reporting. This was a regression introduced by the recently added interactive slice intersection feature. I've pushed a fix.
