### ISSUE TITLE
Issue with write a segment as a NumPy array

### ISSUE THREAD

**Issue by weathon** [Slicer/Slicer#6325]
In the [documentation](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#read-and-write-a-segment-as-a-numpy-array) the code
```python
slicer.util.updateSegmentBinaryLabelmapFromArray(segmentArray, segmentationNode, segmentId, volumeNode)
```
is not working as the `updateSegmentBinaryLabelmapFromArray` is not a function in the `slicer.util`

**Comment by lassoan** [comment]
The latest version of the documentation is for the latest Slicer Preview Release. Please use the latest Slicer Preview Release and let us know if you still run into any issues.

**Comment by weathon** [comment]
is there a way to write segmentation array without using the preview? (Is there a function to do so in the old version) @lassoan

**Comment by jamesobutler** [comment]
Hi @weathon, let us know if this is still an issue for you. Since your original post there has been a new Slicer stable release. You can download current Slicer stable 5.0.3 from https://download.slicer.org/.

**Comment by lassoan** [comment]
Good catch @jamesobutler, this can be closed now.
