### ISSUE TITLE
Cannot install extensions from ExtensionManager on MacOS

### ISSUE THREAD

**Issue by che85** [Slicer/Slicer#6347]
In most recent versions of Slicer, extensions cannot be installed directly from the ExtensionManager on  MacOS

<img width="2168" alt="Screen Shot 2022-05-02 at 10 19 36 AM" src="https://user-images.githubusercontent.com/10195822/166249936-11de4c36-89d1-404d-b64f-6be6465ec40b.png">

## Steps to reproduce

Install Slicer on MacOS and try to install any extension from the ExtensionManager.

## Environment
- Slicer version: 
  - Slicer-5.0.1-2022-05-01 and Slicer-4.13.0-2022-04-27 and probably versions prior to that. 
- Operating system: MacOS Monterey 12.2

**Comment by che85** [comment]
I just tested on older Slicer preview versions and it's happening for all of them. The stable release works fine.

**Comment by jcfr** [comment]
I am wondering is this is specific to `Monterey 12.2` or this is related to institution network ...  

| Status | Extension Manager | macOS version |
|--|--|--|
| :heavy_check_mark:  | ![image](https://user-images.githubusercontent.com/219043/166329640-4084bdbb-28e3-4e92-9a20-ada1d5ff459d.png) | ![image](https://user-images.githubusercontent.com/219043/166329761-3a907f0b-fc45-41cb-a52e-03d0e150d0f6.png) |

**Comment by jcfr** [comment]
Here is a discourse post to gather feedback from other users:
https://discourse.slicer.org/t/help-for-package-testing-on-macos-monterrey-or-bigsur-system/23249/3

**Comment by che85** [comment]
@jcfr I started Slicer from the terminal:

```
herzc@MH6RP2059X /A/S/C/MacOS [SIGINT]> ./Slicer                                                                                                                                                                                                                       (base) 
qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_param_check
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_ciphersuites
qt.network.ssl: QSslSocket: cannot resolve SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot resolve SSL_SESSION_is_resumable
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
[SSL] SSL support disabled - Failed to load SSL library !
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
[SSL] Failed to load Slicer.crt
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0m-dev  xx XXX xxxx was found instead
Switch to module:  "Welcome"
```

It turns out, that I had an older OpenSSL version installed.

After uninstalling that version and using the system default, everything works.

**Comment by jcfr** [comment]
Thanks for the update. And well done finding the root cause.

Do you happen to have more details about how was OpenSSL installed?

Since  the ssl libraries are shipped with Slicer, it would be nice to understand how that other install caused trouble.

**Comment by che85** [comment]
When building Slicer on Apple M1, I followed these guidelines: https://github.com/Slicer/Slicer/issues/5944#issuecomment-1003591261

OpenSSL 1.1.0 was built locally and compiling of Slicer worked. 

At some point in a more recent Slicer revision, I then didn't need to use the locally build OpenSSL version but didn't `make uninstall` which caused all this headache here.

**Comment by jcfr** [comment]
Thanks for clarifying.

### installed location of OpenSSL

> didn't `make uninstall` which caused all this headache here.

For future reference, in which system folder was it installed ?

### Meaning of "installed Slicer"

When you indicated the following in the issue:

> Steps to reproduce
> Install Slicer on MacOS and try to install any extension from the ExtensionManager.

By `Install Slicer`, you meant you downloaded the nightly build and for some reason, the package attempted to load the incorrect OpenSSL libraries ?

I am trying to understand better so that we can ensure the expected libraries (aka the one we built and ship) are effectively used.
