### ISSUE TITLE
Ignore QT_PLUGIN_PATH environment variable

### ISSUE THREAD

**Issue by fbordignon** [Slicer/Slicer#6353]
Hey guys, I am proposing to ignore the `QT_PLUGIN_PATH` environment variable altogether when it comes from the user or system environment variable.

Bear with me. I know that Qt recommends not using it globally in our systems but some users do it anyways, effectively crashing Slicer upon startup. You can reproduce it by globally setting `QT_PLUGIN_PATH` to a plugins path from another qt version. e.g. `C:\Qt\Qt5.9.1\5.9.1\msvc2017_64\plugins`

The recommendation is to set it on a local context only, i.e. use a launch script. See the blue note reproduced below and[ linked](https://doc.qt.io/qt-5/deployment-plugins.html):

> Note: Do not export QT_PLUGIN_PATH as a system-wide environment variable because it can interfere with other Qt installations.

In slicer's case we already have a launcher and `SlicerLauncherSettings.ini` file. In this file we set the internal Slicer qt plugins directory, so the user/developer can easily add folders to the list and manipulate the `QT_PLUGIN_PATH` variable that goes to `SlicerApp-real.exe`.

So what I am proposing is to ship `SlicerLauncherSettings.ini` with the following addition to the [EnvironmentVariables]

```
[EnvironmentVariables]
...
QT_PLUGIN_PATH=QT_PLUGIN_PATH
```

This way it overwrites the environment variable and still maintains the ability to edit what goes to `SlicerApp-real.exe`. It also allows the user to delete this line and use the global environment variable again.
Some users of ours are having this issue and I believe we can make this modification to prevent issues with 3D Slicer as well.

Please advise why this is a bad/good idea.

**Comment by lassoan** [comment]
> some users do it anyways

If it is just a use then tell him to stop. If it is an application then report the issue to the developers.

There are many, many ways you can mess up an application by setting environment variables incorrectly, so I don't think that eliminating one possibility would make any significant difference.

**Comment by fbordignon** [comment]
Ok, agreed. At least if someone runs into it there is a half good explanation about the issue that happened. Thanks

**Comment by jcfr** [comment]
Thanks for the detailed report :pray: 

Alternatively, we could look into improving the AppLauncher/AppLauncherLib to have the concept of validation rules with:

* Launcher specific option like `--launcher-environment-validation` accepting `none`, `warn` or `error`

* Support for new settings entries:
  * `Environment/validation` 
  * `EnvironmentValidationRules/APPLAUNCHER_0_<varNAme>=<expectedValue>`

```diff
[Environment]
additionalPathVariables=QT_PLUGIN_PATH,PYTHONPATH,LibraryPaths
+validation=none

+[EnvironmentValidationRules]
+APPLAUNCHER_0_QT_PLUGIN_PATH=
```

That said, this would add more complexity  ...
