### ISSUE TITLE
Infinite loop possible due to circular singleton transform node references on scene load

### ISSUE THREAD

**Issue by Sunderlandkyl** [Slicer/Slicer#6355]
When loading a scene that contains markups transformed by singleton transform nodes it is possible to enter an infinite loop calling vtkMRMLTransformNode::GetTransformBetweenNodes(). This can happen if a circular loop is created between the transform nodes as their references are being updated.

It is possible that infinite loops may happen elsewhere during scene load due to similar function calls.

## Steps to reproduce

To reproduce the bug:
- Copy and paste the following code into the python interactor
- Save the scene
- Call SetReferenceFrameToA()
- Load the saved scene

<details><summary>Python Interactor Code</summary>
<pre>
def SetReferenceFrameToA():
  getNode("AToA").SetAndObserveTransformNodeID(None)
  getNode("BToB").SetAndObserveTransformNodeID(transformBToA.GetID())

def SetReferenceFrameToB():
  getNode("BToB").SetAndObserveTransformNodeID(None)
  getNode("AToA").SetAndObserveTransformNodeID(transformAToB.GetID())

name = "AToA"
transformAToA = slicer.vtkMRMLLinearTransformNode()
transformAToA.SetName(name)
transformAToA.SetSingletonTag(name)
slicer.mrmlScene.AddNode(transformAToA)

name = "BToB"
transformBToB = slicer.vtkMRMLLinearTransformNode()
transformBToB.SetName(name)
transformBToB.SetSingletonTag(name)
slicer.mrmlScene.AddNode(transformBToB)

name = "AToB"
transformAToB = slicer.vtkMRMLLinearTransformNode()
transformAToB.SetName(name)
transformAToB.SetSingletonTag(name)
slicer.mrmlScene.AddNode(transformAToB)

name = "BToA"
transformBToA = slicer.vtkMRMLLinearTransformNode()
transformBToA.SetName(name)
transformBToA.SetSingletonTag(name)
slicer.mrmlScene.AddNode(transformBToA)

name = "A"
markupsNodeA = slicer.vtkMRMLMarkupsFiducialNode()
markupsNodeA.SetName("A")
markupsNodeA.SetSingletonTag("A")
slicer.mrmlScene.AddNode(markupsNodeA)

markupsNodeA.SetAndObserveTransformNodeID(transformAToA.GetID())
transformBToA.SetAndObserveTransformNodeID(transformAToA.GetID())
transformAToB.SetAndObserveTransformNodeID(transformBToB.GetID())
SetReferenceFrameToB()
</pre>
</details>

<details><summary>Example stack trace</summary>
<pre>
[External Code]	
vtkCommon-9.1.dll!vtkTransformConcatenation::Concatenate(vtkAbstractTransform * trans) Line 444	C++
vtkCommon-9.1.dll!vtkGeneralTransform::Concatenate(vtkAbstractTransform * transform) Line 238	C++
MRMLCore.dll!vtkMRMLTransformNode::GetTransformBetweenNodes(vtkMRMLTransformNode * sourceNode, vtkMRMLTransformNode * targetNode, vtkGeneralTransform * transformSourceToTarget) Line 533	C++
vtkSlicerMarkupsModuleMRML.dll!vtkMRMLMarkupsNode::ProcessMRMLEvents(vtkObject * caller, unsigned long event, void * callData) Line 228	C++
MRMLCore.dll!vtkMRMLNode::MRMLCallback(vtkObject * caller, unsigned long eid, void * clientData, void * callData) Line 901	C++
vtkCommon-9.1.dll!vtkCallbackCommand::Execute(vtkObject * caller, unsigned long event, void * callData) Line 42	C++
MRMLCore.dll!vtkEventBroker::InvokeObservation(vtkObservation * observation, unsigned long eid, void * callData) Line 841	C++
MRMLCore.dll!vtkEventBroker::ProcessEvent(vtkObservation * observation, vtkObject * caller, unsigned long eid, void * callData) Line 713	C++
MRMLCore.dll!vtkEventBroker::Callback(vtkObject * caller, unsigned long eid, void * clientData, void * callData) Line 920	C++
vtkCommon-9.1.dll!vtkCallbackCommand::Execute(vtkObject * caller, unsigned long event, void * callData) Line 42	C++
vtkCommon-9.1.dll!vtkSubjectHelper::InvokeEvent(unsigned long event, void * callData, vtkObject * self) Line 651	C++
[Inline Frame] MRMLCore.dll!vtkObject::InvokeEvent(unsigned long) Line 230	C++
MRMLCore.dll!vtkMRMLNode::InvokePendingModifiedEvent() Line 557	C++
MRMLCore.dll!vtkMRMLScene::AddNodeNoNotify(vtkMRMLNode * n) Line 1252	C++
MRMLCore.dll!vtkMRMLScene::AddNode(vtkMRMLNode * n) Line 1336	C++
MRMLCore.dll!vtkMRMLScene::Import(vtkMRMLMessageCollection * userMessagesInput) Line 845	C++
MRMLCore.dll!vtkMRMLScene::ReadFromMRB(const char * fullName, bool clear, vtkMRMLMessageCollection * userMessagesInput) Line 3983	C++
qSlicerBaseQTCore.dll!qSlicerSceneBundleReader::load(const QMap & properties) Line 93	C++
qSlicerBaseQTCore.dll!qSlicerCoreIOManager::loadNodes(const QString & fileType, const QMap & parameters, vtkCollection * loadedNodes, vtkMRMLMessageCollection * userMessages) Line 587	C++
qSlicerBaseQTGUI.dll!qSlicerIOManager::loadNodes(const QString & fileType, const QMap & parameters, vtkCollection * loadedNodes, vtkMRMLMessageCollection * userMessages) Line 446	C++
qSlicerBaseQTGUI.dll!qSlicerIOManager::loadNodes(const QList> & files, vtkCollection * loadedNodes, vtkMRMLMessageCollection * userMessages) Line 468	C++
qSlicerBaseQTGUI.dll!qSlicerDataDialog::exec(const QMap & readerProperties) Line 679	C++
qSlicerBaseQTGUI.dll!qSlicerIOManager::execDelayedFileDialog() Line 363	C++
[External Code]	
qSlicerBaseQTGUI.dll!qSlicerApplication::notify(QObject * receiver, QEvent * event) Line 426	C++
[External Code]	
qSlicerBaseQTCore.dll!qSlicerCoreApplication::exec() Line 929	C++
SlicerApp-real.exe!`anonymous namespace'::SlicerAppMain(int argc, char * * argv) Line 62	C++
[External Code]	
</pre>
</details>

## Expected behavior

Scene will load successfully.

## Environment
- Slicer version: Slicer-4.13.0+
- Operating system: Windows

## Possible fixes

- #6323 fixes the issue by ensuring that GetTransformBetweenNodes() does not get caught in a circular reference loop.
- To be more robust, it would be better to improve scene loading so that node references ID conflicts are resolved before nodes are inserted into the scene.

**Comment by lassoan** [comment]
fixed in https://github.com/jcfr/Slicer/commit/45978905083edfeda4a1d65219f35e4d9e16c31e
