### ISSUE TITLE
BUG: in Endoscopy module

### ISSUE THREAD

**Issue by gaoyi** [Slicer/Slicer#6360]
[Give a short summary of what the problem is. Note: Before submitting an error report, please test if the problem is reproducible in the latest Slicer Preview Release. If the problem does not occur in the latest Slicer Preview Release then most likely it has been already fixed and there is no need to report it again.]

## Steps to reproduce

The call to vtk_to_numpy function call was removed in a258951f473d74f24a93cff95673ea6163a7b5e1 by mistake. Causing path generation to fail.

It's a small bug. I've added it back and created an PR.

## Expected behavior

Things should be back to normal.

## Environment
- Slicer version: Slicer-4.13.0-2022-05-08
- Operating system: Linux + Ubuntu 22.04

**Comment by jamesobutler** [comment]
Closed by https://github.com/Slicer/Slicer/commit/3d66964c524a58b2583aac051e1310a5019d0039.
