### ISSUE TITLE
Saving structures with 3D slicer

### ISSUE THREAD

**Issue by MohHu** [Slicer/Slicer#6361]
Dear developer,

I am writing to you because I have set of images with structure in form of DICOM. The DICOM set was exported by MONACO. When I import it to 3D slicer, It works and there is no problem. I modified the structures and export it to TPS in order to calculate the dose. However, CT images are exported as DICOM, but structure is omitted. I use '' Create a DICOM series''.

Is it possible to export images and structure from 3D Slicer without missing structure DICOM?

Yours sincerely

**Comment by lassoan** [comment]
You need to follow these instructions here: https://slicer.readthedocs.io/en/latest/user_guide/modules/dicom.html#export-data-from-the-scene-to-dicom-database

The issue tracker is for tracking software changes. If you have questions about how to usebthe software, please post it to the [Slicer Forum](https://discourse.slicer.org).
