### ISSUE TITLE
Clone a node with copying display properties

### ISSUE THREAD

**Issue by jumbojing** [Slicer/Slicer#6372]
我画了一条直线如图, 并且设置了显示属性加粗和颜色…

> I drew a straight line as shown in the figure, and set the display attributes with the line width and color…

![image](https://aws1.discourse-cdn.com/standard17/uploads/slicer/optimized/2X/9/9198492ddc2e91035f65a6a7ce48d3d361a0da6d_2_582x500.png)

and then clone it… get this result

![image](https://aws1.discourse-cdn.com/standard17/uploads/slicer/optimized/2X/b/bb0b3618687299afce7937abc13b50ac8ea4641a_2_690x407.png)

Why clone a line node without display properties?

**Comment by cpinter** [comment]
Question answered on discourse
https://discourse.slicer.org/t/why-clone-a-line-node-without-display-properties/19922/7

@jumbojing Please ask a question only one place at a time. Duplicate questions generate unnecessary extra work for the community. Than you.
