### ISSUE TITLE
Unable to load DICOM module

### ISSUE THREAD

**Issue by arge-7** [Slicer/Slicer#6373]
All of a sudden today, I lost the ability to use the DICOM loader. When I click the button on the welcome screen I get the error

The module "DICOM" has not been registered.

I've tried uninstalling and reinstalling, as well as trying the earlier stable version. The DICOM module isn't even listed when I use the search feature to see all available modules. I'm not sure what changed because it started out of the blue without doing anything I can think of that would affect it.

## Steps to reproduce

Open Slicer, get to welcome screen, click Add DICOM Data button.

## Expected behavior

DICOM importer opens with no errors and imports data flawlessly like it has in the past

## Environment
- Slicer version: Slicer-5.1.0-2022-05-12
- Operating system: macOS Montery

I've attached the only error logs I see.
<img width="926" alt="Screen Shot 2022-05-13 at 11 11 20 AM" src="https://user-images.githubusercontent.com/68198440/168325185-bafefc70-37c5-49d4-87ad-d39b5ba88856.png">
![Uploading Screen Shot 2022-05-13 at 11.11.43 AM.png…]()
<img width="514" alt="Screen Shot 2022-05-13 at 11 11 59 AM" src="https://user-images.githubusercontent.com/68198440/168325201-15a745f0-a5bb-4c27-8c8c-dc628b7e4c6a.png">

**Comment by arge-7** [comment]
[DEBUG][Qt] 13.05.2022 11:24:13 [] (unknown:0) - Session start time .......: 2022-05-13 11:24:13
[DEBUG][Qt] 13.05.2022 11:24:13 [] (unknown:0) - Slicer version ...........: 5.1.0-2022-05-12 (revision 30939 / 9c7f205) macosx-amd64 - installed release
[DEBUG][Qt] 13.05.2022 11:24:13 [] (unknown:0) - Operating system .........: macOS / 12.3.1 / 21E258 / UTF-8 - 64-bit
[DEBUG][Qt] 13.05.2022 11:24:13 [] (unknown:0) - Memory ...................: 65536 MB physical, 0 MB virtual
[DEBUG][Qt] 13.05.2022 11:24:13 [] (unknown:0) - CPU ......................:  Apple M1 Max, 10 cores, 10 logical processors
[DEBUG][Qt] 13.05.2022 11:24:13 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, Sequential threading
[DEBUG][Qt] 13.05.2022 11:24:13 [] (unknown:0) - Qt configuration .........: version 5.15.2, with SSL, requested OpenGL 3.2 (core profile)
[DEBUG][Qt] 13.05.2022 11:24:13 [] (unknown:0) - Internationalization .....: disabled, language=
[DEBUG][Qt] 13.05.2022 11:24:13 [] (unknown:0) - Developer mode ...........: disabled
[DEBUG][Qt] 13.05.2022 11:24:13 [] (unknown:0) - Application path .........: /Applications/Slicer.app/Contents/MacOS
[DEBUG][Qt] 13.05.2022 11:24:13 [] (unknown:0) - Additional module paths ..: Extensions-30939/FiducialsToModelDistance/lib/Slicer-5.1/qt-scripted-modules, Extensions-30939/GyroGuide/lib/Slicer-5.1/qt-scripted-modules, Extensions-30939/NvidiaAIAssistedAnnotation/lib/Slicer-5.1/qt-scripted-modules, Extensions-30939/SkullStripper/lib/Slicer-5.1/cli-modules, Extensions-30939/SlicerFreeSurfer/lib/Slicer-5.1/qt-loadable-modules
[DEBUG][Python] 13.05.2022 11:24:14 [Python] (/Applications/Slicer.app/Contents/lib/Slicer-5.1/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:38) - Scripted subject hierarchy plugin registered: Annotations
[INFO][Python] 13.05.2022 11:24:14 [Python] (/Applications/Slicer.app/Contents/Extensions-30939/NvidiaAIAssistedAnnotation/lib/Slicer-5.1/qt-scripted-modules/SegmentEditorNvidiaAIAA.py:32) - This plugin dir: /Applications/Slicer.app/Contents/Extensions-30939/NvidiaAIAssistedAnnotation/lib/Slicer-5.1/qt-scripted-modules
[DEBUG][Qt] 13.05.2022 11:24:14 [] (unknown:0) - Switch to module:  "Welcome"
[INFO][Stream] 13.05.2022 11:24:14 [] (unknown:0) - This plugin dir: /Applications/Slicer.app/Contents/Extensions-30939/NvidiaAIAssistedAnnotation/lib/Slicer-5.1/qt-scripted-modules
[DEBUG][Qt] 13.05.2022 11:24:36 [] (unknown:0) - The module "DICOM" has not been registered.
[DEBUG][Qt] 13.05.2022 11:24:36 [] (unknown:0) - The following modules have been registered: ("ACPCTransform", "AddScalarVolumes", "Annotations", "BRAINSDWICleanup", "BRAINSDeface", "BRAINSFit", "BRAINSIntensityNormalize", "BRAINSROIAuto", "BRAINSResample", "BRAINSResize", "BRAINSStripRotation", "BRAINSTransformConvert", "Cameras", "CastScalarVolume", "CheckerBoardFilter", "Colors", "CreateDICOMSeries", "CropVolume", "CurvatureAnisotropicDiffusion", "DWIConvert", "Data", "Decimation", "DynamicModeler", "EventBroker", "ExecutionModelTour", "ExtractSkeleton", "FiducialRegistration", "FiducialsToModelDistance", "FreeSurferImporter", "FreeSurferMarkups", "GaussianBlurImageFilter", "GradientAnisotropicDiffusion", "GrayscaleFillHoleImageFilter", "GrayscaleGrindPeakImageFilter", "GrayscaleModelMaker", "GyroGuide", "HistogramMatching", "ImageLabelCombine", "LabelMapSmoothing", "Markups", "MaskScalarVolume", "MedianImageFilter", "MergeModels", "ModelMaker", "ModelToLabelMap", "Models", "MultiVolumeExplorer", "MultiplyScalarVolumes", "N4ITKBiasFieldCorrection", "OrientScalarVolume", "PETStandardUptakeValueComputation", "PerformMetricTest", "Plots", "ProbeVolumeWithModel", "Reformat", "ResampleDTIVolume", "ResampleScalarVectorDWIVolume", "ResampleScalarVolume", "RobustStatisticsSegmenter", "SceneViews", "SegmentEditorNvidiaAIAA", "Segmentations", "Sequences", "SimpleRegionGrowingSegmentation", "SkullStripper", "SubjectHierarchy", "SubtractScalarVolumes", "Tables", "Terminologies", "Texts", "ThresholdScalarVolume", "Transforms", "Units", "ViewControllers", "VolumeRendering", "Volumes", "VotingBinaryHoleFillingImageFilter", "Welcome")
[DEBUG][Qt] 13.05.2022 11:25:47 [] (unknown:0) - Switch to module:  "CropVolume"
[DEBUG][Qt] 13.05.2022 11:25:58 [] (unknown:0) - Switch to module:  "CreateDICOMSeries"

**Comment by lassoan** [comment]
It seems that Python scripting got broken. Maybe your settings got corrupted. Please try starting Slicer using this command:

    open Slicer.app --args --disable-settings

If this does not help then delete /Applications/Slicer.app and install Slicer again.

**Comment by arge-7** [comment]
OK that completely worked. When I try opening it via clicking the icon like normal, the error persists. What can I do to fix this? Earlier I tried deleting and reinstalling and that didn't seem to work. Thanks!

**Comment by lassoan** [comment]
You can rename/move/delete the Slicer settings file to resolve the issue. https://slicer.readthedocs.io/en/latest/user_guide/settings.html#settings-file-location

**Comment by arge-7** [comment]
This completely fixed it. You da man! Thanks so much for the quick response and solving the issue.
