### ISSUE TITLE
Slicer build CI step error

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#6392]
Slicer build CI step in pull requests fail since the last CTK update with an error like this:

```
/usr/src/Slicer/Modules/Loadable/Colors/qSlicerColorsModuleWidget.cxx: In member function ‘void qSlicerColorsModuleWidget::onMRMLColorNodeChanged(vtkMRMLNode*)’:
/usr/src/Slicer/Modules/Loadable/Colors/qSlicerColorsModuleWidget.cxx:273:132: error: no matching function for call to ‘ctkVTKScalarsToColorsView::setColorTransferFunctionToPlots(vtkColorTransferFunction*, bool&)’
     d->ContinuousScalarsToColorsWidget->view()->setColorTransferFunctionToPlots(procColorNode->GetColorTransferFunction(), editable);
```

(https://github.com/Slicer/Slicer/runs/6562089633?check_suite_focus=true)

It may be due to Slicer build requires latest CTK but it seems https://hub.docker.com/r/slicer/slicer-base/tags is not updated anymore (`Last pushed 2 months ago by samhorvath`).

**Comment by jcfr** [comment]
Thanks for the report :pray: 

This should be fixed in https://github.com/Slicer/SlicerDockerUpdate/commit/12f1e7bf05d9c742c5ee42eeb79b13de35554a74

**Comment by jcfr** [comment]
Follow up commit pushed to https://github.com/Slicer/SlicerDocker/commit/efd7f6cee78f2006250c9c491fea1cd4ece25696

Build of the image manually triggered running [SlicerDockerUpdate/cronjob.sh](https://github.com/Slicer/SlicerDockerUpdate/blob/master/cronjob.sh)

**Comment by jcfr** [comment]
Issue has now been addressed:

![image](https://user-images.githubusercontent.com/219043/170133874-dcd30a4d-68fc-4c18-84b2-170442699f62.png)

![image](https://user-images.githubusercontent.com/219043/170133937-fa47a7a8-c196-4646-b9d1-3b07e5ad30cc.png)
