### ISSUE TITLE
Missing api-ms-win-core-path-l1-1-0.dll when trying to run Slicer 5.0 on Windows 7

### ISSUE THREAD

**Issue by bratmody11** [Slicer/Slicer#6393]
[Give a short summary of what the problem is. Note: Before submitting an error report, please test if the problem is reproducible in the latest Slicer Preview Release. If the problem does not occur in the latest Slicer Preview Release then most likely it has been already fixed and there is no need to report it again.]
I was using the 4.11 version which crashed so I went to install version 5.02 by downloading. but it did not get installed because of a missing DLL file. error report attached.
## Steps to reproduce
I downloaded it three times still has the same error. I even tried the unstable version it gave the same error.
[describe what you did and what happened - attach screenshots if possible]

## Expected behavior 
![slicer](https://user-images.githubusercontent.com/18465013/170420386-ed25394c-f3f6-41e4-bbbc-b0384dab4cc7.jpg)
i expected the downloaded versions to be installed but it did not on repeated trying.

[describe what you expected to happen]

## Environment
- Slicer version: Slicer-4.??.?-YYYY-MM-DD   5.02 2022-05-25 
- Operating system: Windows / Linux / Mac + which version windows

**Comment by lassoan** [comment]
What Windows version do you use?

**Comment by lassoan** [comment]
Check if installing this [Visual Studio 2022 Redistributable package](https://aka.ms/vs/17/release/vc_redist.x64.exe) fixes the issue. 

For reference, the link was obtained from [here](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) -> `Microsoft Visual C++ Redistributable` -> `Visual Studio 2015, 2017, 2019, and 2022` -> `X64`.

**Comment by jcfr** [comment]
@bratmody11  Thanks for reporting the issue. Installing specific packages should not be required.

We should address this in the upcoming patch release `5.0.3`

For additional context:

* CMake 3.22.1 is used to build and package 

* Relevant CMake module is [InstallRequiredSystemLibraries](https://cmake.org/cmake/help/latest/module/InstallRequiredSystemLibraries.html)

* The module `InstallRequiredSystemLibraries` is used in the Slicer build-system at [CMake/SlicerCPack.cmake#L154-L160](https://github.com/Slicer/Slicer/blob/80869f11bc507ddf60449014c3c11878cd4d9068/CMake/SlicerCPack.cmake#L154-L160)

* All latest patches to `InstallRequiredSystemLibraries` (See [here](https://github.com/Kitware/CMake/commits/master/Modules/InstallRequiredSystemLibraries.cmake)) seems to be available in `CMake 3.22.1`

**Comment by bratmody11** [comment]
Sir, I am using the older Windows 7 version. if possible since i am a user
not a researcher the older 4.10 and 4.11 version of slicer 3d was good
enough for my work. but now not available for download. please help me.

bharat m. mody
dental surgeon

**Comment by jcfr** [comment]
Could you confirm the following ?

* Slicer 4.10 and 4.11 on Window 7: 
   * Slicer can be installed and executed
   * There is crash when trying to use the application  (as indicated in the [issue description](https://github.com/Slicer/Slicer/issues/6393#issue-1249111862))

* Slicer 5.0.2 on Windows 7
   * Slicer can *NOT* be started and instead display an error dialog indicating that `api-ms-win-core-path-l1-1-0.dll` is missing 


Since Window 7 support ended in January 2020 and that version will not receive security fixes, we recommend that you update your system. See https://www.microsoft.com/en-gb/windows/windows-7-end-of-life-support-information

[This discussion](https://superuser.com/questions/1660386/api-ms-win-core-path-l1-1-0-dll-is-missing-from-your-computer/1660401#1660401) also mentions that starting with Python 3.9, support for Window 7 was dropped. This means that since Slicer 5.0 bundles Python 3.9.10, having a fully functional application on windows 7 is not supported.

**Comment by bratmody11** [comment]
No, it does not. Actually 4.10 and 4.11 used to work fine while updating it
was removed. Sorry for not being clear. Now those versions are not
available so cannot download and use. Yes but if i get those i do not need
the latest version as I said I am a simple user
I would love to be able to download and use the 4.10 and 4.11 if possible

Bharat Mody

**Comment by jamesobutler** [comment]
> Now those versions are not available so cannot download and use. 

Please see the following post on the forum about how to download older versions of Slicer. https://discourse.slicer.org/t/older-versions-of-3d-slicer/23378/2

**Comment by jcfr** [comment]
> Yes but if i get those i do not need
the latest version as I said I am a simple user

This makes sense and we will be doing our best to provide answer enabling you to move forward.

Let us know if the answer shared by @jamesobutler is helpful and if yes, we will close this issue.

**Comment by lassoan** [comment]
> I am a simple user I would love to be able to download and use the 4.10 and 4.11 if possible

If you use  your Windows7 computer to access the internet (email, web browsing) then I would strongly recommend to disconnect immediately, as you expose your computer (and all other computers on your network) to very high risk of data theft. Just by receiving an email or opening a website, you can give attackers full access to your computer and all files on it. The main motivation for upgrading your computer should not be to run Slicer but to avoid this very high risk of exposing all your data on the internet.

**Comment by bratmody11** [comment]
ok thanks. i will try.
