### ISSUE TITLE
Crash in slice view showing markups and interactive slice intersections

### ISSUE THREAD

**Issue by januszhu707** [Slicer/Slicer#6400]
Errors are easy to find:

1. Open any CT

2. Open the measuring ruler, and then measure several more, such as 1-2

3. Open interaction

4. Drag line (cross line)

5. Stuck
--------------------------
System:win10, slicer-2022-05-28
-------------------------------------------------------
Snap images:
 
![image](https://user-images.githubusercontent.com/105405296/170873991-ecf94dce-aa5e-4eb3-96f1-c8ee08c75411.png)

![image](https://user-images.githubusercontent.com/105405296/170873863-c5e58593-b83d-4432-b666-9c36e7968b5b.png)

**Comment by lassoan** [comment]
Thank you for the detailed error report. Based on this information I was able to reproduce and fix the issue.
The fix will be available in the Slicer Preview Release from tomorrow.

**Comment by cpinter** [comment]
Thank you both!
