### ISSUE TITLE
vtkMRMLSequenceNode::Copy not working on trimmed sequences

### ISSUE THREAD

**Issue by matthewsholden** [Slicer/Slicer#6435]
## Summary

The vtkMRMLSequenceNode::Copy method does not correctly copy sequences after the RemoveDataNodeAtValue function has been used to remove data nodes from the beginning of the sequence.

## Steps to reproduce

1. Create a new LinearTransform in the Transforms module (for example).
2. Create a new sequence node in the Sequences module.
3. Add the LinearTransform as a data node to the sequence (will be added at index value 0).
4. Add the LinearTransform as a data node to the sequence (will be added at index value 1).
5. Remove the data node at index value 1 from the sequence.
6. Use the commands below to copy the sequence.
7. Inspect the copied sequence in the Sequences module (it will have one entry in it, but both the index value and data node will be empty).

```
trimmedSequence = slicer.mrmlScene.GetNodeByID("vtkMRMLSequenceNode1") # The sequence you just created
copySequence = slicer.vtkMRMLSequenceNode()
copySequence.Copy(trimmedSequence)
slicer.mrmlScene.AddNode(copySequence)
```

## Expected behavior

The copied sequence should contain one entry with index value 1, and the data node should be the LinearTransform.

## Environment
- Slicer version: Slicer-5.1.0-2022-06-15
- Operating system: Windows 10

My initial impression is that this may be due to an assumption in the Copy function that the data nodes in the original sequence and the copied sequence are assumed to have the same IDs in their respective SequenceScenes, but this is not always the case, including when a sequence has been trimmed at the beginning. See: https://github.com/Slicer/Slicer/blob/eb82cc0e2a104043dbdb6ad5c042aa4104f3e9ed/Libs/MRML/Core/vtkMRMLSequenceNode.cxx#L270

**Comment by lassoan** [comment]
Thanks for the detailed report, it is very helpful. When I followed the exact instructions I could not reproduce the issue, but when I deleted data node at index 0 (instead of at index 1 - as it was suggested in the instructions) then I saw the error. I've created a tentative fix:

https://github.com/Slicer/Slicer/commit/aedbf502d7ea2b6d2ebbc28fccc7a7748ac20e30

Could you test if it fixes the issue for you?

**Comment by matthewsholden** [comment]
Thanks very much, @lassoan. Yes, I meant to write "delete the data node at index 0".

Will test the fix shortly.

**Comment by dgmato** [comment]
I tested the fix and I was able to copy trimmed sequences successfully. Thanks @lassoan
