### ISSUE TITLE
Invalid error from vtk causes vtp file not to load

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#6447]
## Summary

A file that loads in slicer 4.11 does not load in 5.x due to invalid logic in Slicer and VTK.

## Steps to reproduce

The attached zip file contains a vtp file that has no points.  This is a valid file that is used in SlicerDMRI to indicate that no data was detected for the brain region that the file corresponds to (this is part of the [WhiteMatterAnalysis](https://github.com/SlicerDMRI/whitematteranalysis) pipeline).  The convention has been used for many years with no problem across several versions of Slicer and VTK.

Now when you try to load as a model (or fiber bundle with SlicerDMRI installed) you get an error:

![image](https://user-images.githubusercontent.com/126077/175128238-c30fb1d3-3a3b-48e0-b30f-eaf6cf19ea2a.png)

The full text is:

```
- Error: Loading /opt/data/SlicerDMRI/vtk9-fail-T_Sup-O_right.vtp - ERROR: In /opt/s/VTK/IO/XML/vtkXMLUnstructuredDataReader.cxx, line 393
vtkXMLPolyDataReader (0x7fe30b116e30): No Points element available in first piece found in file. Reading file may fail.
- Error: Loading /opt/data/SlicerDMRI/vtk9-fail-T_Sup-O_right.vtp - Failed to read node vtk9-fail-T_Sup-O_right_2 (vtkMRMLModelNode6) from filename='/opt/data/SlicerDMRI/vtk9-fail-T_Sup-O_right.vtp'
```

But this is a false negative generated by the catching the `vtkErrorMacro` events in [this PR](https://github.com/Slicer/Slicer/commit/517ded4fd4fb6e69c48b042bc7ade36fadf0f29f).  The underlying problem is that `vtkXMLPolyDataReader` uses `vtkErrorMacro` where it should be using `vtkWarningMacro`.  It was added in [this commit](https://github.com/Kitware/VTK/commit/7f768465185b4dbe04ab23de0a7a6034db4a2e61}.

Another problem that should be addressed is that the contents of the `vtkErrorMacro` string are only reported in the gui and do not get printed to stdout/stderr, meaning that they are not part of any log files generated when using a call like `slicer.util.loadModel` in a script.

## Expected behavior

1. The vtp file should be loaded as an empty file for consistency with earlier versions of Slicer.
2. The strings from any `vtkErrorMacros` should be written to output and not swallowed by the GUI.

## Environment
- Slicer version: Slicer-5.0.2
- Operating system: All

## Notes
This test confirms that the data loads correctly in Slicer5, with the warning about the missing points printed to the console.
```
>>> r = vtk.vtkXMLPolyDataReader()
>>> r.SetFileName("/opt/data/SlicerDMRI/slicer5-fail-T_Sup-O_right.vtp")
>>> r.Update()
>>> print(r.GetOutput())
(omit print of valid empty vtkPolyData)
```

[slicer5-fail-T_Sup-O_right.vtp.zip](https://github.com/Slicer/Slicer/files/8961006/slicer5-fail-T_Sup-O_right.vtp.zip)

**Comment by pieper** [comment]
Confirmed that changing to `vtkWarningMacro` allows the data to load as it did in previous versions.  I will generate a gitlab merge request to the upstream VTK, but in the meantime we should probably also just patch this in the Slicer/VTK fork.

Not that the warning message generated when loading is completely swallowed now (it is captured by the GUI and does not appear in the stdout so potentially important debugging information is being lost).

I'll also try to look into fixing these missing warning/error messages when I have a chance.

**Comment by lassoan** [comment]
> We do need to fix more than just slicer.util.loadNodeFromFile for the reasons listed above but better warning/error reporting at the python level s a great start.

Boolean result (success/fail) and detailed error messages are returned at all levels (except in slicer.util.loadNodes which indeed swallowed the details and had no API to return them). It is up to the caller to decide what to do with the detailed information (discard it, log it, print it, etc.). Warning messages are collected, too, do even if the reading returns with success, the warning may be logged.

**Comment by pieper** [comment]
Even though I don't know if/when it will be accepted I created a VTK MR: https://gitlab.kitware.com/vtk/vtk/-/commit/7f768465185b4dbe04ab23de0a7a6034db4a2e61

I'll look a bit more to see what we can do at the Slicer level to re-enable loading of these files.

**Comment by lassoan** [comment]
> I'll look a bit more to see what we can do at the Slicer level to re-enable loading of these files.

In the vtkMRMLMessageCollection class you could add a methods to make it easy to find and remove or re-classify certain messages. You could then use them to find the error message and downgrade it to a warning.

**Comment by pieper** [comment]
> add a methods to make it easy to find and remove or re-classify certain messages

Yes, that would be workaround.  I'm torn though, since cherrypicking the change from VTK would in some ways be cleaner.

@jcfr how much maintenance effort does it add the MR above to the Slicer/VTK repo?

**Comment by jcfr** [comment]
Cherry picking is straightforward. Thanks for the MR in upstream VTK 🙏

**Comment by lassoan** [comment]
Merge request has not been integrated into VTK:

https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9314

**Comment by jcfr** [comment]
A new merge request was pushed as `MR-9648`[^1] and I just rebased it against the release branch for VTK `9.3`.

[^1]: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9648
