### ISSUE TITLE
FAST MARCHING EFFECT

### ISSUE THREAD

**Issue by orukundo** [Slicer/Slicer#6462]
How can I access/use the FAST MARCHING effect or Button in the 3D slicer version 5.0.1 or 5.0.2 ?

**Comment by lassoan** [comment]
Fast marching effect is available in the Segment Editor module after installing SegmentEditorExtraEffects extension.

Note that github issues are for tracking confirmed problems and planned developments of Slicer core. Please post questions about how to use Slicer to https://discourse.slicer.org
