### ISSUE TITLE
Saving MRB into a root directory causes a crash

### ISSUE THREAD

**Issue by Sunderlandkyl** [Slicer/Slicer#6470]
## Summary

Saving an MRB into a root directory will cause a crash.

<details><summary>Stack trace</summary>
<pre>
>	archive.dll!__archive_write_filter(archive_write_filter * f, const void * buff, unsigned __int64 length) Line 233	C
 	archive.dll!archive_write_zip_close(archive_write * a) Line 1343	C
 	archive.dll!_archive_write_close(archive * _a) Line 615	C
 	MRMLCore.dll!vtkArchive::Zip(const char * zipFileName, const char * directoryToZip) Line 491	C++
 	MRMLCore.dll!vtkMRMLScene::WriteToMRB(const char * filename, vtkImageData * thumbnail, vtkMRMLMessageCollection * userMessages) Line 3905	C++
 	qSlicerDataModule.dll!qSlicerSceneWriter::writeToMRB(const QMap<QString,QVariant> & properties) Line 190	C++
 	qSlicerDataModule.dll!qSlicerSceneWriter::write(const QMap<QString,QVariant> & properties) Line 112	C++
 	qSlicerBaseQTCore.dll!qSlicerCoreIOManager::saveNodes(QString fileType, const QMap<QString,QVariant> & parameters, vtkMRMLMessageCollection * userMessages, vtkMRMLScene * scene) Line 796	C++
 	qSlicerBaseQTCore.dll!qSlicerCoreIOManager::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 488	C++
 	qSlicerBaseQTCore.dll!qSlicerCoreIOManager::qt_metacall(QMetaObject::Call _c, int _id, void * * _a) Line 521	C++
 	qSlicerBaseQTGUI.dll!qSlicerIOManager::qt_metacall(QMetaObject::Call _c, int _id, void * * _a) Line 309	C++
 	PythonQt.dll!PythonQtSlotInfo::invokeQtMethod(QObject * obj, PythonQtSlotInfo * slot, void * * args) Line 651	C++
 	PythonQt.dll!PythonQtCallSlot(PythonQtClassInfo * classInfo, QObject * objectToCall, _object * args, bool strict, PythonQtSlotInfo * info, void * firstArgument, _object * * pythonReturnValue, void * * directReturnValuePointer, PythonQtPassThisOwnershipType * passThisOwnershipToCPP) Line 172	C++
 	PythonQt.dll!PythonQtSlotFunction_CallImpl(PythonQtClassInfo * classInfo, QObject * objectToCall, PythonQtSlotInfo * info, _object * args, _object * kw, void * firstArg, void * * directReturnValuePointer, PythonQtPassThisOwnershipType * passThisOwnershipToCPP) Line 402	C++
 	PythonQt.dll!PythonQtMemberFunction_Call(PythonQtSlotInfo * info, _object * m_self, _object * args, _object * kw) Line 277	C++
 	[External Code]	
 	CTKScriptingPythonWidgets.dll!ctkPythonConsolePrivate::push(const QString & code) Line 564	C++
 	CTKScriptingPythonWidgets.dll!ctkPythonConsole::executeCommand(const QString & command) Line 700	C++
 	CTKWidgets.dll!ctkConsolePrivate::internalExecuteCommand() Line 806	C++
 	CTKWidgets.dll!ctkConsolePrivate::keyPressEvent(QKeyEvent * e) Line 524	C++
 	[External Code]	
 	qSlicerBaseQTGUI.dll!qSlicerApplication::notify(QObject * receiver, QEvent * event) Line 426	C++
 	[External Code]	
 	qSlicerBaseQTGUI.dll!qSlicerApplication::notify(QObject * receiver, QEvent * event) Line 426	C++
 	[External Code]	
 	qSlicerBaseQTCore.dll!qSlicerCoreApplication::exec() Line 929	C++
 	SlicerApp-real.exe!`anonymous namespace'::SlicerAppMain(int argc, char * * argv) Line 62	C++
 	[External Code]		
</pre>
</details>

The issue exists in the latest nightly/stable on Windows. I haven't tested Linux or Mac.
It happens at least as far back as 4.10.2.

## Steps to reproduce

- Crashes:
saveScene("C:/scene.mrb")

- Doesn't crash:
saveScene("C:/dir/scene.mrb")

## Environment
- Slicer version: Slicer-4.10.2+
- Operating system: Windows

**Comment by lassoan** [comment]
Thanks for reporting, I'll take care of this within a few days
