### ISSUE TITLE
Endoscopy jitters a bit

### ISSUE THREAD

**Issue by mauigna06** [Slicer/Slicer#6476]
## Summary

While using the endoscopy module for a given path curve when it's playing you can see the camera jitter a bit

## Steps to reproduce

A complex enough path (with enough torsion)

## Expected behavior

Camera doesn't jitter a bit

## Environment
- Slicer version: Slicer-5.1.0-2022-07-20
- Operating system: Windows 10

**Comment by lassoan** [comment]
Closing this issue, as the underlying algorithm did not end up integrated and resampling the curve in markups module can be used to remove jitter.
