### ISSUE TITLE
SubjectHierarchyTreeView firing currentItemChanged twice

### ISSUE THREAD

**Issue by fbordignon** [Slicer/Slicer#6486]
The SubjectHierarchyTreeView currentItemChanged is firing twice when clicking to select one item (without ctrl+click) I presume it is because it is calling one time when clearing the selection and another when selecting the new item. The problem is that both times the itemIDs are the same:

```python
dataWidget = slicer.modules.data.widgetRepresentation()
sh = dataWidget.findChild(qt.QObject, "SubjectHierarchyTreeView")
def currentItemChanged( itemID):
  print(itemID)

sh.currentItemChanged.connect(currentItemChanged)
```
This yields two prints every time the user clicks on a item without ctrl+click
![image](https://user-images.githubusercontent.com/4790289/181817384-0fb1b6ed-eea6-4702-8fe7-f67aa79b9897.png)

Additionally currentItem**s**Changed argument does not seem to work as it always prints none:
```python
dataWidget = slicer.modules.data.widgetRepresentation()
sh = dataWidget.findChild(qt.QObject, "SubjectHierarchyTreeView")
def currentItemChanged( itemID):
  print(itemID)

sh.currentItemsChanged.connect(currentItemChanged)
```

![image](https://user-images.githubusercontent.com/4790289/181817812-e5744bea-de9f-4bb0-b17c-59ffa88e6405.png)

**Comment by lassoan** [comment]
Thanks for reporting. Based on your description it is easy to reproduce the issue.

Since the extra signal should not cause any problem (other than potentially triggering some unnecessary updates), I don't think we'll work on it right away, but only when this part of code needs to be touched for some reason.

**Comment by fbordignon** [comment]
It seems that it is fixed now, perhaps via 91acebfd62550dcd90a0c40917fec4b73195d7de
Which is 1 day after the revision I tested 🤯

**Comment by fbordignon** [comment]
Well, at least the double firing, is fixed. The second problem is still present. The list of changed itens always returns None for currentItemsChanged

**Comment by lassoan** [comment]
PythonQt cannot wrap `QList<vtkIdType>` (probably because Qt does not know `vtkIdType`), so the signal will always return `None`. But you can retrieve the list of selected IDs in the callback:

```python
ids=vtk.vtkIdList()
sh.currentItems(ids)
print(ids.GetNumberOfIds()
print(ids.GetId(0))
print(ids.GetId(1))
```
