### ISSUE TITLE
Could not initialize GLX

### ISSUE THREAD

**Issue by TYYTao** [Slicer/Slicer#6509]
## Summary

After I installed 3dslicer, I tried to start it, but only a pop-up window appeared, and then it disappeared, and then an error message appeared.

## Steps to reproduce

A brief pop-up window：
![image](https://user-images.githubusercontent.com/111364191/186151724-4dc43581-6d2a-4dbe-bfd3-175b3786aab7.png)

Contents of error report：
![image](https://user-images.githubusercontent.com/111364191/186152193-ed765d5e-1264-4b2a-be51-5ca89926c0e1.png)

## Environment
- Slicer version: Slicer-5.0.3
- Operating system: Linux
- 
![image](https://user-images.githubusercontent.com/111364191/186151331-cd315c97-9f5e-49db-be47-290995d7c835.png)

**Comment by pieper** [comment]
Make sure your computer [meets the system requirements](https://slicer.readthedocs.io/en/latest/user_guide/getting_started.html#system-requirements).  GLX on linux can be tricky to install so I doubt this is a Slicer-specific issue.  If other programs run well (i.e. glxgears and blender) but Slicer doesn't then reopen this issue with more details about your os version, graphics card, and what you have done to debug.
