### ISSUE TITLE
Disclosure Arrows not working in the Favorite Modules Section of Settings

### ISSUE THREAD

**Issue by HarryDC** [Slicer/Slicer#6511]
## Summary

When clicking on the arrows to the right hand side of the Favorite Modules section in "Settings/Modules" the view to the left of the arrows stays visible. The start state for the arrows indicates that the view should be hidden, but it isn't 

![image](https://user-images.githubusercontent.com/1878111/186173350-39f3be1a-7e4b-4cb6-9df1-199aeafab4f6.png)
![image](https://user-images.githubusercontent.com/1878111/186173449-14e65eaf-3130-49af-a993-5d65a283eeef.png)

## Steps to reproduce

- Navigate to "Application Settings/Module" 
- click on the ">>" arrows in the "Favorite Modules" section
- The interface to the right doesn't change

## Expected behavior

- The view with the "Remove" button and the left and right arrows should disappear
- Looking at the state of the arrows at first open ">>" the view should be hidden at first (or the state be set to "<<")

## Environment
- Slicer version: Slicer-5.1.0-2022-08-11 r31107
- Operating system: Windows 10

**Comment by lassoan** [comment]
Thanks for reporting, fix and additional improvements are available in the PR #6513 and expected to be merged into Slicer Preview Release within a few days.
