### ISSUE TITLE
Extension Manager non-functional in Linux

### ISSUE THREAD

**Issue by smr99** [Slicer/Slicer#6534]
## Summary

I opened the Extensions Manager but no extensions are shown.  This is the behaviour on Linux with Slicer versions 5.0.3 and (preview version 5.1.0).  Extension Manager works fine on Windows.

## Environment
- Slicer version: Slicer-5.0.3-linux-amd64
 and Slicer-5.1.0-2022-09-15-linux-amd64

- Operating system: Linux Debian (sid)

**Comment by lassoan** [comment]
See troubleshooting instructions here: https://slicer.readthedocs.io/en/latest/user_guide/extensions_manager.html#troubleshooting

**Comment by smr99** [comment]
Thank you!  It was the linux sandboxing one.  Works after disabling sandbox.
