### ISSUE TITLE
Unexpected behaviour in  extension manager, new extension not loading

### ISSUE THREAD

**Issue by manishdhakal** [Slicer/Slicer#6538]
### Setup
- ArchLinux OS
- Slicer 5.0.3

After opening extensions manager, in the **Install Extensions** tab I see **100%** prompt message at the bottom, but no new extensions are seen inside the tab.

## Problem

![image](https://user-images.githubusercontent.com/36515191/190916444-6bcc3a6d-427b-41ce-bc35-01848bcc33c9.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/36515191/190916483-44304ff6-2104-4c16-a519-c08b18e4e4ce.png)

## Environment
- Slicer version: Slicer-5.0.3-2022-07-08
- Operating system: ArchLinux

**Comment by jamesobutler** [comment]
This a duplicate of #6534.

> See troubleshooting instructions here: https://slicer.readthedocs.io/en/latest/user_guide/extensions_manager.html#troubleshooting


Also see https://discourse.slicer.org/t/extension-manager-in-linux-empty/22343/8?u=jamesobutler for more details. The discourse forum is an excellent place to ask usage questions about potential issues and also a good resource to find if others have faced the similar issue as you.

**Comment by lassoan** [comment]
For each error report there are probably dozens of cases where users experience the issue and don't tell us about it. So, this may be a pretty widespread problem on Linux.

@pieper @jcfr Should we add this browser sandboxing environment variable to the Linux launcher?

**Comment by pieper** [comment]
> Should we add this browser sandboxing environment variable to the Linux launcher?

If I understand the issue correctly there's some security implication of setting this flag so we might want to detect this situation and only set the flag if needed.  On the other hand I'm sure if it's a significant security issue in the scheme of things.

**Comment by lassoan** [comment]
There are so many reasons (proxy servers, browser sandboxing, etc.) that may cause the web frontend to not be able to connect to the girder backend that probably the best would be to detect this in the frontend and instead of displaying an empty page, show an error message with a link to the extensions manager FAQ.

I reopen the issue to keep track of this discussion.

**Comment by lassoan** [comment]
Fixed in https://github.com/Slicer/Slicer/commit/7960e2d288f3f96aca7b994e3fe8cf9928cc848f by disabling browser sandboxing on linux.
