### ISSUE TITLE
Segmentation Node slow to write temp nrrd input for CLI module

### ISSUE THREAD

**Issue by fbordignon** [Slicer/Slicer#6555]
Hello all, I have a python CLI that can receive a labelmap or a segmentation node as input. In my case, the segmentation node is around 120MB on disk, if I convert it to a labelmap, it ends up being 5GB because of the size of the reference volume (1300^3). The funny thing is that if I use the segmentation node via command line, it takes more than one minute to write the segmentation node to the temp .nrrd whereas if I use the labelmap, it takes 4 seconds.

I know that segmentation nodes are not on the image type list of the XML schema, but it sort of works and in this case it should be more advantageous to use the segmentation because of the size.

Example just to compare the time it takes to initialize the cli:
Create a big volume of 1000x1000x1000 voxels and segment it in anyway.
```python
a = getNode("Segmentation")
b = getNode("Segmentation_1")
cliParams = {
"inputVolume1": a.GetID(),
"inputVolume2": a.GetID(),
"outputVolume": b.GetID(),
}
cliNode = slicer.cli.run(slicer.modules.addscalarvolumes, None, cliParams)
```
Takes 1 minute to write the segmentation node of 120MB and start the AddScalarVolumes executable.

On the other hand if I convert the segmentations to labelmaps and do:
```python
a = getNode("Segmentation-label")
b = getNode("Segmentation_1-label")
cliParams = {
"inputVolume1": a.GetID(),
"inputVolume2": a.GetID(),
"outputVolume": b.GetID(),
}
cliNode = slicer.cli.run(slicer.modules.addscalarvolumes, None, cliParams)
```
Takes 4 seconds to write the labelmap volume of 5GB to disk. The reference volume I am using has more or less 1300^3 voxels in this case. While writing the segmentation node, the disk utilization is minimal, whereas for the labelmap it is on 80% for the 4 seconds it takes.

Tested on latest slicer build on windows 10 pro
version 5.1.0
revision 31161
built 2022-09-28

I appreciate any tips and/or indication of what I am doing wrong. If it is not a bug, please relabel it.

**Comment by lassoan** [comment]
In the segmentation node's storage node you can choose to export with the minimum necessary extents. If you only segmented a small part of the volume then this option should drastically decrease the saving time.

Disabling compression in the storage node can also make saving 1-2 magnitudes faster.

**Comment by lassoan** [comment]
I've updated the CLI infrastructure to allow using segmentation as input and output wherever labelmap volume is accepted (see #6558).

Fast saving of segmentation nodes (by disabling compression and padding) may be a topic of interest but not specific to using segmentations as CLI module inputs/outputs, so I'm closing this issue now. If you want to continue a discussion on segmentation node saving speed then you can start a discussion on the Slicer forum.

**Comment by fbordignon** [comment]
Thanks, @lassoan. As the segmentation node was not supported by the CLI I was thinking it was something related to it, but you are right. I will take a look at the performance of the segmentation node writer.
