### ISSUE TITLE
DICOM previews are stretched

### ISSUE THREAD

**Issue by joshstovall** [Slicer/Slicer#6560]
## Summary

DICOM previews are stretched in the bottom two views after loading them in.  I can fix this somewhat by going to Volumes mode and editing the values, however no matter what I do, the preview is stretched like this.  Is this a known error?  It seems to happen regardless of the DICOMs I upload or machine I use (various Linux distros). Does anyone know why this maybe happening? Thanks for the help.

![image](https://user-images.githubusercontent.com/40344766/193703848-cb70ef60-b561-4d14-a201-253f69c37de9.png)

## Expected behavior

DICOM preview should not be stretched.

## Environment
- Slicer version: Slicer-5.0.3.30893-2022-07-08
- Operating system: Linux

**Comment by jamesobutler** [comment]
Hi @joshstovall, are you using the DICOM module to load your DICOM data? Please read https://discourse.slicer.org/t/merging-different-dicom-files-together/4345/11 and let us know if that is helpful. 

Also see https://discourse.slicer.org/t/dicom-too-large-and-upside-down/19054/2 which xrefs #5726.

**Comment by pieper** [comment]
Thanks for reporting but these images do not look wrong to me.  If after more research you disagree, please provide more detail and information to reproduce and reopen the issue.

**Comment by joshstovall** [comment]
It looks very odd to me, but maybe I am missing something. I guess I don't quite understand what I am looking at in the bottom two squares. I've tried a few other DICOM cases that work better, but are still somewhat stretched. I am new to using Slicer. But I appreciate the comments! I'll keep playing around with it. Thank you!

**Comment by pieper** [comment]
Yes, experiment more and see if you find any issues.  DICOM files are complex and weird enough that I'm sure there are cases that don't work, but this case looks to me like a slab that is correctly rendered.
