### ISSUE TITLE
Extensions build errors in Slicer-5.1 due to dependency updates

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#6587]
Several extensions fail to build, mostly due to recent ITK and VTK updates. These build errors have to be fixed before releasing Slicer-5.2.

- [x] BoneTextureExtension https://github.com/Kitware/BoneTextureExtension
  * Fixed in https://github.com/Slicer/Slicer/pull/6645
- [x] SlicerITKUltrasound https://github.com/KitwareMedical/SlicerITKUltrasound
  * Fixed in https://github.com/Slicer/Slicer/pull/6645
- [x] SlicerOpenCV https://github.com/Slicer/SlicerOpenCV
  * See https://github.com/Slicer/SlicerOpenCV/pull/77
  * See https://github.com/Slicer/SlicerOpenCV/pull/78
- [x] PBNRR https://github.com/aangelos28/PBNRR
  * Fixed in https://github.com/Slicer/Slicer/pull/6645
- [x] Chest Imaging Platform https://github.com/acil-bwh/SlicerCIP
  * Fixed in 
    * https://github.com/acil-bwh/SlicerCIP/commit/dd9b876f9d7eb53cbc115769d8acf7bb2d87f41b
    * https://github.com/Slicer/ChestImagingPlatform/commit/7b06fcb39b4f5bfbe56ee8a4cf258cd94330bc70
    * https://github.com/Slicer/ChestImagingPlatform/commit/7b06fcb39b4f5bfbe56ee8a4cf258cd94330bc70
  * https://github.com/acil-bwh/ChestImagingPlatform/pull/46)
- [x] SPHARM-PDM https://github.com/NIRALUser/SPHARM-PDM
  * Fixed in https://github.com/NIRALUser/SPHARM-PDM/pull/79
- [x] SlicerLookingGlass https://github.com/KitwareMedical/SlicerLookingGlass
  * Fixed in https://github.com/KitwareMedical/SlicerLookingGlass/pull/26

**Comment by jamesobutler** [comment]
I've added a checklist in the original post of the extensions failing to build as of https://slicer.cdash.org/index.php?project=SlicerPreview&date=2022-10-21

**Comment by jcfr** [comment]
Re: SpharmPdm
-> add `itkConfigure.h` to faulty cxx (including `itkNamespace.h` would be sufficient but would break possibility to build project standalone)

Re: CIP
-> same as above

**Comment by lassoan** [comment]
I've switched CIP to use our Slicer fork and merged the change. Local build on Windows succeeded. Hopefully there will be no build errors on the dashboard from tomorrow.

SPHARM-PDM pull request is still has not been merged.

**Comment by jcfr** [comment]
> SPHARM-PDM pull request is still has not been merged.

The `SPHARM-PDM` extension is now available for download:
* https://slicer.cdash.org/index.php?project=SlicerPreview&date=2022-10-31&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=SPHARM
* Linux: https://extensions.slicer.org/catalog/All/31255/linux?q=SPHARM-PDM
* macOS: https://extensions.slicer.org/catalog/All/31255/macosx?q=SPHARM-PDM
* Windows: https://extensions.slicer.org/catalog/All/31255/win?q=SPHARM-PDM

**Comment by jcfr** [comment]
> Chest Imaging Platform

The `Chest Imaging Platform` extension is now available for download:

* CDash: https://slicer.cdash.org/index.php?project=SlicerPreview&date=2022-10-31&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=Chest
* Linux: https://extensions.slicer.org/catalog/All/31255/linux?q=Chest_Imaging_Platform
* macOS: https://extensions.slicer.org/catalog/All/31255/macosx?q=Chest_Imaging_Platform
* Windows: https://extensions.slicer.org/catalog/All/31255/win?q=Chest_Imaging_Platform

**Comment by lassoan** [comment]
The only remaining extensions that are failing are:
- OpenCV has build errors on all platforms:
  - no real error is reported, only a distutils deprecation warning `<string>:1: DeprecationWarning: ` - not sure why it is reported as an error
  - Maybe the real error is that `PythonInterp` is not found? On [Windows](https://slicer.cdash.org/build/2850222) it is not found at all. On [macOS](https://slicer.cdash.org/build/2850556) and [Linux](https://slicer.cdash.org/build/2849931) some Python-2.7 version is found.
- [SlicerLookingGlass has build errors on macOS](https://slicer.cdash.org/viewBuildError.php?buildid=2850551): `Error copying file "@rpath/libHoloPlayCore.dylib" to "/.../SlicerLookingGlass-build/inner-build/_CPack_Packages/Darwin/TGZ/31273-macosx-amd64-SlicerLookingGlass-gitbd9fec8-2022-11-01/Slicer.app/Contents/Extensions-31273/SlicerLookingGlass/lib/Slicer-5.1/libHoloPlayCore.dylib".`

**Comment by jcfr** [comment]
> SlicerLookingGlass has build errors on macOS

This has been fixed in https://github.com/KitwareMedical/SlicerLookingGlass/pull/26

**Comment by jcfr** [comment]
> OpenCV has build errors on all platforms

Currently looking into this.
