### ISSUE TITLE
Move vtkCurveGenerator from Libs/MRML to vtkAddon

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#6603]
## Is your feature request related to a problem? Please describe.

Support use of `vtkCurveGenerator` outside of Slicer. This is will allow to move forward with https://github.com/BICCN/cell-locator/pull/215

## Describe the solution you'd like

* [x] Relocate the class from [Modules/Loadable/Markups/MRML](https://github.com/Slicer/Slicer/blob/main/Modules/Loadable/Markups/MRML/vtkCurveGenerator.h) to [vtkAddon](https://github.com/slicer/vtkAddon) repository and update Slicer accordingly.
* [x] Review Slicer extensions to check if the class is directly used (this can be done using `fgrep` on the `metroplex` factory)

## Describe alternatives you've considered

NA

## Additional context

* https://github.com/BICCN/cell-locator/pull/215

**Comment by jcfr** [comment]
> Review Slicer extensions to check if the class is directly used

```bash
$ cd /home/kitware/Dashboards/Slicer/Preview/S-0-E-b
$ fgrep -irnsI -F "\"vtkCurveGenerator.h"  .
./MarkupsToModel/MarkupsToModel/Logic/vtkSlicerMarkupsToModelLogic.cxx:21:#include "vtkCurveGenerator.h"
```

```bash
$ cd /home/kitware/Dashboards/Slicer/Preview/S-0-E-b
$ fgrep -irnsI -F "<vtkCurveGenerator.h"  .
./SlicerFreeSurfer/FreeSurferImporter/Logic/vtkSlicerFreeSurferImporterLogic.cxx:34:#include <vtkCurveGenerator.h>
./SlicerFreeSurfer/FreeSurferImporter/MRML/vtkFreeSurferCurveGenerator.h:25:#include <vtkCurveGenerator.h>
./SlicerFreeSurfer/FreeSurferMarkups/MRML/vtkFreeSurferCurveGenerator.h:25:#include <vtkCurveGenerator.h>
```

**Comment by jcfr** [comment]
Impacted extensions:
* https://github.com/PerkLab/SlicerFreeSurfer
* https://github.com/SlicerIGT/SlicerMarkupsToModel

Since the integration of the class `vtkCurveGenerator` is done through the target `vtkSlicerMarkupsModuleMRML` itself depending on `MRMLCore` that itself depends on `vtkAddon`, implementing this change may not require any changes to extensions.

That said, for sake of being explicit and avoid future unwanted side effect due to refactoring. `vtkAddon` target should still be explicitly added to these files:
* [ ] https://github.com/SlicerIGT/SlicerMarkupsToModel/blob/835453f30c0da005853d5175aa8980928da5cd49/MarkupsToModel/Logic/CMakeLists.txt#L17-L22
* [ ] https://github.com/PerkLab/SlicerFreeSurfer/blob/2d2812392d63461893556137c8f234c501f15f09/FreeSurferMarkups/MRML/CMakeLists.txt#L20-L24
* [ ] https://github.com/PerkLab/SlicerFreeSurfer/blob/8864db903fc34c3e1ed8bf1f27436c7cf438f896/FreeSurferImporter/Logic/CMakeLists.txt#L19-L24
* [ ] https://github.com/PerkLab/SlicerFreeSurfer/blob/8864db903fc34c3e1ed8bf1f27436c7cf438f896/FreeSurferImporter/MRML/CMakeLists.txt#L20-L23

**Comment by lassoan** [comment]
This could be useful, especially if vtkAddon is available as a Python package on PyPI. Is that the plan?

**Comment by allemangD** [comment]
Yes; we are building a python-only tool for Cell Locator that loads markups. Once vtkCurveGenerator is available via the vtkAddon python bindings we would be able to publish that tool on PyPI.

Currently we are launching the tool via `Slicer --python-script ...` and importing `slicer.vtkCurveGenerator`.
