### ISSUE TITLE
VTKObservationMixin observers not removed if object reference is not kept in Python

### ISSUE THREAD

**Issue by Sunderlandkyl** [Slicer/Slicer#6610]
## Summary

If an observer is attached to an object (MRML node) through VTKObservationMixin, and a reference to the object is not kept in Python, then the observer will automatically be garbage collected from the WeakKeyDictionary even if the VTK object still exists. This means the observer cannot be removed with removeObserver()/removeObservers().

## Steps to reproduce

Run the following script in the Python interactor:
```python
v = VTKObservationMixin()
v.addObserver(getNode("Camera"), vtk.vtkCommand.ModifiedEvent, lambda caller, event : print("CameraModified"))
getNode("Camera").Modified() # "CameraModified expected -- OK"
v.removeObservers()
getNode("Camera").Modified() # "CameraModified not expected -- Error"
```

The same issue does not occur if a reference is kept in Python:
```python
c = getNode("Camera")
v = VTKObservationMixin()
v.addObserver(c, vtk.vtkCommand.ModifiedEvent, lambda caller, event : print("CameraModified"))
c.Modified() # "CameraModified expected -- OK"
v.removeObservers()
c.Modified() # "CameraModified not expected -- OK"
```

## Expected behavior

Observers should not be garbage collected for MRML nodes that are still in the scene.

## Environment
- Slicer version: Slicer-5.0.3 / 5.1.0-2022-10-21
- Operating system: Windows

**Comment by jcfr** [comment]
May be potentially related to https://github.com/Slicer/Slicer/commit/1e6d0685e40e7bdeb409a15425d1687a4b724bac addressing https://github.com/Slicer/Slicer/issues/6406 and introduced through https://github.com/Slicer/Slicer/pull/6409
