### ISSUE TITLE
Failed to load .hdr files 

### ISSUE THREAD

**Issue by shahrzad93** [Slicer/Slicer#6619]
## Summary

 I am not able to load hdr files in 3D slicer, while loading i am getting this error: error occurred while loading the selected files!

## Steps to reproduce

 I just wanted to liad data but i could not!  

## Expected behavior

I want to be able to load my hdr files.

## Environment
- Slicer version: Slicer-5.0.3
- Operating system: Windows 10

**Comment by lassoan** [comment]
It seems that it was due to not having the voxel data (.img file) available, only the header (.hdr). The images can be loaded correctly when both the .hdr and .img files are there. See https://discourse.slicer.org/t/failed-to-load-hdr-file/25912/18 for details.
