### ISSUE TITLE
Transform subject hierachy still visible

### ISSUE THREAD

**Issue by riep** [Slicer/Slicer#6621]
## Summary
The transfom subject hierarchy plugin is always visible even after having black listed it.

## Steps to reproduce
-In python terminal:
```
     dataModuleWidget = slicer.modules.data.widgetRepresentation()
     treeView = slicer.util.findChildren(dataModuleWidget, className='qMRMLSubjectHierarchyTreeView')[0]
     treeView.setPluginWhitelist([''])
```
-Load a volume 
-Go to the subject hierarchy tree of the data module
-Right click on the transform icon of a volume node loaded in the application. 
-Transform menu of the transform plugin is visible 

## Expected behavior
Nothing should be visible on the right click 

## Environment
- Slicer version: Slicer-5.0.3
- Operating system: Linux 20.04

**Comment by riep** [comment]
would you accept 
`      else if (sourceIndex.column() == this->model()->transformColumn())
        {
        vtkIdType itemID = d->SortFilterModel->subjectHierarchyItemFromIndex(index);
        if (itemID) // Valid item is needed for transform actions
          {
          foreach (qSlicerSubjectHierarchyAbstractPlugin *plugin, d->enabledPlugins())
            {
            QString pluginName = plugin->name();

            if (d->SelectedItems.size() > 0 && pluginName == "Transforms")
              {
              this->populateTransformContextMenuForItem(itemID);
              d->TransformMenu->exec(globalPoint);
              return;
              }
            }
          }
        }`

**Comment by lassoan** [comment]
Please send a pull request with the proposed change, that would make it much easier to review and test. Thank you!
