### ISSUE TITLE
Auto complete difficult to use with latest python console changes

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#6630]
## Summary

As originally discussed in https://discourse.slicer.org/t/problems-with-python-console-tab-completion/25965

## Steps to reproduce

Use `slicer.app.layoutManager().threeDWidget(index).[TAB]` as shown in the video below:

https://user-images.githubusercontent.com/15837524/198852374-3f19cd0b-f310-48e3-b9bf-f08a4c2d1e4a.mp4

From @lassoan 

> Maybe the simplest would be to suppress all outputs during these auto-completion evaluations. 

## Environment
- Slicer version: Slicer-5.1.0-2022-10-27
- Operating system: Windows

**Comment by jcfr** [comment]
@lassoan is currently evaluating if error message should be either disabled during auto-complete or displayed "differently".

**Comment by jcfr** [comment]
Following integration of #6638:

| Before | After |
|--|--|
| ![image](https://user-images.githubusercontent.com/219043/199385422-d7917607-eec8-4416-90d2-71119d468fd7.png) | ![image](https://user-images.githubusercontent.com/219043/199386361-bfa23e84-706b-4692-8d85-2b53f5278e92.png) |
