### ISSUE TITLE
Markups initiating with a clear (0,0,0) position

### ISSUE THREAD

**Issue by feliciamiranda** [Slicer/Slicer#6661]
@allemangD 

## Summary

When we load a markups file (.mrk.json) in slicer and change the position of one of the landmarks in the list, after saving the file and opening again for other purposes, the other landmarks positions are cleared (0,0,0, except for the one that the position was changed). 

![Fig1](https://user-images.githubusercontent.com/110692943/201361880-6d64b069-1e4a-49de-8009-a757acfe6841.png)

![Fig2](https://user-images.githubusercontent.com/110692943/201361891-9890e17a-91ad-4f08-83e4-89df9d544aa9.png)

## Steps to reproduce

Load a landmarks list in Slicer (.mrk.json)
- Open Markups module
- Go to Control Points: Change the position of one of the landmarks
- Save the markups file and open it again

*I can provide data to the test if needed.

## Expected behavior

We noticed that in the control points (inside the markups module) when we load a markups list, all the landmarks are in an "Edit" state (Fig1.1). After changing the position, the landmark receives another state (Fig1.2). When we finish the editing, we have to change the "state" of all landmarks in the list, including the ones that we did not change positions to make sure that when we open again, we still have the positions. The expected behavior would be to have the landmarks in a state that does not require a change of the entire list after editing one or more landmarks. 

## Environment
- Slicer version: Slicer-5.1.0-2022-10-27
- Operating system: Windows and Mac

**Comment by jamesobutler** [comment]
@feliciamiranda I'm having difficulties replicating the issue. Can you provide more detail about how the originally .mrk.json was saved? Were positions cleared, .mrk.json saved, application closed/reopened, then load .mrk.json and trying to restore the positions of the .mrk.json that were previously cleared prior to last save? Does this issue still happen with latest Slicer preview?

**Comment by feliciamiranda** [comment]
@jamesobutler The positions were not cleared before saving. I opened the .mrk.json, changed the position of one of the landmarks, and saved it (Fig 2). However, after opening the same file again, the positions of the other landmarks were cleared (Fig 3). I just tried again using version 5.1.0 (revision 31284 / built 2022-11-14) and had the same problem.

**Comment by allemangD** [comment]
Could you share a `.mrk.json` file that demonstrates the issue?

**Comment by feliciamiranda** [comment]
@allemangD Yes, I am sending the .mrk.json below. 
[001_T2_Scanreg_lm_Pred_CB.mrk.json.zip](https://github.com/Slicer/Slicer/files/10006568/001_T2_Scanreg_lm_Pred_CB.mrk.json.zip)

**Comment by lassoan** [comment]
All the points have incorrect status:

    "positionStatus": "preview"

How was this .mrk.json file created?

**Comment by jamesobutler** [comment]
I have been unable to figure out a way in the GUI to set all control points to save with a "preview" position status. Was the original .mrk.json manually edited in which case this is a typo that more than 1 control point is in the "preview" position status. A position that has a cleared position has a position status of "undefined".

**Comment by feliciamiranda** [comment]
> All the points have incorrect status:
> 
> ```
> "positionStatus": "preview"
> ```
> 
> How was this .mrk.json file created?

The .mrk.json was created using ALICBCT (In Slicer Automated Dental Tools). @lucanchling was able to find and solve the issue with the position status. He now changed the position status to "defined" when a new .mrk.json is created. Thank you!
