### ISSUE TITLE
Typed Parameter Nodes in Python

### ISSUE THREAD

**Issue by Connor-Bowley** [Slicer/Slicer#6665]
## The problem

In Python, it is recommended to use the parameter node concept, as the parameter nodes are in the scene and are automatically handled when saving and loading the scene. One large downside to the parameter node, in my opinion, is that they are essentially just a string to string dictionary. This has two large downsides:

- There is a loss of value typing. The user needs to know the type and cast to it at each usage.
- Compared to named access of a member variable or function, the errors from using the wrong key are harder to track down (especially because there is an implicit default of return empty string in `GetParameter`). It is also more difficult to discover possible parameter keys in the Python interpreter than it is to discover members.

## A possible solution

A solution I have implemented for a custom Slicer application is to create a wrapper around the parameter node that has "typed" member variables. A similar solution was implemented independently for the NousNav project (developed by @allemangD). This involves using Python properties on a custom non-MRML class to allow for pythonic access to a contained parameter node.

```py
# instead of
x = int(untypedParameterNode.GetParameter("x"))
inputNode = untypedParameterNode.GetNodeReference("inputNode")

# it would be
x = typedParameterNode.x # which returns an int
inputNode = typedParameter.inputNode # which returns a vtkMRMLNode of the appropriate type
```

An ideal solution would allow for easy to create wrappers, using some syntax such as the following:

```py
CustomTypedParameterNode = MakeTypedParameterNode(
"CustomTypedParameterNode", [
    Parameter("x", type=int, default=0),
    Parameter("values", type=float, multi=True),
    Parameter("inputNode", type=slicer.vtkMRMLModelNode),
])

parameterNode = CustomTypedParameterNode(self.logic.getParameterNode())
parameterNode.x = 4
parameterNode.values = [1.0, 1.5, 2.0]
parameterNode.inputNode = slicer.mrmlScene.AddNewNodeByClass('vtkMRMLModelNode')
```

This proposed syntax for creating the new type is inspired by the syntax for Python's [collections.namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple) and [argparse](https://docs.python.org/3/library/argparse.html).

The generated Python properties (such as `x`, `values`, and `inputNode` above) would use `GetParameter/SetParameter/GetNodeReference/SetNodeReferenceID` under the hood, so as to reuse existing code for saving and loading the item to the scene.

## Describe alternatives you've considered

- Create a new MRML node in C++ that has the particular typed parameters you want and nicely implements the Read/WriteXMLAttributes
    - This is a lot of code and boilerplate, and cannot easily be done without creating a new C++ loadable module

## Additional context

It would be desirable to make custom parameter node classes in C++ easier to implement. My opinion is that the solution for C++ could be developed independent of the Python solution, as the interfaces only have a one way overlap.

Custom C++ parameter nodes should be usable from Python with normal `object.member` syntax (or at least `object.SetMember/GetMember functions`), but custom Python parameter nodes cannot be access in C++ via the `object.member` syntax because they do not exist at C++ compile time. However, C++ can continue to access Python written parameter nodes via the `GetParameter/SetParameter` methods, and this is not affected by the implementation of the Python typed parameter node described.

**Comment by jcfr** [comment]
Notes from 2022.11.15 hangout
* Proposed syntax is a subset of capabilities also provided by the CLI node, this means further improvement may enable to also leverage this for python based CLI module
* pull request integrating the feature should also update existing scripted module. For example,  [VectorToScalarVolume](https://github.com/Slicer/Slicer/blob/main/Modules/Scripted/VectorToScalarVolume/VectorToScalarVolume.py) and [SegmentStatistics](https://github.com/Slicer/Slicer/blob/main/Modules/Scripted/SegmentStatistics/SegmentStatistics.py)
* Consider reviewing how these projects implement parameters: [napari](https://github.com/napari/napari), [traitlets](https://github.com/ipython/traitlets) (used in Jupyter)
