### ISSUE TITLE
The "remove remove unnecessary items" in the document may be one more "remove"

### ISSUE THREAD

**Issue by chinanewer** [Slicer/Slicer#6693]
## Summary

in doc path “Docs/user_guide/get_help.md”， There are the following statements: “If Slicer starts successfully then you need to remove remove unnecessary items from the system path (or delete the libraries installed at incorrect locations).”. There are two consecutive “remove ”, one of which may need to be deleted.

## Steps to reproduce

null

## Expected behavior

“If Slicer starts successfully then you need to remove unnecessary items from the system path (or delete the libraries installed at incorrect locations).”

## Environment
- Slicer version: current mian branch
- Operating system: null

**Comment by jcfr** [comment]
Thanks for the report :pray: 

If you would like you could create a pull request following these steps:

1. Go to https://github.com/Slicer/Slicer/blob/main/Docs/user_guide/get_help.md

2. Click on the edit button

3. Edit the file

4. Select ` Create a new branch for this commit and start a pull request`, enter title like `DOC: Fix typo in Troubleshooting guide`

**Comment by chinanewer** [comment]
OK, Thank you for your guidance.

**Comment by jcfr** [comment]
Thanks @chinanewer for taking the time to report the issue and create the pull request :pray: 

If you identify any other issue like this one, do not hesitate to create similar pull requests.
