### ISSUE TITLE
slicer has caught application error

### ISSUE THREAD

**Issue by minha40** [Slicer/Slicer#6716]
## Environment
- Slicer version: Slicer-5.??.?-YYYY-MM-DD
- Operating system: Windows / Linux / Mac + which version

**Comment by lassoan** [comment]
Can you provide more information about what you did, what you expected to happen, and what happened instead?

**Comment by jamesobutler** [comment]
Closing now following no response from original reporter.

**Comment by minha40** [comment]
Thank you so much.i have downloaded a new version of slicer now it's work.
Many thanks
Minha
