### ISSUE TITLE
CPack always uses NA-MIC as the vendor for extension packages

### ISSUE THREAD

**Issue by ClaudioHoffmann** [Slicer/Slicer#6722]
## Summary

https://github.com/Slicer/Slicer/blob/53625c29ec8c212a91ba34750e01ea2a4b25272e/CMake/SlicerExtensionCPack.cmake#L126
CPack's NuGet generator, for example, uses this value for the `<authors>` property in the resulting package. Since `CPackConfig.cmake` is also written from that file, this setting can't be easily replaced.

## Expected behavior

Either `${EXTENSION_CONTRIBUTORS}` or the replaceable `${Slicer_ORGANIZATION_NAME}` seem to make more sense in this context.

**Comment by jamesobutler** [comment]
Yes, by default Slicer_ORGANIZATION_NAME is `NA-MIC` so should functionally be the same when using defaults. Slicer_ORGANIZATION_NAME is `NA-MIC` (for now) until it actually gets changed to `Slicer` by default. See https://discourse.slicer.org/t/inconsistency-between-organization-name-used-for-settings-files-and-for-macos-bundle-identifier/26547
