### ISSUE TITLE
Volumes module w/l lock does not lock w/l slider

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#6738]
## Summary

In Slicer 4.11.20210226, the Window/Level lock in the Volumes module would disable all presets and the window/level mode option and values. You could not drag the slider when it was locked.

![image](https://user-images.githubusercontent.com/15837524/208150175-19853a31-0096-4748-9408-1122b3bdcf92.png)

Starting in Slicer 5.0.3, the Window/Level lock in the Volumes module still disables all presets, but it does not disable the window/level mode option or spinboxes anymore. You can successfully drag the Window/Level slider to change the Window/Level even when in the locked state. This was likely due to the changes made in https://github.com/Slicer/Slicer/commit/1af95e000940297c5fada31251c82f3a34264960 or associated commits from the originating PR.

![image](https://user-images.githubusercontent.com/15837524/208150426-184fe108-bcc1-4d04-8b33-5e53bb44ebd2.png)

## Steps to reproduce

1. Open Slicer and load MRHead Sample data set
2. Switch to Volumes module
3. Press the "Lock" window/level button
4. Change the window/level slider and observe that window/level can still be changed.

## Expected behavior

While in the locked mode, the window/level mode and spinboxes to changes the values should be disabled to prevent moving the slider which changes the window/level. This would restore the behavior as it was in Slicer 4.11.20210226 and earlier.

## Environment
- Slicer version: Slicer 5.2.1
- Operating system: Windows

**Comment by lassoan** [comment]
This locking was added when left-click-and-drag adjusted the window/level. Maybe we could remove this feature completely to make things a bit simpler?

**Comment by jamesobutler** [comment]
I'm not sure how many others have reimplemented adjusting window/level on mouse left-click-and-drag outside of changing the mouse mode. For strictly Slicer behavior, I think the functionality would be fine to removed. I don't see accidentally changing window/level from the Volumes module. If you are clicking on presets or the slider, those clicks are likely deliberate and very very unlikely to be accidental.
