### ISSUE TITLE
Mouse behavior is incorrect after "Operate on invisible segment" popup

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#6748]
## Summary

Mouse behavior is incorrect after initiating editing operation on a hidden segment and the "Operate on invisible segment" popup is displayed.

Reported at: https://discourse.slicer.org/t/3d-rotation-without-mouse-press-after-popup-operate-on-invisible-segment/26889

## Steps to reproduce

- Download Sample Data CTChest.
- Create a segment
- Hide the segment
- Activate Scissor effect
- Click in the 3D view
- Popup appears: “Operate on invisible segment?”
- Press cancel.
- Move cursor in 3D view (without mouse button press)

The 3D view rotates as the mouse is moved around.

## Expected behavior

After the popup is dismissed, the view should work correctly (only rotates if the mouse button is depressed).

## Workaround

After the popup is displayed, the proper mouse behavior can be achieved by deactivating the effect and clicking in the view. 

## Environment
- Slicer version: Slicer-5.2.1
- Operating system: all

**Comment by jcfr** [comment]
@lassoan If you think this should be addressed, we can definitely re-assign the `Slicer 5.3` milestone
