### ISSUE TITLE
Calling `vtkMRMLModelDisplayNode.SetColor` seems to invert normals

### ISSUE THREAD

**Issue by ekhahniii** [Slicer/Slicer#6749]
## Summary

Calling `SetColor` on a vtkMRMLModelDisplayNode via the python console results in the model appearing to have inverted normals. 

If the model color is adjusted via the UI, the normals are returned to the correct orientation.

## Steps to reproduce

![image](https://user-images.githubusercontent.com/49728874/209271139-d286cd31-f829-470c-b68e-65667ddb3015.png)

```python
slicer.mrmlScene.GetSubjectHierarchyNode().GetDisplayNodeForItem(model_id).SetColor(255,0,0)
```
![image](https://user-images.githubusercontent.com/49728874/209271193-909df560-98f7-480b-885c-936cb2a4f68f.png)

Setting color to (255, 0, 0) via the Models module (Display > Visibility > Color)

![image](https://user-images.githubusercontent.com/49728874/209271238-84b4047d-ecd7-4a83-9b53-02e41c6f7b7d.png)

## Expected behavior

No inverted normals.

## Environment
- Slicer version: Slicer-5.2.1 r31317 / 77da381
- Operating system: Windows 10

**Comment by RafaelPalomar** [comment]
I can confirm the same behavior. @ekhahniii, what makes you think is a problem with normals inversion? The problem could be related to internal updating of illumination settings. I'll have a closer look at this. Thanks for reporting!

**Comment by lassoan** [comment]
It is all good. VTK uses float colors in the [0.0, 1.0] range and not unsigned char in [0, 255].

**Comment by RafaelPalomar** [comment]
> It is all good. VTK uses float colors in the [0.0, 1.0] range and not unsigned char in [0, 255].

I wonder if we shouldn't give a warning or try to normalize the values.

**Comment by lassoan** [comment]
None of the lighting related properties are capped VTK, which is useful in some special cases. It would be hard to decide which one is more important: support some niche use cases or make the API more foolproof. However, since this decision was made in VTK decades ago, I would probably vote for keeping the current state, unless changing the API would be required for some major new feature or very serious bug.

**Comment by ekhahniii** [comment]
Apologies for the noise on this one—certainly a novice mistake. The confusion stemmed from seeing [0, 255] in the UI and naively assuming the module logic accepted that range.

> I wonder if we shouldn't give a warning

Agree an out-of-range warning or at least module logic documentation would be helpful, especially when direct module logic usage is [encouraged](https://slicer.readthedocs.io/en/latest/developer_guide/python_faq.html#how-to-find-a-python-function-for-any-slicer-features). That said, I do acknowledge there are numerous examples of setting color in the [script repository](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html) that hint at a range [0.0, 1.0].
