### ISSUE TITLE
Q3DC points don't remain on the surface

### ISSUE THREAD

**Issue by demannett** [Slicer/Slicer#6753]
## Summary

The problem is that un the 5.2 version, when you use Q3DC extension and you set point on a surface (of an .stl file, for example) to take measurements, if you then use transform to shift the object, the points don't move with the object. As if the point was not associated to the object. This issue was not present in the 4.11 version, and it's also present in the 5.3 version.

## Steps to reproduce

Import an .stl file. Go to Q3DC extension, set some points. Then go to Transform tool, and try to move the .stl mesh. Points don't move with the .stl object.

First image: points as i place in the surface
![WhatsApp Image 2022-12-26 at 21 18 31](https://user-images.githubusercontent.com/121459291/209581130-d665175a-ea6a-48b0-8f67-a51607fc1c8d.jpeg)

Second image: points don't move with the object using "Transform" and they "go out" from the surface
![WhatsApp Image 2022-12-26 at 21 18 32](https://user-images.githubusercontent.com/121459291/209581223-65a0a9aa-b831-465c-94d1-8abf274360c4.jpeg)

## Expected behavior

I expect the points move with the object, as it happens in 4.11 version.

## Environment
- Slicer version: Slicer-5.2.1-2022-11-24
- Operating system:  Mac + Ventura 13.0.1

**Comment by allemangD** [comment]
As this issue is specific to Q3DC I have opened a duplicate in that repository. Thanks for reporting!
