### ISSUE TITLE
z spacing incorrectly read for multi-frame dicom

### ISSUE THREAD

**Issue by SimonRelu** [Slicer/Slicer#6773]
## Summary

The z spacing is set to `1.0` instead of the value in the `SliceThickness` or `SpacingBetweenSlices` tag. When I convert the dicom to a single-frame dicom (folder with `.dcm` files for each file) the z spacing is detected correctly.

## Steps to reproduce

1. download the following dicom and load it into splicer: https://we.tl/t-TtYP5sc7TV
2. notice that the Coronal and Sagittal view are stretched
3. If you go to the Volumes module the z spacing is set to 1.0

## Expected behavior

The dicom is isotropic. All voxel spacing is the same. The voxel spacing of z should thus be equal to x and y.

## Environment
- Slicer version: Slicer-5.2.1
- Operating system: MacOs 12.6

**Comment by pieper** [comment]
Thanks for reporting and sharing an example dataset.  I had a quick look and the data loads as 0.3 isotropic for me in the current release 5.2.1, but the pixel data appears incorrect (black and white speckles).  Looking at the headers this looks like some kind of research dataset so probably it's not well formed (it's often hard for people to make valid dicom data).

I see many of these errors in the log:

```
WARNING: In /work/Stable/Slicer-0-build/ITK/Modules/IO/GDCM/src/itkGDCMImageIO.cxx, line 360
GDCMImageIO (0xa7292e0): Converting from MONOCHROME1 to MONOCHROME2 may impact the meaning of DICOM attributes related to pixel values.
```
![image](https://user-images.githubusercontent.com/126077/211587444-1cb4eff5-c28a-42ee-ad2d-1d9e8a7b4523.png)

If you are sure this is a valid dataset  you can reopen the issue, and maybe provide more context and evidence that the data is valid (like showing that it loads in other software).

**Comment by SimonRelu** [comment]
Thank you for your response. The issue related the the pixel data is related to an issue in how we used itk and has been resolved. However the pixel spacing is still wrong when opened within Slicer. MeVisLab opens the scan correctly.
Here's an updated version of the dicom without the pixel data issues: https://we.tl/t-j8FoBTpB4M
I'm not sure why this particular scan fails since other multi-frame dicoms work well in Splicer.

<img width="571" alt="Screenshot 2023-01-17 at 10 20 20" src="https://user-images.githubusercontent.com/110388884/212860265-ba1d0e8e-69de-4404-a7ea-9d346fb3e230.png">
![Screenshot 2023-01-17 at 10 20 59](https://user-images.githubusercontent.com/110388884/212860286-27758d9e-12ae-4d86-aa46-a87e08183ad5.png)

**Comment by pieper** [comment]
This still looks to me like an invalid dicom file.  A multiframe CT should be in enhanced ct image with per-frame-functional-groups for the image positions, but this is a ct image with a non-standard way of encoding the slice spacing.

This tool can help you understand the differences:

https://dicom.innolitics.com/ciods/ct-image

**Comment by SimonRelu** [comment]
Thanks a lot for the response! I'll look into that
