### ISSUE TITLE
Sagittal slice view sign inverted

### ISSUE THREAD

**Issue by simonoxen** [Slicer/Slicer#6778]
## Summary

Sagittal slice view sign seems to be inverted. See screenshot

**A** and **B** indicate crosshair position in the left side.
**C** shows slice view value of positive R

![Picture1](https://user-images.githubusercontent.com/47367230/212303301-a5230c6d-de3c-4fac-9ace-d64774f7f4d0.png)

## Steps to reproduce

- Load sample image MRHead
- Scroll sagittal slice to positive right values
- Place crosshair / look at Data Probe
- Slice view shows positive R, while data probe shows L

## Expected behavior

Sagittal view should show negative R values for left side.

## Environment
- Slicer version: Slicer-5.2.1 and Slicer-5.3.0-2023-01-12
- Operating system: Mac

**Comment by pieper** [comment]
The DataProbe used to report RAS, with positive and negative values, but at some point it was changed to prefix the numbers with L/R, A/P, I/S instead.  I kind of preferred the old way, but apparently there were users who expected the current way.

Do you think there needs to be an option to display either way?  Maybe some text formatting could make the convention clearer?

**Comment by pieper** [comment]
Oh, I see, you are saying the sagittal is inconsistent.  Yes, I see that too.  Probably the IJKtoRAS needs to be taken into account.  This scan is a sagittal acquisition so it is good for testing issues like this.

**Comment by lassoan** [comment]
> Probably the IJKtoRAS needs to be taken into account. 

Agreed! The slider tooltip and orientation label are currently not computed dynamically from the current IJKtoRAS matrix but they are hardcoded strings for the hardcoded IJKToRASDirection matrix here:

https://github.com/Slicer/Slicer/blob/83a84a0f72baa0fcd1bb3653cedae7b02ca3bd1b/Libs/MRML/Widgets/qMRMLSliceControllerWidget.cxx#L80

We could fix the issue by changing the hardcoded labels (it will be always correct because the axes directions are hardcoded, too. However, it would be much nicer to compute the labels dynamically.

**Comment by simonoxen** [comment]
Thanks!

btw, setting the value (`slicer.app.layoutManager().sliceWidget("Yellow").sliceLogic().SetSliceOffset(-20)`) also leads to inconsistencies (sets data probe to R=+20).

Should I give it a try with a PR? Do you have some guidelines on how to approach it?

**Comment by pieper** [comment]
Now that I look, I think it's just that the slicer is mislabled (or rather that it's implemented backwards).

By default the red view goes from left to right in the positive Superior direction, and the green goes left to right in positive Anterior direction, but yellow goes left to right in negative Right direction, so it violates the RAS nature, while the offset label is consistent with RAS.  You can see this in the image that the yellow view is visible in the 3d view obviously on the patient left but the number is positive R when this should be negative R (the value in the dataprobe of positive L is correct).

In terms of a PR I think fixing the label is probably better at this point, although we could change the sense of the slider to be consistent with the RAS convention.  I don't think people would necessarily notice or mind.

![image](https://user-images.githubusercontent.com/126077/212421675-ee5edece-b5fb-4f3c-a660-950a2e9dcbc2.png)

**Comment by lassoan** [comment]
Slider right is world left because usually 3D view shows patient

**Comment by pieper** [comment]
> Slider right is patient left because usually 3D view shows patient left on screen right. 

To clarify, the label "R 79.2183mm" is the part that is incorrect because you can see in the 3D view that the slice is in the patient left.

**Comment by lassoan** [comment]
Yes, the "R" label should be "L". The dynamic label computation result for the current SliceToRAS matrix is "L". If we switch to this dynamic computation that will fix this, and it is nicer anyway because it works with custom axis labels and for any slice orientation.

**Comment by lassoan** [comment]
Here is the pull request with the proposed fix: https://github.com/Slicer/Slicer/pull/6781
