### ISSUE TITLE
Custom application fails to build Markups module after disabling SceneViews module

### ISSUE THREAD

**Issue by tbirdso** [Slicer/Slicer#6789]
## Summary

Slicer custom app build fails by default. On inspection it seems that the failure is in a Markups module test due to SceneViews headers not being available. The SceneViews module is disabled and the Markups module is enabled. There seems to be an implicit test dependency between Markups and SceneViews.

## Steps to reproduce

1. Disable the SceneView module as done in the [SlicerCustomAppTempalte by default](https://github.com/KitwareMedical/SlicerCustomAppTemplate/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/CMakeLists.txt#L125)
2. Build all tests

## Expected behavior

All tests build successfully

## Observed behavior

```sh
18>------ Build started: Project: qSlicerMarkupsModuleCxxTests, Configuration: Release x64 ------
18>vtkMarkupsAnnotationSceneTest.cxx
18>C:\repos\IV3D-bld\slicersources-src\Modules\Loadable\Markups\Testing\Cxx\vtkMarkupsAnnotationSceneTest.cxx(24,10): fatal  error C1083: Cannot open include file: 'vtkSlicerSceneViewsModuleLogic.h': No such file or directory
18>Done building project "qSlicerMarkupsModuleCxxTests.vcxproj" -- FAILED.
```

See https://github.com/Slicer/Slicer/blob/main/Modules/Loadable/Markups/Testing/Cxx/vtkMarkupsAnnotationSceneTest.cxx#L24

## Environment
- Slicer version: Slicer-5.3 commit [2db14ceb](https://github.com/Slicer/Slicer/commit/2db14ceb03248e0fea6610bcdf059f4f24f6cc5a)
- Operating system: Windows 11

cc @jcfr

**Comment by lassoan** [comment]
It seems we actually don't need to use scene views logic in this test. It may be just a copy-paste from a test that used some scene views features as well.

Please remove the 3 lines related to scene views and try again:

```
#include "vtkSlicerSceneViewsModuleLogic.h"
...
  vtkNew<vtkSlicerSceneViewsModuleLogic> sceneViewsModuleLogic;
  sceneViewsModuleLogic->SetMRMLScene(scene.GetPointer()); 
```

If this fixed the issue then please submit a pull request with this change. Thank you!
