### ISSUE TITLE
MatlabBridge - option to create output node by default instead of "None"

### ISSUE THREAD

**Issue by georg-walther** [Slicer/Slicer#6804]
Dear Slicer-community,

I try to develop an extension using MatlabBridge which involves loading multiple 3D and 4D images from Matlab into 3D-Slicer. Unfortunately this only works if I manually select “Create new volume” in the dropdown IO > “Create new volume” (see Figure 2). I have multiple volumes that need to be displayed by 3D-Slicer and I don’t want the user to click through each volume and select “Create new volume”. When I leave the setting at “None” (default, see Figure 1), the code returns the following error:
![Bildschirmfoto vom 2023-01-28 23-27-08](https://user-images.githubusercontent.com/62775496/215340359-4c7f316b-6c16-495e-be31-fd4ed06805a1.png)

I think the most straight forward way would be to add a \<default>node_name_to_create\</default> field to the semantic behind \<image>\</image> in the XML file in MatlabBridge. Or add a conditional: if no output volume selected and MatlabBridge function called -> create an output node for each \<image>\</image>.

For further details about this MatlabBridge problem visit [this discourse-slicer thread](https://discourse.slicer.org/t/matlabbridge-empty-volume-by-default-instead-of-no-volume/27525).
Until this feature request is implemented, I cannot use 3D-Slicer for my Matlab extension but have to code a GUI myself. So I would also be happy if there is any workaround.

Best regards,
Georg

Figure 1 - not working setting:
![Bildschirmfoto vom 2023-01-28 23-01-08](https://user-images.githubusercontent.com/62775496/215339680-b00a54f3-a725-48b2-96d3-285c1e5ad844.png)
Figure 2 - working setting:
![Bildschirmfoto vom 2023-01-28 23-01-01](https://user-images.githubusercontent.com/62775496/215339690-157cf499-8853-4b7d-9f7e-f27d02e40305.png)

**Comment by lassoan** [comment]
I agree that automatically creating an output node automatically can be convenient for the user (it saves 2 clicks). This could be added to the CLI module description XML.

However, if the automatically generated CLI module GUI is not sufficiently convenient for users then we recommend to create a Python scripted module with a sophisticated GUI and make that module use the CLI under the hood for performing computations.
