### ISSUE TITLE
Failed to load Annotation ruler

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#6813]
## Summary

I'm getting a failure when trying to load an old Annotation ruler object that was saved to an acsv file.

## Steps to reproduce

1. Launch Slicer
2. Drag and drop the acsv onto the main window
[C_1.zip](https://github.com/Slicer/Slicer/files/10677998/C_1.zip)
![image](https://user-images.githubusercontent.com/15837524/217324022-fa700a42-66aa-4ea8-9d65-7c9adce9582f.png)
4. Press "OK" on the add data dialog and observe the following error
![image](https://user-images.githubusercontent.com/15837524/217323606-fea93593-c565-41c1-8650-ccd76c3ed045.png)

> [VTK] vtkSlicerMarkupsLogic::LoadMarkups failed: unrecognized file extension in C:/Users/butlej30383/Downloads/C_1.acsv
> [Qt] void __cdecl qSlicerIOManager::showLoadNodesResultDialog(bool,class vtkMRMLMessageCollection *) Errors occurred while loading nodes: "Error: Loading C:/Users/butlej30383/Downloads/C_1.acsv -  load failed.\n"

## Expected behavior

Annotation files should load and convert into Markups objects. Associated commit https://github.com/Slicer/Slicer/commit/f44849b014ecf9a245901239db64037556110970

## Environment
- Slicer version: Slicer-5.3.0-2023-02-01
- Operating system: Windows

**Comment by jamesobutler** [comment]
If I do the following I observe that the object is appropriately loaded and converted to a Markups Line node, but it doesn't return the converted object which results in `ruler_node` being a nonetype.
```python
ruler_node = slicer.util.loadAnnotationRuler(r"C:\Users\butlej30383\Downloads\C_1.acsv")
# [Qt] Python console user input: ruler_node = slicer.util.loadAnnotationRuler(r"C:\Users\butlej30383\Downloads\C_1.acsv")
# [Qt] "Annotation" Reader has successfully read the file "C:\\Users\\butlej30383\\Downloads\\C_1.acsv" "[0.03s]"
# [Qt] bool __cdecl qSlicerCoreIOManager::loadNodes(const class QString &,const class QMap<class QString,class QVariant> &,class vtkCollection *,class vtkMRMLMessageCollection *)  error: cannot find node by ID  "vtkMRMLAnnotationRulerNode1"
type(ruler_node)
# <class 'NoneType'>
```

**Comment by jamesobutler** [comment]
@lassoan Are loading individual Annotation files something that will/should be supported? https://github.com/Slicer/Slicer/commit/f44849b014ecf9a245901239db64037556110970 details loading from old scenes, but not necessarily loading of individual files.

**Comment by lassoan** [comment]
> Are loading individual Annotation files something that will/should be supported? https://github.com/Slicer/Slicer/commit/f44849b014ecf9a245901239db64037556110970 details loading from old scenes, but not necessarily loading of individual files.

I don't think we would need support loading of old annotation file formats forever, but it makes sense that we support it for a while.

Loading of annotation ruler and ROI still works. I'll just remove the markup reading from .acsv because it is not implemented.
Support for annotation fiducials was probably removed long time ago, I don't think anyone misses that but I'll have a quick look if it is easy to fix it.

slicer.util.loadAnnotationRuler does not work because by the time the user processes the node it is already removed (converted to a markup node). I'll fix this.
