### ISSUE TITLE
Module title cannot be translated to other languages

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#6826]
It is not possible to provide translations for module title (module name that is displayed to users). They do not show up in [Weblate](https://hosted.weblate.org/projects/3d-slicer/3d-slicer/).

Loadable module titles are specified in the CMake file of the module, using the MODULE_TITLE variable. For example:

https://github.com/Slicer/Slicer/blob/30a390822689e1ccaf72b22467258dd215be51cf/Modules/Loadable/VolumeRendering/CMakeLists.txt#L4

Qt's lupdate does not detect this as translatable string and the string.

Potential fixes:
- Option A: Remove the MODULE_TITLE variable and specify it in the source file. Advantage: source file location listed in the .ts file is the same as the actual file location.
- Option B: Generate a C++ header file that contains the module name in a QT_TRANSLATE_NOOP macro. Advantage: if we store basic module information in CMake file (or some json description file) then it is easier to extract that data with automated processing (e.g., to display list of modules in the extensions catalog).

Note: the English module name should be accessible (in tooltips or next to the translated module name) and the module should be searchable by English name, to make it easier for finding a module in a translated Slicer when using a tutorial written in English.

**Comment by pieper** [comment]
How about introducing a new variable for the module's display title and make that translatable?

**Comment by lassoan** [comment]
We already have two variables: module name (English, no special characters, no spaces) and module title. Do you mean you would add a new property in addition to these?

**Comment by pieper** [comment]
Yes, I mean that if we can't currently translate the module title it might be easier to create a new display variable rather than change the CMake (since that could be hard to retrofit to existing modules and extensions).

**Comment by lassoan** [comment]
It would be an easy change, we could simply set the module title the same way as other module properties (in the cxx file). We can keep the these module title macros so that other modules that don't need internationalization can continue to use them. Here is an example what I mean, for Volumes and Volume Rendering modules: https://github.com/Slicer/Slicer/commit/3526e4ad4638005df08c61c00a6109e91032af34

I only raised the question because I was not sure why this odd mechanism for setting the module title was implemented. The only thing I could think of was this ability to provide metadata without instantiating the module. But to get any other metadata you need to instantiate the module anyway, so I don't think we need this mechanism. For some module properties, such as dependencies, it could worth the trouble to implement a mechanism to get it without instantiation (it could simplify the module discovery and loading process), but the module title is really not that interesting (other than that we show it to users in the GUI).

**Comment by pieper** [comment]
> I only raised the question because I was not sure why this odd mechanism for setting the module title was implemented

I'm not sure either, and I don't have a strong feeling about keeping it other than avoiding the need to edit a lot of CMake file, or needing to handle complexity of a backwards compatibility mode.  But clearly something needs to be done, so whatever seems least painful is fine with me.

**Comment by lassoan** [comment]
This has been implemented in the commits referred above.
