### ISSUE TITLE
Color legend display not working as expected in all slice views

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#6827]
## Summary

As originally mentioned at https://discourse.slicer.org/t/issue-displaying-color-legend-in-other-slice-views/27784, the color legend display is not working as expected in some of the other slice views other than Red/Yellow/Green. 

## Steps to reproduce

```python
# Start Slicer so that on startup it is the Four-Up Layout
slicer.app.layoutManager().setLayout(slicer.vtkMRMLLayoutNode.SlicerLayoutThreeOverThreeView)

import SampleData
sampleDataLogic = SampleData.SampleDataLogic()
mrHead = sampleDataLogic.downloadMRHead()

color_legend_display_node = slicer.modules.colors.logic().AddDefaultColorLegendDisplayNode(mrHead)
color_legend_display_node.SetVisibility(True)
```
If you start Slicer where it begins in the the Three-over-three layout, then the color legend display shows as expected. Something about the views on startup has some impact here.

## Expected behavior

The color legend display should turn on/off for the specified volume in all slice views that the volume is displayed in. It should not be tied to Slice visibility in 3D either.

## Current workaround
```python
slicer.app.layoutManager().setLayout(slicer.vtkMRMLLayoutNode.SlicerLayoutThreeOverThreeView)

import SampleData
sampleDataLogic = SampleData.SampleDataLogic()
mrHead = sampleDataLogic.downloadMRHead()

# Workaround - set slice view visibles before turning on color legend display
layoutManager = slicer.app.layoutManager()
for sliceViewName in layoutManager.sliceViewNames():
  view = layoutManager.sliceWidget(sliceViewName).sliceView()
  sliceNode = view.mrmlSliceNode()
  sliceNode.SetSliceVisible(True)

color_legend_display_node = slicer.modules.colors.logic().AddDefaultColorLegendDisplayNode(mrHead)
color_legend_display_node.SetVisibility(True)
```

## Environment
- Slicer version: Slicer-5.3.0-2022-02-10 and Slicer 5.2.1.
- Operating system: Windows

**Comment by lassoan** [comment]
Probably a fix could be to update visibility of the color legends when a new slice composite node is added (in vtkMRMLColorLegendDisplayableManager::OnMRMLSceneNodeAdded) or when the layout is changed.

**Comment by MichaelColonel** [comment]
I will try to fix the issue.

**Comment by MichaelColonel** [comment]
Problem when changing the layout in the color legend displayable manager:

1. The method [UpdateFromMRMLScene()](https://github.com/Slicer/Slicer/blob/main/Modules/Loadable/Colors/MRMLDM/vtkMRMLColorLegendDisplayableManager.cxx#L805-#L808) calls the [UpdateSliceNode()](https://github.com/Slicer/Slicer/blob/main/Modules/Loadable/Colors/MRMLDM/vtkMRMLColorLegendDisplayableManager.cxx#L517) which iterates among all newly created slice nodes to get a `SliceCompositeNode`. The main problem is that the [SliceLogic is invalid](https://github.com/Slicer/Slicer/blob/main/Modules/Loadable/Colors/MRMLDM/vtkMRMLColorLegendDisplayableManager.cxx#L507-#L511) in the [FindSliceCompositeNode](https://github.com/Slicer/Slicer/blob/main/Modules/Loadable/Colors/MRMLDM/vtkMRMLColorLegendDisplayableManager.cxx#L492) method.
2. I tried to update a slice node when a new `vtkMRMLSliceCompositeNode` is added to the scene in (in vtkMRMLColorLegendDisplayableManager::OnMRMLSceneNodeAdded), the last slice node has invalid slice logic. For example for slices: `Red`, `Green`, `Yellow`, `Red+`, `Green+`, `Yellow+`. The slice node `Yellow+` has invalid slice logic.

**Comment by MichaelColonel** [comment]
Fix is ready. PR #6836. If some color legend problems are still present on non-standard slice views, you can delete color legend display node in `Colors` module and recreate a new one.

**Comment by lassoan** [comment]
@jamesobutler does this work correctly in current Slicer Preview Release?

**Comment by jamesobutler** [comment]
Last I checked, I had observed Color legend issues re https://github.com/Slicer/Slicer/pull/6836#issuecomment-1458696583
