### ISSUE TITLE
Error exporting Nifti, fails to write image

### ISSUE THREAD

**Issue by fmends** [Slicer/Slicer#6858]
## Summary

Hello, After adding my annotations to the image and setting a reference volume under Export to Files tab, I receive the following an error message (see screen shot). Exception thrown in event. Nifti libary failed to write image/Users/(rest of target directory). I then have to save my annotated file manually.

## Steps to reproduce

After I import my Nifti volume and segmentations, edit the annotations and then switch to segmentations tab and under export to files section, I set my reference volume and then I hit Export, i get an error message

## Expected behavior

Normally, the export button opens up the destination folder and shows the exported file
![Screen Shot 2023-03-06 at 4 29 12 PM](https://user-images.githubusercontent.com/26937541/223261581-73e0d9b2-3539-496a-b8c2-b7319c745a5b.png)
≈

## Environment
![Screen Shot 2023-03-06 at 4 28 38 PM](https://user-images.githubusercontent.com/26937541/223261647-20b7d34b-1564-488e-8e87-a18eb9419e4e.png)
- Slicer version: Slicer-5.2.2-2023-02-23
- Operating system: Mac OS High Sierra 10.13.6

**Comment by lassoan** [comment]
Thanks for reporting. I cannot reproduce this issue with my data sets. Could you please share the scene that reproduces the issue? (save the scene as .mrb, upload to dropbox/onedrive/etc. and post the link here) Thank you!

**Comment by lassoan** [comment]
We cannot reproduce the issue, so we cannot fix it. @fmends if you can provide an example file then we can reopen the issue.
