### ISSUE TITLE
identical conditions 

### ISSUE THREAD

**Issue by maddin200** [Slicer/Slicer#6861]
/Libs/MRML/Core/vtkMRMLVolumeSequenceStorageNode.cxx line 396

Code:
 if (currentFrameVolumeDimensions[0] != frameVolumeDimensions[0]
    || currentFrameVolumeDimensions[0] != frameVolumeDimensions[0]  // <- identical
    || currentFrameVolumeDimensions[0] != frameVolumeDimensions[0] // <- identical

**Comment by maddin200** [comment]
maybe other indices necessary

**Comment by lassoan** [comment]
Good catch, thank you, fixed.

**Comment by jcfr** [comment]
To add the missing `Co-authored-by:` and considering that the commit was pushed less than 15mins ago, the `main` branch has been force pushed.
