### ISSUE TITLE
Array maybe out of bounds in vtkCurveGenerator::SortByMinimumSpanningTreePosition

### ISSUE THREAD

**Issue by maddin200** [Slicer/Slicer#6866]
/Slicer-main/Modules/Loadable/Markups/MRML/vtkCurveGenerator.cxx line 935
Code:

```cpp
   int nextPointIndex = -1;
    double minDistance = VTK_DOUBLE_MAX; 
   ...
    // Add the picked vertex to the MST Set
    mstSet[nextPointIndex] = true; // <- maybe out of bounds
```

**Comment by pieper** [comment]
Thanks for your report 👍 As technical points about github, please use ```  to format code snippets (I've edited your comment above to illustrate.  Also, please include deep links to the code in question so others can easily follow up on your comments.  In this case it could be: `https://github.com/Slicer/Slicer/blob/a5f75351073ef62fd6198d9480d86c0009d70f9b/Modules/Loadable/Markups/MRML/vtkCurveGenerator.cxx#L935` which you can get by clicking on the line number and then copying the url from the browser.

If you select a range of lines and paste that url directly in a message like this it gets auto-formatted like this: https://github.com/Slicer/Slicer/blob/a5f75351073ef62fd6198d9480d86c0009d70f9b/Modules/Loadable/Markups/MRML/vtkCurveGenerator.cxx#L918-L935

And, if you would be able to submit a pull request with a suggested fix (which would be very welcome) it would be great to make a mention of that in your report.

**Comment by jcfr** [comment]
Proposed fix:

```diff
+   if (nextPointIndex >= 0 && nextPointIndex < numberOfPoints)
+      {
+      // Add the picked vertex to the MST Set
+      mstSet[nextPointIndex] = true;
+      }
-    // Add the picked vertex to the MST Set
-    mstSet[nextPointIndex] = true;
```

**Comment by lassoan** [comment]
@maddin200 Thank you, good catch. Could you submit a pull request with the suggested fix? (you can do it all in the GitHub web interface, don't even need to clone the repository on your computer)

The file was moved into the vtkAddon repository: https://github.com/Slicer/vtkAddon/blob/main/vtkCurveGenerator.cxx#L935
