### ISSUE TITLE
fclose twice applied in vtkSlicerVolumesLogic::InitializeDefaultVolumeDisplayPresets

### ISSUE THREAD

**Issue by maddin200** [Slicer/Slicer#6867]
https://github.com/Slicer/Slicer/blob/56a314f36f60e92cb52ff1aa43d1ba6065e71fd5/Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx#L1601-L1607

<details><summary>Original description</summary>

/Slicer-main/Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx line 1606
Code:
 if (jsonRoot->ParseStream(fs).HasParseError())
    {
    vtkErrorMacro("vtkSlicerVolumesLogic::InitializeDefaultVolumeDisplayPresets failed: Error parsing the file '" << displayPresetsFilename << "'.");
    fclose(fp);
    }
  fclose(fp); // <- twice

</details>

**Comment by jcfr** [comment]
For reference, the duplicated call was introduced through https://github.com/Slicer/Slicer/commit/c72d890515ccca70e4173dfcedd370e197c44ae9#diff-e66332c76fe962dd310d54e008ed379b062f3fec8a74f0969d4706d96b362ad4

**Comment by lassoan** [comment]
@maddin200 Thank you, good catch. Could you submit a pull request with the suggested fix? (you can do it all in the GitHub web interface, don't even need to clone the repository on your computer)
