### ISSUE TITLE
return value not boolean in vtkSlicerCropVolumeLogic::GetVoxelBasedCropOutputExtent

### ISSUE THREAD

**Issue by maddin200** [Slicer/Slicer#6868]
https://github.com/Slicer/Slicer/blob/56a314f36f60e92cb52ff1aa43d1ba6065e71fd5/Modules/Loadable/CropVolume/Logic/vtkSlicerCropVolumeLogic.cxx#L284-L288

<details><summary>Original description</summary>

Slicer-main/Modules/Loadable/CropVolume/Logic/vtkSlicerCropVolumeLogic.cxx line 287
Code:
 if (inputVolume->GetParentTransformNode() && !inputVolume->GetParentTransformNode()->IsTransformToWorldLinear())
    {
    vtkGenericWarningMacro("vtkSlicerCropVolumeLogic::CropVoxelBased: voxel-based cropping of non-linearly transformed input volume is not supported");
    return -1; // <- should be true of false 
    }

</details>

**Comment by pieper** [comment]
@maddin200 See my note on the other issue.  https://github.com/Slicer/Slicer/issues/6866#issuecomment-1460528388.  Maybe you can apply those suggestions here?

**Comment by jcfr** [comment]
For reference, the issue was introduced in https://github.com/Slicer/Slicer/commit/4cacc07bd54a87ec96801a23e5e9099057959514
