### ISSUE TITLE
Segment disappears after threshold effect preview; two widgets

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#6874]
## Summary

Trying to apply threshold to a segment results in the segment disappearing.  The data is correct as shown in DataProbe and save/reload but it is not visible in slice views.

## Steps to reproduce

1) Install MONAI Label and connect to a server.
2) Run inference
3) Open SegmentEditor and select threshold
4) Either apply or cancel and selected segment is gone.

## Expected behavior

Segment Editor effects should work as normal on segmentations coming from MONAI Label

## Environment
- Slicer version: Slicer-5.2.2
- Operating system: Linux

## More Information

After some debugging I believe the issue is that the MONAI Label has a segment editor widget that shares state via the segment editor node with the Segment  Editor module's widget such that when you enter the Threshold effect in either widget are two instances of the threshold effect class created.  The first instance correctly stores the opacity states and sets the display node to 0, but the second instance records the zero state.  Then on cancel the original non-zero opacity states are not restored.

This would appear to be an issue the threshold any time there would be more than one segment editor widget.  I think the solution would be to store the pre-preview opacity state (`previewedSegmentID, segment2DFillOpacity,segment2DOutlineOpacity`) in the segment editor node and not in the threshold effect instance so that only one of the instances would save/restore the opacity.
        
https://github.com/Slicer/Slicer/blob/5dfb6fb6945d3fb56320c2920571f3ffcc5b48fb/Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorThresholdEffect.py#L99-L145

**Comment by pieper** [comment]
@lassoan did you have a chance to review this and do you agree with the analysis?  We need some way for this visualization state to be part of a singleton of class static variable to avoid crosstalk between the two widget instances.

**Comment by lassoan** [comment]
> store the pre-preview opacity state (previewedSegmentID, segment2DFillOpacity,segment2DOutlineOpacity) in the segment editor node

Storing the state in the MRML node would solve the problem of incorrectly restoring the state and I don't think it could cause any regressions. Do you plan to work on this or have a prototype ready or you would like me to work on it?

However, the glow would be still done in parallel by two segment editor widgets, which would be some unnecessary computation and potentially some extra flashing (if the current opacity values get out of sync between the two editors). It is also possible that there are multiple segment editor widgets using different segment editor nodes. It would be nice if restoring of the state would work well in that case, too. We'll have to invent some mechanism to have only one active segment editor widget per view. Maybe we could maintain a "focused segment editor widget" in the segmentation displayable manager - similarly to the focused markup in the markups displayable manager. That would clarify the mouse&keyboard event routing, too.

**Comment by pieper** [comment]
Yes, I agree it's a little tricky and that's why I thought we should discuss before diving in.  It's not really in my critical path so I haven't worked on it, but it definitely surprised me so I'm sure others would be confused too.

I was thinking that one instance of the threshold effect could "claim" the display node and manage the pulsing.  Then any other instances would know to ignore a claimed display node.
