### ISSUE TITLE
Cannot install extensions in latest Slicer Preview Release on Linux

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#6878]
There is a name clash of the settings folder and Slicer executable since changing of the `organization name` from `NA-MIC` to `Slicer` (https://github.com/Slicer/Slicer/pull/6750).

There was no issue on Windows, because the Slicer executable name is Slicer.exe and on macOS the folder structure is special, but on linux there is indeed a name clash. The only way to change this is to modify the Slicer executable or the organization name, because the settings subfolder naming logic logic is hardcoded in the constructor of the QSettings class.

See more information here:
https://discourse.slicer.org/t/install-extensions-is-not-working-on-latest-preview-release/28316/7?u=lassoan

Changing the Slicer executable name is probably not a good idea, as it could cause regressions at many places. Therefore, we need to choose a different organization name.

**Comment by jcfr** [comment]
> Does this need to be specifically prevented?

Good point. Adding an explicit check for this is sensible.

I am thinking about the following:

```diff
diff --git a/CMake/SlicerMacroBuildApplication.cmake b/CMake/SlicerMacroBuildApplication.cmake
index c8428fe796..cb41800f2e 100644
--- a/CMake/SlicerMacroBuildApplication.cmake
+++ b/CMake/SlicerMacroBuildApplication.cmake
@@ -339,6 +339,11 @@ macro(slicerMacroBuildApplication)
   message(STATUS "Configuring ${SLICERAPP_APPLICATION_NAME} application: ${SLICERAPP_NAME}")
   message(STATUS "--------------------------------------------------")
 
+  if(Slicer_ORGANIZATION_NAME STREQUAL SLICERAPP_APPLICATION_NAME)
+    # See https://github.com/Slicer/Slicer/issues/6878
+    message(FATAL_ERROR "Application name must be different from the organization name")
+  endif()
+
   macro(_set_app_property varname)
     set_property(GLOBAL PROPERTY ${SLICERAPP_APPLICATION_NAME}_${varname} ${SLICERAPP_${varname}})
     message(STATUS "Setting ${SLICERAPP_APPLICATION_NAME} ${varname} to '${SLICERAPP_${varname}}'")

```
