### ISSUE TITLE
Build of the extensions index is blocking due to extension waiting for user input

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#6912]
## Summary

After connecting to the windows factory using VNC, I was able to observe that the ExtraMarkups extension was showing a popup dialog and expecting the user to click.

<img width=75% src="https://user-images.githubusercontent.com/219043/227523221-7a3f6995-a7f8-4e0c-a31f-1f3632cbd08d.png"/>

## Steps to reproduce

NA

## Expected behavior

No popup should be displayed.

## Environment

* Observed in the context of the Preview build on Windows (overload factory) associated with fbc2ede

**Comment by jcfr** [comment]
The function `qSlicerStenosisMeasurement3DModuleWidget::installExtensionFromServer` should be improved to skip the popup when running test mode.

https://github.com/vmtk/SlicerExtension-VMTK/blob/5c31f18ba995fa97494b302e23f8a8d16cdc4f8d/StenosisMeasurement3D/qSlicerStenosisMeasurement3DModuleWidget.cxx#L416-L466

Ideally, the function should be contributed to Slicer itself.

**Comment by jcfr** [comment]
cc: @chir-set @lassoan

**Comment by jcfr** [comment]
Once the function `installExtensionFromServer` is added to Slice core, the following should be updated:

| Project | URL |
|--|--|
| SlicerMorph | https://github.com/SlicerMorph/SlicerMorph/blob/c86b3dd507ab0df9ad0fef721b1da1d69cc37d43/SegmentEndocranium/SegmentEndocranium.py#L51-L61 |
| slicer-notebook | https://github.com/Slicer/SlicerDocker/blob/4fc3be96fd28cf97677650a76ac83f209efe834b/slicer-notebook/install.sh |
| Slicer documentation | https://github.com/Punzo/Slicer/blob/08fe346009554f82e63e7d7aaaaec06c16f0a233/Docs/developer_guide/script_repository/gui.md?plain=1#L1137-L1147 |
| DMRIInstall | https://github.com/Punzo/Slicer/blob/08fe346009554f82e63e7d7aaaaec06c16f0a233/Modules/Scripted/DMRIInstall/DMRIInstall.py#L111-L125 |
| kaapana | https://github.com/kaapana/kaapana/blob/0a3b2e14f64510671c9c9dcb7ef73853002d8940/services/applications/slicer-workbench/docker/files/install-slicer-extension.py#L8 |

**Comment by jcfr** [comment]
Related discourse post(s):
* https://discourse.slicer.org/t/programatically-install-extensions/19241

**Comment by chir-set** [comment]
> Ideally, the function should be contributed to Slicer itself.

Thank you for showing this issue.

-2. OK, contributing the function to Slicer is not a problem, and will be done secondarily.

-1. Fixing the popup showing itself seems immediately important. Referring to [this](https://github.com/vmtk/SlicerExtension-VMTK/commit/70b662278f9fef85e690e12ec55ae815924be9ca) resolution, would exiting the function at the very beginning by checking 

qSlicerApplication::application()->layoutManager() == nullptr

be an acceptable solution ?

**Comment by jcfr** [comment]
Instead you could add something like this:

```
  bool isTestingEnabled = qSlicerApplication::testAttribute(qSlicerCoreApplication::AA_EnableTesting);
  if (isTestingEnabled)
    {
    // Do not block the execution with popup windows if testing mode is enabled.
    return;
    }
```

**Comment by chir-set** [comment]
> Instead you could add something like this:

OK.

As for 'StenosisMeasurement3D' module in SlicerVMTK, I think we could just remove that function from there to install 'ExtraMarkups', since that extension is now marked as dependency in SlicerVMTK.

Secondarily, I'll request addition of that function, corrected, in Slicer : where in Slicer ? In which generic library ?

**Comment by lassoan** [comment]
At build time (and so during all testing performed at build time), extension dependencies are not installed (regardless of you list them in the dependencies or not). Therefore, you must exclude all tests from running automatically during build that require other extensions. See more details in this issue: https://github.com/Slicer/Slicer/issues/6529

**Comment by lassoan** [comment]
> Ideally, the function should be contributed to Slicer itself.

Most extensions are implemented in Python and our recommendation has been to follow the [example in the script repository](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#download-and-install-extension). However, the example does not include the user confirmation popup, so users may forget about making it non-interactive in testing mode.

To allow harmonizing the behavior between C++ and Python and between all extensions, I agree that it would be better to add a helper function to the extensions manager. We could start from the helper function that in VMTK. @chir-set would you like to submit a pull request to Slicer that adds the method you implemented?

**Comment by chir-set** [comment]
> @chir-set would you like to submit a pull request to Slicer that adds the method you implemented?

I can, but it is not a problem at all if it's not me.

Can you check this [PR](https://github.com/vmtk/SlicerExtension-VMTK/pull/81) for a final resolution of this issue ?

**Comment by lassoan** [comment]
I've realized why this is not needed ever for C++ extensions!

A C++ module is not even loaded if dependent DLLs are not found. Therefore, it cannot install missing extensions. Therefore, the helper function can be kept in Python. No need to add it to the C++ implementation.

**Comment by lassoan** [comment]
All you need to do is to remove qSlicerStenosisMeasurement3DModuleWidget::installExtensionFromServer from your module.

We can later consider adding a Python function to harmonize how extensions are installed in Python.

**Comment by chir-set** [comment]
> remove qSlicerStenosisMeasurement3DModuleWidget::installExtensionFromServer

Yes, simplest solution.

**Comment by jcfr** [comment]
> re: install from c++
If functionality provided by an extension at runtime (e.g markups, dicom plugin,..) are relevant for a workflow.

Installing them at runtime without a hard requirement at build time is sensible.

While it doesn't have to happen to address this specific issue, I still think we should add the function to the extension manager, it will be useful.

**Comment by lassoan** [comment]
Until now the need for installing an extension in C++ has not come up, but I agree that in theory such use cases are possible (for example, a C++ module using a module implemented in Python).

**Comment by jcfr** [comment]
Update documentation to explain that extension should not be installed as part of the tests.

**Comment by chir-set** [comment]
> Update documentation to mention that extensions should not be installed as part of the tests.
> 
> This means that dialog asking user to install extensions should be conditional implementing code like the following:
> 
> ```c++
>   bool isTestingEnabled = qSlicerApplication::testAttribute(qSlicerCoreApplication::AA_EnableTesting);
>   if (isTestingEnabled)
>     {
>     //...

Hi @jcfr,

I'm abroad right now without any PC. I'll look into that in 2 weeks. cdash doesn't report a build failure for SlicerVMTK nor ExtraMarkups AFAIU.

**Comment by chir-set** [comment]
> This means that dialog asking user to install extensions should be conditional implementing code like the following:
> 
> ```c++
>   bool isTestingEnabled = qSlicerApplication::testAttribute(qSlicerCoreApplication::AA_EnableTesting);


> Ideally, the function should be contributed to Slicer itself.

Hi @jcfr ,

Is this [patch](https://github.com/Slicer/Slicer/compare/main...chir-set:Slicer:EM) what you meant ?

Regards.

**Comment by lassoan** [comment]
The application should not work very differently in testing mode. Skipping display of an information/confirmation popup is a minor behavior change, which should be fine. However, silently not installing dependencies of an extension would be a major behavior change, which should not be done just because we are in testing mode.

**Comment by chir-set** [comment]
> silently not installing dependencies of an extension... should not be done

The patch now shows dialog boxes when not in testing mode, and always installs a requested extension.

**Comment by jcfr** [comment]
> Can you check this [PR](https://github.com/vmtk/SlicerExtension-VMTK/pull/81) for a final resolution of this issue ?

@chir-set  Thanks for creating the branch, the corresponding changes have been reviewed and contributed in a dedicated pull request:
* https://github.com/Slicer/Slicer/pull/7145
