### ISSUE TITLE
Plane handler visibility is not updated correctly on using slice slider 

### ISSUE THREAD

**Issue by malbi** [Slicer/Slicer#6922]
## Summary

Reproduced in Slicer-5.3.0-2023-04-01-linux-amd64.

When a plane interaction handler is displayed in 2D views for a markup plane, its visibility is not updated correctly when changing slice.

## Steps to reproduce

- Create a markup plane
- Enable the translate interaction option
- Change slice displayed using the slider
- The interaction handler visibility is one slice update off and is correctly update when mouse pass over it.

https://user-images.githubusercontent.com/26160797/229798545-03eb3818-74b1-49d7-a8c7-3e2414fecb2d.mp4

## Expected behavior

Interaction handler disappear when it is not on the slice displayed.

## Environment

- Slicer version: Slicer-5.3.0-2023-04-01-linux-amd64.
- Linux Ubuntu 20.04.1

**Comment by lassoan** [comment]
Thank you, I was able to reproduce the behavior on Windows, too.

@Sunderlandkyl could you have a look at this?
