### ISSUE TITLE
Switch to ITK's grow from seeds algorithm implementation

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#6936]
The grow from seeds algorithm in Slicer was ported into ITK. We should switch to it to reduce the maintenance workload.

Before we switch, we need to test if ITK's implementation has
- has the same features (masking, seed locality, incremental update, etc.)
- has the same performance (speed, memory usage), and
- provides the same segmentation result.

Also try if it works for a single-slice input image.

**Comment by jamesobutler** [comment]
Yes the GrowCut module began to be built as part of Slicer's ITK configuration in https://github.com/Slicer/Slicer/commit/846de4444b60e9fba80bcbaaff979e751deb2af9, but the work to actually begin using it hasn't occurred. @dzenanz stated he could support someone's effort to begin using the ITK version.
