### ISSUE TITLE
Support enabling thick slab reconstruction through user interface

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#6965]
## Is your feature request related to a problem? Please describe.

Enabling thick slab reconstruction as well as selection of the composite method (min, max, mean or sum) is available through the python console[^1]. 

[^1]: https://slicer.readthedocs.io/en/latest/developer_guide/script_repository/volumes.html#thick-slab-reconstruction-and-maximum-minimum-intensity-volume-projections

For user without scripting skills and good understanding of the data model[^2], this is a challenging approach.

[^2]: https://slicer.readthedocs.io/en/latest/developer_guide/mrml_overview.html

It also requires additional work to convert thickness usually expressed in `mm` to a `number of slices` required to configure the `vtkImageReslice`[^3] filter used in the script.

[^3]: https://vtk.org/doc/nightly/html/classvtkImageReslice.html#a7dcce2c2e7103bb2e8a43cea40301ba8

## Describe the solution you'd like

Update the Slice viewer controller to allow user to:
- Enable/disable thick slab reconstruction
- Integrate with the "View link" feature
- Select the compositing mode
- Define the slab thickness in mm.

## Describe alternatives you've considered

* See [QReads](https://github.com/KitwareMedical/SlicerQReads/blob/d40ce875aa49f396fc8fe2b578e477d6cd02894f/Modules/Scripted/QReads/QReads.py#L609-L613) scripted for implementation of function like `slabThicknessInMmToNumberOfSlices`

### Excerpt copied from the historical `slicer-devel@bwh.harvard.edu`

From @lassoan / Nov 7, 2015

> This feature is already available in Slicer, but we haven't added a user interface to configure it. You can enable it by a few lines of Python script as described here:

From Marta / Mar 3, 2017

> [...] I ran into this old post while trying to find out how to show MIP in the
slice viewers and was wondering how it would be possible to toggle between
the "resliced" and the original view in the same window (e.g. with a
button), instead of having two windows showing the "resliced" and original
view at the same time. [...]

> what is exactly the slabSliceSpacingFraction?
>
> I find the explanation here[^4] a bit confusing:
> ```
> The slab spacing as a fraction of the output slice spacing.
> When one of the various slab modes is chosen, each output slice is produced
> by generating several "temporary" output slices and then combining them
> according to the slab mode. By default, the spacing between these temporary
> slices is the Z component of the OutputSpacing. This method sets the spacing
> between these temporary slices to be a fraction of the output spacing.
>

[^4]: https://vtk.org/doc/nightly/html/classvtkImageReslice.html#adfcc3bd9a2f04a17e4328d437cb40947

From @lassoan  / Mar 3, 2017

> Unfortunately, it is not easy to interpret those parameters - I didn't implement a GUI on Slicer to set the slab thickness because I did not have time to figure this out. Probably the best is to keep reading the documentation, source code of the filter, perform tests, maybe ask the filter's author - and once you've found how it works exactly, report back to us.

**Comment by lassoan** [comment]
Displaying essential image quality information (such as slice thickness) in corner annotations could be useful, but reflecting the slice thickness in slice intersections would be important, too. For example, we could add thinner, more transparent, or dashed lines to indicate the thickness of the slice. In interactive slice intersection mode, the user could adjust the slice thickness using keyboard modifiers or by grabbing some handles on the intersection widget.

**Comment by stephencrowell** [comment]
The basic UI elements have been implemented. These changes introduce a new button for slab reconstruction. The image below shows the drop down menu. 

![image75](https://github.com/Slicer/Slicer/assets/85647068/a41d539e-07c6-4fe9-bce3-5be486aab0c4)

The checkbox item will toggle the slab reconstruction on the volume. The Slab Thickness spin box controls the thickness of the slab in mm. The other four options are the type of slab reconstruction should be performed.

Once enabled, the image below shows what the view will look like.

![Screenshot from 2023-06-13 13-43-28](https://github.com/Slicer/Slicer/assets/85647068/67bfad78-f873-4f8b-8e5b-ed6dcfe0422a)

The top right corner shows what type of reconstruction is happening and the thickness of the slab in mm.

If you have any suggestions/comments on the UI, please let me know.

Once the basic UI is finished, the next steps are to add more interactive controls similar to how @lassoan described. Some sort of dashed lines that can control the slab thickness would be optimal; however, I am open to any suggestions/comments of other ways to control the slab thickness.
