### ISSUE TITLE
Correctly handle non-modified terminology type properties

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#6972]
## Summary

If selecting "No type modifier" for a terminology type that has modifiers, then the non-modified properties (e.g. color) should be correctly used instead of leaving them undefined/invalid.

See details https://discourse.slicer.org/t/terminologies-questions/27384/20

## Steps to reproduce

First, need to edit the terminology json to specify a color for the "non-modified" type. For example add this
```
            "recommendedDisplayRGBValue": [
              203,
              179,
              77
            ],
```
above this line
https://github.com/Slicer/Slicer/blob/main/Modules/Loadable/Terminologies/Resources/SegmentationCategoryTypeModifier-SlicerGeneralAnatomy.json#L1554
(the file can be found in Windows Slicer installations here: `c:\Users\[UserName]\AppData\Local\slicer.org\Slicer 5.3.0-2023-05-14\share\Slicer-5.3\qt-loadable-modules\Terminologies\SegmentationCategoryTypeModifier-SlicerGeneralAnatomy.term.json`)

* Load TinyPatient sample data (need to have Developer mode enabled)
* Go to Data module
* Double-click color of the `Body_Contour` segment
* Select `Frontal bone` terminology type

## Expected behavior

Color should be yellow instead of the undefined gray.

## Environment
- Slicer version: Slicer 5.3.0-2023-05-14
- Operating system: Windows 11

**Comment by smrolfe** [comment]
I created a [pull request](https://github.com/Slicer/Slicer/pull/6973) with my suggested solution. Assigning a type with no modifiers the color of the first modifier would be consistent with the assignment of the color box icon in the Property types viewer.

**Comment by cpinter** [comment]
Thank you very much @smrolfe (and sorry for the long process)! Unless I'm missing something this can be closed.
