### ISSUE TITLE
How to sub class QWidget

### ISSUE THREAD

**Issue by Fokatu** [Slicer/Slicer#6981]
I write the following code, but it does not work
thanks!

```
import qt

class MyWidget(qt.QWidget):
  def __init__(self, parent=None):
    try:
      super().__init__(parent=parent)
    except Exception as e:
      print(e)


try:
  w = MyWidget()
  w.show()
except Exception as e:
  print(e)
```

**Comment by lassoan** [comment]
You can search for `(qt.qwidget)` in .py files in the Slicer source code for working examples.

The issue tracker is for tracking problems and planned enhancements for Slicer core. Next time you need help with using or programming Slicer, please post it on the Slicer Forum: https://discourse.slicer.org
