### ISSUE TITLE
pointer invalid in vtkSlicerSegmentationsModuleLogic.cxx

### ISSUE THREAD

**Issue by maddin200** [Slicer/Slicer#6987]
Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx line 1430

```cpp
    // Set segment name
    if (!labelName)
      {
      std::stringstream ss;
      ss << "Label_" << label;
      labelName = ss.str().c_str();
      }
    segment->SetName(labelName); // <- pointer could be invalid (ss only local)
```

**Comment by lassoan** [comment]
Good catch. Please send a pull request!

It is great if you can report such problems, but to streamline the process please send them as pull requests. Thank you!
