### ISSUE TITLE
unused variable

### ISSUE THREAD

**Issue by maddin200** [Slicer/Slicer#6989]
/Libs/MRML/Core/vtkCacheManager.cxx line 222
Code:
int vtkCacheManager::LocalFileExists ( const char *uri )
{
  int index;
  std::string uriString (uri);
  std::string prefix; // <- unused
  std::string filename;

**Comment by maddin200** [comment]
https://github.com/Slicer/Slicer/pull/6991

**Comment by lassoan** [comment]
Thank you! Since we have the pull request, I close this issue now.
