### ISSUE TITLE
Slicer command line options not working with 5.2.2 on Windows from cmd or powershell

### ISSUE THREAD

**Issue by sjh26** [Slicer/Slicer#7012]
## Summary

When running Slicer.exe with command line options, nothing occurs and the process immediately exits.  Example:

![Screenshot 2023-06-09 13 02 23](https://github.com/Slicer/Slicer/assets/25040869/13e8963f-1bcd-47d4-95eb-44837dbd0a9d)

I am not seeing this happen when running the same command in git bash:
![Screenshot 2023-06-09 13 03 36](https://github.com/Slicer/Slicer/assets/25040869/673aaff2-f664-413d-9209-8219318c0c2f)

## Steps to reproduce

1. Download and install 5.2.2
2. Launch cmd.exe and cd to the Slicer installation location
3. run `.\Slicer.exe --help`

## Expected behavior

The launcher instructions should be printed

## Environment
- Slicer version: Slicer-5.2.2
- Operating system: Windows 10

**Comment by lassoan** [comment]
This is the expected behavior of non-console applications on Windows. See more information here: https://slicer.readthedocs.io/en/latest/developer_guide/debugging/tips.html#console-output-on-windows

**Comment by sjh26** [comment]
got it, thanks!
