### ISSUE TITLE
Viewing DICOM metadata of a particular patient in the DICOM database always shows the data of the first added patient

### ISSUE THREAD

**Issue by ivezakis** [Slicer/Slicer#7037]
## Steps to reproduce

Select the "Add DICOM Data" module, then import a few different DICOM directories. Patients should start showing in the DICOM database. Right click on any patient except for the one added first, and click "View DICOM metadata". The metadata for the first added patient shows, irrespective of which patient was clicked on.

Note: This behavior stops upon reordering the patients by clicking on any property, such as "Last study date".

## Environment
- Slicer version: 5.2.2 r31382 / fb46bd1
- Operating system: Windows 11

**Comment by ivezakis** [comment]
I have also been unable to reproduce this issue since. I had a fresh slicer installation then, so maybe this could have something to do with it. As mentioned, the moment I reordered the patients, the issue was fixed.

Seems the issue is much less minor than I thought.

**Comment by lassoan** [comment]
Closing it as not reproducible.
