### ISSUE TITLE
License file contains typo

### ISSUE THREAD

**Issue by luzpaz** [Slicer/Slicer#7056]
## Summary

Heads up: there is a typo in the License.txt file https://github.com/Slicer/Slicer/blob/183584877ff421e18a7bdeff893bf651ad14ffd1/License.txt#L82
should obviously be `REQUIRES`

## Steps to reproduce

n/a

## Expected behavior

n/a

## Environment

n/a

**Comment by RafaelPalomar** [comment]
Thanks for reporting @luzpaz!
