### ISSUE TITLE
Faild to run py.files on local slicer environment. 

### ISSUE THREAD

**Issue by ML-lilith** [Slicer/Slicer#7066]
## Summary
Faild to run py.files on local slicer environment. 

## Steps to reproduce
I tried to run a py.file on local slicer environment.   According to Script repository. I tried to run my python file on slicer environment by commands "Slicer.exe --python-script. main_window.py" on pycharm python console. However, no matter what py.files I choosed. The output always is :

Traceback (most recent call last):
File "C:\Users\mingl\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-20-d6f7f82fa517>", line 1, in <module>
Slicer.exe --python-script. main_window.py
NameError: name 'Slicer' is not defined. Even when I try the example.py generated by model"extension wizard"

My python package is inside the extension packages created by extension wizard. 
the py.files path is :C:\D\S4D\Slicer-build\Extensions\cicerone_extensions\Cicerone_Extension\scripted_python\cicerone\main_window.py

Notes:
scripted_python was created by extension wizard. 

folder-cicerone included the python files which will be verified in local slicer environment. 

main_window.py is trying to create widges. Mainly used PyQt5. 

## Expected behavior
Test own python files on local slicer environment.

## Environment
my slicer version is debugger version 5.3. Based on windows 11.  Debugger tool: pycharm. configuration: Slicer remote debugger. python 3.9.

**Comment by pieper** [comment]
The command `Slicer.exe --python-script. main_window.py` is meant to be run in a command terminal.  Also you need to provide the full path to Slicer.exe if you haven't changed into that directory.

Usually you will need a command like this:
`C:\Users\piepe\AppData\Local\slicer.org\Slicer 5.3.0-2023-07-01\Slicer.exe`
