### ISSUE TITLE
BUG: Condition always true

### ISSUE THREAD

**Issue by maddin200** [Slicer/Slicer#7067]
/Modules/Loadable/Colors/qSlicerColorsReader.cxx line 96
Code:
 if (confidence > 0 || confidence < 0.55) // <-- always true (probably &&)
    {
    // Generic file extension, inspect the content
    QString upperCaseFileName = fileName.toUpper();
    if (upperCaseFileName.endsWith("TXT"))
      {

**Comment by maddin200** [comment]
same stuff:
[D:/Data/OpenSource/Slicer-main/Modules/Loadable/Markups/qSlicerMarkupsReader.cxx line 106

**Comment by maddin200** [comment]
and here as well:
Modules/Loadable/Terminologies/qSlicerTerminologiesReader.cxx line 96

**Comment by pieper** [comment]
@maddin200 thanks for the reports 👍 

It would help if you included links to the code in question in the github repository.  Even better, could you provide pull requests with proposed fixes so that we can get these resolved?
