### ISSUE TITLE
Bug: Identical expression

### ISSUE THREAD

**Issue by maddin200** [Slicer/Slicer#7068]
Libs/MRML/Core/vtkMRMLVolumeSequenceStorageNode.cxx line524:
 
if (currentFrameVolumeDimensions[0] != frameVolumeDimensions[0] 
    || currentFrameVolumeDimensions[0] != frameVolumeDimensions[0] // <-- identical
    || currentFrameVolumeDimensions[0] != frameVolumeDimensions[0]

**Comment by pieper** [comment]
Thanks for reporting @maddin200 .  Are you able to provide a pull request with a fix?  @lassoan you may want to have a look too.

For reference: https://github.com/Slicer/Slicer/blob/main/Libs/MRML/Core/vtkMRMLVolumeSequenceStorageNode.cxx#L523-L526
