### ISSUE TITLE
unused variable in vtkMRMLAnnotationRulerStorageNode and vtkMRMLAnnotationNode

### ISSUE THREAD

**Issue by maddin200** [Slicer/Slicer#7086]
Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationRulerStorageNode.cxx line 80

Code:
  int sel = 1, vis = 1;
  std::string annotation; // <-- unused

**Comment by maddin200** [comment]
same stuff  Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationNode.cxx line 113
std::string tmpStr;

**Comment by jamesobutler** [comment]
@maddin200 Can you describe what utility you may be using to find these recent issues that you have reported? That way we can bulk update all issues rather than doing it piecemeal.

**Comment by maddin200** [comment]
@jamesobutler I try out some tools, but I only mentioned issues which I verified myself.

**Comment by jamesobutler** [comment]
Which tools did you use?

**Comment by maddin200** [comment]
gcc with more options
clang -Weverything
clang-tidy
