### ISSUE TITLE
3D Slicer fails to launch on Fedora 38

### ISSUE THREAD

**Issue by Villafruela** [Slicer/Slicer#7088]
## Summary

requirements are met GLIBC 2.17 and GLIBCCC 3.4.19 (i'm above)
mesa-libGLU and libnsl are installed
3D Slicer fails to launch on Fedora 38

## Steps to reproduce
i have GLIBC 2.37-4.fc38 and gcc-c++ 13.1.1-4.fc38
when launched the application does nothing.
Gnome logs shows:
_"gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed"_

## Environment
fedora 38 up to date
Kernel 6.3.12-200

**Comment by pieper** [comment]
We try to make our linux binaries widely compatible, but meeting the requirements of all distributions is beyond our scope.  It would be good if you started a PR to improve the documentation either reporting that it doesn't work or, better, documenting any workarounds you figure out:  https://github.com/Slicer/Slicer/blob/main/Docs/user_guide/getting_started.md#fedora

**Comment by lassoan** [comment]
Linux instructions have been updated, hopefully that addresses similar issues in the future.
