### ISSUE TITLE
Restore View Layout has no affect

### ISSUE THREAD

**Issue by hannah-morilak** [Slicer/Slicer#7095]
## Summary

When looking at the context menu of the slice layouts, if you click "maximize view" on one of the slices, then in the context menu again click "Restore view layout", no change happens, even though double clicking the slice gets you back to the four up view.
![ViewIssue](https://github.com/Slicer/Slicer/assets/105175523/ac4c01d8-780a-43ee-a7d4-a8ad734497b2)

## Steps to reproduce

1. Right click one of the slice viewers
2. Click "Maximize View" [view should maximize]
3. Right click the slice view and click "Restore View Layout" [no change happens]

## Expected behavior

Restore view layout should appropriately restore the layout.

## Environment
- Slicer version: Slicer-5.3.000-2023-04-11
- Operating system: Windows

**Comment by lassoan** [comment]
Excellent error report, thank you. I was able to reproduce the issue and will push a fix within a few days.
