### ISSUE TITLE
References to non-existing Slicer coordinate system page

### ISSUE THREAD

**Issue by jhlegarreta** [Slicer/Slicer#7099]
I have found a location
https://slicer.readthedocs.io/en/latest/developer_guide/modules/transforms.html ("(see Coordinate systems page for details)")

where readers are referred to a Slicer coordinate system page that is not linked or does not exist. 

There may be other locations where the cross-reference is missing as well, or maybe there is one where the page is actually linked but I have not found them.

I have found other miscellaneous sections that maybe related:
https://slicer.readthedocs.io/en/latest/developer_guide/style_guide.html#coordinate-systems
https://slicer.readthedocs.io/en/latest/user_guide/data_loading_and_saving.html#on-use-of-lps-ras-coordinate-systems

I am wondering whether there is actually a Slicer coordinate system page. If yes, I would be willing to submit a patch set to actually link it from the above locations if somebody provides me with the link.

Otherwise, should it be created and the contents in the latter 2 sections be put into there? It seems to me that this is a relevant enough topic to avoid inconsistencies.

PS: Sorry for not having used a template, but this issue does not fit in current templates.

**Comment by jcfr** [comment]
Thanks for the report, waiting we migrate  away from the wiki,  links should the following https://www.slicer.org/wiki/Coordinate_systems

**Comment by jhlegarreta** [comment]
@jcfr Thanks for the early reply. I'd dare to say that this wiki page describes medical imaging coordinate systems in general, but  does not explicitly say which convention is used in Slicer or other details, if they exist. I am happy to help in translating the site to a markdown page and making all this consistent, but IMO if there are other sections that describe coordinate systems, they should be gathered into the same page.

**Comment by jcfr** [comment]
This section may be relevant too. See https://slicer.readthedocs.io/en/latest/user_guide/data_loading_and_saving.html#supported-data-formats

Thanks for offering help moving the page  to the Slicer readthedocs. 

While working on the page, consider using link to the wiki image. We will then upload them to the docs-resource Slicer release before merging.
