### ISSUE TITLE
"Model", "Plane Markups" and "Segmentation Closed Surface"  Slice intersections are broken

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#7101]
## Summary

Model slice intersections worked, at least as of Slicer-5.3.0-2023-04-23 but does not work at least as of Slicer-5.3.0-2023-07-13 and I can reproduce the issue with my local build.  Issue reported by Zora Kikinis with FiberBundles in with SlicerDMRI, but the same issue happens for any model node.

**Update**: Similar issue can be observed with either the Plane markups or a segmentation wotj its master representation being a closed surface. See https://github.com/Slicer/Slicer/pull/7102#pullrequestreview-1533562575

## Steps to reproduce

* Download sample data
* Segment, e.g. sphere brush, and make visible in 3D
* Export to models
* Go to Model Display and enable slice visibility

## Expected behavior

Models should display in slice view but it doesn't.

Instead we get these error messages:
```
Input for connection index 0 on input port index 0 for algorithm vtkCompositeDataGeometryFilter (0x600003b17000) is of type vtkPolyData, but a vtkCompositeDataSet is required.
```

The message is being generated at this call:

https://github.com/Slicer/Slicer/blob/3acf6800e3578015ffd4d23404fcd1ff9bd1337d/Libs/MRML/DisplayableManager/vtkMRMLModelSliceDisplayableManager.cxx#L482

It appears that with the use of this filter was introduced by this commit:

https://github.com/Slicer/Slicer/commit/72914989516fbb7e593e4e1fe1894d65b2c93dab

But something must have changed in a recent version of VTK and needs to be investigated.

## Environment
See summary

**Comment by pieper** [comment]
@lassoan @jcfr @sjh26 FYI, in case you have any ideas.

**Comment by lassoan** [comment]
This is a very significant bug. We should have caught it with automated testing. 

I've noticed the other day that some models don't appear in slice views but I thought we messed up something in our custom modules. I've also noticed the error message but have not had time to investigate it.

I'm quite busy until Thursday. Can someone investigate this? It is almost surely a regression in the new VTK version we switched to.

**Comment by pieper** [comment]
I agree, we definitely want to fix this.  I started looking but figured I'd report what I found so far.  I'm hopeful it's something simple.

**Comment by pieper** [comment]
Turns out it's a trivial fix: `vtkCompositeDataGeometryFilter` -> `vtkGeometryFilter`

I'll make a PR.

**Comment by jcfr** [comment]
For reference, the last VTK updates was introduced in this pull request:
* https://github.com/Slicer/Slicer/pull/7010

The preview release without the update is available using this link:


CDash links:
* After VTK update: https://slicer.cdash.org/index.php?project=SlicerPreview&date=2023-06-26
* Before VTK update:
  * https://slicer.cdash.org/index.php?project=SlicerPreview&date=2023-06-25
  * https://slicer.cdash.org/index.php?project=SlicerPreview&date=2023-06-23

**Comment by pieper** [comment]
After discussion in developer meeting, it is probably better to investigate fixing the regression in VTK proper since that would probably be more useful for the community.
