### ISSUE TITLE
SampleData module minimum width unreasonable

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#7108]
## Summary

In the latest versions the Sample Data module occupies a lot of horizontal space, which is annoying because after that I always have to resize it. I added the flow layout a while ago exactly so that this does not occur, so for me this is a regression.

## Steps to reproduce

* Enter SampleData module

https://github.com/Slicer/Slicer/assets/1325980/29de2b60-6aeb-4929-bd44-edf097a939ea

## Expected behavior

* The module panel is not resized to be super wide, but stays the same

## Environment
- Slicer version: Slicer-5.3.0-2023-07-10
- Operating system: Windows 10

**Comment by lassoan** [comment]
Reverting this CTK commit fixes the issue: https://github.com/commontk/CTK/commit/e6632421274a5dd9cebed881f5714a8aed6e63b9

**Comment by jcfr** [comment]
Since I have been pushing some changes onto CTK, I will take care of updating CTK and Slicer
