### ISSUE TITLE
Curve cut does not work

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#7109]
## Summary

The Curve cut option in Dynamic modeler stopped working.

It worked in 5.2.2. Also in 7a50f6ad1d3250beb633434a40c22e496165b162 (5.3.0 nightly 2023.06.05.)

## Steps to reproduce

* Use Dynamic modeler / Curve cut normally, on any input

https://github.com/Slicer/Slicer/assets/1325980/fc2881d4-e49a-4122-929e-1f15e821acc1

## Expected behavior

* Curve cut cuts the input model with the curve.

## Environment
- Slicer version: Slicer-5.3.0-2023-07-10
- Operating system: Windows 10

**Comment by pieper** [comment]
Are there messages in the console?   It may be related to https://github.com/Slicer/Slicer/issues/7101

**Comment by jcfr** [comment]
@cpinter Thanks for report

@pieper I will generalize the fix so that the other impacted classes[^1] are fixed as well. Then, we will integrate.

[^1]: https://github.com/Slicer/Slicer/pull/7102#pullrequestreview-1533562575

**Comment by jcfr** [comment]
> Are there messages in the console? It may be related to #7101

Issue is still reproducible after fixing #7101

**Comment by cpinter** [comment]
Thanks for looking into this!
There are no errors from C++ or Python. Nothing in the log or the console.

**Comment by jcfr** [comment]
Relevant files:
* https://github.com/Slicer/SlicerSurfaceToolbox/blob/master/DynamicModeler/Logic/vtkSlicerDynamicModelerCurveCutTool.cxx

Related VTK filters:
* https://github.com/Kitware/VTK/commits/master/Filters/Modeling/vtkSelectPolyData.cxx
* https://github.com/Kitware/VTK/commits/master/Filters/Core/vtkClipPolyData.cxx
* https://github.com/Kitware/VTK/commits/master/Filters/Core/vtkConnectivityFilter.cxx

Related pull requests:
* https://github.com/Slicer/Slicer/pull/7010

**Comment by lassoan** [comment]
I got lucky. I looked at the change log and saw this suspicious commit:

https://gitlab.kitware.com/vtk/vtk/-/commit/926ec960d6c80c311faf9ab51ba5b6fd9bf98ddb

I've reverted it and the filter works again!

I don't know how to fix it other than reverting it, the change does not make a whole lot of sense to me. I don't see what was wrong with the original implementation.

**Comment by lassoan** [comment]
The https://gitlab.kitware.com/vtk/vtk/-/blob/master/Filters/Modeling/Testing/Python/TestSelectPolyDataFilter.py?ref_type=heads#L152 test could catch this error by adding this check:

```python
# Selection array range (signed distance from the loop) is expected to be about (-0.421, 8.379).
# If minimum or maximum of the range is near zero on one side then it means that the algorithm failed to split the surface.
if testArray.GetRange()[0] > -0.1:
    raise ValueError("Selection scalar array failed to generate using Dijkstra edge search: larger negative range is expected.")
if testArray.GetRange()[1] < 0.1:
    raise ValueError("Selection scalar array failed to generate using Dijkstra edge search: larger positive range is expected.")
```

**Comment by lassoan** [comment]
@sjh26 could you take this from here? Either revert or fix the breaking commit in VTK?

**Comment by sjh26** [comment]
Can do!

**Comment by jcfr** [comment]
In the meantime, I also posted a comment in the relevant VTK merge request. See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10063#note_1391157

**Comment by cpinter** [comment]
Thanks all for the great teamwork! (I've been on vacation so just looking out for critical stuff)
