### ISSUE TITLE
Create single external link resource page for documentation 

### ISSUE THREAD

**Issue by jhlegarreta** [Slicer/Slicer#7120]
All common refs (e.g. ITK, VTK, etc.) should dwell in a single markdown page and import from there across all the documentation to avoid. Doing this would reduce maintenance: if a link changes, the URL would need to be changed at a single place.

**Comment by lassoan** [comment]
What kind of references do you mean? Can you point out a few specific examples?

**Comment by jhlegarreta** [comment]
> What kind of references do you mean? Can you point out a few specific examples?

@lassoan It's been a while since I had a look at the documentation, and cannot afford trying to go or remember the pages that I may have visited when I opened this. Feel free to close it.

**Comment by lassoan** [comment]
OK, thank you, I'm closing this then. Feel free to reopen if something comes into your mind.
