### ISSUE TITLE
Colorbar does not work for streamline tube display mode

### ISSUE THREAD

**Issue by jhlegarreta** [Slicer/Slicer#7123]
When loading a file that contains tractography streamlines, and when using the "Tube" visualization mode, the colorbar displayed in the 3D view does not match the scalar value that is chosen for the "Tube" option; the colorbar is only able to match the scalar value displayed for the "Line" visualization option.

More context: https://discourse.slicer.org/t/displaying-a-colorbar-across-viewers-for-diffusion-scalar-maps-on-tractography-data/30564

## Steps to reproduce

- Load a tractography data file that contains scalar values associated to its vertices.
- Select the "Tube" visualization option.
- Select a scalar value to be used to color the streamlines.
- Show the colorbar in the 3D view selection `Models`; `ColorLegend`.

## Expected behavior

The colorbar displays correctly the scalar values associated with the "Tube" visualization option.

## Environment

- Slicer version: Slicer-5.2.2
- Operating system: Ubuntu 22.04

**Comment by MichaelColonel** [comment]
Dear @jhlegarreta,

Cay upload a test data somewhere, so i can add color legend (colorbar) support for streamline tubes?
Do you want to control color legend directly from `Tractography Display` module?

**Comment by jhlegarreta** [comment]
@MichaelColonel

> Cay upload a test data somewhere, so i can add color legend (colorbar) support for streamline tubes?

Here is some test data (I had to change the extension; you can drop the `.txt` suffixe when downloading):
[T_IOFF_left.vtp.txt](https://github.com/Slicer/Slicer/files/12906594/T_IOFF_left.vtp.txt)

> Do you want to control color legend directly from the Tractography Display module?

I don't know what is the best option; certainly having to navigate across different panels is not the best option, but duplicating the code into the `Tractography Display` module does not seem either the best solution (e.g. being able to apply the properties both from the `Models` and the `Tractography Display` modules does not seem ideal).

**Comment by MichaelColonel** [comment]
For the start i will add support only in the `Tractography Display` module, because `vtkMRMLFiberBundleNode` can display lines, tubes and glyphs in the same time. Each option (line, tube, glyph) has it's own display node: `vtkMRMLFiberBundleLineDisplayNode`, `vtkMRMLFiberBundleTubeDisplayNode`, `vtkMRMLFiberBundleGlyphDisplayNode` , as a result it must be a separate color legend for each displayed element.

**Comment by MichaelColonel** [comment]
SlicerDMRI [PR](https://github.com/SlicerDMRI/SlicerDMRI/pull/184) is ready

**Comment by jhlegarreta** [comment]
https://github.com/SlicerDMRI/SlicerDMRI/pull/184 was superseded by PR https://github.com/SlicerDMRI/SlicerDMRI/pull/185 and has been merged.

Closing the issue. Thanks for your work @MichaelColonel.
