### ISSUE TITLE
Code problem about data process

### ISSUE THREAD

**Issue by zxy630** [Slicer/Slicer#7128]
Do you preprocess the DICOM while importing? And if so, can you tell me where is the part of the code.

**Comment by jcfr** [comment]
By default, the DICOM are not modified.

Optionally, the `DICOMPatcher` module may be used.

Infrastructure is described in these pages:
* https://slicer.readthedocs.io/en/latest/user_guide/modules/dicom.html
* https://slicer.readthedocs.io/en/latest/developer_guide/modules/dicom.html
* https://slicer.readthedocs.io/en/latest/user_guide/modules/dicompatcher.html

Sources:
* https://github.com/Slicer/Slicer/tree/main/Modules/Scripted/DICOM
* https://github.com/Slicer/Slicer/tree/main/Modules/Scripted/DICOMLib
* https://github.com/Slicer/Slicer/tree/main/Modules/Scripted/DICOMPatcher
* https://github.com/Slicer/Slicer/tree/main/Modules/Scripted/DICOMPlugins

I am now closing this issue. Please, consider asking questions on the forum:
* https://discourse.slicer.org/
* https://slicer.readthedocs.io/en/latest/user_guide/get_help.html
