### ISSUE TITLE
The problem of image quality

### ISSUE THREAD

**Issue by maoyij** [Slicer/Slicer#7130]
We found that the display effect of the same DICOM on 3D slicer and itk is different, and the former is clearer. Do you know why?

**Comment by pieper** [comment]
Many things may be involved.  Please post specific details along with screenshots at the Slicer discourse forum and we can give you suggestions how to proceed.  While we appreciate your participation in the community, this issue tracker is for specific bugs not general questions.

**Comment by lassoan** [comment]
Slicer interpolates the voxels when it displays on screen by default, while ITK-Snap does not. I've described in detail in [this Slicer forum discussion](https://discourse.slicer.org/t/volume-display-interpolate-turned-off-by-default-in-newest-stable/13918/) and illustrated with several examples why interpolation is the right thing to do, but you can disable it.
