### ISSUE TITLE
Slicer build fails if `Slicer_USE_PYTHONQT` is turned off

### ISSUE THREAD

**Issue by jhlegarreta** [Slicer/Slicer#7136]
## Summary

Building Slicer fails if `Slicer_USE_PYTHONQT` is turned off. Slicer should build successfully even if all Python features are turned off, including its dependencies'.

As shown by this GHA workflow build:
https://github.com/jhlegarreta/SlicerDMRI/actions/runs/5695300037/job/15438164734#step:6:21779

Slicer build fails when `Slicer_USE_PYTHONQT` is explicitly set to `OFF`:
https://github.com/jhlegarreta/SlicerDMRI/actions/runs/5695300037/job/15438164734#step:6:20

When the flag is removed (and considering [its default value is `ON`](https://github.com/Slicer/Slicer/blob/968fd241328d3a7b6d5fe632b32db863aabcf90c/CMakeLists.txt#L289)),
https://github.com/jhlegarreta/SlicerDMRI/actions/runs/5701134575/job/15451559662#step:6:30

Slicer compilation continues past that point:
https://github.com/jhlegarreta/SlicerDMRI/actions/runs/5701134575/job/15451559662#step:6:43108
(The build failure above is due to `vtkAddon` having been turned off)

## Steps to reproduce

1. Clone Slicer (`HEAD` revision as of 2023-07-30, 968fd241328d3a7b6d5fe632b32db863aabcf90c).
1. Configure Slicer and set `Slicer_USE_PYTHONQT` to `OFF`.
1. Check the build failure.

## Expected behavior

Slicer should build successfully without requiring any Python feature be turned on. Slicer should not look for any Python installation if not explicitly instructed to look for one, and to build with Python features.

## Environment
- Slicer version: `HEAD` (e.g. as of 2023-07-30, 968fd241328d3a7b6d5fe632b32db863aabcf90c).
- Operating system: Ubuntu 22.04.2 LTS

**Comment by jhlegarreta** [comment]
Setting a docker image without any Python component, and turning off all Python features would be helpful to avoid this.

**Comment by jhlegarreta** [comment]
@jcfr :+1: Will give a try to turning off the flag in `SlicerDMRI`'s CI. If it works, I think it will speed up the build. Thanks.

**Comment by jcfr** [comment]
> If it works, I think it will speed up the build. Thanks.

Considering that Python is integral to `SlicerDMRI`, working on building it against a Slicer built without python support would give you an false sense of success.

When the extension is build, as a sanity check, the scripts are "compiled" into byte-code and disabling python would prevent this from happening.

**Comment by jhlegarreta** [comment]
OK as for `SlicerDMRI`. Thanks for the explanation @jcfr.
