### ISSUE TITLE
Running Total Segmentator after installing last 3D slicer stable version 5.4.0 on Windows 11

### ISSUE THREAD

**Issue by DrKhaldoun** [Slicer/Slicer#7192]
## Summary

<I have installed last stable version 5.4.0 on new computer running on Windows 11 with 16Go ram and 12th Gen Intel(R) Core(TM) i5-12500   3.00 GHz 64 bits without GPU. Running Lung Ct segmentor on a Chest CT to obtain lobes segmentation using CPU AI with Total segmentator module did not work giving the following bug report

## Steps to reproduce
This is the entire log report:

[DEBUG][Qt] 25.08.2023 19:36:04 [] (unknown:0) - Session start time .......: 2023-08-25 19:36:04
[DEBUG][Qt] 25.08.2023 19:36:04 [] (unknown:0) - Slicer version ...........: 5.4.0 (revision 31938 / 311cb26) win-amd64 - installed release
[DEBUG][Qt] 25.08.2023 19:36:04 [] (unknown:0) - Operating system .........: Windows /  Professional / (Build 22621, Code Page 65001) - 64-bit
[DEBUG][Qt] 25.08.2023 19:36:04 [] (unknown:0) - Memory ...................: 16072 MB physical, 19016 MB virtual
[DEBUG][Qt] 25.08.2023 19:36:04 [] (unknown:0) - CPU ......................: GenuineIntel , 12 cores, 12 logical processors
[DEBUG][Qt] 25.08.2023 19:36:04 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, TBB threading
[DEBUG][Qt] 25.08.2023 19:36:04 [] (unknown:0) - Qt configuration .........: version 5.15.2, with SSL, requested OpenGL 3.2 (compatibility profile)
[DEBUG][Qt] 25.08.2023 19:36:04 [] (unknown:0) - Internationalization .....: disabled, language=
[DEBUG][Qt] 25.08.2023 19:36:04 [] (unknown:0) - Developer mode ...........: disabled
[DEBUG][Qt] 25.08.2023 19:36:04 [] (unknown:0) - Application path .........: C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/bin
[DEBUG][Qt] 25.08.2023 19:36:04 [] (unknown:0) - Additional module paths ..: slicer.org/Extensions-31938/DICOMwebBrowser/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/DCMQI/lib/Slicer-5.4/cli-modules, slicer.org/Extensions-31938/DensityLungSegmentation/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/ExtraMarkups/lib/Slicer-5.4/qt-loadable-modules, slicer.org/Extensions-31938/LungCTAnalyzer/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/MarkupsToModel/lib/Slicer-5.4/qt-loadable-modules, slicer.org/Extensions-31938/OpenDose3D/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/PET-IndiC/lib/Slicer-5.4/cli-modules, slicer.org/Extensions-31938/PET-IndiC/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/PET-MUST-Segmenter/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/PETCPhantom/lib/Slicer-5.4/cli-modules, slicer.org/Extensions-31938/PETCPhantom/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/PETDICOMExtension/lib/Slicer-5.4/cli-modules, slicer.org/Extensions-31938/PETDICOMExtension/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/PETLiverUptakeMeasurement/lib/Slicer-5.4/cli-modules, slicer.org/Extensions-31938/PETLiverUptakeMeasurement/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/PETTumorSegmentation/lib/Slicer-5.4/qt-loadable-modules, slicer.org/Extensions-31938/PETTumorSegmentation/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/PyTorch/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/QuantitativeReporting/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/SegmentEditorExtraEffects/lib/Slicer-5.4/qt-loadable-modules, slicer.org/Extensions-31938/SegmentEditorExtraEffects/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/SlicerDevelopmentToolbox/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/SlicerFreeSurfer/lib/Slicer-5.4/qt-loadable-modules, slicer.org/Extensions-31938/SlicerNeuroSegmentation/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/SlicerRadiomics/lib/Slicer-5.4/cli-modules, slicer.org/Extensions-31938/SlicerRadiomics/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/TCIABrowser/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/SlicerLiver/lib/Slicer-5.4/qt-loadable-modules, slicer.org/Extensions-31938/SlicerLiver/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/SurfaceWrapSolidify/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/TotalSegmentator/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/SlicerElastix/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/SlicerVMTK/lib/Slicer-5.4/qt-loadable-modules, slicer.org/Extensions-31938/SlicerVMTK/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/SlicerRT/lib/Slicer-5.4/cli-modules, slicer.org/Extensions-31938/SlicerRT/lib/Slicer-5.4/qt-loadable-modules, slicer.org/Extensions-31938/SlicerRT/lib/Slicer-5.4/qt-scripted-modules, slicer.org/Extensions-31938/RVesselX/lib/Slicer-5.4/qt-scripted-modules
[CRITICAL][Stream] 25.08.2023 19:36:05 [] (unknown:0) - Failed to load vtkSlicerCrossSectionAnalysisModuleLogicPython: No module named vtkSlicerShapeModuleMRMLPython
[CRITICAL][Stream] 25.08.2023 19:36:05 [] (unknown:0) - Failed to load vtkSlicerStenosisMeasurement3DModuleLogicPython: No module named vtkSlicerShapeModuleMRMLPython
[DEBUG][Python] 25.08.2023 19:36:06 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\sentry_sdk\scope.py:205) - [Tracing] Create new propagation context: {'trace_id': '84e84abb085f434c9150e9fb75822338', 'span_id': 'a5160f4e692046b0', 'parent_span_id': None, 'dynamic_sampling_context': None}
[DEBUG][Python] 25.08.2023 19:36:07 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\matplotlib\__init__.py:334) - matplotlib data path: C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\matplotlib\mpl-data
[DEBUG][Python] 25.08.2023 19:36:07 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\matplotlib\__init__.py:334) - CONFIGDIR=C:\Users\g-tnn5367812\.matplotlib
[DEBUG][Python] 25.08.2023 19:36:07 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\matplotlib\__init__.py:1508) - interactive is False
[DEBUG][Python] 25.08.2023 19:36:07 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\matplotlib\__init__.py:1509) - platform is win32
[INFO][Stream] 25.08.2023 19:36:09 [] (unknown:0) -
[INFO][Stream] 25.08.2023 19:36:09 [] (unknown:0) - [notice] A new release of pip is available: 23.1.2 -> 23.2.1
[INFO][Stream] 25.08.2023 19:36:09 [] (unknown:0) - [notice] To update, run: python-real.exe -m pip install --upgrade pip
[DEBUG][Python] 25.08.2023 19:36:09 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\matplotlib\__init__.py:334) - CACHEDIR=C:\Users\g-tnn5367812\.matplotlib
[DEBUG][Python] 25.08.2023 19:36:09 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\matplotlib\font_manager.py:1543) - Using fontManager instance from C:\Users\g-tnn5367812\.matplotlib\fontlist-v330.json
[CRITICAL][Qt] 25.08.2023 19:36:09 [] (unknown:0) -   Error(s):
    CLI executable: C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/SlicerVMTK/lib/Slicer-5.4/qt-loadable-modules/vtkvmtk.py
    The process failed to start. Either the invoked program is missing, or you may have insufficient permissions to invoke the program.
[CRITICAL][Qt] 25.08.2023 19:36:09 [] (unknown:0) - Fail to instantiate module  "vtkvmtk"
[CRITICAL][Qt] 25.08.2023 19:36:09 [] (unknown:0) - The following modules failed to be instantiated:
[CRITICAL][Qt] 25.08.2023 19:36:09 [] (unknown:0) -    vtkvmtk
[DEBUG][Python] 25.08.2023 19:36:10 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Slicer-5.4\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:38) - Scripted subject hierarchy plugin registered: SegmentStatistics
[DEBUG][Python] 25.08.2023 19:36:10 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Slicer-5.4\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:38) - Scripted subject hierarchy plugin registered: SegmentEditor
[DEBUG][Qt] 25.08.2023 19:36:11 [] (unknown:0) - Switch to module:  "Welcome"
[DEBUG][Qt] 25.08.2023 19:36:15 [] (unknown:0) - Switch to module:  "DICOM"
[DEBUG][Python] 25.08.2023 19:36:19 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\slicer.org\Extensions-31938\QuantitativeReporting\lib\Slicer-5.4\qt-scripted-modules\base\DICOMPluginBase.py:52) - DICOMParametricMapPluginClass : Caching files
[DEBUG][Python] 25.08.2023 19:36:19 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\slicer.org\Extensions-31938\QuantitativeReporting\lib\Slicer-5.4\qt-scripted-modules\base\DICOMPluginBase.py:49) - DICOMParametricMapPluginClass : Using cached files
[WARNING][Python] 25.08.2023 19:36:19 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Slicer-5.4\qt-scripted-modules\DICOMLib\DICOMUtils.py:697) - Geometric issues were found with 1 of the series. Please use caution.
[DEBUG][Python] 25.08.2023 19:36:19 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\slicer.org\Extensions-31938\QuantitativeReporting\lib\Slicer-5.4\qt-scripted-modules\base\DICOMPluginBase.py:52) - DICOMSegmentationPluginClass : Caching files
[DEBUG][Python] 25.08.2023 19:36:19 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\slicer.org\Extensions-31938\QuantitativeReporting\lib\Slicer-5.4\qt-scripted-modules\base\DICOMPluginBase.py:49) - DICOMSegmentationPluginClass : Using cached files
[DEBUG][Python] 25.08.2023 19:36:19 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\slicer.org\Extensions-31938\QuantitativeReporting\lib\Slicer-5.4\qt-scripted-modules\base\DICOMPluginBase.py:52) - DICOMTID1500PluginClass : Caching files
[DEBUG][Python] 25.08.2023 19:36:20 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\slicer.org\Extensions-31938\QuantitativeReporting\lib\Slicer-5.4\qt-scripted-modules\base\DICOMPluginBase.py:49) - DICOMTID1500PluginClass : Using cached files
[WARNING][Python] 25.08.2023 19:36:23 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Slicer-5.4\qt-scripted-modules\DICOMLib\DICOMBrowser.py:568) - Warning in DICOM plugin Scalar Volume when examining loadable 4: Poumons  2.5  B70s: Images are not equally spaced (a difference of 1.7 vs 0 in spacings was detected).  Slicer will apply a transform to this series trying to regularize the volume. Please use caution.
[INFO][Python] 25.08.2023 19:36:23 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\bin\Python\slicer\util.py:2909) - Warnings detected during load.  Examine data in Advanced mode for details.  Load anyway?
[INFO][Python] 25.08.2023 19:36:24 [Python] (C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/qt-scripted-modules/DICOMScalarVolumePlugin.py:400) - Loading with imageIOName: GDCM
[WARNING][ITK] 25.08.2023 19:36:28 [] (unknown:0) - WARNING: In D:\D\S\S-0-build\ITK\Modules\IO\ImageBase\include\itkImageSeriesReader.hxx, line 478
ImageSeriesReader (000001658172B860): Non uniform sampling or missing slices detected,  maximum nonuniformity:0.851972
[INFO][Python] 25.08.2023 19:36:28 [Python] (C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/qt-scripted-modules/DICOMScalarVolumePlugin.py:479) - Window/level found in DICOM tags (center=-600.0, width=1200.0) has been applied to volume 4: Poumons  2.5  B70s
[WARNING][Python] 25.08.2023 19:36:28 [Python] (C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/qt-scripted-modules/DICOMScalarVolumePlugin.py:844) - Irregular volume geometry detected (maximum error of 0.848028 mm is above tolerance threshold of 0.001 mm).  Adding acquisition transform to regularize geometry.
[WARNING][VTK] 25.08.2023 19:36:28 [vtkOrientedGridTransform (00000165D339C7D0)] (vtkOrientedGridTransform.cxx:335) - InverseTransformPoint: no convergence (361.961, 173.488, 1580.09) error = 1.90871e+12 after 500 iterations.  Further convergence warnings suppressed until transform is modified.
[WARNING][VTK] 25.08.2023 19:36:28 [vtkOrientedGridTransform (00000165D339C7D0)] (vtkOrientedGridTransform.cxx:335) - InverseTransformPoint: no convergence (361.961, 173.488, 1335.49) error = 6.26942e+12 after 500 iterations.  Further convergence warnings suppressed until transform is modified.
[WARNING][VTK] 25.08.2023 19:36:28 [vtkOrientedGridTransform (00000165D339C7D0)] (vtkOrientedGridTransform.cxx:335) - InverseTransformPoint: no convergence (361.961, 173.488, 1518.66) error = 2.90981e+12 after 500 iterations.  Further convergence warnings suppressed until transform is modified.
[WARNING][VTK] 25.08.2023 19:36:28 [vtkOrientedGridTransform (00000165D339C7D0)] (vtkOrientedGridTransform.cxx:335) - InverseTransformPoint: no convergence (361.961, 173.488, 1398.01) error = 1.90885e+12 after 500 iterations.  Further convergence warnings suppressed until transform is modified.
[WARNING][VTK] 25.08.2023 19:36:28 [vtkOrientedGridTransform (00000165D339C7D0)] (vtkOrientedGridTransform.cxx:335) - InverseTransformPoint: no convergence (361.961, 173.488, 1428.72) error = 5.00532e+11 after 500 iterations.  Further convergence warnings suppressed until transform is modified.
[WARNING][VTK] 25.08.2023 19:36:28 [vtkOrientedGridTransform (00000165D339C7D0)] (vtkOrientedGridTransform.cxx:335) - InverseTransformPoint: no convergence (361.961, 173.488, 1459.44) error = 2.90986e+12 after 500 iterations.  Further convergence warnings suppressed until transform is modified.
[DEBUG][Qt] 25.08.2023 19:36:36 [] (unknown:0) - Switch to module:  "LungCTSegmenter"
[DEBUG][Python] 25.08.2023 19:36:36 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\urllib3\connectionpool.py:244) - Starting new HTTP connection (1): scientific-networks.de:80
[DEBUG][Python] 25.08.2023 19:36:36 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\urllib3\connectionpool.py:546) - http://scientific-networks.de:80 "GET /get_counter_values.php?api_key=WVnB2F7Uibt2TC HTTP/1.1" 200 None
[ERROR][VTK] 25.08.2023 19:36:36 [vtkMRMLSliceNode (00000165F3E11060)] (vtkMRMLSliceNode.cxx:1921) - Cannot handle non-linear transforms
[ERROR][VTK] 25.08.2023 19:36:36 [vtkMRMLSliceNode (00000165F3E0D820)] (vtkMRMLSliceNode.cxx:1921) - Cannot handle non-linear transforms
[ERROR][VTK] 25.08.2023 19:36:36 [vtkMRMLSliceNode (00000165F3E12000)] (vtkMRMLSliceNode.cxx:1921) - Cannot handle non-linear transforms
[INFO][VTK] 25.08.2023 19:36:44 [vtkSlicerCLIModuleLogic (00000165F6EFC120)] (D:\D\S\S-0\Base\QTCLI\vtkSlicerCLIModuleLogic.cxx:870) - Found CommandLine Module, target is C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/cli-modules/ResampleScalarVolume.exe
[INFO][VTK] 25.08.2023 19:36:44 [vtkSlicerCLIModuleLogic (00000165F6EFC120)] (D:\D\S\S-0\Base\QTCLI\vtkSlicerCLIModuleLogic.cxx:888) - ModuleType: CommandLineModule
[INFO][VTK] 25.08.2023 19:36:44 [vtkSlicerCLIModuleLogic (00000165F6EFC120)] (D:\D\S\S-0\Base\QTCLI\vtkSlicerCLIModuleLogic.cxx:1729) - Resample Scalar Volume command line: 

C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/cli-modules/ResampleScalarVolume.exe --spacing 2.0,2.0,2.0 --interpolation linear C:/Users/g-tnn5367812/AppData/Local/Temp/Slicer/BFGJG_vtkMRMLScalarVolumeNodeB.nrrd C:/Users/g-tnn5367812/AppData/Local/Temp/Slicer/BFGJG_vtkMRMLScalarVolumeNodeC.nrrd
[INFO][VTK] 25.08.2023 19:36:45 [vtkSlicerCLIModuleLogic (00000165F6EFC120)] (D:\D\S\S-0\Base\QTCLI\vtkSlicerCLIModuleLogic.cxx:1943) - Resample Scalar Volume completed without errors
[WARNING][Qt] 25.08.2023 19:36:45 [] (unknown:0) - QLayout::addChildLayout: layout "" already has a parent
[WARNING][Qt] 25.08.2023 19:36:45 [] (unknown:0) - libpng warning: iCCP: known incorrect sRGB profile
[WARNING][Qt] 25.08.2023 19:36:45 [] (unknown:0) - ctkSliderWidget::setSingleStep()  0 is out of bounds. 0 1000 1
[INFO][Python] 25.08.2023 19:36:45 [Python] (C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/LungCTAnalyzer/lib/Slicer-5.4/qt-scripted-modules/LungCTSegmenter.py:1540) - StartSegmentation completed in 1.19 seconds
[INFO][Python] 25.08.2023 19:36:45 [Python] (C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/LungCTAnalyzer/lib/Slicer-5.4/qt-scripted-modules/LungCTSegmenter.py:1112) - Saving markups in temp directory ...
[DEBUG][Python] 25.08.2023 19:36:45 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\urllib3\connectionpool.py:244) - Starting new HTTP connection (1): scientific-networks.de:80
[DEBUG][Python] 25.08.2023 19:36:45 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\urllib3\connectionpool.py:546) - http://scientific-networks.de:80 "GET /increment_counter.php?api_key=WVnB2F7Uibt2TC&counter=counter_lcts HTTP/1.1" 200 None
[INFO][Python] 25.08.2023 19:36:46 [Python] (C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/LungCTAnalyzer/lib/Slicer-5.4/qt-scripted-modules/LungCTSegmenter.py:2282) - Pytorch CUDA is not available. AI will use CPU processing.
[INFO][Python] 25.08.2023 19:36:46 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\bin\Python\slicer\util.py:2909) - Warning: Pytorch CUDA is not found on your system. The AI processing will last 3-10 minutes. Are you sure you want to continue AI segmentation?
[DEBUG][Python] 25.08.2023 19:36:50 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\urllib3\connectionpool.py:244) - Starting new HTTP connection (1): scientific-networks.de:80
[DEBUG][Python] 25.08.2023 19:36:50 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\urllib3\connectionpool.py:546) - http://scientific-networks.de:80 "GET /increment_counter.php?api_key=WVnB2F7Uibt2TC&counter=counter_ai HTTP/1.1" 200 None
[WARNING][Qt] 25.08.2023 19:36:58 [] (unknown:0) - ctkSliderWidget::setSingleStep()  0 is out of bounds. 0 100 1
[DEBUG][Python] 25.08.2023 19:36:59 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\urllib3\connectionpool.py:244) - Starting new HTTP connection (1): scientific-networks.de:80
[DEBUG][Python] 25.08.2023 19:36:59 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\urllib3\connectionpool.py:546) - http://scientific-networks.de:80 "GET /increment_counter.php?api_key=WVnB2F7Uibt2TC&counter=counter_ts HTTP/1.1" 200 None
[INFO][Python] 25.08.2023 19:36:59 [Python] (C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/TotalSegmentator/lib/Slicer-5.4/qt-scripted-modules/TotalSegmentator.py:552) - Processing started
[INFO][Python] 25.08.2023 19:36:59 [Python] (C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/TotalSegmentator/lib/Slicer-5.4/qt-scripted-modules/TotalSegmentator.py:552) - Writing input file to C:/Users/g-tnn5367812/AppData/Local/Temp/Slicer/__SlicerTemp__2023-08-25_19+36+59.965/total-segmentator-input.nii
[INFO][Python] 25.08.2023 19:37:00 [Python] (C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/TotalSegmentator/lib/Slicer-5.4/qt-scripted-modules/TotalSegmentator.py:552) - Creating segmentations with TotalSegmentator AI...
[INFO][Python] 25.08.2023 19:37:00 [Python] (C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/TotalSegmentator/lib/Slicer-5.4/qt-scripted-modules/TotalSegmentator.py:552) - Total Segmentator arguments: ['-i', 'C:/Users/g-tnn5367812/AppData/Local/Temp/Slicer/__SlicerTemp__2023-08-25_19+36+59.965/total-segmentator-input.nii', '-o', 'C:/Users/g-tnn5367812/AppData/Local/Temp/Slicer/__SlicerTemp__2023-08-25_19+36+59.965/segmentation', '--ml', '--task', 'total', '--fast']
[INFO][Python] 25.08.2023 19:37:00 [Python] (C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/TotalSegmentator/lib/Slicer-5.4/qt-scripted-modules/TotalSegmentator.py:552) - C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\bin\.\python-real.exe: can't open file 'C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Scripts\TotalSegmentator': [Errno 2] No such file or directory
[ERROR][Python] 25.08.2023 19:37:00 [Python] (C:\Users\g-tnn5367812\AppData\Local\slicer.org\Slicer 5.4.0\bin\Python\slicer\util.py:2909) - Failed to compute results: Command '['C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/bin/../bin\\PythonSlicer.EXE', 'C:\\Users\\g-tnn5367812\\AppData\\Local\\slicer.org\\Slicer 5.4.0\\lib\\Python\\Scripts\\TotalSegmentator', '-i', 'C:/Users/g-tnn5367812/AppData/Local/Temp/Slicer/__SlicerTemp__2023-08-25_19+36+59.965/total-segmentator-input.nii', '-o', 'C:/Users/g-tnn5367812/AppData/Local/Temp/Slicer/__SlicerTemp__2023-08-25_19+36+59.965/segmentation', '--ml', '--task', 'total', '--fast']' returned non-zero exit status 2.
[CRITICAL][Stream] 25.08.2023 19:37:06 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 25.08.2023 19:37:06 [] (unknown:0) -   File "C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/LungCTAnalyzer/lib/Slicer-5.4/qt-scripted-modules/LungCTSegmenter.py", line 1002, in runProcessing
[CRITICAL][Stream] 25.08.2023 19:37:06 [] (unknown:0) -     self.logic.applySegmentation()
[CRITICAL][Stream] 25.08.2023 19:37:06 [] (unknown:0) -   File "C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/LungCTAnalyzer/lib/Slicer-5.4/qt-scripted-modules/LungCTSegmenter.py", line 2418, in applySegmentation
[CRITICAL][Stream] 25.08.2023 19:37:06 [] (unknown:0) -     tslogic.process(self.inputVolume, self.tsOutputSegmentation, True, "total")
[CRITICAL][Stream] 25.08.2023 19:37:06 [] (unknown:0) -   File "C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/TotalSegmentator/lib/Slicer-5.4/qt-scripted-modules/TotalSegmentator.py", line 868, in process
[CRITICAL][Stream] 25.08.2023 19:37:06 [] (unknown:0) -     self.logProcessOutput(proc)
[CRITICAL][Stream] 25.08.2023 19:37:06 [] (unknown:0) -   File "C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/TotalSegmentator/lib/Slicer-5.4/qt-scripted-modules/TotalSegmentator.py", line 701, in logProcessOutput
[CRITICAL][Stream] 25.08.2023 19:37:06 [] (unknown:0) -     raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
[CRITICAL][Stream] 25.08.2023 19:37:06 [] (unknown:0) - subprocess.CalledProcessError: Command '['C:/Users/g-tnn5367812/AppData/Local/slicer.org/Slicer 5.4.0/bin/../bin\\PythonSlicer.EXE', 'C:\\Users\\g-tnn5367812\\AppData\\Local\\slicer.org\\Slicer 5.4.0\\lib\\Python\\Scripts\\TotalSegmentator', '-i', 'C:/Users/g-tnn5367812/AppData/Local/Temp/Slicer/__SlicerTemp__2023-08-25_19+36+59.965/total-segmentator-input.nii', '-o', 'C:/Users/g-tnn5367812/AppData/Local/Temp/Slicer/__SlicerTemp__2023-08-25_19+36+59.965/segmentation', '--ml', '--task', 'total', '--fast']' returned non-zero exit status 2.
[WARNING][VTK] 25.08.2023 19:37:06 [vtkMRMLSegmentationDisplayNode (00000165F533EF20)] (vtkMRMLSegmentationDisplayNode.cxx:295) - vtkMRMLSegmentationDisplayNode::GetSegmentDisplayProperties: no display properties are found for segment ID=, return default

## Environment
- Slicer version: Slicer-5..4.0
- Operating system: Windows 11 professional
- Could you please help as I am not skilled in programming 
- Thank you
-

**Comment by lassoan** [comment]
There have been lots of improvements in the robustness of TotalSegmentator installation. If you still experience any difficulties then please write to the Slicer forum (https://discourse.slicer.org) or to the SlicerTotalSegmentator extension's repository (not to this issue tracker, as it is not a Slicer core problem).
