### ISSUE TITLE
securityscorecards: Address false postive report related to release not being signed

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#7198]
## Summary

Following the integration of https://github.com/Slicer/Slicer/pull/7197, a list of checks are performed with the intent of given a "security" score.

Considering that:

* our macOS and Windows release packages are effectively signed[^1]
* release packages are not stored as GitHub release assets

this is misleading.

[^1]: https://github.com/Slicer/Slicer/wiki/Signing-Application-Packages

## Steps to reproduce

| See https://securityscorecards.dev/viewer/?uri=github.com/Slicer/Slicer |
|--|
| ![image](https://github.com/Slicer/Slicer/assets/219043/714d55d5-73a0-41c4-b9b8-bf1ea66ebf38) |

## Expected behavior

The `docs-resources` should either not be scored or should be marked as "signed".

**Comment by jamesobutler** [comment]
Considering that it is pretty common to be able to download new releases from the GitHub releases area, could Slicer have official GitHub releases to go along with the git tags for Slicer stable releases? The 3 platforms signed installers and a file with the checksums could be included as release assets. The GitHub release could also serve as secondary download site if the Slicer download webpage is unavailable. 

It appears you can get the download count of release assets by using the GitHub API. See `download_count` fields at https://api.github.com/repos/Slicer/Slicer/releases.

**Comment by lassoan** [comment]
> could Slicer have official GitHub releases to go along with the git tags for Slicer stable releases?

It would have advantage of hosting Slicer packages on GitHub, mostly fast and reliable downloads from a familiar location. However, for all downloads directly from GitHub we would lose location information (we would only know how Slicer does worldwide, but would have no idea about growth in various regions). GitHub may also be banned in countries with heacy censorship, like China, therefore we would still need to maintain our current server infrastructure. We would need to take care of archiving the statistics beyond GitHub's data retention policies and merge it with data we get from our own server. 

Overall, offering release downloads via GitHub would result in less insight, extra development and maintenance efforts, and would not solve any significant issues.

**Comment by jcfr** [comment]
To temporarily workaround this, I followed the suggested guide[^1] and then uploaded `docs-resources.tar.gz.asc`.

| Before | After |
|--|--|
| ![image](https://github.com/Slicer/Slicer/assets/219043/714d55d5-73a0-41c4-b9b8-bf1ea66ebf38) | ![image](https://github.com/Slicer/Slicer/assets/219043/629cd011-fddd-4021-91b4-fe3ed5010e5a) |

[^1]: https://wiki.debian.org/Creating%20signed%20GitHub%20releases
