### ISSUE TITLE
securityscorecards: Fix  "Branch-Protection" check

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#7201]
## Summary

Following the integration of https://github.com/Slicer/Slicer/pull/7197, a list of checks are performed with the intent of given a "security" score.

The "Branch-Protection" check is currently failing with the following message:

```
internal error: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by integration
```

Following the recommendation described in the following issue should help:
* https://github.com/ossf/scorecard/issues/1097#issuecomment-1654496747

## Steps to reproduce

See https://securityscorecards.dev/viewer/?uri=github.com/Slicer/Slicer

<img width=75% src="https://github.com/Slicer/Slicer/assets/219043/a7ba3156-4c30-4e51-afc2-8c822fc6f761"/>

## Expected behavior

No internal error

**Comment by jcfr** [comment]
Specific instruction are documented here:
* https://github.com/ossf/scorecard-action#authentication-with-fine-grained-pat-optional

**Comment by jcfr** [comment]
Given the open-source nature of the Slicer project, I don't see an issue granting the [scorecard.yml](https://github.com/Slicer/Slicer/blob/main/.github/workflows/scorecard.yml) workflow `read` access to the administration scope[^1].

@jamesobutler @pieper @sjh26 @lassoan  Do you have any concern ?

### Read access associated with the Administration scope

> GET /repos/{owner}/{repo}/actions/permissions
> GET /repos/{owner}/{repo}/actions/permissions/access
> GET /repos/{owner}/{repo}/actions/permissions/selected-actions
> GET /repos/{owner}/{repo}/actions/permissions/workflow
> GET /repos/{owner}/{repo}/actions/runners
> GET /repos/{owner}/{repo}/actions/runners/downloads
> GET /repos/{owner}/{repo}/actions/runners/{runner_id}
> GET /repos/{owner}/{repo}/actions/runners/{runner_id}/labels
> GET /repos/{owner}/{repo}/autolinks
> GET /repos/{owner}/{repo}/autolinks/{autolink_id}
> GET /repos/{owner}/{repo}/automated-security-fixes
> GET /repos/{owner}/{repo}/branches/{branch}/protection
> GET /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
> GET /repos/{owner}/{repo}/branches/{branch}/protection/required_pull_request_reviews
> GET /repos/{owner}/{repo}/branches/{branch}/protection/required_signatures
> GET /repos/{owner}/{repo}/branches/{branch}/protection/required_status_checks
> GET /repos/{owner}/{repo}/branches/{branch}/protection/required_status_checks/contexts
> GET /repos/{owner}/{repo}/branches/{branch}/protection/restrictions
> GET /repos/{owner}/{repo}/branches/{branch}/protection/restrictions/apps
> GET /repos/{owner}/{repo}/branches/{branch}/protection/restrictions/teams
> GET /repos/{owner}/{repo}/branches/{branch}/protection/restrictions/users
> GET /repos/{owner}/{repo}/interaction-limits
> GET /repos/{owner}/{repo}/invitations
> GET /repos/{owner}/{repo}/keys
> GET /repos/{owner}/{repo}/keys/{key_id}
> GET /repos/{owner}/{repo}/tags/protection
> GET /repos/{owner}/{repo}/teams
> GET /repos/{owner}/{repo}/traffic/clones
> GET /repos/{owner}/{repo}/traffic/popular/paths
> GET /repos/{owner}/{repo}/traffic/popular/referrers
> GET /repos/{owner}/{repo}/traffic/views
> GET /repos/{owner}/{repo}/vulnerability-alerts
> GET /user/repository_invitations


[^1]: https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#repository-permissions-for-administration

**Comment by jamesobutler** [comment]
Yes I see no problem adding a token for read access to the administration information. @jcfr following the instructions at https://github.com/ossf/scorecard-action#authentication-with-fine-grained-pat-optional makes sense. Since you are a main Slicer developer, re-upping the token whenever it expires seems reasonable and a low effort future task to enable the scorecard action to have access to what it needs for the additional checks.
