### ISSUE TITLE
CARDIAC module: ECHO VOLUME RENDER Bug

### ISSUE THREAD

**Issue by mvergnat** [Slicer/Slicer#7209]
dear Slicer Program team,
thank you for your help,
I am really big fan of Slicer and it is big problem for me that this echo volume render module does not function anymore.

## Summary
echo loop from Qlab exported into 3dslicer as NRRD file. the ECHO VOLUME RENDER module (sub module of CARDIAC module extension) does not function: no 3d volume showed in the 3d panel.
## Environment
- Slicer version: 5.4.0 r31938 / 311cb26
- Operating system: Windows 10

## Steps to reproduce
echo loop from Qlab exported into 3dslicer as NRRD file. works fine

then opening of module Cardiac, subset ECHO VOLUME RENDER,
then classic pathway:
click apply to sequence, (smoothing factor is 1)
apply.
Then I dont see any 3D volume…
![image](https://github.com/Slicer/Slicer/assets/143593990/8ed75864-ef12-4a3f-a338-c8115ec4518b)

## Expected behavior
expected is to see a volume in the 3d Panel, which is not the case.

I used the ECHO VOLUME RENDER module a month ago and it was working.
now the module does not function anymore??
since a month, I did not use my computer (nothing new nothing was installed, nobody used computer).
I tried multiple procedures:
-modify Rendering settings (smoothing, threshold…),
-close other App in computer, restart the 3dslicer, restart computer,
-redo the philips 4d US dicom patcher,
-I also tried other NRDD files that were functioning last month.
-use older Slicer version (5.2),
-look at computer memory (seems all normal, no problem of computer memory),
-use another computer, use another windows User session.
(in fact I tried several computer from my center, AND on only one computer, it was functionning, but on 3 other it did not function; unfortunately I dont undersatnd why, because there is no big difference between the 1 computer and the other...)

Seems to be a setting problem, because 
the ECHO VOLUME RENDER module does not function
BUT
the VOLUME RENDERING module DOES function:
![image](https://github.com/Slicer/Slicer/assets/143593990/8e368547-6da8-442b-8aff-5efbeaedf994)

Any idea???
many thanks for help!!!!!!!!!!!!!!

mathieu
big fan of 3dSlicer

**Comment by lassoan** [comment]
Thank you very much for reporting. We have reproduced the problem and fixed it in https://github.com/SlicerHeart/SlicerHeart/commit/c4a277337fa5e561a2ac4406b0a92bf3b0ef7d86

You'll get the fix if you update SlicerHeart extension in Slicer-5.4 later today.

**Comment by mvergnat** [comment]
Many thanks for help, but I am still blocked. Apologizes.
I went on extension manager:
1. I tried "check for updates" and installed updates. Restart. Failed again.
2. I unsinstalled SlicerHeart und reinstalled it. Restart. Failed again.
3. Python module:
**Warning: In vtkSlicerVolumeRenderingLogic.cxx, line 692
vtkSlicerVolumeRenderingLogic (000001AE2C301E50): CopyDisplayToVolumeRenderingDisplayNode: Volume Rendering display node does not reference a volume node.
Same problem.**

Did I do something wrong? Should I do differently??
again, comment (maybe they help to understand): 
how is it possible that it was last month functioning and today not anymore???
how is it possible that I found 2 computers where it works..,???

I apologize for hassling people.
I love 3Dslicer, and I compliment everyday the 3dslicer progammer for their wonderful Programm, that ist SUPER helpful!!!!
(I also understand that all these things are made by volonteers! still very nice work!)
again thank you!!
mathieu

**Comment by lassoan** [comment]
The issue is tracked here: https://github.com/SlicerHeart/SlicerHeart/issues/32
I'll try to fix it today.

**Comment by lassoan** [comment]
Echo Volume Renderer requires GPU rendering mode. Change the default mode in application settings / Volume rendering to `VTK GPU Raycasting` to fix this issue. I'll make the module more robust to avoid this issue.
