### ISSUE TITLE
Deleting the first segment removes closed surface representation

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#7220]
## Summary

When removing the first segment in a segmentation and show 3D was enabled, after the segment was removed, 3D is no longer displayed.

## Steps to reproduce

- Load a volume
- Create a segmentation with 3 segments
- Paint something into each segment
- Click Show 3D button to see the segmentation in 3D
- Remove the first segment

### Expected behavior

The first segment should be removed but all the other segments should be still visible in 3D.

### Actual behavior

All the segments disappear. Show 3D button is untoggled.

## Environment
- Slicer version: Slicer-5.4
- Operating system: Windows and Mac

**Comment by cpinter** [comment]
Do you think this is relatively new? I noticed mysterious disappearance of the closed surface representation recently.

Let me know if I can help.

**Comment by lassoan** [comment]
I'm not sure how new it is, probavly not very. The issue is that the available representations are retrieved from the first segment at a time when the first segment is already partially deleted. I think Kyle is on vacation this week, so it would be great if somebody else could look at this.

**Comment by Sunderlandkyl** [comment]
I can take a look this week. I am not on vacation until next week.

**Comment by jcfr** [comment]
> I'm not sure how new it is, probably not very.

I confirm that issue was introduced post Slicer 5.2.2
