### ISSUE TITLE
Unable to find node with ID "" in the given scene, when saving scene into .mrb by python

### ISSUE THREAD

**Issue by derekcbr** [Slicer/Slicer#7228]
## Summary
```
output_file = os.path.join(file_dir, “test.mrb”)
slicer.util.saveScene(output_file)
```

I got the warnings from Slicer:

```
[Qt] class QList<class qSlicerFileWriter *> __cdecl qSlicerCoreIOManagerPrivate::writers(const class QString &,const class QMap<class QString,class QVariant> &,class vtkMRMLScene *) const warning: Unable to find node with ID “” in the given scene.
```

How to solve this problem? Thanks a lot!

## Environment
- Slicer version: Slicer-5.??.?-YYYY-MM-DD
- Operating system: Windows / Linux / Mac + which version

**Comment by pieper** [comment]
Please provide the steps to reproduce (what's in the scene at the time of the save).

**Comment by jcfr** [comment]
Without any updates from @derekcbr , I am now closing this issue.

@derekcbr If you still experience issue, do not hesitate to create a new issue (referencing this one if relevant) and or posting your question on https://discourse.slicer.org

**Comment by lassoan** [comment]
This was a false alarm (empty nodeID means saving the scene, so we don't need to try to look up a node by that empty ID). It was fixed in https://github.com/Slicer/Slicer/commit/5204e7a31876893a529ab60d2054f068759d3d32
