### ISSUE TITLE
Support Numpy2 API

### ISSUE THREAD

**Issue by BishopWolf** [Slicer/Slicer#7230]
## Is your feature request related to a problem? Please describe.

The numpy team has issued [this statement](https://github.com/numpy/numpy/issues/24300)

## Describe the solution you'd like

Basically you shall temporarily add requirements to pinned numpy<2 version, then create a CI based on numpy2 and correct all relevant errors before migrating.

If you already have a pinned numpy version in Slicer builds, then you have no issues until next release, but users must be warned not to upgrade numpy in any way. Therefore, you shall block numpy upgrades in the pip_install function.

## Describe alternatives you've considered

When numpy 2 is out, every user upgrading numpy will see Slicer crashing. You shall emit a WARNING.

## Additional context

Future Slicer releases shall be compatible with numpy 2 API

**Comment by jamesobutler** [comment]
Thanks for the information.

> If you already have a pinned numpy version in Slicer builds, then you have no issues until next release, but users must be warned not to upgrade numpy in any way. 

Slicer does indeed pin the numpy version as part of the build process. I’m sure if users post about problems on the discourse forum we can ask and recommend to not use numpy 2 if it is not compatible with Slicer yet.
https://github.com/Slicer/Slicer/blob/23bf4eb14c3367b77563b428b75577a1616b5559/SuperBuild/External_python-numpy.cmake#L32-L46

> Therefore, you shall block numpy upgrades in the pip_install function.

This could potentially be done if numpy is specified directly, however it would not cover all cases if say a user specifies to install some other package that happens to depend on numpy where that package may specify numpy >= 2. Slicer `pip_install` is not going to know about various python package dependencies.

**Comment by lassoan** [comment]
If numpy maintainers do this right, making changes gradually (using deprecation warnings for several years before any breaking change takes effect) then the transition will be smooth. No packages will require numpy 2.x until all other packages already support numpy 2.x. In this case we will not need to do anything special in Slicer, just find a safe time to update Slicer's numpy to 2.x.

If numpy developers mess up the transition and there will be a time when many packages still only support numpy 1.x while some already require numpy 2.x then we'll see what we need to do, but I'm optimistic that numpy developers are smart enough to avoid this.

**Comment by jamesobutler** [comment]
numpy 2.0.0rc1 has gone live with final release coming soon. See https://github.com/numpy/numpy/issues for pinned issues with latest announcements and the documentation of the ecosystem adoption of support. The latest versions of major packages will be built against numpy 2 providing Abi compatibility with installed versions of numpy 2 AND 1.

There is a ruff plugin for help with numpy 2.0 compatibility.
https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin

**Comment by jamesobutler** [comment]
Numpy ruff rules have already been applied in Slicer’s configuration.

https://github.com/Slicer/Slicer/blob/22f0d749ca494a62445688d8212d52237a1477f4/.ruff.toml#L22

The NPY rules specifically includes NPY201 the numpy deprecation rules.

https://docs.astral.sh/ruff/rules/#numpy-specific-rules-npy

Python’s pip resolver will handle any case where numpy in Slicer core needs updating when installing additional Python packages that require it. Slicer itself does build C extension Python packages that would otherwise need to go through migration to build against Numpy 2 to be compatible with Numpy 2 and 1.
