### ISSUE TITLE
Unreachable code in vtkMRMLPlotChartNode.cxx

### ISSUE THREAD

**Issue by maddin200** [Slicer/Slicer#7277]
/Libs/MRML/Core/vtkMRMLPlotChartNode.cxx line 331

Code:
```
if (id && !strcmp(plotSeriesNodeID, id))
      {
      return plotIndex;
      break; // <-- unreachable
      }
    }
```

**Comment by jcfr** [comment]
https://github.com/Slicer/Slicer/blob/29b57d2d0a592c2634011314cbf85c37c429c03d/Libs/MRML/Core/vtkMRMLPlotChartNode.cxx#L328-L333
