### ISSUE TITLE
Latest Preview in Linux crashes with GPU rendering 

### ISSUE THREAD

**Issue by muratmaga** [Slicer/Slicer#7281]
1. Download and install the latest preview (I used r32228) for Linux (testing with Ubuntu 20 and 22, both on cloud and locally). 
2. obtain MRHead and try to volume rendering with gpu rendering. 

Consistently crashes with bad allocation error. See screenshot above. Doesn't reproduce on windows or mac. 

Also referred in this thread https://discourse.slicer.org/t/vtk-multivolume-cinematic-volume-rendering/31981/35?u=muratmaga

<img width="1225" alt="image" src="https://github.com/Slicer/Slicer/assets/21285140/daf51f74-60e2-4dea-9aa2-3bc1e579ab7e">

@lassoan @pieper

**Comment by lassoan** [comment]
The difference between the previous working version and the current one is just our two commits: https://github.com/Slicer/VTK/compare/b142c0d088f9f29fa42b4137b24abf5ce232d27b...3e45140d5ed4c38ff93bbfd4af033216f9fc820c

If reverting these commits fixes the crash then we should look into the shader replacement code. It is surprising that this code can crash, but you can try replacing regex with something else, as in the past we ran into unexplainable crashes due to using regex.

**Comment by muratmaga** [comment]
@pieper we really like to demo this and JS2 functionality in our upcoming office hour (10/23), but lack of GPU volume rendering in Linux is an issue.

**Comment by lassoan** [comment]
I can reproduce the crash with a factory-built Slicer. Unfortunately, I could not reproduce the issue with a Slicer that I've built on linux (either in Release or Debug mode) - GPU volume rendering works fine.

@pieper can you reproduce it on linux in either release or debug mode?

@sjh26 @jcfr could you test it on the factory machine if you can reproduce the crash? Does reverting the two VTK changes makes the crash disappear?

**Comment by pieper** [comment]
I was going to report the same - factory build of 5.5 fails, but my local release build works (built on ubuntu 22.04).  Building debug now.

@muratmaga we can make you a package from the working release builds for your demo as a workaround.

At the developer meeting tomorrow we can talk about why the factory machine builds are different.

**Comment by muratmaga** [comment]
> we can make you a package from the working release builds for your demo as a workaround.

That would be great, thank you!

**Comment by pieper** [comment]
Okay, it's ready.  In your BIO180006 project on jetstream there's a VM called sdp-sliderdebug.

On that machine the package is here:

/home/exouser/slicer/latest/r-Slicer-superbuild/Slicer-build/Slicer-5.5.0-2023-10-16-linux-amd64.tar.gz

I'll shelve the machine now but you should be able to unshelve it when you are ready.

**Comment by muratmaga** [comment]
Will try tonight. Thansk.

**Comment by muratmaga** [comment]
seems to have been fixed. Thanks everyone.
