### ISSUE TITLE
GLEW could not be initialized: Unknown error

### ISSUE THREAD

**Issue by weiyshay** [Slicer/Slicer#7282]
## Summary
I successfully built Slicer(latest mater by the day) and it prompts some messages in the terminal after launching it.

## Steps to reproduce
Building:
```
sudo apt install git subversion build-essential cmake cmake-curses-gui cmake-qt-gui   qtmultimedia5-dev qttools5-dev libqt5xmlpatterns5-dev libqt5svg5-dev qtwebengine5-dev qtscript5-dev   qtbase5-private-dev libqt5x11extras5-dev libxt-dev libssl-dev
wget https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1-Linux-x86_64.sh
chmod  +x cmake-3.27.1-Linux-x86_64.sh
sudo ./cmake-3.27.1-Linux-x86_64.sh --skip-license --prefix=/usr/local
cd Slicer-SuperBuild-Debug/
/usr/local/bin/cmake -DCMAKE_BUILD_TYPE:STRING=Debug ../Slicer

```

Logs:
```
Slicer-build$ ./Slicer
QSocketNotifier: Can only be used with threads started with QThread
qt.network.ssl: Incompatible version of OpenSSL (built with OpenSSL >= 3.x, runtime version is < 3.x)
[SSL] SSL support disabled - Failed to load SSL library !
[SSL] Failed to load Slicer.crt
QObject::connect: No such signal qSlicerSegmentationsSettingsPanel::setDefaultOverwriteMode(QString) in /data/2023/src/slicer/Slicer/Modules/Loadable/Segmentations/qSlicerSegmentationsSettingsPanel.cxx:122
QObject::connect:  (sender name:   'DefaultOverwriteModeComboBox')
QObject::connect:  (receiver name: 'qSlicerSegmentationsSettingsPanel')
Switch to module:  "Welcome"
GLEW could not be initialized: Unknown error
GLEW could not be initialized: Unknown error
GLEW could not be initialized: Unknown error
GLEW could not be initialized: Unknown error
```
## Expected behavior
No error in the console.

## Environment
- Ubuntu 23.04
- Slicer version: 
```
commit 2800aeef881bab3366a0656f2fcaa8bf9cf78788 (HEAD -> main, origin/main, origin/HEAD)
Author: SET <set@chirvasc-60.pro>
Date:   Wed Jul 26 21:08:00 2023 +0200

    ENH: Add a setting for the overwrite mode masking option of the segment editor
    
    Co-authored-by: Andras Lasso <lasso@queensu.ca>
```

**Comment by lassoan** [comment]
- SSL: you can use system SSL or use custom-built Qt that has the right SSL version
- Qt connection: update Slicer from latest main version from github
- GLEW: I don't know that is causing it, but it is most likely not specific to Slicer (but a Qt and/or VTK issue, so you may find hints online about what causes it and how to resolve)

Does Slicer run fine?

**Comment by weiyshay** [comment]
Thank your very much for your comment!

>SSL: you can use system SSL or use custom-built Qt that has the right SSL version
Any option that I can configure to use system SSL? Better not to rebuilt QT. :) 

>Qt connection: update Slicer from latest main version from github
It was the 'main' branch a few days ago and I will pull and give it a shot. 

>GLEW: I don't know that is causing it, but it is most likely not specific to Slicer (but a Qt and/or VTK issue, so you may find hints online about what causes it and how to resolve)
Yes, it might be OpenGL/VTK related. I searched around and couldn't resolve it. 
Is there anyway to know that how the official release for linux is built? That will be very helpful.
The binary that I tried without error is 'Slicer-5.4.0-linux-amd64.tar.gz'.

Some references:
https://discourse.vtk.org/t/glew-could-not-be-initialized-missing-gl-version-vtk-under-python-windows/4598/13

>Does Slicer run fine?
Yes, it can be launched successfully. I am a starter and triedload a DICOM file so far.
I downloaded a release binary and run it via command line and didn't get any message in console.
I am not sure if there is something different comparing to the run the binary directly.

**Comment by weiyshay** [comment]
btw, anyway to rebuild slicer without redownloading all the dependent libraries? I am switching to 5.4 and rebuild a version.

I tried deleting CMakeCache.txt and CMakefiles, 'cmake -DCMAKE_BUILD_TYPE:STRING=Debug --fresh', either not working.

**Comment by weiyshay** [comment]
Log on a rebuild on 5.4 with system-ssl and it seems a bit different or less warnings/errors.
Any idea on how to debug?

```
#Slicer-build/Slicer
QSocketNotifier: Can only be used with threads started with QThread
Switch to module:  "Welcome"
Wayland does not support QWindow::requestActivate()
GLEW could not be initialized: Unknown error

```

**Comment by xaprier** [comment]
can you try this command and retry it?

```sh
export XDG_SESSION_TYPE=""
```

With that command you unset parameter from Wayland, then try to execute Slicer from the terminal where you execute command above.

**Comment by luzpaz** [comment]
@weiyshay :point_up_2:

**Comment by lassoan** [comment]
The reporter did not respond. Assuming the problem was solved, I'm closing this issue.
