### ISSUE TITLE
Fix py_SubjectHierarchyGenericSelfTest  test

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#7288]
## Summary

The test `py_SubjectHierarchyGenericSelfTest` passed on all platform when executed against a build of Slicer 31ba8942a031b907d4be2f2f5d81db717b347a1b  and started to fail with Slicer  80ad0a04dacf134754459557bf2638c63f3d1d1b.

| | :white_check_mark: | :x: |
|---|---|---|
| CDash link | https://slicer.cdash.org/test/25604578 | https://slicer.cdash.org/test/25610246 | 
| Slicer Source | 31ba8942a031b907d4be2f2f5d81db717b347a1b | 80ad0a04dacf134754459557bf2638c63f3d1d1b |

### Useful links

* Compare link: https://github.com/Slicer/Slicer/compare/31ba8942a031b907d4be2f2f5d81db717b347a1b...80ad0a04dacf134754459557bf2638c63f3d1d1b

* Associated pull requests:
  * https://github.com/Slicer/Slicer/pull/7214
  * https://github.com/Slicer/Slicer/pull/7234

* Test sources: https://github.com/Slicer/Slicer/blob/main/Modules/Loadable/SubjectHierarchy/Testing/Python/SubjectHierarchyGenericSelfTest.py

## Steps to reproduce

```
ctest -C Release -R py_SubjectHierarchyGenericSelfTest

[...]

308: FAIL: test_SubjectHierarchyGenericSelfTest_FullTest1 (SubjectHierarchyGenericSelfTest.SubjectHierarchyGenericSelfTestTest)
308: ----------------------------------------------------------------------
308: Traceback (most recent call last):
308:   File "/home/jcfr/Projects/Slicer-Release/Slicer-build/lib/Slicer-5.5/qt-scripted-modules/SubjectHierarchyGenericSelfTest.py", line 113, in test_SubjectHierarchyGenericSelfTest_FullTest1
308:     self.section_AttributeFilters()
308:   File "/home/jcfr/Projects/Slicer-Release/Slicer-build/lib/Slicer-5.5/qt-scripted-modules/SubjectHierarchyGenericSelfTest.py", line 565, in section_AttributeFilters
308:     testAttributeFilters(shProxyModel, shProxyModel)
308:   File "/home/jcfr/Projects/Slicer-Release/Slicer-build/lib/Slicer-5.5/qt-scripted-modules/SubjectHierarchyGenericSelfTest.py", line 480, in testAttributeFilters
308:     self.assertEqual(shProxyModel.acceptedItemCount(shNode.GetSceneItemID()), 5)
308: AssertionError: 6 != 5
```

## Expected behavior

Test should pass on all platform

**Comment by cpinter** [comment]
It seems that the failure is due to the fact that the showEmptyHierarchyItems flag is on in the proxy model. Trying to see why it is enabled.

**Comment by cpinter** [comment]
It seems that it has been always on by default, and it seems correct that the empty folder shows up, so the item count of 6 that made the test fail is the correct number. I propose to fix the test by adjusting the expected value.

The six items:
![image](https://github.com/Slicer/Slicer/assets/1325980/aad031c6-f7b2-4409-b40d-8068778fab99)
The four markup nodes have the node attribute that was filtered. Their parent shows up anyway, and the empty folder shows up due to the (by default) enabled `showEmptyHierarchyItems` flag.

**Comment by jcfr** [comment]
Updating the expected value makes sense and would be consistent with the new default behavior.

| Before https://github.com/Slicer/Slicer/pull/7214 | After https://github.com/Slicer/Slicer/pull/7214 |
|-------|-----|
| ![image](https://github.com/Slicer/Slicer/assets/219043/17add86c-366a-41ef-8e01-c346e87ff00b) | ![image](https://github.com/Slicer/Slicer/assets/219043/c63faa09-6fee-469e-a702-c5f97cf958b3) |

I also suggest to update to check that setting `showEmptyHierarchyItems` works as expected.


After loading [SubjectHierarchyAttributeFilterTestScene.mrb](https://github.com/Slicer/SlicerTestingData/releases/download/SHA256/83e0df42d178405dccaf5a87d0661dd4bad71b535c6f15457344a71c4c0b7984), I used the following convenient snippet based of the current test:

```python
shTreeView = slicer.qMRMLSubjectHierarchyTreeView()
shTreeView.setMRMLScene(slicer.mrmlScene)
shTreeView.show()
shProxyModel = shTreeView.sortFilterProxyModel()
shNode = slicer.mrmlScene.GetSubjectHierarchyNode()

assert shProxyModel.acceptedItemCount(shNode.GetSceneItemID()) == 9

shProxyModel.includeNodeAttributeNamesFilter = ['Markups.MovingInSliceView']

# By default, shProxyModel.showEmptyHierarchyItems is True
assert shProxyModel.acceptedItemCount(shNode.GetSceneItemID()) == 6

shProxyModel.showEmptyHierarchyItems = False
assert shProxyModel.acceptedItemCount(shNode.GetSceneItemID()) == 5
```

**Comment by cpinter** [comment]
PR ready to review.

Yes I also realized the `showEmptyHierarchyItems` flag was not tested so I added a small test at the end of the attributes test section.
