### ISSUE TITLE
PET-CT fusion / MIP

### ISSUE THREAD

**Issue by eyalhana** [Slicer/Slicer#7293]
Hello,

First and foremost, I want to express my appreciation for the outstanding software you have provided.

I currently have two folders containing registered PET and CT NIfTI files. My objective is to generate new fusion files for each case, which can be either NIfTI files for each volume or PNG files for each slice. The process of manually opening each PET and CT file, selecting the fusion option, and saving the file is quite time-consuming.

Is there an automated solution available? Is it possible to utilize Slicer to process all the files automatically? Alternatively, is there an option to access the relevant code from Slicer and modify it to suit my needs? Unfortunately, I was unable to locate this code.

Additionally, I have a similar question regarding Maximum Intensity Projection (MIP). Is there a way to automate the MIP creation process for these files or access the code for customization?

Thank you!

**Comment by cpinter** [comment]
Hi! We use GitHub to track progress about tasks related to Slicer core development: bugs and feature requests. Additionally, typically Slicer core developers use this system. Then we have the [Slicer discourse forum](https://discourse.slicer.org/) for more general questions, requests, discussions. The community that uses the forum is much larger as well, so you'll get more comprehensive feedback there. I suggest closing this issue and re-posting the same thing on discourse. Thank you very much!

**Comment by jcfr** [comment]
> First and foremost, I want to express my appreciation for the outstanding software you have provided.

Thanks for the feedback :pray: 

To follow up on @cpinter, let us know if you have any issue posting your question on the forum at https://discourse.slicer.org

**Comment by jcfr** [comment]
> if you have any issues posting your question on the forum

@eyalhana Once you have posted question on the forum, consider relying here adding a link to it.

Thanks for your help.

**Comment by jcfr** [comment]
Without any updates from @eyalhana, I am now closing this issue.
