### ISSUE TITLE
Fix py_nomainwindow_DCMTKPrivateDictTest failure introduced by DICOMProcess and DICOMCommand refactoring

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#7298]
## Summary

Following the introduction of adb997269bacf3dfe15b597480391ce8e880d12e introduced by [PR-7260](ttps://github.com/Slicer/Slicer/pull/7260), the test `py_nomainwindow_DCMTKPrivateDictTest` started to fail with the following error:

```
Test command: /path/to/Slicer-Release/Slicer-build/Slicer "--no-splash" "--testing" "--no-main-window" "--disable-modules" "--python-script" "/path/to/Slicer/Applications/SlicerApp/Testing/Python/DCMTKPrivateDictTest.py" "/path/to/Slicer/Testing/Data/Input/philips_ingenia_4_1_3_dwi.dcm"
Test timeout computed to be: 1500
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "<string>", line 19, in <module>
Exception: Could not find 'DiffusionBFactor' private tag reading file '/path/to/Slicer/Testing/Data/Input/philips_ingenia_4_1_3_dwi.dcm' using 'dcmdump' !
1/1 Test #py_nomainwindow_DCMTKPrivateDictTest ...***Failed    2.10 sec
```

Related pull requests:
* https://github.com/Slicer/Slicer/pull/7260

## Steps to reproduce

```
$ ctest -C Release -R py_nomainwindow_DCMTKPrivateDictTest
```

## Environment

Reproducible on all platforms.

| | Without PR-7260 | With PR-7260 |
|--|--|--|
| `py_nomainwindow_DCMTKPrivateDictTest` | :white_check_mark:  | :x: |

| https://slicer.cdash.org/index.php?project=SlicerPreview&date=2023-10-21&filtercount=1&showfilters=1&field1=groupname&compare1=63&value1=Nightly-Packages |
|--|
| ![image](https://github.com/Slicer/Slicer/assets/219043/885a1f16-8b52-4c2a-afd9-c9214cb78d83) |

**Comment by tbirdso** [comment]
For my and others' reference, the failing test is here: https://github.com/Slicer/Slicer/blob/9e581502b55ed5c2e53ad96624c507d36951494a/Applications/SlicerApp/Testing/Python/DCMTKPrivateDictTest.py#L19

**Comment by pieper** [comment]
Nice example of s regression test doing its job 👍

**Comment by tbirdso** [comment]
I am a bit confused on why this didn't fail during the PR test. Are Slicer regression tests run nightly and not on a per-PR basis? Where can I find more information on testing?
