### ISSUE TITLE
`SampleData::downloadFromURL` does not tell whether the data was effectively downloaded

### ISSUE THREAD

**Issue by jhlegarreta** [Slicer/Slicer#7342]
## Summary

The method `SampleData::downloadFromURL` does not tell whether the data was effectively downloaded: it does not fail when the URL does not exist or the data cannot be downloaded.

## Steps to reproduce

Execute the `SlicerMRBTest` from the `SlicerDMRI` extension, i.e.
https://github.com/SlicerDMRI/SlicerDMRI/blob/372675b96e917acb61bc8cb2ac9262d87cc5b06a/Modules/Loadable/TractographyDisplay/Testing/Python/SlicerMRBTest.py

and check that the result is
```
"Volume" Reader has successfully read the file "/home/kitware/.cache/slicer.org/Slicer-tmp/Slicer-tmpIO/DTIVolume.nhdr" "[1.92s]"
Finished with download and loading of ('DTIVolume.raw.gz', 'DTIVolume.nhdr')
Finished with download and loading of FA.nrrd
Finished with download and loading of tract1.vtk
Finished with download and loading of tract2.vtk
Finished with download and loading of tract3.vtk
```

visible at https://slicer.cdash.org/test/25940214.

This behavior can be reproduced locally having built Slicer and the extension and launching `ctest -V from the command line at the `SlicerDMRI` extension build `inner-build` directory.

None of these data can be downloaded from the URLs at
https://github.com/SlicerDMRI/SlicerDMRI/blob/372675b96e917acb61bc8cb2ac9262d87cc5b06a/Modules/Loadable/TractographyDisplay/Testing/Python/SlicerMRBTest.py#L75

If one copies and pastes the URLs into a browser an error page is displayed, with the message, e.g
```
Parameter 'items' must be a valid ObjectID. Value is 5767
```

So,
- The method or class does not check that the data file is on disk. It should.
- If the URL does not exist, or the data could not be loaded, the method should be able to inform the user with a meaningful message.

## Environment

- Slicer version: The dashboard shows that this happens for any nightly Slicer version.
- Operating system: The dashboard shows that this happens across all 3 OS.

**Comment by lassoan** [comment]
I would recommend to specify hash, as it is done in more recent examples, such as https://github.com/rbumm/SlicerLungCTAnalyzer/blob/d861e002578e0678e7c38217786311dcd2768af4/LungCTAnalyzer/LungCTAnalyzer.py#L62-L71

That should take care of errors at any level: if the downloaded file content does not match the required hash then it will be detected.

**Comment by jhlegarreta** [comment]
Thanks for the answer @lassoan. Will adopt the approach once I figure out and solve why the data is not being loaded into the scene even if I manually place the files in the temporary folder and bypass the download not taking place. Will report back then.

**Comment by lassoan** [comment]
By default the data is assumed to be "VolumeFile". If you load a special different file type then you need to specify that.

SampleData module is implemented in Python, so you can attach a [Python debugger](https://slicer.readthedocs.io/en/latest/developer_guide/debugging/python.html#python-debugging) and run the command step by step to see exactly what is happening. That way you don't need to guess or even think to solve the downloading issue.

**Comment by jhlegarreta** [comment]
> By default the data is assumed to be "VolumeFile". If you load a special different file type then you need to specify that.

The data is being specified correctly, e.g.
https://github.com/SlicerDMRI/SlicerDMRI/blob/372675b96e917acb61bc8cb2ac9262d87cc5b06a/Modules/Loadable/TractographyDisplay/Testing/Python/SlicerMRBTest.py#L75

So it does not seem to be the issue.

> SampleData module is implemented in Python, so you can attach a Python debugger and run the command step by step to see exactly what is happening. That way you don't need to guess or even think to solve the downloading issue.

Thanks. Will have a look whenever I find the time.

**Comment by lassoan** [comment]
It works well for me:

```python
import SampleData
TESTING_DATA_URL = ""
SampleData.downloadFromURL(
    nodeNames="FA",
    fileNames="FA.nrrd", 
    uris="https://github.com/Slicer/SlicerTestingData/releases/download/SHA256/12d17fba4f2e1f1a843f0757366f28c3f3e1a8bb38836f0de2a32bb1cd476560",
    checksums="SHA256:12d17fba4f2e1f1a843f0757366f28c3f3e1a8bb38836f0de2a32bb1cd476560")
```

Note that if you don't specify a checksum then you make Slicer load whatever garbage might have been in a previously downloaded and cached version of the file. So, always specify a checksum.

> Thanks. Will have a look whenever I find the time.

If loading still does not work after you specify the checksum then I would strongly recommend to spend your time with setting up the Python debugger before doing anything else. If you do it the first time then maybe it takes 5-10 minutes, but it pays off immediately, as probably it'll make it obvious what you need to change.

**Comment by lassoan** [comment]
Fiber loading works, too, I just had to use a simple `ModelFile`, as the fiber reader seems to be broken in SlicerDMRI:

```python
SampleData.downloadFromURL(
    nodeNames="tract1",
    fileNames="tract1.vtk",
    uris="https://github.com/Slicer/slicer.kitware.com-midas3-archive/releases/download/SHA256/06d5b5777915857fbac7b3cbd9c371523d1371f29b0c89eb7a33d86d780d5b2b",
    checksums="SHA256:06d5b5777915857fbac7b3cbd9c371523d1371f29b0c89eb7a33d86d780d5b2b",
    loadFileTypes="ModelFile")
```

Note that you can now perform quick checks in your file reader plugin's `canLoadFileConfidence` method and return a higher-than default confidence value if the model is a fiber bundle and not just a generic model. Just make sure you don't read the entire file or do some other potentially computationally heavy operations in the `canLoadFileConfidence` method, as that operation is performed whenever loading any model. Typically we just search for strings in the first few hundred bytes of a file.

**Comment by lassoan** [comment]
I've noticed some `toLatin1` calls. Replace them by `ToStdString` or `ToUtf8`, as Slicer is now using UTF8 everywhere.

While it is possible that the fiber reading might need some fixes in Slicer core, if that's the case, a new issue should be added for that. The original topic of this report - `downloadFromURL` should check integrity of the downloaded data - is already resolved.

**Comment by jhlegarreta** [comment]
Thanks for all the effort @lassoan.

> Note that if you don't specify a checksum then you make Slicer load whatever garbage might have been in a previously downloaded and cached version of the file. So, always specify a checksum.

The files that I have been used corresponded exactly to the desired checksums, and the tests were launched from the terminal, so I do not think there was undesired information in the cache.

> If loading still does not work after you specify the checksum then I would strongly recommend to spend your time with setting up the Python debugger before doing anything else.

Thanks for the tip. Will do as time permits.

> Fiber loading works, too, I just had to use a simple ModelFile,

Maybe in the particular test that you used it passed, but in the one I used `ModelFile` crashed down the road because it did not have access to a fiber-specific property.

> as the fiber reader seems to be broken in SlicerDMRI:

How do you conclude this? Asking because if it is the case, I may look into fixing it, and because in Slicer 5.2.2 loading a bundle using the `FiberBundle` description (which I assume corresponds to `FiberBundleFile`) works well.

> Note that you can now perform quick checks in your file reader plugin's canLoadFileConfidence method

Will look into this as time permits. Thanks.

> I've noticed some toLatin1 calls. Replace them by ToStdString or ToUtf8, as Slicer is now using UTF8 everywhere.

Will do. Thanks.

**Comment by lassoan** [comment]
> > as the fiber reader seems to be broken in SlicerDMRI:
> 
> How do you conclude this? Asking because if it is the case, I may look into fixing it, and because in Slicer 5.2.2 loading a bundle using the `FiberBundle` description (which I assume corresponds to `FiberBundleFile`) works well.

My tests were the followings (all on Windows):

Test 1:

```python
import SampleData
SampleData.downloadFromURL(
    nodeNames="tract1",
    fileNames="tract1.vtk",
    uris="https://github.com/Slicer/slicer.kitware.com-midas3-archive/releases/download/SHA256/06d5b5777915857fbac7b3cbd9c371523d1371f29b0c89eb7a33d86d780d5b2b",
    checksums="SHA256:06d5b5777915857fbac7b3cbd9c371523d1371f29b0c89eb7a33d86d780d5b2b",
    loadFileTypes="ModelFile")
```

Works on Slicer-5.2.2, Slicer-5.4.0, latest Slicer-5.5.

Test 2:

```python
import SampleData
SampleData.downloadFromURL(
    nodeNames="tract1",
    fileNames="tract1.vtk",
    uris="https://github.com/Slicer/slicer.kitware.com-midas3-archive/releases/download/SHA256/06d5b5777915857fbac7b3cbd9c371523d1371f29b0c89eb7a33d86d780d5b2b",
    checksums="SHA256:06d5b5777915857fbac7b3cbd9c371523d1371f29b0c89eb7a33d86d780d5b2b",
    loadFileTypes="FiberBundleFile")
```

Works on Slicer-5.2.2.
Crashes on Slicer-5.4.0, latest Slicer-5.5.

**Comment by jhlegarreta** [comment]
> Crashes on Slicer-5.4.0, latest Slicer-5.5.

OK. Interesting. Thanks for reporting. Maybe @pieper has some insight on this?

**Comment by pieper** [comment]
> > Crashes on Slicer-5.4.0, latest Slicer-5.5.
> 
> OK. Interesting. Thanks for reporting. Maybe @pieper has some insight on this?

I haven't looked, but there have been examples in the past where changes in VTK caused problems.  Best thing to do is make a debug build and check with a debugger.
