### ISSUE TITLE
Crash with current nightly on linux

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#7343]
## Summary

Just running the application leads to memory corruption on exit.

## Steps to reproduce

Below is a build from a few days ago vs 5.4:

```
(base) ubuntu@sdp-trainer3-reborn2:~/Downloads$ ./Slicer-5.5.0-2023-11-01-linux-amd64/Slicer --python-code "exit()"
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-ubuntu'
Switch to module:  "Welcome"
Loading Slicer RC file [/home/ubuntu/.slicerrc.py]
Switch to module:  ""
Switch to module:  ""
double free or corruption (!prev)
error: [/home/ubuntu/Downloads/Slicer-5.5.0-2023-11-01-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.
(base) ubuntu@sdp-trainer3-reborn2:~/Downloads$ ./Slicer-5.4.0-linux-amd64/Slicer --python-code "exit()"
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-ubuntu'
Switch to module:  "Welcome"
Loading Slicer RC file [/home/ubuntu/.slicerrc.py]
Switch to module:  ""
Switch to module:  ""
(base) ubuntu@sdp-trainer3-reborn2:~/Downloads$ 
```

## Environment
Happens for me with ubuntu 20.04 but not on my local mac builds or 5.4/5.5.0-2023-11-01 on mac.  Have not tried windows.

**Comment by pieper** [comment]
@lassoan @jcfr @sjh26 It would be great if you could also try to reproduce.

**Comment by jcfr** [comment]
Thanks for the report. Does the problem happen with build from few days ago before integration of the listening of ActiveCameraChangeEvent ?

**Comment by pieper** [comment]
I had been seeing this for a while and just got around to reporting it.  I only tested the two versions reported above so far.

**Comment by jcfr** [comment]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

* Slicer-5.5.0-2023-11-02-linux-amd64: :white_check_mark: 

    ```
    $ pwd
    /home/jcfr/Downloads/Slicer-5.5.0-2023-11-02-linux-amd64
    $ ./Slicer --python-code "exit();"
    Switch to module:  "Welcome"
    Switch to module:  ""
    Switch to module:  ""
    ```

* Slicer-5.5.0-2023-11-01`-linux-amd64: :white_check_mark: 

    ```
    $ pwd
    /home/jcfr/Downloads/Slicer-5.5.0-2023-11-01-linux-amd64
    $ ./Slicer --python-code "exit();"
    Switch to module:  "Welcome"
    Switch to module:  ""
    Switch to module:  ""
    ```

* Slicer-5.5.0-2023-10-30-linux-amd64: :white_check_mark: 

    ```
    $ pwd
    /home/jcfr/Downloads/Slicer-5.5.0-2023-10-30-linux-amd64
    $ ./Slicer --python-code "exit();"
    Switch to module:  "Welcome"
    Switch to module:  ""
    Switch to module:  ""
    ```

**Comment by jcfr** [comment]
I am wondering if:
* you are loading some package through `/home/ubuntu/.slicerrc.py` that would lead to issue
* you have additional module paths configured

I suggest you try the following flags:
* `--ignore-slicerrc`
* `--disable-settings`

**Comment by pieper** [comment]
Thanks for testing Jc.  I realize that there are several extensions installed in the version that's crashing so I'll track down which one and file an issue in the appropriate repo.

**Comment by pieper** [comment]
As a follow up these are the extensions that were installed on the version that crashes.  Even with all extensions disabled, the program still crashes on exit with the double-free memory error.  Checking the directory compared to a fresh install of the same version, it appears that some python packages were re-installed by one of these extensions and that leads to the crash.


```
HDBrainExtraction.s4ext
PET-IndiC.s4ext
PETDICOMExtension.s4ext
PETTumorSegmentation.s4ext
PyTorch.s4ext
Sandbox.s4ext
SlicerDMRI.s4ext
SlicerDcm2nii.s4ext
SlicerFreeSurfer.s4ext
SlicerNeuro.s4ext
SwissSkullStripper.s4ext
TotalSegmentator.s4ext
UKFTractography.s4ext
```
