### ISSUE TITLE
LOCAL THRESHOLD

### ISSUE THREAD

**Issue by fatemeh0seini** [Slicer/Slicer#7349]
hi

I don't have some icons in Segmentediter including local threshold
I tried on stable release Slicer 5.4.0 and also Slicer 4.11.20210226
- Operating system: Windows 11
- 
![3D Slicer 5 4 0 11_6_2023 1_11_16 PM](https://github.com/Slicer/Slicer/assets/150013566/baba0df9-9583-4480-b3ac-88050d443891)

as there were similar issue in [discussion](https://discourse.slicer.org/t/new-segment-editor-effect-local-threshold/9233/21?page=2) I tried some of suggestion but it didn't work out
1)I put slicer file in a folder without special character 
and restarted my laptop
2)I can't find this folder C:/Users/Félix/AppData/Roaming/NA-MIC/Extensions-29402/SegmentEditorExtraEffects/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorLocalThresholdLib/SegmentEditorEffect.py
3)this is my log file content
[DEBUG][Qt] 06.11.2023 13:10:48 [] (unknown:0) - Session start time .......: 2023-11-06 13:10:48
[DEBUG][Qt] 06.11.2023 13:10:48 [] (unknown:0) - Slicer version ...........: 5.4.0 (revision 31938 / 311cb26) win-amd64 - installed release
[DEBUG][Qt] 06.11.2023 13:10:48 [] (unknown:0) - Operating system .........: Windows /  Personal / (Build 22000, Code Page 65001) - 64-bit
[DEBUG][Qt] 06.11.2023 13:10:48 [] (unknown:0) - Memory ...................: 16075 MB physical, 18507 MB virtual
[DEBUG][Qt] 06.11.2023 13:10:48 [] (unknown:0) - CPU ......................: GenuineIntel , 8 cores, 8 logical processors
[DEBUG][Qt] 06.11.2023 13:10:48 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, TBB threading
[DEBUG][Qt] 06.11.2023 13:10:48 [] (unknown:0) - Qt configuration .........: version 5.15.2, with SSL, requested OpenGL 3.2 (compatibility profile)
[DEBUG][Qt] 06.11.2023 13:10:48 [] (unknown:0) - Internationalization .....: disabled, language=
[DEBUG][Qt] 06.11.2023 13:10:48 [] (unknown:0) - Developer mode ...........: disabled
[DEBUG][Qt] 06.11.2023 13:10:48 [] (unknown:0) - Application path .........: C:/Users/User/AppData/Local/slicer.org/Slicer 5.4.0/bin
[DEBUG][Qt] 06.11.2023 13:10:48 [] (unknown:0) - Additional module paths ..: (none)
[DEBUG][Python] 06.11.2023 13:10:54 [Python] (C:\Users\User\AppData\Local\slicer.org\Slicer 5.4.0\lib\Slicer-5.4\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:38) - Scripted subject hierarchy plugin registered: SegmentEditor
[DEBUG][Python] 06.11.2023 13:10:54 [Python] (C:\Users\User\AppData\Local\slicer.org\Slicer 5.4.0\lib\Slicer-5.4\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:38) - Scripted subject hierarchy plugin registered: SegmentStatistics
[DEBUG][Qt] 06.11.2023 13:10:54 [] (unknown:0) - Switch to module:  "Welcome"
[DEBUG][Qt] 06.11.2023 13:10:57 [] (unknown:0) - Switch to module:  "DICOM"
[DEBUG][Qt] 06.11.2023 13:11:03 [] (unknown:0) - Switch to module:  "SampleData"
[DEBUG][Python] 06.11.2023 13:11:03 [Python] (C:/Users/User/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/qt-scripted-modules/SampleData.py:385) - <p>Status: <i>Idle</i></p>
[DEBUG][Python] 06.11.2023 13:11:05 [Python] (C:/Users/User/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/qt-scripted-modules/SampleData.py:385) - <b>Verifying checksum</b>
[DEBUG][Python] 06.11.2023 13:11:05 [Python] (C:/Users/User/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/qt-scripted-modules/SampleData.py:385) - <b>File already exists and checksum is OK - reusing it.</b>
[DEBUG][Python] 06.11.2023 13:11:05 [Python] (C:/Users/User/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/qt-scripted-modules/SampleData.py:385) - <b>Requesting load</b> <i>Panoramix-cropped</i> from C:/Users/User/AppData/Local/slicer.org/Slicer/cache/SlicerIO/Panoramix-cropped.nrrd ...
[DEBUG][Qt] 06.11.2023 13:11:05 [] (unknown:0) - "Volume" Reader has successfully read the file "C:/Users/User/AppData/Local/slicer.org/Slicer/cache/SlicerIO/Panoramix-cropped.nrrd" "[0.37s]"
[DEBUG][Python] 06.11.2023 13:11:05 [Python] (C:/Users/User/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/qt-scripted-modules/SampleData.py:385) - <b>Load finished</b>
[DEBUG][Python] 06.11.2023 13:11:05 [Python] (C:/Users/User/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/qt-scripted-modules/SampleData.py:385) - <b>Verifying checksum</b>
[DEBUG][Python] 06.11.2023 13:11:05 [Python] (C:/Users/User/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/qt-scripted-modules/SampleData.py:385) - <b>File already exists and checksum is OK - reusing it.</b>
[DEBUG][Python] 06.11.2023 13:11:05 [Python] (C:/Users/User/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/qt-scripted-modules/SampleData.py:385) - <b>Requesting load</b> <i>Panoramix-cropped</i> from C:/Users/User/AppData/Local/slicer.org/Slicer/cache/SlicerIO/Panoramix-cropped.nrrd ...
[DEBUG][Qt] 06.11.2023 13:11:06 [] (unknown:0) - "Volume" Reader has successfully read the file "C:/Users/User/AppData/Local/slicer.org/Slicer/cache/SlicerIO/Panoramix-cropped.nrrd" "[0.33s]"
[DEBUG][Python] 06.11.2023 13:11:06 [Python] (C:/Users/User/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/qt-scripted-modules/SampleData.py:385) - <b>Load finished</b>
[DEBUG][Qt] 06.11.2023 13:11:07 [] (unknown:0) - Switch to module:  "SegmentEditor"

**Comment by cpinter** [comment]
You need to install the SegmentEditorExtraEffects extension. Please for such questions use https://discourse.slicer.org/ in the future, where, as a matter of fact, this question has been answered various times. Thank you.

**Comment by fatemeh0seini** [comment]
thank you so much
