### ISSUE TITLE
 Segmentation.GetDisplayNode().SetAllSegmentsVisibility(True) not working

### ISSUE THREAD

**Issue by kritsini21** [Slicer/Slicer#7376]
Hello,

I have a segmented image (seg.nrrd format) , and i want to split my segmentation to labels in order to extract on a next step the radiomic features. However, even if in my segmented image i have 15 different labelmaps, when i split the image, only 10 of them appear in my folder. 

I tried this command as well but it didnt work:  `Segmentation.GetDisplayNode().SetAllSegmentsVisibility(True)`

Any advice? 

Thank you!!!!!

**Comment by cpinter** [comment]
There are many unknowns still after your brief description. Please provide a step by step guide that helps us reproduce the problem, with data that is easy to access (preferable from Sample Data). Thank you!

**Comment by lassoan** [comment]
Closing this, as we have not received response for the reporter.
