### ISSUE TITLE
SlicerIGT module -> Surface Registration -> ROI Registration. Problem placing multiple landmarks

### ISSUE THREAD

**Issue by rsalest** [Slicer/Slicer#7378]
When trying to add landmarks on the aforesaid module, I'm only allowed to insert one. Ticking the "Add" button after placing the first point does nothing, no new landmark is added to the list. Moving back the mouse through the 3rd view only drags the former point to the new cursor position. I've been using Slicer 4.11 without any issue for years. Changing to version 5.4 (and testing the 5.5) led to this drawback. Any solution would be much appreciated. Thank you.

**Comment by lassoan** [comment]
There is no SlicerIGT module. Maybe you mean SlicerCMF extension?
That extension has a Surface registration module, and within that a ROI registration option - https://discourse.slicer.org/t/roi-registration-non-functional/14509

Please test in the latest Slicer Preview Release and if you still experience problems then report to the extension developers by creating an issue at the https://github.com/DCBIA-OrthoLab/CMFreg
