### ISSUE TITLE
Segmentation size limited

### ISSUE THREAD

**Issue by dzenanz** [Slicer/Slicer#7394]
## Summary

I am trying to manually segment a histology image of size 685x502 (2D), and I cannot segment the entire image. The rightmost portion (i indices 589 and higher) does not remember the segmentation. Once I finish drawing (release the left mouse button), whatever I traced on the right edge disappears.
<img width="1510" alt="Screenshot 2023-11-15 15 18 08" src="https://github.com/Slicer/Slicer/assets/1792121/8be79bd3-ea01-4710-958a-48aab2f4598c">

## Steps to reproduce

Load a large-ish 2D RGB image (grayscale does not seem to trigger it), go to segment editor, choose the RGB image as the source volume, try to trace an outline using paint tool over majority of the image.

## Environment
- Slicer version: Slicer-5.2.1 and Slicer-5.4.0
- Operating system: Windows 11

**Comment by lassoan** [comment]
I cannot reproduce this issue. I've loaded a color PNG of 1917x1001, opened Segment Editor, and could paint everywhere.

Can you upload somewhere an image with that you can reproduce tha issue and post the link here?

**Comment by dzenanz** [comment]
Here it is: https://drive.google.com/file/d/117Uw3LyPoZAvqCN4fposyA_GYThBgyxu/view?usp=sharing

**Comment by lassoan** [comment]
It all works well for me. Can you take a screen capture video (or describe every clicks that you make)?

**Comment by dzenanz** [comment]
I tried it several times yesterday, and I always ran into the issue. Now I tried it twice, and I cannot reproduce it.
