### ISSUE TITLE
Update TEST_SET_GET_STRING to support both char* and std::string

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#7403]
## Is your feature request related to a problem? Please describe.

When building Slicer using the Centos 7 (GCC 7) build environment[^1], warnings like this one are reported:

[^1]: https://github.com/Slicer/Slicer/pull/7401

```
Slicer/Libs/MRML/Core/Testing/vtkMRMLSceneViewNodeTest1.cxx:
 In function ‘int vtkMRMLSceneViewNodeTest1(int, char**)’:
Slicer/Libs/MRML/Core/vtkMRMLCoreTestingMacros.h:328:62:
 warning: ‘vtkStdString::operator const char*()’ is deprecated: Call `.c_str()` explicitly [-Wdeprecated-declarations]
   const char * originalStringPointer = object->Get##variable(); \
```

also raised for example in https://github.com/Slicer/Slicer/actions/runs/6885650499/job/187301131

## Describe the solution you'd 

Since `TEST_SET_GET_STRING` is also used for `char*`[^2][^3], addressing this could instead be done using a template based approach where the compiler would choose the specialization based on the type.

_Originally posted by @jcfr in https://github.com/Slicer/Slicer/pull/7401#pullrequestreview-1735762477_

[^2]: https://github.com/Slicer/Slicer/blob/b41abc4f69a7f99253f6880733be97186dbfbd77/Libs/MRML/Core/vtkMRMLNode.h#L995-L997
[^3]: https://github.com/Slicer/Slicer/blob/b41abc4f69a7f99253f6880733be97186dbfbd77/Libs/MRML/Core/vtkMRMLCoreTestingUtilities.cxx#L207C13-L209

## Describe alternatives you've considered

NA

## Additional context

* https://github.com/Slicer/Slicer/pull/7401
* https://github.com/Slicer/Slicer/pull/7411
* https://github.com/Slicer/Slicer/pull/7419

**Comment by lassoan** [comment]
To fix the warnings, we should use the appropriate test macros.

- `CHECK_STRING...` macros are for classic VTK string (that are get/set as `char*`) properties
- `CHECK_STD_STRING...` macros are for std::string properties (see for example [here](https://github.com/Slicer/SlicerGitSVNArchive/blob/65e92bb16c2b32ea47a1a66bee71f238891ee1ca/Libs/vtkAddon/vtkAddonTestingMacros.h#L168))
