### ISSUE TITLE
Sequence Nodes won't save to .nrrd

### ISSUE THREAD

**Issue by ashgillman** [Slicer/Slicer#7408]
## Summary

Introduced in #6482, CLI Modules should be able to use Sequence Nodes as input for "dynamic-contrast-enhanced", "signal", or "multichannel" images. However, doing so attempts to save files to .nrrd, which is not supported by the Sequence Storage Node https://github.com/Slicer/Slicer/blob/main/Libs/MRML/Core/vtkMRMLSequenceStorageNode.cxx#L148-L203

## Steps to reproduce

1. Load at least 2x images in a common sampling space
2. Create a Sequence with them in the Sequences node.
3. Set the sequence as input to Input 4D Image in PkModeling
4. Run PkModeling
5. Get an error:

```
vtkMRMLSequenceStorageNode::WriteDataInternal: No file extension recognized: /private/var/folders/_3/5s_kvnhj53x7sny2_71tf3lr0000gp/T/Slicer-gil2a4/BIIA_vtkMRMLSequenceNodeBA.nrrd


ERROR writing file /private/var/folders/_3/5s_kvnhj53x7sny2_71tf3lr0000gp/T/Slicer-gil2a4/BIIA_vtkMRMLSequenceNodeBA.nrrd
```
Resulting in:
```
PkModeling standard error:

/Applications/Slicer.app/Contents/Extensions-31382/PkModeling/lib/Slicer-5.2/cli-modules/PkModeling: exception caught !
/Volumes/D/S/S-0-build/ITK/Modules/IO/ImageBase/include/itkImageFileReader.hxx:132:
 Could not create IO object for reading file /private/var/folders/_3/5s_kvnhj53x7sny2_71tf3lr0000gp/T/Slicer-gil2a4/BIIA_vtkMRMLSequenceNodeBA.nrrd
The file doesn't exist. 
Filename = /private/var/folders/_3/5s_kvnhj53x7sny2_71tf3lr0000gp/T/Slicer-gil2a4/BIIA_vtkMRMLSequenceNodeBA.nrrd




PkModeling completed with errors
```

## Environment
- Slicer version: 5.2.2 r31382 / fb46bd1
- Operating system:  Mac 14.1 (23B74)

**Comment by ashgillman** [comment]
I've tested again, to the same effect, w/ Slicer version: 5.5.0-2023-11-18 r32348 / f48756b

**Comment by lassoan** [comment]
If a sequence contains volumes with the same geometry then the default storage node should be a volume sequence storage node. This can load/save nrrd files. If you post a link to a file with that you can reproduce the issue then we can have a look.

**Comment by ashgillman** [comment]
Great, thanks for that info. Unfortunately I'm not able to share the data as it is patient data.

It seems that my original data indeed has one volume with an abhorrent sampling.

However, I omitted that I used the Sequence Registration module to co-register all the volumes. This registered Sequence was the actual input to PkModeling and seems to have consistent sampling. Could the fact that it is derived from a non-Volume Sequence prevent it from becoming one with registration?

Apologies. If this isn;t a bug I'm happy to move this to the forum.

**Comment by lassoan** [comment]
If you remove the irregular time point from the sequence, create a new storage node for it (by deleting its old storage node; or by cloning to create new node) then can you save the sequence as NRRD?

**Comment by ashgillman** [comment]
Apologies for quite a delay on this, I was pulled away from this project.

Indeed: removing the irregular time point allows saving to NRRD.
I have tried using the Sequence Registration node to have all the sampling the same, and also to manually resample the irregular time points to the same sampling, but then it cannot save to NRRD. So I guess there is some metadata that the resampling isn't harmonising.

I actually run into a new error though with PkModelling, it seems to assume some MultiVolume metadata?
> ITK ERROR: Missing attribute 'MultiVolume.FrameIdentifyingDICOMTagName'.

**Comment by ashgillman** [comment]
Small unrelated note: You mentioned to clone the Sequence. Actually it seems cloning a Sequence instead will make a clone of the first volume.

Maybe this is a bug? As noted, I am using older 5.2.2 (due to an unrelated error on Mac with some extensions failing. I need to follow up later, seems to be related to https://discourse.slicer.org/t/the-dependency-dicomrtimportexport-failed-to-be-loaded-slicerrt-issue/32073/4)

**Comment by lassoan** [comment]
>  Actually it seems cloning a Sequence instead will make a clone of the first volume.

Probably you used the GUI to clone the seuence by clicking on the proxy node in the subject hierarchy (the sequence node itself does not show up in the subject hierarchy).

Overall, I'm not user if any fix or change is needed in Slicer. It is more likely that there are just a few things to clarify about how to use this - unfortunately somewhat complicated - API. I'm closing the issue now but please feel free to start a discussion on the Slicer forum (https://discourse.slicer.org) anytime.
