### ISSUE TITLE
Doubleclick to maximize sliceViews and threeDViews stopped working

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#7429]
## Summary

See this discussion:

https://discourse.slicer.org/t/maximize-views-on-double-click-stopped-working/33025/4

## Steps to reproduce

Use latest and try doubleclicking.

## Environment
- Slicer version: Local build linux from git main as of 2023-11-15
- Operating system: linux

**Comment by pieper** [comment]
@jcfr do you think it could be related to https://github.com/Slicer/Slicer/pull/7311 ?

**Comment by jamesobutler** [comment]
I can confirm this issue exists on Slicer 5.6.0 stable on the Windows platform. I often use this mouse shortcut as well to maximize views so this is a quite obvious bug for me as well.

The current workaround is that you must click the "Maximize/Restore" button located in the Slice view controller.
