### ISSUE TITLE
Sequence proxy node not updated after reopening scene with stored sequence

### ISSUE THREAD

**Issue by che85** [Slicer/Slicer#7440]
## Summary

@lassoan 

When loading a scene that includes a sequence in Slicer 5.6.0 (I only tested with volume sequence), the proxy node of the sequence node is not updated anymore when playing the sequence.

## Steps to reproduce

1. Download from SampleData: CT Cardio Sequence
2. Save the current scene to .mrb file
3. close scene
4. reopen .mrb file
5. play sequence --> proxy node is not updated 

## Environment
- Slicer version: Slicer-5.6.0 stable
- Operating system: tested on Windows and Mac

**Comment by lassoan** [comment]
Thanks for reporting, I'll investigate.
