### ISSUE TITLE
Fix  error checking the latest version of pip

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#7448]
## Is your feature request related to a problem? Please describe.

After updating the Slicer python packages in https://github.com/Slicer/Slicer/commit/028fb31981eec40056d52759e42723e44b30bf86, where pip was upgraded from version `23.1.2` to `23.3`, the version check for pip availability fails under specific circumstances, as detailed in https://github.com/pypa/pip/issues/12357. Instead of the expected update message, the following warning is reported:

```
WARNING: There was an error checking the latest version of pip.
```

## Describe the solution you'd like

As proposed in [pip issue #12357](https://github.com/pypa/pip/issues/12357#issuecomment-1765844404), a potential solution involves updating the launcher setting `PIP_DISABLE_PIP_VERSION_CHECK` to `1`. More information about this setting can be found [here](https://pip.pypa.io/en/stable/cli/pip/#cmdoption-disable-pip-version-check). This approach not only addresses the specific warning but also disables the check for outdated versions in Slicer. Given that package updates occur on a quarterly basis, suppressing this warning would reduce unnecessary console clutter.

## Describe alternatives you've considered

Considering that the issue was resolved in pip version `22.3.1` through https://github.com/pypa/pip/pull/12363, an alternative solution involves simply updating the bundled version of pip in Slicer while keeping the version check enabled.

## Additional context

NA

**Comment by jcfr** [comment]
cc: @jamesobutler @pieper

**Comment by pieper** [comment]
Yes, that sounds good to me, thanks for looking into it.
