### ISSUE TITLE
A technical question！！！

### ISSUE THREAD

**Issue by yinyin-llll** [Slicer/Slicer#7481]
## Summary

Is there any way to implement the mapping of my red arrows, and the CT displayed will still be normal? The top one was linearly mapped, but only the window level of the bone was left. What I need is the bottom result, that is Normal results.

![c94597384e409dc609cc624bf85dcba](https://github.com/Slicer/Slicer/assets/56313508/138ca6c0-77dc-48b4-8a14-15e049429eae)

**Comment by lassoan** [comment]
We use the issue tracker for tracking status of bugs and planned enhancements. We use the [Slicer Forum](https://discourse.slicer.org) for questions and discussions. Please post your question there. Thank you!
