### ISSUE TITLE
VTK build error

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#7504]
This line fails to build on MSVC:

https://github.com/Slicer/VTK/blob/08161371c282cd7eb8ce3058882e6ffa846fac67/Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx#L1083

Changing it to `#ifdef VTK_REPORT_OPENGL_ERRORS` seems to fix the issue. The problem is already fixed in VTK master.

**Comment by jcfr** [comment]
It was fixed in https://github.com/Kitware/VTK/commit/8d73768a09c7a7c286751c079006a697d5e2f5cf through [MR-10664](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10664)
