### ISSUE TITLE
[BUG] Can't load .seg.nrrd from Version 4.10 in Version 5.6

### ISSUE THREAD

**Issue by dkermany** [Slicer/Slicer#7510]
## Summary

I had segmentations done in version 4.10, however, trying to load them in version 5.6 has the segmentations scales and positioned incorrectly relative to the input image. How do I resolve this issue so that I can use my segmentations with newer versions of slicer?

## Steps to reproduce
1. Create a segmentation for a volume in 4.10
2. Save segmentation as .seg.nrrd
3. Load volume and segmentation in 5.6
4. Segmentation and volume should now appear misaligned

## Environment
- Slicer version: 4.10 & 5.6
- Operating system: Windows + Mac

**Comment by pieper** [comment]
Thanks for the report - please try setting the coordinate system to LPS when loading (enable the options in the Add Data dialog).  If that doesn't work, please provide a sample file for debugging.

**Comment by dkermany** [comment]
Clicking the options button in the Add Data dialog does not seem to present options for coordinate systems. See attached.
<img width="1129" alt="Screenshot 2023-12-25 at 12 17 45 AM" src="https://github.com/Slicer/Slicer/assets/6502959/998a9b11-8dfe-429f-abd9-eef7357d9acc">

**Comment by pieper** [comment]
Okay, right, I guess that's not an option for volumes.  Maybe it's something else then.  It would be good for you to upload an example segmentation based on SampleData and someone should be able to have a look.  4.10 is pretty old by now but this should work.

**Comment by lassoan** [comment]
The reporter of the issue did not respond.
