### ISSUE TITLE
Volume hides labels of unoccluded markup points after shadows were made visible

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#7520]
## Summary

Enabling and disabling shadows visibility makes volume rendering hide markup point labels as if the volume was a solid block.

## Steps to reproduce

- Load MRHead sample data
- In Data module, drag-and-drop the volume into a 3D view to show it using volume rendering
- Drop a markup points on the volume's surface and a few farther from it => all the point labels are visible (even if the point is occluded, which is not optimal, but not a regression, it is acceptable)
- Enable shadow visibility
- Labels of visible points are visible => good
- Labels of occluded points are not visible => good
- Dsiable shadow visibility
- Labels of all points on the volume's surface are no longer visible => ERROR
- Labels of farther points are not visible if the entire cube of the volume would occlude it =-> ERROR (point labels should not be occluded if the label itself is visible)

## Analysis

I've tried to remove the `GLDepthMaskOverride` property keys of all volumes in the renderer (`info->Remove(vtkOpenGLActor::GLDepthMaskOverride())`) but it had no effect. All the labels of points within the volume's bounding were still hidden.

After that I've set the mask override to `0` (`info->Set(vtkOpenGLActor::GLDepthMaskOverride(), 0)`) and that restored the original behavior (volume rendering never hides labels).

It seems that enabling/disabling SSAO rendering step permanently changes the depth mask override for volumes. Most likely the issue is here:

https://github.com/Kitware/VTK/blob/ee961519dbd13049d3b0f310a1d3507a888e9326/Rendering/VolumeOpenGL2/vtkOpenGLGPUVolumeRayCastMapper.cxx#L1369-L1389

If `DepthMaskOverride` property key is deleted then the `this->DepthMaskOverride` member variable will be never restored to the default (`false`) but remains always `true`. 

## Proposed fix

The issue should be probably fixed in VTK by changing vtkOpenGLGPUVolumeRayCastMapper.cxx so that if depth mask override property key is missing then treat it as there is no override (set `this->DepthMaskOverride = false` by default).

## Environment
- Slicer version: Slicer-5.7-2023-12-31
- Operating system: Windows 11

**Comment by lassoan** [comment]
Confirmed that adding `this->DepthMaskOverride = false;` right after [this line](https://github.com/Kitware/VTK/blob/ee961519dbd13049d3b0f310a1d3507a888e9326/Rendering/VolumeOpenGL2/vtkOpenGLGPUVolumeRayCastMapper.cxx#L1369) fixes the issue.

@LucasGandel please check and if you sibmit a fix for the depth buffer anyway, it would be nice if you could include this fix, too. Thank you!

**Comment by LucasGandel** [comment]
@lassoan Thank you so much for the report and investigations, it helps a lot.
I did not take the time to reproduce as I confirm the fix you propose completely makes sense, the DepthMaskOverride flag should always be reset. I will add this fix when pushing the depth buffer fix related to #7518. Thank you so much

**Comment by lassoan** [comment]
Great, thank you!

**Comment by LucasGandel** [comment]
VTK MR here: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10807

**Comment by lassoan** [comment]
Fixed by the referenced VTK updates.
