### ISSUE TITLE
“Compare volumes” module permanently engulf working memory and processing units once used in a specific Slicer dataset.

### ISSUE THREAD

**Issue by bailom** [Slicer/Slicer#7522]
I'm not a computer expert (I'm a clinician and medical researcher). I posted the issue in Slicer community forum first (https://discourse.slicer.org/t/compare-volumes-module-display-order/31261/5) and was suggested to report the issue also here. I apologize if, perhaps, I'm not doing it in right way.

I have been using the “compare volumes” a lot in the last months (with different Slicer versions, including the latest updates).

Unfortunately, I noticed that in those datasets where I used this module at least once, things start to go extremely slow thereafter: even scrolling a single series in the Red view alone shows extreme “lagging”. The problem persists even if save and close the scene, reboot the pc (which is an incredibly powerful workstation with 128 GB DDR RAM and 12th Gen Intel Core i9-12900F, 2400 Mhz, 16 Cores, 24 Logical Processors; Windows 11 Pro) and reload the saved scene.

On the contrary, this problem does not occur when I “manually” set the same number of panels, such as a “4 by 3” or even “7 by 3” scenes, without using the “compare volumes” module.

My impression is that once the “compare volumes” module is utilized to display multiple views, it somehow keeps occupying a huge amount of resources, even if the additional view-panels are not shown anymore. It gets better again if I manually delete all the additional Slice-views created from the “Data”->”All Nodes” module.

**Comment by lassoan** [comment]
Can you give a step-by-step description (starting with loading some data from Sample Data module or other openly available repositories) to reproduce the slowdown?

**Comment by lassoan** [comment]
No response received from the user.
