### ISSUE TITLE
Cannot start after setting language to Chinese

### ISSUE THREAD

**Issue by FFFPrime** [Slicer/Slicer#7523]
## Summary
When the language is set to **Simplified Chinese** in **Utilities\Language Tools**, the program cannot be opened after restarting, and the Windows problem report shows that `SlicerApp-real.exe` has stopped working. Switching to **Japanese** will display Japanese normally, switching to **Traditional Chinese** will display English, but it can start normally.

After careful investigation, after deleting the **Slicer_zh-CN.qm** file in the `%LocalAppData%\slicer.org\Slicer 5.6.1\bin\translations`  directory, the program can start normally.

## Steps to reproduce

1. Press Ctrl+4, enter **Extensions Manger**, search for "language", you can see a utility called **LanguagePacks**, restart the software after installation
2. Press Ctrl+2, open **Application Setting**, check **internationalization**, and restart the software.
3. Click **Utilities**→**Language Tools** in the module options, select **Weblate** in the Input translations column, click the **refresh** button, you can see a list of many languages, check **Japanese**, **Simplified Chinese** and **Traditional Chinese**, click **Update translation files** , the translation file will start to download automatically. After downloading, restart the software
4. Open **Language Tools** again, select **Application language** as **Chinese (China)** at the top, click **Restart the application** on the right, and the software will restart.

![repo1](https://github.com/Slicer/Slicer/assets/47420679/00876f83-97b7-4629-b012-85cf9d595775)

5. When starting the software, text such as the initialization module will be displayed, but when it reaches the `Loading module "SegmentEditor"... `stage, it will crash.
![repo2](https://github.com/Slicer/Slicer/assets/47420679/2363c2fb-41ba-451d-99d2-061bef3e1958)

6. Also select the **second** Chinese (China). After restarting, the software can be started normally but it is displayed in **English**.

7. After selecting **Japanese**, the software starts normally and the translation takes effect.
![repo3](https://github.com/Slicer/Slicer/assets/47420679/64d70e7d-09b3-43e3-99e8-951b02c38598)

##  Environment
System: Windows 10 Chinese version
System version: 22H2(19045.3803)
Slicer version: 5.6.1 Stable Release (You see there is no utility named Language Tools in Preview Release )

## Problem log of Windows system
Source: SlicerApp-real.exe
Summary: Stopped working
Date: 2014-01-‎08 23:22
Status: Report Sent
Wrong application path: C:\Users\1233\AppData\Local\slicer.org\Slicer 5.6.1\bin\SlicerApp-real.exe
Problem event name: APPCRASH
Application name: SlicerApp-real.exe
Application version: 0.0.0.0
Application timestamp: 65633afb
Faulty module name: Qt5Widgets.dll
Faulty module version: 5.15.2.0
Faulty module timestamp: 5fa4de1c
Exception code: c0000005
Exception offset: 0000000000032fe9
OS version: 10.0.19045.2.0.0.768.99
Locale ID: 2052
Additional information 1: 6cfd
Additional information 2: 6cfdfc8dd99a7ae0ef76343ef9579a3f
Additional information 3: f94b
Additional information 4: f94bf039ba88192a82b805ca52b38915
Bucket ID: 4ebf9e4a2a29d98d46356509a199b490 (1600296334640395408)

**Comment by FFFPrime** [comment]
This problem exists but is not limited to 5.6.0 and 5.6.1. [Netizens](https://blog.csdn.net/CodeWorld1999/article/details/135457559) said that version 5.2.2 can use Simplified Chinese normally.

**Comment by pieper** [comment]
Thanks for the report - this should be working.  Probably it's a regression due to some translation files.

Are you able to check the Slicer application logs from the version that didn't start up?  (In the Help menu -> report a bug you can see logs from recent previous runs).

**Comment by lassoan** [comment]
The issue is that in the Chinese translation, the string that was used as category name of "Segment Editor" module was already used as module name. This made Slicer crash at startup (I'll fix this today, it'll just log a warning instead), but you need to modify the Chinese translation to not use the same word (分割) as both module name and module category. In English, the module name is "Segmentations", while the category name is "Segmentation".

It "worked" in Slicer-5.2 because there it was not possible to translate Python scripted modules, such as the Segment Editor.

**Comment by lassoan** [comment]
@FFFPrime I see that on the [Chinese forum](http://t.csdnimg.cn/go0T7) the conclusion is:

![image](https://github.com/Slicer/Slicer/assets/307929/19654246-13b9-4f7d-a043-a3539ca78248)

This conclusion is misleading, as we fixed the software issue immediately and downgrading to a several-year-old Slicer version (that has barely any translation) is not a good solution. Please add comment in that Chinese forum that clarifies that the problem is fixed and users should upgrade to the latest Slicer Preview Release (and modify translation of "Segmentations" module and "Segmentation" category so that they are not translated exactly the same).

**Comment by Programming-D** [comment]
> @FFFPrime I see that on the [Chinese forum](http://t.csdnimg.cn/go0T7) the conclusion is:
> 
> ![image](https://private-user-images.githubusercontent.com/307929/295602966-19654246-13b9-4f7d-a043-a3539ca78248.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDQ5MTAsIm5iZiI6MTcwNzMwNDYxMCwicGF0aCI6Ii8zMDc5MjkvMjk1NjAyOTY2LTE5NjU0MjQ2LTEzYjktNGY3ZC1hMDQzLWEzNTM5Y2E3ODI0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxMTE2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjQ5Njc0NjNiZGNhNjBlZjk3YjA5MGI0NjYxNzRmNDBjOGMyYzJiMDkwNDQyMjc1Nzc2ZjcyM2NjNDJjMzQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NdPcpbSpWeaMwyE9DCHIybOBS5InZlidP05AcoVGQ60)
> 
> This conclusion is misleading, as we fixed the software issue immediately and downgrading to a several-year-old Slicer version (that has barely any translation) is not a good solution. Please add comment in that Chinese forum that clarifies that the problem is fixed and users should upgrade to the latest Slicer Preview Release (and modify translation of "Segmentations" module and "Segmentation" category so that they are not translated exactly the same).

Thanks for your prompt reply! I have added comment on the blog to explain what the exact problem lies as you mentioned!
