### ISSUE TITLE
SlicerDMRI not building on mac SlicerStable

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#7530]
## Summary

https://slicer.cdash.org/build/3267614

SlicerDMRI extension for 5.6.1 is an old version from Dec 12, 2023 and doesn't have the latest commits.

The current SlicerPreview version is up to date.  Both point s4ext files in the main and 5.6 branches point to the master branch of the SlicerDMRI repository.

## Steps to reproduce

The dashboard reports this error:

```
CMake Error in Libs/vtkDMRI/CMakeLists.txt:
  Imported target "vtkTeem" includes non-existent path

    "/Applications/Xcode-14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/OpenGL.framework"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.
```

@jcfr or @sjh26 could you have a look at the mac build machine or suggest how this could be fixed?

**Comment by jamesobutler** [comment]
This appears to have been resolved by https://discourse.slicer.org/t/many-extensions-are-not-getting-updates-for-slicer-stable-release/34343/4.

@pieper can confirm prior to closing.

**Comment by pieper** [comment]
@jhlegarreta or @ljod could you check before this is closed?

**Comment by ljod** [comment]
Hi yes now I get a Dec 30 version of SlicerDMRI, more recent than the previous one that was stuck on Dec 12.

**Comment by ljod** [comment]
Hi I am getting a Dec 30 version of SlicerDMRI on Mac when I install it in Slicer 5.6.1. Is that what we expect? Or do we expect something from Jan 11?

**Comment by ljod** [comment]
Hi again. I see two different dates, Dec 12 in the extension itself and Dec 30 in the Extension manager info webpage thing. I am not sure why this is. See screenshots. This is after uninstalling and reinstalling SlicerDMRI today using Slicer 5.6.1 on Mac. It seems it is not updated. Please advise. 

<img width="831" alt="Screenshot 2024-02-21 at 3 57 21 PM" src="https://github.com/Slicer/Slicer/assets/4721911/caabf770-c7e7-4091-9956-e72865161317">

<img width="906" alt="Screenshot 2024-02-21 at 3 56 36 PM" src="https://github.com/Slicer/Slicer/assets/4721911/9ff932ae-12ba-446c-830e-9bc4cf504fe8">

**Comment by lassoan** [comment]
SlicerDMRI builds no macOS now.

**Comment by jcfr** [comment]
As of 2024.10.01:

![image](https://github.com/user-attachments/assets/6df0ebd6-2d09-4f5f-b3cb-68b0601e3b3d)
