### ISSUE TITLE
3D slicer quitting abruptly on arch linux.

### ISSUE THREAD

**Issue by divital-coder** [Slicer/Slicer#7536]
## Summary
3D slicer not being able to generate the GUI on arch linux systems based on hyprland.

## Steps to reproduce
Hands on an arch linux machine on using hyprland window manager.
Install 3dslicer-git from the aur (yay or paru)
Launch the 3dslicer, nothing shows up, the program exits abruptly.
## Environment
- Slicer version: Slicer-5.1.0-2024-01-11
- Operating system: Linux- Arch linux (Hyprland)

**Comment by divital-coder** [comment]
![Uploading Screenshot_2024-01-12-01-58-33_27680.png…]()

**Comment by jcfr** [comment]
Thanks for the report, I suggest you instead report the issue in the forum where this particular problem will be more visible.

Am I also correct assuming you are referring to https://aur.archlinux.org/packages/3dslicer-git ? 

In the meantime, I suggest we close this issue.

Relevant discussions:
* https://discourse.slicer.org/t/availability-of-slicer-5-0-on-archlinux/23245/10
* https://discourse.slicer.org/t/build-slicer-stable-release-from-the-source-on-archlinux/14236

**Comment by divital-coder** [comment]
Alright, thanks for that, i opened an issue cuz it prompted me so to report for potential bugs and issues.
you can close this, since i installed the 3dslicer-bin instead and it works great.
Although still not sure what could cause the 3dslicer-git to not be functional....

**Comment by jamesobutler** [comment]
@jcfr We may seek to improve the location of where to report crashes as mentioned at https://github.com/Slicer/Slicer/issues/6653.
