### ISSUE TITLE
Display warning when 3D image is saved as TIFF file

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#7588]
## Summary

Users may not know that TIFF file cannot store image orientation and Z spacing and so they lose this information when saving the scene.

See for example this user error report: https://discourse.slicer.org/t/older-scenes-and-specimens-loading-incorrectly/34328

## Steps to reproduce

- Load MRHead example
- Save as TIFF file => ERROR: no warning is displayed
- Load the TIFF file => ERROR: the image is distorted

## Environment
- Slicer version: Slicer-5.6.1
- Operating system: Windows11

**Comment by lassoan** [comment]
It would be better to change the default file format for 3D images loaded from TIFF to nrrd.

**Comment by pieper** [comment]
I believe in the past the mrml node's ijkToRAS was preserved when saving to formats like jpg or tiff (e.g. when the mrml file points to the original data), but avoiding any ambiguity in save/restore is the most important goal, so making nrrd be the default for new storage makes good sense.

**Comment by lassoan** [comment]
Fixed in https://github.com/Slicer/Slicer/pull/7655
