### ISSUE TITLE
Add support for unregistering segment editor effects

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#7589]
## Is your feature request related to a problem? Please describe.

In the context of custom application or workflow, it may be sensible to reduce the set of effects available to the user.

## Describe the solution you'd like

* Add `qSlicerSegmentEditorEffectFactory::unregisterEffect` and associated signal `effectUnregistered(QString)`
* Update `SegmentEditor.py` adding `editorEffectUnregistered()` signal handler 

## Describe alternatives you've considered

NA

## Additional context

* https://github.com/Slicer/Slicer/blob/main/Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorEffectFactory.h
* https://github.com/Slicer/Slicer/blob/main/Modules/Scripted/SegmentEditor/SegmentEditor.py

cc: @ludicludo

**Comment by jcfr** [comment]
cc: @lassoan

**Comment by jamesobutler** [comment]
Is there a need for unregistering a segment editor effect when there already exists a method to customize the list of available of displayed segment editor effects? https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#customize-list-of-displayed-segment-editor-effects
```python
segmentEditorWidget = slicer.modules.segmenteditor.widgetRepresentation().self().editor
segmentEditorWidget.setEffectNameOrder(["Paint", "Erase"])
segmentEditorWidget.unorderedEffectsVisible = False
```

**Comment by lassoan** [comment]
Agreed, unregister should not be necessary. Customizing the list and order of effects is also more flexible than globally removing the possibility of using an effect in the entire application.

**Comment by jcfr** [comment]
Thanks for the follow-up, considering it is already possible to customize the list of effects, I am closing this issue.
