### ISSUE TITLE
3d slicer 5.6.1 vtk complie error

### ISSUE THREAD

**Issue by xjjgjmeng** [Slicer/Slicer#7637]
I compiled 3D slicer (5.6.1), but vtk failed to compile successfully (vs2019, Qt5.15.2). It seems to be python related, and one of them reported an error:

```
16> Generating Python wrapper sources for vtkAbstractGridConnectivity
16> vtkWrapPython-9.2d.exe: In D:/gitrepos/Slicer/build/VTK/Filters/Geometry/vtkAbstractGridConnectivity.h:1: syntax error.
16>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: “D:\gitrepos\Slicer\build \VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkAbstractGridConnectivityPython.cxx.rule;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkAttributeSmoothingFilterPython.cxx .rule;D:\gitrepos\Slicer\build\VTK-build \CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkCompositeDataGeometryFilterPython.cxx.rule;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkDataSetRegionSurfaceFilterPython.cxx .rule;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a \vtkDataSetSurfaceFilterPython.cxx.rule;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkExplicitStructuredGridSurfaceFilterPython.cxx.rule;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af1 1fe569d29134735de9f076a\vtkGeometryFilterPython.cxx .rule; D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkHierarchicalDataSetGeometryFilterPython.cxx.rule; f076a\vtkImageDataGeometryFilterPython.cxx.rule;D :\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkImageDataToUniformGridPython.cxx.rule;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vt kLinearToQuadraticCellsFilterPython.cxx.rule;D:\gitrepos\ Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkMarkBoundaryFilterPython.cxx.rule;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkProjectSphereFilterPython .cxx.rule;D:\gitrepos\Slicer\build\ VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkRecoverGeometryWireframePython.cxx.rule;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkRectilinearGridGeometryFilter Python.cxx.rule;D:\gitrepos\Slicer\build\VTK-build\ CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkRectilinearGridPartitionerPython.cxx.rule; ;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\ vtkStructuredAMRNeighborPython.cxx.rule;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkStructuredGridConnectivityPython.cxx.rule;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569 d29134735de9f076a\vtkStructuredGeometryFilterPython.cxx. rule;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkStructuredGridPartitionerPython.cxx.rule;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a \vtkStructuredNeighborPython.cxx.rule;D: \gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkStructuredPointsGeometryFilterPython.cxx.rule;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\v tkUnstructuredGridGeometryFilterPython.cxx.rule;D:\gitrepos\Slicer \build\VTK-build\CMakeFiles\403ee1af11fe569d29134735de9f076a\vtkFiltersGeometryModulePython.cxx.rule;D:\gitrepos\Slicer\build\VTK-build\CMakeFiles\91e9c2b522b46bd386e977bc61299a90\vtkFiltersG eometryPythonInit.cxx.rule" exited with code 1 . [D:\gitrepos\Slicer\build\VTK-build\vtkFiltersGeometryPython.vcxproj]
```

**Comment by xjjgjmeng** [comment]
@lassoan Do you know how to solve this? thank you.

**Comment by xjjgjmeng** [comment]
The error reported when compiling `vtkCommonColorPython` is as follows:
![image](https://github.com/Slicer/Slicer/assets/134293399/76104278-91a5-45d0-b874-15cf4f9e39eb)

**Comment by jcfr** [comment]
Unless the problem has been problem clearly identified[^1], I suggest you post the question at https://discourse.slicer.org/

Once you have done so, considering commenting here with a link to the post so that we can close this issue :pray: 


[^1]: https://slicer.readthedocs.io/en/latest/user_guide/get_help.html

**Comment by xjjgjmeng** [comment]
> Few questions:
> 
> * Do you have an issue building the Slicer `main` branch ?
> * Did you modify the VTK sources in any way ?

I followed the steps below to compile:
1.git clone https://github.com/Slicer/Slicer.git
2.git checkout v5.6.1
3.cmake (no errors)
4. open project
5.do ALL_BUILD


I didn't modify any files, but after compiling I found that a py file was modified：

**Comment by xjjgjmeng** [comment]
> Few questions:
> 
> * Do you have an issue building the Slicer `main` branch ?
> * Did you modify the VTK sources in any way ?

I followed the steps below to compile:
1.git clone https://github.com/Slicer/Slicer.git
2.git checkout v5.6.1
3.cmake (no errors)
4. open project
5.do ALL_BUILD

I didn't modify any files, but after compiling I found that a py file was modified：
![image](https://github.com/Slicer/Slicer/assets/134293399/846b9649-48d9-406a-aeea-5f4f8833f064)

**Comment by xjjgjmeng** [comment]
I tried vs2022 again today, and the following error also occurred：
19:36:17:355	46>  Generating Python wrapper sources for vtkSlicerVolumesLogic
19:36:18:118	46>  vtkWrapPython-9.2d.exe: In D:/Slicer/Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.h:1: syntax error.
`19:36:17:355	46>  Generating Python wrapper sources for vtkSlicerVolumesLogic
19:36:18:118	46>  vtkWrapPython-9.2d.exe: In D:/Slicer/Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.h:1: syntax error.
19:36:18:924	46>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(249,5): error MSB8066: “D:\Slicer\b\Slicer-build\CMakeFiles\c302bb999142b2ae1412943bd7cd9c5f\vtkSlicerVolumesModuleLogicPythonInit.cxx.rule;`

**Comment by xjjgjmeng** [comment]
I tried vs2022 again today, and the following error also occurred:
```
19:36:17:355	46>  Generating Python wrapper sources for vtkSlicerVolumesLogic
19:36:18:118	46>  vtkWrapPython-9.2d.exe: In D:/Slicer/Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.h:1: syntax error.
19:36:18:924	46>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(249,5): error MSB8066: “D:\Slicer\b\Slicer-build\CMakeFiles\c302bb999142b2ae1412943bd7cd9c5f\vtkSlicerVolumesModuleLogicPythonInit.cxx.rule;
```

**Comment by xjjgjmeng** [comment]
The following are the projects that failed to compile (they are all related to vtk python wrapper), and the others passed the compilation:
CTK
Experimental
ITK
SimpleITK
Slicer
SlicerExcutionModel
teem
VTK

**Comment by xjjgjmeng** [comment]
> > “D:\Slicer\b\Slicer-build\CMakeFiles\c302bb999142b2ae1412943bd7cd9c5f\vtkSlicerVolumesModuleLogicPythonInit.cxx.rule;
> 
> Try a very short build path, like `D:\sb`

Now build path is `D:\Slicer\b`，too long?

**Comment by jcfr** [comment]
Thanks for your patience with this.

As hinted by @pieper, consider trying a very short path.

Using `D:\Slicer\b`  may indeed be too long.

**Comment by xjjgjmeng** [comment]
I modified the build path`D:/b`, but the problem still occurs：
![image](https://github.com/Slicer/Slicer/assets/134293399/f566007b-eee5-49fa-a652-2db4220d6bf8)
The compilation result takes vtkCommonColor as an example:
![image](https://github.com/Slicer/Slicer/assets/134293399/a0aa6542-ff1b-406d-8980-0e9fcfc9d3d0)
vtkCommonColor-hierachy:
![image](https://github.com/Slicer/Slicer/assets/134293399/8e56889d-d62b-4adf-896b-da85aee1f396)
vtkCommonColorPython:
![image](https://github.com/Slicer/Slicer/assets/134293399/e617d949-8cc6-40f2-bf87-d1f98f4e02a0)

**Comment by xjjgjmeng** [comment]
https://discourse.slicer.org/t/3d-slicer-5-6-1-vtk-complie-error/34958

**Comment by jcfr** [comment]
Let's now check if the issue has been addressed in the latest version of VTK.

Since the version of VTK built as part of Slicer is not the latest, this will help us understand if the root problem has already been fixed.

To move forward consider building VTK by cloning it from git, see https://docs.vtk.org/en/latest/build_instructions/build.html

**Comment by xjjgjmeng** [comment]
> Throughout your experiments, after opening the solution file of a specific project (e.g `D:/b/VTK-build/VTK.sln`), make also sure you select the build type matching the one used for the outer build (e.g `Release` vs `Debug`)
> 
> Assuming that after opening `VTK.sln`, it looks like you selected the matching build type and were able to narrow down the issue to failure in generating the wrappers (e.g `Generating Python wrapper sources for vtkColorSeries` failed).
> 
> ![image](https://private-user-images.githubusercontent.com/219043/316521747-3960b0f4-92f7-47a9-b5a9-0ed1dd7a42db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzUzNTEsIm5iZiI6MTcxMTUzNTA1MSwicGF0aCI6Ii8yMTkwNDMvMzE2NTIxNzQ3LTM5NjBiMGY0LTkyZjctNDdhOS1iNWE5LTBlZDFkZDdhNDJkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxMDI0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2Y3YTMwMTlmMWU0NWE4ZThmMzc0MWU1MWMyN2FhMTQyZjc3ZDZhM2EyMzEzM2UwNzQzOTJhNWViNjBhY2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QYJU-O80Eyfm0hvm77pkU-9_hD7tqHk9AgYOpponIk8) ![image](https://private-user-images.githubusercontent.com/219043/316521991-8d32a1cb-d9cd-4953-a4c4-5a4dbe3ee47b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzUzNTEsIm5iZiI6MTcxMTUzNTA1MSwicGF0aCI6Ii8yMTkwNDMvMzE2NTIxOTkxLThkMzJhMWNiLWQ5Y2QtNDk1My1hNGM0LTVhNGRiZTNlZTQ3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxMDI0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDY4MDljYjc3ODQ3NDU0ZmYyZTU3YWYyZWMxZTIzYTkyOTUyZWVhNTExYjliZjkxOTU5NmFmNDgwZTUyZGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GA0HESGfiPxGA6uVR5b7vp5QiWYLShM1SNf8w1D7JQ0)
> 
> The expected output should be similar to the following:
> 
> ```
> Rebuild started...
> 1>------ Rebuild All started: Project: vtkCommonColorPython, Configuration: Release x64 ------
> 1>Generating Python wrapper sources for vtkColorSeries
> 1>Generating Python wrapper sources for vtkNamedColors
> 1>Generating Python wrapper sources for vtkCommonColorModule
> 1>Generating the Python module initialization sources for vtkCommonColorPython
> 1>Building Custom Rule C:/D/T/jcfr/vpaw-rel/VTK/CMakeLists.txt
> 1>vtkColorSeriesPython.cxx
> 1>vtkNamedColorsPython.cxx
> 1>vtkCommonColorModulePython.cxx
> 1>vtkCommonColorPythonInit.cxx
> 1>vtkCommonColorPythonInitImpl.cxx
> 1>Generating Code...
> ...
> ```

I compiled it according to your suggestion and the result is as shown below:
![image](https://github.com/Slicer/Slicer/assets/134293399/b477cc0b-d00d-4357-ba63-0cf76078e9dd)

**Comment by xjjgjmeng** [comment]
Another piece of information: I can compile and run and debug on another computer, but the same steps don't work on this computer.

**Comment by lassoan** [comment]
It seems the problem was specific to one computer. Closing this issue due to not having any activity in it for almost 6 months.
