### ISSUE TITLE
Error on mouse interaction: "qMRMLThreeDView::mouseMoveEvent: cannot retrieve camera node"

### ISSUE THREAD

**Issue by osemmler** [Slicer/Slicer#7645]
**Environment**

Slicer version: v5.6.1
Operating System: Ubuntu 23.04
Build: cmake 3.28.3 / g++ 12.3.0 / make 4.3

**Description**

When integrating MRML (Medical Reality Markup Language) components from the Slicer project into a custom application, I encounter an error while attempting to interact using the mouse within a qMRMLThreeDWidget. The specific error message is: qMRMLThreeDView::mouseMoveEvent: cannot retrieve camera node. This issue prevents the intended interact functionality from working correctly in the view.

**Steps to Reproduce**

Initialize a QApplication and setup the MRML scene with a vtkMRMLScene, vtkMRMLInteractionNode, and a vtkMRMLViewNode.
Create a qMRMLThreeDWidget, set its MRML scene and view node.
Run the application and try to zoom in or out using the mouse wheel within the 3D view.
The mentioned error message appears, and the zoom functionality does not work as expected.

**Expected Behavior**

Zooming in and out with the mouse wheel in the qMRMLThreeDWidget should adjust the view accordingly without any errors.

**Actual Behavior**

An error message is displayed in the console, and the zoom functionality does not work: qMRMLThreeDView::mouseMoveEvent: cannot retrieve camera node.

**Code Snippet**
```
#include <QApplication>
#include <vtkMRMLScene.h>
#include <vtkMRMLInteractionNode.h>
#include <vtkMRMLViewNode.h>
#include <qMRMLThreeDWidget.h>

int main(int argc, char *argv[])
{
  qMRMLWidget::preInitializeApplication();
  QApplication app(argc, argv);
  qMRMLWidget::postInitializeApplication();

  vtkNew<vtkMRMLScene> scene;
  scene->SetURL("vtkMRMLScene.mrml");

  vtkNew<vtkMRMLInteractionNode> interactionNode;
  interactionNode->SetCurrentInteractionMode(vtkMRMLInteractionNode::ViewTransform);
  scene->AddNode(interactionNode);

  vtkNew<vtkMRMLViewNode> viewNode;
  viewNode->SetName("View");
  viewNode->SetOrientationMarkerType(1);
  viewNode->SetActive(true);
  scene->AddNode(viewNode);

  qMRMLThreeDWidget* threeDWidget = new qMRMLThreeDWidget();
  threeDWidget->setMRMLScene(scene);
  threeDWidget->setMRMLViewNode(viewNode);
  threeDWidget->resize(800, 600);
  threeDWidget->show();

  return app.exec();
}
```
I would appreciate any guidance or suggestions on resolving this error to ensure proper interact functionality within the qMRMLThreeDWidget.

**Comment by lassoan** [comment]
The `LayoutName` value connects the camera to the view, therefore you must set it, for example by calling `viewNode->SetLayoutName("1");`

Developer support is provided via the Slicer forum (https://discourse.slicer.org) so in the future please post all your questions there.
