### ISSUE TITLE
Compile error on ubuntu 20.04 using QLatin1String::arg()

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#7653]
## Summary

Using the standard linux build instructions on ubuntu 20.04 (in a github codespace) these lines generate an error due to missing .arg method:

https://github.com/Slicer/Slicer/blob/6639f2926196b8f1df16e35a4f8a4acc61ea4dfb/Base/QTGUI/qSlicerExtensionsLocalWidget.cxx#L419-L435

Commenting out the lines allows the compilation to complete and Slicer runs.

## Steps to reproduce

Follow [linux build instructions](https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/linux.html).

## Environment

Slicer main as of 6639f2926196b8f1df16e35a4f8a4acc61ea4dfb, build on Ubuntu 20.04.6 LTS

## See also

https://github.com/commontk/CTK/issues/1196

**Comment by ltetrel** [comment]
Still present in release `5.6.2`, it is still not merged so in the meantime upgrade to `qt5.14` or just apply this patch to avoid calling the method.
```
diff --git a/Base/QTGUI/qSlicerExtensionsLocalWidget.cxx b/Base/QTGUI/qSlicerExtensionsLocalWidget.cxx
index b9c054bd41..30a96291c5 100644
--- a/Base/QTGUI/qSlicerExtensionsLocalWidget.cxx
+++ b/Base/QTGUI/qSlicerExtensionsLocalWidget.cxx
@@ -428,7 +428,7 @@ protected:
     if (!compatible)
       {
       statusText += QLatin1String("<p style=\"font-weight: bold; font-size: 80%; color: %1;\">"
-        "<img style=\"float: left\" src=\":/Icons/ExtensionIncompatible.svg\"/> ").arg(this->WarningColor) +
+        "<img style=\"float: left\" src=\":/Icons/ExtensionIncompatible.svg\"/> ") +
         qSlicerExtensionsLocalWidget::tr("Incompatible with Slicer r%1 [built for r%2]")
         .arg(this->SlicerRevision)
         .arg(this->WidgetItem->data(qSlicerExtensionsLocalWidgetPrivate::InstalledExtensionSlicerVersionRole).toString()) + QLatin1String("</p>");
 ```

**Comment by lassoan** [comment]
Fixed - see https://github.com/commontk/CTK/issues/1196
