### ISSUE TITLE
Identical code in vtkITKMorphologicalContourInterpolator::SimpleExecute

### ISSUE THREAD

**Issue by maddin200** [Slicer/Slicer#7722]
Libs\vtkITK\vtkITKMorphologicalContourInterpolator.cxx line 87
code:
  //
  vtkPointData *pd = input->GetPointData();
  pd=input->GetPointData(); // <- identical

**Comment by jcfr** [comment]
https://github.com/Slicer/Slicer/blob/bfc6f7f67d0dfc15f50c8491218dca8e04cb8187/Libs/vtkITK/vtkITKMorphologicalContourInterpolator.cxx#L84-L89

**Comment by jcfr** [comment]
@maddin200 Thanks for the patch :pray:
