### ISSUE TITLE
unused variable in vtkMRMLNode.cxx

### ISSUE THREAD

**Issue by maddin200** [Slicer/Slicer#7725]
Libs\MRML\Core\vtkMRMLNode.cxx line 517
Code:
 //write node references
  std::stringstream ssRef;
  NodeReferencesType::iterator it;
  std::map< std::string, std::string>::iterator itName; // <- unused

**Comment by lassoan** [comment]
Thank you for pointing this out. It would be awesome if you could send a pull request, but if that's not feasible then we'll get to work on it later.

**Comment by jcfr** [comment]
https://github.com/Slicer/Slicer/blob/3802d812b1a5d855399d8a19cea0bd1705715d52/Libs/MRML/Core/vtkMRMLNode.cxx#L514-L527
