### ISSUE TITLE
 Control point visibility for lines

### ISSUE THREAD

**Issue by riep** [Slicer/Slicer#7729]
## Summary
For a line, when control points are hidden the line disappears in the volume rendering and is still visible in views. 
We could expect that the line is visible in volume rendering as it is for views. 

## Steps to reproduce
    create a line and then run the following code:
    line.SetNthControlPointVisibility(0, False)
    line.SetNthControlPointVisibility(1, False)

## Environment
- Slicer version: Slicer-5.XX
- Operating system:  Linux

**Comment by cpinter** [comment]
I tried the latest Slicer nightly on Windows and on Ubuntu 20.04, and in both cases the line did not disappear in the 3D view (nor the slice views).

Please specify better the Slicer version, 5.XX is very broad, and it seems that in this case it does not apply.

Probably it would be best to use a newer Slicer.

**Comment by riep** [comment]
True this is fixed in nightly. Sorry for that
