### ISSUE TITLE
Issues downloading the sample

### ISSUE THREAD

**Issue by DaniTheStudent** [Slicer/Slicer#7759]
## Summary

I am trying for the past hours to find some acceptable images for 3d slicer. However none seem to be good. The only one i find ideal, actually perfect would be from the sample data section, the brain tumor example. However i can't download the images.. i can load the sample to 3d slicer but i can't download the images to my pc, so i can modify them a bit with C++ and load them back into 3d slicer.

## Steps to reproduce
No idea what steps to folow.. i did save data but had to option to save the images only the entire project

## Environment
- Slicer version: Slicer-5.6.2
- Operating system: Windows

**Comment by lassoan** [comment]
Saving works well (your can delete the mrml file or uncheck the checkbox to avoid saving), or you can right-click on the image in Data module to export.

We use the issue tracker for tracking confirmed issues or feature requests. If you have further questions on how to use 3D Slicer, please post to the Slicer Forum ‐ https://discourse.slicer.org

**Comment by DaniTheStudent** [comment]
I apologize but saving doesn't work well :))
Or not from my point of view.. yes i can save the abra cadabra going on the screen in all kind of formats. But how do i save those hundreds of pictures that create it? 
I can't find anywhere some usefull files.. And i would like to download the ones from the sample, from the example; but looks like there is no option to get the images.. And it should totally be possible.

In case that i am mistaken, do you mind showing how could i get them? Like a folder or something with all the photos, from all the 3 windows red green and yellow (up. side and front angles) So i can modify those images before loading them back in the 3d slicer
    Pe miercuri, 22 mai 2024 la 14:27:44 EEST, Andras Lasso ***@***.***> a scris:  
 
 


Saving works well (your can delete the mrml file or uncheck the checkbox to avoid saving), or you can right-click on the image in Data module to export.

We use the issue tracker for tracking confirmed issues or feature requests. If you have further questions on how to use 3D Slicer, please post to the Slicer Forum ‐ https://discourse.slicer.org

**Comment by lassoan** [comment]
There should not be hundreds of files. When you load the brain tumor sample data set and hit Save, you are offered to save two files: the scene file (you can uncheck the checkbox if you don't want to save your display settings, etc.) and the image file.

![image](https://github.com/Slicer/Slicer/assets/307929/05d6cb9b-441f-46d8-b928-c73c9ba1266a)

**Comment by lassoan** [comment]
Do not expect to see a JPG/PNG/TIFF stack export option for a 3D image file. These file formats do not have a standard way to store the image geometry (image origin, spacing, axis directions), therefore they are not suitable for storing 3D image data.

**Comment by DaniTheStudent** [comment]
Awesome explanation, thanks solved one of my future issues but the thing is.. I might understood this right or wrong:
To create a 3d model in 3d slicer first you need some images (3 sets)
After that you interact with them and save whatever you did
The file you get will be nrrd or some other type of format that can be open with 3d slicer later on

But first you need some images in order to work with 3d slicer. 
Those images from what i noticed when you use the slider are quite a lot, hundreds.

I tried also downloading some zip files from the internet and use my own dataset of images but they were not in the right order or same scenario but images from more than one patient,etc. As i became desperate in finding something suitable, i decided i am going to use the sample images for the brain tumor. However before using it i need to "play" a little with the images in some other program and after that to reimport them to the 3d slicer.

How should i explain this.. ahmm I didn't get to the playing with the 3d slicer part yet. That will come later. First i need a set of images, modify them a bit, and after that add to the 3d slicer in order to create the 3d model and all that kind of stuff. 

Thanks again for your time and i apologize if this email is too long. 


    Pe miercuri, 22 mai 2024 la 16:46:48 EEST, Andras Lasso ***@***.***> a scris:  
 
 


Do not expect to see a JPG/PNG/TIFF stack export option for a 3D image file. These file formats do not have a standard way to store the image geometry (image origin, spacing, axis directions), therefore they are not suitable for storing 3D image data.

**Comment by cpinter** [comment]
I understand that 1:1 user support is more convenient, but I do suggest that you review some of the documentation first.

For example see this section about interaction between different data types:
https://slicer.readthedocs.io/en/latest/user_guide/user_interface.html#review-loaded-data

And this part about different file formats:
https://slicer.readthedocs.io/en/latest/user_guide/data_loading_and_saving.html

**Comment by DaniTheStudent** [comment]
Thank you
    Pe miercuri, 22 mai 2024 la 17:30:32 EEST, Csaba Pinter ***@***.***> a scris:  
 
 


I understand that 1:1 user support is more convenient, but I do suggest that you review some of the documentation first.

For example see this section about interaction between different data types:
https://slicer.readthedocs.io/en/latest/user_guide/user_interface.html#review-loaded-data

And this part about different file formats:
https://slicer.readthedocs.io/en/latest/user_guide/data_loading_and_saving.html
