### ISSUE TITLE
Add documentation for Ctrl + Left-Click-and-drag in 3D view

### ISSUE THREAD

**Issue by parikhmn** [Slicer/Slicer#7770]
## Is your feature request related to a problem? Please describe.
I've been looking to duplicate the ability of the MacOS trackpad to spin a 3D view around the pinch center while using a keyboard and mouse and no trackpad. I came across [this post](https://discourse.slicer.org/t/segment-editor-and-rotate-tumble-orbit-function-in-3d-view/2726/5) describing the existing ability to rotate the 3D view around an axis normal to the plan of the screen by using ctrl + left-click-and-drag. This is exactly the function I was looking for, but it wasn't present in the documentation on [Mouse & Keyboard Shortcuts](https://slicer.readthedocs.io/en/latest/user_guide/user_interface.html#d-views).

## Describe the solution you'd like
Would you be able to add this shortcut to the documentation so that it is a clear option for others in the future?

Thanks!

**Comment by pieper** [comment]
I'm glad you figured this out 👍 Would you be able to make a pull request with the text you think should appear?  Click the "Edit on Github" button at the top right of the page, then the edit button (pencil icon) on the github page and suggest changes.

**Comment by lassoan** [comment]
Documentation was added.
