### ISSUE TITLE
I have found that "Grid Surface" can achieve precise surfaces, so can we use this in turn to generate surfaces from countless points. Just like the effects of the minics below. Because it would be much more convenient to operate in this way

### ISSUE THREAD

**Issue by linhuanfeng** [Slicer/Slicer#7790]
<img width="1512" alt="f9db0bcfaf3b34e6d4dd72a44d9e24f" src="https://github.com/Slicer/Slicer/assets/85426969/d5a016c3-9175-480d-9c67-577f13dcaff3">

I have found that "Grid Surface" can achieve precise surfaces, so can we use this in turn to generate surfaces from countless points. Just like the effects of the minics below. Because it would be much more convenient to operate in this way

https://github.com/Slicer/Slicer/assets/85426969/893b729b-0822-4a80-8509-48fce8960cc7

**Comment by lassoan** [comment]
This is an interesting topic to discuss. This issue tracker is for tracking confirmed problems and planned enhancements. Could you please post this on the Slicer Forum (if you have not done it already) and post the link here? Thank you!
