### ISSUE TITLE
SimpleITK import fails in preview builds of Windows 

### ISSUE THREAD

**Issue by muratmaga** [Slicer/Slicer#7799]
Seems windows specific, Mac and Linux doesn't appear to be affected. See:

https://discourse.slicer.org/t/import-simpleitk-fails/36735

**Comment by SlicerMorph** [comment]
Is there an update on this? This breaking the ImageStacks module, which we use fairly heavily.

**Comment by lassoan** [comment]
It should be fixed now. Let @jcfr know if you still encounter problems.

**Comment by SlicerMorph** [comment]
Unfortunately still same error with todays build. Or should i try tomorrows build?

**Comment by jcfr** [comment]
To follow-up, I am actively working on this :rocket:

**Comment by jcfr** [comment]
@muratmaga @lassoan @blowekamp @jamesobutler 

Fixes were integrated into both our SimpleITK fork[^1] and Slicer itself[^2].

[^1]: https://github.com/Slicer/SimpleITK/compare/1236005d4f501aa87457a2b2d8fb07790169dfd5...slicer-v2.3.1-2024-05-20-bc4449e/
[^2]: https://github.com/Slicer/Slicer/pull/7812

**Comment by blowekamp** [comment]
@jcfr  I back ported some of the CMake changes to SimpleITK here: https://github.com/SimpleITK/SimpleITK/pull/2137

I am little concerned about the challenges of maintaining this forked version of SimpleITK with the namespace changes. Is there something that can be incorporated into upstream SimpleITK to make the maintenance of this easier and reduce the chance of this type of issue and difficulty from reoccurring?
