### ISSUE TITLE
Set filter for DICOM query in python scipted modules from version 5.7.0

### ISSUE THREAD

**Issue by marcus-wirtz-snkeos** [Slicer/Slicer#7801]
With latest preview releast, overwriting attributes like `filters`, or `preferCGET` in `ctk.ctkDICOMQuery()` will raise an `AttributeError` like
```AttributeError: Slot 'filters' can not be overwritten on ctkDICOMQuery object```

What is the proper way to set those attributes in `ctkDICOMQuery` from Slicer version 5.7.0?

https://github.com/Slicer/Slicer/blob/9391c208f0d25a2fe2e6b19667766e759c6160c7/Docs/developer_guide/script_repository/dicom.md?plain=1#L335

**Comment by lassoan** [comment]
Thanks for reporting. Indeed, we have not updated this example when the new-generation DICOM browser wa added. I've updated the documentation now - see https://github.com/Slicer/Slicer/commit/dc97ab25ebc1c595fc74cac4cb6ad93dfc894d58

Query/retrieve can take long time, so the new DICOM browser (or at least the new DICOM job management classes) are recommended, which perform all network communications on background threads.

**Comment by marcus-wirtz-snkeos** [comment]
Thanks for your prompt reply, works perfectly!
