### ISSUE TITLE
unused variable in `vtkMRMLSequenceBrowserNode::SynchronizationProperties::FromString`

### ISSUE THREAD

**Issue by maddin200** [Slicer/Slicer#7840]
File:
Modules\Loadable\Sequences\MRML\vtkMRMLSequenceBrowserNode.cxx line 91

Code:

```
std::string subAttValue; // <-- unused
```

**Comment by jcfr** [comment]
https://github.com/Slicer/Slicer/blob/b05d25b1920bbf46e37ef45672630a7be6af28fc/Modules/Loadable/Sequences/MRML/vtkMRMLSequenceBrowserNode.cxx#L81-L95
