### ISSUE TITLE
Title: Failed to load segmentation in DentalSegmentator extension - nnUNet processing error

### ISSUE THREAD

**Issue by adityashiralkar07** [Slicer/Slicer#7857]
Summary:
I encountered an error while using the DentalSegmentator extension in 3D Slicer. When attempting to run the segmentation process, the following error message was displayed:
"Failed to load the segmentation. Something went wrong during the nnUNet processing. Please check the log files for potential errors and contact the library maintainers."

Steps to reproduce:
Open 3D Slicer (version 5.7.0-2024-07-12) on Windows 11.
Install and enable the DentalSegmentator extension.
Import MRI files.
Attempt to run the segmentation process.
Observe the error message.

Expected behavior:
The segmentation process should complete successfully, generating a 3D model from the MRI scans.

Actual behavior"
The segmentation process fails with the error message:
"Failed to load the segmentation. Something went wrong during the nnUNet processing. Please check the log files for potential errors and contact the library maintainers."

Environment:
Slicer version: Slicer-5.7.0-2024-07-12
Operating system: Windows 11

![Screenshot 2024-07-17 105336](https://github.com/user-attachments/assets/6e77fd0b-286d-4c40-b043-01d9ce284e16)

![Screenshot 2024-07-17 105610](https://github.com/user-attachments/assets/11d57e44-4918-4119-821e-f59753ddb2fb)

![Screenshot 2024-07-18 120432](https://github.com/user-attachments/assets/076aff21-b666-47d6-b471-75cd2c5ce032)

![Screenshot 2024-07-18 123657](https://github.com/user-attachments/assets/a46a1046-fe7b-441c-99ac-871714b581a0)

**Comment by lassoan** [comment]
This is a question about an extension. Please use the Slicer forum or the extensions issue tracker.
