### ISSUE TITLE
Interaction handles do not respect the slice visibility of parent ROI node

### ISSUE THREAD

**Issue by hannah-morilak** [Slicer/Slicer#7865]
## Summary

If you place a markups ROI node and then set its slice display visibility to only some of the slices, its possible that the interaction handles do not match up with that of the parent ROI

![image](https://github.com/user-attachments/assets/59edbc56-f525-4c98-a85c-8be4cc5fb1e9)

## Steps to reproduce

```python
slicer.app.layoutManager().setLayout(slicer.vtkMRMLLayoutNode.SlicerLayoutFourUpView)
roi_node = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsROINode")
roi_node.SetSize([100, 100, 100])
roi_node.GetDisplayNode().SetViewNodeIDs(["vtkMRMLSliceNodeRed"])
```

## Environment
- Slicer version: Slicer-5.7.0-2024-07-22
- Operating system: Windows 10

**Comment by Sunderlandkyl** [comment]
Thanks for reporting, I'll look into it!
