### ISSUE TITLE
questions regarding using Slicer by Python

### ISSUE THREAD

**Issue by mingtian126** [Slicer/Slicer#7876]
Hello, I'm new to the slicer and try to write some python script to do image registration in a batch (loop through many subjects). My images are deidentified DICOM format. When I load images using: 
loadedNodes = DICOMUtils.loadSeriesByUID([seriesUID])
loadedNodeID = loadedNodes[0]
loadedNode = slicer.mrmlScene.GetNodeByID(loadedNodeID)

Since these are deidentified DICOM, the slicer gave warning as: 
[Qt] Patient ID is empty, using studyInstanceUID (xxxx) as patient ID
[Qt] Failed to find patient with PatientsName= and PatientID=

My first question is can I turn off these messages? I think it  will slow down the processing.

My second question is when I try to output the results (volumeNode) using following:
def save_volume(volumeNode, filename):
    myNode = slicer.util.getNode(volumeNode)
    # Create storage node
    storageNode = myNode.CreateDefaultStorageNode()
    # Set file name
    storageNode.SetFileName(filename)
    # Write data
    if not storageNode.WriteData(myNode):
        raise RuntimeError(f"Failed to write volume to file: {filename}")

I got error from "slicer.util.getNode(volumeNode)" as: 
TypeError: object of type 'MRMLCorePython.vtkMRMLScalarVolumeNode' has no len()

If I comment this out and use volumeNode directly, I got error as: 
VTK] vtkMRMLVolumeArchetypeStorageNode::UpdateFileList: Failed to write '/mnt/DataDisc/.../subject/sub2/TempWriteOutVolume/OutVolume'
where mnt/DataDisc/.../subject/sub2/OutVolume is the filename I set. I do see a folder  mnt/DataDisc/.../subject/sub2/TempWriteOutVolume has been created, but empty. 
What's the problem? I saw images appeared on the GUI, so the DICOM loading supposed working? Why it cannot output the volume? I tried to output the loaded DICOM images (loadedNode), same error. I assume something was wrong with the WriteData? Thank you!

**Comment by pieper** [comment]
Hi @mingtian126 - please use [discourse.slicer.org](https://discourse.slicer.org) for usage questions and discussions so we can keep github issues for issues that need be resolved in the code itself.  Also be sure to use markdown's "```" operator around code snippets to preserve formatting.  Also, posting one specific question at a time will make it easier for people to help you out.
