### ISSUE TITLE
Cannot save scene to MRB on Windows if some node names are long

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#7901]
## Summary

Posting this as an issue because it comes up more and more often. If I want to save a scene to MRB that has at least one node with a name longer than ~60 characters (which is not at all unreasonably long), then saving the scene fails, even if I save it to the root directory (e.g. `D:\`).

Such long node names are quite frequent for example in RT data (such as `2: RTDOSE: DOSIsoft:RTDOSE:Phase #1 Dosi Dosi 1: Beam setup 1 (GY) [11]` in the data provided in https://discourse.slicer.org/t/creating-a-module-for-electron-bolus/37766). Another case when I have such long names is when I use a module that combines nodes, such as `ComparisonSubtraction_[NodeName1]_[NodeName2]`. So to me it seems that it is quite standard having a node with a name longer than a few dozen characters.

Important to note that if you save the scene as `.mrml` + data files then saving does not fail in this case.

The relevant part of the log:
```
[Qt] void __cdecl qSlicerSaveDataDialogPrivate::updateStatusIconFromMessageCollection(int,class vtkMRMLMessageCollection *,bool) Data save error: "- Error: MRHeadzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz (vtkMRMLScalarVolumeNode1): Failed to write 'C:/Users/CsabaPintér/AppData/Local/slicer.org/Slicer/cache/SlicerIO/__BundleSaveTemp-2024-08-22_124836_56/2024-08-22-Scene/Data/TempWriteMRHeadzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz/MRHeadzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz.nrrd'\n- Error: Failed to save D:/zzzzzzzzzzzzzzzzzzzz/2024-08-22-Scene.mrb: Failed to save scene to data bundle directory\n- Error: Failed to save scene as D:/zzzzzzzzzzzzzzzzzzzz/2024-08-22-Scene.mrb\n- Error: Saving failed with all writers found for file 'D:/zzzzzzzzzzzzzzzzzzzz/2024-08-22-Scene.mrb' of type 'SceneFile'.\n"
```

## Steps to reproduce
1. Load MRHead in SampleData
2. Go to Data module and rename MRHead: add 60 characters at the end
3. Save scene as MRB to anywhere

## Environment
- Slicer version: Slicer-5.7.0-2024-08-06
- Operating system: Windows 11

**Comment by cpinter** [comment]
What a coincidence, thanks for point out the PR. I did some searches among the issues and did not find one, so I decided to create this. I haven't looked at the PRs

**Comment by Sunderlandkyl** [comment]
I think that the PR doesn't address this problem since it only shortens the temporary bundle directory, and impacts sequences more than regular node types (since they use the bundle directory twice in the same path).

**Comment by cpinter** [comment]
The problem I think is the length of the entire path. I'll test my use cases after that PR is integrated and get back here with what I find.

**Comment by Sunderlandkyl** [comment]
Yeah the problem in both cases is likely the full path length, this issue is also related: https://github.com/Slicer/Slicer/issues/6037.

**Comment by che85** [comment]
At least three team members (@iacovellaj, @akoluda, @zelonis) have been experiencing this issue when saving fails if long node names exist in the scene. Only going into the data module and shortening node names would fix it.

**Comment by cpinter** [comment]
Yes I still see this issue from time to time. The path of the Slicer temp folder and the node name contribute to this together. I can devote some time to fix this if we agree on a good way to do it.

**Comment by che85** [comment]
It would be great to get notified about long node names if saving is likely to fail before saving is attempted. At the moment, the save dialog pops up and only displays errors once the actual saving process is started.

I think, the error messages were not indicating the reason for the failing save was the long file names.

**Comment by zelonis** [comment]
> I think, the error messages were not indicating the reason for the failing save was the long file names.

This was true for me at least. I did not know that the long node names in the file were the reason for the failed save attempt based on the error messages given

**Comment by cpinter** [comment]
Correct, there is currently no warning before nor reason in the error message afterwards. I think there are various reasons contributing to this, and it affects certain components of the saving process. Also there might be solutions other than a warning, for example falling back to another (shorter path) location if any.

**Comment by lassoan** [comment]
I've run into this issue recently, too. The error message is not very specific, because file saving fails at the file system level and the API does not provide any specifics why saving failed.

I think we need a fix at two levels:
- Avoid creating nodes with very long names. Specifically, in `DICOMPlugin.py`, if `seriesDescription` is longer than 20 characters then keep 20 characters of the name (and generate a unique node name using `slicer.mrmlScene.GetUniqueNameByString()`.
- Enforce short filenames by shortening filenames in `qSlicerCoreIOManager::forceFileNameValidCharacters()` (or add a new `forceFileNameValid` method that would call `forceFileNameValidCharacters()` but would also limit the filename; and call this new method everywhere where currently `forceFileNameValidCharacters` is used). If the filename is longer than 25 characters then keep the first 20 characters and add a separator (`_` or space) and a 4-character hash (capital letters, maybe also numbers, generated from the entire name).

The 20, 25, 4 characters can be changed to more or less if somebody thinks that they are not ideal.

**Comment by Sunderlandkyl** [comment]
I've discussed it with Andras, and I'll take a look at this issue starting this week, so that it will hopefully be fixed in the stable release.

**Comment by jamesobutler** [comment]
I assume limited node name lengths is really only necessary for Windows machine that don't have [long paths](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#registry-setting-to-enable-long-paths) enabled. Slicer on macOS and Linux likely don't have to be limited.

**Comment by lassoan** [comment]
Although maximum path length is typically much longer on unix-based systems than on Windows, there are two main reasons to keep the filenames short everywhere.

1. It is better to have the same behavior on all operating systems. We want to be able to load a scene on Windows that was saved on Linux/macOS. Even if the scene can be loaded, we don't want to save some nodes again with a shorter filename on Windows. In general, we want to minimize operating system dependent behavior to make it easier to reprodude and fix issues.

2. Long paths cause problems in many environments, regardless of the operating system. For example, path length is limited in many file systems (e.g., you may not be able to copy a scene with long file paths to a removable drive that was formatted with FAT file system), you may not be able to write files with very long file paths into a zip file, and path length may be limited in some virtual drives and cloud sync services.
