### ISSUE TITLE
 Gray areas in registered images using 3D Slicer

### ISSUE THREAD

**Issue by NastaranVB** [Slicer/Slicer#7911]
Hello,

I used 3D Slicer’s General Registration (BRAINS) to register Brain CT images from two different modalities. An example of the resulting registered image is shown below. Could you please advise on how to address the gray areas that appeared after the registration process?
Thanks in advance.

<img src="https://github.com/user-attachments/assets/7f116db8-a306-48be-96c5-20c662cb3e4a" width="200px">

**Comment by cpinter** [comment]
The background is filled by values of 0 (which in HU is water). If you set the background to -3000 for example, you'll get air.
![image](https://github.com/user-attachments/assets/4a846e17-a860-4901-bc61-d4d04ba2b1c7)

For future user support please use the Slicer forum: https://discourse.slicer.org/
