### ISSUE TITLE
How to add the plug-in module you wrote to slicer in the form of code or command line?

### ISSUE THREAD

**Issue by ningw-git** [Slicer/Slicer#7921]
## Is your feature request related to a problem? Please describe.

Thank you very much for your reply, I have solved this problem. Now I have encountered a new difficulty: I wrote a plug-in myself and put the .py file and .ui file in a folder, but I don't know how to import this plug-in module into slicer. Is there any way to implement it in the code or command line? I urgently need your help, thank you.

## Describe the solution you'd like

I currently only know that I can manually add the module path in Edit->Application Settings->Modules in slicer, but I want to know if there are other ways.

**Comment by pieper** [comment]
Please use discourse.slicer.org for how-to questions, but before you post please review other posts and the documentation since there are standard ways of doing what you are asking about.
