### ISSUE TITLE
DICOM module: Inconsistent checking of disabled plugins

### ISSUE THREAD

**Issue by jadh4v** [Slicer/Slicer#7931]
## Summary

`DICOMBrowser` checks for user-disabled plugins by referring to `QSettings`. Whereas functions in `DICOMUtil` do not. This causes inconsistent behavior when loading DICOM data programmatically through DICOMUtil functions rather than using the user interface (DICOM Browser).

## Steps to reproduce
Particularly, loading dataset using `DICOMUtils.loadPatientByUID(patientUID)` doesn't work the same way as DICOM Browser user actions would.

There appears to be a discrepancy between [DICOMBrowser.py](https://github.com/Slicer/Slicer/blob/main/Modules/Scripted/DICOMLib/DICOMBrowser.py#L471) and [DICOMUtils.py](https://github.com/Slicer/Slicer/blob/main/Modules/Scripted/DICOMLib/DICOMUtils.py#L738) in how they generate the list of available plugins. DICOMUtils.py doesn't check QSettings for user preferences or disabled plugins. We need to move the logic to a common function so all paths will lead to correctly checking for disabled plugins.

## Environment
- Slicer version: https://github.com/Slicer/Slicer/commit/e8a49d6659898eb75ed0980367affd70c7715be6 (July 25, 2024)
- Operating system: _Windows 11 Pro_ 23H2 22635.4145

**Comment by lassoan** [comment]
Please have a look at this pull request for a suggested fix:

https://github.com/Slicer/Slicer/pull/7935

(I've accidentally pushed a commit to Slicer main, I've reverted it, sorry for that noise).
