### ISSUE TITLE
Markups ROI not shown with fill opacity for Coronal slice orientation

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#7944]
## Summary

As originally reported at https://discourse.slicer.org/t/roi-markup-is-not-filled-with-color-in-coronal-view-in-slicer-5-6-0/33341:

A Markups ROI object with a visible 2D fill opacity shows that there an issue with the display of that fill when the slice orientation is "Coronal". 

## Steps to reproduce
```python
slicer.app.layoutManager().setLayout(slicer.vtkMRMLLayoutNode.SlicerLayoutFourUpView)
roi_node = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsROINode")
roi_node.SetSize([100, 100, 100])
```
![image](https://github.com/user-attachments/assets/a73761e2-9e34-4eef-a4e6-168fc309b9d1)

## Environment
- Slicer version: Slicer-5.7.0-2024-09-17 (as of https://github.com/Slicer/Slicer/commit/114731d5f71167f1a2da81ed2494c8201d6a1654), Slicer 5.6.2, 5.4.0
- Operating system: Windows, an issue on Linux and likely on macOS as well

**Comment by jamesobutler** [comment]
cc: @Sunderlandkyl This might be an area of code that you are familiar with to know if there is some missing code or a typo somewhere.

**Comment by shai-ikko** [comment]
Hi. I was on that forum thread, will be happy to help if I can (e.g. with testing on Linux)

**Comment by shai-ikko** [comment]
I was able to test with the latest nightly and verify it was fixed. Thanks!
