### ISSUE TITLE
Add the option to upgrade existing package to slicer.util.pip_install()

### ISSUE THREAD

**Issue by fedorov** [Slicer/Slicer#7957]
## Is your feature request related to a problem? Please describe.

I maintain SlicerIDCBrowser extension that depends on a [`idc-index`](https://github.com/imagingdatacommons/idc-index) python package that wraps access to [Imaging Data Commons (IDC)](https://imaging.datacommons.cancer.gov). As IDC releases new data versions, `idc-index` is updated to support access to the latest version. Currently in Slicer, once the user installed SlicerIDCBrowser, the version of `idc-index` is frozen, and the user cannot access the latest data in IDC.

## Describe the solution you'd like

Since upgrading an existing package is commonly used functionality, I believe it would make sense to add support for the upgrade flag in `slicer.util.pip_install()` in https://github.com/Slicer/Slicer/blob/main/Base/Python/slicer/util.py#L3891.

## Describe alternatives you've considered

I can definitely call `pip install --upgrade idc-index` in my module myself.

**Comment by fedorov** [comment]
I can send the PR if there is agreement that this makes sense.

**Comment by pieper** [comment]
Andrey, did you know you can do` pip_install("--upgrade idc-index")`?  That might be cleaner than `slicer.util._executePythonModule("pip",["install","--upgrade","idc-index"])`

**Comment by fedorov** [comment]
I did not! Thank you!

**Comment by fedorov** [comment]
I did not mean to close this by that PR above. I will let you close it if you feel the workaround by Steve above is sufficient.

**Comment by lassoan** [comment]
This is not a workaround by any means, but a proper solution (by the way, all pip install commands work in the Slicer Python environment as in any other Python requirement).

An alternative solution is to require a specific or minimum version in the module, such as `pip_install("idc-index>=1.2.3"). This has the advantage that you update the source code of the module, which generates a new extension package, which shows up as an extension update in Slicer, so users can see that there is an update. Another small advantage is that there is no need to check the internet so frequently.

**Comment by fedorov** [comment]
Obviously, it was not intuitive to me that "--upgrade" can be included in the parameter to that function. I hope it is obvious to others.

**Comment by lassoan** [comment]
Although it was described in the documentation that the same syntax can be used, it can be unexpected that a Python function takes a command-line argument list as a single string. I clarified this a bit and added an example for `--upgrade` in this pull request: https://github.com/Slicer/Slicer/pull/7959
