### ISSUE TITLE
Failed to export DICOM volume

### ISSUE THREAD

**Issue by chourroutm** [Slicer/Slicer#7963]
## Summary

I tried to export as DICOM a volume I first imported as NIFTI (.nii.gz). The export wizard auto-created the patient/study architecture.

## Steps to reproduce

1. Load .nii.gz volume
2. Select "Export to DICOM"
3. Agree to the creation of a patient and study structure. => Slicer creates  a patient and a study - OK
5. Export. => Fails with following error:

```
Failed to get exportables from plugin DICOMScalarVolumePluginClass
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "C:/Users/Matthieu/AppData/Local/slicer.org/Slicer 5.6.2/bin/../lib/Slicer-5.6/qt-scripted-modules/DICOMScalarVolumePlugin.py", line 597, in examineForExport
    shn = slicer.vtkMRMLSubjectHierarchyNode.GetSubjectHierarchyNode(slicer.mrmlScene)
TypeError: GetSubjectHierarchyNode argument 1: method requires a VTK object
Failed to get exportables from plugin DICOMVolumeSequencePluginClass
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "C:/Users/Matthieu/AppData/Local/slicer.org/Slicer 5.6.2/bin/../lib/Slicer-5.6/qt-scripted-modules/DICOMVolumeSequencePlugin.py", line 66, in examineForExport
    createDicomSeriesParameterNode.UnRegister(None)
AttributeError: 'MRMLCLIPython.vtkMRMLCommandLineModuleNode' object has no attribute 'UnRegister'
Failed to export using plugin DICOMSlicerDataBundlePluginClass
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:/Users/Matthieu/AppData/Local/slicer.org/Slicer 5.6.2/bin/../lib/Slicer-5.6/qt-scripted-modules/DICOMSlicerDataBundlePlugin.py", line 179, in export
    shNode = slicer.vtkMRMLSubjectHierarchyNode.GetSubjectHierarchyNode(slicer.mrmlScene)
TypeError: GetSubjectHierarchyNode argument 1: method requires a VTK object
```

Is maybe the metadata invalid?

<details><summary>Snapshot 1: Export wizard</summary>
<p>

![Screenshot 2024-09-26 115142](https://github.com/user-attachments/assets/7158ae4f-0413-422a-beb1-4c9f4dfea8ba)

</p>
</details> 

<details><summary>Snapshot 2: Data tab</summary>
<p>

![image](https://github.com/user-attachments/assets/5a333114-ee38-40a2-85c3-131068d9c8b1)

</p>
</details> 

(Edit: tried without modifying the metadata this time - same error)

## Environment
- Slicer version: Slicer-5.6.2 r32448 / f10cd8c
- Operating system: Windows 11 23H2

**Comment by lassoan** [comment]
The problem seems to be that `slicer.mrmlScene` is not recognized as a VTK object and a `vtkMRMLCommandLineModuleNode` is not recognized to have a basic VTK object method (`UnRegister`). To me, this indicates that some Slicer extension (or maybe some code that you executed) seriously messed up the entire environment. Maybe you replaced Slicer's VTK by pip installing VTK?

**Comment by chourroutm** [comment]
The preview 5.7 version worked as expected (here the `DICOMScalarVolumePlugin` is recognized). 

![image](https://github.com/user-attachments/assets/10a3f19d-010f-4e4e-8315-e31c763a26bd)


The only installed plugins I had were the ones in the neuroimaging tab.

**Comment by lassoan** [comment]
Great, thanks for the update.
