### ISSUE TITLE
Linked zoom desynchronizes on "reset field of view"

### ISSUE THREAD

**Issue by jadh4v** [Slicer/Slicer#7974]
## Summary

Linked zoom mechanic desynchronizes between 2D views when any of the view is reset by selecting "Reset field of view" from the context menu.

## Steps to reproduce

1. Load any 3D volume / DICOM series into Slicer and select the four-up layout.
2. Select the pin on any of the slice control widgets and select "link slice views" (this should link the three 2D views red, green, and yellow).
3. Now use right-click action to zoom any of the 2D slice views (say Red).
4. Other two views will also zoom.
5. Now right click and select "Reset field of view".
6. All three views are reset.
7. Now right click again but click away from the context menu without selecting anything (perhaps to trigger a redraw)
8. This will re-sync the other two views to the proper zoom levels that were expected to happen immediately after the selection of "Reset field of view."

See video below:

https://github.com/user-attachments/assets/0b8f80b3-9bb0-47c6-a133-ee97e726478b

## Environment
- Slicer version: Slicer-5.7.0-2024-07-29
- Operating system: Windows Pro 11

**Comment by lassoan** [comment]
Thank you for taking the time to describe this. 

Linking means an action that the user performs on one slice view is automatically performed on all other slice views in the same view group. Reset FOV action fits the view to the image in all views. Changing zoom factor sets the same zoom factor in all views. These are two distinct actions. The current behavior is as intended, not a bug.

We could think about changing the meaning of linking. For example, a new feature could be to add an option for geometric alignment (not just set the same zoom factor, but the pan position, too). This would be a new feature that indeed could be useful. You could submit a feature request for this in this issue tracker. However, before doing that, it would be nice to discuss about your exact needs, hear from others about their similar needs, and brainstorm ideas about addressing them all.
