### ISSUE TITLE
Tiff errors slowing down the Slicer performance. 

### ISSUE THREAD

**Issue by muratmaga** [Slicer/Slicer#7994]
## Summary
Please see for detail discussion and solution:

https://github.com/SlicerMorph/SlicerMorph/issues/320#issuecomment-2411678264

This issue is added to make sure that ITK changes to fix the slowness issue are incorporated before the 5.8 stable is released.

**Comment by muratmaga** [comment]
@jcfr @pieper @lassoan

**Comment by jcfr** [comment]
Can the change https://github.com/lassoan/ITK/commit/f85248f5378de26b0a57a3bd2cc843099e0a00cd be contributed to upstream ITK through a pull request ?

**Comment by lassoan** [comment]
I wanted to test it more after a clean build before submitting the ITK pull request. @jcfr if you have time to create an ITK pull request in the meantime so that ITK developers can start reviewing it that would speed up the process. (if not then I'll get to this in the next few days) Thanks!

**Comment by jcfr** [comment]
For reference:
* https://github.com/InsightSoftwareConsortium/ITK/pull/4909
