### ISSUE TITLE
There was an issue when running ./Slicer --launch /home/xxx/Qt5.14.2/Tools/QtCreator/bin/qtcreator on Ubuntu 18.04.

### ISSUE THREAD

**Issue by tthh7** [Slicer/Slicer#8043]
## Summary
I successfully built Slicer version 5.7.0-2024-11-08 on Ubuntu 18.04 following the instructions in the [Slicer documentation](https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/linux.html). However, when I try to debug using Qt, I encounter an issue. I attempted to launch Qt Creator with the following command:

**./Slicer --launch /home/xxx/Qt5.14.2/Tools/QtCreator/bin/qtcreator**

but received this error:

**Cannot mix incompatible Qt library (version 0x50e02) with this library (version 0x50e01)
error: [/home/xxx/Qt5.14.2/Tools/QtCreator/bin/qtcreator] exit abnormally - Report the problem.**

During the build, I used this cmake command:

**cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DQt5_DIR=/home/xxx/Qt5.14.2/5.14.2/gcc_64/lib/cmake/Qt5 ../Slicer**

Could someone advise on how to resolve this issue? Thank you!

## Environment
- Slicer version: Slicer-5..7.0-2024-11-08
- Operating system: ubuntu 18.04
--IDE: QT5.14.2

**Comment by lassoan** [comment]
This question is discussed here: https://discourse.slicer.org/t/there-was-an-issue-when-running-slicer-launch-home-xxx-qt5-14-2-tools-qtcreator-bin-qtcreator-on-ubuntu-18-04/40173/3
