### ISSUE TITLE
Segment visibility toggle in Segment Editor doesn't work in latest preview (11-14) in linux

### ISSUE THREAD

**Issue by muratmaga** [Slicer/Slicer#8047]
## Summary
The eye icon to toggle visibility in Segment Editor is non-functional for the latest Linux preview (haven't tested it others). Visibility can still be set from the subject hierarchy. But clicking it from Segment Editor or Segmentations modules have no effect. Neither the visibility of the segment changes, nor the icon changes. 

There are no errors in the applicaiton log. Toggling the "use standard terminology for name and color selection" has not effect either.

@cpinter @lassoan

**Comment by lassoan** [comment]
I cannot reproduce it. Is it a clean install, without any extensions?

**Comment by muratmaga** [comment]
Yes, vanilla Slicer on the morphocloud. I will send you the credentials for you to explore.

**Comment by lassoan** [comment]
I see thank you, I can also reproduce it now after pulling latest changes from Slicer main. Probably it is due to the refactoring of the edit trigger handling. I'll investigate.
