### ISSUE TITLE
Interaction events are no longer triggered by plane and ROI markups

### ISSUE THREAD

**Issue by RomanFenioux** [Slicer/Slicer#8074]
## Summary

Originally mentioned in https://discourse.slicer.org/t/possible-regression-in-events-triggered-by-plane-and-roi-markups/40474

I am encountering an inconsistent behavior / regression regarding the handling of events for plane and ROI markups in the latest preview version of Slicer, compared to the last stable release (slicer 5.6.2).

It seems that in the cases detailed below, some events (`StartInteractionEvent`, `EndInteractionEvent`, and in one case also the `PointModifiedEvent`) are not triggered when interacting with the markups handles (more details below)

Here is the detailed behaviour :

## Steps to reproduce

1. Create the markups (plane or ROI) using the markups module
2. use the following snippet to get the node and connect the observers
```
node = getNode("P")
node.AddObserver(slicer.vtkMRMLMarkupsROINode.PointStartInteractionEvent, lambda *_: print("start"))
node.AddObserver(slicer.vtkMRMLMarkupsROINode.PointModifiedEvent, lambda *_: print("modified"))
node.AddObserver(slicer.vtkMRMLMarkupsROINode.PointEndInteractionEvent, lambda *_: print("end"))
```
3. observe the console logs while click and dragging either the center point, or the corner handles

| Use case                        | Slicer 5.6.2                                   | Slicer 5.7.2 2024-12-01                         |
|---------------------------------|-----------------------------------------------|------------------------------------------------|
| Dragging center of ROI          | start, modified, end | modified                                       |
| Dragging corner of ROI          | start, modified, end | modified                                       |
| Dragging center of plane markup | start, modified, end | start, modified, end |
| Dragging corner of plane markup | start, end*             | No event                                       |

*The behavior for this case is an odd one even in 5.6.2 : the first time a corner of the plane is moved in 5.6.2, a single modifiedEvent is triggered between the start and end events. When I release and do it again, no modifiedEvent is triggered

## Environment
- Slicer version: Slicer-5.7.0-2024-12-01 (revision 33134)
- Operating system: Windows 11

**Comment by lassoan** [comment]
@Sunderlandkyl It would be nice if this could be included in Slicer-5.8, which is planned to be finalized by around Dec 24; but not a big issue if you cannot get it in.
